Repository rerun-io/rerun, pull requests merged in 2023-06, with the labels that each got.

#2293 Add command to screenshot the application
  Cargo.lock
  crates/re_data_ui/src/image.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/command.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/remote_viewer_app.rs
  crates/re_viewer/src/screenshotter.rs
  crates/rerun/src/run.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer

#2296 Update wgpu-hal to 0.16.1 to fix mobile Safari
  Cargo.lock
  crates/re_build_web_viewer/Cargo.toml
  crates/re_build_web_viewer/src/lib.rs
  crates/re_build_web_viewer/src/main.rs
  crates/re_error/src/lib.rs
  crates/re_renderer/Cargo.toml
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/build.rs
Labels: 🪳 bug, 🕸️ web, 🔺 re_renderer, dependencies

#2297 lint: standardize formatting of let-else-return statements
  crates/re_data_ui/src/image.rs
  crates/re_viewer/src/app.rs
  rerun_py/src/python_bridge.rs
  scripts/lint.py
Labels: 🧑‍💻 dev experience

#2299 CI: Retry `linkinator`
  .github/workflows/documentation.yaml
Labels: 🧑‍💻 dev experience

#2300 Expose type erased draw data that can be consumed directly
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/depth_offset.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/outlines.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/queuable_draw_data.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_space_view_spatial/src/ui_renderer_bridge.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
Labels: 🔺 re_renderer, 🚜 refactor

#2303 Break up app.rs into parts
  Cargo.lock
  crates/re_data_ui/src/image.rs
  crates/re_space_view_spatial/src/scene/parts/images.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/background_tasks.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/loading.rs
  crates/re_viewer/src/ui/mobile_warning_ui.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/ui/wait_screen_ui.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/caches.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/view_tensor/ui.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 📺 re_viewer, 🚜 refactor

#2316 Removed unnecessary workaround in blueprint python example
  examples/python/blueprint/main.py
Labels: examples

#2318 Fix deadlock when misusing the Caches
  crates/re_data_ui/src/image.rs
  crates/re_space_view_spatial/src/scene/parts/images.rs
  crates/re_space_view_spatial/src/scene/parts/meshes.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_viewer_context/src/caches.rs
  crates/re_viewer_context/src/tensor/tensor_stats_cache.rs
  crates/re_viewport/src/view_tensor/scene.rs
  crates/re_viewport/src/view_tensor/ui.rs
Labels: 🪳 bug, 📺 re_viewer

#2309 add manifest + readmes to examples
  docs/content/getting-started.md
  docs/content/getting-started/examples.md
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/logging-rust.md
  docs/content/getting-started/viewer-walkthrough.md
  docs/content/reference/sdk-operating-modes.md
  examples/README.md
  examples/manifest.yml
  examples/python/README.md
  examples/python/api_demo/README.md
  examples/python/arkitscenes/README.md
  examples/python/car/README.md
  examples/python/clock/README.md
  examples/python/colmap/README.md
  examples/python/deep_sdf/README.md
  examples/python/dicom/README.md
  examples/python/minimal/README.md
  examples/python/mp_pose/README.md
  examples/python/multiprocessing/README.md
  examples/python/multithreading/README.md
  examples/python/nyud/README.md
  examples/python/objectron/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/segment_anything/README.md
  examples/python/stable_diffusion/README.md
  examples/python/text_logging/README.md
  examples/python/tracking_hf_opencv/README.md
  examples/rust/api_demo/README.md
  examples/rust/clock/README.md
  examples/rust/minimal/README.md
  examples/rust/objectron/README.md
  examples/rust/raw_mesh/README.md
Labels: 📖 documentation, 🧑‍💻 dev experience

#2311 Finalize move of SpatialSpaceView to SpaceViewClass trait framework
  Cargo.lock
  crates/re_data_store/src/entity_properties.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/unreachable_transform_reason.rs
  crates/re_space_view_spatial/src/axis_lines.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/scene/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/scene/contexts/mod.rs
  crates/re_space_view_spatial/src/scene/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/scene/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/scene/contexts/transform_context.rs
  crates/re_space_view_spatial/src/scene/mod.rs
  crates/re_space_view_spatial/src/scene/parts/arrows3d.rs
  crates/re_space_view_spatial/src/scene/parts/boxes2d.rs
  crates/re_space_view_spatial/src/scene/parts/boxes3d.rs
  crates/re_space_view_spatial/src/scene/parts/cameras.rs
  crates/re_space_view_spatial/src/scene/parts/images.rs
  crates/re_space_view_spatial/src/scene/parts/lines2d.rs
  crates/re_space_view_spatial/src/scene/parts/lines3d.rs
  crates/re_space_view_spatial/src/scene/parts/meshes.rs
  crates/re_space_view_spatial/src/scene/parts/mod.rs
  crates/re_space_view_spatial/src/scene/parts/points2d.rs
  crates/re_space_view_spatial/src/scene/parts/points3d.rs
  crates/re_space_view_spatial/src/scene/picking.rs
  crates/re_space_view_spatial/src/scene/primitives.rs
  crates/re_space_view_spatial/src/space_view_class.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/ui_renderer_bridge.rs
  crates/re_space_view_text/src/space_view_class.rs
  crates/re_space_view_text_box/src/space_view_class.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/scene.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_impl.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_info.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
Labels: 📺 re_viewer, 🚜 refactor

#2319 Fix and clean up BUILD.md
  BUILD.md
Labels: 📖 documentation, 🧑‍💻 dev experience

#2323 Make examples setup a separate page
  examples/manifest.yml
Labels: 📖 documentation, 🧑‍💻 dev experience, examples

#2321 Typename cleanup in SpaceViewClass framework
  crates/re_space_view_spatial/src/space_view_class.rs
  crates/re_space_view_text/src/scene_part.rs
  crates/re_space_view_text/src/space_view_class.rs
  crates/re_space_view_text_box/src/scene_part.rs
  crates/re_space_view_text_box/src/space_view_class.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/scene.rs
  crates/re_viewer_context/src/space_view/scene_part.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_impl.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
Labels: 📺 re_viewer, 🚜 refactor

#2325 Remove unreferenced copy of editable_auto_value.rs
  crates/re_viewer/src/ui/editable_auto_value.rs
Labels: 📺 re_viewer, 🚜 refactor

#2326 Add `site_url` to `mkdocs.yml`
  rerun_py/mkdocs.yml
Labels: 📖 documentation

#2331 Centralized build tools in `re_build_tools`
  Cargo.lock
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_analytics/build.rs
  crates/re_build_info/Cargo.toml
  crates/re_build_info/src/lib.rs
  crates/re_build_tools/Cargo.toml
  crates/re_build_tools/README.md
  crates/re_build_tools/src/lib.rs
  crates/re_build_tools/src/rebuild_detector.rs
  crates/re_renderer/Cargo.toml
  crates/re_renderer/build.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/build.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/build.rs
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/build.rs
  crates/rerun-cli/Cargo.toml
  crates/rerun-cli/build.rs
  crates/rerun/Cargo.toml
  crates/rerun/build.rs
  examples/rust/objectron/Cargo.toml
  examples/rust/objectron/build.rs
  rerun_py/Cargo.toml
  rerun_py/build.rs
  scripts/publish_crates.sh
Labels: 🧑‍💻 dev experience, dependencies

#2324 Separate crate for time series space view
  Cargo.lock
  Cargo.toml
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/README.md
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/scene_part.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/view_time_series/mod.rs
  crates/re_viewport/src/view_time_series/ui.rs
  crates/re_viewport/src/viewport.rs
  scripts/publish_crates.sh
Labels: 📺 re_viewer, 🚜 refactor

#2339 Viewer's command queue is now a channel, allowing to queue commands without mutable access
  Cargo.lock
  crates/re_ui/Cargo.toml
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/command.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: 📺 re_viewer, 🚜 refactor

#2343 Things broken on main
  _typos.toml
  crates/re_components/src/coordinates.rs
  crates/re_renderer/shader/outlines/jumpflooding_init.wgsl
  crates/re_renderer/shader/outlines/jumpflooding_init_msaa.wgsl
  crates/re_tuid/Cargo.toml
  crates/re_tuid/README.md
  crates/re_viewer/src/app.rs
Labels: 🔨 testing, 🦟 regression

#2334 Separate crate for tensor space view
  Cargo.lock
  Cargo.toml
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_tensor/README.md
  crates/re_space_view_tensor/src/lib.rs
  crates/re_space_view_tensor/src/scene_part.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_dimension_mapper.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_tensor_ops/src/dimension_mapping.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/view_tensor/mod.rs
  crates/re_viewport/src/viewport.rs
Labels: 📺 re_viewer, 🚜 refactor

#2332 Add nitpicky lint
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  scripts/lint.py
Labels: 🧑‍💻 dev experience

#2302 Update RFC with outcomes from blueprint discussion
  design/blueprint_store.md
Labels: 📖 documentation

#2350 PyO3 0.19
  Cargo.lock
  rerun_py/Cargo.toml
Labels: 🐍 python API, dependencies

#2351 Fix ARKit example
  rerun_py/rerun_sdk/rerun/components/quaternion.py
Labels: 🪳 bug, examples

#2345 Optimization: avoid a memory allocation when padding RGB u8 to RGBA
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
Labels: 📺 re_viewer, 📉 performance

#2330 Move StoreHub out of the Viewer during Update
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/loading.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/blueprint.rs
  crates/re_viewer/src/ui/blueprint_load.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/store_context.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor, 🟦 blueprint

#2356 Remove long dead code python unit test
  rerun_py/tests/unit/api_tests.py
Labels: 🧑‍💻 dev experience, 😤 annoying

#2344 Expand CommandSender to support SystemCommand
  Cargo.lock
  crates/re_time_panel/src/time_control_ui.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/command.rs
  crates/re_ui/src/command_palette.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor

#2377 Enforce `from __future__ import annotations` in Python files
  rerun_py/docs/gen_common_index.py
  rerun_py/docs/gen_package_index.py
  rerun_py/pyproject.toml
  rerun_py/rerun/__init__.py
  rerun_py/rerun_demo/__init__.py
  rerun_py/tests/unit/test_color_conversion.py
  scripts/build_demo_app.py
  scripts/check_requirements.py
  scripts/fetch_crashes.py
  scripts/generate_changelog.py
  scripts/generate_pr_summary.py
  scripts/generate_prerelease_pip_index.py
  scripts/lint.py
  scripts/pr_link_docs.py
  scripts/run_all.py
  scripts/run_python_e2e_test.py
  scripts/upload_image.py
  scripts/verify_wheels.py
  scripts/version_util.py
Labels: 🐍 python API, 🧑‍💻 dev experience

#2378 Fix freestanding store helpers coming back from the dead
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/src/util.rs
  crates/re_viewer/src/ui/blueprint_load.rs
  crates/re_viewer/src/ui/blueprint_sync.rs
Labels: ⛃ re_datastore

#2342 Automatically determine image/tensor color mapping & need for srgb decoding
  crates/re_components/src/tensor.rs
  crates/re_data_ui/src/image.rs
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/tensor/tensor_stats.rs
Labels: enhancement, 🔺 re_renderer, 📺 re_viewer

#2376 Replace `image` crate jpeg decoder with zune-jpeg
  Cargo.lock
  crates/re_components/Cargo.toml
  crates/re_components/src/tensor.rs
  crates/re_log/src/lib.rs
  crates/re_log/src/setup.rs
  crates/re_sdk/Cargo.toml
  crates/re_viewer/Cargo.toml
  crates/re_viewport/Cargo.toml
  crates/rerun/Cargo.toml
  rerun_py/Cargo.toml
Labels: 📉 performance, dependencies

#2381 Added gcloud project name to `upload_image.py`
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience

#2396 Fix blueprint sync by bringing back `store_one_component`
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/src/util.rs
  crates/re_viewer/src/ui/blueprint_sync.rs
Labels: 📺 re_viewer, 🦟 regression

#2358 Split the Blueprint into AppBlueprint and ViewportBlueprint
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/ui/blueprint.rs
  crates/re_viewer/src/ui/blueprint_load.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/blueprint_sync.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🚜 refactor, 🟦 blueprint

#2404 Use forked `mkdocs-redirects`
  rerun_py/requirements-doc.txt
Labels: 📖 documentation

#2406 Update wasm-bindgen to 0.2.87
  Cargo.lock
  crates/re_build_web_viewer/Cargo.toml
  crates/re_log/Cargo.toml
  crates/re_memory/Cargo.toml
Labels: 🕸️ web, dependencies

#2407 Fix transforms not applied to connections from transform context
  crates/re_space_view_spatial/src/scene/mod.rs
Labels: 🪳 bug, 📺 re_viewer

#2409 Fix some browsers failing due to 8k texture requirement, pick always highest available now
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/shader/global_bindings.wgsl
  crates/re_renderer/shader/utils/depth_offset.wgsl
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/global_bindings.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_viewer/src/lib.rs
Labels: 🪳 bug, enhancement, 🕸️ web, 🔺 re_renderer

#2398 Remove weird-looking argument parsing in examples
  examples/python/api_demo/main.py
  examples/python/arkitscenes/main.py
  examples/python/car/main.py
  examples/python/clock/main.py
  examples/python/colmap/main.py
  examples/python/deep_sdf/main.py
  examples/python/dicom/main.py
  examples/python/dna/main.py
  examples/python/minimal/main.py
  examples/python/minimal_options/main.py
  examples/python/mp_pose/main.py
  examples/python/multiprocessing/main.py
  examples/python/multithreading/main.py
  examples/python/nyud/main.py
  examples/python/objectron/main.py
  examples/python/opencv_canny/main.py
  examples/python/plots/main.py
  examples/python/raw_mesh/main.py
  examples/python/segment_anything/main.py
  examples/python/stable_diffusion/main.py
  examples/python/text_logging/main.py
  examples/python/tracking_hf_opencv/main.py
  scripts/build_demo_app.py
  scripts/run_all.py
Labels: examples

#2401 Add support for classes to generated python common API index
  rerun_py/docs/css/mkdocstrings.css
  rerun_py/docs/gen_common_index.py
  rerun_py/docs/package/index.md
  rerun_py/docs/templates/python/material/class.html
  rerun_py/docs/templates/python/material/function.html
  rerun_py/mkdocs.yml
Labels: 📖 documentation

#2411 Added support for creating multi-resolution stacks with upload_image.py
  examples/python/clock/README.md
  scripts/requirements-dev.txt
  scripts/upload_image.py
Labels: 📖 documentation, 🧑‍💻 dev experience

#2419 Fix tracking_hf example: put scaled thing under its own root entity
  examples/python/tracking_hf_opencv/main.py
Labels: examples

#2424 Clean up our examples
  crates/re_components/src/tensor.rs
  crates/re_space_view_text/src/scene_part.rs
  examples/python/arkitscenes/main.py
  examples/python/mp_pose/main.py
  examples/python/plots/main.py
  examples/python/stable_diffusion/main.py
  examples/python/tracking_hf_opencv/main.py
  scripts/run_python_e2e_test.py
Labels: examples

#2425 Update xml-rs v0.8.13 -> v0.8.14
  Cargo.lock
Labels: dependencies

#2417 Show hover ui on points in custom space view example
  crates/re_viewer/src/lib.rs
  examples/rust/custom_space_view/src/color_coordinates_scene_parts.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: enhancement, examples

#2420 Update web examples
  examples/python/tracking_hf_opencv/main.py
  scripts/build_demo_app.py
  scripts/requirements-web-demo.txt
Labels: 🕸️ web, examples

#2430 Fix BGR/RGB mixup in colmap demo
  examples/python/colmap/main.py
Labels: 🪳 bug, examples

#2362 Codegen/IDL 1: add more build tools
  .github/workflows/labels.yml
  .gitignore
  Cargo.lock
  crates/re_build_tools/Cargo.toml
  crates/re_build_tools/src/hashing.rs
  crates/re_build_tools/src/lib.rs
  crates/re_build_tools/src/rebuild_detector.rs
Labels: codegen/idl

#2369 Codegen/IDL 3: introduce `re_types`
  Cargo.lock
  Cargo.toml
  crates/re_types/Cargo.toml
  crates/re_types/README.md
  crates/re_types/build.rs
  crates/re_types/definitions/arrow/attributes.fbs
  crates/re_types/definitions/fbs/attributes.fbs
  crates/re_types/definitions/fbs/scalars.fbs
  crates/re_types/definitions/python/attributes.fbs
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rust/attributes.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/lib.rs
Labels: codegen/idl

#2370 Codegen/IDL 4: definitions for a `Points2D` archetype
  crates/re_types/definitions/arrow/attributes.fbs
  crates/re_types/definitions/python/attributes.fbs
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/definitions/rerun/attributes.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/label.fbs
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/radius.fbs
  crates/re_types/definitions/rerun/datatypes.fbs
  crates/re_types/definitions/rerun/datatypes/vec2d.fbs
  crates/re_types/definitions/rust/attributes.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
Labels: codegen/idl

#2374 Codegen/IDL 5: auto-generated Python code for `Points2D`
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/pyproject.toml
  rerun_py/rerun2/__init__.py
  rerun_py/rerun_sdk/rerun2/__init__.py
  rerun_py/rerun_sdk/rerun2/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun2/components/color.py
  rerun_py/rerun_sdk/rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun2/components/label.py
  rerun_py/rerun_sdk/rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun2/datatypes/vec2d.py
Labels: 🐍 python API, codegen/idl

#2410 Codegen/IDL 7: handwritten Python tests and extensions for `Points2D`
  crates/re_types/build.rs
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  justfile
  rerun_py/rerun_sdk/rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun2/components/class_id_ext.py
  rerun_py/rerun_sdk/rerun2/components/color.py
  rerun_py/rerun_sdk/rerun2/components/color_ext.py
  rerun_py/rerun_sdk/rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun2/components/draw_order_ext.py
  rerun_py/rerun_sdk/rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun2/components/instance_key_ext.py
  rerun_py/rerun_sdk/rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun2/components/keypoint_id_ext.py
  rerun_py/rerun_sdk/rerun2/components/label.py
  rerun_py/rerun_sdk/rerun2/components/label_ext.py
  rerun_py/rerun_sdk/rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun2/components/point2d_ext.py
  rerun_py/rerun_sdk/rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun2/components/radius_ext.py
  rerun_py/rerun_sdk/rerun2/datatypes/vec2d.py
  rerun_py/rerun_sdk/rerun2/datatypes/vec2d_ext.py
  rerun_py/tests/unit/test_points2d.py
Labels: 🐍 python API, codegen/idl

#2432 Codegen/IDL 8: handwritten Rust tests and extensions for `Points2D`
  Cargo.lock
  crates/re_types/Cargo.toml
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/src/components/class_id_ext.rs
  crates/re_types/src/components/color_ext.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/draw_order_ext.rs
  crates/re_types/src/components/instance_key_ext.rs
  crates/re_types/src/components/keypoint_id_ext.rs
  crates/re_types/src/components/label_ext.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/point2d_ext.rs
  crates/re_types/src/components/radius_ext.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/datatypes/vec2d_ext.rs
  crates/re_types/tests/points2d.rs
Labels: 🦀 rust SDK, codegen/idl

#2441 Fix typo in `run_all.py`
  scripts/run_all.py
Labels: 🧑‍💻 dev experience

#2449 Minor fixes/improvements of `upload_image.py`
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience

#2451 Add Quarternion xyzw argument to ros_node example
  examples/python/ros_node/main.py
Labels: examples

#2421 When loading on web, match style and show a progress indicator while wasm is loading
  crates/re_ui/src/design_tokens.rs
  crates/re_viewer/src/ui/wait_screen_ui.rs
  scripts/demo_assets/static/index.css
  scripts/demo_assets/static/index.js
  scripts/demo_assets/templates/example.html
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 🕸️ web

#2412 Stream `.rrd` files
  .github/workflows/reusable_build_web_demo.yml
  .vscode/launch.json
  Cargo.lock
  crates/re_log_encoding/Cargo.toml
  crates/re_log_encoding/src/decoder.rs
  crates/re_log_encoding/src/decoder/stream.rs
  crates/re_log_encoding/src/encoder.rs
  crates/re_log_encoding/src/file_sink.rs
  crates/re_log_encoding/src/lib.rs
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_sdk/src/log_sink.rs
  crates/rerun/src/run.rs
  scripts/build_demo_app.py
Labels: enhancement, 📉 performance

#2454 Added example screenshot instructions in `just upload --help`
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience

#2392 Add example template
  Cargo.lock
  examples/README.md
  examples/python/requirements.txt
  examples/python/template/README.md
  examples/python/template/main.py
  examples/python/template/requirements.txt
  examples/rust/template/Cargo.toml
  examples/rust/template/README.md
  examples/rust/template/src/main.rs
Labels: examples

#2456 Fix greyscale colormapping being not gamma-corrected
  crates/re_renderer/shader/colormap.wgsl
Labels: 🪳 bug, 🔺 re_renderer

#2455 Show hidden url search param in `app.rerun.io`
  web_viewer/index.html
Labels: 📖 documentation, examples

#2463 version bump to 0.8-alpha.0 & 0.7 changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  examples/rust/api_demo/Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
Labels: 🧑‍💻 dev experience

#2460 Update Logging Data in Rust/Python doc page
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/logging-rust.md
Labels: 📖 documentation

#2457 Update all documentation screenshots to optimised multi-resolution stacks
  docs/content/concepts/annotation-context.md
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/python.md
  docs/content/getting-started/rust.md
  docs/content/getting-started/viewer-walkthrough.md
  docs/content/howto/extend-ui.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/reference/viewer/blueprint.md
  docs/content/reference/viewer/overview.md
  docs/content/reference/viewer/selection.md
  docs/content/reference/viewer/timeline.md
  docs/content/reference/viewer/viewport.md
  docs/cspell.json
Labels: 📖 documentation

#2462 Added support for puling image from an URL to `upload_image.py`
  scripts/requirements-dev.txt
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience

#2464 Update transform doc link for 0.7.0
  docs/content/reference/primitives.md
Labels: 📖 documentation

#2438 Split the API examples into sub-pages
  Cargo.lock
  Cargo.toml
  docs/code-examples/Cargo.toml
  docs/code-examples/point2d_random.py
  docs/code-examples/point2d_simple.py
  docs/code-examples/point2d_simple.rs
  docs/code-examples/point3d_random.py
  docs/code-examples/point3d_simple.py
  docs/content/concepts/entity-component.md
  docs/content/getting-started/viewer-walkthrough.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/reference/data_types.md
  docs/content/reference/data_types/annotation_context.md
  docs/content/reference/data_types/arrow3d.md
  docs/content/reference/data_types/box3d.md
  docs/content/reference/data_types/depth_image.md
  docs/content/reference/data_types/image.md
  docs/content/reference/data_types/linestrip2d.md
  docs/content/reference/data_types/linestrip3d.md
  docs/content/reference/data_types/mesh.md
  docs/content/reference/data_types/pinhole.md
  docs/content/reference/data_types/point2d.md
  docs/content/reference/data_types/point3d.md
  docs/content/reference/data_types/rect2d.md
  docs/content/reference/data_types/scalar.md
  docs/content/reference/data_types/segmentation_image.md
  docs/content/reference/data_types/tensor.md
  docs/content/reference/data_types/text_entry.md
  docs/content/reference/data_types/transform3d.md
  docs/content/reference/primitives.md
  docs/content/reference/python.md
  docs/content/reference/rust.md
  docs/content/reference/sdk-logging-controls.md
  docs/content/reference/sdk-micro-batching.md
  docs/content/reference/sdk-operating-modes.md
  docs/cspell.json
  rerun_py/pyproject.toml
Labels: 📖 documentation

#2470 `setup_dev.sh` now installs pngcrush
  scripts/setup_dev.sh
Labels: 🧑‍💻 dev experience

#2475 Fix example CSS
  scripts/demo_assets/static/index.css
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 📖 documentation, examples

#2473 Fill out archetype docs: Transform3d, Pinhole, Scalar, TextEntry
  docs/code-examples/pinhole_simple.py
  docs/code-examples/scalar_simple.py
  docs/code-examples/text_entry_simple.py
  docs/code-examples/transform3d_simple.py
  docs/content/reference/data_types/pinhole.md
  docs/content/reference/data_types/scalar.md
  docs/content/reference/data_types/text_entry.md
  docs/content/reference/data_types/transform3d.md
Labels: 📖 documentation

#2476 Added docs/code-examples to the directories checked by py-lint and py-format
  docs/code-examples/annotation-context/example.py
  docs/code-examples/default-off-session/example.py
  justfile
  rerun_py/pyproject.toml
Labels: 🧑‍💻 dev experience

#2477 Fixed a couple of image-related documentation errors
  rerun_py/rerun_sdk/rerun/log/image.py
Labels: 📖 documentation

#2474 Fill out more archetype docs: image, tensor, depth image, segmentation image
  docs/code-examples/annotation_context_connections.py
  docs/code-examples/annotation_context_rects.py
  docs/code-examples/annotation_context_segmentation.py
  docs/code-examples/depth_image_simple.py
  docs/code-examples/image_advanced.py
  docs/code-examples/image_simple.py
  docs/code-examples/segmentation_image_simple.py
  docs/code-examples/tensor_one_dim.py
  docs/code-examples/tensor_simple.py
  docs/content/reference/data_types/annotation_context.md
  docs/content/reference/data_types/depth_image.md
  docs/content/reference/data_types/image.md
  docs/content/reference/data_types/linestrip2d.md
  docs/content/reference/data_types/linestrip3d.md
  docs/content/reference/data_types/point2d.md
  docs/content/reference/data_types/rect2d.md
  docs/content/reference/data_types/segmentation_image.md
  docs/content/reference/data_types/tensor.md
  docs/cspell.json
Labels: 📖 documentation

#2492 Minor doc fix in image archetype's docs related to signed ints
  docs/content/reference/data_types/image.md
Labels: 📖 documentation

#2493 Documentation improvements highlighting the loggable data types section
  docs/code-examples/depth_image_3d.py
  docs/code-examples/depth_image_simple.py
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/logging-rust.md
  docs/content/getting-started/python.md
  docs/content/getting-started/rust.md
  docs/content/index.md
  docs/content/reference/data_types/depth_image.md
Labels: 📖 documentation

#2498 Change capitalization and order of examples
  examples/manifest.yml
Labels: 📖 documentation, examples

#2502 Various fixes to the example READMEs
  examples/manifest.yml
  examples/python/arkit_scenes/README.md
  examples/python/face_tracking/README.md
  examples/python/raw_mesh/README.md
Labels: 📖 documentation

#2508 Version `rand` & friends at workspace level
  Cargo.toml
  crates/re_arrow_store/Cargo.toml
  crates/re_components/Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_sdk/Cargo.toml
  crates/re_sdk_comms/Cargo.toml
  rerun_py/Cargo.toml
Labels: dependencies

#2491 Tweak the depth bias multiplier for WebGL
  crates/re_renderer/shader/utils/depth_offset.wgsl
Labels: 🪳 bug, 🔺 re_renderer

#2504 Double-click to select entity
  crates/re_data_ui/src/item_ui.rs
  crates/re_log_types/src/instance_key.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_space_view_spatial/src/scene/parts/arrows3d.rs
  crates/re_space_view_spatial/src/scene/parts/boxes2d.rs
  crates/re_space_view_spatial/src/scene/parts/boxes3d.rs
  crates/re_space_view_spatial/src/scene/parts/cameras.rs
  crates/re_space_view_spatial/src/scene/parts/lines2d.rs
  crates/re_space_view_spatial/src/scene/parts/lines3d.rs
  crates/re_space_view_spatial/src/scene/parts/meshes.rs
  crates/re_space_view_spatial/src/scene/parts/mod.rs
  crates/re_space_view_spatial/src/scene/parts/points2d.rs
  crates/re_space_view_spatial/src/scene/parts/points3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_viewer_context/src/space_view/highlights.rs
  crates/re_viewport/src/space_view_highlights.rs
Labels: enhancement, 📺 re_viewer

#2515 Fix missing feature flags for benchmarks
  crates/re_components/Cargo.toml
  crates/re_sdk_comms/Cargo.toml
Labels: 🧑‍💻 dev experience, 🦟 regression

#2506 Simpler, sturdier stateful time tracking in both SDKs
  crates/re_sdk/src/msg_sender.rs
  crates/re_sdk/src/recording_stream.rs
  docs/content/getting-started/logging-rust.md
  examples/rust/api_demo/src/main.rs
  examples/rust/clock/src/main.rs
  examples/rust/dna/src/main.rs
  examples/rust/minimal_options/src/main.rs
  examples/rust/raw_mesh/src/main.rs
  rerun_py/src/python_bridge.rs
Labels: 🐍 python API, 🦀 rust SDK

#2501 Create Rust version of the "Loggable Data Types" doc section
  Cargo.lock
  docs/code-examples/Cargo.toml
  docs/code-examples/annotation_context_connections.rs
  docs/code-examples/annotation_context_rects.rs
  docs/code-examples/annotation_context_segmentation.rs
  docs/code-examples/arrow3d_simple.rs
  docs/code-examples/box3d_simple.rs
  docs/code-examples/depth_image_3d.rs
  docs/code-examples/depth_image_simple.rs
  docs/code-examples/image_simple.rs
  docs/code-examples/line_segments2d_simple.rs
  docs/code-examples/line_segments3d_simple.rs
  docs/code-examples/line_strip2d_simple.rs
  docs/code-examples/line_strip3d_simple.rs
  docs/code-examples/mesh_simple.rs
  docs/code-examples/pinhole_simple.rs
  docs/code-examples/point2d_random.rs
  docs/code-examples/point3d_random.rs
  docs/code-examples/point3d_simple.rs
  docs/code-examples/rect2d_simple.rs
  docs/code-examples/scalar_simple.rs
  docs/code-examples/segmentation_image_simple.rs
  docs/code-examples/tensor_one_dim.rs
  docs/code-examples/tensor_simple.rs
  docs/code-examples/text_entry_simple.rs
  docs/code-examples/transform3d_simple.rs
Labels: 📖 documentation

#2519 `run_all.py` script fixes
  scripts/run_all.py
Labels: 🪳 bug, 🧑‍💻 dev experience

#2528 Move `rerun2` package into `rerun`
  .mypy.ini
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/lib.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/lib.rs
  rerun_py/pyproject.toml
  rerun_py/rerun2/__init__.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/class_id_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/color.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/color_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/keypoint_id_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/label.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/label_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec2d_ext.py
  rerun_py/rerun_sdk/rerun2/components/__init__.py
  rerun_py/tests/unit/test_points2d.py
Labels: 🐍 python API, codegen/idl

#2465 Show layout in blueprint tree view
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/src/component.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/blueprint_components/mod.rs
  crates/re_viewport/src/blueprint_components/viewport.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/rust/api_demo/Cargo.toml
  examples/rust/dna/Cargo.toml
Labels: ui, 📺 re_viewer, dependencies

#2484 Codegen'd Rust/Arrow (de)ser 1: upgrading to actual `TokenStream`s
  Cargo.lock
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
Labels: 🦀 rust SDK, codegen/idl

#2485 Codegen'd Rust/Arrow (de)ser 2: matching legacy definitions
  Cargo.lock
  crates/re_types/definitions/rerun/attributes.fbs
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/label.fbs
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/radius.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point2d_ext.rs
  crates/re_types/src/components/radius.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  rerun_py/rerun_sdk/rerun/_rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/color.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/label.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec2d.py
  rerun_py/tests/unit/test_points2d.py
Labels: 🦀 rust SDK, codegen/idl

#2540 Add Rerun.io link/text in top bar
  crates/re_ui/data/icons/rerun_io.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: ui, 📺 re_viewer

#2555 Update egui_tiles with fix for drag-and-drop-panic
  Cargo.lock
  Cargo.toml
Labels: 🪳 bug, dependencies

#2543 Link to demo in PR + check checkboxes
  .github/pull_request_template.md
  .github/workflows/README.md
  .github/workflows/checkboxes.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_update_pr_body.yml
  .github/workflows/reusable_upload_web_demo.yml
  scripts/check_pr_checkboxes.py
  scripts/requirements-dev.txt
  scripts/update_pr_body.py
Labels: 🧑‍💻 dev experience

#2532 Add script to find external issues we haven't commented on
  scripts/highlight_issues.py
Labels: 🧑‍💻 dev experience

#2559 Convert objectron proto.py back to using typing.List
  examples/python/objectron/proto/objectron/proto.py
Labels: 🪳 bug

#2560 Fix spurious build failure due to missing `.git/refs/heads/BRANCH` file
  crates/re_build_tools/src/lib.rs
Labels: 🪳 bug, 🧑‍💻 dev experience

#2544 Remove defunct entity filter from Text Space View
  crates/re_space_view_text/src/space_view_class.rs
Labels: 🪳 bug, 📺 re_viewer

#2562 Exclude from `objectron/proto/objectron/proto.py` from `just py-format`
  justfile
Labels: 🪳 bug, 🧑‍💻 dev experience

#2561 Move CI-related scripts to its own folder
  .github/workflows/checkboxes.yml
  .github/workflows/manual_release.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_update_pr_body.yml
  crates/re_build_info/src/crate_version.rs
  scripts/ci/build_demo_app.py
  scripts/ci/cargo_deny.sh
  scripts/ci/check_large_files.sh
  scripts/ci/check_large_files_allow_list.txt
  scripts/ci/check_pr_checkboxes.py
  scripts/ci/check_requirements.py
  scripts/ci/demo_assets/static/caret-down.svg
  scripts/ci/demo_assets/static/caret-right.svg
  scripts/ci/demo_assets/static/favicon.svg
  scripts/ci/demo_assets/static/github-mark-white.svg
  scripts/ci/demo_assets/static/index.css
  scripts/ci/demo_assets/static/index.html
  scripts/ci/demo_assets/static/index.js
  scripts/ci/demo_assets/static/manifest.json
  scripts/ci/demo_assets/static/sw.js
  scripts/ci/demo_assets/templates/example.html
  scripts/ci/generate_pr_summary.py
  scripts/ci/generate_prerelease_pip_index.py
  scripts/ci/templates/pip_index.html
  scripts/ci/templates/pr_results_summary.html
  scripts/ci/update_pr_body.py
  scripts/ci/verify_wheels.py
  scripts/ci/version_util.py
  scripts/requirements-dev.txt
Labels: 🧑‍💻 dev experience

#2558 New auto-layout of space views
  Cargo.lock
  Cargo.toml
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/space_view_class.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text/src/space_view_class.rs
  crates/re_space_view_text_box/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  scripts/run_all.py
Labels: enhancement, ui, 📺 re_viewer

#2564 add 'Dump datastore' command to palette
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
Labels: ui, 🧑‍💻 dev experience

#2565 Deploy docs in release workflows
  .github/workflows/manual_build_release.yml
  .github/workflows/manual_release.yml
Labels: 📖 documentation

#2567 Fix out-of-sync codegen hash
  crates/re_types/source_hash.txt
Labels: 🪳 bug

#2568 Fix pinhole visualization not working with camera extrinsics & intrinsics on the same path
  crates/re_space_view_spatial/src/scene/parts/cameras.rs
  examples/python/objectron/main.py
  examples/rust/objectron/src/main.rs
Labels: 🪳 bug, 📺 re_viewer

#2563 Render PR description as template
  .github/pull_request_template.md
  .github/workflows/reusable_update_pr_body.yml
  scripts/ci/generate_pr_summary.py
  scripts/ci/update_pr_body.py
Labels: 🧑‍💻 dev experience

#2569 Fix not taking np.array for single colors
  rerun_py/rerun_sdk/rerun/components/color.py
  rerun_py/rerun_sdk/rerun/log/arrow.py
  rerun_py/rerun_sdk/rerun/log/bounding_box.py
  rerun_py/rerun_sdk/rerun/log/lines.py
  rerun_py/rerun_sdk/rerun/log/points.py
  rerun_py/rerun_sdk/rerun/log/rects.py
  rerun_py/rerun_sdk/rerun/log/scalar.py
  rerun_py/rerun_sdk/rerun/log/text.py
  rerun_py/rerun_sdk/rerun/log/text_internal.py
Labels: 🪳 bug, 🐍 python API

#2536 Add basic testing automation against all version of Python using nox
  .gitignore
  justfile
  noxfile.py
  scripts/run_all.py
  scripts/setup_dev.sh
Labels: 🧑‍💻 dev experience

#2487 Codegen'd Rust/Arrow (de)ser 3: misc fixes & improvements
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/lib.rs
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/color.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/label.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec2d.py
  scripts/lint.py
Labels: codegen/idl

#2545 Codegen'd Rust/Arrow (de)ser 4: out-of-sync definitions CI detection
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/build.rs
Labels: 🧑‍💻 dev experience, codegen/idl

#2546 Codegen'd Rust/Arrow (de)ser 5: doc, definitions and regression tests for combinatorial affixes
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/testing/archetypes/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  rerun_py/rerun_sdk/rerun/_rerun2/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy_ext.py
Labels: codegen/idl

#2549 Codegen'd Rust/Arrow (de)ser 6: serialization
  Cargo.lock
  _typos.toml
  crates/re_types/Cargo.toml
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/lib.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/points2d.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, codegen/idl

#2554 Codegen'd Rust/Arrow (de)ser 7: deserialization
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/lib.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/points2d.rs
  crates/re_types_builder/src/codegen/rust.rs
  scripts/ci/check_large_files_allow_list.txt
Labels: 🦀 rust SDK, codegen/idl

#2570 Codegen'd Rust/Arrow (de)ser 8: carry extension metadata across transparency layers
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/lib.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/points2d.rs
  crates/re_types/tests/util.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, codegen/idl
