Repository rerun-io/rerun, pull requests merged in 2023-07, with the labels that each got.

#2580 Fix `scripts/lint.py` to ignore `.nox`
  scripts/lint.py
Labels: 🪳 bug, 🧑‍💻 dev experience

#2512 Add a simple example to display Open Photogrammetry Format datasets
  .gitignore
  BUILD.md
  crates/re_space_view_spatial/src/ui.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/python/open_photogrammetry_format/README.md
  examples/python/open_photogrammetry_format/main.py
  examples/python/open_photogrammetry_format/requirements.txt
  examples/python/requirements.txt
  justfile
  rerun_py/README.md
  scripts/run_all.py
Labels: examples

#2571 Codegen'd Rust/Arrow (de)ser 9: Rust backport!
  Cargo.lock
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/msg_sender.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/points2d.rs
  crates/re_types_builder/src/codegen/rust.rs
  examples/rust/api_demo/src/main.rs
Labels: 🦀 rust SDK, codegen/idl

#2584 Fix CI: Don't pin Pillow version
  .github/workflows/reusable_build_and_test_wheels.yml
  rerun_py/pyproject.toml
Labels: 🐍 python API, 🧑‍💻 dev experience, dependencies

#2587 Pin `half` to `2.2.1`
  Cargo.toml
Labels: 🪳 bug, dependencies

#2581 Python backport: add `log_any()`
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  examples/python/api_demo/main.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/color.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/label.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/label_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/log_any.py
  rerun_py/tests/unit/test_log.py
Labels: 🐍 python API, codegen/idl

#2583 Fix: always auto-layout spaceviews until the user interveens
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, ui, 📺 re_viewer

#2586 Docs: link to `rr.save` and suggest `rerun` instead of `python -m rerun`
  docs/content/getting-started/logging-python.md
  docs/content/reference/sdk-operating-modes.md
  examples/python/README.md
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📖 documentation

#2592 Disable codegen on windows
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/build.rs
Labels: 🪟 windows, codegen/idl

#2596 Run clippy on public API too
  Cranky.toml
  clippy.toml
  crates/re_arrow_store/src/store_arrow.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_components/src/color.rs
  crates/re_components/src/coordinates.rs
  crates/re_components/src/rect.rs
  crates/re_components/src/tensor.rs
  crates/re_components/src/transform3d.rs
  crates/re_log_encoding/src/lib.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/time.rs
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/file_server.rs
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_sdk/src/msg_sender.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view_spatial/src/scene/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_types/src/components/color_ext.rs
  crates/re_ui/src/command.rs
  crates/re_ui/src/lib.rs
  crates/re_web_viewer_server/src/lib.rs
  rerun_py/src/python_bridge.rs
  scripts/clippy_wasm/clippy.toml
Labels: 🚜 refactor

#2588 Fix freeze/crash when logging large times
  .vscode/launch.json
  crates/re_log_types/src/time_real.rs
  crates/re_time_panel/src/paint_ticks.rs
Labels: 🪳 bug, 💣 crash

#2594 Seed of C and C++ SDKs
  .clang-format
  .github/workflows/labels.yml
  .vscode/extensions.json
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/store_db.rs
  crates/re_log_encoding/src/decoder.rs
  crates/re_log_encoding/src/lib.rs
  crates/re_log_types/src/arrow_msg.rs
  crates/re_log_types/src/lib.rs
  crates/re_memory/Cargo.toml
  crates/re_query/src/lib.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/buffered_client.rs
  crates/re_sdk_comms/src/tcp_client.rs
  crates/re_string_interner/Cargo.toml
  crates/re_tuid/Cargo.toml
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  crates/rerun_c/Cargo.toml
  crates/rerun_c/example_c/.gitignore
  crates/rerun_c/example_c/Makefile
  crates/rerun_c/example_c/README.md
  crates/rerun_c/example_c/main.c
  crates/rerun_c/example_cpp/.gitignore
  crates/rerun_c/example_cpp/CMakeLists.txt
  crates/rerun_c/example_cpp/README.md
  crates/rerun_c/example_cpp/build_and_run.sh
  crates/rerun_c/example_cpp/main.cpp
  crates/rerun_c/run_examples.sh
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  crates/rerun_c/src/rerun.hpp
  justfile
  rerun_py/Cargo.toml
  scripts/lint.py
Labels: C/C++ SDK

#2598 Update egui_tiles to fix crash
  Cargo.lock
  Cargo.toml
  Cranky.toml
Labels: 🪳 bug, dependencies, 💣 crash

#2595 Refactor: Swap the naming of Viewport and ViewportBlueprint
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor

#2600 Bump all `py-lint`-related package versions
  rerun_py/requirements-lint.txt
Labels: 🧑‍💻 dev experience

#2578 Basic persistence for blueprints
  .github/workflows/labels.yml
  Cargo.lock
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_data_store/src/editable_auto_value.rs
  crates/re_data_store/src/entity_properties.rs
  crates/re_data_store/src/store_db.rs
  crates/re_space_view/src/data_blueprint.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/loading.rs
  crates/re_viewer/src/saving.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewport/src/blueprint_components/space_view.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/python/blueprint/main.py
Labels: 🟦 blueprint

#2602 Support any `dtype` for depth images
  crates/re_analytics/src/sink_native.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_renderer/shader/depth_cloud.wgsl
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_space_view_spatial/src/scene/parts/images.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/tensor/tensor_decode_cache.rs
  examples/python/live_depth_sensor/requirements.txt
  examples/python/rgbd/main.py
  rerun_py/rerun_sdk/rerun/log/image.py
Labels: enhancement, 🔺 re_renderer, 📺 re_viewer

#2604 Crates publishing script
  .github/workflows/checkboxes.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_update_pr_body.yml
  scripts/ci/crates.py
  scripts/ci/requirements-web-demo.txt
  scripts/ci/requirements.txt
  scripts/requirements-web-demo.txt
Labels: 🧑‍💻 dev experience

#2608 Automatically assume arrow transparency for components
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/label.fbs
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/radius.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/fuzzy.rs
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/objects.rs
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
Labels: 🏹 arrow, codegen/idl

#2612 Fix wrong path being `rerun_if_changed()` in `compute_dir_hash`
  crates/re_build_tools/src/hashing.rs
  crates/re_types/source_hash.txt
Labels: codegen/idl

#2613 Automatically derive `Debug` and `Clone` in Rust backend
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/label.fbs
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/radius.fbs
  crates/re_types/definitions/rerun/datatypes/point2d.fbs
  crates/re_types/definitions/rerun/datatypes/vec2d.fbs
  crates/re_types/definitions/rerun/testing/archetypes/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/definitions/rust/attributes.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, 🧑‍💻 dev experience, codegen/idl

#2615 Fix rust docs deploy
  .github/workflows/reusable_deploy_docs.yml
Labels: 🧑‍💻 dev experience

#2610 Add a basic pyright config
  pyrightconfig.json
Labels: 🧑‍💻 dev experience

#2609 Update release script + release `0.8.0-alpha.2`
  Cargo.lock
  Cargo.toml
  crates/re_log_encoding/src/lib.rs
  crates/re_log_types/Cargo.toml
  crates/re_space_view/Cargo.toml
  crates/re_space_view_spatial/Cargo.toml
  crates/rerun_c/README.md
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
  scripts/ci/crates.py
  scripts/ci/requirements.txt
  tests/rust/test_api/Cargo.toml
Labels: ⛴ release

#2622 CI: don't run e2e roundtrip tests on windows
  .github/workflows/reusable_build_and_test_wheels.yml
Labels: 🪳 bug, 🪟 windows

#2624 Move C++ SDK to own folder
  .clang-format
  .github/workflows/reusable_pr_summary.yml
  _typos.toml
  ci_docker/Dockerfile
  crates/rerun_c/example/.gitignore
  crates/rerun_c/example/Makefile
  crates/rerun_c/example/README.md
  crates/rerun_c/example/main.c
  crates/rerun_c/example_cpp/.gitignore
  crates/rerun_c/example_cpp/CMakeLists.txt
  crates/rerun_c/example_cpp/build_and_run.sh
  crates/rerun_c/example_cpp/main.cpp
  crates/rerun_c/run_examples.sh
  rerun_cpp/.gitignore
  rerun_cpp/CMakeLists.txt
  rerun_cpp/README.md
  rerun_cpp/build_and_run.sh
  rerun_cpp/example/CMakeLists.txt
  rerun_cpp/example/README.md
  rerun_cpp/example/main.cpp
  rerun_cpp/src/CMakeLists.txt
  rerun_cpp/src/recording_stream.cpp
  rerun_cpp/src/recording_stream.hpp
  rerun_cpp/src/rerun.cpp
  rerun_cpp/src/rerun.hpp
  scripts/ci/check_pr_checkboxes.py
  scripts/ci/generate_pr_summary.py
  scripts/ci/generate_prerelease_pip_index.py
  scripts/ci/update_pr_body.py
  scripts/lint.py
  scripts/setup.sh
  scripts/upload_image.py
Labels: C/C++ SDK

#2618 Fix `order` attribute not being mandatory in some situations
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/radius.fbs
  crates/re_types/definitions/rerun/datatypes/vec2d.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/objects.rs
Labels: 🪳 bug, codegen/idl

#2626 Generating (de)serialization code for dense unions in Rust backend
  crates/re_types/definitions/rerun/testing/archetypes/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/objects.rs
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  scripts/ci/check_large_files_allow_list.txt
Labels: 🦀 rust SDK, codegen/idl

#2631 Change "Save Selection" command to Cmd+Alt+S
  crates/re_ui/src/command.rs
Labels: 🪳 bug, ui, 📺 re_viewer

#2614 Improve `log_pinhole` and support non-RDF pinholes
  crates/re_components/src/coordinates.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/shader/depth_cloud.wgsl
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/scene/contexts/mod.rs
  crates/re_space_view_spatial/src/scene/contexts/transform_context.rs
  crates/re_space_view_spatial/src/scene/mod.rs
  crates/re_space_view_spatial/src/scene/parts/cameras.rs
  crates/re_space_view_spatial/src/scene/parts/images.rs
  crates/re_space_view_spatial/src/space_camera_3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_types/source_hash.txt
  docs/code-examples/depth_image_3d.py
  docs/code-examples/pinhole_simple.py
  docs/content/concepts/spaces-and-transforms.md
  examples/python/arkit_scenes/main.py
  examples/python/blueprint/main.py
  examples/python/live_depth_sensor/main.py
  examples/python/objectron/main.py
  examples/python/open_photogrammetry_format/main.py
  examples/python/rgbd/main.py
  examples/python/ros_node/main.py
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/log/camera.py
  rerun_py/rerun_sdk/rerun/log/transform.py
  rerun_py/src/python_bridge.rs
  scripts/ci/crates.py
  tests/python/view_coordinates/main.py
Labels: 🪳 bug, enhancement, 📺 re_viewer, C/C++ SDK

#2632 Automagic flush when `take()`ing a `MemorySinkStorage`
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/points2d.rs
  docs/code-examples/annotation_context_connections.rs
  docs/code-examples/annotation_context_rects.rs
  docs/code-examples/annotation_context_segmentation.rs
  docs/code-examples/arrow3d_simple.rs
  docs/code-examples/box3d_simple.rs
  docs/code-examples/depth_image_3d.rs
  docs/code-examples/depth_image_simple.rs
  docs/code-examples/image_simple.rs
  docs/code-examples/line_segments2d_simple.rs
  docs/code-examples/line_segments3d_simple.rs
  docs/code-examples/line_strip2d_simple.rs
  docs/code-examples/line_strip3d_simple.rs
  docs/code-examples/mesh_simple.rs
  docs/code-examples/pinhole_simple.rs
  docs/code-examples/point2d_random.rs
  docs/code-examples/point2d_random_v2.rs
  docs/code-examples/point2d_simple.rs
  docs/code-examples/point2d_simple_v2.rs
  docs/code-examples/point3d_random.rs
  docs/code-examples/point3d_simple.rs
  docs/code-examples/rect2d_simple.rs
  docs/code-examples/scalar_simple.rs
  docs/code-examples/segmentation_image_simple.rs
  docs/code-examples/tensor_one_dim.rs
  docs/code-examples/tensor_simple.rs
  docs/code-examples/text_entry_simple.rs
  docs/code-examples/transform3d_simple.rs
  examples/rust/minimal/src/main.rs
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
Labels: 🦀 rust SDK, 🧑‍💻 dev experience

#2630 Logging SDK: Log warnings if user data is dropped
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
Labels: 📖 documentation, 🦀 rust SDK

#2637 Use `camino` crate for UTF8 paths in `re_types_builder`
  Cargo.lock
  Cargo.toml
  crates/re_types/source_hash.txt
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/src/codegen/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
Labels: 🚜 refactor

#2573 Fix clicking object with single instance (of every component) selecting instance instead of entity
  crates/re_data_ui/src/item_ui.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#2666 Add support for .gitignore to scripts/lint.py
  .github/workflows/reusable_checks.yml
  scripts/lint.py
  scripts/requirements-dev.txt
Labels: 🧑‍💻 dev experience

#2655 Rename _typos.toml to .typos.toml
  .typos.toml
Labels: 🧑‍💻 dev experience

#2673 Fix `FixedSizeList` deserialization edge-case + trivial optimizations
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types_builder/src/codegen/rust.rs
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
Labels: 🪳 bug, 🦀 rust SDK, 📉 performance, codegen/idl

#2668 Rust codegen: generate proper docstrings
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types_builder/src/codegen/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
Labels: codegen/idl

#2677 Make `Datatype` & `Component` both inherit from `Loggable`
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/lib.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, codegen/idl

#2676 Cleanup internal data-structures when process has been forked
  crates/re_sdk/src/global.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  examples/python/multiprocessing/main.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
Labels: 🪳 bug, 🐍 python API

#2683 `lint.py`: forbid trailing whitespace and missing ending newline
  .github/workflows/manual_adhoc_web.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .gitignore
  CHANGELOG.md
  crates/re_build_tools/src/hashing.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/source_hash.txt
  crates/re_ui/data/OFL.txt
  docs/content/getting-started/troubleshooting.md
  docs/content/howto/limit-ram.md
  docs/content/howto/notebook.md
  docs/content/reference/viewer.md
  docs/content/reference/viewer/selection.md
  docs/content/reference/viewer/viewport.md
  rerun_cpp/.gitignore
  scripts/lint.py
Labels: 🧑‍💻 dev experience

#2681 Run ruff before black when formatting python code
  crates/re_types/build.rs
  justfile
Labels: 🧑‍💻 dev experience

#2686 Format python with: black, ruff, black
  crates/re_types/build.rs
  justfile
Labels: 🧑‍💻 dev experience

#2687 Better `Print Datastore` tools
  crates/re_arrow_store/src/store_dump.rs
  crates/re_viewer/src/app.rs
  crates/rerun/src/run.rs
Labels: 🧑‍💻 dev experience, ⛃ re_datastore, 📺 re_viewer

#2667 Fix camera tracking delay/flicker
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 🪳 bug, 📺 re_viewer

#2533 Writeup of the Space View (Class) framework
  design/space_views.md
Labels: 📖 documentation

#2688 Dynamically registered space view (part/context) systems
  crates/re_data_ui/src/lib.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/src/contexts/annotation_context.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_spatial/src/parts/spatial_view_part.rs
  crates/re_space_view_spatial/src/space_view_class.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_space_view_text/src/space_view_class.rs
  crates/re_space_view_text/src/view_part_system.rs
  crates/re_space_view_text_box/src/space_view_class.rs
  crates/re_space_view_text_box/src/view_part_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/scene.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
Labels: 📺 re_viewer, 🚜 refactor

#2577 Consistent transform visualization for all entities with transforms
  crates/re_data_store/src/entity_properties.rs
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_space_view_spatial/src/axis_lines.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/transform3d_arrows.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/annotations.rs
  tests/python/test_api/main.py
Labels: enhancement, 📺 re_viewer

#2703 Clear cache workflow
  .github/workflows/clear_cache.yml
Labels: 🧑‍💻 dev experience

#2710 Weekly crates.io release
  .github/workflows/weekly_release.yml
  scripts/ci/crates.py
Labels: 🧑‍💻 dev experience, ⛴ release

#2711 Weekly release (part 2)
  .github/workflows/weekly_release.yml
Labels: 🧑‍💻 dev experience, ⛴ release

#2693 run_all.py: rename `--separate` to `--parallel`
  RELEASES.md
  ci_docker/Dockerfile
  crates/re_data_store/src/entity_tree.rs
  crates/re_ui/src/toasts.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/time_control.rs
  crates/rerun/src/run.rs
  justfile
  scripts/run_all.py
  scripts/setup.sh
  scripts/setup_dev.sh
Labels: 🧑‍💻 dev experience

#2744 Fix weekly crate release
  .github/workflows/manual_release.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/weekly_release.yml
Labels: 🧑‍💻 dev experience

#2751 WASM -> wasm in reusable_release_crates.yml
  .github/workflows/reusable_release_crates.yml
Labels: 🧑‍💻 dev experience

#2707 C++ codegen of structs and unions
  .clang-format
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/codegen/cpp.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  examples/cpp/minimal/main.cpp
  rerun_cpp/src/archetypes/affix_fuzzer1.hpp
  rerun_cpp/src/archetypes/points2d.hpp
  rerun_cpp/src/archetypes/transform3d.hpp
  rerun_cpp/src/components/affix_fuzzer1.hpp
  rerun_cpp/src/components/affix_fuzzer10.hpp
  rerun_cpp/src/components/affix_fuzzer11.hpp
  rerun_cpp/src/components/affix_fuzzer12.hpp
  rerun_cpp/src/components/affix_fuzzer13.hpp
  rerun_cpp/src/components/affix_fuzzer14.hpp
  rerun_cpp/src/components/affix_fuzzer16.hpp
  rerun_cpp/src/components/affix_fuzzer17.hpp
  rerun_cpp/src/components/affix_fuzzer18.hpp
  rerun_cpp/src/components/affix_fuzzer19.hpp
  rerun_cpp/src/components/affix_fuzzer2.hpp
  rerun_cpp/src/components/affix_fuzzer3.hpp
  rerun_cpp/src/components/affix_fuzzer4.hpp
  rerun_cpp/src/components/affix_fuzzer5.hpp
  rerun_cpp/src/components/affix_fuzzer6.hpp
  rerun_cpp/src/components/affix_fuzzer7.hpp
  rerun_cpp/src/components/affix_fuzzer8.hpp
  rerun_cpp/src/components/affix_fuzzer9.hpp
  rerun_cpp/src/components/class_id.hpp
  rerun_cpp/src/components/color.hpp
  rerun_cpp/src/components/draw_order.hpp
  rerun_cpp/src/components/instance_key.hpp
  rerun_cpp/src/components/keypoint_id.hpp
  rerun_cpp/src/components/label.hpp
  rerun_cpp/src/components/point2d.hpp
  rerun_cpp/src/components/radius.hpp
  rerun_cpp/src/components/transform3d.hpp
  rerun_cpp/src/datatypes/affix_fuzzer1.hpp
  rerun_cpp/src/datatypes/affix_fuzzer2.hpp
  rerun_cpp/src/datatypes/affix_fuzzer3.hpp
  rerun_cpp/src/datatypes/affix_fuzzer4.hpp
  rerun_cpp/src/datatypes/affix_fuzzer5.hpp
  rerun_cpp/src/datatypes/angle.hpp
  rerun_cpp/src/datatypes/flattened_scalar.hpp
  rerun_cpp/src/datatypes/mat3x3.hpp
  rerun_cpp/src/datatypes/mat4x4.hpp
  rerun_cpp/src/datatypes/point2d.hpp
  rerun_cpp/src/datatypes/quaternion.hpp
  rerun_cpp/src/datatypes/rotation3d.hpp
  rerun_cpp/src/datatypes/rotation_axis_angle.hpp
  rerun_cpp/src/datatypes/scale3d.hpp
  rerun_cpp/src/datatypes/transform3d.hpp
  rerun_cpp/src/datatypes/translation_and_mat3x3.hpp
  rerun_cpp/src/datatypes/translation_rotation_scale3d.hpp
  rerun_cpp/src/datatypes/vec2d.hpp
  rerun_cpp/src/datatypes/vec3d.hpp
  rerun_cpp/src/datatypes/vec4d.hpp
  scripts/lint.py
Labels: C/C++ SDK

#2708 Support nullable Arrow unions using virtual union arms
  Cargo.lock
  crates/re_types/Cargo.toml
  crates/re_types/definitions/rerun/testing/archetypes/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/lib.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/objects.rs
  rerun_cpp/src/archetypes/affix_fuzzer1.hpp
  rerun_cpp/src/components.hpp
  rerun_cpp/src/components/affix_fuzzer15.cpp
  rerun_cpp/src/components/affix_fuzzer15.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/scale3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/transform3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/translation_rotation_scale3d.py
Labels: 🏹 arrow, codegen/idl

#2669 Roundtrip-able `Transform3D`s
  .gitignore
  crates/re_log_types/src/data_table.rs
  crates/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/re_types/definitions/rerun/components/transform3d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/transform3d_ext.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/angle_ext.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mat3x3_ext.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation3d_ext.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/rotation_axis_angle_ext.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/scale3d_ext.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/transform3d_ext.rs
  crates/re_types/src/datatypes/translation_and_mat3x3_ext.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d_ext.rs
  crates/re_types/src/datatypes/vec3d_ext.rs
  crates/re_types/tests/transform3d.rs
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/codegen/rust.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/transform3d_simple_v2.py
  docs/code-examples/transform3d_simple_v2.rs
  rerun_cpp/src/archetypes/transform3d.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/transform3d.py
  rerun_py/rerun_sdk/rerun/experimental.py
  scripts/ci/crates.py
  scripts/ci/run_e2e_roundtrip_tests.py
  tests/python/roundtrips/transform3d/main.py
  tests/rust/roundtrips/transform3d/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 🐍 python API, 🦀 rust SDK, codegen/idl

#2746 Fix flickering of orbit camera indicator
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 🪳 bug, 📺 re_viewer

#2753 Point sccache to GCS
  .github/actions/setup-rust/action.yml
  .github/workflows/manual_dispatch.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
Labels: 🧑‍💻 dev experience, ⏱ build-times

#2761 Fix caching on main
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_deploy_docs.yml
Labels: 🧑‍💻 dev experience, ⏱ build-times

#2760 Don't inline recursive datatypes in Rust backend
  crates/re_types/source_hash.txt
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, 🧑‍💻 dev experience, codegen/idl

#2743 Introduce support for querying Archetypes
  Cargo.lock
  crates/re_components/Cargo.toml
  crates/re_components/src/class_id.rs
  crates/re_components/src/keypoint_id.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/instance_key.rs
  crates/re_query/Cargo.toml
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_query/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_query/src/range.rs
  crates/re_query/src/util.rs
  crates/re_query/tests/archetype_visit_tests.rs
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/fuzzy.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/instance_key_ext.rs
  crates/re_types/src/lib.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: codegen/idl

#2764 Move object property heuristics to heuristics.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/ui.rs
Labels: 📺 re_viewer, 🚜 refactor

#2770 Update python's `test_api` to use new `Transform3D` APIs
  tests/python/test_api/main.py
Labels: 🐍 python API, codegen/idl

#2772 Automatically derive `tuple_struct` attr and trivial `From` impls where possible
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/draw_order.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/label.fbs
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/radius.fbs
  crates/re_types/definitions/rerun/components/transform3d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point2d_ext.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/transform3d_ext.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, 🧑‍💻 dev experience, codegen/idl

#2766 Cpp codegen to_arrow_data_type for unions
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/cpp/method.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  rerun_cpp/src/components/affix_fuzzer14.cpp
  rerun_cpp/src/components/affix_fuzzer15.cpp
  rerun_cpp/src/components/affix_fuzzer16.cpp
  rerun_cpp/src/components/affix_fuzzer17.cpp
  rerun_cpp/src/components/affix_fuzzer18.cpp
  rerun_cpp/src/components/transform3d.cpp
  rerun_cpp/src/datatypes/affix_fuzzer3.cpp
  rerun_cpp/src/datatypes/affix_fuzzer3.hpp
  rerun_cpp/src/datatypes/affix_fuzzer4.cpp
  rerun_cpp/src/datatypes/affix_fuzzer4.hpp
  rerun_cpp/src/datatypes/affix_fuzzer5.cpp
  rerun_cpp/src/datatypes/angle.cpp
  rerun_cpp/src/datatypes/angle.hpp
  rerun_cpp/src/datatypes/rotation3d.cpp
  rerun_cpp/src/datatypes/rotation3d.hpp
  rerun_cpp/src/datatypes/rotation_axis_angle.cpp
  rerun_cpp/src/datatypes/scale3d.cpp
  rerun_cpp/src/datatypes/scale3d.hpp
  rerun_cpp/src/datatypes/transform3d.cpp
  rerun_cpp/src/datatypes/transform3d.hpp
  rerun_cpp/src/datatypes/translation_rotation_scale3d.cpp
Labels: codegen/idl, C/C++ SDK

#2777 Mark generated files as generated in .gitattributes
  .gitattributes
  crates/re_types/.gitattributes
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
  rerun_cpp/src/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/scale3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/transform3d.py
Labels: 🧑‍💻 dev experience, codegen/idl

#2781 Add "UP" ruff ruleset and remove pyupgrade
  justfile
  rerun_py/pyproject.toml
  rerun_py/requirements-lint.txt
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/scale3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/transform3d.py
Labels: 🐍 python API, 🧑‍💻 dev experience

#2783 Add missing feature-dependency from `re_sdk` to `re_components/arrow_datagen`.
  crates/re_sdk/Cargo.toml
Labels: 🔨 testing, dependencies

#2796 Disable expansion effects in the UI
  crates/re_ui/src/design_tokens.rs
Labels: ui

#2769 Speed up Component interface by passing iterators through from arrow2-convert
  Cargo.lock
  crates/re_arrow_store/src/store_helpers.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/example_components.rs
  crates/re_log_types/src/instance_key.rs
  crates/re_log_types/src/lib.rs
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_query/src/visit.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/fuzzy.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/fuzzy.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/point3d.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/lib.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 📉 performance, codegen/idl

#2784 Add `fmt::Debug` implementations to various types.
  crates/re_log_encoding/src/file_sink.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/buffered_client.rs
Labels: 🦀 rust SDK, 🧑‍💻 dev experience

#2804 Avoid unwrap when generating authkey
  rerun_py/src/python_bridge.rs
Labels: 🐍 python API

#2803 Implement the unit-tests for archetype-based queries and range-queries and fix range-query bug
  crates/re_query/src/range.rs
  crates/re_query/tests/archetype_query_tests.rs
  crates/re_query/tests/archetype_range_tests.rs
Labels: 🪳 bug, codegen/idl

#2806 Fix visibility toggle for maximized Space Views
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, ui, 📺 re_viewer

#2807 Fix loading file via CLI
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/src/run.rs
Labels: 🪳 bug, 📺 re_viewer, 📊 analytics, 🦟 regression

#2810 Isolate testing types in Rust backend
  crates/re_types/.gitattributes
  crates/re_types/Cargo.toml
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/archetypes/fuzzy.rs
  crates/re_types/src/testing/archetypes/mod.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/mod.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types/src/testing/datatypes/mod.rs
  crates/re_types/src/testing/mod.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/rust.rs
  scripts/ci/check_large_files_allow_list.txt
Labels: 🦀 rust SDK, 🧑‍💻 dev experience, codegen/idl

#2811 Temporarily switch points2d back to using the legacy entity interface
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
Labels: 📺 re_viewer, 📉 performance, 🦟 regression

#2819 Fix objectron 2D view not being 2D
  crates/re_space_view_spatial/src/heuristics.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#2818 Recreate __all__ in rerun/__init__.py
  rerun_py/rerun_sdk/rerun/__init__.py
Labels: 🪳 bug, 🐍 python API

#2813 Support feature-gated rust attributes
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rust/attributes.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/instance_key_ext.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/lib.rs
Labels: 🦀 rust SDK, codegen/idl

#2815 Add support for `RecordingStream::serve`
  Cargo.lock
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk/src/web_viewer.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/clap.rs
  crates/rerun/src/lib.rs
  crates/rerun/src/run.rs
  docs/content/reference/sdk-operating-modes.md
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/minimal_serve/README.md
  examples/rust/minimal_serve/src/main.rs
Labels: 🕸️ web, 🦀 rust SDK

#2832 Fix disconnected space APIs in Python SDK
  rerun_py/rerun_sdk/rerun/log/transform.py
Labels: 🪳 bug, 🐍 python API

#2831 Fixup remaining usages of log_rigid3 in docs
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/reference/data_types/transform3d.md
  examples/python/ros_node/main.py
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation

#2821 Fix shutdown race-condition by introducing a flush_timeout before dropping data
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/buffered_client.rs
  crates/re_sdk_comms/src/lib.rs
  crates/re_sdk_comms/src/tcp_client.rs
  crates/rerun/src/clap.rs
  crates/rerun/src/lib.rs
  crates/rerun_c/src/lib.rs
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 🪳 bug, 🐍 python API

#2822 Expose batch APIs for linestrips
  crates/re_types/source_hash.txt
  docs/code-examples/line_strip2d_batch.py
  docs/code-examples/line_strip3d_batch.py
  docs/content/reference/data_types/linestrip2d.md
  docs/content/reference/data_types/linestrip3d.md
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/components/linestrip.py
  rerun_py/rerun_sdk/rerun/log/lines.py
Labels: 🐍 python API

#2834 Actually use sccache in the reusable_checks job
  .github/workflows/reusable_checks.yml
Labels: 🧑‍💻 dev experience

#2824 Fix selection highlighting in blueprint tree view
  crates/re_ui/src/design_tokens.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, ui

#2837 Rename log_any to log
  crates/re_types/source_hash.txt
  docs/code-examples/point2d_random_v2.py
  docs/code-examples/point2d_simple_v2.py
  docs/code-examples/point3d_random_v2.py
  docs/code-examples/point3d_simple_v2.py
  docs/code-examples/transform3d_simple_v2.py
  examples/python/blueprint/main.py
  examples/python/notebook/blueprint.ipynb
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/log_any.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/tests/unit/test_log.py
  rerun_py/tests/unit/test_points2d.py
  rerun_py/tests/unit/test_points3d.py
  tests/python/roundtrips/points2d/main.py
  tests/python/roundtrips/points3d/main.py
  tests/python/roundtrips/transform3d/main.py
  tests/python/test_api/main.py
Labels: 🐍 python API

#2844 "Show bounding box" now shows correct bounding box, added "Show accumulated bounding box" for previous behavior
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 🪳 bug, enhancement, 📺 re_viewer

#2845 Fix `rr2.log()` silently dropping data in some cases
  rerun_py/ARCHITECTURE.md
  rerun_py/rerun_sdk/rerun/_rerun2/log.py
  rerun_py/rerun_sdk/rerun/experimental.py
Labels: 🪳 bug, 🐍 python API

#2839 If a user hasn't interacted with the camera, continue to resize to the orbit-eye
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: ui, 🛑 controversial

#2847 Apply space view heuristics before showing any ui & improve default arrow length for camera extrinsics
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport.rs
  tests/python/test_api/main.py
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#2848 Lower logo resolution to avoid aliasing on low-dpi screens
  crates/re_ui/data/icons/rerun_io.png
Labels: 🪳 bug, 📺 re_viewer

#2842 Release 0.8 - Infrastructure investments and more transform improvements - 2023-07-27
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
Labels: ⛴ release

#2851 Migrate to custom checkbox/radio_value UI
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text/src/space_view_class.rs
  crates/re_space_view_text_box/src/space_view_class.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  scripts/lint.py
Labels: ui

#2853 Bump to version 0.9.0-alpha.0
  Cargo.lock
  Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
Labels: ⛴ release

#2854 Fix outdated links in docs
  docs/content/concepts/annotation-context.md
  docs/content/concepts/entity-component.md
  docs/content/getting-started/logging-rust.md
Labels: 📖 documentation

#2863 Remove expansion effect from time panel toolbar
  crates/re_time_panel/src/time_control_ui.rs
  crates/re_ui/src/lib.rs
Labels: ui

#2836 `DisconnectSpace` improvements
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_viewport/src/space_info.rs
  crates/re_viewport/src/space_view_heuristics.rs
  docs/content/concepts/spaces-and-transforms.md
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/log/transform.py
Labels: 🐍 python API, 📺 re_viewer, 🍏 primitives

#2864 Remove expansion effect from the large collapsing headers
  crates/re_ui/src/lib.rs
Labels: ui

#2867 Remove draw order from 3d points
  crates/re_types/definitions/rerun/archetypes/points3d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/tests/points3d.rs
  rerun_cpp/src/archetypes/points3d.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/log/points.py
  rerun_py/tests/unit/test_points3d.py
  tests/python/roundtrips/points3d/main.py
  tests/rust/roundtrips/points3d/src/main.rs
Labels: 🪳 bug, 🍏 primitives, 🦟 regression

#2872 Change the styling of hyperlinks
  crates/re_ui/src/design_tokens.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: ui

#2878 Recreate the analytics state directory if necessary before creating pipeline
  crates/re_analytics/src/pipeline_native.rs
Labels: 🪳 bug, 📊 analytics
