Repository rerun-io/rerun, pull requests merged in 2023-08, with the labels that each got.

#2879 Improve space view tab design
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/lib.rs
  crates/re_viewport/src/viewport.rs
Labels: ui

#2891 Improved automatic `From` impl in Rust codegen backend
  crates/re_types/source_hash.txt
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/point3d_ext.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/transform3d_ext.rs
  crates/re_types/src/datatypes/point2d_ext.rs
  crates/re_types/src/datatypes/point3d_ext.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, 🧑‍💻 dev experience, codegen/idl

#2882 Handle transparency for nested components that are primitives or strings
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/testing/archetypes/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy_deps.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/testing/archetypes/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy_deps.rs
  crates/re_types/src/testing/components/mod.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types/src/testing/datatypes/mod.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/rust.rs
  rerun_cpp/src/.gitattributes
  rerun_cpp/src/archetypes/affix_fuzzer1.cpp
  rerun_cpp/src/archetypes/affix_fuzzer1.hpp
  rerun_cpp/src/components.hpp
  rerun_cpp/src/components/affix_fuzzer20.cpp
  rerun_cpp/src/components/affix_fuzzer20.hpp
  rerun_cpp/src/components/primitive_component.cpp
  rerun_cpp/src/components/primitive_component.hpp
  rerun_cpp/src/components/string_component.cpp
  rerun_cpp/src/components/string_component.hpp
  rerun_cpp/src/datatypes.hpp
  rerun_cpp/src/datatypes/affix_fuzzer20.cpp
  rerun_cpp/src/datatypes/affix_fuzzer20.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy_deps.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
Labels: codegen/idl

#2896 Handle older numpy versions / py 3.8 in `VecND` extensions
  crates/re_types/source_hash.txt
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/arrow3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/vecxd.py
Labels: 🪳 bug, 🐍 python API

#2894 Redefine `PointND` components as SoA
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_components/tests/data_table.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/point3d.fbs
  crates/re_types/definitions/rerun/datatypes.fbs
  crates/re_types/definitions/rerun/datatypes/point2d.fbs
  crates/re_types/definitions/rerun/datatypes/point3d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point2d_ext.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/point3d_ext.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/datatypes/point2d.rs
  crates/re_types/src/datatypes/point2d_ext.rs
  crates/re_types/src/datatypes/point3d.rs
  crates/re_types/src/datatypes/point3d_ext.rs
  rerun_cpp/src/.gitattributes
  rerun_cpp/src/components/point2d.cpp
  rerun_cpp/src/components/point2d.hpp
  rerun_cpp/src/components/point3d.cpp
  rerun_cpp/src/components/point3d.hpp
  rerun_cpp/src/datatypes.hpp
  rerun_cpp/src/datatypes/point2d.cpp
  rerun_cpp/src/datatypes/point2d.hpp
  rerun_cpp/src/datatypes/point3d.cpp
  rerun_cpp/src/datatypes/point3d.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/point3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/point3d.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_points2d.py
  rerun_py/tests/unit/test_points3d.py
Labels: 🐍 python API, 🏹 arrow, 🦀 rust SDK, codegen/idl, C/C++ SDK

#2898 Redefine `Arrow3D` as SoA: introduce `Origin3D` and `Vector3D`
  crates/re_components/src/lib.rs
  crates/re_sdk/src/lib.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes/arrows3d.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/origin3d.fbs
  crates/re_types/definitions/rerun/components/vector3d.fbs
  crates/re_types/definitions/rerun/datatypes.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/arrow3d.rs
  crates/re_types/src/components/arrow3d_ext.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/arrow3d.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/tests/arrows3d.rs
  docs/code-examples/arrow3d_simple.rs
  docs/code-examples/arrow3d_simple_v2.py
  docs/code-examples/arrow3d_simple_v2.rs
  docs/code-examples/transform3d_simple.rs
  docs/code-examples/transform3d_simple_v2.rs
  examples/rust/clock/src/main.rs
  rerun_cpp/src/.gitattributes
  rerun_cpp/src/archetypes/arrows3d.cpp
  rerun_cpp/src/archetypes/arrows3d.hpp
  rerun_cpp/src/components.hpp
  rerun_cpp/src/components/origin3d.cpp
  rerun_cpp/src/components/origin3d.hpp
  rerun_cpp/src/components/vector3d.cpp
  rerun_cpp/src/components/vector3d.hpp
  rerun_cpp/src/datatypes.hpp
  rerun_cpp/src/datatypes/arrow3d.cpp
  rerun_cpp/src/datatypes/arrow3d.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/arrow3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/origin3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/vector3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/arrow3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/arrow3d.py
  rerun_py/rerun_sdk/rerun/log/arrow.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_arrows3d.py
  rerun_py/tests/unit/test_points3d.py
  tests/python/roundtrips/arrows3d/main.py
  tests/rust/roundtrips/arrows3d/src/main.rs
Labels: 🐍 python API, 🏹 arrow, 🦀 rust SDK, codegen/idl

#2901 CI for C++ (formatting check + running tests)
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_upload_wheels.yml
  CMakeLists.txt
  ci_docker/Dockerfile
  ci_docker/publish.sh
  examples/cpp/minimal/CMakeLists.txt
  rerun_cpp/CMakeLists.txt
  rerun_cpp/tests/CMakeLists.txt
  scripts/setup.sh
Labels: 🧑‍💻 dev experience, C/C++ SDK

#2900 Fix always redrawing in the presence of a 3D space view
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 🪳 bug, 📺 re_viewer, 📉 performance

#2910 Fully migrate to new AnnotationContext and remove more legacy types.
  Cargo.lock
  crates/re_components/src/class_id.rs
  crates/re_components/src/color.rs
  crates/re_components/src/context.rs
  crates/re_components/src/datagen.rs
  crates/re_components/src/keypoint_id.rs
  crates/re_components/src/label.rs
  crates/re_components/src/lib.rs
  crates/re_data_ui/Cargo.toml
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/image.rs
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/query.rs
  crates/re_query/src/range.rs
  crates/re_query/tests/archetype_visit_tests.rs
  crates/re_sdk/src/lib.rs
  crates/re_space_view_spatial/src/contexts/annotation_context.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_types/definitions/rerun/components/annotation_context.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/body_ext.rs
  crates/re_types/src/components/level_ext.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  examples/python/human_pose_tracking/main.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/annotation_context.py
  rerun_py/rerun_sdk/rerun/log/annotation.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_annotation_context.py
Labels: codegen/idl

#2742 Allow changing plot aspect ratio with scroll + cmd/ctrl + alt
  crates/re_space_view/src/controls.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: enhancement, 📺 re_viewer

#2913 Make `cargo codegen` work irrelevant of CWD
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/bin/build_re_types.rs
Labels: 🧑‍💻 dev experience, codegen/idl

#2912 Derive `app_id` from example name for all rust doc examples
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/transform3d.rs
  docs/code-examples/annotation_context_connections.rs
  docs/code-examples/annotation_context_rects.rs
  docs/code-examples/annotation_context_segmentation.rs
  docs/code-examples/arrow3d_simple.rs
  docs/code-examples/arrow3d_simple_v2.rs
  docs/code-examples/box3d_simple.rs
  docs/code-examples/depth_image_3d.rs
  docs/code-examples/depth_image_simple.rs
  docs/code-examples/disconnected_space_v2.rs
  docs/code-examples/extension-components/example.rs
  docs/code-examples/image_simple.rs
  docs/code-examples/line_segments2d_simple.rs
  docs/code-examples/line_segments3d_simple.rs
  docs/code-examples/line_strip2d_simple.rs
  docs/code-examples/line_strip3d_simple.rs
  docs/code-examples/mesh_simple.rs
  docs/code-examples/pinhole_simple.rs
  docs/code-examples/point2d_random.rs
  docs/code-examples/point2d_random_v2.rs
  docs/code-examples/point2d_simple.rs
  docs/code-examples/point2d_simple_v2.rs
  docs/code-examples/point3d_random.rs
  docs/code-examples/point3d_random_v2.rs
  docs/code-examples/point3d_simple.rs
  docs/code-examples/point3d_simple_v2.rs
  docs/code-examples/rect2d_simple.rs
  docs/code-examples/scalar_simple.rs
  docs/code-examples/segmentation_image_simple.rs
  docs/code-examples/tensor_one_dim.rs
  docs/code-examples/tensor_simple.rs
  docs/code-examples/text_entry_simple.rs
  docs/code-examples/transform3d_simple.rs
  docs/code-examples/transform3d_simple_v2.rs
Labels: 📖 documentation, 🦀 rust SDK, examples, codegen/idl

#2914 Add (debug-only) style panel
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/rerun_menu.rs
Labels: ui, 🧑‍💻 dev experience

#2916 C++ codegen extensions, archetype tests, array ctors
  crates/re_build_tools/src/hashing.rs
  crates/re_build_tools/src/lib.rs
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/lib.rs
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  docs/code-examples/arrow3d_simple_v2.cpp
  docs/code-examples/point3d_random_v2.cpp
  docs/code-examples/point3d_simple_v2.cpp
  examples/cpp/minimal/main.cpp
  rerun_cpp/src/rerun/archetypes/affix_fuzzer1.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/components/color.hpp
  rerun_cpp/src/rerun/components/color_ext.cpp
  rerun_cpp/src/rerun/components/label.hpp
  rerun_cpp/src/rerun/components/label_ext.cpp
  rerun_cpp/src/rerun/components/origin3d.hpp
  rerun_cpp/src/rerun/components/origin3d_ext.cpp
  rerun_cpp/src/rerun/components/point2d.hpp
  rerun_cpp/src/rerun/components/point2d_ext.cpp
  rerun_cpp/src/rerun/components/point3d.hpp
  rerun_cpp/src/rerun/components/point3d_ext.cpp
  rerun_cpp/src/rerun/components/vector3d.hpp
  rerun_cpp/src/rerun/components/vector3d_ext.cpp
  rerun_cpp/src/rerun/datatypes/mat3x3.hpp
  rerun_cpp/src/rerun/datatypes/mat4x4.hpp
  rerun_cpp/src/rerun/datatypes/quaternion.hpp
  rerun_cpp/src/rerun/datatypes/quaternion_ext.cpp
  rerun_cpp/src/rerun/datatypes/vec2d.hpp
  rerun_cpp/src/rerun/datatypes/vec2d_ext.cpp
  rerun_cpp/src/rerun/datatypes/vec3d.hpp
  rerun_cpp/src/rerun/datatypes/vec3d_ext.cpp
  rerun_cpp/src/rerun/datatypes/vec4d.hpp
  rerun_cpp/src/rerun/datatypes/vec4d_ext.cpp
  rerun_cpp/tests/archetype_test.hpp
  rerun_cpp/tests/arrows3d.cpp
  rerun_cpp/tests/color.cpp
  rerun_cpp/tests/disconnected_space.cpp
  rerun_cpp/tests/points2d.cpp
  rerun_cpp/tests/points3d.cpp
  rerun_cpp/tests/recording_stream.cpp
  rerun_cpp/tests/vec_and_quaternion.cpp
  tests/cpp/roundtrips/arrows3d/main.cpp
  tests/cpp/roundtrips/disconnected_space/main.cpp
  tests/cpp/roundtrips/points3d/main.cpp
  tests/cpp/run_all.sh
Labels: C/C++ SDK

#2930 Add `Helix` to `demo.rerun.io`
  examples/python/dna/main.py
  scripts/ci/build_demo_app.py
Labels: examples

#2929 Sunset legacy `LineStrip{2|3}D`
  crates/re_components/src/lib.rs
  crates/re_components/src/linestrip.rs
  crates/re_components/tests/data_table.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_sdk/src/lib.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  docs/code-examples/line_strip2d_batch_v2.py
  docs/code-examples/line_strip2d_batch_v2.rs
  docs/code-examples/line_strip3d_batch_v2.py
  docs/code-examples/line_strip3d_batch_v2.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/components/linestrip.py
  rerun_py/rerun_sdk/rerun/log/lines.py
  rerun_py/rerun_sdk/rerun/log/points.py
  tests/rust/test_api/src/main.rs
Labels: 🐍 python API, 🏹 arrow, 🦀 rust SDK, 📺 re_viewer, codegen/idl

#2936 Add clip rect in panels and use them for large collapsing headers
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui

#2931 Pass through strings using arrow2::Buffers
  crates/re_data_ui/src/annotation_context.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/arrow_string.rs
  crates/re_types/src/components/body_ext.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/label_ext.rs
  crates/re_types/src/components/level_ext.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy_deps.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types/tests/arrows3d.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/line_strips2d.rs
  crates/re_types/tests/line_strips3d.rs
  crates/re_types/tests/points2d.rs
  crates/re_types/tests/points3d.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_viewer_context/src/annotations.rs
  examples/rust/objectron/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 📉 performance, codegen/idl

#2939 `scripts/highlight_issues.py`: print issues with no comments
  scripts/highlight_issues.py
Labels: 🧑‍💻 dev experience

#2942 Update clang-format
  Cargo.lock
  crates/re_types/source_hash.txt
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/src/codegen/cpp/mod.rs
Labels: dependencies

#2945 Fix major perf regression caused by unoptimized boundchecks
  Cargo.lock
  crates/re_types/Cargo.toml
  crates/re_types/source_hash.txt
  crates/re_types/src/components/annotation_context.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/disconnected_space.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/line_strip2d.rs
  crates/re_types/src/components/line_strip3d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/datatypes/class_description.rs
  crates/re_types/src/datatypes/class_description_map_elem.rs
  crates/re_types/src/datatypes/keypoint_pair.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy_deps.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types_builder/src/codegen/rust.rs
Labels: 🦀 rust SDK, 📺 re_viewer, 📉 performance, 🦟 regression

#2943 Fix quotes in generated C++ doc strings
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/cpp/mod.rs
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/datatypes/keypoint_pair.hpp
Labels: codegen/idl, C/C++ SDK

#2949 Use `prettyplease` to improve formatting of generated Rust code
  Cargo.lock
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/annotation_context.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/disconnected_space.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/line_strip2d.rs
  crates/re_types/src/components/line_strip3d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/datatypes/class_description.rs
  crates/re_types/src/datatypes/class_description_map_elem.rs
  crates/re_types/src/datatypes/keypoint_pair.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/testing/archetypes/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy_deps.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/src/codegen/rust.rs
  deny.toml
Labels: 🧑‍💻 dev experience, codegen/idl

#2948 C++ annotation context
  .vscode/settings.json
  crates/re_types/definitions/rerun/archetypes/annotation_context.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/cpp/mod.rs
  docs/code-examples/annotation_context_arrows_v2.cpp
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/components/affix_fuzzer11.cpp
  rerun_cpp/src/rerun/components/affix_fuzzer12.cpp
  rerun_cpp/src/rerun/components/affix_fuzzer13.cpp
  rerun_cpp/src/rerun/components/affix_fuzzer16.cpp
  rerun_cpp/src/rerun/components/affix_fuzzer17.cpp
  rerun_cpp/src/rerun/components/affix_fuzzer18.cpp
  rerun_cpp/src/rerun/components/affix_fuzzer7.cpp
  rerun_cpp/src/rerun/components/annotation_context.cpp
  rerun_cpp/src/rerun/components/annotation_context.hpp
  rerun_cpp/src/rerun/components/annotation_context_ext.cpp
  rerun_cpp/src/rerun/components/line_strip2d.cpp
  rerun_cpp/src/rerun/components/line_strip3d.cpp
  rerun_cpp/src/rerun/datatypes/affix_fuzzer1.cpp
  rerun_cpp/src/rerun/datatypes/annotation_info.hpp
  rerun_cpp/src/rerun/datatypes/annotation_info_ext.cpp
  rerun_cpp/src/rerun/datatypes/class_description.cpp
  rerun_cpp/src/rerun/datatypes/class_description.hpp
  rerun_cpp/src/rerun/datatypes/class_description_ext.cpp
  rerun_cpp/src/rerun/datatypes/class_description_map_elem.hpp
  rerun_cpp/src/rerun/datatypes/class_description_map_elem_ext.cpp
  rerun_cpp/src/rerun/datatypes/keypoint_pair.hpp
  rerun_cpp/src/rerun/datatypes/keypoint_pair_ext.cpp
  rerun_cpp/src/rerun/datatypes/mat3x3.cpp
  rerun_cpp/src/rerun/datatypes/mat4x4.cpp
  rerun_cpp/src/rerun/datatypes/quaternion.cpp
  rerun_cpp/src/rerun/datatypes/vec2d.cpp
  rerun_cpp/src/rerun/datatypes/vec3d.cpp
  rerun_cpp/src/rerun/datatypes/vec4d.cpp
  rerun_cpp/tests/annotation_context.cpp
  scripts/ci/run_e2e_roundtrip_tests.py
  tests/cpp/roundtrips/annotation_context/main.cpp
Labels: 🍏 primitives, codegen/idl, C/C++ SDK

#2953 Codegen'd deserialization refactoring: correctness, error handling, helpers
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy_deps.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/components/annotation_context.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/disconnected_space.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/line_strip2d.rs
  crates/re_types/src/components/line_strip3d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/datatypes/class_description.rs
  crates/re_types/src/datatypes/class_description_map_elem.rs
  crates/re_types/src/datatypes/keypoint_pair.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/archetypes/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy_deps.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types/src/testing/datatypes/fuzzy_ext.rs
  crates/re_types/src/testing/datatypes/mod.rs
  crates/re_types_builder/src/codegen/rust.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/arrow.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/codegen/rust/mod.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_builder/src/codegen/rust/util.rs
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/transform3d.py
Labels: 🐍 python API, 🦀 rust SDK, codegen/idl

#2956 C++ Linestrips examples & tests
  crates/re_types/definitions/rerun/archetypes/line_strips2d.fbs
  crates/re_types/definitions/rerun/archetypes/line_strips3d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  docs/code-examples/line_segments2d_simple_v2.cpp
  docs/code-examples/line_segments3d_simple_v2.cpp
  docs/code-examples/line_strip2d_batch_v2.cpp
  docs/code-examples/line_strip2d_simple_v2.cpp
  docs/code-examples/line_strip3d_batch_v2.cpp
  docs/code-examples/line_strip3d_simple_v2.cpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/components/line_strip2d.hpp
  rerun_cpp/src/rerun/components/line_strip3d.hpp
  rerun_cpp/tests/archetypes/annotation_context.cpp
  rerun_cpp/tests/archetypes/archetype_test.hpp
  rerun_cpp/tests/archetypes/arrows3d.cpp
  rerun_cpp/tests/archetypes/disconnected_space.cpp
  rerun_cpp/tests/archetypes/lines_strips2d.cpp
  rerun_cpp/tests/archetypes/lines_strips3d.cpp
  rerun_cpp/tests/archetypes/points2d.cpp
  rerun_cpp/tests/archetypes/points3d.cpp
  rerun_cpp/tests/archetypes/transform3d.cpp
  rerun_cpp/tests/color.cpp
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/line_strips3d.py
  scripts/ci/run_e2e_roundtrip_tests.py
  tests/cpp/roundtrips/line_strips3d/main.cpp
Labels: codegen/idl, C/C++ SDK

#2962 Enable debug symbols in build scripts (`build.rs`) in dev mode
  Cargo.toml
Labels: 🧑‍💻 dev experience, codegen/idl

#2958 `generate_changelog.py`: ignore PRs with label `exclude from changelog`
  .github/workflows/labels.yml
  scripts/generate_changelog.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#2938 Add Recordings section to the left panel
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/command.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui

#2959 C++ MSVC compilation fixes
  rerun_cpp/CMakeLists.txt
  rerun_cpp/src/rerun/recording_stream.cpp
Labels: 🪟 windows, C/C++ SDK

#2920 New triangle collapse arrow for large collapsible header
  crates/re_ui/src/lib.rs
Labels: ui

#2968 Add support for tree to ListItem
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
Labels: ui

#2969 Update egui via a `[patch]`
  Cargo.lock
  Cargo.toml
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_time_panel/src/time_ranges_ui.rs
  crates/re_ui/src/lib.rs
Labels: 🧑‍💻 dev experience, dependencies

#2971 Add hierarchical display in recordings panel
  Cargo.lock
  crates/re_ui/src/list_item.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/recordings_panel.rs
Labels: ui

#2961 New release process (part 1)
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_publish_wheels.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/weekly_release.yml
  scripts/ci/crates.py
Labels: 🧑‍💻 dev experience

#2972 Add support to close a recording
  crates/re_data_store/src/store_db.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/command_sender.rs
Labels: enhancement, ui

#2979 New release process (part 3)
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_web.yml
  Cargo.lock
  Cargo.toml
  crates/re_build_info/Cargo.toml
  crates/re_build_info/src/crate_version.rs
  crates/re_log_encoding/src/decoder.rs
  crates/re_log_encoding/src/encoder.rs
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
  scripts/ci/crates.py
  scripts/ci/version_util.py
Labels: 🧑‍💻 dev experience

#2984 New release process (part 4)
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_publish_web.yml
  .github/workflows/reusable_build_and_publish_wheels.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  Cargo.toml
  scripts/ci/crates.py
Labels: 🧑‍💻 dev experience

#2985 Add a warning category and stacklevel to rerun warnings.warn calls
  rerun_py/rerun_sdk/rerun/log/log_decorator.py
Labels: 🐍 python API

#2970 Introduce codegen optimizations for primitives and fixed-sized-arrays
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/lib.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/arrow_buffer.rs
  crates/re_types/src/components/annotation_context.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/disconnected_space.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/line_strip2d.rs
  crates/re_types/src/components/line_strip3d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/transform3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/datatypes/class_description.rs
  crates/re_types/src/datatypes/class_description_map_elem.rs
  crates/re_types/src/datatypes/class_id.rs
  crates/re_types/src/datatypes/color.rs
  crates/re_types/src/datatypes/keypoint_id.rs
  crates/re_types/src/datatypes/keypoint_pair.rs
  crates/re_types/src/datatypes/label.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/components/fuzzy_deps.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types/src/testing/datatypes/fuzzy_deps.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/util.rs
  crates/re_types/tests/validity.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/arrow.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_builder/src/objects.rs
Labels: 📉 performance, codegen/idl

#2991 Fix big bug in size estimation of array buffers
  crates/re_log_types/src/data_table.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/line_strip2d.rs
  crates/re_types/src/components/line_strip3d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/size_bytes.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  rerun_py/rerun_sdk/rerun/_rerun2/components/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/line_strip2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/line_strip3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/annotation_info.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/class_description.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/class_description_map_elem.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/fuzzy.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/keypoint_pair.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/mat4x4.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/quaternion.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/scale3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/transform3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/translation_and_mat3x3.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/translation_rotation_scale3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/vec4d.py
  scripts/ci/run_e2e_roundtrip_tests.py
Labels: 🪳 bug, 🏹 arrow

#2992 New release process (part 5)
  .github/actions/deploy-vercel/action.yml
  .github/actions/deploy-vercel/client.mjs
  .github/actions/deploy-vercel/index.mjs
  .github/actions/deploy-vercel/util.mjs
  .github/workflows/release.yml
  .github/workflows/reusable_deploy_docs.yml
  RELEASES.md
Labels: 🧑‍💻 dev experience

#2986 Automatically select user timeline if no timeline was explicitly selected yet
  crates/re_data_store/src/editable_auto_value.rs
  crates/re_viewer_context/src/time_control.rs
Labels: enhancement, 📺 re_viewer

#2998 New release process (part 7)
  .github/actions/deploy-vercel/action.yml
  .github/actions/deploy-vercel/index.mjs
  .github/actions/deploy-vercel/util.mjs
  .github/actions/deploy-vercel/vercel.mjs
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_publish_web.yml
  .github/workflows/reusable_build_and_publish_wheels.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_upload_wheels.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#2980 Update to wgpu 0.17 & latest egui
  Cargo.lock
  Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/shader/types.wgsl
  crates/re_renderer/src/error_tracker.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/texture_info.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_tensor/src/tensor_dimension_mapper.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport.rs
  deny.toml
Labels: ui, 🔺 re_renderer, dependencies

#3000 New release process (part 8)
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_upload_wheels.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#2997 Show RAM use and data rate when hovering an entity in stream view
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_data_ui/src/item_ui.rs
Labels: enhancement, ui, 📺 re_viewer

#2987 Comment that our .gitattributes files are auto-generated
  crates/re_types/.gitattributes
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/lib.rs
  rerun_cpp/src/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
Labels: 🧑‍💻 dev experience, exclude from changelog

#2988 Don't select the spaceview when maximizing it
  crates/re_viewport/src/viewport.rs
Labels: ui, 📺 re_viewer

#2976 Add delete buttons in the Recordings UI
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/recordings_panel.rs
Labels: ui

#2989 Commit to allowing multiple app ids open at the same time
  crates/re_viewer/src/store_hub.rs
Labels: exclude from changelog

#3015 Docs: mention that `rerun-sdk` is available on `conda`
  README.md
  docs/content/getting-started/viewer-walkthrough.md
  examples/python/README.md
Labels: 📖 documentation, exclude from changelog

#3016 Lint vertical spacing in .fbs files
  crates/re_types/definitions/rerun/datatypes/angle.fbs
  crates/re_types/definitions/rerun/datatypes/annotation_info.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/definitions/reflection.fbs
  crates/re_types_builder/source_hash.txt
  crates/re_types_builder/src/reflection.rs
  scripts/lint.py
Labels: 🧑‍💻 dev experience, codegen/idl, exclude from changelog

#3014 Make sure `re_analytics` never log higher than at `debug` level
  crates/re_analytics/src/lib.rs
  crates/re_analytics/src/pipeline_native.rs
Labels: 📊 analytics

#3017 Add default value for `info` argument of `ClassDescription`
  crates/re_types/definitions/rerun/datatypes/annotation_info.fbs
  crates/re_types/definitions/rerun/datatypes/class_description.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/datatypes/class_description.rs
  rerun_cpp/src/rerun/datatypes/class_description.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/annotation_info.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/class_description.py
  tests/python/roundtrips/annotation_context/main.py
Labels: 🐍 python API

#3001 C/C++ errorhandling
  CMakeLists.txt
  crates/re_types/source_hash.txt
  crates/rerun_c/src/error.rs
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/ptr.rs
  crates/rerun_c/src/rerun.h
  docs/code-examples/annotation_context_arrows_v2.cpp
  docs/code-examples/arrow3d_simple_v2.cpp
  docs/code-examples/disconnected_space_v2.cpp
  docs/code-examples/line_segments2d_simple_v2.cpp
  docs/code-examples/line_segments3d_simple_v2.cpp
  docs/code-examples/line_strip2d_batch_v2.cpp
  docs/code-examples/line_strip2d_simple_v2.cpp
  docs/code-examples/line_strip3d_batch_v2.cpp
  docs/code-examples/line_strip3d_simple_v2.cpp
  docs/code-examples/point3d_random_v2.cpp
  docs/code-examples/point3d_simple_v2.cpp
  docs/code-examples/transform3d_simple_v2.cpp
  examples/c/minimal/main.c
  examples/cpp/minimal/main.cpp
  rerun_cpp/CMakeLists.txt
  rerun_cpp/src/archetypes.hpp
  rerun_cpp/src/components.hpp
  rerun_cpp/src/datatypes.hpp
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/arrow.cpp
  rerun_cpp/src/rerun/error.cpp
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/CMakeLists.txt
  rerun_cpp/tests/error_check.hpp
  rerun_cpp/tests/main.cpp
  rerun_cpp/tests/recording_stream.cpp
  tests/cpp/roundtrips/annotation_context/main.cpp
  tests/cpp/roundtrips/arrows3d/main.cpp
  tests/cpp/roundtrips/disconnected_space/main.cpp
  tests/cpp/roundtrips/line_strips3d/main.cpp
  tests/cpp/roundtrips/points3d/main.cpp
  tests/cpp/roundtrips/transform3d/main.cpp
Labels: C/C++ SDK

#2982 Introduce a welcome screen when no recording is loaded
  crates/re_ui/data/icons/external_link.png
  crates/re_ui/data/images/welcome_screen_configure.png
  crates/re_ui/data/images/welcome_screen_live_data.png
  crates/re_ui/data/images/welcome_screen_recorded_data.png
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/wait_screen_ui.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: ui

#3029 Update `CHANGELOG.md` with 0.8.1 release
  .github/workflows/weekly_release.yml
  CHANGELOG.md
  crates/re_build_web_viewer/src/lib.rs
  rerun_py/README.md
  scripts/generate_changelog.py
  scripts/run_all.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3025 Add `clippy_wasm.sh` to `justfile` for discoverability
  justfile
Labels: 🧑‍💻 dev experience, exclude from changelog

#3030 Remove the limitation to a single dropped file
  crates/re_viewer/src/app.rs
Labels: enhancement, ui

#3026 Uniform icon, pointer, and tooltip for external links
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: ui

#3027 Fix the Streams UI when the recording is empty
  crates/re_time_panel/src/lib.rs
Labels: 🪳 bug, ui

#3037 Track file sizes
  .github/pull_request_template.md
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_track_size.yml
  scripts/ci/sizes.py
Labels: 🧑‍💻 dev experience

#3034 Reduce code bloat from generated Rust code: reuse datatype definition
  crates/re_types/source_hash.txt
  crates/re_types/src/components/annotation_context.rs
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/disconnected_space.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/label.rs
  crates/re_types/src/components/line_strip2d.rs
  crates/re_types/src/components/line_strip3d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/datatypes/class_description.rs
  crates/re_types/src/datatypes/class_description_map_elem.rs
  crates/re_types/src/datatypes/class_id.rs
  crates/re_types/src/datatypes/color.rs
  crates/re_types/src/datatypes/keypoint_id.rs
  crates/re_types/src/datatypes/keypoint_pair.rs
  crates/re_types/src/datatypes/label.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/testing/components/fuzzy.rs
  crates/re_types/src/testing/datatypes/fuzzy.rs
  crates/re_types/src/testing/datatypes/fuzzy_deps.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
Labels: codegen/idl, exclude from changelog

#3028 Add upload rerun_c to ci and show artifacts build results & releases
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  Cargo.lock
  crates/rerun_c/Cargo.toml
  scripts/ci/generate_pr_summary.py
  scripts/ci/templates/pr_results_summary.html
Labels: C/C++ SDK

#3048 Set shell to bash in reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
Labels: 🪳 bug, 🧑‍💻 dev experience

#3024 C++ resolve `archetypes` namespace within `rerun` namespace by default
  crates/re_types/source_hash.txt
  docs/code-examples/annotation_context_arrows_v2.cpp
  docs/code-examples/arrow3d_simple_v2.cpp
  docs/code-examples/disconnected_space_v2.cpp
  docs/code-examples/line_segments2d_simple_v2.cpp
  docs/code-examples/line_segments3d_simple_v2.cpp
  docs/code-examples/line_strip2d_batch_v2.cpp
  docs/code-examples/line_strip2d_simple_v2.cpp
  docs/code-examples/line_strip3d_batch_v2.cpp
  docs/code-examples/line_strip3d_simple_v2.cpp
  docs/code-examples/point3d_random_v2.cpp
  docs/code-examples/point3d_simple_v2.cpp
  docs/code-examples/transform3d_simple_v2.cpp
  examples/cpp/minimal/main.cpp
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
Labels: C/C++ SDK

#3022 Improve styling of demo header
  scripts/ci/build_demo_app.py
  scripts/ci/demo_assets/static/github-mark-white.svg
  scripts/ci/demo_assets/static/index.css
  scripts/ci/demo_assets/templates/example.html
Labels: 🕸️ web, ui

#3059 C++ CMake: let users chose dynamic or static linking for Arrow
  rerun_cpp/tests/CMakeLists.txt
Labels: 🦟 regression, C/C++ SDK

#3064 Use deterministic flushing when building web demo `.rrd` files
  .github/workflows/reusable_track_size.yml
  scripts/ci/build_demo_app.py
  scripts/ci/sizes.py
Labels: 🧑‍💻 dev experience, examples, exclude from changelog

#3068 Implement "Open file" dialog on Web
  Cargo.lock
  crates/re_ui/src/command.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/wait_screen_ui.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/lib.rs
Labels: 🕸️ web, ui

#3066 Fix docs previews
  .github/pull_request_template.md
  scripts/ci/update_pr_body.py
Labels: 🧑‍💻 dev experience

#3035 Show Welcome Screen after closing recording even with `--skip-welcome-screen`
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
Labels: ui

#3073 Fix link previews (part 2)
  scripts/ci/update_pr_body.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3067 Make use of `EditableAutoValue` implementing `Deref`
  crates/re_data_store/src/editable_auto_value.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/transform3d_arrows.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/time_control.rs
Labels: 🚜 refactor, exclude from changelog

#3060 Name the rayon threads
  Cargo.lock
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/bin/build_re_types.rs
  crates/rerun-cli/Cargo.toml
  crates/rerun-cli/src/bin/rerun.rs
Labels: 🧑‍💻 dev experience

#3070 Improve error message in common `re_renderer` crash
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  scripts/fetch_crashes.py
Labels: 🔺 re_renderer, 💣 crash

#3088 Fix quadratic slowdown when ingesting data with uniform time
  crates/re_arrow_store/src/store_write.rs
Labels: 🪳 bug, 📉 performance

#3061 Fix GitHub labels used in our weekly releases
  .github/workflows/weekly_release.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3090 Remove unused profiling macros
  Cargo.lock
  crates/re_data_store/src/lib.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/lib.rs
  crates/re_ws_comms/Cargo.toml
  crates/re_ws_comms/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#3094 Normalize quaternions
  crates/re_types/definitions/rerun/datatypes/quaternion.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/quaternion_ext.rs
  rerun_cpp/src/rerun/datatypes/quaternion.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/quaternion.py
Labels: 🪳 bug, 📺 re_viewer

#3100 Lint: Use `…` instead of `...`
  README.md
  crates/re_analytics/src/pipeline_native.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_build_info/src/build_info.rs
  crates/re_build_tools/src/lib.rs
  crates/re_components/src/tensor.rs
  crates/re_data_store/src/store_db.rs
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_query/tests/range_tests.rs
  crates/re_renderer/README.md
  crates/re_renderer/build.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view_spatial/src/space_camera_3d.rs
  crates/re_time_panel/src/lib.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/rerun/src/run.rs
  design/batching.md
  design/blueprint_store.md
  docs/content/concepts/spaces-and-transforms.md
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/logging-rust.md
  docs/content/howto/ros2-nav-turtlebot.md
  examples/rust/template/src/main.rs
  scripts/lint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3093 Fix crash on reaching line number limit
  crates/re_log/src/lib.rs
  crates/re_log/src/result_extensions.rs
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/resource_managers/resource_manager.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_types/source_hash.txt
Labels: 🔺 re_renderer, 💣 crash

#3101 Update resolved analytics URL
  crates/re_analytics/src/sink_native.rs
Labels: 📊 analytics

#3108 Optimize big point clouds by ~20%
  Cargo.lock
  crates/re_arrow_store/src/store_read.rs
  crates/re_query/src/archetype_view.rs
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/lib.rs
Labels: 📺 re_viewer, 📉 performance

#3115 A better Rust interface for `Color` datatype and component
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/src/components/color_ext.rs
  crates/re_types/src/datatypes/color_ext.rs
  crates/re_viewer_context/src/annotations.rs
  examples/rust/raw_mesh/src/main.rs
  rerun_py/src/python_bridge.rs
Labels: 🦀 rust SDK

#3114 A nice speed up of 3D points clouds by ~69%
  .cargo/config.toml
  Cargo.lock
  crates/re_query/src/archetype_view.rs
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/contexts/annotation_context.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/lib.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_ws_comms/src/client.rs
Labels: 📺 re_viewer, 📉 performance

#3123 Make `custom_space_view` example more verbose
  examples/rust/custom_space_view/src/main.rs
Labels: examples

#3130 Handle serde-field that fails to deserialize
  crates/re_log_types/src/serde_field.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🟦 blueprint

#3078 Improve performance for many entities
  Cargo.lock
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/src/contexts/annotation_context.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_spatial/src/parts/transform3d_arrows.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_space_view_text/src/space_view_class.rs
  crates/re_space_view_text/src/view_part_system.rs
  crates/re_space_view_text_box/src/view_part_system.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/named_system.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/blueprint_components/space_view.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
  rerun_py/src/python_bridge.rs
Labels: 📺 re_viewer, 📉 performance

#3121 Inject marker components
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/archetypes/fuzzy.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
  rerun_cpp/src/rerun/archetypes/annotation_context.cpp
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d.cpp
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/disconnected_space.cpp
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.cpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.cpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/points2d.cpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.cpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.cpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/arrow.cpp
  rerun_cpp/src/rerun/arrow.hpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer1.cpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer1.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/log.py
Labels: 🐍 python API, 🏹 arrow, 🦀 rust SDK, 🔍 re_query, C/C++ SDK

#3131 Support loading images and meshes on web
  Cargo.lock
  crates/re_components/src/lib.rs
  crates/re_components/src/load_file.rs
  crates/re_data_source/Cargo.toml
  crates/re_data_source/src/data_source.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_sdk/src/msg_sender.rs
  crates/re_viewer/src/app.rs
  crates/rerun/Cargo.toml
Labels: 🕸️ web, 📺 re_viewer

#3132 Fix the 3d space view's tooltip help text
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: ui, 🏎️ Quick Issue

#3117 Improve size tracking table
  .github/workflows/reusable_track_size.yml
  scripts/ci/sizes.py
Labels: 🧑‍💻 dev experience

#3136 Fix hot repaint: run pending commands _last_, skip request_repaint()
  crates/re_viewer/src/app.rs
Labels: 🪳 bug, 📉 performance, exclude from changelog

#3140 Change paper visualizations url
  examples/manifest.yml
Labels: examples, exclude from changelog

#3143 Remove `setup-rust` from toml lint job
  .github/workflows/reusable_checks.yml
Labels: 🧑‍💻 dev experience

#3118 Use `ListItem` in blueprint tree UI
  crates/re_data_ui/src/item_ui.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui

#3137 Fix bug in `ReceiveSet`: drop disconnected receivers
  crates/re_smart_channel/src/lib.rs
  crates/re_smart_channel/src/receive_set.rs
  crates/re_smart_channel/src/receiver.rs
  crates/re_smart_channel/src/sender.rs
  crates/re_viewer/src/app_state.rs
Labels: 🪳 bug, exclude from changelog

#3145 Add `rerun reset` command
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/Cargo.toml
  crates/re_data_ui/src/image.rs
  crates/re_space_view_bar_chart/Cargo.toml
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/saving.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/rerun/src/run.rs
  docs/content/getting-started/troubleshooting.md
Labels: 📺 re_viewer

#3151 Render demo manifest
  scripts/ci/build_demo_app.py
  scripts/ci/demo_assets/templates/example.html
  scripts/ci/requirements.txt
Labels: 🧑‍💻 dev experience

#3149 Fix log spam during data store tests
  crates/re_arrow_store/src/store_write.rs
Labels: ⛃ re_datastore, exclude from changelog

#3134 Warn if using software rasterizer (lavapipe or llvmpipe)
  crates/re_viewer/src/native.rs
  docs/content/getting-started/troubleshooting.md
Labels: 🔺 re_renderer, 🐧 linux

#3155 Use `ehttp` in `re_analytics`
  Cargo.lock
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_analytics/src/lib.rs
  crates/re_analytics/src/native/config.rs
  crates/re_analytics/src/native/mod.rs
  crates/re_analytics/src/native/pipeline.rs
  crates/re_analytics/src/native/sink.rs
  crates/re_analytics/src/sink_web.rs
  crates/re_analytics/src/web/config.rs
  crates/re_analytics/src/web/mod.rs
  crates/re_analytics/src/web/pipeline.rs
  crates/re_analytics/src/web/sink.rs
  crates/re_log/src/lib.rs
  crates/re_log_encoding/Cargo.toml
  crates/re_types/source_hash.txt
Labels: 📺 re_viewer, 📊 analytics

#3160 Bug fix: `cargo rerun websocket-url`
  crates/rerun/src/run.rs
Labels: 🪳 bug, exclude from changelog

#3051 Change the "slow-down-camera" modifier to Alt on non-Mac
  crates/re_space_view/src/controls.rs
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: ui, 📺 re_viewer

#3161 Turn on garbage-collection (`--memory-limit`) by default
  crates/re_log_types/src/data_cell.rs
  crates/re_memory/src/memory_limit.rs
  crates/re_memory/src/ram_warner.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_sdk_comms/src/tcp_client.rs
  crates/re_viewer/src/app.rs
  crates/rerun/src/run.rs
  docs/content/howto/limit-ram.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/live_camera_edge_detection/main.py
  examples/python/live_depth_sensor/README.md
  examples/python/live_depth_sensor/main.py
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📺 re_viewer, 📉 performance

#3172 Run all Python doc examples in CI
  crates/re_types/source_hash.txt
  docs/code-examples/annotation_context_connections.py
  docs/code-examples/transform3d_simple_v2.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/transform3d.py
  scripts/run_python_e2e_test.py
Labels: 🔨 testing, 🐍 python API

#3176 Update webpki: https://rustsec.org/advisories/RUSTSEC-2023-0052
  Cargo.lock
Labels: dependencies
