Repository rerun-io/rerun, pull requests merged in 2023-09, with the labels that each got.

#3169 Clamp time panel height to avoid visual glitches
  crates/re_time_panel/src/lib.rs
Labels: 🪳 bug, ui

#3182 Add `DrawOrder` component to `Image` archetype
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/image.rs
  crates/re_types/src/archetypes/image_ext.rs
  crates/re_types/tests/image.rs
  rerun_cpp/src/rerun/archetypes/image.cpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/image.py
Labels: 🐍 python API, 🦀 rust SDK, 🍏 primitives, C/C++ SDK

#3181 Fix update PR body script
  scripts/ci/update_pr_body.py
Labels: 🧑‍💻 dev experience

#3153 Use `ListItem` in Stream Tree UI
  crates/re_data_ui/src/item_ui.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui

#3171 Limit the size of component tooltips with `UiVerbosity::Reduced`
  crates/re_data_ui/src/component.rs
Labels: enhancement, ui

#3186 Add missing title to `manifest.json`
  scripts/ci/build_demo_app.py
Labels: 🪳 bug

#3166 Web analytics
  .vscode/settings.json
  crates/re_analytics/src/cli.rs
  crates/re_analytics/src/event.rs
  crates/re_analytics/src/lib.rs
  crates/re_analytics/src/native/config.rs
  crates/re_analytics/src/native/pipeline.rs
  crates/re_analytics/src/native/sink.rs
  crates/re_analytics/src/web/config.rs
  crates/re_analytics/src/web/mod.rs
  crates/re_analytics/src/web/pipeline.rs
  crates/re_analytics/src/web/sink.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
  rerun_py/rerun_sdk/rerun/recording.py
  scripts/ci/demo_assets/static/index.js
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 🕸️ web, 📊 analytics

#3188 Introduce IDL-based Tensor/Image APIs for python.
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_data.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_id.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  docs/code-examples/image_simple_v2.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/tensor_data.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/tensor_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_data.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_id.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/tests/unit/test_image.py
  rerun_py/tests/unit/test_tensor.py
Labels: 🐍 python API, codegen/idl

#3195 Add an aspect ratio check to `upload_image.py`
  examples/python/detect_and_track_objects/README.md
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3199 Activate recording when openening via file dialog
  CHANGELOG.md
  crates/re_viewer/src/app.rs
Labels: 🪳 bug, 📺 re_viewer

#3203 Round-trip test for tensors
  Cargo.lock
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/image_ext.rs
  crates/re_types/src/datatypes/tensor_data_ext.rs
  crates/re_types/tests/image.rs
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/tensor_data.py
  rerun_py/tests/unit/test_image.py
  scripts/ci/run_e2e_roundtrip_tests.py
  tests/cpp/roundtrips/tensor/main.cpp
  tests/python/roundtrips/image/main.py
  tests/python/roundtrips/tensor/main.py
  tests/rust/roundtrips/image/Cargo.toml
  tests/rust/roundtrips/image/src/main.rs
  tests/rust/roundtrips/tensor/Cargo.toml
  tests/rust/roundtrips/tensor/src/main.rs
Labels: codegen/idl

#3205 Fix the manual_release.yml deploy script
  .github/workflows/manual_release.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3201 Move example description to README frontmatter
  .github/workflows/reusable_checks.yml
  examples/python/arkit_scenes/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/dna/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/plots/README.md
  examples/python/structure_from_motion/README.md
  examples/python/template/README.md
  scripts/ci/build_demo_app.py
  scripts/lint.py
  scripts/requirements-dev.txt
Labels: 🕸️ web, 🧑‍💻 dev experience

#3209 Fix instantiateStreaming usage on web
  scripts/ci/demo_assets/static/index.js
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 🕸️ web

#3215 Update `CHANGELOG` with `0.8.2` release
  CHANGELOG.md
Labels: ⛴ release, exclude from changelog

#3218 Fix bbox for line-strip-3d
  crates/re_space_view_spatial/src/parts/lines3d.rs
Labels: exclude from changelog

#3211 Add how-to guide for clearing entities
  docs/content/howto/short-lived-entities.md
  docs/cspell.json
Labels: 📖 documentation

#3214 Improve output from `crates.py publish`
  scripts/ci/crates.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3227 Show picking position when hovering something in the spatial view
  crates/re_space_view_spatial/src/ui.rs
Labels: 📺 re_viewer

#3191 Add Examples page to the Welcome Screen
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/data/examples_manifest.json
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/wait_screen_ui.rs
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
Labels: enhancement, ui

#3219 `Welcome Page` refresh
  crates/re_ui/data/images/onboarding-configure.png
  crates/re_ui/data/images/onboarding-examples.jpg
  crates/re_ui/data/images/onboarding-live-data.png
  crates/re_ui/data/images/onboarding-recorded-data.png
  crates/re_ui/data/images/welcome_screen_configure.png
  crates/re_ui/data/images/welcome_screen_live_data.png
  crates/re_ui/data/images/welcome_screen_recorded_data.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/data/examples_manifest.json
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
Labels: ui

#3241 [bugfix] Allow user to edit colormap for depth images
  crates/re_viewer/src/ui/selection_panel.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#3245 Clean up intra-workspace dependencies
  Cargo.lock
  crates/re_components/Cargo.toml
  crates/re_data_ui/Cargo.toml
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_text/Cargo.toml
  crates/re_space_view_text_document/Cargo.toml
  crates/re_string_interner/src/lib.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer_context/Cargo.toml
  crates/re_viewport/Cargo.toml
  docs/code-examples/Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  tests/rust/roundtrips/image/Cargo.toml
  tests/rust/roundtrips/text_document/Cargo.toml
Labels: exclude from changelog

#3259 Fix typo: recoding -> recording in how-to guide
  docs/content/howto/short-lived-entities.md
Labels: 🪳 bug, 📖 documentation, exclude from changelog

#3251 First-class indicator components for Rust
  crates/re_components/src/lib.rs
  crates/re_components/src/load_file.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view_text_document/src/view_part_system.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetype.rs
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/image.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/segmentation_image.rs
  crates/re_types/src/archetypes/tensor.rs
  crates/re_types/src/archetypes/text_document.rs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/loggable.rs
  crates/re_types/src/loggable_batch.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer1.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  docs/code-examples/annotation_context_rects.rs
  docs/code-examples/box3d_simple.rs
  docs/code-examples/depth_image_3d.rs
  docs/code-examples/line_segments2d_simple.rs
  docs/code-examples/line_strip2d_batch.rs
  docs/code-examples/line_strip2d_simple.rs
  docs/code-examples/mesh_simple.rs
  docs/code-examples/pinhole_simple.rs
  docs/code-examples/point2d_random.rs
  docs/code-examples/point2d_simple.rs
  docs/code-examples/rect2d_simple.rs
  docs/code-examples/scalar_simple.rs
  examples/rust/clock/src/main.rs
  examples/rust/custom_data/src/main.rs
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
  examples/rust/objectron/src/main.rs
  examples/rust/raw_mesh/src/main.rs
  tests/rust/roundtrips/line_strips2d/src/main.rs
  tests/rust/roundtrips/points2d/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 🏹 arrow, 🦀 rust SDK

#3280 Remove `publish_crates.sh`
  scripts/publish_crates.sh
Labels: exclude from changelog

#3281 Fix lurking bug in datastore bucket sorting routines
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/data_store.rs
Labels: 🪳 bug, ⛃ re_datastore

#3289 Document our encoding of `Color` datatype and component
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/datatypes/color.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/color.rs
  crates/re_types/src/datatypes/color.rs
  rerun_cpp/src/rerun/components/color.hpp
  rerun_cpp/src/rerun/datatypes/color.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/color.py
Labels: 📖 documentation, exclude from changelog

#3286 Deterministically seed Python RNGs for all rerun examples
  examples/python/dna/main.py
  examples/python/plots/main.py
  rerun_py/rerun_sdk/rerun/__init__.py
  tests/python/test_api/main.py
Labels: examples, exclude from changelog

#3288 Fix row ordering flakiness when using clear APIs
  crates/re_data_store/src/store_db.rs
  crates/re_log_types/src/data_row.rs
  crates/re_tuid/src/lib.rs
Labels: 🪳 bug, ⛃ re_datastore

#3295 Improve viewport tile behavior
  Cargo.lock
  Cargo.toml
  crates/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, ui, dependencies

#3293 Boxes2D archetype unit tests
  crates/re_types/tests/box2d.rs
  rerun_cpp/tests/archetypes/boxes2d.cpp
  rerun_py/tests/unit/test_box2d.py
Labels: 🔨 testing, 🍏 primitives, exclude from changelog

#3291 Implement `Clear` archetype for all SDKs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/archetypes/clear.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/clear_settings.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/clear.rs
  crates/re_types/src/archetypes/clear_ext.rs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/components/clear_settings.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/tests/clear.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/clear_recursive.cpp
  docs/code-examples/clear_recursive.py
  docs/code-examples/clear_recursive.rs
  docs/code-examples/clear_simple.cpp
  docs/code-examples/clear_simple.py
  docs/code-examples/clear_simple.rs
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/clear.cpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/archetypes/clear_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/clear_settings.cpp
  rerun_cpp/src/rerun/components/clear_settings.hpp
  rerun_cpp/tests/archetypes/clear.cpp
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/clear_settings.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/clear_settings.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/rerun_sdk/rerun/log/clear.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_clear.py
  tests/roundtrips.py
  tests/rust/test_api/src/main.rs
Labels: 🐍 python API, 🏹 arrow, 🦀 rust SDK, codegen/idl, C/C++ SDK

#3308 Fix `Mat3x3` defaulting to zero
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_types/definitions/rerun/components/class_id.fbs
  crates/re_types/definitions/rerun/components/color.fbs
  crates/re_types/definitions/rerun/components/half_sizes2d.fbs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types/definitions/rerun/components/keypoint_id.fbs
  crates/re_types/definitions/rerun/components/origin2d.fbs
  crates/re_types/definitions/rerun/components/origin3d.fbs
  crates/re_types/definitions/rerun/components/point2d.fbs
  crates/re_types/definitions/rerun/components/point3d.fbs
  crates/re_types/definitions/rerun/components/vector3d.fbs
  crates/re_types/definitions/rerun/datatypes/color.fbs
  crates/re_types/definitions/rerun/datatypes/mat3x3.fbs
  crates/re_types/definitions/rerun/datatypes/mat4x4.fbs
  crates/re_types/definitions/rerun/datatypes/scalars.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/half_sizes2d.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/origin2d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/point2d.rs
  crates/re_types/src/components/point3d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/datatypes/color.rs
  crates/re_types/src/datatypes/float32.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/transform3d_ext.rs
  crates/re_types_builder/src/codegen/rust/api.rs
Labels: 🪳 bug, codegen/idl, exclude from changelog

#3307 Show currently loading recordings in Recordings menu
  crates/re_renderer/examples/framework.rs
  crates/re_smart_channel/src/receive_set.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer_context/src/store_context.rs
  crates/re_ws_comms/src/server.rs
Labels: ui, 📺 re_viewer

#3310 Always codegen queries that contain `InstanceKey`
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/boxes2d.rs
  crates/re_types/src/archetypes/clear.rs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/image.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/segmentation_image.rs
  crates/re_types/src/archetypes/tensor.rs
  crates/re_types/src/archetypes/text_document.rs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer1.rs
  crates/re_types_builder/src/codegen/rust/api.rs
Labels: 🪳 bug, 🔍 re_query, 💣 crash, 🦟 regression

#3303 Create objects for delegating components
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/text_log_level.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer1.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer14.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer15.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer19.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer2.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer20.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer3.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer4.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer5.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer6.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/class_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/color.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/half_sizes2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/keypoint_id.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/origin2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/origin3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/point3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/tensor_data.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/text.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/text_log_level.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/text_log_level_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/transform3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/vector3d.py
Labels: 🐍 python API, codegen/idl

#3315 Remove debug print
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/color_ext.py
Labels: exclude from changelog

#3311 Update to latest egui + use new Image api
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/command.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_ui/src/static_image_cache.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, 📺 re_viewer, 🚜 refactor

#3314 Speed up startup of viewer
  Cargo.lock
  crates/re_data_source/src/data_source.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_memory/Cargo.toml
  crates/re_memory/src/ram_warner.rs
  crates/re_sdk_comms/Cargo.toml
  crates/re_tracing/src/server.rs
  crates/re_types/source_hash.txt
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/src/run.rs
Labels: 📺 re_viewer, 📉 performance, exclude from changelog

#3319 Fix Boxes2D system still expecting Origin2D
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_types/src/components/half_sizes2d_ext.rs
Labels: 🪳 bug, exclude from changelog

#3316 Migrate all the components to new `_ext.py` system
  crates/re_types/source_hash.txt
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/clear_settings.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/depth_meter.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/disconnected_space.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/draw_order.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/instance_key.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/line_strip2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/line_strip3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/radius.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/annotation_context_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/clear_settings.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/clear_settings_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/depth_meter.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/depth_meter_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/disconnected_space.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/disconnected_space_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/draw_order_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/instance_key_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/line_strip2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/line_strip2d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/line_strip3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/line_strip3d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/radius_ext.py
Labels: 🐍 python API, codegen/idl

#3317 Migrate all the archetypes to new `_ext.py` system
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/depth_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/segmentation_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/depth_image_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/segmentation_image_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/class_description.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/color.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/mat4x4.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/translation_rotation_scale3d.py
Labels: 🐍 python API, codegen/idl

#3321 Get rid of spurious warning and creating of TextDocumentView when using TextLogs
  Cargo.lock
  crates/re_space_view_text_document/Cargo.toml
  crates/re_space_view_text_document/src/view_part_system.rs
Labels: 🪳 bug, 📺 re_viewer

#3318 Now that types have been migrated, remove the old overrides implementation.
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/rerun_sdk/rerun/_rerun2/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/_overrides/__init__.py
Labels: 🐍 python API, codegen/idl

#3324 Better naming of things to help diagnose #3242
  crates/re_renderer/src/transform.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: 🚜 refactor, exclude from changelog

#3322 Update all uses of `actions/checkout` to use explicit `ref`
  .github/workflows/checkboxes.yml
  .github/workflows/documentation.yaml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_track_size.yml
  .github/workflows/reusable_update_pr_body.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_web_demo.yml
  .github/workflows/reusable_upload_wheels.yml
Labels: 🧑‍💻 dev experience

#3326 Python rotation3d array serialization
  crates/re_types/source_hash.txt
  rerun_py/rerun_sdk/rerun/_rerun2/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_rerun2/_unions.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/angle_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/quaternion.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/quaternion_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation3d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/rotation_axis_angle_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_data_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/transform3d_ext.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_rotation3d.py
Labels: 🐍 python API, codegen/idl, exclude from changelog

#3328 Update to latest egui
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewport/src/viewport.rs
Labels: dependencies, exclude from changelog

#3323 Rethink view selection & filtering + make all views opt-in
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/src/contexts/annotation_context.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_spatial/src/parts/transform3d_arrows.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_space_view_text_document/src/view_part_system.rs
  crates/re_space_view_text_log/src/view_part_system.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_types/src/archetype.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/loggable.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewport/src/space_view_heuristics.rs
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
Labels: 📺 re_viewer, 🍏 primitives

#3331 Fix Boxes2D view not processing annotation labels
  crates/re_space_view_spatial/src/parts/boxes2d.rs
Labels: ui, 📺 re_viewer

#3333 Hide stream view and selection view in welcome app
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/store_hub.rs
Labels: ui, 📺 re_viewer

#3329 Onboarding screen: better margin, and shrink images to fit buttons
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#3343 Markdown support in `TextDocument`
  Cargo.lock
  Cargo.toml
  crates/re_space_view_text_document/Cargo.toml
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_document/src/view_part_system.rs
  crates/re_string_interner/src/lib.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes/text_document.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/media_type.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/text_document.rs
  crates/re_types/src/components/media_type.rs
  crates/re_types/src/components/media_type_ext.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/tests/text_document.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewport/src/space_info.rs
  crates/re_viewport/src/space_view_heuristics.rs
  docs/code-examples/text_document.cpp
  docs/code-examples/text_document.py
  docs/code-examples/text_document.rs
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes/text_document.cpp
  rerun_cpp/src/rerun/archetypes/text_document.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/media_type.cpp
  rerun_cpp/src/rerun/components/media_type.hpp
  rerun_cpp/src/rerun/components/media_type_ext.cpp
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/media_type.py
  tests/cpp/roundtrips/text_document/main.cpp
  tests/python/roundtrips/text_document/main.py
  tests/rust/roundtrips/text_document/src/main.rs
Labels: enhancement, 📺 re_viewer

#3352 Fix incorrect propagation of field's nullability into its inner list
  crates/re_types/source_hash.txt
  crates/re_types/src/testing/components/affix_fuzzer1.rs
  crates/re_types/src/testing/components/affix_fuzzer11.rs
  crates/re_types/src/testing/components/affix_fuzzer13.rs
  crates/re_types/src/testing/components/affix_fuzzer17.rs
  crates/re_types/src/testing/components/affix_fuzzer18.rs
  crates/re_types/src/testing/components/affix_fuzzer2.rs
  crates/re_types/src/testing/components/affix_fuzzer3.rs
  crates/re_types/src/testing/components/affix_fuzzer4.rs
  crates/re_types/src/testing/components/affix_fuzzer5.rs
  crates/re_types/src/testing/components/affix_fuzzer6.rs
  crates/re_types/src/testing/components/affix_fuzzer7.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer1.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer4.rs
  crates/re_types_builder/src/arrow_registry.rs
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer11.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer13.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer16.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer17.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer18.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer7.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer1.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer3.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer4.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer5.py
Labels: 🪳 bug, 🔨 testing, 🏹 arrow

#3345 Web-Viewer: Don't auto-connect to `wss://hostname` when an `?url=` is missing
  crates/re_viewer/src/web.rs
  scripts/ci/demo_assets/static/index.js
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 🕸️ web

#3346 Fix forced sink race
  crates/re_log_encoding/src/file_sink.rs
  crates/re_sdk/src/recording_stream.rs
Labels: 🪳 bug, C/C++ SDK

#3340 Introduce `as_components` interface for Python APIs
  Cargo.lock
  crates/re_sdk/src/demo_util.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/python.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/custom_data.py
  docs/code-examples/custom_data.rs
  docs/code-examples/roundtrips.py
  examples/rust/custom_data/Cargo.toml
  examples/rust/custom_data/README.md
  rerun_py/rerun_sdk/rerun/_rerun2/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/affix_fuzzer1.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/disconnected_space.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/translation_and_mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/translation_rotation_scale3d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/log.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/rerun_sdk/rerun/log/lines.py
  rerun_py/rerun_sdk/rerun/log/points.py
  rerun_py/rerun_sdk/rerun/log/rects.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_arrows3d.py
  rerun_py/tests/unit/test_box2d.py
  rerun_py/tests/unit/test_box3d.py
  rerun_py/tests/unit/test_line_strips2d.py
  rerun_py/tests/unit/test_line_strips3d.py
  rerun_py/tests/unit/test_points2d.py
  rerun_py/tests/unit/test_points3d.py
Labels: 🐍 python API, codegen/idl

#3350 CODE_STYLE.md: profess love for Json, Toml, and snake_case
  CODE_STYLE.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#3332 Generate manifest for examples page in viewer
  .github/workflows/README.md
  .github/workflows/manual_adhoc_web.yml
  .github/workflows/manual_build_release.yml
  .github/workflows/manual_dispatch.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_web_demo.yml
  Cargo.lock
  crates/re_viewer/Cargo.toml
  crates/re_viewer/build.rs
  crates/re_viewer/data/examples_manifest.json
  examples/python/arkit_scenes/README.md
  examples/python/car/README.md
  examples/python/clock/README.md
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/differentiable_blocks_world/README.md
  examples/python/dna/README.md
  examples/python/face_tracking/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/limap/README.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/live_depth_sensor/README.md
  examples/python/mcc/README.md
  examples/python/minimal/README.md
  examples/python/multiprocessing/README.md
  examples/python/multithreading/README.md
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/ros_node/README.md
  examples/python/segment_anything_model/README.md
  examples/python/shape_pointe/README.md
  examples/python/signed_distance_fields/README.md
  examples/python/simplerecon/README.md
  examples/python/slahmr/README.md
  examples/python/structure_from_motion/README.md
  examples/python/tapir/README.md
  examples/python/text_logging/README.md
  examples/python/widebaseline/README.md
  scripts/ci/thumbnails.py
Labels: 🧑‍💻 dev experience, examples

#3348 Box2D/3D Python __init__ extension
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_viewer/data/examples_manifest.json
  docs/code-examples/annotation_context_rects.py
  docs/code-examples/annotation_context_rects.rs
  docs/code-examples/box2d_simple.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/boxes2d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/boxes3d_ext.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/image.py
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/log/bounding_box.py
  rerun_py/rerun_sdk/rerun/log/rects.py
  rerun_py/tests/unit/test_box2d.py
  rerun_py/tests/unit/test_box3d.py
Labels: 🐍 python API

#3359 Sort example manifest
  crates/re_viewer/build.rs
  crates/re_viewer/data/examples_manifest.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#3351 Fill in remaining C++ samples and tests that were blocked by lack of Box2D
  crates/re_types/definitions/rerun/archetypes/annotation_context.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/boxes3d.rs
  docs/code-examples/annotation_context_rects.cpp
  docs/code-examples/box3d_batch.cpp
  docs/code-examples/box3d_batch.rs
  docs/code-examples/box3d_simple.cpp
  docs/code-examples/line_segments2d_simple.cpp
  docs/code-examples/line_strip2d_batch.cpp
  docs/code-examples/line_strip2d_simple.cpp
  docs/code-examples/point2d_random.cpp
  docs/code-examples/point2d_simple.cpp
  docs/code-examples/roundtrips.py
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/components/rotation3d_ext.cpp
  rerun_cpp/src/rerun/datatypes/rotation3d.hpp
  rerun_cpp/src/rerun/datatypes/rotation3d_ext.cpp
  tests/cpp/roundtrips/line_strips2d/main.cpp
  tests/cpp/roundtrips/line_strips3d/main.cpp
  tests/cpp/roundtrips/points2d/main.cpp
  tests/roundtrips.py
Labels: 📖 documentation, 🔨 testing, C/C++ SDK

#3365 Double-click to toggle list items
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
Labels: ui, exclude from changelog

#3368 Speed up Python codegen by running black/ruff on a directory of files
  Cargo.lock
  crates/re_types/source_hash.txt
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/lib.rs
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer3.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_buffer.py
Labels: 📉 performance, codegen/idl, exclude from changelog

#3344 Switch to Vimeo for paper visualizations
  examples/python/differentiable_blocks_world/README.md
  examples/python/limap/README.md
  examples/python/mcc/README.md
  examples/python/shape_pointe/README.md
  examples/python/simplerecon/README.md
  examples/python/slahmr/README.md
  examples/python/tapir/README.md
  examples/python/widebaseline/README.md
Labels: enhancement, examples, exclude from changelog

#3356 Re-enable F16 Support for Images
  Cargo.lock
  crates/re_data_ui/src/image.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_types/.gitattributes
  crates/re_types/Cargo.toml
  crates/re_types/definitions/rerun/attributes.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/re_types/definitions/rerun/testing/archetypes/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/components/fuzzy.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/depth_image_ext.rs
  crates/re_types/src/archetypes/image_ext.rs
  crates/re_types/src/archetypes/segmentation_image_ext.rs
  crates/re_types/src/archetypes/tensor_ext.rs
  crates/re_types/src/datatypes/tensor_buffer.rs
  crates/re_types/src/datatypes/tensor_buffer_ext.rs
  crates/re_types/src/datatypes/tensor_data_ext.rs
  crates/re_types/src/image.rs
  crates/re_types/src/tensor_data.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer1.rs
  crates/re_types/src/testing/components/affix_fuzzer21.rs
  crates/re_types/src/testing/components/mod.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer21.rs
  crates/re_types/src/testing/datatypes/mod.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/cpp/array_builder.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/tensor/tensor_stats.rs
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/datatypes/tensor_buffer.cpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer1.cpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer1.hpp
  rerun_cpp/tests/generated/components.hpp
  rerun_cpp/tests/generated/components/affix_fuzzer21.cpp
  rerun_cpp/tests/generated/components/affix_fuzzer21.hpp
  rerun_cpp/tests/generated/datatypes.hpp
  rerun_cpp/tests/generated/datatypes/affix_fuzzer21.cpp
  rerun_cpp/tests/generated/datatypes/affix_fuzzer21.hpp
  rerun_py/rerun_sdk/rerun/_rerun2/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/archetypes/affix_fuzzer1.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/components/affix_fuzzer21.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer21.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/affix_fuzzer3.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/_rerun2/datatypes/tensor_data.py
  tests/python/roundtrips/image/main.py
  tests/python/test_api/main.py
  tests/rust/roundtrips/image/Cargo.toml
  tests/rust/roundtrips/image/src/main.rs
Labels: codegen/idl

#3371 Keep track of how files where sources for analytics and UI
  crates/re_data_source/src/data_source.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/src/run.rs
Labels: 📊 analytics

#3369 CI: Check that a clean checkout can build `rerun` with just `cargo`
  .github/workflows/on_push_main.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3376 Rust 1.72.1 and rerunio/docker_ci 0.9.1
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_upload_wheels.yml
  BUILD.md
  ci_docker/Dockerfile
  ci_docker/publish.sh
  rerun_py/README.md
  rust-toolchain
  scripts/setup.sh
Labels: 🦀 rust SDK, 🧑‍💻 dev experience

#3364 Fix post-GC purging of streams view time histogram
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_crash_handler/src/lib.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_int_histogram/src/tree.rs
  crates/re_log_types/src/time_point/timeline.rs
  crates/re_time_panel/src/lib.rs
  examples/python/live_camera_edge_detection/main.py
  examples/python/notebook/blueprint.ipynb
  examples/python/notebook/cube.ipynb
Labels: 🪳 bug, 📺 re_viewer

#3377 Optimize out unnecessary joins when querying archetypes
  crates/re_log_types/src/data_cell.rs
  crates/re_query/src/archetype_view.rs
Labels: 📺 re_viewer, 📉 performance

#3385 Clarify matrix storage, improve Python API, add Python matrix array serializers
  crates/re_types/definitions/rerun/datatypes/mat3x3.fbs
  crates/re_types/definitions/rerun/datatypes/mat4x4.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  rerun_cpp/src/rerun/datatypes/mat3x3.cpp
  rerun_cpp/src/rerun/datatypes/mat3x3.hpp
  rerun_cpp/src/rerun/datatypes/mat3x3_ext.cpp
  rerun_cpp/src/rerun/datatypes/mat4x4.cpp
  rerun_cpp/src/rerun/datatypes/mat4x4.hpp
  rerun_cpp/src/rerun/datatypes/mat4x4_ext.cpp
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  rerun_py/tests/unit/test_matnxn.py
Labels: 📖 documentation, 🐍 python API

#3373 Fix colormap picker preview & show it for depth point clouds as well
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: 🪳 bug, enhancement, 📺 re_viewer

#3390 Introduce ViewCoordinates archetype
  Cargo.lock
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/archetypes/view_coordinates.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/view_coordinates.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/view_coordinates.rs
  crates/re_types/src/archetypes/view_coordinates_ext.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/view_coordinates.rs
  crates/re_types/src/components/view_coordinates_ext.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/view_coordinates.rs
  crates/re_types/tests/view_coordinates.rs
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/view_coordinates.cpp
  rerun_cpp/src/rerun/archetypes/view_coordinates.hpp
  rerun_cpp/src/rerun/archetypes/view_coordinates_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/view_coordinates.cpp
  rerun_cpp/src/rerun/components/view_coordinates.hpp
  rerun_cpp/src/rerun/components/view_coordinates_ext.cpp
  rerun_cpp/tests/archetypes/view_coordinates.cpp
  rerun_py/rerun_sdk/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer3.py
  rerun_py/tests/unit/test_view_coordinates.py
  scripts/generate_view_coordinate_defs.py
  tests/cpp/roundtrips/view_coordinates/main.cpp
  tests/python/roundtrips/view_coordinates/main.py
  tests/rust/roundtrips/view_coordinates/Cargo.toml
  tests/rust/roundtrips/view_coordinates/src/main.rs
Labels: codegen/idl

#3396 Generate `impl From` for trivial tuple types
  crates/re_query/src/dataframe_util.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/components/clear_settings.rs
  crates/re_types/src/components/depth_meter.rs
  crates/re_types/src/components/depth_meter_ext.rs
  crates/re_types/src/components/disconnected_space.rs
  crates/re_types/src/components/disconnected_space_ext.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/draw_order_ext.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/instance_key_ext.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/radius_ext.rs
  crates/re_types/src/components/view_coordinates.rs
  crates/re_types/src/datatypes/class_id.rs
  crates/re_types/src/datatypes/class_id_ext.rs
  crates/re_types/src/datatypes/color.rs
  crates/re_types/src/datatypes/color_ext.rs
  crates/re_types/src/datatypes/float32.rs
  crates/re_types/src/datatypes/keypoint_id.rs
  crates/re_types/src/datatypes/keypoint_id_ext.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/mesh_properties.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/utf8.rs
  crates/re_types/src/datatypes/uvec2d.rs
  crates/re_types/src/datatypes/uvec2d_ext.rs
  crates/re_types/src/datatypes/uvec3d.rs
  crates/re_types/src/datatypes/uvec3d_ext.rs
  crates/re_types/src/datatypes/uvec4d.rs
  crates/re_types/src/datatypes/uvec4d_ext.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec2d_ext.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec3d_ext.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/datatypes/vec4d_ext.rs
  crates/re_types/src/testing/components/affix_fuzzer10.rs
  crates/re_types/src/testing/components/affix_fuzzer11.rs
  crates/re_types/src/testing/components/affix_fuzzer12.rs
  crates/re_types/src/testing/components/affix_fuzzer13.rs
  crates/re_types/src/testing/components/affix_fuzzer8.rs
  crates/re_types/src/testing/components/affix_fuzzer9.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer2.rs
  crates/re_types/src/testing/datatypes/flattened_scalar.rs
  crates/re_types/src/testing/datatypes/primitive_component.rs
  crates/re_types/src/testing/datatypes/string_component.rs
  crates/re_types_builder/src/codegen/rust/api.rs
Labels: 🦀 rust SDK, codegen/idl, exclude from changelog

#3403 Force each PR to opt-in to or opt-out of the changelog
  .github/workflows/labels.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3404 Enforce TODO formatting
  crates/re_query/src/archetype_view.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_spatial/src/space_camera_3d.rs
  crates/re_types/definitions/rerun/components/view_coordinates.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  docs/content/reference/viewer/viewport.md
  examples/python/arkit_scenes/main.py
  examples/python/depth_guided_stable_diffusion/huggingface_pipeline.py
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/log_deprecated/scalar.py
  rerun_py/rerun_sdk/rerun_demo/__main__.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer3.py
  scripts/generate_view_coordinate_defs.py
  scripts/lint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3397 `TimeSeriesScalar` archetype
  Cargo.lock
  crates/re_components/src/lib.rs
  crates/re_components/src/scalar.rs
  crates/re_sdk/src/lib.rs
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/archetypes/time_series_scalar.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/scalar.fbs
  crates/re_types/definitions/rerun/components/scalar_scattering.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/time_series_scalar.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/scalar.rs
  crates/re_types/src/components/scalar_ext.rs
  crates/re_types/src/components/scalar_scattering.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/roundtrips.py
  docs/code-examples/scalar_multiple_plots.py
  docs/code-examples/scalar_multiple_plots.rs
  docs/code-examples/scalar_simple.py
  docs/code-examples/scalar_simple.rs
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.cpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/scalar.cpp
  rerun_cpp/src/rerun/components/scalar.hpp
  rerun_cpp/src/rerun/components/scalar_scattering.cpp
  rerun_cpp/src/rerun/components/scalar_scattering.hpp
  rerun_cpp/src/rerun/components/view_coordinates.hpp
  rerun_cpp/src/rerun/components/view_coordinates_ext.cpp
  rerun_py/rerun_sdk/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/_rerun2/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/scalar.py
  rerun_py/rerun_sdk/rerun/components/scalar_ext.py
  rerun_py/rerun_sdk/rerun/components/scalar_scattering.py
  rerun_py/rerun_sdk/rerun/components/scalar_scattering_ext.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/rerun_sdk/rerun/log_deprecated/scalar.py
  rerun_py/src/python_bridge.rs
  tests/roundtrips.py
Labels: 🐍 python API, 🦀 rust SDK, 🍏 primitives, C/C++ SDK, include in changelog

#3407 Fix cargo doc race condition
  .github/workflows/reusable_checks.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3401 Fix `transform3d_simple` and reenable roundtrip test
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/transform3d.rs
  docs/code-examples/roundtrips.py
  docs/code-examples/transform3d_simple.py
  docs/code-examples/transform3d_simple.rs
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
Labels: 🔨 testing, examples

#3405 Hunting down zombie TODOs: script + clean up
  .github/workflows/reusable_checks.yml
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_components/src/load_file.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/parts/assets.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/source_hash.txt
  crates/re_types_builder/src/codegen/cpp/mod.rs
  docs/code-examples/clear_recursive.py
  docs/code-examples/clear_simple.py
  docs/code-examples/segmentation_image_simple.py
  docs/content/reference/viewer/viewport.md
  examples/python/arkit_scenes/main.py
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  scripts/ci/requirements.txt
  scripts/lint.py
  scripts/zombie_todos.py
  tests/roundtrips.py
  tests/rust/test_api/src/main.rs
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#3400 New explicit archetype API for logging barcharts
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/archetypes/bar_chart.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/bar_chart.rs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/datatypes/tensor_data_ext.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/bar_chart.py
  docs/code-examples/bar_chart.rs
  docs/code-examples/roundtrips.py
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/bar_chart.cpp
  rerun_cpp/src/rerun/archetypes/bar_chart.hpp
  rerun_py/rerun_sdk/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/rerun_sdk/rerun/log_deprecated/tensor.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer3.py
  tests/roundtrips.py
Labels: 🐍 python API, 🦀 rust SDK, codegen/idl, include in changelog

#3406 Fix crash on mismatch component lengths
  Cargo.lock
  Cranky.toml
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_helpers.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/src/test_util.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_components/src/datagen.rs
  crates/re_components/tests/arrow_msg.rs
  crates/re_components/tests/data_row.rs
  crates/re_components/tests/data_table.rs
  crates/re_components/tests/data_table_batcher.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_data_store/examples/memory_usage.rs
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/src/util.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/lib.rs
  crates/re_query/benches/query_benchmark.rs
  crates/re_query/benches/query_benchmark2.rs
  crates/re_query/examples/range.rs
  crates/re_query/src/query.rs
  crates/re_query/tests/archetype_query_tests.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_query/tests/query_tests.rs
  crates/re_query/tests/range_tests.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/recording_stream.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/rerun/src/run.rs
  rerun_py/src/arrow.rs
  rerun_py/src/python_bridge.rs
Labels: 📺 re_viewer, 💣 crash, exclude from changelog

#3411 Enforce named constructor (argument) for Arrows3D
  crates/re_types/definitions/rerun/archetypes/arrows3d.fbs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/arrows3d_ext.rs
  crates/re_types/src/archetypes/clear.rs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/archetypes/view_coordinates.rs
  crates/re_types/tests/arrows3d.rs
  docs/code-examples/arrow3d_simple.cpp
  docs/code-examples/arrow3d_simple.py
  docs/code-examples/arrow3d_simple.rs
  docs/code-examples/clear_recursive.cpp
  docs/code-examples/clear_recursive.py
  docs/code-examples/clear_recursive.rs
  docs/code-examples/clear_simple.cpp
  docs/code-examples/clear_simple.py
  docs/code-examples/clear_simple.rs
  docs/code-examples/transform3d_simple.cpp
  docs/code-examples/transform3d_simple.py
  docs/code-examples/transform3d_simple.rs
  docs/code-examples/view_coordinates_simple.cpp
  docs/code-examples/view_coordinates_simple.rs
  examples/rust/clock/src/main.rs
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d_ext.cpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/view_coordinates.hpp
  rerun_cpp/tests/archetypes/arrows3d.cpp
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/tests/unit/test_arrows3d.py
  tests/cpp/roundtrips/arrows3d/main.cpp
  tests/python/roundtrips/arrows3d/main.py
  tests/rust/roundtrips/arrows3d/src/main.rs
Labels: 🐍 python API, 🦀 rust SDK, 🍏 primitives, C/C++ SDK, exclude from changelog

#3409 Add a overview roadmap under docs/reference
  docs/content/reference/roadmap.md
  docs/cspell.json
Labels: 📖 documentation, exclude from changelog

#3442 Click `recording://entity/path` links in markdown
  Cargo.lock
  Cargo.toml
  crates/re_data_store/src/instance_path.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_log_types/src/index.rs
  crates/re_log_types/src/path/data_path.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/entity_path_impl.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_log_types/src/path/parse_path.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_types/source_hash.txt
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/item.rs
  crates/rerun_c/src/lib.rs
  docs/code-examples/text_document.cpp
  docs/code-examples/text_document.py
  docs/code-examples/text_document.rs
  examples/python/structure_from_motion/main.py
  examples/python/text_logging/main.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/test_types/datatypes/affix_fuzzer3.py
  scripts/lint.py
  tests/python/roundtrips/text_document/main.py
  tests/python/test_api/main.py
  tests/rust/test_api/src/main.rs
Labels: 📺 re_viewer, include in changelog

#3428 Remove debug print from image shape validator
  rerun_py/rerun_sdk/rerun/_validators.py
Labels: 🐍 python API, exclude from changelog

#3429 Remove vector check for images
  crates/re_space_view_spatial/src/parts/images.rs
Labels: 📺 re_viewer, exclude from changelog

#3439 Fix Asset3D transform
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/assets3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
Labels: 🦟 regression, exclude from changelog

#3446 Friendler `rr.Clear(recursive=xx)` APIs in python
  crates/re_types/source_hash.txt
  docs/code-examples/clear_recursive.py
  docs/code-examples/clear_simple.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/clear_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/clear.py
  rerun_py/tests/unit/test_clear.py
Labels: 🐍 python API, include in changelog

#3444 Fix rust objectron's lack of timeless data
  examples/rust/objectron/src/main.rs
Labels: examples, 🦟 regression, exclude from changelog

#3447 Add up-axes to code-examples
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/view_coordinates.rs
  docs/code-examples/asset3d_out_of_tree.py
  docs/code-examples/asset3d_out_of_tree.rs
  docs/code-examples/asset3d_simple.cpp
  docs/code-examples/asset3d_simple.py
  docs/code-examples/asset3d_simple.rs
  docs/code-examples/roundtrips.py
  docs/code-examples/view_coordinates_simple.cpp
  docs/code-examples/view_coordinates_simple.py
  docs/code-examples/view_coordinates_simple.rs
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d_ext.cpp
  rerun_cpp/src/rerun/archetypes/view_coordinates.hpp
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
Labels: 📖 documentation, examples, exclude from changelog

#3448 Fix crash on empty mesh
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
Labels: 💣 crash, exclude from changelog

#3449 `log_timeless`: remove the extra `bool` parameter
  crates/re_sdk/src/recording_stream.rs
  crates/re_types/source_hash.txt
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/view_coordinates.rs
  docs/code-examples/asset3d_out_of_tree.rs
  docs/code-examples/asset3d_simple.rs
  docs/code-examples/view_coordinates_simple.rs
  examples/rust/objectron/src/main.rs
  rerun_py/src/python_bridge.rs
Labels: 🦀 rust SDK, exclude from changelog

#3452 Make 'Print datastore' viable with real world data
  crates/re_format/src/arrow.rs
Labels: 🧑‍💻 dev experience, include in changelog

#3460 Remove `source_hash.txt`es from git
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_upload_wheels.yml
  .gitignore
  ci_docker/Dockerfile
  ci_docker/publish.sh
  crates/re_build_tools/src/lib.rs
  crates/re_build_tools/src/rebuild_detector.rs
  crates/re_types/build.rs
  crates/re_types/source_hash.txt
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/build.rs
  crates/re_types_builder/source_hash.txt
  crates/re_types_builder/src/bin/build_re_types.rs
  crates/re_types_builder/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#3459 Update to latest egui and egui_commonmark
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/list_item.rs
Labels: ui, dependencies, exclude from changelog

#3457 Improve how indicator components show up in the UI
  crates/re_arrow_store/src/store_gc.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/lib.rs
  crates/re_format/src/lib.rs
  crates/re_time_panel/src/lib.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#3427 Plumb camera_xyz through the PinholeExt constructor
  crates/re_types/definitions/rerun/archetypes/pinhole.fbs
  crates/re_types/src/archetypes/pinhole.rs
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole_ext.py
Labels: 🐍 python API, exclude from changelog

#3458 Rename `ClearSettings` component to `ClearIsRecursive`
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_sdk/src/lib.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes/clear.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/clear_is_recursive.fbs
  crates/re_types/src/archetypes/clear.rs
  crates/re_types/src/archetypes/clear_ext.rs
  crates/re_types/src/components/clear_is_recursive.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/tests/clear.rs
  docs/code-examples/clear_recursive.cpp
  docs/code-examples/clear_simple.cpp
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes/clear.cpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/archetypes/clear_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/clear_is_recursive.cpp
  rerun_cpp/src/rerun/components/clear_is_recursive.hpp
  rerun_py/rerun_sdk/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/clear_ext.py
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/clear_is_recursive.py
  rerun_py/rerun_sdk/rerun/components/clear_is_recursive_ext.py
  rerun_py/rerun_sdk/rerun/components/clear_settings.py
  rerun_py/tests/unit/test_clear.py
Labels: ui, exclude from changelog

#3466 Rename ArchetypeLike -> AsComponents
  docs/code-examples/custom_data.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_and_mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_rotation_scale3d_ext.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/rerun_sdk/rerun/log.py
Labels: 🐍 python API, exclude from changelog

#3464 Remove the legacy Transform helper types and all of components_deprecated
  examples/python/arkit_scenes/main.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/components_deprecated/__init__.py
  rerun_py/rerun_sdk/rerun/components_deprecated/box.py
  rerun_py/rerun_sdk/rerun/components_deprecated/experimental/__init__.py
  rerun_py/rerun_sdk/rerun/components_deprecated/pinhole.py
  rerun_py/rerun_sdk/rerun/components_deprecated/quaternion.py
  rerun_py/rerun_sdk/rerun/components_deprecated/rect2d.py
  rerun_py/rerun_sdk/rerun/components_deprecated/scalar.py
  rerun_py/rerun_sdk/rerun/components_deprecated/transform3d.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation_axis_angle_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/extension_components.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
Labels: 🐍 python API, exclude from changelog

#3463 Port all Rust examples
  examples/rust/clock/src/main.rs
  examples/rust/objectron/src/main.rs
  examples/rust/raw_mesh/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 🦀 rust SDK, examples, exclude from changelog

#3468 Make new APIs available at the toplevel rerun namespace
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_and_mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_rotation_scale3d_ext.py
  rerun_py/rerun_sdk/rerun/experimental.py
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
Labels: 🐍 python API, include in changelog

#3451 Fix no default colors showing for class ids when there's no annotation context
  crates/re_viewer_context/src/annotations.rs
Labels: 🦟 regression, exclude from changelog

#3471 Do not document `rerun-cli`
  .github/workflows/reusable_checks.yml
  crates/rerun-cli/Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3474 Fix `re_types_builder` falsely triggering rebuilds
  crates/re_types_builder/build.rs
Labels: ⏱ build-times, 🦟 regression, codegen/idl, exclude from changelog

#3472 Make new space views active in whatever tab container they are in
  Cargo.lock
  Cargo.toml
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, ui, exclude from changelog

#3481 New helper object for logging ImageEncoded in python
  docs/code-examples/image_advanced.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_image_encoded.py
Labels: 🐍 python API, exclude from changelog

#3486 Test the component rather than the datatype in test_tensor.py
  rerun_py/tests/unit/test_tensor.py
Labels: 🔨 testing, exclude from changelog

#3454 Fixes no space views showing up for later logged entities
  crates/re_viewer/src/app_state.rs
  crates/re_viewport/src/blueprint_components/viewport.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, 🦟 regression, exclude from changelog

#3489 Remove `EntityView` and related querying tools
  Cargo.lock
  crates/re_query/Cargo.toml
  crates/re_query/examples/range.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_query/src/entity_view.rs
  crates/re_query/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_query/src/range.rs
  crates/re_query/src/util.rs
  crates/re_query/src/visit.rs
  crates/re_query/tests/query_tests.rs
  crates/re_query/tests/range_tests.rs
  crates/re_query/tests/visit_tests.rs
  crates/re_space_view_text_log/Cargo.toml
  crates/re_space_view_text_log/src/view_part_system.rs
Labels: 🔍 re_query, 🚜 refactor, exclude from changelog

#3491 Remove `LegacyComponent`
  crates/re_log_types/src/component.rs
  crates/re_log_types/src/example_components.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/lib.rs
  crates/re_types/src/components/position2d_ext.rs
  crates/re_viewer/src/blueprint_components/panel.rs
  crates/re_viewport/src/blueprint_components/space_view.rs
  crates/re_viewport/src/blueprint_components/viewport.rs
Labels: 📺 re_viewer, 🔍 re_query, 🍏 primitives, exclude from changelog

#3490 Prune dependencides
  Cargo.lock
  Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_ui/src/image_meaning.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/load_file.rs
  crates/re_space_view_bar_chart/Cargo.toml
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/assets3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_space_view_text_document/Cargo.toml
  crates/re_space_view_text_document/src/view_part_system.rs
  crates/re_space_view_text_log/Cargo.toml
  crates/re_space_view_text_log/src/view_part_system.rs
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_tracing/src/server.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/archetype.rs
  crates/re_types/src/loggable_batch.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/src/design_tokens.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/web.rs
  crates/re_viewer_context/Cargo.toml
  deny.toml
  rerun_py/Cargo.toml
  tests/rust/roundtrips/depth_image/Cargo.toml
  tests/rust/roundtrips/segmentation_image/Cargo.toml
Labels: dependencies, exclude from changelog

#3484 Make Tensor __init__ support the names argument.
  docs/code-examples/tensor_simple.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/tensor.py
  rerun_py/tests/unit/test_tensor.py
Labels: 🐍 python API, exclude from changelog

#3497 [python] ViewCoordinates constants on rr.ViewCoordinates are now components not archetypes
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates_ext.py
  rerun_py/tests/unit/test_pinhole.py
  scripts/generate_view_coordinate_defs.py
Labels: 🪳 bug, 🐍 python API, exclude from changelog

#3493 Add `indices` parameter to python Mesh3D api to skip mesh properties
  crates/re_data_ui/src/data.rs
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_types/definitions/rerun/datatypes/mesh_properties.fbs
  crates/re_types/src/archetypes/mesh3d_ext.rs
  crates/re_types/src/components/mesh_properties.rs
  crates/re_types/src/datatypes/mesh_properties.rs
  crates/re_types/src/datatypes/mesh_properties_ext.rs
  crates/re_types/tests/mesh3d.rs
  docs/code-examples/mesh3d_indexed.cpp
  docs/code-examples/mesh3d_indexed.py
  examples/python/raw_mesh/main.py
  rerun_cpp/src/rerun/components/mesh_properties.hpp
  rerun_cpp/src/rerun/components/mesh_properties_ext.cpp
  rerun_cpp/src/rerun/datatypes/mesh_properties.cpp
  rerun_cpp/src/rerun/datatypes/mesh_properties.hpp
  rerun_cpp/tests/archetypes/mesh3d.cpp
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/mesh_properties.py
  rerun_py/rerun_sdk/rerun/datatypes/mesh_properties_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/mesh.py
  rerun_py/tests/unit/test_mesh3d.py
Labels: enhancement, 🐍 python API, exclude from changelog

#3498 Update README.md with "multimodal data" messaging
  README.md
Labels: 📖 documentation, exclude from changelog

#3509 Consistent naming for instantiated recording streams
  docs/code-examples/text_document.cpp
  docs/code-examples/text_log.cpp
  examples/cpp/minimal/main.cpp
  scripts/lint.py
  tests/cpp/roundtrips/text_document/main.cpp
  tests/cpp/roundtrips/text_log/main.cpp
  tests/cpp/roundtrips/view_coordinates/main.cpp
Labels: 🧑‍💻 dev experience, examples, C/C++ SDK, exclude from changelog

#3499 Add python validators for vec2d/3d/4d shape mismatch
  docs/code-examples/arrow3d_simple.py
  rerun_py/rerun_sdk/rerun/_validators.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/datatypes/quaternion_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/vec2d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/vec3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/vec4d_ext.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_vecnd.py
Labels: enhancement, 🐍 python API, exclude from changelog

#3511 `MediaType` extension improvements for Python
  docs/code-examples/text_document.py
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/components/media_type_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  tests/python/roundtrips/text_document/main.py
Labels: 🐍 python API, 🧑‍💻 dev experience, include in changelog

#3514 Fix depth point cloud not taking transformation at its path into account
  crates/re_space_view_spatial/src/parts/images.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#3507 Make ColorBatch constructor more forgiving
  crates/re_types/definitions/rerun/datatypes/color.fbs
  rerun_py/rerun_sdk/rerun/datatypes/color.py
  rerun_py/rerun_sdk/rerun/datatypes/color_ext.py
Labels: 🐍 python API, exclude from changelog

#3501 Check if another process is already listening on the port before trying to spawn
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 🐍 python API, include in changelog

#3500 Establish proof-of-concept for deprecating legacy functions
  .github/workflows/reusable_build_and_test_wheels.yml
  docs/content/reference/migration-0-9.md
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/log_deprecated/points.py
Labels: 🐍 python API, exclude from changelog

#3515 Force kw-args on more Python functions
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/_rerun2/__init__.py
  rerun_py/rerun_sdk/rerun/recording.py
Labels: 🐍 python API, include in changelog

#3505 Simplify MatNxN construction to make it more permissive
  crates/re_types/definitions/rerun/datatypes/mat3x3.fbs
  crates/re_types/definitions/rerun/datatypes/mat4x4.fbs
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4_ext.py
Labels: 🐍 python API, exclude from changelog

#3517 Force kwargs in codegened `__init__` methods of Archetypes
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/objects.rs
  docs/code-examples/mesh3d_indexed.py
  docs/code-examples/mesh3d_partial_updates.py
  docs/code-examples/mesh3d_simple.py
  examples/python/raw_mesh/main.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_and_mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_rotation_scale3d_ext.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
  rerun_py/tests/unit/test_mesh3d.py
Labels: 🐍 python API, exclude from changelog

#3518 Rename Asset3D.data → blob, TextLog.body & TextDocument.body → text
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_space_view_spatial/src/parts/assets3d.rs
  crates/re_types/definitions/rerun/archetypes/asset3d.fbs
  crates/re_types/definitions/rerun/archetypes/boxes2d.fbs
  crates/re_types/definitions/rerun/archetypes/text_document.fbs
  crates/re_types/definitions/rerun/archetypes/text_log.fbs
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/asset3d_ext.rs
  crates/re_types/src/archetypes/boxes2d.rs
  crates/re_types/src/archetypes/text_document.rs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_types/tests/asset3d.rs
  crates/re_types/tests/text_document.rs
  crates/re_types_builder/src/objects.rs
  docs/code-examples/text_log.py
  rerun_cpp/src/rerun/archetypes/asset3d.cpp
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/boxes2d.cpp
  rerun_cpp/src/rerun/archetypes/boxes2d.hpp
  rerun_cpp/src/rerun/archetypes/text_document.cpp
  rerun_cpp/src/rerun/archetypes/text_document.hpp
  rerun_cpp/src/rerun/archetypes/text_log.cpp
  rerun_cpp/src/rerun/archetypes/text_log.hpp
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/error_utils.py
  rerun_py/rerun_sdk/rerun/log_deprecated/log_decorator.py
  rerun_py/rerun_sdk/rerun/log_deprecated/text.py
  rerun_py/rerun_sdk/rerun/log_deprecated/text_internal.py
  tests/python/roundtrips/text_document/main.py
  tests/python/roundtrips/text_log/main.py
Labels: 🐍 python API, codegen/idl, exclude from changelog

#3506 Update import path for HuggingFace's `randn_tensor`
  examples/python/depth_guided_stable_diffusion/huggingface_pipeline.py
Labels: examples

#3523 Update to egui 0.23
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/icons.rs
Labels: 📺 re_viewer, dependencies, include in changelog

#3524 Fix auto-layout of space views
  Cargo.lock
  Cargo.toml
  crates/re_viewport/src/blueprint_components/viewport.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#3525 Make `FileSink` actually flush its data when asked to
  crates/re_log_encoding/src/encoder.rs
  crates/re_log_encoding/src/file_sink.rs
  crates/re_sdk/src/lib.rs
Labels: 🪳 bug, 🦀 rust SDK, include in changelog

#3536 Simpler deserialization code(gen)
  crates/re_types/src/components/class_id.rs
  crates/re_types/src/components/color.rs
  crates/re_types/src/components/depth_meter.rs
  crates/re_types/src/components/draw_order.rs
  crates/re_types/src/components/half_sizes2d.rs
  crates/re_types/src/components/half_sizes3d.rs
  crates/re_types/src/components/instance_key.rs
  crates/re_types/src/components/keypoint_id.rs
  crates/re_types/src/components/origin2d.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/pinhole_projection.rs
  crates/re_types/src/components/position2d.rs
  crates/re_types/src/components/position3d.rs
  crates/re_types/src/components/radius.rs
  crates/re_types/src/components/resolution.rs
  crates/re_types/src/components/scalar.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/components/view_coordinates.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
Labels: 🚜 refactor, codegen/idl, exclude from changelog

#3487 Converting `anyhow` to `this-error` for re_renderer Renderer::draw
  crates/re_renderer/src/queuable_draw_data.rs
  crates/re_renderer/src/renderer/compositor.rs
  crates/re_renderer/src/renderer/debug_overlay.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/generic_skybox.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/renderer/test_triangle.rs
Labels: enhancement, 🔺 re_renderer, exclude from changelog

#3533 Support for constructing `Boxes2D` from arrays of arbitrary formats
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  rerun_py/tests/unit/test_box2d.py
Labels: 🐍 python API, 🧑‍💻 dev experience, 🦟 regression, include in changelog

#3544 Update workflows to support fork PRs
  .github/workflows/checkboxes.yml
  .github/workflows/contrib/checks.yml
  .github/workflows/contrib/rerun_py.yml
  .github/workflows/documentation.yaml
  .github/workflows/labels.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_pull_request_contrib.yml
  .github/workflows/on_pull_request_target_contrib.yml
Labels: 🧑‍💻 dev experience, include in changelog

#3546 Update to egui_tiles 0.3.1
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog

#3549 Support fork PRs
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_pull_request_contrib.yml
  .github/workflows/on_pull_request_target_contrib.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3550 Support fork PRs (p3)
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  scripts/ci/update_pr_body.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3554 Support fork PRs (p4)
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  scripts/ci/check_pr_checkboxes.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3556 Support fork PRs (p5)
  .github/workflows/contrib_rerun_py.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3534 Fix infinite recursion when putting a container inside a viewer tab
  Cargo.lock
  Cargo.toml
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, 💣 crash, include in changelog

#3520 Fix failing to preview small images
  crates/re_data_ui/src/image.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#3564 Deprecate all of the legacy `log_` prefixed APIs.
  rerun_py/rerun_sdk/rerun/log_deprecated/annotation.py
  rerun_py/rerun_sdk/rerun/log_deprecated/arrow.py
  rerun_py/rerun_sdk/rerun/log_deprecated/bounding_box.py
  rerun_py/rerun_sdk/rerun/log_deprecated/camera.py
  rerun_py/rerun_sdk/rerun/log_deprecated/clear.py
  rerun_py/rerun_sdk/rerun/log_deprecated/extension_components.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  rerun_py/rerun_sdk/rerun/log_deprecated/image.py
  rerun_py/rerun_sdk/rerun/log_deprecated/lines.py
  rerun_py/rerun_sdk/rerun/log_deprecated/mesh.py
  rerun_py/rerun_sdk/rerun/log_deprecated/points.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  rerun_py/rerun_sdk/rerun/log_deprecated/scalar.py
  rerun_py/rerun_sdk/rerun/log_deprecated/tensor.py
  rerun_py/rerun_sdk/rerun/log_deprecated/text.py
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
Labels: 🐍 python API, include in changelog

#3566 Ignore RUSTSEC-2023-0065 in deny.toml
  deny.toml
Labels: exclude from changelog

#3567 Make more dependencies into workspace dependencies
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_arrow_store/Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_log/Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_memory/Cargo.toml
  crates/re_query/Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_sdk/Cargo.toml
  crates/re_sdk_comms/Cargo.toml
  crates/re_tuid/Cargo.toml
  crates/re_types/Cargo.toml
  crates/re_viewer/Cargo.toml
  crates/re_viewer_context/Cargo.toml
  crates/re_viewport/Cargo.toml
  crates/re_web_viewer_server/Cargo.toml
  crates/re_ws_comms/Cargo.toml
  crates/rerun-cli/Cargo.toml
  crates/rerun/Cargo.toml
  rerun_py/Cargo.toml
  run_wasm/Cargo.toml
Labels: 🧑‍💻 dev experience, dependencies, exclude from changelog

#3531 New decorator/context manager to catch exceptions when not in strict mode.
  crates/re_sdk/src/log_sink.rs
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/_validators.py
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/disconnected_space.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/rerun_sdk/rerun/error_utils.py
  rerun_py/rerun_sdk/rerun/log_deprecated/log_decorator.py
  rerun_py/rerun_sdk/rerun/recording.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
  rerun_py/tests/unit/test_exceptions.py
  rerun_py/tests/unit/test_expected_warnings.py
Labels: 🐍 python API, include in changelog
