Repository rerun-io/rerun, pull requests merged in 2023-12, with the labels that each got.

#4111 Update egui and wgpu
  Cargo.lock
  Cargo.toml
  crates/re_build_web_viewer/Cargo.toml
  crates/re_log_encoding/Cargo.toml
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/draw_phases/screenshot.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/screenshotter.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/blueprint/viewport_layout_ext.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  deny.toml
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 🔺 re_renderer, dependencies, include in changelog

#4391 Load examples manifest via HTTP
  .github/pull_request_template.md
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_web_demo.yml
  .prettierignore
  .prettierrc.toml
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  crates/re_build_examples_manifest/Cargo.toml
  crates/re_build_examples_manifest/src/main.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/build.rs
  crates/re_viewer/data/examples_manifest.json
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
  pixi.lock
  pixi.toml
  scripts/ci/demo_assets/static/index.html
  scripts/ci/demo_assets/templates/example.html
  scripts/ci/templates/benchmark.html
  scripts/ci/templates/pip_index.html
  scripts/ci/templates/pr_results_summary.html
  scripts/screenshot_compare/assets/templates/example.html
  scripts/screenshot_compare/assets/templates/index.html
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 🕸️ web, include in changelog, :ship: CI

#4300 Remove the "can't copy/cut on Safari" warning from the Getting Started guides
  crates/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/re_viewer/data/quick_start_guides/python_connect.md
  crates/re_viewer/data/quick_start_guides/python_spawn.md
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  crates/re_viewer/data/quick_start_guides/rust_spawn.md
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
Labels: ui, exclude from changelog

#4417 Datastore: don't eagerly sort in bucket split rountine on ingestion path
  crates/re_arrow_store/src/store_write.rs
Labels: 🪳 bug, ⛃ re_datastore, 📉 performance, include in changelog

#4419 Install only PyGithub for checkboxes.yml
  .github/workflows/checkboxes.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#4270 Restore `egui_plot` auto-bounds state after dragging the time cursor in timeseries space views
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: ui, include in changelog

#4403 Make Space View containers selectable and editable
  Cargo.lock
  crates/re_data_ui/src/item.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4414 Log wgpu adapter on web
  crates/re_renderer/src/context.rs
  crates/re_viewer/src/native.rs
Labels: 🕸️ web, 🔺 re_renderer, include in changelog

#4411 Add Python version of the basic benchmarks
  justfile
  rerun_py/pyproject.toml
  tests/python/log_benchmark/__init__.py
  tests/python/log_benchmark/test_log_benchmark.py
  tests/python/requirements.txt
Labels: 🐍 python API, 🧑‍💻 dev experience, exclude from changelog

#4394 GC improvements 0: use-case driven benchmarks
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/gc.rs
  crates/re_sdk/Cargo.toml
  crates/re_types_core/src/loggable_batch.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4395 GC improvements 1: fix timeless tables not being `RowId`-ordered
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_arrow.rs
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_format.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_sanity.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/correctness.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4396 GC improvements 2: `VecDeque` extensions & benchmarks
  Cargo.lock
  crates/re_log_types/Cargo.toml
  crates/re_log_types/benches/vec_deque_ext.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/vec_deque_ext.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4398 GC improvements 4: index `EntityPathHash`es in metadata registry
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_log_types/src/hash.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_types_core/src/size_bytes.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4399 GC improvements 5: `Store{Diff,Event}` optimizations
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/time_histogram_per_timeline.rs
  crates/re_data_store/src/times_per_timeline.rs
  examples/rust/custom_store_subscriber/src/main.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4400 GC improvements 6: introduce batched GC
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/benches/gc.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_arrow.rs
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_sanity.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_data_store/src/store_db.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4401 GC improvements 7: introduce `time_budget` GC setting
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/benches/gc.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_data_store/src/store_db.rs
  scripts/clippy_wasm/clippy.toml
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4429 Replace `lazy_static` with `OnceLock`
  Cargo.lock
  Cargo.toml
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/highlights.rs
Labels: dependencies, 🚜 refactor, exclude from changelog

#4421 Interior mutablilty for re_renderer's static resource pools (RenderPipeline/Shader/Layouts/etc.)
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/global_bindings.rs
  crates/re_renderer/src/queuable_draw_data.rs
  crates/re_renderer/src/renderer/compositor.rs
  crates/re_renderer/src/renderer/debug_overlay.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/generic_skybox.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/renderer/test_triangle.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/bind_group_layout_pool.rs
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_renderer/src/wgpu_resources/mod.rs
  crates/re_renderer/src/wgpu_resources/pipeline_layout_pool.rs
  crates/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
  crates/re_renderer/src/wgpu_resources/sampler_pool.rs
  crates/re_renderer/src/wgpu_resources/shader_module_pool.rs
  crates/re_renderer/src/wgpu_resources/static_resource_pool.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: 🔺 re_renderer, 🚜 refactor, include in changelog

#4434 DataStore: unjustified `debug_assert` & mutability shenanigans
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/test_util.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_viewer/src/saving.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#4422 Make draw data creation no longer require a mutable re_renderer context
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/depth_offset.rs
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/outlines.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_renderer/src/file_server.rs
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/compositor.rs
  crates/re_renderer/src/renderer/debug_overlay.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/generic_skybox.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/renderer/test_triangle.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/pipeline_layout_pool.rs
  crates/re_renderer/src/wgpu_resources/shader_module_pool.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
Labels: 🔺 re_renderer, 🚜 refactor, include in changelog

#4430 Make viewer contexts's render context reference non-mutable
  crates/re_data_ui/src/image.rs
  crates/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/draw_phases/screenshot.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: 🔺 re_renderer, 📺 re_viewer, 🚜 refactor, include in changelog

#4416 Improve the Selection Panel UI for components when a single item is selected
  clippy.toml
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/transform3d.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  scripts/clippy_wasm/clippy.toml
  tests/python/annotation_context_ui_stress/annotation_context_ui_stress.py
Labels: ui, include in changelog

#4445 Rename `RowId::random` to `RowId::new`
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/benches/gc.rs
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_helpers.rs
  crates/re_arrow_store/src/store_subscriber.rs
  crates/re_arrow_store/src/test_util.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_data_store/examples/memory_usage.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/tests/clear.rs
  crates/re_data_store/tests/time_histograms.rs
  crates/re_log_encoding/src/decoder.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_query/benches/query_benchmark.rs
  crates/re_query/src/query.rs
  crates/re_query/tests/archetype_query_tests.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_tuid/benches/bench_tuid.rs
  crates/re_tuid/src/lib.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/rerun_c/src/lib.rs
  rerun_py/src/arrow.rs
  rerun_py/src/python_bridge.rs
Labels: 🚜 refactor, exclude from changelog

#4446 RenderContext usage cleanup
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/renderer/compositor.rs
  crates/re_renderer/src/renderer/debug_overlay.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/generic_skybox.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/renderer/test_triangle.rs
  crates/re_renderer/src/resource_managers/mesh_manager.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/pipeline_layout_pool.rs
  crates/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
  crates/re_renderer/src/wgpu_resources/shader_module_pool.rs
Labels: 🚜 refactor, include in changelog

#4439 Remove demo build script
  .gitignore
  scripts/ci/build_demo_app.py
  scripts/ci/demo_assets/static/caret-down.svg
  scripts/ci/demo_assets/static/caret-right.svg
  scripts/ci/demo_assets/static/favicon.svg
  scripts/ci/demo_assets/static/github-mark-white.svg
  scripts/ci/demo_assets/static/index.css
  scripts/ci/demo_assets/static/index.html
  scripts/ci/demo_assets/static/index.js
  scripts/ci/demo_assets/static/manifest.json
  scripts/ci/demo_assets/static/sw.js
  scripts/ci/demo_assets/templates/example.html
  scripts/screenshot_compare/build_screenshot_compare.py
Labels: 🕸️ web, exclude from changelog

#4450 Integrate re_tensor_ops crate into re_space_view_tensor
  Cargo.lock
  Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_tensor/src/dimension_mapping.rs
  crates/re_space_view_tensor/src/lib.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_dimension_mapper.rs
  crates/re_space_view_tensor/src/tensor_tests.rs
  crates/re_tensor_ops/Cargo.toml
  crates/re_tensor_ops/README.md
  crates/re_tensor_ops/src/lib.rs
Labels: 🚜 refactor, include in changelog

#4407 Add nuScenes-based lidar examples
  docs/cspell.json
  examples/manifest.yml
  examples/python/lidar/.gitignore
  examples/python/lidar/README.md
  examples/python/lidar/dataset
  examples/python/lidar/download_dataset.py
  examples/python/lidar/main.py
  examples/python/lidar/requirements.txt
  examples/python/nuscenes/.gitignore
  examples/python/nuscenes/README.md
  examples/python/nuscenes/download_dataset.py
  examples/python/nuscenes/main.py
  examples/python/nuscenes/requirements.txt
  examples/python/requirements.txt
Labels: examples, include in changelog

#4462 `re_format`: Make the arrow-features opt-in
  crates/re_arrow_store/Cargo.toml
  crates/re_format/Cargo.toml
  crates/re_format/src/arrow.rs
  crates/re_format/src/lib.rs
  crates/re_log_types/Cargo.toml
  crates/re_query/Cargo.toml
Labels: dependencies, 🚜 refactor, exclude from changelog

#4449 Add conda step in the Release PR template
  .github/workflows/release.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#4458 Document our crate organization in ARCHITECTURE.md
  ARCHITECTURE.md
  docs/cspell.json
  scripts/lint.py
Labels: 📖 documentation, include in changelog

#4459 Improve C++ example page entries
  examples/cpp/eigen_opencv/README.md
  examples/cpp/vrs/README.md
  examples/manifest.yml
Labels: examples, exclude from changelog

#4461 Update egui_extras to 0.24.2
  Cargo.lock
Labels: dependencies, exclude from changelog

#4463 Refactor: `re_tuid` no longer depends on `re_types_core`
  Cargo.lock
  crates/re_build_examples/Cargo.toml
  crates/re_data_store/src/store_db.rs
  crates/re_format/Cargo.toml
  crates/re_format/src/arrow.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_tuid/Cargo.toml
  crates/re_tuid/benches/bench_tuid.rs
  crates/re_tuid/src/lib.rs
  crates/re_types_core/Cargo.toml
  crates/re_types_core/benches/bench_tuid.rs
  crates/re_types_core/src/lib.rs
  crates/re_types_core/src/tuid.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewport/Cargo.toml
  rerun_py/Cargo.toml
  tests/rust/log_benchmark/Cargo.toml
Labels: 🚜 refactor, exclude from changelog

#4460 Parallize Space View system evaluation
  Cargo.lock
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_tracing/src/lib.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/format/cpp.rs
  crates/re_types_builder/src/format/rust.rs
  crates/re_types_builder/src/lib.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/caches.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/system_execution_output.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#4467 Add the possibility to add empty space views of all registered types
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4473 Fix taplo on auto crates release
  .github/workflows/auto_release_crates.yml
Labels: exclude from changelog, :ship: CI

#4454 Local-first wheel publishing
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_upload_wheels.yml
  .gitignore
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/generate_prerelease_pip_index.py
  scripts/ci/publish_wheels.py
  scripts/ci/templates/pip_index.html
  scripts/ci/verify_wheels.py
  scripts/ci/wheel_utils.py
Labels: 🧑‍💻 dev experience, include in changelog, :ship: CI

#4474 CI: Fix web viewer build on platforms other than linux
  scripts/ci/build_and_upload_wheels.py
Labels: exclude from changelog, :ship: CI

#4479 CI: Fix web viewer build
  .github/workflows/reusable_build_and_upload_wheels.yml
Labels: exclude from changelog, :ship: CI

#4475 Update to puffin 0.18.1
  Cargo.lock
Labels: dependencies, exclude from changelog

#4481 CI: Don't build web viewer during maturin build
  scripts/ci/build_and_upload_wheels.py
Labels: exclude from changelog, :ship: CI

#4483 CI: Fix wheel build
  scripts/ci/build_and_upload_wheels.py
Labels: exclude from changelog, :ship: CI

#4480 Remove unused features from `env_logger` and `tracing`
  Cargo.lock
  Cargo.toml
  crates/re_log/Cargo.toml
Labels: 🧑‍💻 dev experience, dependencies, exclude from changelog

#4485 Fix puffin connecting on the wrong address
  crates/re_tracing/src/server.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#4472 Move re_renderer examples to its own crate in order to make workspace level examples less confusing
  ARCHITECTURE.md
  Cargo.lock
  crates/re_renderer/Cargo.toml
  crates/re_renderer/examples/README.md
  crates/re_renderer/src/file_resolver.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer_examples/2d.rs
  crates/re_renderer_examples/Cargo.toml
  crates/re_renderer_examples/README.md
  crates/re_renderer_examples/assets/rerun.obj.zip
  crates/re_renderer_examples/depth_cloud.rs
  crates/re_renderer_examples/depth_offset.rs
  crates/re_renderer_examples/framework.rs
  crates/re_renderer_examples/multiview.rs
  crates/re_renderer_examples/outlines.rs
  crates/re_renderer_examples/picking.rs
  crates/re_renderer_examples/rerun.obj.zip
  docs/cspell.json
Labels: 🔺 re_renderer, 🚜 refactor, include in changelog

#4487 Remove `RowId` collision log spam
  crates/re_data_store/src/store_db.rs
  crates/re_viewer/src/app.rs
Labels: 🧑‍💻 dev experience, ⛃ re_datastore, exclude from changelog

#4471 Use `:` instead of `.` as the entity:component separator in paths
  crates/re_data_ui/src/item_ui.rs
  crates/re_log_types/src/path/data_path.rs
  crates/re_log_types/src/path/parse_path.rs
  crates/re_types/src/archetypes/text_document.rs
  docs/code-examples/text_document.cpp
  docs/code-examples/text_document.py
  docs/code-examples/text_document.rs
  examples/python/dna/main.py
  examples/python/structure_from_motion/main.py
  rerun_cpp/src/rerun/archetypes/text_document.hpp
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
Labels: 😤 annoying, include in changelog, 🔩 data model

#4501 Add missing example dependencies and remove dataset softlink
  examples/python/lidar/dataset
  examples/python/lidar/requirements.txt
  examples/python/nuscenes/requirements.txt
Labels: examples, exclude from changelog

#4476 File-like entity paths
  Cargo.lock
  Cargo.toml
  crates/re_data_store/src/lib.rs
  crates/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/index.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/entity_path_impl.rs
  crates/re_log_types/src/path/entity_path_part.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_log_types/src/path/natural_ordering.rs
  crates/re_log_types/src/path/parse_path.rs
  crates/re_query/benches/query_benchmark.rs
  crates/re_viewer_context/src/blueprint_id.rs
  docs/content/concepts/entity-component.md
  docs/content/concepts/entity-path.md
  docs/content/concepts/spaces-and-transforms.md
Labels: include in changelog, Log-API

#4506 Move all our dependencies to workspace Cargo.toml
  Cargo.lock
  Cargo.toml
  crates/re_build_tools/Cargo.toml
  crates/re_build_web_viewer/Cargo.toml
  crates/re_crash_handler/Cargo.toml
  crates/re_int_histogram/Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_query/Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_space_view/Cargo.toml
  crates/re_space_view_spatial/Cargo.toml
  crates/re_string_interner/Cargo.toml
  crates/re_time_panel/Cargo.toml
  crates/re_tuid/Cargo.toml
  crates/re_types_builder/Cargo.toml
  crates/re_types_core/Cargo.toml
  rerun_py/Cargo.toml
  tests/rust/roundtrips/annotation_context/Cargo.toml
  tests/rust/roundtrips/arrows3d/Cargo.toml
  tests/rust/roundtrips/boxes2d/Cargo.toml
  tests/rust/roundtrips/boxes3d/Cargo.toml
  tests/rust/roundtrips/depth_image/Cargo.toml
  tests/rust/roundtrips/disconnected_space/Cargo.toml
  tests/rust/roundtrips/image/Cargo.toml
  tests/rust/roundtrips/line_strips2d/Cargo.toml
  tests/rust/roundtrips/line_strips3d/Cargo.toml
  tests/rust/roundtrips/pinhole/Cargo.toml
  tests/rust/roundtrips/points2d/Cargo.toml
  tests/rust/roundtrips/points3d/Cargo.toml
  tests/rust/roundtrips/segmentation_image/Cargo.toml
  tests/rust/roundtrips/tensor/Cargo.toml
  tests/rust/roundtrips/text_document/Cargo.toml
  tests/rust/roundtrips/text_log/Cargo.toml
  tests/rust/roundtrips/transform3d/Cargo.toml
  tests/rust/roundtrips/view_coordinates/Cargo.toml
  tests/rust/test_api/Cargo.toml
Labels: dependencies, exclude from changelog

#4508 Add a new "🪵 Log-API" GitHub label
  .github/workflows/labels.yml
  scripts/generate_changelog.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#4509 Improved wgpu error handling, no more crashes through wgpu validation errors
  Cargo.lock
  Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_renderer/build.rs
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/error_handling/error_tracker.rs
  crates/re_renderer/src/error_handling/mod.rs
  crates/re_renderer/src/error_handling/now_or_never.rs
  crates/re_renderer/src/error_handling/wgpu_core_error.rs
  crates/re_renderer/src/error_handling/wgpu_error_scope.rs
  crates/re_renderer/src/error_tracker.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_renderer/src/file_server.rs
  crates/re_renderer/src/file_system.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer_examples/framework.rs
Labels: enhancement, 🔺 re_renderer, include in changelog

#4502 Show e2e latency in metric ui in top panel
  Cargo.lock
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/store_db.rs
  crates/re_log_types/src/data_row.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/rerun_c/src/lib.rs
  rerun_py/src/arrow.rs
Labels: ui, 🧑‍💻 dev experience, include in changelog

#4523 Remove things we are no longer using after the query migration
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewport/src/space_view.rs
Labels: 🚜 refactor, 🟦 blueprint, exclude from changelog

#4510 Add an entity path filter
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/entity_path_filter.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_log_types/src/path/natural_ordering.rs
Labels: exclude from changelog

#4534 Refactor `EntityTree`
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 🚜 refactor, exclude from changelog

#4505 Nightly builds
  .github/pull_request_template.md
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_upload_examples.yml
  .github/workflows/reusable_upload_web.yml
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_build_examples/Cargo.toml
  crates/re_build_examples/src/example.rs
  crates/re_build_examples/src/main.rs
  crates/re_build_examples/src/manifest.rs
  crates/re_build_examples/src/rrd.rs
  crates/re_build_examples_manifest/Cargo.toml
  crates/re_build_examples_manifest/src/main.rs
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  examples/README.md
  examples/cpp/dna/README.md
  examples/python/arkit_scenes/README.md
  examples/python/arkit_scenes/requirements.txt
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/depth_guided_stable_diffusion/requirements.txt
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/dna/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/human_pose_tracking/requirements.txt
  examples/python/lidar/requirements.txt
  examples/python/nuscenes/README.md
  examples/python/nuscenes/requirements.txt
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/segment_anything_model/README.md
  examples/python/structure_from_motion/README.md
  examples/rust/dna/README.md
  pixi.toml
  scripts/ci/requirements-examples-main.txt
  scripts/ci/requirements-examples-nightly.txt
  scripts/screenshot_compare/build_screenshot_compare.py
Labels: examples, include in changelog, :ship: CI

#4511 Standard input/output support 1: stream RRD data from stdin
  Cargo.toml
  crates/re_data_source/src/data_source.rs
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_stdin.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/src/lib.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, include in changelog, CLI

#4512 Standard input/output support 2: Rust SDK stdout impl/examples/docs
  Cargo.lock
  crates/re_data_source/src/load_stdin.rs
  crates/re_log_encoding/src/file_sink.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/recording_stream.rs
  docs/content/reference/sdk-operating-modes.md
  examples/rust/stdio/Cargo.toml
  examples/rust/stdio/README.md
  examples/rust/stdio/src/main.rs
Labels: 🦀 Rust API, 🧑‍💻 dev experience, include in changelog

#4513 Standard input/output support 3: Python SDK stdout impl/examples/docs
  docs/content/reference/sdk-operating-modes.md
  examples/python/requirements.txt
  examples/python/stdio/README.md
  examples/python/stdio/main.py
  examples/python/stdio/requirements.txt
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, 🧑‍💻 dev experience, include in changelog

#4514 Standard input/output support 4: C++ SDK stdout impl/examples/docs
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  docs/content/reference/sdk-operating-modes.md
  examples/cpp/CMakeLists.txt
  examples/cpp/stdio/CMakeLists.txt
  examples/cpp/stdio/README.md
  examples/cpp/stdio/main.cpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
Labels: 🧑‍💻 dev experience, 🌊 C++ API, include in changelog

#4539 Fix the entity-expression-editor
  crates/re_viewer/src/ui/selection_panel.rs
Labels: 🦟 regression, 🟦 blueprint, exclude from changelog

#4543 Use hyphen instead of underscore for example arguments
  examples/python/controlnet/README.md
  examples/python/controlnet/main.py
  examples/python/depth_guided_stable_diffusion/main.py
  examples/python/detect_and_track_objects/main.py
  examples/python/human_pose_tracking/main.py
  examples/python/lidar/main.py
  examples/python/nuscenes/main.py
  examples/python/objectron/main.py
  examples/python/raw_mesh/main.py
  examples/python/signed_distance_fields/main.py
  examples/python/structure_from_motion/read_write_model.py
Labels: examples, exclude from changelog

#4546 Ensure `main` is included in `nightly` builds
  crates/re_build_examples/src/example.rs
Labels: examples, exclude from changelog, :ship: CI

#4542 Improve entity size stats: include whole subtree
  crates/re_arrow_store/src/store_stats.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/item_ui.rs
Labels: ui, include in changelog

#4545 Limit the sizes of some of the nightly examples
  examples/python/nuscenes/README.md
  examples/python/nuscenes/main.py
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/open_photogrammetry_format/main.py
  examples/python/open_photogrammetry_format/requirements.txt
  examples/python/rgbd/README.md
  examples/python/rgbd/main.py
  examples/rust/objectron/README.md
Labels: examples, exclude from changelog

#4544 Add `--stdout`/`-o` to our CLI helper library
  crates/rerun/src/clap.rs
  rerun_py/rerun_sdk/rerun/script_helpers.py
Labels: 🐍 Python API, 🦀 Rust API, 🧑‍💻 dev experience, include in changelog, CLI

#3795 Migrate to `mime_guess2`
  Cargo.lock
  Cargo.toml
  crates/re_types/Cargo.toml
  crates/re_types/src/components/media_type_ext.rs
Labels: dependencies, exclude from changelog

#4516 `DataLoader`s 0: utility for hierarchical `EntityPath` from file path
  Cargo.lock
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/path/entity_path.rs
Labels: do-not-merge, include in changelog, 🔩 data model, Log-API

#4540 Keep global registry of all visualizers & context systems instead of isolating per space view class
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/system_execution.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🚜 refactor, exclude from changelog

#4517 `DataLoader`s 1: introduce, and migrate to, `DataLoader`s
  Cargo.lock
  crates/re_data_source/Cargo.toml
  crates/re_data_source/src/data_loader/loader_archetype.rs
  crates/re_data_source/src/data_loader/loader_rrd.rs
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_data_source/src/data_source.rs
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_file.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_types/src/archetypes/asset3d_ext.rs
  crates/re_types/src/archetypes/image_ext.rs
  crates/re_types/tests/asset3d.rs
  crates/re_viewer/src/app.rs
  examples/assets/.gitignore
  examples/assets/example.glb
  examples/assets/example.gltf
  examples/assets/example.jpg
  examples/assets/example.mtl
  examples/assets/example.obj
  examples/assets/example.png
  examples/assets/example.rrd
Labels: 📺 re_viewer, include in changelog, CLI

#4549 When duplicating a SpaceViewBlueprint, also duplicate its Query
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog

#4518 `DataLoader`s 2: add text-based `DataLoader` (`.txt`, `.md`)
  .typos.toml
  crates/re_data_source/src/data_loader/loader_archetype.rs
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_data_source/src/lib.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/archetypes/image_ext.rs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/text_document_ext.rs
  docs/cspell.json
  examples/assets/example.md
  examples/assets/example.txt
  scripts/lint.py
Labels: 📺 re_viewer, include in changelog, CLI

#4519 `DataLoader`s 3: add 3D point cloud `DataLoader` (`.ply`)
  Cargo.lock
  Cargo.toml
  crates/re_data_source/src/data_loader/loader_archetype.rs
  crates/re_data_source/src/lib.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/points3d_ext.rs
  deny.toml
  examples/assets/example.ply
Labels: 📺 re_viewer, include in changelog, CLI

#4520 `DataLoader`s 4: add generic folder `DataLoader`
  crates/re_data_source/src/data_loader/loader_directory.rs
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_data_source/src/load_file.rs
Labels: 📺 re_viewer, include in changelog, CLI

#4548 Resolve spurious blueprint panel group collapsing
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, 🦟 regression, include in changelog

#4521 `DataLoader`s 5: add support for external binary `DataLoader`s (PATH)
  Cargo.lock
  crates/re_data_source/src/data_loader/loader_external.rs
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_file.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  examples/assets/example.cpp
  examples/assets/example.py
  examples/assets/example.rs
  examples/cpp/CMakeLists.txt
  examples/cpp/external_data_loader/CMakeLists.txt
  examples/cpp/external_data_loader/README.md
  examples/cpp/external_data_loader/main.cpp
  examples/python/external_data_loader/README.md
  examples/python/external_data_loader/main.py
  examples/python/external_data_loader/requirements.txt
  examples/python/requirements.txt
  examples/rust/external_data_loader/Cargo.toml
  examples/rust/external_data_loader/README.md
  examples/rust/external_data_loader/src/main.rs
Labels: 📺 re_viewer, include in changelog, CLI

#4524 Get rid of `sync_blueprint_changes`
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/viewport_blueprint.fbs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/viewport_blueprint.py
Labels: 🚜 refactor, 🟦 blueprint, exclude from changelog

#4547 Add DataUi implementations for Blueprint Components
  crates/re_data_ui/src/blueprint_data.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/blueprint_id.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/blueprint/data_ui.rs
  crates/re_viewport/src/blueprint/mod.rs
Labels: ui, 🟦 blueprint, exclude from changelog

#4558 Introduce store subscriber (VisualizerEntitySubscriber) to maintain list of entities per system incrementally
  Cargo.lock
  Cargo.toml
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 📺 re_viewer, 🚜 refactor, exclude from changelog

#4559 Fix scripts/lint.py to work on windows
  scripts/lint.py
Labels: 🧑‍💻 dev experience, 🪟 windows, exclude from changelog

#4562 Don't run queries we know will be empty
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 📉 performance, exclude from changelog

#4541 Add LLM token classification example
  examples/manifest.yml
  examples/python/llm_embedding_ner/README.md
  examples/python/llm_embedding_ner/main.py
  examples/python/llm_embedding_ner/requirements.txt
  examples/python/requirements.txt
Labels: examples, include in changelog

#4578 Bumped zerocopy to 0.7.31
  Cargo.lock
Labels: dependencies, exclude from changelog

#4573 Add `SizeBytes::is_pod` and related optimizations
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/num_instances.rs
  crates/re_types_core/src/size_bytes.rs
Labels: 📉 performance, exclude from changelog

#4582 Open all links in a new tab
  crates/re_viewer/src/app.rs
Labels: 🕸️ web, include in changelog

#4577 Add support for modal windows to `re_ui` and use it for the Space View entity picker
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/modal.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport.rs
Labels: ui, 🚜 refactor, include in changelog

#4589 Update cfg_aliases
  Cargo.lock
  Cargo.toml
  crates/re_renderer/build.rs
  deny.toml
Labels: dependencies, exclude from changelog

#4591 Fix code talking about "views" instead of subscribers
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_subscriber.rs
Labels: 😤 annoying, exclude from changelog

#4565 `DataLoader`s 6: first-class support for `NotSupported`
  Cargo.lock
  crates/re_data_source/src/data_loader/loader_archetype.rs
  crates/re_data_source/src/data_loader/loader_directory.rs
  crates/re_data_source/src/data_loader/loader_external.rs
  crates/re_data_source/src/data_loader/loader_rrd.rs
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_file.rs
  crates/rerun/src/lib.rs
  examples/cpp/external_data_loader/main.cpp
  examples/python/external_data_loader/main.py
  examples/rust/external_data_loader/Cargo.toml
  examples/rust/external_data_loader/src/main.rs
  rerun_cpp/src/rerun.hpp
  rerun_py/rerun_sdk/rerun/__init__.py
Labels: 🧑‍💻 dev experience, 📺 re_viewer, include in changelog

#4566 `DataLoader`s 7: support for custom `DataLoader`s
  Cargo.lock
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_file.rs
  examples/rust/custom_data_loader/Cargo.toml
  examples/rust/custom_data_loader/README.md
  examples/rust/custom_data_loader/build.rs
  examples/rust/custom_data_loader/src/main.rs
Labels: 📺 re_viewer, include in changelog

#4584 Document how to construct an entity path for the Rust logging API
  crates/re_log_types/src/path/mod.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
Labels: 📖 documentation, 🦀 Rust API, include in changelog

#4581 Expose `wgpu` profiling scopes to puffin
  Cargo.lock
  Cargo.toml
  crates/re_renderer/Cargo.toml
Labels: 🔺 re_renderer, include in changelog

#4590 Fix rectangle that indicates the zoomed pixel area on hover being one pixel to small
  crates/re_data_ui/src/image.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#4586 Add tomlkit to pixi
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#4594 Get rid of `core_benchmarks_only`
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/arrow2.rs
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/benches/gc.rs
  crates/re_arrow_store/benches/vectors.rs
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#4585 Make it possible to log segmentation images directly as floats
  crates/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/re_types/src/archetypes/segmentation_image.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  docs/content/reference/types/archetypes/segmentation_image.md
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image_ext.py
  rerun_py/tests/unit/test_segmentation_image.py
Labels: 🐍 Python API, 📺 re_viewer, include in changelog

#4595 C++ & Python API: add helpers for constructing an entity path
  crates/re_log_types/src/path/mod.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  docs/code-examples/Cargo.toml
  docs/code-examples/entity_path.cpp
  docs/code-examples/entity_path.py
  docs/code-examples/entity_path.rs
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/entity_path.cpp
  rerun_cpp/src/rerun/entity_path.hpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, 🌊 C++ API, include in changelog

#4605 Remove spammy debug message in space_view_heuristics
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 📺 re_viewer, exclude from changelog

#4603 Show entity path parts (entity "folder" names) unescaped in UI
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/entity_path_part.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer_context/src/blueprint_id.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  crates/rerun_c/src/lib.rs
  rerun_py/src/python_bridge.rs
Labels: ui, include in changelog

#4563 Speed up query usage in heuristics by splitting DataQuery into separate query and update_properties passes
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/transform3d_arrows.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 📉 performance, exclude from changelog

#4599 Plot dashboard stress tool for Python & Rust
  Cargo.lock
  Cargo.toml
  justfile
  pixi.toml
  tests/python/plot_dashboard_stress/main.py
  tests/rust/plot_dashboard_stress/Cargo.toml
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 🐍 Python API, 🦀 Rust API, 🧑‍💻 dev experience, 📉 performance, exclude from changelog

#4587 3D->2D & 2D->3D selection visualizations stick now around on selection
  crates/re_data_ui/src/item_ui.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/selection_history.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#4604 Allow systems to specify custom filter for the applicable set beyond required_components
  Cargo.lock
  crates/re_space_view/src/lib.rs
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
Labels: 📺 re_viewer, 🚜 refactor, 🟦 blueprint, exclude from changelog

#4601 Replace include/exclude lists with new entity path filter DSL
  Cargo.lock
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/entity_path_expr.rs
  crates/re_log_types/src/path/entity_path_filter.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_space_view/src/blueprint/components/query_expressions.rs
  crates/re_space_view/src/blueprint/components/query_expressions_ext.rs
  crates/re_space_view/src/blueprint/datatypes/.gitattributes
  crates/re_space_view/src/blueprint/datatypes/mod.rs
  crates/re_space_view/src/blueprint/datatypes/query_expressions.rs
  crates/re_space_view/src/blueprint/mod.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/query_expressions.fbs
  crates/re_types/definitions/rerun/blueprint/datatypes/query_expressions.fbs
  crates/re_ui/Cargo.toml
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  rerun_cpp/src/rerun/blueprint/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/query_expressions.cpp
  rerun_cpp/src/rerun/blueprint/components/query_expressions.hpp
  rerun_cpp/src/rerun/blueprint/datatypes.hpp
  rerun_cpp/src/rerun/blueprint/datatypes/.gitattributes
  rerun_cpp/src/rerun/blueprint/datatypes/query_expressions.cpp
  rerun_cpp/src/rerun/blueprint/datatypes/query_expressions.hpp
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/query_expressions.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/query_expressions.py
Labels: ui, 🟦 blueprint, exclude from changelog

#4608 Store indicator component mapping as part of Visualizer's store subscription
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 📉 performance, 🚜 refactor, 🟦 blueprint, exclude from changelog

#4600 Plot dashboard stress tool for C++
  .typos.toml
  justfile
  pixi.toml
  rerun_cpp/CMakeLists.txt
  rerun_cpp/src/rerun/third_party/cxxopts.hpp
  scripts/lint.py
  tests/cpp/CMakeLists.txt
  tests/cpp/plot_dashboard_stress/CMakeLists.txt
  tests/cpp/plot_dashboard_stress/main.cpp
Labels: 🧑‍💻 dev experience, 📉 performance, 🌊 C++ API, exclude from changelog

#4611 Add tree mutation APIs to `ViewportBlueprint`
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, exclude from changelog

#4613 Add `italics` and `weak` to `ListItem`
  crates/re_ui/src/list_item.rs
Labels: ui, exclude from changelog

#4592 Primary caching 1: more `VecDeque` extensions
  crates/re_log_types/benches/vec_deque_ext.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/vec_deque_ext.rs
Labels: ⛃ re_datastore, 📉 performance, exclude from changelog

#4567 `DataLoader`s 8: docs, guide, etc
  crates/re_data_source/src/data_loader/loader_external.rs
  crates/re_data_source/src/data_loader/mod.rs
  docs/content/getting-started/installing-viewer.md
  docs/content/howto/open-any-file.md
  docs/cspell.json
  examples/cpp/external_data_loader/main.cpp
  examples/python/external_data_loader/main.py
  examples/rust/external_data_loader/src/main.rs
Labels: 📖 documentation, exclude from changelog

#4612 Separation & improved book-keeping of entity -> visualizer assignment
  .vscode/settings.json
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/named_system.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewer_context/src/typed_entity_collections.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 📺 re_viewer, 🟦 blueprint, exclude from changelog

#4617 Properly clear containers that have been removed from the tile tree
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🟦 blueprint, exclude from changelog

#4625 Fix a bunch of clippy 1.75 lints
  crates/re_arrow_store/src/arrow_util.rs
  crates/re_arrow_store/src/store_helpers.rs
  crates/re_log_types/src/hash.rs
  crates/re_log_types/src/vec_deque_ext.rs
  crates/re_query/src/query.rs
  crates/re_types_builder/src/codegen/common.rs
  crates/re_viewer/src/saving.rs
  rerun_py/src/python_bridge.rs
Labels: 🚜 refactor, exclude from changelog
