Repository rerun-io/rerun, pull requests merged in 2023-10, with the labels that each got.

#3576 Hide indicator components from hover-ui
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/lib.rs
  crates/re_types/src/archetypes/pinhole_ext.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/pinhole_projection_ext.rs
  crates/re_types/src/loggable.rs
  crates/re_viewer_context/src/component_ui_registry.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#3577 Alpha release workflow
  .github/workflows/auto_release_crates.yml
  .github/workflows/release.yml
  RELEASES.md
  scripts/ci/crates.py
  scripts/ci/requirements.txt
Labels: 🧑‍💻 dev experience, ⛴ release, exclude from changelog

#3579 Tighter UI for Pinhole and when hovering images
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_types/src/components/pinhole_projection_ext.rs
Labels: ui, 📺 re_viewer, include in changelog

#3580 Single Wasm bundle
  .github/workflows/reusable_release_crates.yml
  crates/re_build_web_viewer/src/lib.rs
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/src/lib.rs
  scripts/ci/sizes.py
  scripts/lint.py
  web_viewer/.gitignore
Labels: 🕸️ web, exclude from changelog

#3568 Add ControlNet example
  examples/manifest.yml
  examples/python/controlnet/README.md
  examples/python/controlnet/main.py
  examples/python/controlnet/requirements.txt
  examples/python/requirements.txt
Labels: examples, include in changelog

#3560 Nicer transform archetype interface in python
  crates/re_data_ui/src/transform3d.rs
  crates/re_types/definitions/rerun/datatypes/translation_and_mat3x3.fbs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/datatypes/transform3d_ext.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_and_mat3x3_ext.rs
  crates/re_types/tests/transform3d.rs
  docs/code-examples/transform3d_simple.py
  docs/code-examples/transform3d_simple.rs
  examples/python/live_depth_sensor/main.py
  examples/python/open_photogrammetry_format/main.py
  examples/python/raw_mesh/main.py
  examples/python/ros_node/rerun_urdf.py
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d_ext.cpp
  rerun_cpp/src/rerun/datatypes/translation_and_mat3x3.cpp
  rerun_cpp/src/rerun/datatypes/translation_and_mat3x3.hpp
  rerun_cpp/src/rerun/datatypes/translation_and_mat3x3_ext.cpp
  rerun_cpp/tests/archetypes/transform3d.cpp
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_and_mat3x3.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_and_mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_rotation_scale3d_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  rerun_py/tests/unit/test_transform3d.py
  tests/python/roundtrips/transform3d/main.py
  tests/python/test_api/main.py
Labels: 🐍 python API, exclude from changelog

#3542 Improve Rust API docs
  crates/re_data_store/src/store_db.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_log/src/lib.rs
  crates/re_log/src/setup.rs
  crates/re_log_types/src/index.rs
  crates/re_log_types/src/path/component_path.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/log_integration.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/mod.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/clap.rs
  crates/rerun/src/lib.rs
  docs/code-examples/point2d_random.rs
  docs/code-examples/point3d_random.rs
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📖 documentation, 🦀 rust SDK, exclude from changelog

#3595 Replace `Result<T, anyhow::Error>` with `anyhow::Result<T>`
  crates/re_data_source/src/load_file_contents.rs
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/asset3d_ext.rs
  docs/code-examples/asset3d_out_of_tree.rs
  docs/code-examples/asset3d_simple.rs
  docs/content/reference/data_types/datatypes/translation_and_mat3x3.md
  scripts/lint.py
Labels: 🚜 refactor, exclude from changelog

#3593 Fix links in the docs
  .github/workflows/documentation.yaml
  docs/content/reference/data_types.md
Labels: 📖 documentation, exclude from changelog

#3597 Fix egui ID clash warning on toast notifcations
  crates/re_ui/src/toasts.rs
Labels: 🪳 bug, ui, exclude from changelog

#3591 Improve Asset3D and Blob APIs
  crates/re_types/definitions/rerun/archetypes/asset3d.fbs
  crates/re_types/src/archetypes/asset3d.rs
  docs/code-examples/asset3d_out_of_tree.py
  docs/code-examples/asset3d_simple.py
  docs/content/reference/data_types/archetypes/asset3d.md
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_py/rerun_sdk/rerun/_converters.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  rerun_py/tests/unit/test_asset3d.py
  rerun_py/tests/unit/test_blob.py
Labels: 🐍 python API, include in changelog

#3598 Checkout `github.sha` in `documentation` workflow
  .github/workflows/documentation.yaml
Labels: 🧑‍💻 dev experience, exclude from changelog

#2434 Install rerun-sdk with --no-index
  .github/workflows/reusable_run_notebook.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3583 Allow showing image shaped tensors in the tensor view
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#3581 Document annotation context archetype field.
  crates/re_types/definitions/rerun/archetypes/annotation_context.fbs
  crates/re_types/definitions/rerun/components/annotation_context.fbs
  crates/re_types/definitions/rerun/datatypes/mat3x3.fbs
  crates/re_types/definitions/rerun/datatypes/mat4x4.fbs
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/components/annotation_context.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/components/annotation_context.hpp
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/components/annotation_context.py
Labels: 📖 documentation, exclude from changelog

#3602 Document all datatypes and components
  crates/re_types/definitions/rerun/components/blob.fbs
  crates/re_types/definitions/rerun/components/material.fbs
  crates/re_types/definitions/rerun/components/mesh_properties.fbs
  crates/re_types/definitions/rerun/components/tensor_data.fbs
  crates/re_types/definitions/rerun/datatypes/material.fbs
  crates/re_types/definitions/rerun/datatypes/mesh_properties.fbs
  crates/re_types/definitions/rerun/datatypes/scalars.fbs
  crates/re_types/src/components/blob.rs
  crates/re_types/src/components/material.rs
  crates/re_types/src/components/mesh_properties.rs
  crates/re_types/src/components/tensor_data.rs
  crates/re_types/src/datatypes/float32.rs
  crates/re_types/src/datatypes/material.rs
  crates/re_types/src/datatypes/mesh_properties.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  docs/content/reference/data_types/components/blob.md
  docs/content/reference/data_types/components/material.md
  docs/content/reference/data_types/components/mesh_properties.md
  docs/content/reference/data_types/components/tensor_data.md
  docs/content/reference/data_types/datatypes/float32.md
  docs/content/reference/data_types/datatypes/material.md
  docs/content/reference/data_types/datatypes/mesh_properties.md
  rerun_cpp/src/rerun/components/blob.hpp
  rerun_cpp/src/rerun/components/material.hpp
  rerun_cpp/src/rerun/components/mesh_properties.hpp
  rerun_cpp/src/rerun/components/tensor_data.hpp
  rerun_cpp/src/rerun/datatypes/float32.hpp
  rerun_cpp/src/rerun/datatypes/material.hpp
  rerun_cpp/src/rerun/datatypes/mesh_properties.hpp
  rerun_py/rerun_sdk/rerun/components/blob.py
  rerun_py/rerun_sdk/rerun/components/material.py
  rerun_py/rerun_sdk/rerun/components/mesh_properties.py
  rerun_py/rerun_sdk/rerun/components/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/float32.py
  rerun_py/rerun_sdk/rerun/datatypes/material.py
  rerun_py/rerun_sdk/rerun/datatypes/mesh_properties.py
Labels: 📖 documentation, codegen/idl, exclude from changelog

#3561 Introduce AnyValues as an alternative to extension_components
  docs/code-examples/any_values.py
  docs/code-examples/roundtrips.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/tests/unit/test_any_values.py
Labels: 🐍 python API, include in changelog

#3565 Update the python API docs site for the new APIs
  rerun_py/docs/css/mkdocstrings.css
  rerun_py/docs/gen_common_index.py
  rerun_py/docs/package/index.md
  rerun_py/mkdocs.yml
  rerun_py/rerun_sdk/rerun/_image.py
Labels: 📖 documentation, include in changelog

#3562 Remove ext= and allow logging extra component bundles
  docs/code-examples/extra_values.py
  docs/code-examples/roundtrips.py
  examples/python/face_tracking/main.py
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/log_deprecated/arrow.py
  rerun_py/rerun_sdk/rerun/log_deprecated/bounding_box.py
  rerun_py/rerun_sdk/rerun/log_deprecated/image.py
  rerun_py/rerun_sdk/rerun/log_deprecated/lines.py
  rerun_py/rerun_sdk/rerun/log_deprecated/points.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  rerun_py/rerun_sdk/rerun/log_deprecated/scalar.py
  rerun_py/rerun_sdk/rerun/log_deprecated/tensor.py
  rerun_py/rerun_sdk/rerun/log_deprecated/text.py
  tests/python/test_api/main.py
Labels: 🐍 python API, exclude from changelog

#3603 Add upcasting support to `ClassDescription`
  crates/re_types/definitions/rerun/datatypes/class_description.fbs
  examples/python/face_tracking/main.py
  examples/python/human_pose_tracking/main.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/datatypes/class_description.py
  rerun_py/rerun_sdk/rerun/datatypes/class_description_ext.py
Labels: 🐍 python API, include in changelog

#3605 Use tau for rotations in Rust
  crates/re_arrow_store/src/arrow_util.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_types/tests/asset3d.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types/tests/transform3d.rs
  tests/rust/roundtrips/transform3d/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 📖 documentation, 🚜 refactor, exclude from changelog

#3610 If keypoints are provided without class_ids, default to class_ids=0
  examples/python/human_pose_tracking/main.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d_ext.py
Labels: 🐍 python API, exclude from changelog

#3613 Bump to alpha.8+dev
  Cargo.lock
  Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
Labels: ⛴ release, exclude from changelog

#3608 Coerce segmentation images to u16 if necessary
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image_ext.py
  rerun_py/tests/unit/test_segmentation_image.py
Labels: 🐍 python API, exclude from changelog

#3370 Update documentation welcome page
  docs/content/index.md
  docs/cspell.json
Labels: 📖 documentation, exclude from changelog

#3623 Update component prefix for AnyBatchValue to .any.value
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/tests/unit/test_any_values.py
Labels: 🐍 python API, examples, exclude from changelog

#3629 Replace the `Origin` comoponent with the `Position` component
  crates/re_sdk/src/lib.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes/arrows3d.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/origin2d.fbs
  crates/re_types/definitions/rerun/components/origin3d.fbs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/origin2d.rs
  crates/re_types/src/components/origin2d_ext.rs
  crates/re_types/src/components/origin3d.rs
  crates/re_types/src/components/origin3d_ext.rs
  crates/re_types/tests/arrows3d.rs
  docs/code-examples/arrow3d_simple.cpp
  docs/code-examples/arrow3d_simple.rs
  docs/code-examples/clear_recursive.cpp
  docs/code-examples/clear_simple.cpp
  docs/content/reference/data_types/.gitattributes
  docs/content/reference/data_types/archetypes/arrows3d.md
  docs/content/reference/data_types/components.md
  docs/content/reference/data_types/components/position3d.md
  docs/content/reference/data_types/datatypes/vec2d.md
  docs/content/reference/data_types/datatypes/vec3d.md
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/origin2d.cpp
  rerun_cpp/src/rerun/components/origin2d.hpp
  rerun_cpp/src/rerun/components/origin2d_ext.cpp
  rerun_cpp/src/rerun/components/origin3d.cpp
  rerun_cpp/src/rerun/components/origin3d.hpp
  rerun_cpp/src/rerun/components/origin3d_ext.cpp
  rerun_py/rerun_sdk/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/origin2d.py
  rerun_py/rerun_sdk/rerun/components/origin3d.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_arrows3d.py
Labels: 🚜 refactor, codegen/idl, exclude from changelog

#3618 Fix `recursive` python method name-clash & fix autocomplete thereof
  crates/re_types/definitions/rerun/archetypes/clear.fbs
  crates/re_types/src/archetypes/clear.rs
  crates/re_types/src/archetypes/clear_ext.rs
  crates/re_types/tests/clear.rs
  rerun_cpp/src/rerun/archetypes/clear.cpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/archetypes/clear_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/clear_ext.py
  rerun_py/tests/unit/test_clear.py
Labels: 🐍 python API, exclude from changelog

#3615 Update python readme
  README.md
  rerun_py/README.md
Labels: 📖 documentation, exclude from changelog

#3632 run odegen to resolve conflict
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
Labels: 🪳 bug, 🐍 python API, 🧑‍💻 dev experience, codegen/idl, exclude from changelog

#3633 Small tweaks to legacy logging API to improve 0.8 compatibility
  rerun_py/rerun_sdk/rerun/log_deprecated/points.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  scripts/run_all.py
Labels: 🐍 python API, exclude from changelog

#3635 Lint against the the problem of writing "the the"
  CHANGELOG.md
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_log_types/src/lib.rs
  crates/re_renderer/examples/outlines.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_viewer_context/src/time_control.rs
  docs/content/reference/viewer/blueprint.md
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
  scripts/lint.py
Labels: 📖 documentation, exclude from changelog

#3611 Update ViewCoordinates and AnnotationContext examples to set timeless=True
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/segmentation_image.rs
  docs/code-examples/annotation-context/example.py
  docs/code-examples/annotation_context_connections.py
  docs/code-examples/annotation_context_connections.rs
  docs/code-examples/annotation_context_rects.py
  docs/code-examples/annotation_context_rects.rs
  docs/code-examples/annotation_context_segmentation.py
  docs/code-examples/annotation_context_segmentation.rs
  docs/code-examples/roundtrips.py
  docs/code-examples/segmentation_image_simple.py
  docs/code-examples/segmentation_image_simple.rs
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  tests/python/test_api/main.py
Labels: 🐍 python API, exclude from changelog

#3637 More aggressive `...` -> `…` linting
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_format/src/arrow.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_query/src/archetype_view.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk/src/web_viewer.rs
  crates/re_space_view_spatial/src/parts/assets3d.rs
  crates/re_types_builder/definitions/reflection.fbs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/objects.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  design/blueprint_store.md
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/logging-rust.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/howto/short-lived-entities.md
  docs/content/reference/sdk-logging-controls.md
  examples/README.md
  examples/python/notebook/requirements.txt
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/script_helpers.py
  scripts/ci/demo_assets/static/index.js
  scripts/lint.py
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#3639 Remove gratuitous np.array inside call to from_quat
  examples/python/arkit_scenes/main.py
Labels: examples, exclude from changelog

#3631 Add Markdown description to demo examples
  examples/python/arkit_scenes/README.md
  examples/python/arkit_scenes/main.py
  examples/python/detect_and_track_objects/main.py
  examples/python/dicom_mri/main.py
  examples/python/dna/main.py
  examples/python/human_pose_tracking/main.py
  examples/python/plots/main.py
  examples/python/structure_from_motion/main.py
Labels: 📖 documentation, examples, exclude from changelog

#3638 First draft of the migration guide
  docs/code-examples/log_line.py
  docs/code-examples/log_line.rs
  docs/code-examples/roundtrips.py
  docs/content/reference/migration-0-9.md
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation, exclude from changelog

#3620 Python docs update: getting-started section
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/python.md
  examples/python/dna/main.py
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3634 Add a how-to guide for using Rerun with custom data
  CHANGELOG.md
  docs/content/howto.md
  docs/content/howto/extend.md
  docs/content/howto/extend/custom-data.md
  docs/content/howto/extend/extend-ui.md
Labels: 📖 documentation, include in changelog

#3627 Python docs update: concepts section
  docs/code-examples/any_values.py
  docs/code-examples/extension-components/example.py
  docs/code-examples/extension-components/example.rs
  docs/content/concepts/annotation-context.md
  docs/content/concepts/batches.md
  docs/content/concepts/entity-component.md
  docs/content/concepts/entity-path.md
  docs/content/concepts/spaces-and-transforms.md
  docs/content/concepts/timelines.md
  docs/content/reference/migration-0-9.md
  rerun_py/pyproject.toml
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3630 Update Rust tutorial & getting started
  docs/content/getting-started/logging-rust.md
  docs/content/getting-started/rust.md
  examples/rust/dna/Cargo.toml
  examples/rust/dna/src/main.rs
Labels: 📖 documentation, exclude from changelog

#3646 Add missing field docs
  crates/re_types/definitions/rerun/archetypes/text_log.fbs
  crates/re_types/definitions/rerun/datatypes.fbs
  crates/re_types/definitions/rerun/datatypes/angle.fbs
  crates/re_types/definitions/rerun/datatypes/class_description_map_elem.fbs
  crates/re_types/definitions/rerun/datatypes/float32.fbs
  crates/re_types/definitions/rerun/datatypes/keypoint_pair.fbs
  crates/re_types/definitions/rerun/datatypes/scale3d.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_dimension.fbs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_types/src/datatypes/class_description_map_elem.rs
  crates/re_types/src/datatypes/float32.rs
  crates/re_types/src/datatypes/keypoint_pair.rs
  crates/re_types/src/datatypes/tensor_dimension.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  rerun_cpp/src/rerun/archetypes/text_log.hpp
  rerun_cpp/src/rerun/datatypes/class_description_map_elem.hpp
  rerun_cpp/src/rerun/datatypes/float32.cpp
  rerun_cpp/src/rerun/datatypes/float32.hpp
  rerun_cpp/src/rerun/datatypes/keypoint_pair.hpp
  rerun_cpp/src/rerun/datatypes/tensor_dimension.hpp
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/datatypes/class_description_map_elem.py
  rerun_py/rerun_sdk/rerun/datatypes/float32.py
  rerun_py/rerun_sdk/rerun/datatypes/keypoint_pair.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_dimension.py
Labels: 📖 documentation, codegen/idl, exclude from changelog

#3652 fix linting error
  docs/content/getting-started/logging-rust.md
  docs/content/howto/extend.md
Labels: 🪳 bug, exclude from changelog

#3657 Asset3D: add explicit `path` or `contents` parameter
  docs/code-examples/asset3d_out_of_tree.py
  docs/code-examples/asset3d_simple.py
  examples/python/signed_distance_fields/main.py
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  rerun_py/tests/unit/test_asset3d.py
Labels: 🐍 python API, exclude from changelog

#3663 Fix crates publish
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_release_crates.yml
  crates/re_viewer/build.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#3660 Remove COMPONENT_PREFIX from AnyValuesBatch
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/tests/unit/test_any_values.py
Labels: 🐍 python API, exclude from changelog

#3669 Improve transform conversion errors
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  rerun_py/tests/unit/test_expected_warnings.py
Labels: 🐍 python API, exclude from changelog

#3670 Add obj mesh support to viewer
  crates/re_renderer/src/importer/obj.rs
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_types/definitions/rerun/archetypes/asset3d.fbs
  crates/re_types/src/archetypes/asset3d.rs
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
Labels: enhancement, 📺 re_viewer, include in changelog

#3672 Make it possible to use the Batch constructor strictly internally when we want it to raise
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/error_utils.py
  rerun_py/tests/unit/test_expected_warnings.py
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3667 Updated notebook docs
  docs/content/howto/notebook.md
  examples/python/notebook/blueprint.ipynb
Labels: 📖 documentation, exclude from changelog

#3654 Minor docs improvements
  docs/content/concepts/annotation-context.md
  docs/content/concepts/entity-component.md
  docs/content/concepts/entity-path.md
  docs/content/reference/types.md
Labels: 📖 documentation, exclude from changelog

#3680 Renamed "Loggable Types" section name to "Types"
  docs/code-examples/README.md
  docs/content/reference/types.md
Labels: 📖 documentation, exclude from changelog

#3662 Touchups to the docs index page
  docs/content/index.md
Labels: 📖 documentation, exclude from changelog

#3676 Show transform arrows for entities with only Transform3D-related components
  crates/re_space_view_spatial/src/heuristics.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, exclude from changelog

#3681 Fix presence of segmentation images and tensor causing generation of root space view
  crates/re_viewport/src/space_view_heuristics.rs
  examples/python/controlnet/main.py
  examples/python/face_tracking/main.py
  examples/python/multiprocessing/main.py
  examples/python/multithreading/main.py
  examples/python/segment_anything_model/main.py
  scripts/run_all.py
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#3682 Add doc-link to `ImageEncoded` from `compress`
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3678 Refactor the generated python docs
  rerun_py/docs/SUMMARY.txt
  rerun_py/docs/gen_common_index.py
  rerun_py/docs/gen_package_index.py
  rerun_py/docs/package/index.md
  rerun_py/mkdocs.yml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/recording.py
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3686 Add the demo data utilities to the docs
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation, exclude from changelog

#3685 Short rust migration guide
  docs/content/reference/migration-0-9.md
Labels: 📖 documentation, exclude from changelog

#3687 Fixed links to python docs
  docs/content/concepts/annotation-context.md
  docs/content/concepts/apps-and-recordings.md
  docs/content/concepts/batches.md
  docs/content/concepts/entity-component.md
  docs/content/concepts/spaces-and-transforms.md
  docs/content/concepts/timelines.md
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/python.md
  docs/content/howto/limit-ram.md
  docs/content/howto/notebook.md
  docs/content/reference/migration-0-9.md
  docs/content/reference/sdk-operating-modes.md
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation, exclude from changelog

#3690 Remove backticks from markdown headings
  docs/content/concepts/entity-component.md
  docs/content/getting-started/logging-python.md
  docs/content/howto/limit-ram.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/reference/migration-0-9.md
  docs/content/reference/sdk-micro-batching.md
  docs/content/reference/sdk-operating-modes.md
Labels: 📖 documentation, exclude from changelog

#3691 Remove event log from docs
  docs/content/reference/viewer/overview.md
  docs/content/reference/viewer/selection.md
Labels: 📖 documentation, exclude from changelog

#3694 Fixes for viewport documentation
  docs/content/reference/viewer/viewport.md
Labels: 📖 documentation, exclude from changelog

#3692 Add alternate download location for RGBD dataset
  examples/python/rgbd/main.py
Labels: 🐍 python API, examples, include in changelog

#3695 Update the contents of the ros howto
  docs/content/howto/ros2-nav-turtlebot.md
  examples/python/ros_node/requirements.txt
  examples/python/ros_node/rerun_urdf.py
Labels: 📖 documentation, exclude from changelog

#3696 Connect to 127.0.0.1 when checking for existing viewer
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 🪳 bug, 🐍 python API, exclude from changelog

#3702 Fix strange input box in DNA demo caused by trailing backticks
  examples/python/dna/main.py
Labels: 🪳 bug, examples, exclude from changelog

#3704 Fix link to AsComponents
  docs/content/howto/extend/custom-data.md
Labels: 🪳 bug, 📖 documentation, exclude from changelog

#3714 Fix a bunch of lints found by Rust 1.73
  crates/re_arrow_store/src/store_dump.rs
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/lib.rs
  crates/re_log_types/src/load_file.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/global_bindings.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/assets3d.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_time_panel/src/paint_ticks.rs
  crates/re_time_panel/src/time_selection_ui.rs
  crates/re_types_builder/src/objects.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_ui/src/toasts.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, exclude from changelog

#3721 Fix broken link to migration guide
  CHANGELOG.md
Labels: 📖 documentation, exclude from changelog

#3722 Run linkinator and spell-check on all markdown documents
  .github/workflows/documentation.yaml
  CHANGELOG.md
  crates/re_analytics/README.md
  examples/python/README.md
  rerun_py/README.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#3719 Added support for PyTorch array to `Boxes2D`'s `array` convenience argument
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  rerun_py/requirements-lint.txt
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d_ext.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_box2d.py
Labels: 🪳 bug, 🐍 python API, include in changelog

#3720 Fix default stroke width handling in `log_line_strip_Xd` and `log_obbs`
  rerun_py/rerun_sdk/rerun/log_deprecated/__init__.py
  rerun_py/rerun_sdk/rerun/log_deprecated/bounding_box.py
  rerun_py/rerun_sdk/rerun/log_deprecated/lines.py
Labels: 🪳 bug, 🐍 python API, include in changelog

#3727 Warn/raise when passing incompatible objects to log
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/tests/unit/test_expected_warnings.py
Labels: 🐍 python API, include in changelog

#3724 Add checkbox to PR template to remind about better PR titles
  .github/pull_request_template.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#3725 Refactor `rerun.AnyValues to handle `None` input more gracefully
  rerun_py/mkdocs.yml
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  rerun_py/rerun_sdk/rerun/error_utils.py
  rerun_py/rerun_sdk/rerun/log_deprecated/extension_components.py
  rerun_py/rerun_sdk/rerun/log_deprecated/lines.py
  rerun_py/rerun_sdk/rerun/log_deprecated/points.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  rerun_py/rerun_sdk/rerun/log_deprecated/tensor.py
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
  rerun_py/tests/unit/test_any_values.py
  rerun_py/tests/unit/test_depth_image.py
  rerun_py/tests/unit/test_image.py
  rerun_py/tests/unit/test_segmentation_image.py
  rerun_py/tests/unit/test_tensor.py
Labels: 🐍 python API, include in changelog

#3740 rr.ClearEntity -> rr.Clear in docs
  docs/content/howto/short-lived-entities.md
Labels: 🪳 bug, 📖 documentation, exclude from changelog

#3732 Turn on `AccessKit` accessibility integration
  Cargo.lock
  Cargo.toml
Labels: enhancement, 📺 re_viewer, include in changelog

#3734 Fix return type of `entity_path!()` and `entity_path_vec!()` on empty input.
  crates/re_log_types/src/path/mod.rs
Labels: 🪳 bug, 🦀 rust SDK, include in changelog

#3674 Add torch.tensors to assorted archetype inputs in unit tests
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_depth_image.py
  rerun_py/tests/unit/test_image.py
  rerun_py/tests/unit/test_line_strips2d.py
  rerun_py/tests/unit/test_line_strips3d.py
  rerun_py/tests/unit/test_matnxn.py
  rerun_py/tests/unit/test_segmentation_image.py
  rerun_py/tests/unit/test_transform3d.py
  scripts/requirements-dev.txt
Labels: 🔨 testing, 🐍 python API, exclude from changelog

#3729 Update to ewebsock 0.4.0
  Cargo.lock
  Cargo.toml
  crates/re_data_source/src/web_sockets.rs
  crates/re_sdk_comms/Cargo.toml
  crates/re_sdk_comms/src/server.rs
  crates/re_ws_comms/src/client.rs
  crates/re_ws_comms/src/lib.rs
  crates/re_ws_comms/src/server.rs
Labels: dependencies, include in changelog

#3763 Update `winit` to 0.28.7 (addresses a Sonoma-related UI glitch on startup)
  Cargo.lock
  Cargo.toml
Labels: 🪳 bug, ui, include in changelog

#3766 Fix `arrow3d_simple` screenshot
  crates/re_types/definitions/rerun/archetypes/arrows3d.fbs
  crates/re_types/src/archetypes/arrows3d.rs
  docs/content/reference/types/archetypes/arrows3d.md
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
Labels: 📖 documentation, examples, exclude from changelog

#3747 Add docs about 'rerun/' being reserved
  docs/content/concepts/entity-path.md
  rerun_py/rerun_sdk/rerun/_log.py
Labels: 📖 documentation, include in changelog

#3769 1D tensors as bar charts
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_tensor/src/view_part_system.rs
Labels: 🧑‍💻 dev experience, 🦟 regression, include in changelog

#3771 Update README.md with high-resolution screenshot
  README.md
Labels: 📖 documentation, exclude from changelog

#3748 Display space views using view coordinates from closest ancestor.
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 📺 re_viewer, include in changelog

#3765 Remove unused `.isort.cfg` file
  .isort.cfg
Labels: 🧑‍💻 dev experience, exclude from changelog

#3772 `MediaType::guess_from_path`: enforce `.obj` extension to be Wavefront Obj
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/components/media_type_ext.rs
  docs/code-examples/asset3d_simple.cpp
  docs/code-examples/asset3d_simple.py
  docs/code-examples/asset3d_simple.rs
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#3749 Only grow 3d view bounds with projected image if image plane has been user-edited
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/images.rs
Labels: 📺 re_viewer, include in changelog

#3768 Replace `list(zip(...))` with `np.stack(..., axis=1)`
  docs/content/getting-started/logging-python.md
  examples/python/dna/main.py
  rerun_py/rerun_sdk/rerun_demo/data.py
Labels: examples, exclude from changelog

#3775 Fix crash when loading huge image
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
Labels: 🔺 re_renderer, 💣 crash, include in changelog

#3767 Fix performance regression when viewing images and tensors
  crates/re_arrow_store/src/lib.rs
  crates/re_data_store/src/instance_path.rs
  crates/re_data_store/src/versioned_instance_path.rs
  crates/re_data_ui/src/image.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/tensor/tensor_decode_cache.rs
  crates/re_viewer_context/src/tensor/tensor_stats.rs
  crates/re_viewer_context/src/tensor/tensor_stats_cache.rs
Labels: 🪳 bug, 📉 performance, 🦟 regression, include in changelog

#3784 Bugfix: still need to grow view bounds when the space view is 2D
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 🦟 regression, exclude from changelog

#3781 Fix cspell situation
  .github/workflows/documentation.yaml
  CHANGELOG.md
  design/batching.md
  design/blueprint_store.md
  design/component_datatypes.md
  docs/cspell.json
  examples/python/shape_pointe/README.md
  examples/python/simplerecon/README.md
  rerun_py/ARCHITECTURE.md
Labels: 🪳 bug, 😤 annoying, exclude from changelog

#3777 Re-export RecordingStreamError
  clippy.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk/src/web_viewer.rs
  crates/re_web_viewer_server/src/lib.rs
  crates/re_ws_comms/src/lib.rs
  scripts/clippy_wasm/clippy.toml
Labels: 🦀 rust SDK, include in changelog

#3730 Optimize gathering of point cloud colors
  Cargo.lock
  crates/re_arrow_store/benches/arrow2.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_row.rs
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_viewer_context/src/annotations.rs
Labels: 📉 performance, include in changelog

#3760 Document `DisconnectedSpaces` boolean
  crates/re_types/definitions/rerun/components/disconnected_space.fbs
  crates/re_types/src/components/disconnected_space.rs
  docs/code-examples/disconnected_space.py
  rerun_cpp/src/rerun/components/disconnected_space.hpp
  rerun_py/rerun_sdk/rerun/archetypes/disconnected_space.py
  rerun_py/rerun_sdk/rerun/archetypes/disconnected_space_ext.py
  rerun_py/rerun_sdk/rerun/components/disconnected_space.py
  rerun_py/rerun_sdk/rerun/components/disconnected_space_ext.py
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
  rerun_py/tests/unit/test_disconnected_space.py
  tests/python/roundtrips/disconnected_space/main.py
  tests/python/test_api/main.py
Labels: 📖 documentation, 🐍 python API, include in changelog

#3779 Show all entities/components in the Streams UI, even if empty for the selected timeline
  crates/re_data_ui/src/instance_path.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: ui, include in changelog

#3789 Refactor our `build.rs` files
  crates/re_analytics/build.rs
  crates/re_build_tools/src/lib.rs
  crates/re_build_tools/src/rebuild_detector.rs
  crates/re_data_source/build.rs
  crates/re_renderer/build.rs
  crates/re_sdk/build.rs
  crates/re_types/build.rs
  crates/re_types_builder/build.rs
  crates/re_viewer/build.rs
  crates/re_web_viewer_server/build.rs
  crates/rerun-cli/build.rs
  crates/rerun/build.rs
  examples/rust/objectron/build.rs
  rerun_py/build.rs
Labels: 🚜 refactor, include in changelog

#3815 Never include the pinhole / camera part in a 2D space view
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/mod.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
Labels: 📺 re_viewer, 😤 annoying, include in changelog

#3705 Fix open photogrammetry example not working on Windows
  examples/python/open_photogrammetry_format/main.py
  scripts/lint.py
Labels: 🪳 bug, examples, 🪟 windows, include in changelog

#3801 Pass over zombie TODOs for `0.9.1`
  crates/re_arrow_store/src/store_write.rs
  crates/re_log_types/src/data_table.rs
  crates/re_tuid/src/lib.rs
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
Labels: 🪳 bug, exclude from changelog

#3814 Less automatic `build.rs` shenanigans
  crates/re_build_info/src/build_info.rs
  crates/re_build_tools/src/git.rs
  crates/re_build_tools/src/lib.rs
  crates/re_build_tools/src/rebuild_detector.rs
  crates/re_types/Cargo.toml
  crates/re_types/build.rs
  crates/re_types_builder/build.rs
  crates/re_types_builder/src/lib.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/build.rs
Labels: 🧑‍💻 dev experience, include in changelog

#3818 Get rid of unreadable TODO-regex in `lint.py`
  scripts/lint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3787 Version bump + last parallel crate fixes
  Cargo.lock
  Cargo.toml
  crates/re_renderer/Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/template/Cargo.toml
  scripts/ci/crates.py
  scripts/ci/dag.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#3821 Don't create 3D space view if there's a pinhole camera at the origin
  crates/re_space_view_spatial/src/space_view_3d.rs
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#3811 Include origin of cameras that are part of scene when computing view bounds
  crates/re_space_view_spatial/src/parts/cameras.rs
Labels: 📺 re_viewer, 😤 annoying, include in changelog

#3799 Add scary warning that default recording_id = authkey
  rerun_py/rerun_sdk/rerun/__init__.py
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3689 Fix release workflow
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_publish_web.yml
  .github/workflows/reusable_deploy_docs.yml
  scripts/ci/crates.py
Labels: 🧑‍💻 dev experience, ⛴ release, exclude from changelog

#3826 Fix release process (part 2)
  .github/workflows/release.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3828 Fix release process (part 3)
  .github/workflows/release.yml
  .github/workflows/reusable_release_crates.yml
  scripts/ci/requirements-crates.txt
  scripts/ci/requirements.txt
Labels: 🧑‍💻 dev experience, exclude from changelog

#3829 Fix release process (part 4)
  .github/workflows/release.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3830 Fix release process (part 5)
  scripts/ci/requirements-crates.txt
Labels: 🧑‍💻 dev experience, exclude from changelog

#3822 Improve heuristics around 2D vs 3D space-view creation
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
Labels: 📺 re_viewer, 😤 annoying, include in changelog

#3819 Fix selection history right-click menu not working
  crates/re_viewer/src/ui/selection_history_ui.rs
Labels: 🪳 bug, 📺 re_viewer, 😤 annoying, include in changelog

#3825 Clean up some dependencies
  Cargo.lock
  Cargo.toml
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/picking.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_ui/Cargo.toml
  docs/code-examples/Cargo.toml
  rerun_py/Cargo.toml
  rerun_py/pyproject.toml
Labels: dependencies, exclude from changelog

#3833 Remove unsued `EntityPathOpMsg`
  crates/re_data_store/src/store_db.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_viewer/src/saving.rs
Labels: 🚜 refactor, exclude from changelog

#3836 Improve comments from #3822
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
Labels: 📺 re_viewer, exclude from changelog

#3844 Remove no longer used crate dependencies
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_ui/Cargo.toml
Labels: dependencies, exclude from changelog

#3802 VSCode: migrate to the new Python extensions
  .vscode/extensions.json
  .vscode/settings.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#3835 `--max-frame` support for tracking examples
  examples/python/detect_and_track_objects/main.py
  examples/python/human_pose_tracking/main.py
  scripts/run_all.py
Labels: 🧑‍💻 dev experience, examples, include in changelog

#3851 Expand C++ style guide
  CODE_STYLE.md
Labels: 📖 documentation, 🧑‍💻 dev experience, C/C++ SDK, exclude from changelog

#3838 C++ time & timeless support
  .github/workflows/reusable_checks.yml
  .gitignore
  CMakeLists.txt
  crates/re_sdk/src/recording_stream.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/rerun_c/Cargo.toml
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  docs/code-examples/CMakeLists.txt
  docs/code-examples/arrow3d_simple.cpp
  docs/code-examples/clear_recursive.cpp
  docs/code-examples/clear_simple.cpp
  docs/code-examples/cpp_build_all.sh
  docs/code-examples/point2d_random.cpp
  docs/code-examples/point3d_random.cpp
  docs/code-examples/transform3d_simple.cpp
  examples/cpp/CMakeLists.txt
  examples/cpp/README.md
  examples/cpp/build_all.sh
  examples/cpp/clock/CMakeLists.txt
  examples/cpp/clock/README.md
  examples/cpp/clock/main.cpp
  examples/cpp/minimal/CMakeLists.txt
  examples/cpp/minimal/README.md
  examples/cpp/minimal/main.cpp
  examples/rust/clock/src/main.rs
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d_ext.cpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/datatypes/angle.hpp
  rerun_cpp/src/rerun/datatypes/rotation3d.hpp
  rerun_cpp/src/rerun/datatypes/scale3d.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_cpp/src/rerun/datatypes/tensor_dimension.hpp
  rerun_cpp/src/rerun/datatypes/tensor_dimension_ext.cpp
  rerun_cpp/src/rerun/datatypes/transform3d.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/generated/datatypes/affix_fuzzer3.hpp
  rerun_cpp/tests/generated/datatypes/affix_fuzzer4.hpp
  rerun_cpp/tests/recording_stream.cpp
  tests/cpp/roundtrips/tensor/main.cpp
  tests/cpp/run_all.sh
Labels: C/C++ SDK, exclude from changelog

#3812 Converting `anyhow` to `this-error` for `re_renderer render_pipeline_pool`
  crates/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
Labels: 🔺 re_renderer, exclude from changelog

#3856 Fix typo in the python logging tutorial
  docs/content/getting-started/logging-python.md
Labels: 📖 documentation, 🐍 python API, exclude from changelog

#3859 Fix examples manifest version detection
  Cargo.lock
  crates/re_build_tools/src/git.rs
  crates/re_build_tools/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/build.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#3853 `arrow2-convert` migration 1: `TUID`, `RowId`, `TableId`
  Cargo.lock
  crates/re_arrow_store/src/store_arrow.rs
  crates/re_arrow_store/src/store_sanity.rs
  crates/re_format/Cargo.toml
  crates/re_format/src/arrow.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/lib.rs
  crates/re_tuid/Cargo.toml
  crates/re_tuid/benches/bench_tuid.rs
  crates/re_tuid/src/arrow.rs
  crates/re_tuid/src/lib.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/components/text_ext.rs
  crates/re_types/src/components/text_log_level_ext.rs
  crates/re_types/src/result.rs
Labels: 🏹 arrow, 📉 performance, 🚜 refactor, exclude from changelog

#3861 Add `RERUN_STRICT` environment variable
  docs/code-examples/roundtrips.py
  pixi.toml
  rerun_cpp/src/rerun/error.cpp
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_py/rerun_sdk/rerun/error_utils.py
  scripts/run_python_e2e_test.py
  tests/roundtrips.py
Labels: 🐍 python API, C/C++ SDK, include in changelog

#3855 `arrow2-convert` migration 2: non-serde blueprint types
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/arrow2_convert.rs
  crates/re_types/.gitattributes
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/auto_space_views.fbs
  crates/re_types/definitions/rerun/blueprint/panel_view.fbs
  crates/re_types/src/blueprint/auto_space_views.rs
  crates/re_types/src/blueprint/mod.rs
  crates/re_types/src/blueprint/panel_view.rs
  crates/re_types/src/blueprint/panel_view_ext.rs
  crates/re_types/src/lib.rs
  crates/re_types/src/testing/blueprint/mod.rs
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/objects.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/blueprint_components/mod.rs
  crates/re_viewer/src/blueprint_components/panel.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewport/src/blueprint_components/mod.rs
  crates/re_viewport/src/blueprint_components/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  rerun_cpp/.gitattributes
  rerun_cpp/src/rerun/blueprint.hpp
  rerun_cpp/src/rerun/blueprint/auto_space_views.cpp
  rerun_cpp/src/rerun/blueprint/auto_space_views.hpp
  rerun_cpp/src/rerun/blueprint/panel_view.cpp
  rerun_cpp/src/rerun/blueprint/panel_view.hpp
  rerun_cpp/tests/generated/blueprint.hpp
  rerun_py/rerun_sdk/rerun/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/auto_space_views.py
  rerun_py/rerun_sdk/rerun/blueprint/panel_view.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/test_types/.gitattributes
  rerun_py/tests/test_types/blueprint/__init__.py
Labels: 🏹 arrow, 🚜 refactor, 🟦 blueprint, exclude from changelog

#3863 Fix examples manifest version detection
  .github/workflows/checkboxes.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_track_size.yml
  .github/workflows/reusable_update_pr_body.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_web_demo.yml
  .github/workflows/reusable_upload_wheels.yml
  Cargo.lock
  crates/re_build_tools/src/git.rs
  crates/re_build_tools/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/build.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#3874 Do not run codegen in `build.rs` scripts
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks.yml
  crates/re_types/Cargo.toml
  crates/re_types/README.md
  crates/re_types/build.rs
  crates/re_types_builder/README.md
  crates/re_types_builder/src/bin/build_re_types.rs
  crates/re_types_builder/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#3541 Support NV12-encoded images
  crates/re_data_ui/src/image.rs
  crates/re_renderer/shader/decodings.wgsl
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/shader/rectangle_vs.wgsl
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/workspace_shaders.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/picking.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/re_types/src/datatypes/tensor_buffer.rs
  crates/re_types/src/datatypes/tensor_buffer_ext.rs
  crates/re_types/src/datatypes/tensor_data_ext.rs
  crates/re_types/src/tensor_data.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/tensor/tensor_stats.rs
  examples/python/nv12/README.md
  examples/python/nv12/main.py
  examples/python/nv12/requirements.txt
  examples/python/requirements.txt
  rerun_cpp/src/rerun/datatypes/tensor_buffer.cpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer_ext.cpp
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  tests/python/nv12image/main.py
  tests/python/nv12image/requirements.txt
  tests/python/requirements.txt
Labels: enhancement, 🔺 re_renderer, 📺 re_viewer, include in changelog

#3880 Fix codegen out-of-date
  crates/re_types/src/datatypes/tensor_buffer.rs
Labels: 🪳 bug, exclude from changelog

#3877 Implement more C++ code-examples
  docs/code-examples/mesh3d_indexed.cpp
  docs/code-examples/mesh3d_partial_updates.cpp
  docs/code-examples/mesh3d_partial_updates.rs
  docs/code-examples/mesh3d_simple.cpp
  docs/code-examples/roundtrips.py
  docs/code-examples/scalar_simple.cpp
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_cpp/src/rerun/as_components.hpp
  rerun_cpp/tests/recording_stream.cpp
Labels: C/C++ SDK, exclude from changelog

#3813 Add basic support for in-app "Quick Start" guides
  crates/re_data_store/src/store_db.rs
  crates/re_log_types/src/lib.rs
  crates/re_viewer/data/quick_start_guides/cpp_native.md
  crates/re_viewer/data/quick_start_guides/how_does_it_work.md
  crates/re_viewer/data/quick_start_guides/python_native.md
  crates/re_viewer/data/quick_start_guides/quick_start_connect.cpp
  crates/re_viewer/data/quick_start_guides/quick_start_connect.py
  crates/re_viewer/data/quick_start_guides/quick_start_connect.rs
  crates/re_viewer/data/quick_start_guides/rust_native.md
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_viewer_context/src/command_sender.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/quick_start_connect.cpp
  docs/code-examples/quick_start_connect.py
  docs/code-examples/quick_start_connect.rs
  docs/code-examples/roundtrips.py
Labels: ui, include in changelog

#3876 Approve all workflow runs for a specific contributor PR
  .github/workflows/auto_approve.yml
  scripts/ci/approve_workflow_runs.py
Labels: 🧑‍💻 dev experience, include in changelog

#3882 Update egui_commonmark to 0.9
  Cargo.lock
  Cargo.toml
Labels: ui, dependencies, include in changelog

#3887 Auto approve workflows (part 3)
  .github/workflows/auto_approve.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3889 Auto approve workflows (part 3)
  .github/workflows/auto_approve.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#3885 Fix jpeg returning None for image_height_width_channels
  crates/re_types/src/datatypes/tensor_data_ext.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, exclude from changelog

#3895 Make sure correct targets for building rerun_c are installed
  .github/actions/setup-rust/action.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
Labels: 🧑‍💻 dev experience, C/C++ SDK, exclude from changelog

#3898 Add warning in the Quick Start guides about Safari breaking Copy to Clipboard
  Cargo.lock
  crates/re_viewer/Cargo.toml
  crates/re_viewer/data/quick_start_guides/python_native.md
  crates/re_viewer/data/quick_start_guides/rust_native.md
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
Labels: 🕸️ web, ui, include in changelog

#3900 Fix `rerun_demo` to stop using deprecated APIs
  rerun_py/rerun_sdk/rerun_demo/__main__.py
  rerun_py/tests/unit/test_rerun_demo.py
Labels: 🪳 bug, include in changelog

#3903 Configure pytest to fail on warnings
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  justfile
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
Labels: 🧑‍💻 dev experience, include in changelog

#3910 C++: turn on `-fsanatize=address` in our debug builds
  CMakeLists.txt
  crates/re_types/src/archetypes/transform3d_ext.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d_ext.rs
  docs/code-examples/roundtrips.py
Labels: C/C++ SDK, exclude from changelog

#3911 Auto-approve workflow run fixes
  .github/workflows/auto_approve.yml
  CONTRIBUTING.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#3914 Implement scalar multiple plots example for C++
  docs/code-examples/roundtrips.py
  docs/code-examples/scalar_multiple_plots.cpp
Labels: examples, C/C++ SDK, exclude from changelog

#3913 C++ example for asset3d_out_of_tree and related cleanup
  .vscode/settings.json
  docs/code-examples/asset3d_out_of_tree.cpp
  docs/code-examples/asset3d_simple.cpp
  docs/code-examples/roundtrips.py
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d_ext.cpp
  rerun_cpp/src/rerun/demo_utils.hpp
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/result.hpp
  tests/cpp/roundtrips/image/main.cpp
Labels: C/C++ SDK, exclude from changelog

#3912 Add "spawn" variants for Quick Start guides
  crates/re_smart_channel/src/receive_set.rs
  crates/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/re_viewer/data/quick_start_guides/cpp_spawn.md
  crates/re_viewer/data/quick_start_guides/python_connect.md
  crates/re_viewer/data/quick_start_guides/python_spawn.md
  crates/re_viewer/data/quick_start_guides/quick_start_spawn.cpp
  crates/re_viewer/data/quick_start_guides/quick_start_spawn.py
  crates/re_viewer/data/quick_start_guides/quick_start_spawn.rs
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  crates/re_viewer/data/quick_start_guides/rust_spawn.md
  crates/re_viewer/src/ui/welcome_screen/welcome_page.rs
  docs/code-examples/Cargo.toml
  docs/code-examples/quick_start_spawn.cpp
  docs/code-examples/quick_start_spawn.py
  docs/code-examples/quick_start_spawn.rs
  docs/code-examples/roundtrips.py
Labels: ui, include in changelog
