Repository rerun-io/rerun, pull requests merged in 2023-02, with the labels that each got.

#1311 Update to eframe 0.21.3 with fix for web text input
  Cargo.lock
  Cargo.toml
Labels: 🪳 bug, dependencies

#1314 Fix some links
  .github/workflows/python.yml
  BUILD.md
  README.md
  examples/rust/objectron/build.rs
  rerun_py/README.md
  rerun_py/docs/gen_common_index.py
  rerun_py/docs/writing_docs.md
  scripts/lint.py
Labels: 📖 documentation

#1319 Only build wheels on push to main or when labeled with the wheel tag
  .github/workflows/python.yml
Labels: 🧑‍💻 dev experience

#1321 Trying to fix the matrix-setup if condition
  .github/workflows/python.yml
Labels: 🧑‍💻 dev experience

#1332 Allow controlling the graphics backend & power preference through standard wgpu env vars
  crates/re_renderer/src/config.rs
  crates/re_viewer/src/lib.rs
Labels: enhancement, 🔺 re_renderer

#1330 Link to SDK operating modes doc in both SDK
  crates/rerun/src/lib.rs
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation, 🐍 python API, 🦀 rust SDK

#1335 Document undocumented environment variables on --help
  crates/rerun/src/run.rs
Labels: 📖 documentation

#1338 Point users to our troubleshooting page on panic
  crates/rerun/src/run.rs
Labels: 📖 documentation, 📺 re_viewer, 💣 crash

#1339 Detailed errors for `include_file!`
  crates/re_renderer/src/file_server.rs
Labels: 🪳 bug, 📺 re_viewer

#1341 Fix path issues when running debug viewer within workspace
  crates/re_renderer/src/file_server.rs
Labels: 🪳 bug, 🔺 re_renderer

#1340 Add signal handler on *nix with troubleshooting and stacktrace
  Cargo.lock
  crates/re_viewer/src/app.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/crash_handler.rs
  crates/rerun/src/lib.rs
  crates/rerun/src/run.rs
Labels: 📖 documentation, 📺 re_viewer, 💣 crash

#1334 Switch ci_docker to a container based on ubuntu 20.04
  .github/workflows/python.yml
  .github/workflows/rust.yml
  ci_docker/Dockerfile
  ci_docker/publish.sh
  rerun_py/requirements-build.txt
Labels: 🧑‍💻 dev experience, dependencies, 🛞 build wheels, 🐧 linux

#1348 Use python3 in the jobs that weren't tested in PR
  .github/workflows/python.yml
Labels: 🧑‍💻 dev experience

#1347 Fix typo in buffered_client.rs
  crates/re_sdk_comms/src/buffered_client.rs
Labels: 📖 documentation

#1359 Texture & buffer call now `destroy` on removal from pool
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_renderer/src/wgpu_resources/buffer_pool.rs
  crates/re_renderer/src/wgpu_resources/dynamic_resource_pool.rs
  crates/re_renderer/src/wgpu_resources/texture_pool.rs
Labels: 🔺 re_renderer

#1360 Rename all instances of `frame_maintenance` to `begin_frame`
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/error_tracker.rs
  crates/re_renderer/src/resource_managers/mesh_manager.rs
  crates/re_renderer/src/resource_managers/resource_manager.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer/src/wgpu_resources/bind_group_layout_pool.rs
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_renderer/src/wgpu_resources/buffer_pool.rs
  crates/re_renderer/src/wgpu_resources/dynamic_resource_pool.rs
  crates/re_renderer/src/wgpu_resources/pipeline_layout_pool.rs
  crates/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
  crates/re_renderer/src/wgpu_resources/sampler_pool.rs
  crates/re_renderer/src/wgpu_resources/shader_module_pool.rs
  crates/re_renderer/src/wgpu_resources/texture_pool.rs
  crates/re_viewer/src/app.rs
Labels: 🔺 re_renderer

#1356 Better time axis on plot view
  CHANGELOG.md
  Cargo.lock
  crates/re_log_types/src/time.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/ui/view_time_series/scene.rs
  crates/re_viewer/src/ui/view_time_series/ui.rs
Labels: ui, 📺 re_viewer

#1365 Add a few more sections to `CODE_STYLE.md`
  CODE_STYLE.md
Labels: 📖 documentation

#1363 Improve the gap-detector
  crates/re_viewer/src/ui/time_panel/time_axis.rs
Labels: 🪳 bug, ui, 📺 re_viewer, 📉 performance

#1368 Refactor analytics
  crates/re_analytics/examples/end_to_end.rs
  crates/re_analytics/src/cli.rs
  crates/re_analytics/src/config_native.rs
  crates/re_analytics/src/events.rs
  crates/re_analytics/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
Labels: 📖 documentation, 🧑‍💻 dev experience

#1370 Fix precision issue when zooming in on the timeline
  crates/re_log_types/src/time_range.rs
  crates/re_viewer/src/ui/time_panel/mod.rs
  crates/re_viewer/src/ui/time_panel/paint_ticks.rs
  crates/re_viewer/src/ui/time_panel/time_ranges_ui.rs
  crates/re_viewer/src/ui/time_panel/time_selection_ui.rs
Labels: ui, 📺 re_viewer, 😤 annoying

#1374 [re_renderer] Interior mutable buffer/texture/bindgroup pools
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/global_bindings.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/renderer/compositor.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_renderer/src/wgpu_resources/buffer_pool.rs
  crates/re_renderer/src/wgpu_resources/dynamic_resource_pool.rs
  crates/re_renderer/src/wgpu_resources/mod.rs
  crates/re_renderer/src/wgpu_resources/texture_pool.rs
  crates/re_viewer/src/ui/view_spatial/ui_renderer_bridge.rs
Labels: 🔺 re_renderer

#1369 Unify the time formatting between the time panel and the plot
  crates/re_log_types/src/time.rs
  crates/re_viewer/src/misc/format_time.rs
  crates/re_viewer/src/misc/mod.rs
  crates/re_viewer/src/ui/time_panel/paint_ticks.rs
  crates/re_viewer/src/ui/view_time_series/ui.rs
Labels: ui, 📺 re_viewer

#1372 Add a test of memory use when logging a lot of big images
  Cargo.lock
  Cargo.toml
  crates/re_arrow_store/Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_int_histogram/Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_query/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  examples/rust/raw_mesh/Cargo.toml
  rerun_py/Cargo.toml
  tests/README.md
  tests/rust/test_image_memory/Cargo.toml
  tests/rust/test_image_memory/src/main.rs
Labels: 🔨 testing, ⛃ re_datastore, 📉 performance

#1378 Use ruff for our python lints
  .flake8
  .github/workflows/python.yml
  .vscode/extensions.json
  .vscode/settings.json
  examples/python/api_demo/main.py
  examples/python/car/main.py
  examples/python/clock/main.py
  examples/python/colmap/main.py
  examples/python/deep_sdf/main.py
  examples/python/dicom/main.py
  examples/python/dna/main.py
  examples/python/minimal/main.py
  examples/python/mp_pose/main.py
  examples/python/multithreading/main.py
  examples/python/nyud/main.py
  examples/python/objectron/download_dataset.py
  examples/python/objectron/main.py
  examples/python/plots/main.py
  examples/python/raw_mesh/main.py
  examples/python/stable_diffusion/huggingface_pipeline.py
  examples/python/stable_diffusion/main.py
  examples/python/tracking_hf_opencv/main.py
  justfile
  rerun_py/docs/gen_common_index.py
  rerun_py/pyproject.toml
  rerun_py/requirements-lint.txt
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/components/annotation.py
  rerun_py/rerun_sdk/rerun/components/arrow.py
  rerun_py/rerun_sdk/rerun/components/box.py
  rerun_py/rerun_sdk/rerun/components/color.py
  rerun_py/rerun_sdk/rerun/components/instance.py
  rerun_py/rerun_sdk/rerun/components/label.py
  rerun_py/rerun_sdk/rerun/components/linestrip.py
  rerun_py/rerun_sdk/rerun/components/point.py
  rerun_py/rerun_sdk/rerun/components/quaternion.py
  rerun_py/rerun_sdk/rerun/components/radius.py
  rerun_py/rerun_sdk/rerun/components/rect2d.py
  rerun_py/rerun_sdk/rerun/components/scalar.py
  rerun_py/rerun_sdk/rerun/components/tensor.py
  rerun_py/rerun_sdk/rerun/components/text_entry.py
  rerun_py/rerun_sdk/rerun/components/vec.py
  rerun_py/rerun_sdk/rerun/log/__init__.py
  rerun_py/rerun_sdk/rerun/log/annotation.py
  rerun_py/rerun_sdk/rerun/log/arrow.py
  rerun_py/rerun_sdk/rerun/log/bounding_box.py
  rerun_py/rerun_sdk/rerun/log/extension_components.py
  rerun_py/rerun_sdk/rerun/log/image.py
  rerun_py/rerun_sdk/rerun/log/lines.py
  rerun_py/rerun_sdk/rerun/log/points.py
  rerun_py/rerun_sdk/rerun/log/rects.py
  rerun_py/rerun_sdk/rerun/log/scalar.py
  rerun_py/rerun_sdk/rerun/log/tensor.py
  rerun_py/rerun_sdk/rerun/log/text.py
  rerun_py/rerun_sdk/rerun/log/transform.py
  rerun_py/rerun_sdk/rerun_demo/__main__.py
  rerun_py/rerun_sdk/rerun_demo/data.py
  rerun_py/tests/unit/api_tests.py
Labels: 🧑‍💻 dev experience

#1371 Analytics: register SDK language and data source
  Cargo.lock
  crates/re_analytics/src/config_web.rs
  crates/re_analytics/src/pipeline_web.rs
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/log_db.rs
  crates/re_log_types/src/encoding.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/session.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/remote_viewer_app.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
  rerun_py/src/python_bridge.rs
Labels: 🦀 rust SDK, 🧑‍💻 dev experience

#1382 `CpuWriteGpuReadBelt` for fast frame by frame memory transfers
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_renderer/src/wgpu_resources/buffer_pool.rs
  crates/re_renderer/src/wgpu_resources/dynamic_resource_pool.rs
  crates/re_renderer/src/wgpu_resources/texture_pool.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/space_view.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/primitives.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
  crates/re_viewer/src/ui/view_spatial/ui_renderer_bridge.rs
Labels: 🔺 re_renderer

#1380 analytics: streamlining host vs. recorder python/rust versions
  crates/re_analytics/src/lib.rs
  crates/re_log_types/src/encoding.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/session.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/src/run.rs
Labels: 🐍 python API, 🦀 rust SDK

#1390 Put all analytics to one bucket
  crates/re_analytics/src/sink_native.rs
  crates/re_viewer/src/viewer_analytics.rs
Labels: 🧑‍💻 dev experience

#1391 Make the native viewer an optional dependency of rerun, re_sdk, rerun_py
  Cargo.lock
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/clap.rs
  crates/re_sdk/src/demo_util.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/session.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  examples/rust/api_demo/Cargo.toml
  examples/rust/dna/src/main.rs
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  rerun_py/Cargo.toml
  rerun_py/src/python_bridge.rs
Labels: 🧑‍💻 dev experience

#1406 Remove derive_more dependency
  Cargo.lock
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_analytics/src/lib.rs
  crates/re_format/Cargo.toml
  crates/re_format/src/arrow.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/component_types/color.rs
  crates/re_log_types/src/component_types/label.rs
  crates/re_log_types/src/component_types/radius.rs
  crates/re_log_types/src/component_types/scalar.rs
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/ui/view_time_series/scene.rs
  deny.toml
Labels: 🧑‍💻 dev experience

#1410 Refactor analytics: more ergonomic API
  .github/workflows/labels.yml
  crates/re_analytics/examples/end_to_end.rs
  crates/re_analytics/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_web_server/src/lib.rs
Labels: 📊 analytics, 🚜 refactor

#1407 Replace `reqwest` with `ureq`
  Cargo.lock
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_analytics/src/pipeline_native.rs
  crates/re_analytics/src/sink_native.rs
  crates/re_log/src/lib.rs
  deny.toml
  examples/rust/raw_mesh/Cargo.toml
Labels: 🧑‍💻 dev experience

#1405 SDK: stream to disk with `save` feature
  crates/re_log_types/src/encoding.rs
  crates/re_sdk/src/clap.rs
  crates/re_sdk/src/file_writer.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/remote_viewer_server.rs
  crates/re_sdk/src/session.rs
  examples/rust/api_demo/src/main.rs
  examples/rust/objectron/src/main.rs
  examples/rust/raw_mesh/src/main.rs
  rerun_py/rerun_sdk/rerun/script_helpers.py
Labels: 🦀 rust SDK, 📉 performance

#1400 [re_renderer] Uniform buffer utility using `CpuWriteGpuReadBelt`
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/global_bindings.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/compositor.rs
  crates/re_renderer/src/renderer/generic_skybox.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/renderer/test_triangle.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_buffer_types.rs
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_renderer/src/wgpu_resources/buffer_pool.rs
  crates/re_renderer/src/wgpu_resources/texture_pool.rs
Labels: 🔺 re_renderer, 🧑‍💻 dev experience, 📉 performance

#1413 Fix expecting always Rgba8Unorm backbuffer on Web & Bgra8Unorm on native
  .vscode/settings.json
  crates/re_renderer/examples/framework.rs
  crates/re_viewer/src/lib.rs
Labels: 🪳 bug, 🔺 re_renderer

#1417 Introduce `DeserializableComponent` trait and high-level `query_latest`
  crates/re_data_store/src/entity_properties.rs
  crates/re_log_types/src/msg_bundle.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_query/src/entity_view.rs
  crates/re_query/src/visit.rs
  crates/re_viewer/src/misc/space_info.rs
  crates/re_viewer/src/misc/transform_cache.rs
  crates/re_viewer/src/ui/data_ui/component_ui_registry.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_heuristics.rs
  crates/re_viewer/src/ui/view_category.rs
Labels: 🏹 arrow, 🧑‍💻 dev experience

#1420 Versioned log streams streams
  Cargo.lock
  Cargo.toml
  crates/re_build_info/src/buid_info.rs
  crates/re_build_info/src/lib.rs
  crates/re_build_info/src/rust_version.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/encoding.rs
  crates/re_viewer/src/viewer_analytics.rs
Labels: enhancement, 🐍 python API, 🦀 rust SDK, 📺 re_viewer

#1411 clippy: dissallow some methods and types
  Cargo.lock
  Cranky.toml
  clippy.toml
  crates/re_analytics/src/pipeline_native.rs
  crates/re_log_types/src/component_types/mesh3d.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/global.rs
  crates/re_sdk/src/session.rs
  run_wasm/src/main.rs
Labels: 🧑‍💻 dev experience

#1409 Send analytics events with callstacks on panics and signals
  Cargo.lock
  Cargo.toml
  crates/re_analytics/src/lib.rs
  crates/re_arrow_store/Cargo.toml
  crates/re_memory/Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_string_interner/Cargo.toml
  crates/re_ui/Cargo.toml
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_ws_comms/Cargo.toml
  crates/rerun/Cargo.toml
  crates/rerun/src/crash_handler.rs
  crates/rerun/src/run.rs
Labels: enhancement, 💣 crash, 📊 analytics

#1425 Remove extreneous `image` features and dependencies
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  crates/re_log/src/lib.rs
  crates/re_log/src/setup.rs
  crates/re_log_types/Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_ui/Cargo.toml
  crates/re_viewer/Cargo.toml
  deny.toml
  examples/rust/objectron/Cargo.toml
  rerun_py/Cargo.toml
  scripts/check.sh
Labels: 🧑‍💻 dev experience

#1416 Use write belt for mesh data gpu upload
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/importer/gltf.rs
  crates/re_renderer/src/importer/obj.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/resource_managers/mesh_manager.rs
  crates/re_viewer/src/misc/mesh_loader.rs
Labels: 🔺 re_renderer

#1429 Remove `show` from Python SDK
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 python API

#1430 Add 2d support for linestrips
  examples/python/api_demo/main.py
  rerun_py/rerun_sdk/rerun/log/lines.py
Labels: 🐍 python API

#1431 Add guidelines for adding dependencies in a PR
  CONTRIBUTING.md
Labels: 📖 documentation, 🧑‍💻 dev experience

#1286 Update log_mesh and log_meshes docs.
  rerun_py/rerun_sdk/rerun/log/mesh.py
Labels: 📖 documentation, 🐍 python API

#1432 Document the changelog management
  .github/pull_request_template.md
  CHANGELOG.md
  RELEASES.md
Labels: 🧑‍💻 dev experience

#1428 Use different artifact names for wasm/js in debug builds
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_build_web_viewer/Cargo.toml
  crates/re_build_web_viewer/README.md
  crates/re_build_web_viewer/src/lib.rs
  crates/re_build_web_viewer/src/main.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/remote_viewer_server.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_web_server/src/main.rs
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/README.md
  crates/re_web_viewer_server/build.rs
  crates/re_web_viewer_server/src/lib.rs
  crates/re_web_viewer_server/src/main.rs
  crates/re_web_viewer_server/web_viewer
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  scripts/build_web.sh
  scripts/check.sh
  scripts/publish_crates.sh
  web_viewer/.gitignore
  web_viewer/README.md
Labels: 🧑‍💻 dev experience

#1433 heuristic for camera frustum length is now based on scene size
  crates/re_data_store/src/editable_auto_value.rs
  crates/re_data_store/src/entity_properties.rs
  crates/re_data_store/src/lib.rs
  crates/re_viewer/src/misc/transform_cache.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/cameras.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
Labels: 📺 re_viewer

#1444 Add option to show performance metrics in the UI in release builds too
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/misc/app_options.rs
Labels: enhancement, ui, 📺 re_viewer

#1440 Fix: don't create a dummy LogDb when opening the Rerun Menu
  crates/re_viewer/src/app.rs
Labels: 🪳 bug, ui, 📺 re_viewer

#1439 Convert view_tensor to use the new native Tensors
  crates/re_log_types/src/component_types/tensor.rs
  crates/re_log_types/src/data.rs
  crates/re_tensor_ops/src/lib.rs
  crates/re_viewer/src/misc/caches/mod.rs
  crates/re_viewer/src/misc/caches/tensor_image_cache.rs
  crates/re_viewer/src/ui/data_ui/image.rs
  crates/re_viewer/src/ui/view_tensor/scene.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: 📉 performance

#1443 Fix type signature for tensor names
  rerun_py/rerun_sdk/rerun/log/tensor.py
Labels: 🐍 python API

#1438 Labels for 3D objects have now a color can now be selected & hovered
  .vscode/settings.json
  crates/re_renderer/shader/point_cloud.wgsl
  crates/re_viewer/src/ui/view_spatial/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/boxes2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/boxes3d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points3d.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
Labels: ui, 📺 re_viewer

#1448 OS independent Zoom factor & serialization thereof
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/misc/app_options.rs
Labels: ui, 📺 re_viewer

#1454 Speed up convesions for color arrays
  rerun_py/rerun_sdk/rerun/color_conversion.py
  rerun_py/rerun_sdk/rerun/components/color.py
Labels: 🐍 python API, 🏹 arrow, 📉 performance

#1452 Remove the python job path filters so that wheels are always buildable
  .github/workflows/python.yml
Labels: 🧑‍💻 dev experience
