Repository rerun-io/rerun, pull requests merged in 2023-04, with the labels that each got.

#1749 Fix logged obb being displayed with half of the requested size
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/boxes3d.rs
Labels: 🪳 bug, 📺 re_viewer

#1747 benchmarks for common vector ops across `smallvec`/`tinyvec`/std
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/vectors.rs
Labels: 🏹 arrow, ⛃ re_datastore, 📊 analytics

#1751 Hover rays for tracked 3D cameras
  crates/re_viewer/src/misc/selection_state.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/cameras.rs
  crates/re_viewer/src/ui/view_spatial/space_camera_3d.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
Labels: enhancement, 📺 re_viewer

#1744 Improve dealing with raw buffers for texture read/write
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/draw_phases/screenshot.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/wgpu_resources/mod.rs
Labels: 🔺 re_renderer, 🧑‍💻 dev experience

#1745 `arrow2` erased refcounted clones benchmarks
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/arrow2.rs
Labels: 🏹 arrow, 📉 performance

#1743 `arrow2` estimated_bytes_size benchmarks
  crates/re_arrow_store/benches/arrow2.rs
Labels: 🏹 arrow, 📉 performance

#1752 Readback depth from GPU picking
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/shader/copy_texture.wgsl
  crates/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/renderer/debug_overlay.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/mod.rs
  crates/re_renderer/src/workspace_shaders.rs
  crates/re_viewer/src/ui/view_spatial/scene/picking.rs
Labels: 🔺 re_renderer, 📺 re_viewer

#1538 Add new ARKitScenes example
  examples/python/arkitscenes/.gitignore
  examples/python/arkitscenes/download_dataset.py
  examples/python/arkitscenes/main.py
  examples/python/arkitscenes/requirements.txt
Labels: examples

#1740 Python SDK: document that we also accept colors in 0-1 floats
  examples/python/arkitscenes/main.py
  rerun_py/rerun_sdk/rerun/log/__init__.py
  rerun_py/rerun_sdk/rerun/log/annotation.py
  rerun_py/rerun_sdk/rerun/log/arrow.py
  rerun_py/rerun_sdk/rerun/log/bounding_box.py
  rerun_py/rerun_sdk/rerun/log/lines.py
  rerun_py/rerun_sdk/rerun/log/mesh.py
  rerun_py/rerun_sdk/rerun/log/points.py
  rerun_py/rerun_sdk/rerun/log/rects.py
  rerun_py/rerun_sdk/rerun/log/scalar.py
  rerun_py/rerun_sdk/rerun/log/text.py
  rerun_py/rerun_sdk/rerun/log/text_internal.py
Labels: 🐍 python API

#1762 Collapse space-view by default if there is only one child
  crates/re_viewer/src/ui/viewport.rs
Labels: ui, 📺 re_viewer

#1763 Always create the log_time timeline
  crates/re_data_store/src/entity_tree.rs
  crates/re_viewer/src/misc/time_control.rs
Labels: 🪳 bug

#1767 Columnar timepoints in data tables and during transport
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/time_point/arrow.rs
  crates/re_log_types/src/time_point/mod.rs
  crates/re_log_types/src/time_point/timeline.rs
Labels: 🏹 arrow, 🧑‍💻 dev experience, 📉 performance

#1765 Fix undo/redo selection shortcut/action changing selection history without changing selection
  crates/re_viewer/src/misc/selection_state.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
Labels: 🪳 bug, 📺 re_viewer

#1768 Don't initialize an SDK session if we are only going to be launching the app
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 python API, 😤 annoying

#1769 Allow torch tensors for log_rigid3
  rerun_py/rerun_sdk/rerun/log/__init__.py
Labels: 🐍 python API

#1770 Option to show scene bounding box
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/view_spatial/scene/primitives.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
  crates/re_viewer/src/ui/view_text/ui.rs
Labels: ui, 📺 re_viewer

#1786 Add typing_extensions to requirements-doc.txt
  rerun_py/requirements-doc.txt
Labels: 📖 documentation

#1783 auto_color class-ids if they are present
  crates/re_viewer/src/ui/annotations.rs
  examples/python/api_demo/main.py
Labels: ui

#1787 Don't run 3rd party bench suites on CI
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/arrow2.rs
  crates/re_arrow_store/benches/arrow2_convert.rs
  crates/re_arrow_store/benches/vectors.rs
Labels: enhancement, 🧑‍💻 dev experience

#1784 Use copilot markers in PR template
  .github/pull_request_template.md
Labels: 🧑‍💻 dev experience

#1778 Always send recording_id as part of LogMsg
  crates/re_data_store/examples/memory_usage.rs
  crates/re_data_store/src/log_db.rs
  crates/re_log_types/benches/msg_encode_benchmark.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/msg_sender.rs
  crates/re_sdk/src/session.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/data_ui/log_msg.rs
  crates/re_viewer/src/ui/event_log_view.rs
  rerun_py/src/arrow.rs
  rerun_py/src/python_bridge.rs
  rerun_py/src/python_session.rs
Labels: 🪳 bug

#1772 Refactor: Add new helper crate `re_log_encoding`
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_data_store/examples/memory_usage.rs
  crates/re_log_encoding/Cargo.toml
  crates/re_log_encoding/README.md
  crates/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/re_log_encoding/src/decoder.rs
  crates/re_log_encoding/src/encoder.rs
  crates/re_log_encoding/src/file_sink.rs
  crates/re_log_encoding/src/lib.rs
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/lib.rs
  crates/re_query/Cargo.toml
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/session.rs
  crates/re_tuid/Cargo.toml
  crates/re_tuid/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/web.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  examples/rust/objectron/Cargo.toml
  rerun_py/Cargo.toml
  scripts/publish_crates.sh
Labels: 🧑‍💻 dev experience, 🚜 refactor

#1788 New example code for facebook research segment anything
  crates/re_viewer/src/ui/data_ui/image.rs
  examples/python/segment_anything/.gitignore
  examples/python/segment_anything/main.py
  examples/python/segment_anything/requirements.txt
Labels: examples

#1796 Implement `re_tuid::Tuid::random()` on web
  Cargo.lock
  crates/re_tuid/Cargo.toml
  crates/re_tuid/src/lib.rs
Labels: 🕸️ web

#1799 ci: fix benchmarks
  .github/workflows/rust.yml
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/arrow2.rs
  crates/re_arrow_store/benches/arrow2_convert.rs
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/benches/vectors.rs
Labels: 🪳 bug, 🔨 testing

#1773 Add `minimal_options` example for Rust SDK
  Cargo.lock
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_options/src/main.rs
Labels: examples

#1797 setup_web.sh supports pacman package manager
  scripts/setup_web.sh
Labels: 🧑‍💻 dev experience

#1806 ci: fix `cargo deny` (`crossbeam-channel` outdated since yesterday's release)
  Cargo.lock
Labels: 🪳 bug, 🧑‍💻 dev experience, 😤 annoying

#1813 Compile with `panic = "abort"`
  Cargo.toml
  clippy.toml
  crates/rerun/src/crash_handler.rs
Labels: 🧑‍💻 dev experience, 📉 performance

#1812 Add `rerun --strict`: crash if any warning or error is logged
  crates/re_log/src/lib.rs
  crates/rerun/src/crash_handler.rs
  crates/rerun/src/run.rs
Labels: 🧑‍💻 dev experience

#1819 Refactor: Remove `TensorTrait`
  .github/workflows/labels.yml
  crates/re_log_types/src/component_types/mod.rs
  crates/re_log_types/src/component_types/tensor.rs
  crates/re_sdk/src/lib.rs
  crates/re_tensor_ops/tests/tensor_tests.rs
  crates/re_viewer/src/misc/caches/mod.rs
  crates/re_viewer/src/misc/caches/tensor_decode_cache.rs
  crates/re_viewer/src/misc/caches/tensor_image_cache.rs
  crates/re_viewer/src/ui/data_ui/image.rs
  crates/re_viewer/src/ui/space_view_heuristics.rs
  crates/re_viewer/src/ui/view_bar_chart/scene.rs
  crates/re_viewer/src/ui/view_category.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_tensor/scene.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
  rerun_py/src/python_bridge.rs
Labels: 🚜 refactor

#1817 End-to-end testing of python logging -> store ingestion
  .github/workflows/python.yml
  Cargo.lock
  crates/re_sdk_comms/src/server.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  justfile
  scripts/run_python_e2e_test.py
Labels: 🔨 testing, 🧑‍💻 dev experience

#1821 Fix e2e test on CI: Don't try to re-build rerun-sdk
  .github/workflows/python.yml
  scripts/run_python_e2e_test.py
Labels: 🧑‍💻 dev experience

#1820 Process 2D points per entities like 3D points
  crates/re_log_types/src/component_types/point.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points3d.rs
Labels: 📉 performance, 🚜 refactor

#1825 New option to disable persistant storage
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
Labels: 📺 re_viewer

#1727 Datastore revamp 1: new indexing model & core datastructures
  Cargo.lock
  Cargo.toml
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/polars_util.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_format.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_sanity.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/src/test_util.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_data_store/src/entity_properties.rs
  crates/re_data_store/src/log_db.rs
  crates/re_int_histogram/Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/component_types/mod.rs
  crates/re_log_types/src/component_types/msg_id.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/lib.rs
  crates/re_memory/Cargo.toml
  crates/re_query/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_query/src/range.rs
  crates/re_renderer/Cargo.toml
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/ui/memory_panel.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
Labels: 🏹 arrow, ⛃ re_datastore, 🚜 refactor

#1735 Datastore revamp 2: serialization & formatting
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_arrow.rs
  crates/re_arrow_store/src/store_format.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/time_point/timeline.rs
Labels: ⛃ re_datastore

#1791 Datastore revamp 5: `DataStore::to_data_tables()`
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/time_range.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: ⛃ re_datastore

#1801 Datastore revamp 7: garbage collection
  Cargo.lock
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_arrow.rs
  crates/re_arrow_store/src/store_dump.rs
  crates/re_arrow_store/src/store_format.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_polars.rs
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_sanity.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/src/test_util.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/log_db.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/path/component_name.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/size_bytes.rs
  crates/re_log_types/src/time_point/mod.rs
  crates/re_log_types/src/time_point/timeline.rs
  crates/re_log_types/src/time_range.rs
  crates/re_query/src/query.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer/src/ui/time_panel/mod.rs
  scripts/lint.py
Labels: ⛃ re_datastore

#1832 Don't assert if inserting a rowid with a matching timepoint does not create a conflict
  crates/re_arrow_store/src/store_write.rs
Labels: 🪳 bug, 🏹 arrow

#1828 re_query: up to date with latest data types and structures
  crates/re_log_types/src/component_types/instance_key.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_query/src/entity_view.rs
  crates/re_query/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_query/src/range.rs
  crates/re_query/src/visit.rs
  crates/re_query/tests/visit_tests.rs
Labels: 🔍 re_query, 📉 performance, 🚜 refactor

#1822 Fix too many points crash
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points3d.rs
Labels: 🪳 bug, 🔺 re_renderer, 📉 performance, 💣 crash, 🦟 regression

#1829 Use GPU picking for line(like) primitives, fix `interactive` flags
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_viewer/src/ui/space_view.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/picking.rs
  crates/re_viewer/src/ui/view_spatial/scene/primitives.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/arrows3d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/boxes2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/boxes3d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/cameras.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/lines2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/lines3d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/meshes.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points2d.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/points3d.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
  crates/re_viewer/src/ui/view_spatial/ui_renderer_bridge.rs
Labels: enhancement, 🔺 re_renderer, 📺 re_viewer

#1836 Reduce memory used by staging belts on Web
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/context.rs
Labels: 🕸️ web, 📉 performance, 💣 crash

#1834 Introduce new MemoryRecording for use with Jupyter notebooks
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/log_sink.rs
  examples/python/notebook/cube.ipynb
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/rerun_sdk/rerun/recording.py
  rerun_py/src/python_bridge.rs
  rerun_py/src/python_session.rs
Labels: 🐍 python API

#1830 Always flush when we remove a sink
  rerun_py/src/python_bridge.rs
  rerun_py/src/python_session.rs
Labels: 🐍 python API

#1835 GPU colormapping, first step
  crates/re_data_store/src/entity_properties.rs
  crates/re_log_types/src/component_types/tensor.rs
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/shader/colormap.wgsl
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/shader/types.wgsl
  crates/re_renderer/src/colormap.rs
  crates/re_renderer/src/importer/gltf.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer/src/wgpu_buffer_types.rs
  crates/re_viewer/src/misc/caches/tensor_image_cache.rs
  crates/re_viewer/src/misc/mod.rs
  crates/re_viewer/src/misc/tensor_to_gpu.rs
  crates/re_viewer/src/ui/annotations.rs
  crates/re_viewer/src/ui/data_ui/image.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: 🔺 re_renderer, 📉 performance, 🚜 refactor

#1838 Install the rerun-sdk in CI using --no-index and split out linux wheel build to run first.
  .github/workflows/python.yml
  scripts/version_util.py
Labels: 🧑‍💻 dev experience

#1841 GPU tensor colormapping
  crates/re_data_store/src/entity_properties.rs
  crates/re_log_types/src/data.rs
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/examples/multiview.rs
  crates/re_renderer/examples/outlines.rs
  crates/re_renderer/examples/picking.rs
  crates/re_renderer/shader/colormap.wgsl
  crates/re_renderer/src/colormap.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_tensor_ops/src/dimension_mapping.rs
  crates/re_viewer/src/gpu_bridge/mod.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/misc/mod.rs
  crates/re_viewer/src/ui/view_spatial/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
  crates/re_viewer/src/ui/view_spatial/ui_renderer_bridge.rs
  crates/re_viewer/src/ui/view_tensor/mod.rs
  crates/re_viewer/src/ui/view_tensor/tensor_slice_to_gpu.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
  scripts/lint.py
Labels: 🔺 re_renderer, 📺 re_viewer, 📉 performance, 🚜 refactor

#1844 Refactor the relationship between the assorted web / websocket servers
  Cargo.lock
  crates/re_viewer/src/remote_viewer_app.rs
  crates/re_viewer/src/web.rs
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/src/lib.rs
  crates/re_web_viewer_server/src/main.rs
  crates/re_ws_comms/Cargo.toml
  crates/re_ws_comms/src/client.rs
  crates/re_ws_comms/src/lib.rs
  crates/re_ws_comms/src/server.rs
  crates/rerun/src/clap.rs
  crates/rerun/src/run.rs
  crates/rerun/src/web_viewer.rs
  examples/python/notebook/cube.ipynb
  rerun_py/Cargo.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
  rerun_py/src/python_session.rs
Labels: 🕸️ web, 🚜 refactor

#1846 Show previews of colormaps when selecting them
  crates/re_viewer/src/gpu_bridge/mod.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/ui/view_tensor/tensor_slice_to_gpu.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: ui, 📺 re_viewer

#1853 Disable wheel tests for x86_64-apple-darwin
  .github/workflows/python.yml
Labels: ⛴ release, 🦟 regression

#1852 Fix typos in notebook readme
  examples/python/notebook/README.md
  examples/python/notebook/cube.ipynb
Labels: 📖 documentation

#1857 Error instead of expect inside msg_encode.
  crates/re_sdk_comms/src/buffered_client.rs
Labels: 🪳 bug

#1854 Restore: New API to reset_time (#1826)
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 python API, 🦟 regression

#1859 Revert "Implement billinear filtering of textures (#1850)"
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: 🪳 bug, 🔺 re_renderer, 🦟 regression

#1802 Add Restart command and keyboard shortcut for moving time to start of timeline
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/misc/time_control.rs
Labels: 📺 re_viewer

#1861 Fix shutdown race condition in `re_sdk_comms` client
  crates/re_sdk_comms/src/buffered_client.rs
Labels: 🪳 bug

#1863 Remove unused dependencies
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_format/Cargo.toml
  rerun_py/Cargo.toml
Labels: 🧑‍💻 dev experience, dependencies

#1849 Gpu picking for depth clouds
  .vscode/settings.json
  crates/re_log_types/src/component_types/instance_key.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/shader/depth_cloud.wgsl
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/picking.rs
  crates/re_viewer/src/ui/view_spatial/scene/primitives.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
Labels: enhancement, 🔺 re_renderer, 📺 re_viewer

#1869 Remove manual depth projection from car and nyud examples
  examples/python/car/main.py
  examples/python/nyud/main.py
Labels: examples

#1862 Improve end-to-end testing slightly
  .github/workflows/python.yml
  scripts/run_python_e2e_test.py
Labels: 🧑‍💻 dev experience

#1860 Re-enable bilinear interpolation again
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/shader/rectangle_vs.wgsl
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/workspace_shaders.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: 🔺 re_renderer

#1865 Use GPU colormapping when showing images in the GUI
  crates/re_data_store/src/entity_properties.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/component_types/mod.rs
  crates/re_log_types/src/component_types/tensor.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/misc/caches/mod.rs
  crates/re_viewer/src/misc/caches/tensor_image_cache.rs
  crates/re_viewer/src/ui/annotations.rs
  crates/re_viewer/src/ui/data_ui/component.rs
  crates/re_viewer/src/ui/data_ui/component_ui_registry.rs
  crates/re_viewer/src/ui/data_ui/image.rs
  crates/re_viewer/src/ui/data_ui/instance_path.rs
  crates/re_viewer/src/ui/data_ui/mod.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: ui

#1872 Turn off benchmakrs comment on each PR
  .github/workflows/rust.yml
Labels: 🧑‍💻 dev experience

#1866 Refactor: remove `GpuTexture2DHandle::invalid`
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_viewer/src/gpu_bridge/mod.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/ui/view_spatial/scene/picking.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
Labels: 🚜 refactor

#1874 Update enumflags2 to non-yanked version
  .github/workflows/labels.yml
  .github/workflows/rust.yml
  Cargo.lock
  deny.toml
  scripts/check.sh
Labels: dependencies

#1881 [notebook] Make presentation_id consistent and use data-attribute for rrd
  rerun_py/rerun_sdk/rerun/recording.py
Labels: 🕸️ web

#1886 Fix filtering artifact for non-color images
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
Labels: 🔺 re_renderer

#1876 Fix broken instance picking in presence of images
  crates/re_viewer/src/ui/view_spatial/ui.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#1884 Remember to decode JPEGs
  crates/re_log_types/src/component_types/mod.rs
  crates/re_log_types/src/component_types/tensor.rs
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/misc/caches/mod.rs
  crates/re_viewer/src/misc/caches/tensor_decode_cache.rs
  crates/re_viewer/src/ui/data_ui/image.rs
  crates/re_viewer/src/ui/space_view.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_tensor/scene.rs
  crates/re_viewer/src/ui/view_tensor/tensor_slice_to_gpu.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: 🪳 bug

#1896 Fix double-negation in scripts/run_python_e2e_test.py
  scripts/run_python_e2e_test.py
Labels: 🧑‍💻 dev experience

#1900 Refactor: Add helper functions to GpuTexture2DHandle
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/src/importer/gltf.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/mod.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_viewer/src/gpu_bridge/mod.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/ui/view_tensor/tensor_slice_to_gpu.rs
Labels: 🔺 re_renderer, 🚜 refactor

#1909 Fix crash in save-to-file
  crates/re_arrow_store/src/store_dump.rs
Labels: ⛃ re_datastore, 💣 crash

#1901 Improve PR template with better comment, and no copilot per default
  .github/pull_request_template.md
Labels: 🧑‍💻 dev experience

#1914 Don't clean up LogDbs that only contain a BeginRecordingMsg
  crates/re_data_store/src/log_db.rs
  crates/re_viewer/src/app.rs
Labels: 🪳 bug

#1912 Optimize generate_changelog.py
  scripts/generate_changelog.py
Labels: 🧑‍💻 dev experience

#1915 Update docs related to notebook
  rerun_py/docs/gen_common_index.py
  rerun_py/mkdocs.yml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording.py
Labels: 📖 documentation

#1911 Fix double clicking camera no longer focusing on said camera
  crates/re_viewer/src/misc/selection_state.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/primitives.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/cameras.rs
  crates/re_viewer/src/ui/view_spatial/space_camera_3d.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_spatial/ui_2d.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#1908 Fix picking entities with image + another object (or label) twice
  crates/re_viewer/src/ui/view_spatial/scene/picking.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression

#1920 Smooth out scroll wheel input for camera zooming
  .vscode/settings.json
  crates/re_viewer/src/ui/view_spatial/eye.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
Labels: enhancement, 📺 re_viewer

#1922 Always spawn instead of fork (See: #1921)
  examples/python/multiprocessing/main.py
Labels: 🪳 bug

#1923 `--num-frames` arg for canny/webcam example
  examples/python/opencv_canny/main.py
Labels: examples

#1926 Collect extra egui features into the main Cargo.toml
  Cargo.toml
  crates/re_ui/Cargo.toml
  crates/re_viewer/Cargo.toml
Labels: 🧑‍💻 dev experience

#1927 `just py-run-all-{native|web|rrd}`
  examples/.gitignore
  examples/python/api_demo/main.py
  examples/python/arkitscenes/main.py
  examples/python/car/main.py
  examples/python/clock/main.py
  examples/python/colmap/main.py
  examples/python/deep_sdf/main.py
  examples/python/dicom/main.py
  examples/python/dna/main.py
  examples/python/minimal/main.py
  examples/python/mp_pose/main.py
  examples/python/multiprocessing/main.py
  examples/python/multithreading/main.py
  examples/python/notebook/cube.ipynb
  examples/python/nyud/main.py
  examples/python/objectron/main.py
  examples/python/opencv_canny/main.py
  examples/python/plots/main.py
  examples/python/raw_mesh/main.py
  examples/python/segment_anything/main.py
  examples/python/stable_diffusion/main.py
  examples/python/text_logging/main.py
  examples/python/tracking_hf_opencv/main.py
  justfile
Labels: 🔨 testing, 🧑‍💻 dev experience, examples

#1934 Join threads at end of multi-threading example
  examples/python/multithreading/main.py
Labels: enhancement, examples

#1925 Add argument parsing to the rerun_demo
  rerun_py/rerun_sdk/rerun_demo/__main__.py
Labels: examples

#1939 More robust wait for exit condition during .serve()
  rerun_py/rerun_sdk/rerun/script_helpers.py
Labels: 🐍 python API

#1936 Use zipfile python library instead of `unzip` command in arkitscene
  examples/python/arkitscenes/download_dataset.py
Labels: examples

#1933 Fix annotation images sometimes drawn in the background.
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/picking.rs
  crates/re_viewer/src/ui/view_spatial/scene/primitives.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
  crates/re_viewer/src/ui/view_spatial/ui_renderer_bridge.rs
Labels: 📺 re_viewer, 😤 annoying

#1938 Fix backslashes in arkitscene rigid transformation path
  examples/python/arkitscenes/main.py
Labels: examples

#1943 Fix hovering depth clouds
  crates/re_viewer/src/ui/view_spatial/scene/mod.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_spatial/ui.rs
Labels: 📺 re_viewer, 🦟 regression

#1944 2.5GB before GC kick in on web
  crates/re_viewer/src/web.rs
Labels: 🕸️ web

#1948 Lint error names in `map_err`
  crates/re_log_types/src/arrow_msg.rs
  crates/re_web_viewer_server/src/lib.rs
  crates/re_ws_comms/src/server.rs
  crates/rerun/src/run.rs
  rerun_py/src/arrow.rs
  scripts/lint.py
Labels: 🧑‍💻 dev experience

#1950 New dispatch-only workflow for running the lint-job
  .github/workflows/dispatch_lint.yml
Labels: 🧑‍💻 dev experience

#1951 Bump hyper version due to RUSTSEC-2023-0034
  Cargo.lock
Labels: ⛴ release

#1947 Fix crash for missing class ids causing zero sized texture
  Cargo.lock
  crates/re_renderer/Cargo.toml
  crates/re_renderer/examples/2d.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/src/importer/gltf.rs
  crates/re_renderer/src/resource_managers/mod.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_viewer/src/gpu_bridge/mod.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/view_tensor/tensor_slice_to_gpu.rs
  crates/re_viewer/src/ui/view_tensor/ui.rs
Labels: 🪳 bug, 🔺 re_renderer, 📺 re_viewer

#1949 Move clippy_wasm/clippy.toml to under scripts
  clippy.toml
  scripts/clippy_wasm.sh
  scripts/clippy_wasm/clippy.toml
Labels: 🧑‍💻 dev experience

#1952 change crate version to 0.6.0-alpha.0
  Cargo.lock
  Cargo.toml
Labels: 🧑‍💻 dev experience

#1959 Fix run-wasm crash on trying to wait for server
  Cargo.lock
  run_wasm/Cargo.toml
  run_wasm/src/main.rs
Labels: 🧑‍💻 dev experience

#1958 Update egui to latest and wgpu to 0.16
  Cargo.lock
  Cargo.toml
  crates/re_renderer/Cargo.toml
  crates/re_renderer/shader/depth_cloud.wgsl
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/shader/point_cloud.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/shader/types.wgsl
  crates/re_renderer/shader/utils/sphere_quad.wgsl
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/draw_phases/mod.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/draw_phases/screenshot.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/renderer/debug_overlay.rs
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer/src/texture_info.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer/src/wgpu_resources/mod.rs
  crates/re_renderer/src/wgpu_resources/sampler_pool.rs
  crates/re_renderer/src/wgpu_resources/texture_pool.rs
  crates/re_viewer/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer/src/ui/view_time_series/ui.rs
Labels: ui, 🔺 re_renderer

#1953 Handle leaking of prerelease into alpha version
  crates/re_build_info/src/crate_version.rs
Labels: 🪳 bug

#1963 Fix incorrect memory usage stats for destroyed on-creation-mapped buffers
  crates/re_renderer/src/wgpu_resources/dynamic_resource_pool.rs
Labels: 🪳 bug, 🔺 re_renderer

#1954 Introduce new reusable workflow jobs and cleanup manual trigger
  .github/workflows/README.md
  .github/workflows/manual_build_wheels_for_pr.yml
  .github/workflows/manual_dispatch.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_wheels.yml
  .vscode/extensions.json
  crates/re_log_types/src/component_types/arrow_convert_shims.rs
  crates/re_log_types/src/component_types/mod.rs
  scripts/cargo_deny.sh
  scripts/generate_pr_summary.py
  scripts/templates/pr_results_summary.html
  scripts/version_util.py
Labels: 🧑‍💻 dev experience

#1955 Use new CI workflows on pull-request
  .github/workflows/README.md
  .github/workflows/manual_build_wheels_for_pr.yml
  .github/workflows/manual_run_bench.yml
  .github/workflows/misc.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/python.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/rust.yml
  .github/workflows/toml.yml
  .github/workflows/typos.yml
  ci_docker/Dockerfile
  scripts/generate_pr_summary.py
  scripts/generate_prerelease_pip_index.py
  scripts/templates/pip_index.html
  scripts/templates/pr_results_summary.html
Labels: 🧑‍💻 dev experience

#1970 Try making pull-request workflows non-concurrent
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
Labels: 🧑‍💻 dev experience

#1974 Another attempt to make jobs non-concurrent on a per-PR basis
  .github/workflows/manual_build_wheels_for_pr.yml
  .github/workflows/manual_dispatch.yml
  .github/workflows/manual_run_bench.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_test_wheels.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_wheels.yml
Labels: 🧑‍💻 dev experience

#1969 Round to nearest color_index when doing color mapping
  crates/re_renderer/shader/rectangle_fs.wgsl
Labels: 🪳 bug, 🔺 re_renderer

#1965 Full (experimental) WebGPU support
  .cargo/config.toml
  BUILD.md
  Cargo.lock
  Cargo.toml
  crates/re_build_web_viewer/src/lib.rs
  crates/re_build_web_viewer/src/main.rs
  crates/re_renderer/Cargo.toml
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/shader/colormap.wgsl
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/shader/screen_triangle_vertex.wgsl
  crates/re_renderer/shader/types.wgsl
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/wgpu_resources/shader_module_pool.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/web.rs
  crates/re_web_viewer_server/build.rs
Labels: 🔺 re_renderer

#1971 If there's a `{{ pr-build-summary }}` in the PR description, update it.
  .github/pull_request_template.md
  .github/workflows/reusable_pr_summary.yml
  scripts/generate_pr_summary.py
Labels: 🧑‍💻 dev experience

#1972 Run the cube notebook on PR
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_run_notebook.yml
  scripts/generate_pr_summary.py
  scripts/templates/pr_results_summary.html
Labels: 🧑‍💻 dev experience

#1966 Add ability to manually run a web build to upload to an adhoc name
  .github/workflows/manual_adhoc_web.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_upload_web.yml
Labels: 🧑‍💻 dev experience

#1976 Set Rerun viewer native app icon using eframe
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/icons.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_icon.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/native.rs
Labels: 📺 re_viewer, 🪟 windows

#1984 Don't use console.error
  crates/re_log/src/web_logger.rs
Labels: 🪳 bug, 🕸️ web, 💣 crash

#1986 Add keyboard shortcut for "Follow", and stop following on "Restart"
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/misc/time_control.rs
Labels: ui, 📺 re_viewer

#1993 Suggest users open an issue on crash, and other fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .vscode/settings.json
  Cranky.toml
  clippy.toml
  crates/re_build_build_info/src/lib.rs
  crates/re_build_web_viewer/src/lib.rs
  crates/re_renderer/build.rs
  crates/re_tensor_ops/tests/tensor_tests.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_viewer/src/misc/transform_cache.rs
  crates/re_viewer/src/ui/view_spatial/ui_3d.rs
  crates/re_viewer/src/ui/view_time_series/scene.rs
  crates/re_viewer/src/ui/view_time_series/ui.rs
  crates/re_web_viewer_server/build.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/clap.rs
  crates/rerun/src/crash_handler.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer

#2001 Limit ipython to 8.12 in the jupyter example
  examples/python/notebook/requirements.txt
Labels: 🧑‍💻 dev experience
