Repository rerun-io/rerun, pull requests merged in 2023-11, with the labels that each got.

#4108 Improve main README.md, plus other minor fixes
  .github/workflows/contrib_rerun_py.yml
  CHANGELOG.md
  README.md
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_data_store/src/entity_properties.rs
  crates/re_log_types/src/data_table.rs
  crates/re_renderer/src/mesh.rs
  crates/re_renderer/src/resource_managers/mesh_manager.rs
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  docs/code-examples/README.md
  docs/code-examples/image_advanced.py
  docs/content/reference/sdk-operating-modes.md
  examples/README.md
Labels: 📖 documentation, 🚜 refactor, exclude from changelog

#4109 Added a a new lint: duplicated words
  .github/workflows/README.md
  .github/workflows/manual_dispatch.yml
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  crates/re_arrow_store/src/store_gc.rs
  crates/re_build_tools/src/hashing.rs
  crates/re_data_store/Cargo.toml
  crates/re_data_store/README.md
  crates/re_query/tests/archetype_visit_tests.rs
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/draw_phases/outlines.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_sdk/src/demo_util.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_types/src/archetypes/tensor_ext.rs
  crates/re_types/src/components/media_type_ext.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_web_viewer_server/Cargo.toml
  design/space_views.md
  docs/code-examples/asset3d_simple.cpp
  docs/code-examples/asset3d_simple.py
  examples/python/template/README.md
  examples/rust/template/README.md
  rerun_cpp/src/rerun/archetypes/tensor.hpp
  rerun_cpp/src/rerun/archetypes/tensor_ext.cpp
  rerun_cpp/src/rerun/component_batch_adapter.hpp
  rerun_cpp/src/rerun/demo_utils.hpp
  rerun_py/rerun_sdk/rerun/log_deprecated/experimental/blueprint.py
  rerun_py/rerun_sdk/rerun_demo/data.py
  scripts/lint.py
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#4103 Reduce amount of cmake log from building & downloading libArrow
  rerun_cpp/CMakeLists.txt
Labels: 😤 annoying, C/C++ SDK, include in changelog

#4113 Remove duplicate words that span a newline
  crates/re_types_builder/src/codegen/python.rs
  rerun_cpp/src/rerun/config.hpp
  rerun_py/src/python_bridge.rs
Labels: 📖 documentation, exclude from changelog

#4114 Bump to `0.11.0-alpha.1+dev`
  Cargo.lock
  Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/spawn_viewer/Cargo.toml
  examples/rust/template/Cargo.toml
Labels: ⛴ release, exclude from changelog

#4110 C++ Windows CI
  .github/workflows/reusable_checks.yml
  CMakeLists.txt
  docs/code-examples/pinhole_simple.cpp
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
Labels: 🧑‍💻 dev experience, 🪟 windows, include in changelog

#4119 Fix vercel redeploy
  .github/actions/deploy-vercel/index.mjs
  .github/actions/deploy-vercel/manual.mjs
  .github/actions/deploy-vercel/util.mjs
  .github/actions/deploy-vercel/vercel.mjs
Labels: ⛴ release, exclude from changelog, :ship: CI

#4115 Update web build instructions, set .gitattributes to always require lf, fix missing requirement(.txt)
  .gitattributes
  BUILD.md
  docs/cspell.json
  examples/python/arkit_scenes/requirements.txt
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#4120 Add MacOS C++ CI, add Linux C++20 CI
  .github/workflows/cpp_matrix_full.json
  .github/workflows/cpp_matrix_partial.json
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  CMakeLists.txt
  rerun_cpp/CMakeLists.txt
Labels: 🧑‍💻 dev experience, C/C++ SDK, include in changelog

#4129 Link C++ SDK on releases
  .github/workflows/release.yml
Labels: examples, ⛴ release, exclude from changelog

#4135 `warn_once` on stream incompatibility
  crates/re_log_encoding/src/decoder.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, exclude from changelog

#4134 Support std::chrono types for `set_time` on `rerun::RecordingStream`
  docs/code-examples/timelines_example.cpp
  docs/content/getting-started/logging-cpp.md
  docs/cspell.json
  examples/cpp/clock/main.cpp
  examples/cpp/dna/main.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/recording_stream.cpp
Labels: enhancement, C/C++ SDK, include in changelog

#4003 Put web viewer on `npm`
  .github/workflows/on_pull_request.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_npm.yml
  .github/workflows/reusable_publish_npm.yml
  crates/re_build_web_viewer/src/lib.rs
  crates/re_build_web_viewer/src/main.rs
  crates/re_web_viewer_server/build.rs
  rerun_js/web-viewer/.gitignore
  rerun_js/web-viewer/README.md
  rerun_js/web-viewer/index.js
  rerun_js/web-viewer/package.json
  rerun_js/web-viewer/react/README.md
  rerun_js/web-viewer/react/index.js
  rerun_js/web-viewer/react/package.json
  rerun_js/web-viewer/react/tsconfig.json
  rerun_js/web-viewer/scripts/build.mjs
  rerun_js/web-viewer/scripts/common.mjs
  rerun_js/web-viewer/scripts/install.mjs
  rerun_js/web-viewer/scripts/publish.mjs
  rerun_js/web-viewer/scripts/version.mjs
  rerun_js/web-viewer/tsconfig.json
Labels: 🕸️ web, include in changelog

#4139 Pin python docs build dependencies
  rerun_py/requirements-doc.txt
Labels: exclude from changelog, :ship: CI

#4126 Improve rerun_cpp readme & CMakeLists.txt
  CMakeLists.txt
  crates/rerun_c/CMakeLists.txt
  docs/code-examples/CMakeLists.txt
  examples/cpp/clock/CMakeLists.txt
  examples/cpp/custom_component_adapter/CMakeLists.txt
  examples/cpp/dna/CMakeLists.txt
  examples/cpp/minimal/CMakeLists.txt
  examples/cpp/spawn_viewer/CMakeLists.txt
  rerun_cpp/CMakeLists.txt
  rerun_cpp/README.md
  rerun_cpp/download_and_build_arrow.cmake
  rerun_cpp/tests/CMakeLists.txt
  scripts/ci/bundle_and_upload_rerun_cpp.py
  tests/cpp/roundtrips/CMakeLists.txt
Labels: 📖 documentation, 🧑‍💻 dev experience, C/C++ SDK, include in changelog

#4149 Replace the many parameters of `rerun::spawn` / `rerun::RecordingStream::spawn` with a `struct`
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/src/rerun/spawn.cpp
  rerun_cpp/src/rerun/spawn.hpp
  rerun_cpp/src/rerun/spawn_options.cpp
  rerun_cpp/src/rerun/spawn_options.hpp
Labels: enhancement, C/C++ SDK, include in changelog

#4123 Improve Visible History to support more general time queries
  crates/re_data_store/src/entity_properties.rs
  crates/re_data_store/src/store_db.rs
  crates/re_query/src/util.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  tests/python/visible_history_playground/main.py
Labels: ui, include in changelog

#4144 Implement complete test suite for (pending) clear logic
  Cargo.lock
  crates/re_data_store/Cargo.toml
  crates/re_data_store/tests/clear.rs
  crates/re_log_types/src/example_components.rs
Labels: 🔨 testing, exclude from changelog, 🔩 data model

#4147 Reduce rerun_c library size (by depending on fewer unnecessary crates)
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/src/store.rs
  crates/re_data_source/Cargo.toml
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_file.rs
  crates/re_data_source/src/load_file_contents.rs
  crates/re_data_source/src/load_file_path.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/example_components.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/num_instances.rs
  crates/re_log_types/src/path/data_path.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/parse_path.rs
  crates/re_query/Cargo.toml
  crates/re_query/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types_core/src/lib.rs
  crates/rerun/Cargo.toml
  crates/rerun/src/demo_util.rs
  crates/rerun/src/lib.rs
  crates/rerun/src/log_integration.rs
  crates/rerun/src/sdk.rs
  scripts/lint.py
Labels: enhancement, C/C++ SDK, include in changelog

#4163 Automatically sync assets on release
  .github/workflows/on_gh_release.yml
  scripts/ci/sync_release_assets.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#4165 Add command to copy direct link to fully qualified URL
  crates/re_build_info/src/build_info.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#4037 Python: remove legacy APIs
  docs/content/howto/ros2-nav-turtlebot.md
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/experimental/__init__.py
  rerun_py/rerun_sdk/rerun/experimental/blueprint.py
  rerun_py/rerun_sdk/rerun/log_deprecated/__init__.py
  rerun_py/rerun_sdk/rerun/log_deprecated/annotation.py
  rerun_py/rerun_sdk/rerun/log_deprecated/arrow.py
  rerun_py/rerun_sdk/rerun/log_deprecated/bounding_box.py
  rerun_py/rerun_sdk/rerun/log_deprecated/camera.py
  rerun_py/rerun_sdk/rerun/log_deprecated/clear.py
  rerun_py/rerun_sdk/rerun/log_deprecated/experimental/__init__.py
  rerun_py/rerun_sdk/rerun/log_deprecated/extension_components.py
  rerun_py/rerun_sdk/rerun/log_deprecated/file.py
  rerun_py/rerun_sdk/rerun/log_deprecated/image.py
  rerun_py/rerun_sdk/rerun/log_deprecated/lines.py
  rerun_py/rerun_sdk/rerun/log_deprecated/log_decorator.py
  rerun_py/rerun_sdk/rerun/log_deprecated/mesh.py
  rerun_py/rerun_sdk/rerun/log_deprecated/points.py
  rerun_py/rerun_sdk/rerun/log_deprecated/rects.py
  rerun_py/rerun_sdk/rerun/log_deprecated/scalar.py
  rerun_py/rerun_sdk/rerun/log_deprecated/tensor.py
  rerun_py/rerun_sdk/rerun/log_deprecated/text.py
  rerun_py/rerun_sdk/rerun/log_deprecated/text_internal.py
  rerun_py/rerun_sdk/rerun/log_deprecated/transform.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun_demo/__init__.py
  rerun_py/rerun_sdk/rerun_demo/data.py
  tests/python/test_api/main.py
  tests/python/view_coordinates/main.py
Labels: 🐍 python API, include in changelog

#4178 Fix markdown heading size
  Cargo.lock
  Cargo.toml
  crates/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/re_viewer/data/quick_start_guides/how_does_it_work.md
  crates/re_viewer/data/quick_start_guides/python_connect.md
  crates/re_viewer/data/quick_start_guides/python_spawn.md
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  crates/re_viewer/data/quick_start_guides/rust_spawn.md
Labels: ui, include in changelog

#4174 Actually unique `RowId`s 1: Forbid use of duplicate `RowId`s
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_data_store/Cargo.toml
  crates/re_data_store/tests/clear.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
Labels: ⛃ re_datastore, exclude from changelog, 🔩 data model

#4176 Actually unique `RowId`s 3: Rework `StoreDb` to support unique `RowId`s
  Cargo.lock
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/tests/clear.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_tuid/Cargo.toml
  crates/re_tuid/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_blueprint.rs
Labels: ⛃ re_datastore, exclude from changelog, 🔩 data model

#4180 Actually unique `RowId`s 4: `RowId` semantics test suite & docs
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_log_types/src/data_row.rs
Labels: ⛃ re_datastore, exclude from changelog, 🔩 data model

#4187 Do not use `RowId::ZERO` in query benchmarks (illegal RowId duplicates)
  crates/re_query/benches/query_benchmark.rs
Labels: exclude from changelog, :ship: CI

#4183 Implement recording/last-modified-at aware garbage collection
  Cargo.lock
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/store_db.rs
  crates/re_memory/src/memory_use.rs
  crates/re_viewer/src/store_hub.rs
  tests/python/gc_stress/many_large_many_rows_recordings.py
  tests/python/gc_stress/many_large_single_row_recordings.py
  tests/python/gc_stress/many_medium_sized_many_rows_recordings.py
  tests/python/gc_stress/many_medium_sized_single_row_recordings.py
Labels: ⛃ re_datastore, 📺 re_viewer, include in changelog

#4181 Simple logging benchmarks for C++ & Rust
  .gitignore
  Cargo.lock
  Cargo.toml
  pixi.lock
  pixi.toml
  tests/cpp/CMakeLists.txt
  tests/cpp/log_benchmark/CMakeLists.txt
  tests/cpp/log_benchmark/benchmarks.hpp
  tests/cpp/log_benchmark/image.cpp
  tests/cpp/log_benchmark/main.cpp
  tests/cpp/log_benchmark/points3d_large_batch.cpp
  tests/cpp/log_benchmark/points3d_many_individual.cpp
  tests/cpp/log_benchmark/points3d_shared.hpp
  tests/cpp/log_benchmark/profile_scope.cpp
  tests/cpp/log_benchmark/profile_scope.hpp
  tests/rust/log_benchmark/Cargo.toml
  tests/rust/log_benchmark/src/image.rs
  tests/rust/log_benchmark/src/main.rs
  tests/rust/log_benchmark/src/points3d_large_batch.rs
  tests/rust/log_benchmark/src/points3d_many_individual.rs
  tests/rust/log_benchmark/src/points3d_shared.rs
Labels: 🧑‍💻 dev experience, include in changelog

#4177 Scope the defaultFormatter override to python
  .vscode/settings.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#4179 Add support for Visible History to time series space views
  Cargo.lock
  crates/re_arrow_store/src/store_read.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_data_store/src/entity_properties.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/space_view.rs
Labels: ui, include in changelog

#4189 New debug option to show the blueprint in the streams view
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 🧑‍💻 dev experience, 🟦 blueprint, include in changelog

#4200 Use built-in wgsl type aliases instead of our own, remove zero/one wgsl constants
  crates/re_renderer/shader/colormap.wgsl
  crates/re_renderer/shader/composite.wgsl
  crates/re_renderer/shader/copy_texture.wgsl
  crates/re_renderer/shader/debug_overlay.wgsl
  crates/re_renderer/shader/decodings.wgsl
  crates/re_renderer/shader/depth_cloud.wgsl
  crates/re_renderer/shader/generic_skybox.wgsl
  crates/re_renderer/shader/global_bindings.wgsl
  crates/re_renderer/shader/instanced_mesh.wgsl
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/shader/mesh_vertex.wgsl
  crates/re_renderer/shader/outlines/jumpflooding_init.wgsl
  crates/re_renderer/shader/outlines/jumpflooding_init_msaa.wgsl
  crates/re_renderer/shader/outlines/jumpflooding_init_shared.wgsl
  crates/re_renderer/shader/outlines/jumpflooding_step.wgsl
  crates/re_renderer/shader/point_cloud.wgsl
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/shader/rectangle_vs.wgsl
  crates/re_renderer/shader/screen_triangle.wgsl
  crates/re_renderer/shader/screen_triangle_vertex.wgsl
  crates/re_renderer/shader/test_triangle.wgsl
  crates/re_renderer/shader/types.wgsl
  crates/re_renderer/shader/utils/camera.wgsl
  crates/re_renderer/shader/utils/depth_offset.wgsl
  crates/re_renderer/shader/utils/encoding.wgsl
  crates/re_renderer/shader/utils/quaternion.wgsl
  crates/re_renderer/shader/utils/sphere_quad.wgsl
  crates/re_renderer/shader/utils/srgb.wgsl
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#4199 Fix line & points (& depth clouds points) radii being unaffected by scale & projection via Pinhole
  crates/re_renderer/shader/depth_cloud.wgsl
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/shader/point_cloud.wgsl
  crates/re_renderer/shader/utils/size.wgsl
  crates/re_renderer/shader/utils/sphere_quad.wgsl
Labels: 🪳 bug, 🔺 re_renderer, user-request, include in changelog

#4216 Merge all doc deploy jobs into a single one to avoid race conditions
  .github/workflows/reusable_deploy_docs.yml
Labels: 🪳 bug, 🧑‍💻 dev experience, ⛴ release, exclude from changelog

#4218 Local-first guidelines
  CONTRIBUTING.md
Labels: 📖 documentation, exclude from changelog, :ship: CI

#4226 Fix inaccessible entities being incorrectly added to space view
  crates/re_viewport/src/space_info.rs
Labels: 🪳 bug, include in changelog

#4217 Add minimal examples in readme C++ api docs
  docs/content/reference/cpp-sdk-cmake.md
  docs/cspell.json
  rerun_cpp/README.md
  rerun_cpp/docs/Doxyfile
  rerun_cpp/tests/readme_snippets.cpp
Labels: 📖 documentation, enhancement, C/C++ SDK, exclude from changelog

#4215 Formalize behaviour of our many time histograms in a test suite
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/tests/time_histograms.rs
Labels: 🔨 testing, ⛃ re_datastore, 📺 re_viewer, exclude from changelog

#4202 `DataStore` changelog 1: let `DataStore`s know about their `StoreId`
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/examples/dump_dataframe.rs
  crates/re_arrow_store/examples/latest_component.rs
  crates/re_arrow_store/examples/latest_components.rs
  crates/re_arrow_store/examples/range_components.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_format.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_arrow_store/tests/internals.rs
  crates/re_data_store/src/store_db.rs
  crates/re_query/benches/query_benchmark.rs
  crates/re_query/src/query.rs
  crates/re_query/tests/archetype_query_tests.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_space_view_spatial/benches/bench_points.rs
Labels: ⛃ re_datastore, do-not-merge, exclude from changelog, 🔩 data model

#4203 `DataStore` changelog 2: introduce `StoreEvent`s
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_format.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_write.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_arrow_store/tests/internals.rs
Labels: ⛃ re_datastore, do-not-merge, include in changelog, 🔩 data model

#4205 `DataStore` changelog 3: introduce `StoreView`s
  Cargo.lock
  crates/re_arrow_store/Cargo.toml
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_stats.rs
  crates/re_arrow_store/src/store_view.rs
  crates/re_arrow_store/src/store_write.rs
Labels: ⛃ re_datastore, include in changelog, 🔩 data model

#4206 `DataStore` changelog 4: add standalone "Custom StoreView" example
  Cargo.lock
  crates/re_data_store/src/lib.rs
  crates/rerun/src/lib.rs
  examples/rust/custom_store_view/Cargo.toml
  examples/rust/custom_store_view/README.md
  examples/rust/custom_store_view/build.rs
  examples/rust/custom_store_view/src/main.rs
Labels: ⛃ re_datastore, exclude from changelog, 🔩 data model

#4208 `DataStore` changelog 5: event-driven time histograms
  Cargo.lock
  crates/re_arrow_store/src/lib.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_data_store/Cargo.toml
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/src/time_histogram_per_timeline.rs
  crates/re_data_store/src/times_per_timeline.rs
  crates/re_data_store/tests/time_histograms.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer_context/src/time_control.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: ⛃ re_datastore, exclude from changelog, 🔩 data model

#4209 `DataStore` changelog 6: event-driven `EntityTree`
  crates/re_arrow_store/src/store_write.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/src/time_histogram_per_timeline.rs
  crates/re_data_store/src/times_per_timeline.rs
  crates/re_data_store/tests/clear.rs
  crates/re_data_store/tests/time_histograms.rs
  crates/re_data_ui/src/lib.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/path/component_path.rs
  crates/re_sdk/src/lib.rs
Labels: ⛃ re_datastore, exclude from changelog, 🔩 data model

#4229 Don't install python in docs deploy job
  .github/workflows/reusable_deploy_docs.yml
Labels: exclude from changelog, :ship: CI

#4233 Fix benchmark jobs
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_track_size.yml
  scripts/ci/render_bench.py
Labels: exclude from changelog, :ship: CI

#4237 Don't let time histograms panic on saturated counters
  crates/re_data_store/src/time_histogram_per_timeline.rs
  crates/re_data_store/src/times_per_timeline.rs
Labels: 🪳 bug, 💣 crash, exclude from changelog

#4235 Faster wheel builds
  .github/workflows/manual_adhoc_web.yml
  .github/workflows/manual_build_release.yml
  .github/workflows/manual_build_wheels_for_pr.yml
  .github/workflows/manual_dispatch.yml
  .github/workflows/manual_publish_cli.yml
  .github/workflows/manual_release.yml
  .github/workflows/manual_run_bench.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_wheels.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_wheels.yml
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun_demo/__main__.py
Labels: exclude from changelog, :ship: CI

#4240 Add --edition 2021 to lint-rs-files
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#4238 Do not fire deletion events for autogen cluster keys + fix test suite
  crates/re_arrow_store/src/store.rs
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_subscriber.rs
  crates/re_log_types/src/data_cell.rs
Labels: 🪳 bug, ⛃ re_datastore, exclude from changelog, 🔩 data model

#4222 Make Visible History UI more ergonomic and show inherited values
  crates/re_data_store/src/entity_properties.rs
  crates/re_query/src/util.rs
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  tests/python/visible_history_playground/main.py
Labels: ui, include in changelog

#4239 [refactor] Move EntitiesPerSystemPerClass to the ViewerContext
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, exclude from changelog

#4243 Introduce new DataQueryBlueprint
  Cargo.lock
  crates/re_log_types/src/path/entity_path.rs
  crates/re_log_types/src/path/entity_path_expr.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/blueprint/.gitattributes
  crates/re_space_view/src/blueprint/mod.rs
  crates/re_space_view/src/blueprint/query_expressions.rs
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/query_expressions.fbs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  rerun_cpp/src/rerun/blueprint.hpp
  rerun_cpp/src/rerun/blueprint/.gitattributes
  rerun_cpp/src/rerun/blueprint/query_expressions.cpp
  rerun_cpp/src/rerun/blueprint/query_expressions.hpp
  rerun_py/rerun_sdk/rerun/blueprint/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/query_expressions.py
Labels: 🟦 blueprint, exclude from changelog

#4261 Fix GC decrementing metadata size trackers _before_ getting deletion confirmation
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/tests/correctness.rs
Labels: 🪳 bug, ⛃ re_datastore, exclude from changelog

#4268 [Docs] Fix howto/short_lived_entities.md for manually clearing entities
  docs/content/howto/short-lived-entities.md
Labels: 📖 documentation, exclude from changelog

#4259 Display Visible History on timeline when the mouse hovers the UI
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: ui, include in changelog

#4265 Fully clean up SpaceViews as they are removed and then GC'd from blueprint
  crates/re_arrow_store/benches/data_store.rs
  crates/re_arrow_store/src/store_event.rs
  crates/re_arrow_store/src/store_gc.rs
  crates/re_arrow_store/src/store_subscriber.rs
  crates/re_arrow_store/tests/correctness.rs
  crates/re_arrow_store/tests/data_store.rs
  crates/re_arrow_store/tests/dump.rs
  crates/re_data_store/src/entity_tree.rs
  crates/re_data_store/src/store_db.rs
  crates/re_data_store/src/time_histogram_per_timeline.rs
  crates/re_data_store/tests/clear.rs
  crates/re_data_store/tests/time_histograms.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🟦 blueprint, exclude from changelog

#4248 Refactor SpaceViewId as a generic BlueprintId
  Cargo.lock
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/blueprint_id.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🚜 refactor, 🟦 blueprint, exclude from changelog

#4279 Fix typo in cargo.toml
  crates/re_viewer_context/Cargo.toml
Labels: exclude from changelog

#4276 Fix a Visible History UI display bug with +/-inf boundaries (sequence only)
  crates/re_viewer/src/ui/visible_history.rs
Labels: ui, exclude from changelog

#4272 Fix incorrect glob for rerun_c rust dependency
  crates/rerun_c/CMakeLists.txt
Labels: 🧑‍💻 dev experience, C/C++ SDK, exclude from changelog

#4282 Use different C++ build directories for debug/release and roundtrips
  docs/code-examples/roundtrips.py
  pixi.toml
  scripts/roundtrip_utils.py
  tests/cpp/log_benchmark/main.cpp
  tests/roundtrips.py
Labels: 🧑‍💻 dev experience, C/C++ SDK, exclude from changelog

#4286 Track separable individual and group overrides for DataResult
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🟦 blueprint, exclude from changelog

#4289 Do not use `rerun`'s `demo` and `sdk` features in `rerun_cli`
  crates/rerun-cli/Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#4294 Mitigate perf issue in tree-ui by using the DataQuery ResultTree
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🦟 regression, 🟦 blueprint, exclude from changelog

#4293 Remove deprecated `rerun_demo` package
  .mypy.ini
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/python.md
  docs/content/getting-started/viewer-walkthrough.md
  examples/python/dna/main.py
  examples/python/notebook/cube.ipynb
  pyrightconfig.json
  rerun_py/docs/gen_common_index.py
  rerun_py/pyproject.toml
  rerun_py/rerun_demo/__init__.py
  rerun_py/rerun_sdk/rerun/utilities/__init__.py
  rerun_py/rerun_sdk/rerun/utilities/data.py
  rerun_py/rerun_sdk/rerun/utilities/turbo.py
  rerun_py/rerun_sdk/rerun/utilities/util.py
  rerun_py/rerun_sdk/rerun_demo/.gitignore
  rerun_py/rerun_sdk/rerun_demo/__init__.py
  rerun_py/rerun_sdk/rerun_demo/__main__.py
  rerun_py/tests/unit/test_rerun_demo.py
Labels: 🐍 python API, include in changelog

#4303 Silence spammy blueprint warnings and validate blueprint on load
  crates/re_arrow_store/src/store_helpers.rs
  crates/re_log/src/lib.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/blueprint_validation.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🟦 blueprint, include in changelog

#4302 Replace setup scripts with pixi
  .github/workflows/contrib_checks.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_build_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_upload_wheels.yml
  ci_docker/Dockerfile
  docs/content/getting-started/troubleshooting.md
  docs/cspell.json
  examples/python/detect_and_track_objects/requirements.txt
  pixi.lock
  pixi.toml
  scripts/ci/requirements-web-demo.txt
  scripts/start_server.sh
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience, include in changelog

#4319 Fix pixified builds
  .github/workflows/auto_approve.yml
  .github/workflows/auto_release_crates.yml
  .github/workflows/checkboxes.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_pull_request_target_contrib.yml
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_npm.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_build_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_publish_npm.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_track_size.yml
  .github/workflows/reusable_update_pr_body.yml
  .github/workflows/reusable_upload_web.yml
  .github/workflows/reusable_upload_web_demo.yml
  .github/workflows/reusable_upload_wheels.yml
Labels: exclude from changelog, :ship: CI

#4312 Update roadmap
  docs/content/reference/roadmap.md
Labels: 📖 documentation, exclude from changelog

#4320 Fix pixi build (part 2)
  .github/workflows/reusable_build_wheels.yml
Labels: exclude from changelog, :ship: CI

#4323 Fix pixi build (part 3)
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_wheels.yml
Labels: exclude from changelog, :ship: CI

#4314 Auto-switch port when getting AddrInUse error
  crates/re_web_viewer_server/src/lib.rs
  crates/re_ws_comms/src/server.rs
Labels: 🕸️ web, 🧑‍💻 dev experience, include in changelog

#4313 Expose Rerun source/include dir in CMakeLists.txt (`RERUN_CPP_SOURCE_DIR`)
  docs/content/reference/cpp-sdk-cmake.md
  rerun_cpp/CMakeLists.txt
Labels: enhancement, C/C++ SDK, include in changelog

#4326 Support cmake install
  docs/content/reference/cpp-sdk-cmake.md
  docs/cspell.json
  examples/cpp/minimal/CMakeLists.txt
  rerun_cpp/CMakeLists.txt
  rerun_cpp/Config.cmake.in
  scripts/ci/bundle_and_upload_rerun_cpp.py
Labels: enhancement, C/C++ SDK, include in changelog

#4329 Various C++ docs improvements
  crates/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/re_viewer_context/src/space_view/view_part_system.rs
  docs/code-examples/asset3d_out_of_tree.cpp
  docs/code-examples/custom_data.cpp
  docs/code-examples/custom_data.py
  docs/code-examples/quick_start_connect.cpp
  docs/content/getting-started/cpp.md
  docs/content/getting-started/logging-cpp.md
  docs/cspell.json
  examples/cpp/CMakeLists.txt
  examples/cpp/custom_collection_adapter/CMakeLists.txt
  examples/cpp/custom_collection_adapter/README.md
  examples/cpp/custom_collection_adapter/main.cpp
  examples/cpp/custom_component_adapter/README.md
  examples/cpp/minimal/main.cpp
  pixi.toml
  rerun_cpp/CMakeLists.txt
  rerun_cpp/README.md
  rerun_cpp/arrow_cpp_install.md
  rerun_cpp/cmake_setup_in_detail.md
  rerun_cpp/docs/Doxyfile
  rerun_cpp/docs/readme_snippets.cpp
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/collection_adapter.hpp
  rerun_cpp/src/rerun/demo_utils.hpp
  rerun_cpp/tests/CMakeLists.txt
  scripts/ci/bundle_and_upload_rerun_cpp.py
Labels: 📖 documentation, C/C++ SDK, exclude from changelog

#4331 Export TensorBuffer & TensorDimension to rerun namespace
  crates/rerun/src/sdk.rs
  rerun_cpp/src/rerun.hpp
Labels: C/C++ SDK, include in changelog

#4330 C++ SDK sanity checks now header/source version against rerun_c binary version
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  rerun_cpp/CMakeLists.txt
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/config.cpp
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/sdk_info.cpp
  rerun_cpp/src/rerun/sdk_info.hpp
  rerun_cpp/src/rerun/spawn.cpp
Labels: enhancement, C/C++ SDK, include in changelog

#4340 Move side-panels margins inside of their `ScrollArea`s
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, ui, exclude from changelog

#4345 C++: Allow creating Image/Tensor/DepthImage/SegmentationImage directly from shape & pointer
  crates/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/re_types/definitions/rerun/archetypes/tensor.fbs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  docs/code-examples/depth_image_3d.cpp
  docs/code-examples/depth_image_simple.cpp
  docs/code-examples/image_simple.cpp
  docs/code-examples/segmentation_image_simple.cpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/depth_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/image_ext.cpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/tensor.hpp
  rerun_cpp/src/rerun/archetypes/tensor_ext.cpp
  rerun_cpp/src/rerun/archetypes/text_log.hpp
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/collection_adapter.hpp
  rerun_cpp/src/rerun/components/tensor_data.hpp
  rerun_cpp/src/rerun/components/tensor_data_ext.cpp
  rerun_cpp/src/rerun/datatypes/tensor_data.hpp
  rerun_cpp/src/rerun/datatypes/tensor_data_ext.cpp
  rerun_cpp/tests/archetypes/image.cpp
  rerun_cpp/tests/archetypes/segmentation_and_depth_image.cpp
  rerun_cpp/tests/archetypes/tensor.cpp
  rerun_cpp/tests/collection.cpp
Labels: enhancement, C/C++ SDK, include in changelog

#4324 Improve the Selection Panel with better title, context, and Space View key properties
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, include in changelog

#4333 Python: don't catch `KeyboardInterrupt` and `SystemExit`
  rerun_py/rerun_sdk/rerun/error_utils.py
Labels: 🐍 python API, include in changelog

#4346 Reference doc fixes - ordering, remove outdated link, fix migration guide title
  docs/content/getting-started/cpp.md
  docs/content/getting-started/logging-cpp.md
  docs/content/getting-started/logging-python.md
  docs/content/getting-started/python.md
  docs/content/howto/cpp-custom-component-batch-adapter.md
  docs/content/reference/cpp.md
  docs/content/reference/migration-0-9.md
  docs/content/reference/python.md
Labels: 📖 documentation, exclude from changelog

#4334 Fix runtime error in `2d` example of `re_render`
  crates/re_renderer/examples/2d.rs
Labels: 🔺 re_renderer, examples, exclude from changelog

#4342 Add more examples to `manifest.yml`
  examples/cpp/eigen_opencv/README.md
  examples/cpp/vrs/README.md
  examples/manifest.yml
  examples/python/open_photogrammetry_format/README.md
  justfile
Labels: examples, exclude from changelog

#4352 Identify proper sha during pull-request jobs
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
Labels: 🪳 bug, exclude from changelog, :ship: CI

#4354 Fix bug where selecting group would instead select the individual entity
  crates/re_viewer/src/ui/selection_panel.rs
Labels: 🪳 bug, exclude from changelog

#4349 Fix c++ spawn failure by handling empty string properly
  crates/rerun_c/src/lib.rs
  rerun_cpp/src/rerun/spawn_options.hpp
Labels: 🪳 bug, C/C++ SDK, exclude from changelog

#4350 Fix warning when running cmake from packaged rerun_sdk folder
  rerun_cpp/CMakeLists.txt
Labels: 🪳 bug, C/C++ SDK, exclude from changelog

#4351 Fix missing quote in cmake install script template
  rerun_cpp/Config.cmake.in
Labels: 🪳 bug, C/C++ SDK, exclude from changelog

#4360 Fix release assets auto-sync
  .github/workflows/on_gh_release.yml
Labels: exclude from changelog, :ship: CI

#4356 Update pixi github action 0.3.0->0.4.1
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_build_wheels.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
Labels: exclude from changelog, :ship: CI

#4357 Set `clip_rect_margin` to zero by default
  crates/re_ui/src/design_tokens.rs
Labels: ui, exclude from changelog

#4363 Plot legend visibility and position control (part 1): route `EntityProperties` to `SpaceViewClass` methods
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewport/src/space_view.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: ui, include in changelog

#4364 Plot legend visibility and position control (part 2): minor UI spacing improvement
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, include in changelog

#4371 All C++ preprocessor macros start now with RR_ (instead of a mix of RR_ and RERUN_)
  CODE_STYLE.md
  crates/re_types_builder/src/codegen/cpp/mod.rs
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/boxes2d.hpp
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/text_document.hpp
  rerun_cpp/src/rerun/archetypes/text_log.hpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/compiler_utils.hpp
  rerun_cpp/src/rerun/datatypes/translation_rotation_scale3d.hpp
  rerun_cpp/src/rerun/datatypes/translation_rotation_scale3d_ext.cpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer3.hpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer4.hpp
Labels: C/C++ SDK, include in changelog

#4369 Reset accumulated bounding box when resetting camera
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: ui, include in changelog

#4370 Improve component data table UI in the selection panel
  crates/re_data_ui/src/component.rs
Labels: ui, include in changelog

#4372 Add optional color component to BarChart archetype
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_types/definitions/rerun/archetypes/bar_chart.fbs
  crates/re_types/src/archetypes/bar_chart.rs
  docs/content/reference/types/archetypes/bar_chart.md
  docs/content/reference/types/components/color.md
  rerun_cpp/src/rerun/archetypes/bar_chart.cpp
  rerun_cpp/src/rerun/archetypes/bar_chart.hpp
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
Labels: ui, 🍏 primitives, include in changelog

#4374 Fix not tracking wgsl file changes for web build
  crates/re_build_tools/src/rebuild_detector.rs
Labels: 🧑‍💻 dev experience, include in changelog

#4362 Protect fenced code-blocks when running update_pr_body.py
  scripts/ci/update_pr_body.py
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#4361 Resolve unexpected view-partitioning by only bucket images when creating a new 2d view
  crates/re_viewport/src/space_view_heuristics.rs
Labels: ui, include in changelog

#4376 fast_lint.py: Always run the full mypy lint
  scripts/fast_lint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#4368 Bugfix: show labels on segmentation images with trivial dimensions
  crates/re_data_ui/src/image.rs
  crates/re_types/src/datatypes/tensor_data_ext.rs
Labels: 🪳 bug, ui, include in changelog

#4310 Move DataQueryResults into the ViewerContext
  Cargo.lock
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/blueprint_id.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, 🟦 blueprint, exclude from changelog

#4380 Add support for exclusion expressions to the DataQueryBlueprint
  crates/re_space_view/src/blueprint/query_expressions.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_types/definitions/rerun/blueprint/query_expressions.fbs
  crates/re_viewer/src/ui/selection_panel.rs
  rerun_cpp/src/rerun/blueprint/query_expressions.cpp
  rerun_cpp/src/rerun/blueprint/query_expressions.hpp
  rerun_py/rerun_sdk/rerun/blueprint/query_expressions.py
Labels: 🟦 blueprint, exclude from changelog

#4381 Wire the remove-entity buttons to query exclusions
  crates/re_log_types/src/path/entity_path_expr.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🟦 blueprint, exclude from changelog

#4387 Selection state is now fully double buffered and has interior mutability
  crates/re_data_ui/src/item_ui.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor, include in changelog

#4390 Update Rust to 1.74.0
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_npm.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_build_web_demo.yml
  .github/workflows/reusable_build_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_upload_wheels.yml
  BUILD.md
  ci_docker/Dockerfile
  ci_docker/publish.sh
  crates/re_analytics/src/native/sink.rs
  crates/re_analytics/src/web/config.rs
  crates/re_analytics/src/web/pipeline.rs
  crates/re_build_info/src/build_info.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_renderer/build.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_string_interner/src/lib.rs
  crates/re_types/src/components/draw_order_ext.rs
  crates/re_types/src/components/media_type_ext.rs
  crates/re_types/src/components/text_log_level_ext.rs
  crates/re_types_core/src/arrow_string.rs
  crates/re_viewer/src/blueprint/panel_view_ext.rs
  crates/re_viewer_context/src/caches.rs
  rerun_py/README.md
  rust-toolchain
  scripts/setup.sh
  tests/rust/log_benchmark/src/image.rs
Labels: dependencies, include in changelog

#4393 Add `ui_name()` to `SpaceViewClass` so space views may provide a user-facing name
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🚜 refactor, exclude from changelog

#4404 Enable (selected) new cargo clippy lints
  Cranky.toml
  crates/re_data_ui/src/item_ui.rs
  crates/re_query/benches/query_benchmark.rs
  crates/re_renderer/examples/depth_cloud.rs
  crates/re_renderer/examples/framework.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_renderer/src/wgpu_resources/dynamic_resource_pool.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_time_panel/src/time_ranges_ui.rs
  crates/re_ui/src/list_item.rs
  crates/re_ui/src/toggle_switch.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, include in changelog

#4406 Rename `name` to `identifier` for `SpaceViewClass` and, well, `IdentifiedViewSystem`
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_bar_chart/src/view_part_system.rs
  crates/re_space_view_spatial/src/contexts/annotation_context.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/parts/arrows3d.rs
  crates/re_space_view_spatial/src/parts/assets3d.rs
  crates/re_space_view_spatial/src/parts/boxes2d.rs
  crates/re_space_view_spatial/src/parts/boxes3d.rs
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/parts/entity_iterator.rs
  crates/re_space_view_spatial/src/parts/images.rs
  crates/re_space_view_spatial/src/parts/lines2d.rs
  crates/re_space_view_spatial/src/parts/lines3d.rs
  crates/re_space_view_spatial/src/parts/meshes.rs
  crates/re_space_view_spatial/src/parts/points2d.rs
  crates/re_space_view_spatial/src/parts/points3d.rs
  crates/re_space_view_spatial/src/parts/transform3d_arrows.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/view_part_system.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_document/src/view_part_system.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_text_log/src/view_part_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/view_part_system.rs
  crates/re_types/definitions/rerun/blueprint/space_view_component.fbs
  crates/re_types/src/blueprint/space_view_component.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/named_system.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_context_system.rs
  crates/re_viewer_context/src/space_view/view_part_system.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  examples/rust/custom_space_view/src/color_coordinates_view_part_system.rs
  rerun_cpp/src/rerun/blueprint/space_view_component.cpp
  rerun_cpp/src/rerun/blueprint/space_view_component.hpp
  rerun_py/rerun_sdk/rerun/blueprint/space_view_component.py
Labels: 🚜 refactor, exclude from changelog

#4392 Implement a mediocre add/remove dialog
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 📺 re_viewer, 🟦 blueprint, exclude from changelog

#4408 Move ResetBlueprint to a SystemCommand
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer_context/src/command_sender.rs
Labels: 🟦 blueprint, exclude from changelog
