Repository rerun-io/rerun, pull requests merged in 2024-09, with the labels that each got.

#7218 Update to latest wgpu and egui/eframe
  .typos.toml
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk/src/batcher.rs
  crates/top/re_sdk/src/web_viewer.rs
  crates/utils/re_log/src/lib.rs
  crates/utils/re_log/src/setup.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/error_handling/error_tracker.rs
  crates/viewer/re_renderer/src/error_handling/wgpu_core_error.rs
  crates/viewer/re_renderer/src/renderer/video/decoder/web.rs
  crates/viewer/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/list_item/button_content.rs
  crates/viewer/re_ui/src/list_item/item_button.rs
  crates/viewer/re_ui/src/list_item/label_content.rs
  crates/viewer/re_ui/src/list_item/property_content.rs
  crates/viewer/re_ui/src/modal.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/native.rs
  crates/viewer/re_viewer/src/web.rs
  deny.toml
  rerun_js/web-viewer/index.ts
  scripts/clippy_wasm/clippy.toml
  web_viewer/index.html
Labels: 🔺 re_renderer, dependencies, exclude from changelog

#7326 Refactor `MediaType` guessing
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d_ext.cpp
  rerun_cpp/src/rerun/archetypes/asset_video.hpp
  rerun_cpp/src/rerun/archetypes/asset_video_ext.cpp
  rerun_cpp/src/rerun/archetypes/encoded_image.hpp
  rerun_cpp/src/rerun/archetypes/encoded_image_ext.cpp
  rerun_cpp/src/rerun/components/media_type.hpp
  rerun_cpp/src/rerun/components/media_type_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image_ext.py
  rerun_py/rerun_sdk/rerun/components/media_type_ext.py
Labels: 🐍 Python API, 🦀 Rust API, 🚜 refactor, 🌊 C++ API, include in changelog

#7332 Fix `AssetVideo`
  rerun_py/rerun_sdk/rerun/archetypes/asset_video_ext.py
Labels: exclude from changelog

#7334 Fix `re_types_core::datatypes::TimeInt::MIN` and avoid using it for `TimeDragValue`
  crates/store/re_types_core/src/datatypes/time_int_ext.rs
  crates/viewer/re_chunk_store_ui/src/chunk_list_mode.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_space_view_dataframe/src/query_kind_ui.rs
  crates/viewer/re_viewer_context/src/time_drag_value.rs
Labels: 🚜 refactor, exclude from changelog

#7342 Bump egui commit and replace all `id_source` by `id_salt`
  Cargo.lock
  Cargo.toml
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_component_ui/src/datatype_uis/enum_combobox.rs
  crates/viewer/re_component_ui/src/marker_shape.rs
  crates/viewer/re_component_ui/src/radius.rs
  crates/viewer/re_component_ui/src/timeline.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_time_panel/src/time_control_ui.rs
  crates/viewer/re_ui/examples/re_ui_example/right_panel.rs
  crates/viewer/re_ui/src/list_item/scope.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/ui/memory_panel.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/mod.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: dependencies, 🚜 refactor, exclude from changelog

#7348 Unpin `wasm-bindgen` and `mimalloc` in published crates.
  Cargo.toml
  crates/top/rerun-cli/Cargo.toml
  crates/viewer/re_viewer/Cargo.toml
  rerun_py/Cargo.toml
Labels: 🦀 Rust API, dependencies, exclude from changelog

#7338 Dataframe queries 0: bootstrap & data model
  ARCHITECTURE.md
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/README.md
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/store/re_query/src/cache.rs
Labels: ⛃ re_datastore, 🔍 re_query, do-not-merge, include in changelog

#7339 Dataframe queries 1: schema resolution
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/engine.rs
Labels: ⛃ re_datastore, 🔍 re_query, do-not-merge, include in changelog

#7340 Dataframe queries 2: latest-at
  crates/store/re_dataframe/examples/latest_at.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/latest_at.rs
  crates/store/re_dataframe/src/lib.rs
Labels: ⛃ re_datastore, 🔍 re_query, include in changelog

#7341 Dataframe queries 3: dense range
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/examples/range.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_dataframe/src/range.rs
Labels: ⛃ re_datastore, 🔍 re_query, include in changelog

#7345 Dataframe queries 4: paginated dense range
  crates/store/re_dataframe/examples/range_paginated.rs
  crates/store/re_dataframe/src/range.rs
Labels: ⛃ re_datastore, 🔍 re_query, include in changelog

#7329 Remove unused archetype docstring to reduce binary bloat
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
Labels: 🧑‍💻 dev experience, 📉 performance, exclude from changelog

#7351 Execute the release checklists in PR CI
  .github/workflows/reusable_test_wheels.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#7331 Add point-of-view entity and component to the dataframe view's UI
  Cargo.lock
  crates/store/re_types/definitions/rerun/blueprint/datatypes/time_range_query.fbs
  crates/store/re_types/src/blueprint/datatypes/time_range_query.rs
  crates/store/re_types/src/blueprint/datatypes/time_range_query_ext.rs
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_space_view_dataframe/Cargo.toml
  crates/viewer/re_space_view_dataframe/src/lib.rs
  crates/viewer/re_space_view_dataframe/src/query_kind.rs
  crates/viewer/re_space_view_dataframe/src/query_kind_ui.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
  crates/viewer/re_space_view_dataframe/src/view_query.rs
  crates/viewer/re_ui/examples/re_ui_example/right_panel.rs
  rerun_cpp/src/rerun/blueprint/datatypes/time_range_query.cpp
  rerun_cpp/src/rerun/blueprint/datatypes/time_range_query.hpp
  rerun_py/rerun_sdk/rerun/blueprint/components/time_range_queries.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/time_range_query.py
Labels: ui, include in changelog

#7361 Dataframe queries: support sparsely encoded dictionary arrays
  crates/store/re_chunk/src/util.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/latest_at.rs
  crates/store/re_dataframe/src/range.rs
Labels: 🏹 arrow, 🔍 re_query, 📉 performance, include in changelog

#7363 Add missing `show_labels` and `draw_order` arguments in Python API.
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d_ext.py
Labels: 🐍 Python API, include in changelog

#7366 Dataframe queries: simplified schema wrapping management
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/latest_at.rs
  crates/store/re_dataframe/src/range.rs
Labels: 🪳 bug, 🔍 re_query, exclude from changelog

#7377 Use `EntityPathFilter` in `re_dataframe`'s queries
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/examples/latest_at.rs
  crates/store/re_dataframe/examples/range.rs
  crates/store/re_dataframe/examples/range_paginated.rs
  crates/store/re_dataframe/src/latest_at.rs
  crates/store/re_dataframe/src/range.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/viewer/re_selection_panel/src/space_view_entity_picker.rs
  crates/viewer/re_viewer_context/src/space_view/spawn_heuristics.rs
  crates/viewer/re_viewport_blueprint/src/space_view_contents.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: ⛃ re_datastore, 🚜 refactor, exclude from changelog

#7355 Add arrow feature to re_chunk and conversions to RecordBatch
  Cargo.lock
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/arrow.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/transport.rs
Labels: 🏹 arrow, ⛃ re_datastore, exclude from changelog

#7383 Switch ArrowDict to signed and fix static datatype
  crates/store/re_chunk/src/util.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/range.rs
Labels: ⛃ re_datastore, exclude from changelog

#7386 Fix bug in `TransportChunk` test
  crates/store/re_chunk/src/transport.rs
Labels: 🪳 bug, exclude from changelog, :ship: CI

#7381 Fix WebGL renderer failing to display video
  crates/viewer/re_renderer/src/renderer/video/decoder/web.rs
Labels: exclude from changelog, 🎞️ video

#7382 Update `mp4` rev
  Cargo.lock
  Cargo.toml
Labels: exclude from changelog, 🎞️ video

#7394 Make the entity path header "sticky" in the dataframe view
  crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs
Labels: ui, include in changelog, feat-dataframe-view

#7397 Fix running python doc tests twice on CI
  .github/workflows/reusable_checks.yml
Labels: exclude from changelog, :ship: CI

#7398 Keep redrawing until video decoder is done decoding requested frame
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/renderer/mod.rs
  crates/viewer/re_renderer/src/video/decoder/mod.rs
  crates/viewer/re_renderer/src/video/decoder/native.rs
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_space_view_spatial/src/video_cache.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
Labels: exclude from changelog, 🎞️ video

#7399 Split out (ultra-)slow cargo doc jobs and run them only on nightly
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks_rust.yml
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  scripts/ci/rust_checks.py
Labels: exclude from changelog, :ship: CI

#7402 Fix Rust's `TimeColumn::new_seconds/new_nanos` creating sequence timelines
  crates/store/re_chunk/src/chunk.rs
Labels: 🪳 bug, 🦀 Rust API, include in changelog

#7401 Move all test assets to single location & introduce a script to for downloading larger test assets
  docs/snippets/compare_snippet_output.py
  docs/snippets/snippets.toml
  rerun_py/tests/unit/test_asset3d.py
  tests/assets/.gitignore
  tests/assets/cube.glb
  tests/assets/download_test_assets.py
  tests/assets/empty.mp4
Labels: 🧑‍💻 dev experience, exclude from changelog

#7409 Remove unused `SpaceViewClass::on_frame_start`
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/space_view/space_view_class.rs
  crates/viewer/re_viewport/src/viewport.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 🚜 refactor, exclude from changelog

#7410 Fix warning popping up when selecting a video asset
  crates/store/re_types/src/image.rs
  crates/viewer/re_viewer_context/src/tensor/image_decode_cache.rs
Labels: 🪳 bug, exclude from changelog, 🎞️ video

#7406 Introduce the chunk zoo, a collection of delightfully unique chunk specimens
  tests/python/chunk_zoo/chunk_zoo.py
Labels: 🔨 testing, include in changelog

#7403 Utils & snippets for manually logged` VideoFrameReference`
  crates/build/re_dev_tools/src/build_examples/snippets.rs
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_types/definitions/rerun/archetypes/asset_video.fbs
  crates/store/re_types/definitions/rerun/archetypes/video_frame_reference.fbs
  crates/store/re_types/src/archetypes/asset_video.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/store/re_types/src/components/video_timestamp_ext.rs
  crates/store/re_types/src/datatypes/video_timestamp_ext.rs
  crates/store/re_types_core/src/archetype.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/archetypes/asset_video.md
  docs/content/reference/types/archetypes/video_frame_reference.md
  docs/snippets/all/archetypes/asset3d_simple.cpp
  docs/snippets/all/archetypes/video_manual_frames.cpp
  docs/snippets/all/archetypes/video_manual_frames.py
  docs/snippets/all/archetypes/video_manual_frames.rs
  docs/snippets/all/archetypes/video_simple.cpp
  docs/snippets/all/archetypes/video_simple.py
  docs/snippets/all/archetypes/video_simple.rs
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset_video.hpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.hpp
  rerun_cpp/src/rerun/components/video_timestamp.hpp
  rerun_cpp/src/rerun/components/video_timestamp_ext.cpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/components/video_timestamp.py
  rerun_py/rerun_sdk/rerun/components/video_timestamp_ext.py
Labels: exclude from changelog, 🎞️ video

#7330 Sanity-check that an archetype has a component
  crates/store/re_types_core/src/lib.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#7415 Remove the `TimeRangeTableOrder` blueprint structure, which is no longer used by the dataframe view
  crates/store/re_types/definitions/rerun/blueprint/archetypes.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/time_range_table_order.fbs
  crates/store/re_types/definitions/rerun/blueprint/components.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/sort_key.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/sort_order.fbs
  crates/store/re_types/src/blueprint/archetypes/.gitattributes
  crates/store/re_types/src/blueprint/archetypes/mod.rs
  crates/store/re_types/src/blueprint/archetypes/time_range_table_order.rs
  crates/store/re_types/src/blueprint/components/.gitattributes
  crates/store/re_types/src/blueprint/components/mod.rs
  crates/store/re_types/src/blueprint/components/sort_key.rs
  crates/store/re_types/src/blueprint/components/sort_order.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
  crates/viewer/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  rerun_cpp/src/rerun/blueprint/archetypes.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/.gitattributes
  rerun_cpp/src/rerun/blueprint/archetypes/time_range_table_order.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/time_range_table_order.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/sort_key.cpp
  rerun_cpp/src/rerun/blueprint/components/sort_key.hpp
  rerun_cpp/src/rerun/blueprint/components/sort_order.cpp
  rerun_cpp/src/rerun/blueprint/components/sort_order.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/time_range_table_order.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/sort_key.py
  rerun_py/rerun_sdk/rerun/blueprint/components/sort_order.py
Labels: ui, 🚜 refactor, exclude from changelog, feat-dataframe-view

#7419 Fix VideoDecoder not showing anything on startup
  crates/viewer/re_renderer/src/video/decoder/web.rs
Labels: 🪳 bug, exclude from changelog, 🎞️ video

#7418 Update to latest egui
  Cargo.lock
  Cargo.toml
  crates/viewer/re_component_ui/src/datatype_uis/enum_combobox.rs
  crates/viewer/re_data_ui/src/component_name.rs
  crates/viewer/re_space_view/src/view_property_ui.rs
  crates/viewer/re_space_view_dataframe/Cargo.toml
  crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_space_view_spatial/src/view_3d.rs
  crates/viewer/re_space_view_text_document/src/space_view_class.rs
  crates/viewer/re_time_panel/benches/bench_density_graph.rs
  crates/viewer/re_time_panel/src/time_control_ui.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/section_collapsing_header.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport/src/viewport.rs
Labels: 📺 re_viewer, dependencies, exclude from changelog, egui

#7426 Silence RUSTSEC-2023-0086
  deny.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#7425 Bug fix: always show latest data in follow-mode
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#7428 Fix encoded image being suggested for non image blobs (like video)
  crates/store/re_types/src/components/media_type_ext.rs
  crates/viewer/re_space_view_spatial/src/visualizers/encoded_image.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#7424 Ci fixes (flaky test, missing unreleased-docs marker)
  crates/store/re_types/definitions/rerun/archetypes/asset_video.fbs
  crates/store/re_types/definitions/rerun/archetypes/video_frame_reference.fbs
  crates/store/re_types/definitions/rerun/components/entity_path.fbs
  crates/store/re_types/definitions/rerun/components/video_timestamp.fbs
  crates/store/re_types/definitions/rerun/datatypes/video_timestamp.fbs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/archetypes/asset_video.md
  docs/content/reference/types/archetypes/video_frame_reference.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/blob.md
  docs/content/reference/types/components/entity_path.md
  docs/content/reference/types/components/media_type.md
  docs/content/reference/types/components/video_timestamp.md
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/entity_path.md
  docs/content/reference/types/datatypes/video_time_mode.md
  docs/content/reference/types/datatypes/video_timestamp.md
  docs/snippets/snippets.toml
Labels: exclude from changelog, :ship: CI, 🎞️ video

#7400 Add support to expand rows to show instances in the dataframe view
  .typos.toml
  Cargo.lock
  Cargo.toml
  crates/viewer/re_component_ui/src/datatype_uis/float_drag.rs
  crates/viewer/re_component_ui/src/range1d.rs
  crates/viewer/re_component_ui/src/visual_bounds2d.rs
  crates/viewer/re_space_view_dataframe/Cargo.toml
  crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_space_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_space_view_dataframe/src/expanded_rows.rs
  crates/viewer/re_space_view_dataframe/src/lib.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
  crates/viewer/re_ui/data/icons/collapse.png
  crates/viewer/re_ui/data/icons/expand.png
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
  tests/python/chunk_zoo/chunk_zoo.py
Labels: ui, include in changelog, feat-dataframe-view

#7432 Fix "no view state found" error
  crates/viewer/re_viewer_context/src/space_view/view_states.rs
  crates/viewer/re_viewport/src/system_execution.rs
  crates/viewer/re_viewport/src/viewport.rs
Labels: 🦟 regression, exclude from changelog

#7434 Dataframe view now has zebra stripes on every line
  crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_space_view_dataframe/src/expanded_rows.rs
  crates/viewer/re_ui/src/design_tokens.rs
Labels: ui, include in changelog, feat-dataframe-view

#7437 In debug builds, spawn the binary at `target/debug/rerun`, if it exists
  BUILD.md
  crates/top/re_sdk/src/spawn.rs
  examples/rust/README.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#7405 Make the choice to dictionary-encode data results explicit
  crates/store/re_chunk/src/util.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/latest_at.rs
  crates/store/re_dataframe/src/range.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
Labels: ⛃ re_datastore, exclude from changelog

#7452 Improve vertical text centering
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#7451 Fix table column auto-sizing
  crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs
Labels: 🪳 bug, ui, exclude from changelog

#7438 Add a hook for views to add additional UI in the tab title bar
  crates/viewer/re_viewer_context/src/space_view/space_view_class.rs
  crates/viewer/re_viewport/src/viewport.rs
Labels: enhancement, ui, include in changelog

#7450 Various picking code refactor & basic pickable videos
  crates/store/re_log_types/src/instance.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_spatial/src/pickable_image.rs
  crates/viewer/re_space_view_spatial/src/pickable_textured_rect.rs
  crates/viewer/re_space_view_spatial/src/picking.rs
  crates/viewer/re_space_view_spatial/src/scene_bounding_boxes.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/view_2d.rs
  crates/viewer/re_space_view_spatial/src/view_3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/spatial_view_visualizer.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
Labels: enhancement, 🚜 refactor, exclude from changelog, 🎞️ video

#7444 Introduce ColumnSelector instead of ColumnDescriptor
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_dataframe/examples/range.rs
  crates/store/re_dataframe/examples/range_paginated.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/latest_at.rs
  crates/store/re_dataframe/src/range.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
Labels: ⛃ re_datastore, exclude from changelog

#7358 Update ndarray to 0.16 and ndarray-rand to 0.15
  Cargo.lock
  Cargo.toml
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/datatypes/tensor_data_ext.rs
  crates/store/re_types/tests/types/tensor.rs
  crates/viewer/re_space_view_tensor/src/space_view_class.rs
  docs/snippets/all/archetypes/image_send_columns.rs
Labels: 🦀 Rust API, dependencies, include in changelog

#7457 Video hover interaction like on images
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/rect.rs
  crates/viewer/re_renderer/src/texture_info.rs
  crates/viewer/re_renderer/src/video/decoder/mod.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_spatial/src/pickable_textured_rect.rs
  crates/viewer/re_space_view_spatial/src/picking_ui.rs
  crates/viewer/re_space_view_spatial/src/picking_ui_pixel.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_tensor/src/space_view_class.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
Labels: 🔺 re_renderer, 📺 re_viewer, exclude from changelog, 🎞️ video

#7453 Dataframe column visibility can now be controlled
  crates/store/re_types/definitions/rerun/blueprint/archetypes.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/dataframe_visible_columns.fbs
  crates/store/re_types/definitions/rerun/blueprint/components.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/column_selection_mode.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/component_column_selector.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/timeline_name.fbs
  crates/store/re_types/definitions/rerun/blueprint/datatypes.fbs
  crates/store/re_types/definitions/rerun/blueprint/datatypes/component_column_selector.fbs
  crates/store/re_types/definitions/rerun/blueprint/datatypes/utf8_list.fbs
  crates/store/re_types/definitions/rerun/datatypes/entity_path.fbs
  crates/store/re_types/src/blueprint/archetypes/.gitattributes
  crates/store/re_types/src/blueprint/archetypes/dataframe_visible_columns.rs
  crates/store/re_types/src/blueprint/archetypes/mod.rs
  crates/store/re_types/src/blueprint/components/.gitattributes
  crates/store/re_types/src/blueprint/components/column_selection_mode.rs
  crates/store/re_types/src/blueprint/components/component_column_selector.rs
  crates/store/re_types/src/blueprint/components/component_column_selector_ext.rs
  crates/store/re_types/src/blueprint/components/mod.rs
  crates/store/re_types/src/blueprint/components/timeline_name.rs
  crates/store/re_types/src/blueprint/components/timeline_name_ext.rs
  crates/store/re_types/src/blueprint/datatypes/.gitattributes
  crates/store/re_types/src/blueprint/datatypes/component_column_selector.rs
  crates/store/re_types/src/blueprint/datatypes/mod.rs
  crates/store/re_types_blueprint/src/blueprint/datatypes/utf8list.rs
  crates/store/re_types_core/src/datatypes/entity_path.rs
  crates/viewer/re_space_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_space_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
  crates/viewer/re_ui/data/icons/column_visibility.png
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  rerun_cpp/src/rerun/blueprint/archetypes.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/.gitattributes
  rerun_cpp/src/rerun/blueprint/archetypes/dataframe_visible_columns.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/dataframe_visible_columns.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/column_selection_mode.cpp
  rerun_cpp/src/rerun/blueprint/components/column_selection_mode.hpp
  rerun_cpp/src/rerun/blueprint/components/component_column_selector.hpp
  rerun_cpp/src/rerun/blueprint/datatypes.hpp
  rerun_cpp/src/rerun/blueprint/datatypes/.gitattributes
  rerun_cpp/src/rerun/blueprint/datatypes/component_column_selector.cpp
  rerun_cpp/src/rerun/blueprint/datatypes/component_column_selector.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/dataframe_visible_columns.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/column_selection_mode.py
  rerun_py/rerun_sdk/rerun/blueprint/components/component_column_selector.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/component_column_selector.py
Labels: ui, include in changelog, feat-dataframe-view

#7470 Update to latest `mp4` rev
  Cargo.lock
  Cargo.toml
  crates/store/re_video/Cargo.toml
  crates/store/re_video/src/lib.rs
  crates/store/re_video/src/mp4.rs
  crates/top/rerun_c/src/video.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_renderer/src/video/decoder/native.rs
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
Labels: exclude from changelog, 🎞️ video

#7474 Show which tracks are in an mp4 file
  Cargo.lock
  crates/store/re_video/src/lib.rs
  crates/store/re_video/src/mp4.rs
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
Labels: ui, exclude from changelog, 🎞️ video

#7473 Allow showing the same videos at several timestamps at the same time
  crates/store/re_types/definitions/rerun/archetypes/asset_video.fbs
  crates/store/re_types/definitions/rerun/archetypes/video_frame_reference.fbs
  crates/store/re_types/src/archetypes/asset_video.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/video/decoder/native.rs
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_space_view_spatial/src/mesh_cache.rs
  crates/viewer/re_space_view_spatial/src/proc_mesh.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/cache/caches.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/tensor_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_cache.rs
  docs/content/reference/types/archetypes/asset_video.md
  docs/content/reference/types/archetypes/video_frame_reference.md
  docs/snippets/all/archetypes/video_manual_frames.cpp
  docs/snippets/all/archetypes/video_manual_frames.py
  docs/snippets/all/archetypes/video_manual_frames.rs
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/asset_video.hpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.hpp
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  tests/assets/download_test_assets.py
Labels: exclude from changelog, 🎞️ video

#7477 Fix crate links in and hide implementation details in documentation
  crates/viewer/re_space_view_text_document/README.md
  crates/viewer/re_viewer_context/src/space_view/space_view_class.rs
Labels: 📖 documentation, exclude from changelog

#7469 Expand and fix the chunk zoo
  tests/python/chunk_zoo/chunk_zoo.py
Labels: 🔨 testing, 🐍 Python API, exclude from changelog

#7487 Text fields in the selection panel now span the available width
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: ui, include in changelog

#7476 simplify video timestamping - remove video time mode
  crates/store/re_types/definitions/rerun/components/video_timestamp.fbs
  crates/store/re_types/definitions/rerun/datatypes/video_timestamp.fbs
  crates/store/re_types/src/components/video_timestamp.rs
  crates/store/re_types/src/components/video_timestamp_ext.rs
  crates/store/re_types/src/datatypes/.gitattributes
  crates/store/re_types/src/datatypes/mod.rs
  crates/store/re_types/src/datatypes/video_time_mode.rs
  crates/store/re_types/src/datatypes/video_timestamp.rs
  crates/store/re_types/src/datatypes/video_timestamp_ext.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/.gitattributes
  docs/content/reference/types/datatypes/video_time_mode.md
  docs/content/reference/types/datatypes/video_timestamp.md
  rerun_cpp/src/rerun/components/video_timestamp.hpp
  rerun_cpp/src/rerun/components/video_timestamp_ext.cpp
  rerun_cpp/src/rerun/datatypes.hpp
  rerun_cpp/src/rerun/datatypes/.gitattributes
  rerun_cpp/src/rerun/datatypes/video_time_mode.cpp
  rerun_cpp/src/rerun/datatypes/video_time_mode.hpp
  rerun_cpp/src/rerun/datatypes/video_timestamp.cpp
  rerun_cpp/src/rerun/datatypes/video_timestamp.hpp
  rerun_py/rerun_sdk/rerun/components/video_timestamp_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/.gitattributes
  rerun_py/rerun_sdk/rerun/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/datatypes/video_time_mode.py
  rerun_py/rerun_sdk/rerun/datatypes/video_timestamp.py
Labels: exclude from changelog, 🎞️ video

#7490 Show a preview of videos when selected and hovered
  Cargo.lock
  Cargo.toml
  crates/store/re_video/src/lib.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/image.rs
Labels: ui, 📺 re_viewer, exclude from changelog, 🎞️ video

#7456 Improve performance for scenes with many entities & transforms
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_query/src/latest_at.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_space_view_spatial/src/transform_component_tracker.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#7496 Report video decoding errors to the user
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
Labels: 🪳 bug, exclude from changelog, 🎞️ video

#7492 implement proper fallback for Entitypath on video frame reference vis…
  crates/utils/re_format/src/lib.rs
  crates/utils/re_format/src/time.rs
  crates/viewer/re_component_ui/src/entity_path.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/video_timestamp.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
Labels: enhancement, exclude from changelog, 🎞️ video

#7475 Retry reading .rrd files until end-of-stream message header
  Cargo.lock
  Cargo.toml
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_encoding/src/file_sink.rs
  crates/store/re_log_encoding/src/lib.rs
  tests/rust/test_ui_wakeup/src/main.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, include in changelog

#7502 Show video at VideoTimestamp when hovering/selecting entity
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/instance_path.rs
Labels: exclude from changelog, 🎞️ video

#7501 linters fixes related to PR #7475
  Cargo.toml
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#7503 Fix error spam after decode error & make video error icon take a fixed amount of space
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
Labels: exclude from changelog, 🎞️ video

#7504 Fix BGR(A) rendering on WebGL
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_space_view_spatial/src/mesh_loader.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#7508 Remove unused `nox` dev dependency & mentions
  .gitignore
  .prettierignore
  noxfile.py
  pixi.lock
  pixi.toml
  pyrightconfig.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#7509 Update egui with less wgpu lifetimes
  Cargo.lock
  Cargo.toml
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/queueable_draw_data.rs
  crates/viewer/re_renderer/src/renderer/compositor.rs
  crates/viewer/re_renderer/src/renderer/debug_overlay.rs
  crates/viewer/re_renderer/src/renderer/depth_cloud.rs
  crates/viewer/re_renderer/src/renderer/generic_skybox.rs
  crates/viewer/re_renderer/src/renderer/lines.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_renderer/src/renderer/mod.rs
  crates/viewer/re_renderer/src/renderer/point_cloud.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_renderer/src/renderer/test_triangle.rs
  crates/viewer/re_renderer/src/view_builder.rs
  crates/viewer/re_renderer/src/wgpu_resources/bind_group_pool.rs
  crates/viewer/re_renderer/src/wgpu_resources/mod.rs
  crates/viewer/re_renderer/src/wgpu_resources/pipeline_layout_pool.rs
  crates/viewer/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
  crates/viewer/re_renderer/src/wgpu_resources/static_resource_pool.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_space_view_dataframe/Cargo.toml
  crates/viewer/re_space_view_tensor/src/space_view_class.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: dependencies, exclude from changelog, egui

#7512 Fix `cargo t --all`
  crates/viewer/re_ui/src/modal.rs
Labels: 🔨 testing, exclude from changelog, :ship: CI

#7514 Remove unnecessary lifetime from `ViewProperty`
  crates/viewer/re_space_view_dataframe/src/view_query.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_tensor/src/dimension_mapping.rs
  crates/viewer/re_space_view_tensor/src/space_view_class.rs
  crates/viewer/re_space_view_tensor/src/tensor_dimension_mapper.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog

#7513 `Caches` per recording
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/store_context.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
  crates/viewer/re_viewport_blueprint/src/space_view_contents.rs
Labels: 📉 performance, 🚜 refactor, include in changelog

#7507 Add `ProcMeshVisBuffer`, deduplicating visualizer code.
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_space_view/src/query.rs
  crates/viewer/re_space_view_bar_chart/src/visualizer_system.rs
  crates/viewer/re_space_view_dataframe/src/visualizer_system.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/proc_mesh_vis.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_space_view_tensor/src/visualizer_system.rs
  crates/viewer/re_space_view_text_document/src/visualizer_system.rs
  crates/viewer/re_space_view_text_log/src/visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_viewer_context/src/space_view/visualizer_system.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 📺 re_viewer, exclude from changelog

#7517 Document constraints of Viewer's continuous read behavior, fix related test
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/top/re_sdk/src/recording_stream.rs
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📖 documentation, 🔨 testing, exclude from changelog

#7511 Support h.264 video decoding on web
  crates/store/re_video/src/lib.rs
  crates/viewer/re_renderer/src/video/decoder/native.rs
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
Labels: 🕸️ web, include in changelog, 🎞️ video

#7520 Fix ci failures
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_deploy_docs.yml
  crates/top/re_sdk/src/recording_stream.rs
Labels: exclude from changelog, :ship: CI

#7518 Automatic removal of unreachable static chunks
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_entity_db/src/entity_db.rs
Labels: ⛃ re_datastore, 📉 performance, include in changelog, 🔩 data model

#7521 Make video decoding errors recoverable
  Cargo.lock
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/video/decoder/native.rs
  crates/viewer/re_renderer/src/video/decoder/web.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
Labels: exclude from changelog, 🎞️ video

#7524 Disable the `map_unwrap_or` lint
  Cargo.toml
Labels: 🦀 Rust API, 🧑‍💻 dev experience, exclude from changelog

#7523 Fix CI
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_track_size.yml
  pixi.lock
  pixi.toml
Labels: exclude from changelog, :ship: CI

#7530 Update to egui 0.29
  Cargo.lock
  Cargo.toml
  crates/viewer/re_space_view_dataframe/Cargo.toml
Labels: dependencies, exclude from changelog, egui

#7528 Don't show video load error if a blob has unrecognized or non-video media type
  crates/store/re_video/src/lib.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/instance_path.rs
Labels: exclude from changelog, 🎞️ video

#7525 Invalidate hub-wide caches on deletions and overwrites
  crates/store/re_entity_db/src/entity_db.rs
  crates/viewer/re_space_view_spatial/src/mesh_cache.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/cache/caches.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/tensor_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_cache.rs
  crates/viewer/re_viewer_context/src/image_info.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  examples/python/face_tracking/face_tracking.py
Labels: 📺 re_viewer, 📉 performance, include in changelog

#7531 Remove old `MeshManager`
  crates/store/re_chunk/src/transport.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/importer/gltf.rs
  crates/viewer/re_renderer/src/importer/obj.rs
  crates/viewer/re_renderer/src/importer/stl.rs
  crates/viewer/re_renderer/src/mesh.rs
  crates/viewer/re_renderer/src/renderer/depth_cloud.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_renderer/src/resource_managers/mesh_manager.rs
  crates/viewer/re_renderer/src/resource_managers/mod.rs
  crates/viewer/re_renderer/src/resource_managers/resource_manager.rs
  crates/viewer/re_renderer/src/resource_managers/texture_manager.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_renderer_examples/outlines.rs
  crates/viewer/re_renderer_examples/picking.rs
  crates/viewer/re_space_view_spatial/src/mesh_loader.rs
  crates/viewer/re_space_view_spatial/src/proc_mesh.rs
  crates/viewer/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  examples/python/face_tracking/face_tracking.py
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#7539 Fix missing re-export `OptionalSpaceViewEntityHighlight` from `re_viewer_context`
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/space_view/mod.rs
Labels: 🪳 bug, 🦀 Rust API, exclude from changelog

#7541 Show spinner icon while waiting for video decoder
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_space_view_spatial/src/picking_ui.rs
  crates/viewer/re_space_view_spatial/src/scene_bounding_boxes.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/spatial_view_visualizer.rs
  crates/viewer/re_space_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer_context/src/space_view/visualizer_system.rs
Labels: ui, exclude from changelog, 🎞️ video

#7547 Nightly ci fixes
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_test_wheels.yml
  crates/store/re_dataframe/README.md
  crates/store/re_types/definitions/rerun/datatypes/uint16.fbs
  docs/content/reference/types/datatypes/uint16.md
  docs/snippets/compare_snippet_output.py
Labels: exclude from changelog, :ship: CI

#7533 Add video reference docs
  crates/store/re_types/definitions/rerun/archetypes/asset_video.fbs
  crates/store/re_types/definitions/rerun/archetypes/video_frame_reference.fbs
  crates/store/re_types/src/archetypes/asset_video.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  docs/content/reference/types/archetypes/asset_video.md
  docs/content/reference/types/archetypes/video_frame_reference.md
  docs/content/reference/video.md
  rerun_cpp/src/rerun/archetypes/asset_video.hpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.hpp
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
Labels: 📖 documentation, include in changelog, 🎞️ video

#7550 Fix missing s in --break-system-packages
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_track_size.yml
Labels: exclude from changelog, :ship: CI

#7548 Do not deselect on ESC when it was used to close some other UI element
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_ui/src/modal.rs
  crates/viewer/re_viewer/src/app_state.rs
  tests/python/release_checklist/check_deselect_on_escape.py
Labels: ui, include in changelog
