Repository rerun-io/rerun, pull requests merged in 2024-05, with the labels that each got.

#6152 Remove `datagen`
  Cargo.lock
  crates/re_data_store/Cargo.toml
  crates/re_data_store/benches/arrow2.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_store/tests/data_store.rs
  crates/re_data_store/tests/dump.rs
  crates/re_entity_db/Cargo.toml
  crates/re_entity_db/examples/memory_usage.rs
  crates/re_log_encoding/Cargo.toml
  crates/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/re_log_types/src/example_components.rs
  crates/re_query/Cargo.toml
  crates/re_types/Cargo.toml
  crates/re_types/src/datagen.rs
  crates/re_types/src/lib.rs
Labels: 🔨 testing, 🚜 refactor, exclude from changelog

#6176 Make visible time range ui aware of latest-at & `QueryRange`
  crates/re_types_core/src/datatypes/visible_time_range_ext.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/query_range_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#6181 Markdown linter
  .github/workflows/reusable_checks.yml
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-in/rust.md
  docs/content/getting-started/what-is-rerun.md
  docs/content/reference/entity-queries.md
  pixi.toml
  scripts/ci/mdlint.py
Labels: 🧑‍💻 dev experience, include in changelog, :ship: CI

#6190 Fix auto properties no longer being applied for legacy properties (`EntityProperties`)
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/visualizers/results_ext.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport.rs
Labels: 🦟 regression, 🟦 blueprint, exclude from changelog

#6174 `ListItem` 2.0 (part 2): introduce `PropertyContent` for two-column, property-like list items
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/list_item2/list_item.rs
  crates/re_ui/src/list_item2/mod.rs
  crates/re_ui/src/list_item2/property_content.rs
  crates/re_ui/src/list_item2/scope.rs
  crates/re_ui/src/toggle_switch.rs
Labels: ui, include in changelog

#6182 `ListItem` 2.0 (part 3): `PropertyContent` column auto-sizing
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/list_item2/label_content.rs
  crates/re_ui/src/list_item2/list_item.rs
  crates/re_ui/src/list_item2/mod.rs
  crates/re_ui/src/list_item2/other_contents.rs
  crates/re_ui/src/list_item2/property_content.rs
  crates/re_ui/src/list_item2/scope.rs
Labels: ui, include in changelog

#6192 Fix 2d blueprint being edited without any interaction due to instant overwrite of default bounds
  crates/re_space_view_spatial/src/ui_2d.rs
Labels: 🦟 regression, exclude from changelog

#6183 `ListItem` 2.0 (part 4): only allocate space for property action buttons when needed
  Cargo.lock
  crates/re_ui/Cargo.toml
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/drag_and_drop.rs
  crates/re_ui/src/list_item2/list_item.rs
  crates/re_ui/src/list_item2/mod.rs
  crates/re_ui/src/list_item2/other_contents.rs
  crates/re_ui/src/list_item2/property_content.rs
  crates/re_ui/src/list_item2/scope.rs
Labels: ui, include in changelog

#6200 Fix not being able to click suggestions in space origin selection dropdown
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
Labels: 🪳 bug, ui, include in changelog

#6199 Fix bug in origin selection ui
  CODE_STYLE.md
  crates/re_space_view/src/heuristics.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/spawn_heuristics.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🪳 bug, ui, include in changelog

#6187 Introduce new mechanism to incrementally drain from a memory_recording
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/memory.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  tests/python/memory_drain/main.py
Labels: 🐍 Python API, include in changelog

#6202 Fix out-of-bounds crash in origin selection popup
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
Labels: 🪳 bug, ui, 💣 crash, include in changelog

#6207 Handle the extra StoreInfo from memory_sink
  crates/re_sdk/src/recording_stream.rs
Labels: 🔨 testing, 🦟 regression, exclude from changelog

#6189 Add a new javascript API for submitting an RRD that is stored directly as bytes
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/viewer_analytics/event.rs
  crates/re_viewer/src/web.rs
  rerun_js/web-viewer/index.js
Labels: notebook, include in changelog, 🪵 Log-API

#6201 Replace some `a = b.clone()` with `a.clone_from(b)`
  crates/re_data_store/src/store_read.rs
  crates/re_data_ui/src/editors.rs
  crates/re_query/src/bin/clamped_zip.rs
  crates/re_query/src/bin/range_zip.rs
  crates/re_query/src/clamped_zip/generated.rs
  crates/re_query/src/range_zip/generated.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewport/src/container.rs
Labels: 📉 performance, exclude from changelog

#6196 Fix ui showing the wrong default solid color when switching from gradient
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#6208 Handle reentrancy edge case in deserialization cache
  crates/re_query/src/range/results.rs
Labels: 🪳 bug, 🔍 re_query, exclude from changelog

#6194 Add button to equalize the size of the children of a container
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: ui, 🟦 blueprint, include in changelog

#6212 Use thousands separators when formatting seconds
  .typos.toml
  .vscode/settings.json
  CHANGELOG.md
  crates/re_log_types/src/time.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types_builder/src/codegen/rust/api.rs
Labels: ui, include in changelog

#6209 Automate parallelism & reentrancy checklist
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
Labels: 🔨 testing, 🔍 re_query, exclude from changelog

#6214 Fix multi-tenant cache concurrency edge-case
  crates/re_query/src/range/query.rs
  crates/re_query/tests/range.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
Labels: 🪳 bug, 🔍 re_query, exclude from changelog

#6184 `ListItem` 2.0 (part 5): deploy to the Visualizers and Overrides UIs
  crates/re_data_ui/src/editors.rs
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/list_item2/label_content.rs
  crates/re_ui/src/list_item2/list_item.rs
  crates/re_ui/src/list_item2/property_content.rs
  crates/re_ui/src/list_item2/scope.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, include in changelog

#6177 Fix missing data for "bridged" range queries
  crates/re_query/src/latest_at/query.rs
  crates/re_query/src/range/query.rs
  crates/re_query/tests/range.rs
Labels: 🪳 bug, 🔍 re_query, exclude from changelog

#6217 Fix formatting of relative times
  crates/re_format/src/lib.rs
  crates/re_log_types/src/time.rs
Labels: 🪳 bug, exclude from changelog

#6220 Fix merge race
  crates/re_query/tests/range.rs
Labels: exclude from changelog, :ship: CI

#6225 Solve inconsistency between code and comment
  crates/re_types/src/datatypes/mat4x4_ext.rs
Labels: 📖 documentation, exclude from changelog

#6229 Fix migration guide redirect link
  docs/content/reference/migration-0-9.md
Labels: 📖 documentation, exclude from changelog

#6230 Fix bad anchor links
  docs/content/reference/viewer/blueprint.md
  examples/python/arflow/README.md
Labels: 📖 documentation, exclude from changelog

#6235 Add space view icons to various context menus
  Cargo.lock
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/context_menu/actions/add_container.rs
  crates/re_viewport/src/context_menu/actions/add_space_view.rs
  crates/re_viewport/src/context_menu/actions/move_contents_to_new_container.rs
  crates/re_viewport/src/context_menu/mod.rs
  scripts/generate_changelog.py
Labels: ui, include in changelog

#6244 Remove dead code, behind unused feature flags
  crates/re_renderer/build.rs
  crates/re_sdk/src/global.rs
  crates/re_sdk/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#6240 Work around some issues where recording streams leaking context when used with generators
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#6242 Introduce a new BinaryStreamSink that allows reading a stream of encoded bytes
  crates/re_sdk/src/binary_stream_sink.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_binary_stream.py
Labels: 🐍 Python API, include in changelog

#6251 Fix rare crash
  crates/re_smart_channel/src/sender.rs
Labels: 🪳 bug, 💣 crash, include in changelog

#6257 Support for unit variants on arrow unions
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types/definitions/rerun/unit_type.fbs
  crates/re_types/src/testing/components/affix_fuzzer14.rs
  crates/re_types/src/testing/components/affix_fuzzer15.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer3.rs
  crates/re_types/tests/fuzzy.rs
  crates/re_types_builder/src/codegen/cpp/array_builder.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_builder/src/objects.rs
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/tests/generated/datatypes/affix_fuzzer3.cpp
  rerun_cpp/tests/generated/datatypes/affix_fuzzer3.hpp
  rerun_py/tests/test_types/components/affix_fuzzer16.py
  rerun_py/tests/test_types/components/affix_fuzzer17.py
  rerun_py/tests/test_types/components/affix_fuzzer18.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer3.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer4.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer5.py
Labels: codegen/idl, exclude from changelog

#6255 Fix visual glitch when extending the time panel
  crates/re_viewer/src/app_state.rs
Labels: 🪳 bug, ui, include in changelog

#6259 `VisibleTimeRange` is now a union, add serialization comparision test
  Cargo.lock
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/visible_time_ranges.fbs
  crates/re_types/definitions/rerun/datatypes/visible_time_range.fbs
  crates/re_types/src/blueprint/archetypes/visible_time_ranges.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_types_core/src/datatypes/.gitattributes
  crates/re_types_core/src/datatypes/mod.rs
  crates/re_types_core/src/datatypes/time_range_boundary.rs
  crates/re_types_core/src/datatypes/time_range_boundary_ext.rs
  crates/re_types_core/src/datatypes/time_range_boundary_kind.rs
  crates/re_types_core/src/datatypes/time_range_ext.rs
  crates/re_viewer/src/ui/query_range_ui.rs
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/.gitattributes
  docs/content/reference/types/datatypes/time_range_boundary.md
  docs/content/reference/types/datatypes/time_range_boundary_kind.md
  rerun_cpp/src/rerun/blueprint/archetypes/visible_time_ranges.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/visible_time_ranges.hpp
  rerun_cpp/src/rerun/datatypes.hpp
  rerun_cpp/src/rerun/datatypes/.gitattributes
  rerun_cpp/src/rerun/datatypes/time_range.cpp
  rerun_cpp/src/rerun/datatypes/time_range_boundary.cpp
  rerun_cpp/src/rerun/datatypes/time_range_boundary.hpp
  rerun_cpp/src/rerun/datatypes/time_range_boundary_kind.cpp
  rerun_cpp/src/rerun/datatypes/time_range_boundary_kind.hpp
  rerun_cpp/src/rerun/datatypes/utf8.hpp
  rerun_cpp/src/rerun/datatypes/utf8_ext.cpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/visible_time_ranges.py
  rerun_py/rerun_sdk/rerun/datatypes/.gitattributes
  rerun_py/rerun_sdk/rerun/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary_kind.py
  rerun_py/rerun_sdk/rerun/datatypes/visible_time_range.py
  tests/cpp/roundtrips/visible_time_ranges/main.cpp
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/roundtrips/visible_time_ranges/main.py
  tests/roundtrips.py
  tests/rust/roundtrips/visible_time_ranges/Cargo.toml
  tests/rust/roundtrips/visible_time_ranges/src/main.rs
Labels: 🔨 testing, 🟦 blueprint, exclude from changelog

#6266 fix double word
  crates/re_types_builder/src/codegen/python/mod.rs
Labels: exclude from changelog

#6261 Reduce the logging verbosity of zbus and tracing
  crates/re_log/src/lib.rs
Labels: 📺 re_viewer, 🐧 linux, exclude from changelog

#6269 fix `None` type handling on union codegen
  crates/re_types_builder/src/codegen/python/mod.rs
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary.py
Labels: codegen/idl, exclude from changelog

#6270 Fix link checker trying to resolve login-required posthog link
  lychee.toml
Labels: exclude from changelog, :ship: CI

#6260 Keep rerun viewer from dying on ctrl-c by setting sid on unix systems
  Cargo.lock
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/spawn.rs
Labels: 🐧 linux, include in changelog, 🪵 Log-API, :apple: MacOS

#6221 Improve new time_ranges property python api & add snippet for time series view, explaining all its options
  crates/re_types/definitions/rerun/blueprint/archetypes/visible_time_ranges.fbs
  crates/re_types/definitions/rerun/blueprint/views/time_series.fbs
  docs/content/reference/types/views/time_series_view.md
  docs/snippets/all/timeseriesview.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial2d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial3d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/time_series_view.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/visible_time_range.py
  rerun_py/rerun_sdk/rerun/datatypes/visible_time_range_ext.py
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/roundtrips/visible_time_ranges/main.py
Labels: 📖 documentation, 🐍 Python API, include in changelog

#6252 Improve error message when using an under-powered GPU
  crates/re_renderer/src/context.rs
  crates/re_renderer_examples/framework.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/web.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: ui, 🔺 re_renderer, include in changelog

#6267 Add a release checklist to check the UI for all components
  examples/python/open_photogrammetry_format/open_photogrammetry_format.py
  tests/python/release_checklist/check_all_components_ui.py
Labels: 🔨 testing, ui, exclude from changelog

#6262 Add a new CLI option / spawn options to hide the welcome screen
  crates/re_sdk/src/spawn.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/no_data_ui.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/spawn_options.cpp
  rerun_cpp/src/rerun/spawn_options.hpp
  rerun_js/web-viewer-react/index.js
  rerun_js/web-viewer/index.js
  rerun_py/rerun_sdk/rerun/_spawn.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 📺 re_viewer, include in changelog, 🪵 Log-API

#6285 Fix crash on `i32` overflow during arrow serialization
  crates/re_types/src/blueprint/components/active_tab.rs
  crates/re_types/src/blueprint/components/included_content.rs
  crates/re_types/src/blueprint/components/query_expression.rs
  crates/re_types/src/blueprint/components/space_view_class.rs
  crates/re_types/src/blueprint/components/space_view_origin.rs
  crates/re_types/src/components/media_type.rs
  crates/re_types/src/components/name.rs
  crates/re_types/src/components/text.rs
  crates/re_types/src/components/text_log_level.rs
  crates/re_types/src/datatypes/annotation_info.rs
  crates/re_types/src/datatypes/tensor_dimension.rs
  crates/re_types/src/testing/components/affix_fuzzer10.rs
  crates/re_types/src/testing/components/affix_fuzzer12.rs
  crates/re_types/src/testing/components/affix_fuzzer13.rs
  crates/re_types/src/testing/components/affix_fuzzer9.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer1.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer20.rs
  crates/re_types/src/testing/datatypes/string_component.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_core/src/components/visualizer_overrides.rs
  crates/re_types_core/src/datatypes/entity_path.rs
  crates/re_types_core/src/datatypes/utf8.rs
  crates/re_types_core/src/datatypes/visible_time_range.rs
  crates/re_types_core/src/result.rs
Labels: 🦀 Rust API, 💣 crash, codegen/idl, include in changelog

#6284 Show Cargo.lock in GitHub diffs
  .gitattributes
Labels: 🧑‍💻 dev experience, exclude from changelog

#6287 Improve the default UI when the welcome screen is hidden
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/no_data_ui.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/no_data_ui.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: ui, include in changelog

#6290 Fix clippy warning about hide_welcome_screen on wasm
  crates/re_viewer/src/web.rs
Labels: 🕸️ web, exclude from changelog

#6283 Validate the blueprint schema when we try to activate a blueprint sent from SDK
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/store_hub.rs
Labels: 🟦 blueprint, include in changelog

#6296 Don't automatically fall back to automatic port if web socket port is already in use, only recommend using 0 instead
  crates/re_ws_comms/src/lib.rs
  crates/re_ws_comms/src/server.rs
Labels: 🪳 bug, include in changelog

#6272 Codegen Rust comments
  crates/re_types/src/blueprint/components/background_kind.rs
  crates/re_types/src/blueprint/components/corner2d.rs
  crates/re_types/src/components/half_sizes2d.rs
  crates/re_types/src/components/half_sizes3d.rs
  crates/re_types/src/components/marker_shape.rs
  crates/re_types/src/components/pinhole_projection.rs
  crates/re_types/src/components/position2d.rs
  crates/re_types/src/components/position3d.rs
  crates/re_types/src/components/range1d.rs
  crates/re_types/src/components/resolution.rs
  crates/re_types/src/components/texcoord2d.rs
  crates/re_types/src/components/triangle_indices.rs
  crates/re_types/src/components/vector2d.rs
  crates/re_types/src/components/vector3d.rs
  crates/re_types/src/components/view_coordinates.rs
  crates/re_types/src/datatypes/angle.rs
  crates/re_types/src/datatypes/mat3x3.rs
  crates/re_types/src/datatypes/mat4x4.rs
  crates/re_types/src/datatypes/quaternion.rs
  crates/re_types/src/datatypes/range1d.rs
  crates/re_types/src/datatypes/range2d.rs
  crates/re_types/src/datatypes/rotation3d.rs
  crates/re_types/src/datatypes/rotation_axis_angle.rs
  crates/re_types/src/datatypes/scale3d.rs
  crates/re_types/src/datatypes/tensor_buffer.rs
  crates/re_types/src/datatypes/transform3d.rs
  crates/re_types/src/datatypes/translation_and_mat3x3.rs
  crates/re_types/src/datatypes/translation_rotation_scale3d.rs
  crates/re_types/src/datatypes/uuid.rs
  crates/re_types/src/datatypes/uvec2d.rs
  crates/re_types/src/datatypes/uvec3d.rs
  crates/re_types/src/datatypes/uvec4d.rs
  crates/re_types/src/datatypes/vec2d.rs
  crates/re_types/src/datatypes/vec3d.rs
  crates/re_types/src/datatypes/vec4d.rs
  crates/re_types/src/testing/components/enum_test.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer22.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer3.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer4.rs
  crates/re_types_blueprint/src/blueprint/components/container_kind.rs
  crates/re_types_blueprint/src/blueprint/components/included_space_view.rs
  crates/re_types_blueprint/src/blueprint/components/root_container.rs
  crates/re_types_blueprint/src/blueprint/components/space_view_maximized.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_builder/src/codegen/rust/util.rs
  crates/re_types_core/src/datatypes/time_range_boundary.rs
Labels: 🦀 Rust API, codegen/idl, exclude from changelog

#6233 Add a migration guide from 0.15 to 0.16
  docs/content/reference/migration.md
  docs/content/reference/migration/migration-0-16.md
Labels: 📖 documentation, ⛴ release, exclude from changelog

#6291 Rename `UiVerbosity` to `UiLayout` and make its variants more precise
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/app_id.rs
  crates/re_data_ui/src/blueprint_data.rs
  crates/re_data_ui/src/blueprint_types.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/data_source.rs
  crates/re_data_ui/src/editors.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/entity_path.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_data_ui/src/material.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_data_ui/src/store_id.rs
  crates/re_data_ui/src/transform3d.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/lib.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🚜 refactor, exclude from changelog

#6271 Fix possible hang when using torch.multiprocessing
  crates/re_sdk/src/recording_stream.rs
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_multiprocessing_gc.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#6301 Fix cmake missing rerun_c changes due to broken glob
  crates/rerun_c/CMakeLists.txt
Labels: 🧑‍💻 dev experience, 🦟 regression, 🌊 C++ API, exclude from changelog

#6302 Fix: Preserve history state
  crates/re_viewer/src/web_tools.rs
Labels: 🕸️ web, include in changelog

#6305 Fix egui id clash in selection panel
  crates/re_ui/src/list_item.rs
Labels: 🪳 bug, ui, exclude from changelog

#6292 Fix issues with cache invalidation related to parallel queries.
  crates/re_query/src/cache_stats.rs
  crates/re_query/src/flat_vec_deque.rs
  crates/re_query/src/range/query.rs
  crates/re_query/src/range/results.rs
  crates/re_query/tests/range.rs
Labels: 🪳 bug, ⛃ re_datastore, exclude from changelog

#6297 Improve UI of various components in the selection panel
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_data_ui/src/transform3d.rs
  crates/re_types/src/components/range1d_ext.rs
  crates/re_types/src/datatypes/angle_ext.rs
  crates/re_types/src/datatypes/range2d_ext.rs
  tests/python/release_checklist/check_all_components_ui.py
Labels: ui, include in changelog

#6316 Fix trying to publish `plot_dashboard_stress`
  tests/rust/plot_dashboard_stress/Cargo.toml
Labels: ⛴ release, 🦟 regression, exclude from changelog

#6314 New example and tutorial showing how to create a live scrolling plot
  docs/content/howto.md
  docs/content/howto/fixed-window-plot.md
  docs/snippets/all/tutorials/fixed_window_plot.py
  docs/snippets/snippets.toml
  examples/manifest.toml
  examples/python/live_scrolling_plot/README.md
  examples/python/live_scrolling_plot/live_scrolling_plot.py
  examples/python/live_scrolling_plot/pyproject.toml
  pixi.lock
  pixi.toml
  rerun_py/tests/unit/test_multiprocessing_gc.py
Labels: 📖 documentation, examples, include in changelog

#6253 Send TCP protocol header to ignore non-rerun clients
  Cargo.lock
  crates/re_sdk_comms/src/lib.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_sdk_comms/src/tcp_client.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
Labels: include in changelog

#6304 Add code examples & screenshots for all blueprint view types
  crates/re_types/definitions/rerun/blueprint/views/bar_chart.fbs
  crates/re_types/definitions/rerun/blueprint/views/spatial2d.fbs
  crates/re_types/definitions/rerun/blueprint/views/spatial3d.fbs
  crates/re_types/definitions/rerun/blueprint/views/tensor.fbs
  crates/re_types/definitions/rerun/blueprint/views/text_document.fbs
  crates/re_types/definitions/rerun/blueprint/views/text_log.fbs
  crates/re_types/definitions/rerun/blueprint/views/time_series.fbs
  docs/content/reference/types/views/bar_chart_view.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  docs/content/reference/types/views/tensor_view.md
  docs/content/reference/types/views/text_document_view.md
  docs/content/reference/types/views/text_log_view.md
  docs/content/reference/types/views/time_series_view.md
  docs/snippets/all/views/bar_chart.py
  docs/snippets/all/views/spatial2d.py
  docs/snippets/all/views/spatial3d.py
  docs/snippets/all/views/spatial3dview.py
  docs/snippets/all/views/tensor.py
  docs/snippets/all/views/text_document.py
  docs/snippets/all/views/text_log.py
  docs/snippets/all/views/timeseries.py
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/blueprint/views/bar_chart_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial2d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial3d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/tensor_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/text_document_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/text_log_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/time_series_view.py
Labels: 📖 documentation, 🐍 Python API, include in changelog

#6322 Transmit url analytics correctly for rerun.io domains
  Cargo.lock
  crates/re_analytics/Cargo.toml
  crates/re_analytics/src/event.rs
  lychee.toml
Labels: 🕸️ web, 📊 analytics, include in changelog

#6324 Keep track of the RRD protocol version and display it where relevant
  Cargo.lock
  crates/re_analytics/src/event.rs
  crates/re_build_info/Cargo.toml
  crates/re_build_info/src/crate_version.rs
  crates/re_data_loader/Cargo.toml
  crates/re_data_loader/src/load_file.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_entity_db/Cargo.toml
  crates/re_entity_db/examples/memory_usage.rs
  crates/re_entity_db/src/store_bundle.rs
  crates/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/re_log_encoding/src/decoder/mod.rs
  crates/re_log_encoding/src/decoder/stream.rs
  crates/re_log_encoding/src/encoder.rs
  crates/re_log_encoding/src/file_sink.rs
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/binary_stream_sink.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/Cargo.toml
  crates/re_sdk_comms/src/buffered_client.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/saving.rs
  crates/re_viewer/src/viewer_analytics/event.rs
  crates/rerun/src/run.rs
Labels: enhancement, ⛃ re_datastore, 📺 re_viewer, 📊 analytics, include in changelog

#6323 Cleanup of todos referring to closed tickets
  crates/re_data_loader/src/lib.rs
  crates/re_data_ui/src/app_id.rs
  crates/re_data_ui/src/data_source.rs
  crates/re_entity_db/src/time_histogram_per_timeline.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/time_point/mod.rs
  crates/re_log_types/src/time_point/time_int.rs
  crates/re_query/src/latest_at/helpers.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/lib.rs
  crates/re_time_panel/src/time_selection_ui.rs
  crates/re_types/definitions/rerun/components/view_coordinates.fbs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/objects.rs
  crates/re_ui/src/list_item2/list_item.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/time_control.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport_blueprint.rs
  docs/snippets/build.rs
  examples/cpp/incremental_logging/main.cpp
  examples/python/depth_guided_stable_diffusion/pyproject.toml
  examples/python/incremental_logging/incremental_logging.py
  examples/rust/incremental_logging/src/main.rs
  rerun_cpp/src/rerun/c/rerun.h
  tests/python/roundtrips/visible_time_ranges/main.py
Labels: 🚜 refactor, exclude from changelog

#6329 Fix broken drag and drop
  crates/re_ui/src/list_item.rs
Labels: 🪳 bug, ui, exclude from changelog

#6327 Set a minimum version of pillow in `rerun_py/pyproject.toml`
  examples/python/raw_mesh/pyproject.toml
  pixi.lock
  rerun_py/pyproject.toml
Labels: 🪳 bug, 🐍 Python API, dependencies, include in changelog

#6331 Fix python example links
  docs/content/getting-started/data-in/python.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/reference/sdk-operating-modes.md
  examples/cpp/external_data_loader/README.md
  examples/python/external_data_loader/README.md
  examples/rust/external_data_loader/README.md
Labels: 📖 documentation, exclude from changelog

#6326 Make it possible to open http-streamed RRDs in follow mode via JS API.
  crates/re_data_source/src/data_source.rs
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_smart_channel/src/receive_set.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer/src/web_tools.rs
  crates/re_viewer_context/src/store_hub.rs
  rerun_js/web-viewer/index.js
Labels: enhancement, 🕸️ web, include in changelog

#6335 Make sure all log messages are sent when using `.serve()`
  crates/re_sdk/src/web_viewer.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_smart_channel/src/sender.rs
  crates/re_viewer/src/app.rs
  crates/re_web_viewer_server/src/lib.rs
  crates/re_ws_comms/src/server.rs
  crates/rerun/src/run.rs
  pixi.toml
  rerun_py/Cargo.toml
Labels: 🪳 bug, 🕸️ web, include in changelog, 🪵 Log-API

#6338 Move sort out of inner loop to fix perf regression on updating range cache
  crates/re_query/src/range/query.rs
Labels: ⛃ re_datastore, 🦟 regression, exclude from changelog

#6339 Disable flush_blocking in Sender on wasm
  clippy.toml
  crates/re_smart_channel/src/sender.rs
  scripts/ci/rust_checks.py
Labels: 🪳 bug, 🕸️ web, exclude from changelog

#6340 fix incorrect roundtrips.py test exception
  tests/roundtrips.py
Labels: 🦟 regression, exclude from changelog, :ship: CI

#6341 Respect the RERUN_STRICT environment variable if not specified in rr.init
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/tests/unit/test_exceptions.py
Labels: 🐍 Python API, include in changelog

#6342 Fix typo in VisualBounds2DExt causing it to throw
  crates/re_dev_tools/src/build_examples/snippets.rs
  docs/snippets/compare_snippet_output.py
  docs/snippets/snippets.toml
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/visual_bounds2d_ext.py
Labels: 🪳 bug, exclude from changelog

#6345 Quick fix for `check_all_components_ui.py`
  tests/python/release_checklist/check_all_components_ui.py
Labels: 🔨 testing, exclude from changelog

#6346 Better docstrings for views
  crates/re_types/definitions/rerun/blueprint/views/spatial2d.fbs
  crates/re_types/definitions/rerun/blueprint/views/spatial3d.fbs
  crates/re_types/definitions/rerun/blueprint/views/tensor.fbs
  crates/re_types/definitions/rerun/blueprint/views/text_document.fbs
  crates/re_types/definitions/rerun/blueprint/views/text_log.fbs
  crates/re_types/definitions/rerun/blueprint/views/time_series.fbs
  crates/re_types/src/blueprint/views/spatial2d_view.rs
  crates/re_types/src/blueprint/views/spatial3d_view.rs
  crates/re_types/src/blueprint/views/tensor_view.rs
  crates/re_types/src/blueprint/views/text_document_view.rs
  crates/re_types/src/blueprint/views/text_log_view.rs
  crates/re_types/src/blueprint/views/time_series_view.rs
  docs/content/reference/types/views.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  docs/content/reference/types/views/tensor_view.md
  docs/content/reference/types/views/text_document_view.md
  docs/content/reference/types/views/text_log_view.md
  docs/content/reference/types/views/time_series_view.md
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial2d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial3d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/tensor_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/text_document_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/text_log_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/time_series_view.py
Labels: 📖 documentation, exclude from changelog

#6350 Explain static vs temporal components in the UI
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, exclude from changelog

#6351 Use nicer colors for the `Spatial2DView` snippet
  crates/re_types/definitions/rerun/blueprint/views/spatial2d.fbs
  docs/content/reference/types/views/spatial2d_view.md
  docs/snippets/all/views/spatial2d.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial2d_view.py
Labels: 📖 documentation, exclude from changelog

#6334 Cleanup usage of `unwrap()` in `re_data_store`
  Cargo.toml
  crates/re_data_store/src/arrow_util.rs
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_gc.rs
  crates/re_data_store/src/store_read.rs
  crates/re_data_store/src/store_write.rs
  crates/re_data_store/src/test_util.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#6359 Quiet the 'not a mono-batch' log spam when selecting keypoint with a batch class-id
  crates/re_data_ui/src/annotation_context.rs
Labels: ui, 😤 annoying, include in changelog

#6361 Fix clearing mesh3d causing a warning
  crates/re_renderer/src/mesh.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
Labels: 🔺 re_renderer, 📺 re_viewer, 🦟 regression, exclude from changelog

#6360 Fix width/height/channel extraction logic
  crates/re_types/src/datatypes/tensor_data_ext.rs
Labels: 🔺 re_renderer, 🦟 regression, exclude from changelog

#6362 Fix crate isolation build issues
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/app.rs
  rerun_py/build.rs
Labels: 🦟 regression, exclude from changelog, :ship: CI

#6337 Cleanup usage of unwrap() in re_dev_tools
  crates/re_dev_tools/src/build_examples/example.rs
  crates/re_dev_tools/src/build_examples/snippets.rs
  crates/re_dev_tools/src/build_search_index/ingest.rs
  crates/re_dev_tools/src/build_search_index/ingest/cpp.rs
  crates/re_dev_tools/src/build_search_index/ingest/docs.rs
  crates/re_dev_tools/src/build_search_index/ingest/rust.rs
  crates/re_dev_tools/src/build_search_index/meili.rs
  crates/re_dev_tools/src/build_search_index/repl.rs
  crates/re_dev_tools/src/main.rs
Labels: 🚜 refactor, exclude from changelog

#6368 Don't log warnings when unknown clients connect over TCP
  crates/re_viewer/src/app.rs
Labels: 📺 re_viewer, 😤 annoying, include in changelog

#6373 Drop rerun_cpp_sdk-{tag}-multiplatform.zip in favor of rerun_cpp_sdk.zip
  scripts/ci/sync_release_assets.py
Labels: 🪳 bug, ⛴ release, exclude from changelog

#6381 Add docs on how to install C++ SDK with conda-forge packages
  rerun_cpp/README.md
Labels: 📖 documentation, 🌊 C++ API, include in changelog

#6369 Fix unnecessary re_viewer dependency
  CHANGELOG.md
  crates/re_sdk_comms/src/lib.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#6384 Fix not being able to set time series y axis ranges from ui
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/src/components/range1d_ext.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, include in changelog

#6390 Update the UI for time series view properties using list item
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: ui, include in changelog

#6391 Fix re_sdk_comms isolated compilation
  crates/re_sdk_comms/src/lib.rs
Labels: 🦟 regression, exclude from changelog

#6325 Add support for exact width to `PropertyContent`
  crates/re_ui/src/list_item2/property_content.rs
  crates/re_ui/src/list_item2/scope.rs
Labels: ui, include in changelog

#6377 `list_item2` migration (part 2): convert all use of legacy list time to `list_item2`
  crates/re_data_ui/src/item_ui.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_ui/src/modal.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#6378 `list_item2` migration (part 3): rename `list_item2` to `list_item`
  crates/re_data_ui/src/editors.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example/drag_and_drop.rs
  crates/re_ui/examples/re_ui_example/hierarchical_drag_and_drop.rs
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/drag_and_drop.rs
  crates/re_ui/src/full_span.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item/label_content.rs
  crates/re_ui/src/list_item/list_item.rs
  crates/re_ui/src/list_item/mod.rs
  crates/re_ui/src/list_item/other_contents.rs
  crates/re_ui/src/list_item/property_content.rs
  crates/re_ui/src/list_item/scope.rs
  crates/re_ui/src/modal.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, 🚜 refactor, include in changelog

#6401 Improve the colormap drop down menu
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
Labels: ui, include in changelog

#6397 Reduce height of top and bottom panels
  crates/re_entity_db/src/entity_db.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/src/lib.rs
Labels: ui, include in changelog

#6406 Allow toggling panels in welcome screen app
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/lib.rs
Labels: 📺 re_viewer, 🟦 blueprint, exclude from changelog

#6400 Generic view property building, applied to `TimeSeriesView`'s `PlotLegend`
  crates/re_data_ui/src/editors/corner2d.rs
  crates/re_data_ui/src/editors/mod.rs
  crates/re_data_ui/src/editors/visible.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/view_properties.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types_core/src/loggable.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer_context/src/component_ui_registry.rs
Labels: 🚜 refactor, include in changelog

#6407 Allow hiding all panels (including the menu bar!)
  Cargo.lock
  crates/re_query/src/latest_at/to_archetype/panel_blueprint.rs
  crates/re_time_panel/Cargo.toml
  crates/re_time_panel/src/lib.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/panel_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/panel_state.fbs
  crates/re_types/src/blueprint/components/.gitattributes
  crates/re_types/src/blueprint/components/mod.rs
  crates/re_types/src/blueprint/components/panel_expanded.rs
  crates/re_types/src/blueprint/components/panel_state.rs
  crates/re_types/src/blueprint/components/panel_state_ext.rs
  crates/re_types_blueprint/src/blueprint/archetypes/panel_blueprint.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/re_viewer/src/ui/top_panel.rs
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/howto/configure-viewer-through-code.md
  examples/python/blueprint/blueprint.py
  examples/python/blueprint_stocks/blueprint_stocks.py
  examples/python/depth_guided_stable_diffusion/depth_guided_stable_diffusion/__main__.py
  examples/python/plots/plots.py
  rerun_cpp/src/rerun/blueprint/archetypes/panel_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/panel_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/panel_expanded.hpp
  rerun_cpp/src/rerun/blueprint/components/panel_state.cpp
  rerun_cpp/src/rerun/blueprint/components/panel_state.hpp
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/panel_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/panel_expanded.py
  rerun_py/rerun_sdk/rerun/blueprint/components/panel_state.py
  tests/python/blueprint/main.py
  tests/python/blueprint/save_blueprint.py
  tests/python/blueprint/spawn_blueprint.py
Labels: ui, 🟦 blueprint, include in changelog

#6408 Use literal unions in python enum codegen
  crates/re_types_builder/src/codegen/python/mod.rs
  examples/python/blueprint_stocks/blueprint_stocks.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/background_kind.py
  rerun_py/rerun_sdk/rerun/blueprint/components/container_kind.py
  rerun_py/rerun_sdk/rerun/blueprint/components/corner2d.py
  rerun_py/rerun_sdk/rerun/blueprint/components/panel_state.py
  rerun_py/rerun_sdk/rerun/components/marker_shape.py
  rerun_py/tests/test_types/components/enum_test.py
Labels: 🐍 Python API, codegen/idl, include in changelog

#6413 Generate archetype field info (opt-in for a single type so far) and use it in blueprint property ui
  Cargo.lock
  crates/re_log_types/src/example_components.rs
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/view_property_ui.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/plot_legend.fbs
  crates/re_types/definitions/rust/attributes.fbs
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/arrows2d.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/bar_chart.rs
  crates/re_types/src/archetypes/boxes2d.rs
  crates/re_types/src/archetypes/boxes3d.rs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/archetypes/image.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/mesh3d.rs
  crates/re_types/src/archetypes/pinhole.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/scalar.rs
  crates/re_types/src/archetypes/segmentation_image.rs
  crates/re_types/src/archetypes/series_line.rs
  crates/re_types/src/archetypes/series_point.rs
  crates/re_types/src/archetypes/tensor.rs
  crates/re_types/src/archetypes/text_document.rs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/archetypes/view_coordinates.rs
  crates/re_types/src/blueprint/archetypes/background.rs
  crates/re_types/src/blueprint/archetypes/plot_legend.rs
  crates/re_types/src/blueprint/archetypes/scalar_axis.rs
  crates/re_types/src/blueprint/archetypes/space_view_blueprint.rs
  crates/re_types/src/blueprint/archetypes/space_view_contents.rs
  crates/re_types/src/blueprint/archetypes/visible_time_ranges.rs
  crates/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer1.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer2.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer3.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer4.rs
  crates/re_types_blueprint/src/blueprint/archetypes/container_blueprint.rs
  crates/re_types_blueprint/src/blueprint/archetypes/panel_blueprint.rs
  crates/re_types_blueprint/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_types_builder/src/casing.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/util.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_core/src/archetype.rs
  crates/re_types_core/src/archetypes/clear.rs
  crates/re_types_core/src/lib.rs
  crates/re_viewport_blueprint/src/lib.rs
  crates/re_viewport_blueprint/src/space_view_contents.rs
  crates/re_viewport_blueprint/src/view_properties.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 📺 re_viewer, ⛴ release, codegen/idl, exclude from changelog

#6392 Remove the ability to display multiple tensors in a single space view
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  docs/snippets/all/views/tensor.py
  rerun_py/rerun_sdk/rerun/blueprint/views/tensor_view.py
  tests/python/release_checklist/check_mono_entity_views.py
Labels: ui, include in changelog

#6422 Smooth scrolling in 2D space views
  crates/re_space_view_spatial/src/ui_2d.rs
Labels: ui, include in changelog

#6426 Improve styling of list item's collapsing triangle
  crates/re_ui/src/list_item/list_item.rs
Labels: ui, exclude from changelog

#6398 Fix `ListItem` bugs
  crates/re_space_view/src/view_property_ui.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example/hierarchical_drag_and_drop.rs
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/list_item/list_item.rs
  crates/re_ui/src/list_item/scope.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, ui, exclude from changelog

#6421 Improve welcome screen for small screens
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: ui, include in changelog

#6380 Refactor usage of unwrap in re_db, re_format_arrow & re_log_types
  crates/re_entity_db/src/entity_tree.rs
  crates/re_entity_db/src/lib.rs
  crates/re_format_arrow/src/lib.rs
  crates/re_log_types/src/arrow_msg.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_log_types/src/example_components.rs
  crates/re_log_types/src/lib.rs
  crates/re_log_types/src/time.rs
  crates/re_types_core/src/result.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#6409 Allow hiding top panel via blueprint
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/top_panel.rs
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
Labels: 🐍 Python API, ui, 🟦 blueprint, include in changelog

#6419 Allow overriding app blueprint from web
  Cargo.lock
  Cargo.toml
  crates/re_time_panel/src/lib.rs
  crates/re_types/src/blueprint/components/panel_state_ext.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/web.rs
  crates/rerun/src/run.rs
  rerun_js/web-viewer-react/index.js
  rerun_js/web-viewer/index.js
  rerun_js/web-viewer/package.json
  web_viewer/index.html
Labels: 🕸️ web, 🟦 blueprint, include in changelog

#6446 Fix Rust web clippy lints
  crates/re_viewer/src/web.rs
Labels: 🚜 refactor, exclude from changelog

#6432 `ViewerContext` test harness 0.1
  crates/re_data_ui/src/image.rs
  crates/re_selection_panel/src/lib.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/store_hub.rs
  crates/re_viewer_context/src/test_context.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/viewport.rs
Labels: 🔨 testing, 💬 discussion, exclude from changelog

#6444 Make re_edit_ui its own crate
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/lib.rs
  crates/re_edit_ui/Cargo.toml
  crates/re_edit_ui/README.md
  crates/re_edit_ui/src/corner2d.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/visible.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
Labels: 🚜 refactor, exclude from changelog

#6451 Fix broken example source links in Viewer example list
  crates/re_dev_tools/src/build_examples/example.rs
  crates/re_dev_tools/src/build_examples/manifest.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#6449 Fix error when logging segmentation image
  crates/re_data_ui/src/image.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_types/src/tensor_data.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
Labels: 🪳 bug, include in changelog

#6457 Changes from the 0.16.1 branch
  CHANGELOG.md
  RELEASES.md
Labels: ⛴ release, exclude from changelog

#6456 Don't log SDK client connected message until after we have confirmed it's a client
  crates/re_sdk_comms/src/server.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#6463 Minor fix - missing double quotes for choosing a video in detect object example
  examples/python/detect_and_track_objects/detect_and_track_objects.py
Labels: examples, exclude from changelog

#6468 Preserve component order in codegened component list
  crates/re_types/src/archetypes/arrows2d.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/boxes2d.rs
  crates/re_types/src/archetypes/boxes3d.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/mesh3d.rs
  crates/re_types/src/archetypes/pinhole.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_types/src/archetypes/series_line.rs
  crates/re_types/src/archetypes/series_point.rs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_types/src/blueprint/archetypes/scalar_axis.rs
  crates/re_types/src/blueprint/archetypes/space_view_blueprint.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer1.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer2.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer3.rs
  crates/re_types/src/testing/archetypes/affix_fuzzer4.rs
  crates/re_types_blueprint/src/blueprint/archetypes/container_blueprint.rs
  crates/re_types_blueprint/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_types_builder/src/codegen/rust/api.rs
Labels: codegen/idl, exclude from changelog

#6466 Update pixi.toml to use `rerun_py` package directly
  .github/workflows/auto_approve.yml
  .github/workflows/auto_release_crates.yml
  .github/workflows/checkboxes.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_pull_request_target_contrib.yml
  .github/workflows/on_push_docs.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_checks_python.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_publish_js.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_update_pr_body.yml
  examples/python/README.md
  examples/python/_empty_rerun_sdk/README.md
  examples/python/_empty_rerun_sdk/empty_rerun_sdk.py
  examples/python/_empty_rerun_sdk/pyproject.toml
  pixi.lock
  pixi.toml
  pixi/maturin_config.bat
  pixi/maturin_config.sh
Labels: 🐍 Python API, 🧑‍💻 dev experience, exclude from changelog

#6462 Improve visibility of Python public APIs to type checkers
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial2d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial3d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/time_series_view.py
  rerun_py/tests/unit/test_box2d.py
  rerun_py/tests/unit/test_box3d.py
  rerun_py/tests/unit/test_points2d.py
  rerun_py/tests/unit/test_points3d.py
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/crates.py
  scripts/ci/publish_wheels.py
Labels: 🐍 Python API, 🧑‍💻 dev experience, include in changelog

#6437 Client-side chunks 0: improved arrow chunk formatters
  Cargo.lock
  Cargo.toml
  crates/re_data_store/src/store_format.rs
  crates/re_format_arrow/Cargo.toml
  crates/re_format_arrow/src/lib.rs
  crates/re_log_types/src/arrow_msg.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/data_table.rs
Labels: 🏹 arrow, 🧑‍💻 dev experience, include in changelog

#6469 Fix cargo.lock merge race & pixi.lock in weird state
  Cargo.lock
  pixi.lock
Labels: exclude from changelog, :ship: CI

#6438 Client-side chunks 1: introduce `Chunk` and its suffle/sort routines
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_chunk/Cargo.toml
  crates/re_chunk/README.md
  crates/re_chunk/src/chunk.rs
  crates/re_chunk/src/lib.rs
  crates/re_chunk/src/shuffle.rs
  crates/re_chunk/src/util.rs
  crates/re_data_store/benches/arrow2.rs
  crates/re_types_core/src/size_bytes.rs
  examples/rust/objectron/src/objectron.rs
Labels: 🏹 arrow, ⛃ re_datastore, include in changelog, 🔩 data model, 🪵 Log-API

#6439 Client-side chunks 2: introduce `TransportChunk`
  crates/re_chunk/src/chunk.rs
  crates/re_chunk/src/lib.rs
  crates/re_chunk/src/shuffle.rs
  crates/re_chunk/src/transport.rs
  crates/re_log_types/src/example_components.rs
  crates/re_tuid/src/lib.rs
Labels: 🏹 arrow, ⛃ re_datastore, include in changelog, 🪵 Log-API

#6440 Client-side chunks 3: micro-batching
  crates/re_chunk/src/batcher.rs
  crates/re_chunk/src/chunk.rs
  crates/re_chunk/src/lib.rs
Labels: 📉 performance, include in changelog, 🔩 data model, 🪵 Log-API

#6441 Client-side chunks 4: integrations
  Cargo.lock
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/rerun/tests/rerun_tests.rs
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/error.hpp
  rerun_py/Cargo.toml
  rerun_py/src/arrow.rs
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, 🦀 Rust API, 🌊 C++ API, include in changelog

#6465 `ComponentFallbackProvider` and greatly simplified `edit_ui`
  Cargo.lock
  crates/re_edit_ui/src/corner2d.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/marker_shape.rs
  crates/re_edit_ui/src/response_utils.rs
  crates/re_edit_ui/src/visible.rs
  crates/re_selection_panel/src/override_ui.rs
  crates/re_space_view/src/view_property_ui.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_dataframe/src/visualizer_system.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/overrides.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/component_defaults/mod.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/component_fallbacks.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewer_context/src/space_view/visualizer_system.rs
  crates/re_viewer_context/src/test_context.rs
  crates/re_viewer_context/src/viewer_context.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: ui, 🚜 refactor, exclude from changelog

#6471 Remove unused scalar scattering component
  crates/re_edit_ui/src/lib.rs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/scalar_scattering.fbs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/mod.rs
  crates/re_viewer/src/component_defaults/mod.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/scalar_scattering.md
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/scalar_scattering.cpp
  rerun_cpp/src/rerun/components/scalar_scattering.hpp
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/scalar_scattering.py
  tests/python/release_checklist/check_all_components_ui.py
Labels: include in changelog, 🪵 Log-API

#6464 Update to latest egui `master`, with better tooltips
  Cargo.lock
  Cargo.toml
Labels: dependencies, include in changelog, egui

#6461 Add fullscreen mode to web viewer
  crates/re_types/src/blueprint/components/panel_state_ext.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer/src/web_tools.rs
  rerun_js/web-viewer/index.js
  rerun_js/yarn.lock
Labels: 🕸️ web, include in changelog
