Repository rerun-io/rerun, pull requests merged in 2024-12, with the labels that each got.

#8261 Use video logging api in `detect_and_track` example
  examples/python/detect_and_track_objects/README.md
  examples/python/detect_and_track_objects/detect_and_track_objects.py
Labels: enhancement, examples, 🍏 primitives, include in changelog

#8257 Suggestion for new project issue template
  .github/ISSUE_TEMPLATE/project.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#7546 Add Undo/Redo support in the viewer
  Cargo.lock
  Cargo.toml
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/lib.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer_context/src/command_sender.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/undo.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#8252 Run snapshot tests everywhere but render/compare only on mac
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_ui/tests/list_item_tests.rs
Labels: 🔨 testing, exclude from changelog

#8274 Fix: simplify viewport tree after dragging a tile
  Cargo.lock
  crates/viewer/re_viewport/Cargo.toml
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#8289 Update 2 icons from 1x to 2x
  crates/viewer/re_ui/data/icons/spaceview_generic.png
  crates/viewer/re_ui/data/icons/spaceview_unknown.png
Labels: ui, exclude from changelog

#8290 Enable `grpc` feature when compiling web viewer via pixi
  pixi.toml
Labels: 🧑‍💻 dev experience, 📺 re_viewer, exclude from changelog, :ship: CI, dataplatform

#8295 Fix web viewer feature flags
  crates/build/re_dev_tools/src/build_web_viewer/lib.rs
  crates/build/re_dev_tools/src/build_web_viewer/mod.rs
  crates/viewer/re_viewer/Cargo.toml
  pixi.toml
  rerun_js/web-viewer/build-wasm.mjs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#8256 Add support for Bezier-curve multi (self-)edges
  crates/viewer/re_space_view_graph/src/graph/ids.rs
  crates/viewer/re_space_view_graph/src/graph/mod.rs
  crates/viewer/re_space_view_graph/src/layout/geometry.rs
  crates/viewer/re_space_view_graph/src/layout/mod.rs
  crates/viewer/re_space_view_graph/src/layout/provider.rs
  crates/viewer/re_space_view_graph/src/layout/request.rs
  crates/viewer/re_space_view_graph/src/layout/result.rs
  crates/viewer/re_space_view_graph/src/layout/slots.rs
  crates/viewer/re_space_view_graph/src/ui/draw.rs
  crates/viewer/re_space_view_graph/src/ui/mod.rs
  crates/viewer/re_space_view_graph/src/ui/state.rs
  crates/viewer/re_space_view_graph/src/view.rs
  tests/python/release_checklist/check_graph_view.py
  tests/python/release_checklist/check_graph_view_multi_self_edges.py
Labels: ui, include in changelog

#8303 Refactor selection panel
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/lib.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_viewer_context/src/item.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 📺 re_viewer, 🚜 refactor, exclude from changelog

#8302 Improve the unknown view class text
  crates/viewer/re_viewer_context/src/space_view/space_view_class_placeholder.rs
Labels: ui, exclude from changelog

#8300 Update release docs
  .github/workflows/release.yml
  RELEASES.md
Labels: 📖 documentation, ⛴ release, exclude from changelog

#8305 improve view property ui methods
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/view_property_ui.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: ui, 🚜 refactor, exclude from changelog

#8315 Bump `hashbrown@0.15.0` to `0.15.1` to fix vuln
  Cargo.lock
Labels: exclude from changelog

#8313 Visually differentiate implicit nodes in graph view
  crates/viewer/re_space_view_graph/src/graph/mod.rs
  crates/viewer/re_space_view_graph/src/ui/draw.rs
Labels: 🪳 bug, ui, exclude from changelog

#8311 Add `re_data_ui` tooltip to graph view nodes
  Cargo.lock
  Cargo.toml
  crates/viewer/re_space_view_graph/Cargo.toml
  crates/viewer/re_space_view_graph/src/ui/draw.rs
  crates/viewer/re_space_view_graph/src/visualizers/edges.rs
Labels: ui, exclude from changelog

#8317 Fix outlines for lines having more preceived aliasing since 0.20
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/viewer/re_renderer/shader/depth_cloud.wgsl
  crates/viewer/re_renderer/shader/lines.wgsl
  crates/viewer/re_renderer/shader/point_cloud.wgsl
Labels: 🪳 bug, 🔺 re_renderer, 📺 re_viewer, 🦟 regression, include in changelog

#8296 Remove selection history
  Cargo.lock
  crates/viewer/re_selection_panel/src/lib.rs
  crates/viewer/re_selection_panel/src/selection_history_ui.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_history.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
Labels: 📺 re_viewer, include in changelog

#8288 Use `egui::Modal` to implement our modal dialogs
  crates/viewer/re_selection_panel/src/space_view_entity_picker.rs
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/modal.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_ui/tests/modal_tests.rs
  crates/viewer/re_ui/tests/snapshots/modal_list_item.png
  crates/viewer/re_ui/tests/snapshots/modal_normal.png
  crates/viewer/re_viewport_blueprint/src/ui/add_space_view_or_container_modal.rs
Labels: ui, 🚜 refactor, exclude from changelog

#8292 gRPC spec update: make metadata APIs more like the data API
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  examples/python/remote/metadata.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8260 Move `re_video` from `crates/store` to `crates/utils`
  Cargo.toml
  crates/utils/re_video/Cargo.toml
  crates/utils/re_video/README.md
  crates/utils/re_video/benches/video_load_bench.rs
  crates/utils/re_video/build.rs
  crates/utils/re_video/examples/frames.rs
  crates/utils/re_video/src/decode/async_decoder_wrapper.rs
  crates/utils/re_video/src/decode/av1.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/mod.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/nalu.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/sps.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/version.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/decode/webcodecs.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/utils/re_video/src/demux/mp4.rs
  crates/utils/re_video/src/lib.rs
  crates/utils/re_video/src/time.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#8321 ReDap Catalog as data source
  Cargo.lock
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/address.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/viewer/re_viewer/src/web_tools.rs
Labels: exclude from changelog

#8341 Fix handling unnormalized axis for (Pose)RotationAxisAngle
  crates/store/re_types/src/components/pose_rotation_axis_angle_ext.rs
  crates/store/re_types/src/components/rotation_axis_angle_ext.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#8322 Refactor design tokens to use a proper color table
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/data/design_tokens.json
  crates/viewer/re_ui/src/color_table.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/tests/snapshots/modal_list_item.png
Labels: ui, 🚜 refactor, exclude from changelog

#8339 Clean up `ForceLayoutProvider`
  crates/viewer/re_space_view_graph/src/layout/provider.rs
  crates/viewer/re_space_view_graph/src/layout/request.rs
  crates/viewer/re_space_view_graph/src/layout/result.rs
  crates/viewer/re_space_view_graph/src/ui/state.rs
Labels: ui, exclude from changelog, feat-graph-view

#8328 gRPC spec update: unify data and metadata API responses
  crates/store/re_protos/proto/rerun/v0/common.proto
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/codec.rs
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8306 Numpy 2.0 allowed in pyproject.toml
  pixi.lock
  rerun_py/pyproject.toml
Labels: dependencies, include in changelog

#8332 End-to-end tagging: basic helpers for Python & Rust
  crates/store/re_types_core/src/loggable_batch.rs
  docs/snippets/all/descriptors/descr_custom_archetype.py
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  docs/snippets/all/descriptors/descr_custom_component.py
  docs/snippets/all/descriptors/descr_custom_component.rs
  docs/snippets/all/tutorials/custom_data.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
Labels: enhancement, 🐍 Python API, 🦀 Rust API, exclude from changelog, 🪵 Log & send APIs

#8360 Fix link checker
  lychee.toml
Labels: exclude from changelog, :ship: CI

#8359 Update web embedding docs
  docs/content/howto/integrations/embed-web.md
Labels: 📖 documentation, exclude from changelog, deploy docs

#8358 Fix child-from-parent transforms
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, exclude from changelog

#8351 More compact selection panel when multiple items selected
  Cargo.lock
  crates/viewer/re_component_ui/src/datatype_uis/singleline_string.rs
  crates/viewer/re_component_ui/src/geo_line_string.rs
  crates/viewer/re_component_ui/src/line_strip.rs
  crates/viewer/re_context_menu/src/actions/add_entities_to_new_space_view.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_selection_panel/Cargo.toml
  crates/viewer/re_selection_panel/src/item_heading_no_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/lib.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/syntax_highlighting.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
Labels: ui, include in changelog

#8366 `cargo update -p url`
  Cargo.lock
  deny.toml
Labels: dependencies, exclude from changelog

#8365 Make `ArrowString` an opaque type
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_types/src/blueprint/datatypes/component_column_selector.rs
  crates/store/re_types/src/blueprint/datatypes/selected_columns.rs
  crates/store/re_types/src/datatypes/annotation_info.rs
  crates/store/re_types/src/datatypes/tensor_dimension.rs
  crates/store/re_types/src/datatypes/utf8pair.rs
  crates/store/re_types/src/testing/components/affix_fuzzer10.rs
  crates/store/re_types/src/testing/components/affix_fuzzer12.rs
  crates/store/re_types/src/testing/components/affix_fuzzer13.rs
  crates/store/re_types/src/testing/components/affix_fuzzer9.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer1.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer20.rs
  crates/store/re_types/src/testing/datatypes/string_component.rs
  crates/store/re_types_blueprint/src/blueprint/datatypes/utf8list.rs
  crates/store/re_types_core/src/arrow_string.rs
  crates/store/re_types_core/src/datatypes/entity_path.rs
  crates/store/re_types_core/src/datatypes/utf8.rs
  crates/store/re_types_core/src/datatypes/visible_time_range.rs
Labels: 🏹 arrow, 🚜 refactor, codegen/idl, exclude from changelog

#8331 Fix various doc links in SDKs
  Cargo.lock
  Cargo.toml
  crates/build/re_types_builder/Cargo.toml
  crates/build/re_types_builder/src/codegen/cpp/method.rs
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/docs/mod.rs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/python/views.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/util.rs
  crates/build/re_types_builder/src/docs.rs
  crates/build/re_types_builder/src/objects.rs
  crates/build/re_types_builder/src/report.rs
  crates/store/re_types/definitions/rerun/archetypes/graph_edges.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/background.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/container_blueprint.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/visualizer_overrides.fbs
  crates/store/re_types/definitions/rerun/components/fill_mode.fbs
  crates/store/re_types/definitions/rerun/datatypes/pixel_format.fbs
  crates/store/re_types/src/archetypes/graph_edges.rs
  crates/store/re_types/src/blueprint/archetypes/background.rs
  crates/store/re_types/src/components/fill_mode.rs
  crates/store/re_types/src/components/transform_relation.rs
  crates/store/re_types/src/datatypes/pixel_format.rs
  crates/store/re_types_blueprint/src/blueprint/archetypes/container_blueprint.rs
  crates/store/re_types_blueprint/src/blueprint/components/visualizer_overrides.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/components/fill_mode.md
  docs/content/reference/types/datatypes/pixel_format.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  rerun_cpp/src/rerun/archetypes/graph_edges.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/background.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components/visualizer_overrides.hpp
  rerun_cpp/src/rerun/components/fill_mode.hpp
  rerun_cpp/src/rerun/datatypes/pixel_format.hpp
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/background.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/container_blueprint.py
  rerun_py/rerun_sdk/rerun/components/fill_mode.py
  rerun_py/rerun_sdk/rerun/datatypes/pixel_format.py
Labels: 📖 documentation, 🧑‍💻 dev experience, codegen/idl, include in changelog

#8357 Make Position2D components editable in selection panel
  crates/viewer/re_component_ui/src/datatype_uis/mod.rs
  crates/viewer/re_component_ui/src/datatype_uis/vec.rs
  crates/viewer/re_component_ui/src/lib.rs
Labels: ui, include in changelog

#8370 Fix `re_types_builder` tests for doc generation
  crates/build/re_types_builder/src/docs.rs
Labels: exclude from changelog

#8348 Make the near clipping plane editable in 2D views
  crates/store/re_types/definitions/rerun/blueprint/archetypes/visual_bounds2d.fbs
  crates/store/re_types/definitions/rerun/blueprint/components.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/near_clip_plane.fbs
  crates/store/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/store/re_types/src/blueprint/components/.gitattributes
  crates/store/re_types/src/blueprint/components/mod.rs
  crates/store/re_types/src/blueprint/components/near_clip_plane.rs
  crates/store/re_types/src/blueprint/components/near_clip_plane_ext.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/migration/migration-0-21.md
  docs/content/reference/types/views/graph_view.md
  docs/content/reference/types/views/spatial2d_view.md
  rerun_cpp/src/rerun/blueprint/archetypes/visual_bounds2d.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/visual_bounds2d.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/near_clip_plane.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/visual_bounds2d.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/visual_bounds2d_ext.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/near_clip_plane.py
Labels: enhancement, 📺 re_viewer, include in changelog

#8372 Prepare to port codegen deserialization from arrow2
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
  crates/store/re_types/src/blueprint/datatypes/component_column_selector.rs
  crates/store/re_types/src/blueprint/datatypes/selected_columns.rs
  crates/store/re_types/src/components/annotation_context.rs
  crates/store/re_types/src/components/geo_line_string.rs
  crates/store/re_types/src/components/line_strip2d.rs
  crates/store/re_types/src/components/line_strip3d.rs
  crates/store/re_types/src/datatypes/annotation_info.rs
  crates/store/re_types/src/datatypes/blob.rs
  crates/store/re_types/src/datatypes/class_description.rs
  crates/store/re_types/src/datatypes/tensor_buffer.rs
  crates/store/re_types/src/datatypes/tensor_data.rs
  crates/store/re_types/src/datatypes/tensor_dimension.rs
  crates/store/re_types/src/datatypes/utf8pair.rs
  crates/store/re_types/src/testing/components/affix_fuzzer10.rs
  crates/store/re_types/src/testing/components/affix_fuzzer11.rs
  crates/store/re_types/src/testing/components/affix_fuzzer12.rs
  crates/store/re_types/src/testing/components/affix_fuzzer13.rs
  crates/store/re_types/src/testing/components/affix_fuzzer16.rs
  crates/store/re_types/src/testing/components/affix_fuzzer17.rs
  crates/store/re_types/src/testing/components/affix_fuzzer18.rs
  crates/store/re_types/src/testing/components/affix_fuzzer7.rs
  crates/store/re_types/src/testing/components/affix_fuzzer9.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer1.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer20.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer21.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer3.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer4.rs
  crates/store/re_types/src/testing/datatypes/string_component.rs
  crates/store/re_types/tests/types/validity.rs
  crates/store/re_types_blueprint/src/blueprint/datatypes/utf8list.rs
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/arrow_string.rs
  crates/store/re_types_core/src/datatypes/entity_path.rs
  crates/store/re_types_core/src/datatypes/time_range_boundary.rs
  crates/store/re_types_core/src/datatypes/utf8.rs
  crates/store/re_types_core/src/datatypes/visible_time_range.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/loggable.rs
  tests/python/release_checklist/main.py
Labels: 🚜 refactor, codegen/idl, exclude from changelog

#8374 Fix indicators showing up in override ui
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/store/re_types/src/archetypes/annotation_context.rs
  crates/store/re_types/src/archetypes/arrows2d.rs
  crates/store/re_types/src/archetypes/arrows3d.rs
  crates/store/re_types/src/archetypes/asset3d.rs
  crates/store/re_types/src/archetypes/asset_video.rs
  crates/store/re_types/src/archetypes/bar_chart.rs
  crates/store/re_types/src/archetypes/boxes2d.rs
  crates/store/re_types/src/archetypes/boxes3d.rs
  crates/store/re_types/src/archetypes/capsules3d.rs
  crates/store/re_types/src/archetypes/depth_image.rs
  crates/store/re_types/src/archetypes/disconnected_space.rs
  crates/store/re_types/src/archetypes/ellipsoids3d.rs
  crates/store/re_types/src/archetypes/encoded_image.rs
  crates/store/re_types/src/archetypes/geo_line_strings.rs
  crates/store/re_types/src/archetypes/geo_points.rs
  crates/store/re_types/src/archetypes/graph_edges.rs
  crates/store/re_types/src/archetypes/graph_nodes.rs
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/archetypes/instance_poses3d.rs
  crates/store/re_types/src/archetypes/line_strips2d.rs
  crates/store/re_types/src/archetypes/line_strips3d.rs
  crates/store/re_types/src/archetypes/mesh3d.rs
  crates/store/re_types/src/archetypes/pinhole.rs
  crates/store/re_types/src/archetypes/points2d.rs
  crates/store/re_types/src/archetypes/points3d.rs
  crates/store/re_types/src/archetypes/scalar.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/archetypes/series_line.rs
  crates/store/re_types/src/archetypes/series_point.rs
  crates/store/re_types/src/archetypes/tensor.rs
  crates/store/re_types/src/archetypes/text_document.rs
  crates/store/re_types/src/archetypes/text_log.rs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/store/re_types/src/archetypes/view_coordinates.rs
  crates/store/re_types/src/blueprint/archetypes/background.rs
  crates/store/re_types/src/blueprint/archetypes/dataframe_query.rs
  crates/store/re_types/src/blueprint/archetypes/line_grid3d.rs
  crates/store/re_types/src/blueprint/archetypes/map_background.rs
  crates/store/re_types/src/blueprint/archetypes/map_zoom.rs
  crates/store/re_types/src/blueprint/archetypes/plot_legend.rs
  crates/store/re_types/src/blueprint/archetypes/scalar_axis.rs
  crates/store/re_types/src/blueprint/archetypes/space_view_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/space_view_contents.rs
  crates/store/re_types/src/blueprint/archetypes/tensor_scalar_mapping.rs
  crates/store/re_types/src/blueprint/archetypes/tensor_slice_selection.rs
  crates/store/re_types/src/blueprint/archetypes/tensor_view_fit.rs
  crates/store/re_types/src/blueprint/archetypes/visible_time_ranges.rs
  crates/store/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/store/re_types/src/testing/archetypes/affix_fuzzer1.rs
  crates/store/re_types/src/testing/archetypes/affix_fuzzer2.rs
  crates/store/re_types/src/testing/archetypes/affix_fuzzer3.rs
  crates/store/re_types/src/testing/archetypes/affix_fuzzer4.rs
  crates/store/re_types_blueprint/src/blueprint/archetypes/container_blueprint.rs
  crates/store/re_types_blueprint/src/blueprint/archetypes/panel_blueprint.rs
  crates/store/re_types_blueprint/src/blueprint/archetypes/viewport_blueprint.rs
  crates/store/re_types_core/src/archetypes/clear.rs
Labels: 🦟 regression, codegen/idl, exclude from changelog

#8363 remove unused dependencies in re_log_types
  crates/store/re_log_types/Cargo.toml
Labels: dependencies, exclude from changelog

#8352 Add hloc_glomap example and update manifest
  examples/manifest.toml
  examples/python/hloc_glomap/README.md
Labels: examples, include in changelog

#8381 Untangle `re_protos` dependencies
  Cargo.lock
  crates/build/re_protos_builder/README.md
  crates/build/re_protos_builder/src/bin/build_re_remote_store_types.rs
  crates/build/re_protos_builder/src/lib.rs
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/src/codec/mod.rs
  crates/store/re_log_encoding/src/codec/wire.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/lib.rs
  crates/store/re_log_types/src/protobuf_conversions.rs
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/README.md
  crates/store/re_protos/proto/rerun/v0/common.proto
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v0/rerun.common.v0.rs
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  crates/utils/re_tuid/Cargo.toml
  crates/utils/re_tuid/src/lib.rs
  crates/utils/re_tuid/src/protobuf_conversions.rs
  pixi.toml
  rerun_py/Cargo.toml
  rerun_py/src/remote.rs
  scripts/lint.py
Labels: 🚜 refactor, exclude from changelog

#8384 Add link to nightly manifest in CI
  .github/workflows/reusable_upload_web.yml
Labels: exclude from changelog

#8392 Improved 'rrd print'
  crates/top/rerun/src/commands/rrd/print.rs
Labels: enhancement, 🧑‍💻 dev experience, include in changelog, CLI

#8393 Store: only run the debug assertion against recordings (not blueprints)
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, exclude from changelog

#8383 Snippet index: implement codegen foundations
  crates/build/re_types_builder/src/bin/build_re_types.rs
  crates/build/re_types_builder/src/codegen/docs/mod.rs
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  crates/build/re_types_builder/src/codegen/mod.rs
  crates/build/re_types_builder/src/lib.rs
  crates/build/re_types_builder/src/objects.rs
  docs/snippets/.gitattributes
  docs/snippets/INDEX.md
  scripts/ci/check_large_files.py
Labels: 📖 documentation, examples, include in changelog

#8385 Snippet index: support for manual opt-outs
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  docs/snippets/INDEX.md
  docs/snippets/snippets.toml
Labels: 📖 documentation, examples, exclude from changelog

#8391 Link to snippet index from main readme
  README.md
Labels: 📖 documentation, examples, exclude from changelog

#8401 Rust: more `impl<AsComponents>` helpers
  crates/store/re_types_core/src/lib.rs
  docs/snippets/all/archetypes/image_send_columns.rs
  docs/snippets/all/archetypes/mesh3d_partial_updates.rs
Labels: enhancement, 🦀 Rust API, 🧑‍💻 dev experience, include in changelog

#8406 Document legend interaction in the timeseries view help text
  crates/viewer/re_view_time_series/src/view_class.rs
Labels: enhancement, ui, include in changelog

#8371 Add missing screenshots of graph view archetypes
  crates/store/re_types/definitions/rerun/archetypes/graph_edges.fbs
  crates/store/re_types/definitions/rerun/archetypes/graph_nodes.fbs
  crates/viewer/re_view_graph/src/properties.rs
  crates/viewer/re_view_graph/src/ui/state.rs
  crates/viewer/re_view_graph/src/view.rs
  docs/content/reference/types/archetypes/graph_edges.md
  docs/content/reference/types/archetypes/graph_nodes.md
  examples/rust/chess_robby_fischer/README.md
  examples/rust/graph_lattice/README.md
  rerun_cpp/src/rerun/blueprint.hpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/tests/unit/test_container_blueprint.py
  rerun_py/tests/unit/test_view_contents.py
Labels: exclude from changelog

#8379 Improve Bezier edge-drawing
  crates/viewer/re_view_graph/src/layout/provider.rs
Labels: exclude from changelog

#8390 Simplify zoom-and-pan area
  crates/store/re_chunk_store/src/writes.rs
  crates/viewer/re_ui/src/zoom_pan_area.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 🪳 bug, ui, exclude from changelog, egui, feat-graph-view

#8387 Don't show transform arrows on all entities without any other visualizer
  crates/viewer/re_view_spatial/src/view_3d.rs
  docs/content/reference/migration/migration-0-21.md
Labels: 📺 re_viewer, 🟦 blueprint, include in changelog, heuristics

#8409 Enforce blueprint data is always untagged during the interim
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, ⛃ re_datastore, 🦟 regression, 🟦 blueprint, exclude from changelog, 🔩 data model

#8400 New `PerStoreStoreSubscriber` wrapper to remove store tracking boilerplate
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/subscribers.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/src/recursive_chunks_per_timeline_subscriber.rs
  crates/viewer/re_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/transform_component_tracker.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
Labels: 🚜 refactor, exclude from changelog

#8394 Fix node selection not working on graph node text labels
  crates/viewer/re_view_graph/src/ui/draw.rs
Labels: exclude from changelog

#8410 Bump `fjadra` to `v0.2.1`
  Cargo.lock
  Cargo.toml
Labels: exclude from changelog

#8416 Partial revert #8390: removal of `Area` in `zoom_pan_area`
  crates/viewer/re_ui/src/zoom_pan_area.rs
Labels: exclude from changelog

#8334 Allow drag-and-dropping multiple containers and views in the blueprint tree
  Cargo.lock
  Cargo.toml
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_ui/data/icons/dnd_add_new.png
  crates/viewer/re_ui/data/icons/dnd_add_to_existing.png
  crates/viewer/re_ui/data/icons/dnd_move.png
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer_context/src/contents.rs
  crates/viewer/re_viewer_context/src/drag_and_drop.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/view_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  crates/viewer/re_viewport_blueprint/src/viewport_command.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
Labels: enhancement, ui, include in changelog

#8404 Improve picking in 2D views
  crates/viewer/re_view_spatial/src/picking_ui.rs
Labels: ui, 📺 re_viewer, include in changelog

#8424 Do query for default components only once per view
  crates/store/re_query/src/latest_at.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/query_context.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/view_context.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
Labels: 📺 re_viewer, 🚀 performance, include in changelog

#8420 `re_viewer::reflection` -> `re_types::reflection`
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_types/src/lib.rs
  crates/store/re_types/src/reflection/.gitattributes
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  scripts/ci/check_large_files.py
Labels: do-not-merge, 🚜 refactor, 🍏 primitives, include in changelog

#8427 Fix nightly execution
  .github/workflows/nightly.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#8405 Improve hovered order in 2D views
  crates/viewer/re_view_spatial/src/picking.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
Labels: 📺 re_viewer, include in changelog

#8408 Make our collapsing triangle thinner for more consistency with our icons
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_ui/src/ui_ext.rs
Labels: ui, include in changelog

#8418 Enrich ReDap Catalog with RecordingUri on the fly
  Cargo.lock
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
Labels: exclude from changelog, remote-store

#8421 Create a more convincing example of the graph view
  Cargo.lock
  crates/viewer/re_view_graph/src/layout/provider.rs
  crates/viewer/re_view_graph/src/view.rs
  examples/manifest.toml
  examples/python/graph_binary_tree/README.md
  examples/python/graph_binary_tree/graph_binary_tree.py
  examples/python/graph_lattice/README.md
  examples/python/graphs/README.md
  examples/python/graphs/graphs.py
  examples/python/graphs/pyproject.toml
  examples/rust/graph_binary_tree/Cargo.toml
  examples/rust/graph_binary_tree/README.md
  examples/rust/graph_binary_tree/src/main.rs
  pixi.lock
  pixi.toml
  tests/python/release_checklist/check_graph_time_layout.py
Labels: ui, examples, include in changelog

#8347 Encode `LogMsg` using protobuf
  Cargo.lock
  Cargo.toml
  crates/build/re_protos_builder/Cargo.toml
  crates/build/re_protos_builder/src/bin/build_re_remote_store_types.rs
  crates/build/re_protos_builder/src/lib.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_data_loader/src/loader_external.rs
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_data_source/src/load_stdin.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/examples/query.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_entity_db/src/store_bundle.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/store/re_log_encoding/src/codec/arrow.rs
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/codec/file/encoder.rs
  crates/store/re_log_encoding/src/codec/file/mod.rs
  crates/store/re_log_encoding/src/codec/mod.rs
  crates/store/re_log_encoding/src/codec/wire.rs
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_encoding/src/file_sink.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/store/re_log_encoding/src/protobuf_conversions.rs
  crates/store/re_log_encoding/src/stream_rrd_from_http.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_log_types/src/protobuf_conversions.rs
  crates/store/re_protos/.gitattributes
  crates/store/re_protos/proto/rerun/v0/log_msg.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v0/rerun.common.v0.rs
  crates/store/re_protos/src/v0/rerun.log_msg.v0.rs
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  crates/store/re_sdk_comms/src/buffered_client.rs
  crates/store/re_sdk_comms/src/server.rs
  crates/top/re_sdk/src/binary_stream_sink.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/top/rerun/src/commands/stdio.rs
  crates/top/rerun/src/lib.rs
  crates/utils/re_tuid/src/protobuf_conversions.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/loading.rs
  crates/viewer/re_viewer/src/saving.rs
  rerun_py/src/dataframe.rs
Labels: include in changelog, 🪵 Log & send APIs, dataplatform

#8434 Update test snapshots invalidated by #8408
  crates/viewer/re_time_panel/tests/snapshots/time_panel_dense_data.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections.png
Labels: 🪳 bug, exclude from changelog, :ship: CI

#8430 Fix links to blueprint components/archetype that don't show up in our reference yet
  crates/build/re_types_builder/src/docs.rs
  crates/store/re_types/src/reflection/mod.rs
Labels: 📖 documentation, 🦟 regression, exclude from changelog

#8426 Fix broken notebook loading on firefox by compressing the encoded wasm payload
  rerun_js/web-viewer/bundle.mjs
Labels: 🐍 Python API, 🦟 regression, notebook, include in changelog

#8432 Improved reflection
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/store/re_types_core/src/reflection.rs
Labels: enhancement, codegen/idl, include in changelog

#8439 Migration kernel for the blueprint space-view-related breaking changes
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/migration.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: enhancement, 🧑‍💻 dev experience, ⛴ release, 🟦 blueprint, include in changelog

#8444 Improved assertion for wrongully tagged chunks
  crates/store/re_chunk_store/src/writes.rs
Labels: enhancement, 🧑‍💻 dev experience, ⛃ re_datastore, exclude from changelog

#8445 Fix another snapshot image
  crates/viewer/re_ui/tests/snapshots/list_items.png
Labels: 🪳 bug, exclude from changelog, :ship: CI

#8446 Enable remote feature in all pypi builds
  rerun_py/Cargo.toml
  scripts/ci/build_and_upload_wheels.py
Labels: 🐍 Python API, ⛴ release, exclude from changelog

#8438 Improve `VisualBounds2D` behavior in graph view
  crates/viewer/re_ui/src/zoom_pan_area.rs
  crates/viewer/re_view_graph/src/ui/state.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: exclude from changelog

#8436 Improve graph view documentation
  crates/viewer/re_view_graph/src/properties.rs
  examples/manifest.toml
  examples/python/graph_lattice/README.md
  examples/python/graphs/README.md
  examples/rust/graph_lattice/README.md
Labels: exclude from changelog

#8460 Fix some assorted lints
  examples/python/arkit_scenes/arkit_scenes/download_dataset.py
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
Labels: 🐍 Python API, exclude from changelog

#8469 Update to latest egui
  Cargo.lock
  Cargo.toml
  crates/viewer/re_viewer/Cargo.toml
Labels: 📺 re_viewer, dependencies, exclude from changelog, egui

#8458 Add utility to `rr.components.Color` to generate colors from any string (and use it in the air traffic data example)
  examples/python/air_traffic_data/air_traffic_data.py
  rerun_py/rerun_sdk/rerun/components/color.py
  rerun_py/rerun_sdk/rerun/components/color_ext.py
Labels: enhancement, 🐍 Python API, include in changelog

#8468 Attempt to fix `StorageNodeClient.query_catalog(…)` signature mismatch
  rerun_py/src/remote.rs
Labels: exclude from changelog

#8457 Fix broken interaction outside of graph views
  crates/viewer/re_ui/src/zoom_pan_area.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: 🪳 bug, exclude from changelog, egui, feat-graph-view

#8449 craft blueprint for Catalog view from raw chunks
  crates/store/re_grpc_client/src/lib.rs
Labels: exclude from changelog, remote-store

#8450 Implement level-of-detail on text labels
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/ui/mod.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: exclude from changelog

#8473 Fix `re_renderer`'s wgpu error scopes not handling internal errors
  crates/viewer/re_renderer/src/error_handling/wgpu_error_scope.rs
Labels: 🔺 re_renderer, exclude from changelog

#8474 Fix single-click and double-click in the graph view
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: exclude from changelog

#8464 Remove wait-time when opening settings panel
  Cargo.lock
  crates/utils/re_video/Cargo.toml
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/version.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
Labels: 📺 re_viewer, 🚀 performance, include in changelog, 🎞️ video

#8480 Update to re_arrow2 0.18
  Cargo.lock
  Cargo.toml
Labels: 🏹 arrow, dependencies, exclude from changelog

#8482 Fix double click no longer selecting the entire entity in 2d/3d views
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🪳 bug, 🦟 regression, exclude from changelog

#8483 Update thumbnail for air traffic example
  examples/python/air_traffic_data/README.md
Labels: examples, exclude from changelog

#8461 Introduce new API to send a dataframe to Rerun
  crates/store/re_chunk_store/src/dataframe.rs
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/rerun_sdk/rerun/dataframe.py
  rerun_py/tests/unit/test_dataframe.py
Labels: 🐍 Python API, include in changelog

#8369 Fix 2D/3D view artifacts on view's border when using fractional zoom
  crates/viewer/re_renderer/shader/composite.wgsl
  crates/viewer/re_renderer/shader/copy_texture.wgsl
  crates/viewer/re_renderer/shader/debug_overlay.wgsl
  crates/viewer/re_renderer/shader/global_bindings.wgsl
  crates/viewer/re_renderer/shader/instanced_mesh.wgsl
  crates/viewer/re_renderer/shader/outlines/jumpflooding_init.wgsl
  crates/viewer/re_renderer/shader/outlines/jumpflooding_init_msaa.wgsl
  crates/viewer/re_renderer/src/global_bindings.rs
Labels: 🪳 bug, 🔺 re_renderer, 📺 re_viewer, include in changelog

#8493 Fix context menu release checklist formatting and casing of the `Hide/Show all` item
  crates/viewer/re_context_menu/src/actions/show_hide.rs
  tests/python/release_checklist/check_context_menu_multi_selection.py
  tests/python/release_checklist/check_context_menu_single_selection.py
  tests/python/release_checklist/check_context_menu_single_selection_blueprint_tree.py
Labels: 🔨 testing, ui, exclude from changelog

#8495 Add missing click and hover interactions for views
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_text_document/src/view_class.rs
  tests/python/release_checklist/check_hover_select_reset.py
Labels: exclude from changelog

#8472 Implement save-view-as-screenshot on web
  Cargo.lock
  Cargo.toml
  crates/viewer/re_context_menu/src/actions/mod.rs
  crates/viewer/re_context_menu/src/actions/screenshot_action.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 🕸️ web, 📺 re_viewer, exclude from changelog, egui

#8496 Remove debug information from graph view selection panel
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/ui/mod.rs
  crates/viewer/re_view_graph/src/ui/state.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: exclude from changelog

#8476 Improve graphics device capability detection, warn on old devices, early error on unsupported render targets
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/draw_phases/outlines.rs
  crates/viewer/re_renderer/src/draw_phases/picking_layer.rs
  crates/viewer/re_renderer/src/renderer/compositor.rs
  crates/viewer/re_renderer/src/renderer/debug_overlay.rs
  crates/viewer/re_renderer/src/renderer/depth_cloud.rs
  crates/viewer/re_renderer/src/renderer/lines.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_renderer/src/renderer/point_cloud.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_renderer/src/view_builder.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
Labels: 🔺 re_renderer, 📺 re_viewer, include in changelog

#8499 Disable tagging entirely for 0.21
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_types_core/src/component_descriptor.rs
  docs/snippets/all/descriptors/descr_builtin_archetype.rs
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  docs/snippets/all/descriptors/descr_custom_component.rs
  rerun_py/tests/unit/test_dataframe.py
Labels: ⛃ re_datastore, exclude from changelog, 🪵 Log & send APIs

#8431 Entities can be dragged from the blueprint tree and streams tree to an existing view in the viewport
  Cargo.lock
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/contents.rs
  crates/viewer/re_viewer_context/src/drag_and_drop.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/entity_add_info.rs
  crates/viewer/re_viewport_blueprint/src/lib.rs
  tests/python/release_checklist/check_drag_and_drop_selection.py
  tests/python/release_checklist/check_entity_drag_and_drop.py
Labels: enhancement, ui, include in changelog

#8492 Add better support for scrolling content to our modals
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_ui/src/modal.rs
  crates/viewer/re_viewport_blueprint/src/ui/add_view_or_container_modal.rs
  tests/python/release_checklist/check_modal_scrolling.py
Labels: 🪳 bug, ui, exclude from changelog

#8501 Improve the tooltip of the `Force*` graph view properties
  crates/store/re_types/definitions/rerun/blueprint/archetypes/force_center.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/force_collision_radius.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/force_link.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/force_many_body.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/force_position.fbs
  crates/store/re_types/src/blueprint/archetypes/force_center.rs
  crates/store/re_types/src/blueprint/archetypes/force_collision_radius.rs
  crates/store/re_types/src/blueprint/archetypes/force_link.rs
  crates/store/re_types/src/blueprint/archetypes/force_many_body.rs
  crates/store/re_types/src/blueprint/archetypes/force_position.rs
  crates/store/re_types/src/reflection/mod.rs
  docs/content/reference/types/views/graph_view.md
  rerun_cpp/src/rerun/blueprint/archetypes/force_center.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/force_collision_radius.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/force_link.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/force_many_body.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/force_position.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/force_center.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/force_collision_radius.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/force_link.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/force_many_body.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/force_position.py
Labels: ui, exclude from changelog, feat-graph-view

#8502 Fix ui radius crashing graph view
  crates/viewer/re_view_graph/src/visualizers/nodes.rs
Labels: 📺 re_viewer, 💣 crash, exclude from changelog, feat-graph-view

#8506 Update egui to the commit before 0.30.0
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#8508 Fix graph node hover
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#8507 Hide outline rectangle around views
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: ui, exclude from changelog, 🧑‍🎨 Design

#8513 Fix the event count in the static-over-temporal error message
  crates/store/re_chunk_store/src/stats.rs
  crates/viewer/re_data_ui/src/component.rs
Labels: ui, 🦟 regression, exclude from changelog

#8509 Fix Plane3D component ui when it's non-editable
  crates/viewer/re_component_ui/src/plane3d.rs
Labels: 🪳 bug, ui, exclude from changelog

#8515 Fix missing `ComponentBatchCow` export in public lib
  crates/top/re_sdk/src/lib.rs
Labels: 🪳 bug, 🦀 Rust API, 🧑‍💻 dev experience, 😤 annoying

#8516 egui 0.30
  Cargo.lock
  Cargo.toml
  crates/viewer/re_component_ui/src/marker_shape.rs
Labels: ⛴ release, dependencies, include in changelog

#8512 Fix graph view node highlight on hover
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/view.rs
Labels: exclude from changelog

#8520 Make all checklists force activate their blueprints
  tests/python/release_checklist/README.md
  tests/python/release_checklist/check_1d_tensor_data.py
  tests/python/release_checklist/check_all_components_ui.py
  tests/python/release_checklist/check_annotations.py
  tests/python/release_checklist/check_bgr.py
  tests/python/release_checklist/check_blueprint_bw_compat.py
  tests/python/release_checklist/check_blueprint_overrides.py
  tests/python/release_checklist/check_chroma_subsampling.py
  tests/python/release_checklist/check_colormap_edit_ui.py
  tests/python/release_checklist/check_component_and_transform_clamping.py
  tests/python/release_checklist/check_container_hierarchy.py
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
  tests/python/release_checklist/check_context_menu_collapse_expand_all.py
  tests/python/release_checklist/check_context_menu_invalid_sub_container.py
  tests/python/release_checklist/check_context_menu_multi_selection.py
  tests/python/release_checklist/check_context_menu_single_selection.py
  tests/python/release_checklist/check_context_menu_single_selection_blueprint_tree.py
  tests/python/release_checklist/check_context_menu_suggested_origin.py
  tests/python/release_checklist/check_deselect_on_escape.py
  tests/python/release_checklist/check_drag_and_drop_selection.py
  tests/python/release_checklist/check_draw_order.py
  tests/python/release_checklist/check_entity_drag_and_drop.py
  tests/python/release_checklist/check_focus.py
  tests/python/release_checklist/check_graph_view.py
  tests/python/release_checklist/check_graph_view_multi_self_edges.py
  tests/python/release_checklist/check_heuristics_2d.py
  tests/python/release_checklist/check_heuristics_mixed_2d_and_3d.py
  tests/python/release_checklist/check_heuristics_mixed_all_root.py
  tests/python/release_checklist/check_hover_select_reset.py
  tests/python/release_checklist/check_latest_at_partial_updates.py
  tests/python/release_checklist/check_modal_scrolling.py
  tests/python/release_checklist/check_mono_entity_views.py
  tests/python/release_checklist/check_notebook.py
  tests/python/release_checklist/check_out_of_tree_data_results.py
  tests/python/release_checklist/check_overrides_2d.py
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/release_checklist/check_plot_overrides.py
  tests/python/release_checklist/check_range_partial_updates.py
  tests/python/release_checklist/check_rbl_import.py
  tests/python/release_checklist/check_scalar_clears.py
  tests/python/release_checklist/check_static_components_ui.py
  tests/python/release_checklist/check_static_override.py
  tests/python/release_checklist/check_transform3d_hierarchy.py
  tests/python/release_checklist/check_version.py
  tests/python/release_checklist/check_video.py
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#8504 Catalog view: fetch StoreInfo from the catalog and do catalog data enrichment on the viewer side
  crates/store/re_grpc_client/src/lib.rs
Labels: exclude from changelog, dataplatform

#8521 Update the remote APIs to take and send a Table
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  examples/python/remote/metadata.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_bindings/types.py
  rerun_py/src/remote.rs
Labels: exclude from changelog, dataplatform

#8511 Hide graph edges from individual graph node ui
  crates/viewer/re_data_ui/src/instance_path.rs
Labels: ui, exclude from changelog

#8519 Fix multi-entity drag-and-drop only adding one entity
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  tests/python/release_checklist/check_multi_entity_drag_and_drop.py
Labels: 🪳 bug, ui, exclude from changelog

#8523 Fix cargo warning
  crates/utils/re_capabilities/Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#8526 Fix undo not working in some entity drag-and-drop instances
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: 🪳 bug, ui, exclude from changelog

#8527 Use single log call in graph examples
  crates/store/re_types/definitions/rerun/archetypes/graph_edges.fbs
  crates/store/re_types/definitions/rerun/archetypes/graph_nodes.fbs
  crates/store/re_types/src/archetypes/graph_edges.rs
  crates/store/re_types/src/archetypes/graph_nodes.rs
  docs/snippets/all/archetypes/graph_directed.cpp
  docs/snippets/all/archetypes/graph_directed.py
  docs/snippets/all/archetypes/graph_directed.rs
  docs/snippets/all/archetypes/graph_undirected.cpp
  docs/snippets/all/archetypes/graph_undirected.py
  docs/snippets/all/archetypes/graph_undirected.rs
  rerun_cpp/src/rerun/archetypes/graph_edges.hpp
  rerun_cpp/src/rerun/archetypes/graph_nodes.hpp
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
Labels: 📖 documentation, exclude from changelog

#8528 Add docstring about need for `include_indicator_columns=True`
  rerun_py/rerun_sdk/rerun/dataframe.py
Labels: 📖 documentation, exclude from changelog

#8524 Enable GH releases for RC
  .github/workflows/release.yml
Labels: 💬 discussion, exclude from changelog, :ship: CI

#8376 Tensor shape and dimension names as separate arrow fields
  crates/store/re_chunk/src/iter.rs
  crates/store/re_types/definitions/rerun/datatypes.fbs
  crates/store/re_types/definitions/rerun/datatypes/tensor_data.fbs
  crates/store/re_types/definitions/rerun/datatypes/tensor_dimension.fbs
  crates/store/re_types/src/archetypes/depth_image_ext.rs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/archetypes/segmentation_image_ext.rs
  crates/store/re_types/src/archetypes/tensor_ext.rs
  crates/store/re_types/src/datatypes/.gitattributes
  crates/store/re_types/src/datatypes/mod.rs
  crates/store/re_types/src/datatypes/tensor_data.rs
  crates/store/re_types/src/datatypes/tensor_data_ext.rs
  crates/store/re_types/src/datatypes/tensor_dimension.rs
  crates/store/re_types/src/datatypes/tensor_dimension_ext.rs
  crates/store/re_types/src/image.rs
  crates/store/re_types/tests/types/tensor.rs
  crates/store/re_types_core/src/arrow_buffer.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/top/rerun/src/lib.rs
  crates/top/rerun/src/sdk.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_view_tensor/src/dimension_mapping.rs
  crates/viewer/re_view_tensor/src/lib.rs
  crates/viewer/re_view_tensor/src/tensor_dimension_mapper.rs
  crates/viewer/re_view_tensor/src/tensor_tests.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  docs/content/reference/migration/migration-0-21.md
  docs/content/reference/types/components/tensor_data.md
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/.gitattributes
  docs/content/reference/types/datatypes/tensor_data.md
  docs/content/reference/types/datatypes/tensor_dimension.md
  docs/snippets/README.md
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/tensor.hpp
  rerun_cpp/src/rerun/archetypes/tensor_ext.cpp
  rerun_cpp/src/rerun/components/tensor_data.hpp
  rerun_cpp/src/rerun/components/tensor_data_ext.cpp
  rerun_cpp/src/rerun/datatypes.hpp
  rerun_cpp/src/rerun/datatypes/.gitattributes
  rerun_cpp/src/rerun/datatypes/tensor_data.cpp
  rerun_cpp/src/rerun/datatypes/tensor_data.hpp
  rerun_cpp/src/rerun/datatypes/tensor_data_ext.cpp
  rerun_cpp/src/rerun/datatypes/tensor_dimension.cpp
  rerun_cpp/src/rerun/datatypes/tensor_dimension.hpp
  rerun_cpp/src/rerun/datatypes/tensor_dimension_ext.cpp
  rerun_py/README.md
  rerun_py/rerun_sdk/rerun/_validators.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/.gitattributes
  rerun_py/rerun_sdk/rerun/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_dimension.py
  rerun_py/tests/unit/test_tensor.py
  tests/cpp/roundtrips/tensor/main.cpp
  tests/python/release_checklist/check_all_components_ui.py
Labels: codegen/idl, exclude from changelog, include in changelog, 🪵 Log & send APIs

#8485 Add `grtlr` to list of `OFFICIAL_RERUN_DEVS`
  scripts/generate_changelog.py
Labels: exclude from changelog

#8532 Fix: `./scripts/lint.py` ignored all under `crates/build`
  .gitignore
  crates/build/re_protos_builder/src/lib.rs
  crates/build/re_types_builder/src/codegen/rust/arrow.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#8533 Add graph view example video (with subtitles) to `CHANGELOG`
  CHANGELOG.md
Labels: exclude from changelog

#8540 Find and annihilate slow component iterators
  crates/store/re_chunk/src/iter.rs
  crates/store/re_types/src/components/colormap_ext.rs
  crates/store/re_types/src/components/fill_mode_ext.rs
  crates/store/re_types/src/components/mod.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_graph/src/visualizers/edges.rs
  crates/viewer/re_view_graph/src/visualizers/nodes.rs
  crates/viewer/re_view_map/src/visualizers/geo_line_strings.rs
  crates/viewer/re_view_map/src/visualizers/geo_points.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_view_text_log/src/visualizer_system.rs
Labels: enhancement, 🏹 arrow, 📺 re_viewer, 🚀 performance, 🍏 primitives, exclude from changelog

#8541 Find and annihilate slow boolean-component iterators
  crates/store/re_chunk/src/iter.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
Labels: enhancement, 🏹 arrow, 📺 re_viewer, 🚀 performance, do-not-merge, 🍏 primitives

#8550 grpc codec simplification - get rid of NoData message
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8542 Show the `GraphNode` as a label by default
  crates/viewer/re_view_graph/src/visualizers/nodes.rs
Labels: ui, include in changelog

#8548 Remove `Chunk::iter_component_arrays`
  crates/store/re_chunk/src/iter.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
Labels: enhancement, 🏹 arrow, 🚜 refactor, include in changelog

#8552 remove screenshot tests for disconnected space component ui
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/DisconnectedSpace_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/DisconnectedSpace_placeholder.png
Labels: 🪳 bug, 🔨 testing, exclude from changelog
