Repository rerun-io/rerun, pull requests merged in 2024-04, with the labels that each got.

#5735 Fix typos from new version of `typos`
  .typos.toml
  CONTRIBUTING.md
  crates/re_renderer/shader/outlines/jumpflooding_init_shared.wgsl
  crates/re_types/src/components/view_coordinates_ext.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_viewer/src/screenshotter.rs
  rerun_cpp/download_and_build_arrow.cmake
Labels: 🧑‍💻 dev experience, exclude from changelog

#5741 Fix appearance of `ListItem` in a tooltip
  crates/re_data_ui/src/data_source.rs
Labels: 🪳 bug, ui, exclude from changelog

#5737 Fix crash/freeze when zooming out too far in a plot
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: 📺 re_viewer, 💣 crash, include in changelog

#5738 Update web viewer links
  .github/pull_request_template.md
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  crates/re_viewer/src/app.rs
  docs/README.md
  docs/content/getting-started/troubleshooting.md
  docs/content/getting-started/what-is-rerun.md
  examples/manifest.toml
  examples/python/notebook/cube.ipynb
  rerun_py/src/python_bridge.rs
  scripts/ci/generate_pr_summary.py
  scripts/screenshot_compare/build_screenshot_compare.py
Labels: 📖 documentation, 🕸️ web, include in changelog

#5745 Fix PR template links
  .github/pull_request_template.md
Labels: 📖 documentation, exclude from changelog

#5744 Fix orphaned space views by constructing from tree rather than redundant component
  crates/re_types/definitions/rerun/blueprint/archetypes/viewport_blueprint.fbs
  crates/re_viewport/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint.rs
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.hpp
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/viewport_blueprint.py
  rerun_py/tests/unit/test_viewport_blueprint.py
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog

#5748 Update to egui 0.27.2
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#5747 Add feedback when no match exist under space origin
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, exclude from changelog

#5739 Make selection history global instead of per recordings
  crates/re_data_ui/src/item_ui.rs
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/store_hub.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: ui, include in changelog

#5641 Update docs with guides and tutorials for blueprint
  .github/workflows/documentation.yaml
  docs/content/getting-started/visualize/blueprint.md
  docs/content/howto/configure-the-viewer.md
  docs/content/howto/configure-the-viewer/blueprint-api-tutorial.md
  docs/content/howto/configure-the-viewer/interactively.md
  docs/content/howto/configure-the-viewer/save-and-load.md
  docs/content/howto/configure-the-viewer/through-code.md
  docs/content/reference/entity-queries.md
  docs/content/reference/types.md
  docs/content/reference/viewer.md
  docs/cspell.json
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
Labels: 📖 documentation, 🟦 blueprint, include in changelog

#5750 Go back to example page with browser Back-button
  Cargo.lock
  crates/re_data_source/src/web_sockets.rs
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_smart_channel/src/receive_set.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer/src/web_tools.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/store_hub.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#5746 Improve `re_format` formatting of floats
  Cargo.lock
  crates/re_data_store/src/store_format.rs
  crates/re_data_store/src/store_gc.rs
  crates/re_data_store/src/store_sanity.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/data.rs
  crates/re_format/Cargo.toml
  crates/re_format/src/lib.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: exclude from changelog

#5753 Improve formatting of numbers on plot Y axis
  crates/re_log_types/src/time_point/mod.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/paint_ticks.rs
Labels: ui, include in changelog

#5756 Make Welcome screen work without internet too
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
  docs/content/getting-started/what-is-rerun.md
Labels: 🪳 bug, ui, examples, exclude from changelog

#5758 Fix clicking example source code links in example cards
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
Labels: 🪳 bug, ui, examples, exclude from changelog

#5763 Add support for directly copying the HTML tag created by `upload_image.py`
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#5760 Use new blueprint id on each sent blueprint
  rerun_py/rerun_sdk/rerun/blueprint/api.py
Labels: 🐍 Python API, 🟦 blueprint, exclude from changelog

#5711 Update README and description of `arkit_scenes` example
  docs/cspell.json
  examples/python/arkit_scenes/README.md
  scripts/lint.py
Labels: 📖 documentation, include in changelog

#5771 Add blueprint concept doc
  docs/content/concepts/blueprint.md
Labels: 📖 documentation, 🟦 blueprint, exclude from changelog

#5770 Cleanup blueprint doc and quick pass on transforms
  docs/content/concepts/spaces-and-transforms.md
  docs/content/howto/configure-viewer-through-code.md
Labels: 📖 documentation, exclude from changelog

#5773 Use space view icons in the "Add to new space view" menu
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewport/src/context_menu/actions/add_entities_to_new_space_view.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: ui, exclude from changelog

#5768 Update the "Configure the viewer interactively" section
  docs/content/getting-started/configure-the-viewer/interactively.md
Labels: 📖 documentation, exclude from changelog

#5754 re_format: add general `format_int` function
  crates/re_format/src/lib.rs
  crates/re_log_types/src/time_point/mod.rs
  crates/re_time_panel/src/paint_ticks.rs
Labels: 🚜 refactor, exclude from changelog

#5767 Example page: make sure title and file size don't overlap
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
Labels: 🪳 bug, ui, exclude from changelog

#5593 Improve readme of `depth_guided_stable_diffusion` example
  docs/cspell.json
  examples/python/depth_guided_stable_diffusion/README.md
  scripts/lint.py
Labels: 📖 documentation, include in changelog

#5546 Add example visualizing KISS-ICP
  docs/cspell.json
  examples/cpp/kiss-icp/README.md
  examples/manifest.toml
  examples/python/kiss-icp/README.md
Labels: examples, include in changelog

#5775 Update h2 to 0.3.26 to address RUSTSEC-2024-0332
  Cargo.lock
Labels: dependencies, include in changelog

#5762 Reorganize getting-started and blueprint tutorials
  docs/content/concepts/blueprint.md
  docs/content/concepts/spaces-and-transforms.md
  docs/content/getting-started/configure-the-viewer.md
  docs/content/getting-started/configure-the-viewer/interactively.md
  docs/content/getting-started/configure-the-viewer/navigating-the-viewer-continued.md
  docs/content/getting-started/configure-the-viewer/save-and-load.md
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/getting-started/data-in.md
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/open-any-file.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-in/rust.md
  docs/content/getting-started/data-in/streaming.md
  docs/content/getting-started/navigating-the-viewer.md
  docs/content/getting-started/quick-start/cpp.md
  docs/content/getting-started/quick-start/python.md
  docs/content/getting-started/quick-start/rust.md
  docs/content/getting-started/visualize.md
  docs/content/howto/add-support-for-arbitrary-file-types.md
  docs/content/howto/configure-the-viewer/interactively.md
  docs/content/howto/configure-viewer-through-code.md
  docs/content/howto/ros2-nav-turtlebot.md
Labels: 📖 documentation, exclude from changelog

#5653 Updated READMEs for examples: LLM Embedding-Based Named Entity Recognition, nuScenes, Objectron, Open Photogrammetry Format, Raw Mesh
  docs/cspell.json
  examples/python/llm_embedding_ner/README.md
  examples/python/nuscenes/README.md
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/raw_mesh/README.md
  examples/python/raw_mesh/main.py
Labels: 📖 documentation, ui, examples, include in changelog

#5766 Show all loaded applications in recordings panel
  crates/re_data_ui/src/app_id.rs
  crates/re_data_ui/src/data_source.rs
  crates/re_data_ui/src/editors.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/lib.rs
  crates/re_entity_db/src/store_bundle.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_ui/data/icons/application.png
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/drag_and_drop.rs
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/store_hub.rs
  crates/re_viewport/src/context_menu/actions/collapse_expand_all.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#5599 Example category rehaul
  examples/manifest.toml
  examples/python/arflow/README.md
  examples/python/differentiable_blocks_world/README.md
  examples/python/limap/README.md
  examples/python/mcc/README.md
  examples/python/shape_pointe/README.md
  examples/python/simplerecon/README.md
  examples/python/slahmr/README.md
  examples/python/tapir/README.md
  examples/python/widebaseline/README.md
  scripts/check_example_manifest_coverage.py
Labels: examples, exclude from changelog

#5786 Fix default time range for time series space view
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/visual_time_range.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#5782 Shorter selection ui for tensor/annotation-context/view coordinates/recording
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/image.rs
Labels: ui, 📺 re_viewer, include in changelog

#5785 Added `ros_bridge` external example
  examples/cpp/ros_bridge/README.md
  examples/manifest.toml
  taplo.toml
Labels: examples, exclude from changelog

#5791 Improve browser back-button navigation
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/web_tools.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/store_hub.rs
Labels: 🕸️ web, exclude from changelog

#5620 Updated READMEs for the examples - Batch 1
  docs/cspell.json
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/face_tracking/README.md
  examples/python/gesture_detection/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/lidar/README.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/live_depth_sensor/README.md
Labels: 📖 documentation, ui, examples, include in changelog

#5793 Prevent gratuitous blueprint saves by not gc'ing when the blueprint hasn't changed
  crates/re_viewer_context/src/store_hub.rs
Labels: 🟦 blueprint, include in changelog

#5792 On Web, implement navigating back/forward with mouse buttons
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/web_tools.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#5790 Add `tfrecord_loader` external example
  .github/workflows/documentation.yaml
  docs/cspell.json
  examples/manifest.toml
  examples/python/tfrecord_loader/README.md
Labels: examples, exclude from changelog

#5795 Add buttons to reset the blueprint in the app selection panel
  crates/re_data_ui/src/app_id.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer_context/src/store_hub.rs
Labels: ui, 🟦 blueprint, exclude from changelog

#5787 Always show welcome screen, but fade it in some situations
  crates/re_sdk/src/spawn.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer_context/src/store_hub.rs
  crates/rerun/src/run.rs
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📺 re_viewer, include in changelog

#5801 Fix syntax highlight in entity-queries.md
  docs/content/reference/entity-queries.md
Labels: 📖 documentation, exclude from changelog

#5802 Change all example tags to "Human case"
  examples/c/spawn_viewer/README.md
  examples/cpp/dna/README.md
  examples/cpp/incremental_logging/README.md
  examples/cpp/kiss-icp/README.md
  examples/cpp/ros_bridge/README.md
  examples/cpp/spawn_viewer/README.md
  examples/cpp/vrs/README.md
  examples/python/arflow/README.md
  examples/python/arkit_scenes/README.md
  examples/python/blueprint_stocks/README.md
  examples/python/controlnet/README.md
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/differentiable_blocks_world/README.md
  examples/python/dna/README.md
  examples/python/face_tracking/README.md
  examples/python/gesture_detection/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/incremental_logging/README.md
  examples/python/kiss-icp/README.md
  examples/python/lidar/README.md
  examples/python/limap/README.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/live_depth_sensor/README.md
  examples/python/llm_embedding_ner/README.md
  examples/python/mcc/README.md
  examples/python/nuscenes/README.md
  examples/python/nv12/README.md
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/ros_node/README.md
  examples/python/segment_anything_model/README.md
  examples/python/shape_pointe/README.md
  examples/python/signed_distance_fields/README.md
  examples/python/simplerecon/README.md
  examples/python/slahmr/README.md
  examples/python/structure_from_motion/README.md
  examples/python/tapir/README.md
  examples/python/template/README.md
  examples/python/tfrecord_loader/README.md
  examples/python/urdf_loader/README.md
  examples/python/widebaseline/README.md
  examples/rust/custom_store_subscriber/README.md
  examples/rust/dna/README.md
  examples/rust/incremental_logging/README.md
  examples/rust/objectron/README.md
  examples/rust/spawn_viewer/README.md
  examples/rust/template/README.md
Labels: examples, exclude from changelog

#5800 Rename ML category to "Diffusion models, LLMs, and Machine Learning"
  examples/manifest.toml
Labels: 📖 documentation, examples, exclude from changelog

#5797 Remove TODOs from save-load blueprint doc
  docs/content/getting-started/configure-the-viewer/save-and-load.md
Labels: 📖 documentation, 🟦 blueprint, exclude from changelog

#5807 ARKit example: blueprint info in REAME + minor formatting fixes
  docs/cspell.json
  examples/python/arkit_scenes/README.md
  examples/python/arkit_scenes/main.py
Labels: examples, exclude from changelog

#5808 Move dataloader docs to reference + document CLI flags
  docs/content/reference.md
  docs/content/reference/about.md
  docs/content/reference/cpp.md
  docs/content/reference/data-loaders.md
  docs/content/reference/data-loaders/cpp.md
  docs/content/reference/data-loaders/overview.md
  docs/content/reference/data-loaders/python.md
  docs/content/reference/data-loaders/rust.md
  docs/content/reference/entity-queries.md
  docs/content/reference/migration.md
  docs/content/reference/python.md
  docs/content/reference/roadmap.md
  docs/content/reference/rust.md
  docs/content/reference/sdk-logging-controls.md
  docs/content/reference/sdk-micro-batching.md
  docs/content/reference/sdk-operating-modes.md
  docs/content/reference/types.md
  docs/content/reference/viewer.md
Labels: 📖 documentation, exclude from changelog

#5803 Spring cleaning of `How to` section of docs
  docs/content/howto.md
  docs/content/howto/configure-viewer-through-code.md
  docs/content/howto/extend.md
  docs/content/howto/extend/custom-data.md
  docs/content/howto/extend/extend-ui.md
  docs/content/howto/limit-ram.md
  docs/content/howto/notebook.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/howto/shared-recordings.md
  docs/content/howto/short-lived-entities.md
  docs/content/howto/using-native-loggers.md
  docs/content/reference/data-loaders/overview.md
Labels: 📖 documentation, exclude from changelog

#5806 Remove aspect ratio check from `upload_image.py`
  scripts/upload_image.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#5540 Static data 4: static-aware Rust SDK
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_query_cache/tests/range.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types/src/archetypes/annotation_context.rs
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/archetypes/segmentation_image.rs
  crates/re_types/src/archetypes/series_line.rs
  crates/re_types/src/archetypes/series_point.rs
  crates/re_types/src/archetypes/view_coordinates.rs
  docs/snippets/all/annotation-context/example.rs
  docs/snippets/all/annotation_context_connections.rs
  docs/snippets/all/annotation_context_rects.rs
  docs/snippets/all/annotation_context_segmentation.rs
  docs/snippets/all/asset3d_out_of_tree.rs
  docs/snippets/all/asset3d_simple.rs
  docs/snippets/all/log-file/example.rs
  docs/snippets/all/scalar_multiple_plots.rs
  docs/snippets/all/segmentation_image_simple.rs
  docs/snippets/all/series_line_style.rs
  docs/snippets/all/series_point_style.rs
  docs/snippets/all/view_coordinates_simple.rs
  examples/rust/clock/src/main.rs
  examples/rust/external_data_loader/src/main.rs
  examples/rust/incremental_logging/src/main.rs
  examples/rust/log_file/src/main.rs
  examples/rust/objectron/src/main.rs
  examples/rust/raw_mesh/src/main.rs
  rerun_cpp/src/rerun/recording_stream.hpp
  tests/rust/roundtrips/view_coordinates/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 🦀 Rust API, include in changelog, 🔩 data model

#5814 Introduce blueprint APIs for connect/spawn
  rerun_py/rerun_sdk/rerun/_spawn.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
  tests/python/blueprint/spawn_blueprint.py
Labels: 🟦 blueprint, include in changelog

#5813 nuScenes: add blueprint info + minor cleaning
  docs/cspell.json
  examples/python/nuscenes/README.md
Labels: examples, exclude from changelog

#5810 Objectron: add blueprint info + minor cleaning
  examples/python/objectron/README.md
  examples/python/objectron/main.py
Labels: examples, exclude from changelog

#5811 Tune copy on welcome page
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: ui, exclude from changelog

#5805 Improve documentation previews
  .github/actions/deploy-vercel/action.yml
  .github/actions/deploy-vercel/index.mjs
  .github/actions/deploy-vercel/preview.mjs
  .github/actions/deploy-vercel/production.mjs
  .github/actions/deploy-vercel/test.mjs
  .github/actions/deploy-vercel/util.mjs
  .github/actions/deploy-vercel/vercel.mjs
  .github/pull_request_template.md
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_deploy_landing_preview.yml
  scripts/ci/update_pr_body.py
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#5817 Stop using `<h1>` in example README.md
  examples/python/controlnet/README.md
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/face_tracking/README.md
  examples/python/gesture_detection/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/lidar/README.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/live_depth_sensor/README.md
  examples/python/llm_embedding_ner/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/raw_mesh/README.md
  examples/python/ros_node/README.md
  scripts/lint.py
Labels: examples, exclude from changelog

#5809 Add changelog for the unreleased 0.15
  CHANGELOG.md
  docs/cspell.json
  scripts/generate_changelog.py
  tests/python/blueprint/save_blueprint.py
Labels: ⛴ release, exclude from changelog

#5818 Add dep for docs-path-filter job
  .github/workflows/on_pull_request.yml
Labels: 📖 documentation, exclude from changelog

#5821 More documentation tweaks as requested
  docs/content/getting-started/configure-the-viewer.md
  docs/content/getting-started/configure-the-viewer/navigating-the-viewer-continued.md
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/navigating-the-viewer.md
  docs/content/getting-started/quick-start.md
Labels: 📖 documentation, exclude from changelog

#5824 Misc example readme fixes
  examples/python/clock/README.md
  examples/python/kiss-icp/README.md
  examples/python/log_file/README.md
  examples/python/minimal/README.md
  examples/python/multiprocessing/README.md
  examples/python/multithreading/README.md
Labels: examples, exclude from changelog

#5826 Fix video elements in docs
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-in/rust.md
Labels: 📖 documentation, exclude from changelog

#5829 Update roadmap for 0.15
  docs/content/reference/roadmap.md
Labels: 📖 documentation, exclude from changelog

#5828 Iteration on What is Rerun? page
  docs/content/getting-started/what-is-rerun.md
Labels: 📖 documentation, exclude from changelog

#5832 Remove `description` from example frontmatter
  examples/README.md
  examples/cpp/dna/README.md
  examples/cpp/incremental_logging/README.md
  examples/cpp/kiss-icp/README.md
  examples/cpp/vrs/README.md
  examples/python/arkit_scenes/README.md
  examples/python/blueprint_stocks/README.md
  examples/python/controlnet/README.md
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/dna/README.md
  examples/python/face_tracking/README.md
  examples/python/gesture_detection/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/incremental_logging/README.md
  examples/python/kiss-icp/README.md
  examples/python/lidar/README.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/live_depth_sensor/README.md
  examples/python/llm_embedding_ner/README.md
  examples/python/nuscenes/README.md
  examples/python/nv12/README.md
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/rrt-star/README.md
  examples/python/segment_anything_model/README.md
  examples/python/structure_from_motion/README.md
  examples/python/template/README.md
  examples/rust/dna/README.md
  examples/rust/incremental_logging/README.md
  examples/rust/objectron/README.md
  examples/rust/raw_mesh/README.md
  examples/rust/template/README.md
  scripts/lint.py
Labels: 📖 documentation, examples, exclude from changelog

#5780 Request attention when Rerun Viewer is sent new recording in background
  crates/re_viewer/src/app.rs
Labels: 📺 re_viewer, include in changelog

#5784 Updated READMEs for the examples - Batch 3
  docs/cspell.json
  examples/cpp/eigen_opencv/README.md
  examples/cpp/vrs/README.md
  examples/python/clock/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/live_depth_sensor/README.md
  examples/python/llm_embedding_ner/README.md
  examples/python/minimal/README.md
  examples/python/multiprocessing/README.md
  examples/python/multithreading/README.md
  examples/python/nuscenes/README.md
  examples/python/plots/README.md
  examples/python/rgbd/README.md
  examples/python/ros_node/README.md
  examples/python/rrt-star/README.md
  examples/python/segment_anything_model/README.md
  examples/python/signed_distance_fields/README.md
  examples/python/structure_from_motion/README.md
Labels: 📖 documentation, ui, examples, include in changelog

#5831 Fix/improve UI when viewing all components of an entity
  Cargo.lock
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_format/Cargo.toml
  crates/re_types_core/src/components/instance_key_ext.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/src/syntax_highlighting.rs
Labels: 🪳 bug, ui, exclude from changelog

#5833 Add preambles to the Paper Walkthroughs' READMEs
  examples/python/arflow/README.md
  examples/python/differentiable_blocks_world/README.md
  examples/python/limap/README.md
  examples/python/mcc/README.md
  examples/python/shape_pointe/README.md
  examples/python/simplerecon/README.md
  examples/python/slahmr/README.md
  examples/python/widebaseline/README.md
Labels: examples, exclude from changelog

#5834 Update concept section
  docs/content/concepts/annotation-context.md
  docs/content/concepts/apps-and-recordings.md
  docs/content/concepts/batches.md
  docs/content/concepts/blueprint.md
  docs/content/concepts/entity-component.md
  docs/content/concepts/entity-path.md
  docs/content/concepts/spaces-and-transforms.md
  docs/content/concepts/timelines.md
Labels: 📖 documentation, exclude from changelog

#5830 0.15 migration guide for removed instance keys
  CHANGELOG.md
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types_core/src/components/instance_key.rs
  docs/content/concepts/batches.md
  docs/content/howto/extend/custom-data.md
  docs/content/reference/migration.md
  docs/content/reference/migration/migration-0-13.md
  docs/content/reference/migration/migration-0-15.md
  docs/content/reference/migration/migration-0-9.md
  docs/content/reference/types/components/instance_key.md
  docs/snippets/all/any_values.py
  rerun_cpp/src/rerun/components/instance_key.hpp
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/rerun_sdk/rerun/components/instance_key.py
Labels: 📖 documentation, ⛴ release, exclude from changelog

#5573 New data APIs 0: `ClampedZip` iterator machinery
  Cargo.lock
  Cargo.toml
  crates/re_query2/Cargo.toml
  crates/re_query2/README.md
  crates/re_query2/src/bin/clamped_zip.rs
  crates/re_query2/src/clamped_zip/.gitattributes
  crates/re_query2/src/clamped_zip/generated.rs
  crates/re_query2/src/clamped_zip/mod.rs
  crates/re_query2/src/lib.rs
  crates/re_query2/src/visible_history.rs
  scripts/lint.py
Labels: 🔍 re_query, include in changelog

#5581 New data APIs 2: cached latest-at queries
  Cargo.lock
  Cargo.toml
  crates/re_query_cache2/Cargo.toml
  crates/re_query_cache2/README.md
  crates/re_query_cache2/benches/flat_vec_deque.rs
  crates/re_query_cache2/benches/latest_at.rs
  crates/re_query_cache2/examples/latest_at.rs
  crates/re_query_cache2/src/cache.rs
  crates/re_query_cache2/src/flat_vec_deque.rs
  crates/re_query_cache2/src/latest_at/mod.rs
  crates/re_query_cache2/src/latest_at/query.rs
  crates/re_query_cache2/src/latest_at/results.rs
  crates/re_query_cache2/src/lib.rs
  crates/re_query_cache2/tests/latest_at.rs
  crates/re_types_core/src/size_bytes.rs
Labels: 🔍 re_query, include in changelog

#5605 New data APIs 3: Send/Sync/'static `Component`, once and for all
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/src/range.rs
  crates/re_query_cache2/src/latest_at/results.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_types_core/src/loggable.rs
Labels: include in changelog, 🔩 data model

#5840 Do not show the remove button when the origin is empty
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, ui, exclude from changelog

#5606 New data APIs 4: cached latest-at mono helpers everywhere
  Cargo.lock
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/store_helpers.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_entity_db/Cargo.toml
  crates/re_entity_db/src/blueprint/components/entity_properties_component_ext.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_entity_db/src/lib.rs
  crates/re_entity_db/tests/clear.rs
  crates/re_error/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_query2/src/promise.rs
  crates/re_query_cache2/Cargo.toml
  crates/re_query_cache2/src/latest_at/helpers.rs
  crates/re_query_cache2/src/latest_at/mod.rs
  crates/re_query_cache2/src/lib.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/view_query.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, include in changelog

#5633 New data APIs 5: port data UIs to new APIs
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/app_id.rs
  crates/re_data_ui/src/blueprint_data.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/data_source.rs
  crates/re_data_ui/src/editors.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/entity_path.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_data_ui/src/material.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_data_ui/src/store_id.rs
  crates/re_data_ui/src/transform3d.rs
  crates/re_query2/src/promise.rs
  crates/re_query_cache2/src/latest_at/helpers.rs
  crates/re_query_cache2/src/latest_at/results.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewport/src/blueprint/data_ui.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 📺 re_viewer, 📉 performance, 🚜 refactor, include in changelog

#5679 New data APIs 7: `RangeZip` iterator machinery
  crates/re_query2/Cargo.toml
  crates/re_query2/src/bin/range_zip.rs
  crates/re_query2/src/lib.rs
  crates/re_query2/src/range_zip/.gitattributes
  crates/re_query2/src/range_zip/generated.rs
  crates/re_query2/src/range_zip/mod.rs
Labels: 🔍 re_query, codegen/idl, include in changelog

#5687 New data APIs 8: uncached range queries
  crates/re_query2/examples/range.rs
  crates/re_query2/src/lib.rs
  crates/re_query2/src/range/mod.rs
  crates/re_query2/src/range/query.rs
  crates/re_query2/src/range/results.rs
  crates/re_query2/tests/range.rs
Labels: 🔍 re_query, include in changelog

#5837 Support displaying 1D tensors
  CHANGELOG.md
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_tensor/src/dimension_mapping.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  tests/python/release_checklist/check_1d_tensor_data.py
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5855 Add inline markdown example description to public examples
  crates/re_build_examples/src/rrd.rs
  examples/README.md
  examples/python/arkit_scenes/main.py
  examples/python/detect_and_track_objects/main.py
  examples/python/dicom_mri/main.py
  examples/python/dna/main.py
  examples/python/human_pose_tracking/main.py
  examples/python/nuscenes/main.py
  examples/python/open_photogrammetry_format/main.py
  examples/python/plots/main.py
  examples/python/raw_mesh/main.py
  examples/python/rgbd/main.py
  examples/python/rrt-star/main.py
  examples/python/segment_anything_model/main.py
  examples/python/structure_from_motion/main.py
Labels: 📖 documentation, examples, exclude from changelog

#5861 Pin `mediapipe` to 0.10.9 to fix Human Pose Tracking example
  examples/python/face_tracking/requirements.txt
  examples/python/gesture_detection/requirements.txt
  examples/python/human_pose_tracking/requirements.txt
Labels: 🪳 bug, examples, dependencies, exclude from changelog

#5846 Check release branch format
  .github/workflows/release.yml
  RELEASES.md
  scripts/ci/crates.py
Labels: ⛴ release, exclude from changelog, :ship: CI

#5851 Add schematics to the blueprint section
  docs/content/concepts/blueprint.md
Labels: 📖 documentation, exclude from changelog

#5863 Minor improvements to CLI help with mention of .rbl files
  crates/rerun/src/run.rs
Labels: exclude from changelog, CLI

#5858 Fix missing clamping semantics for raw instance-based UIs
  crates/re_query_cache2/src/latest_at/helpers.rs
Labels: 🪳 bug, 📺 re_viewer, 🔍 re_query, exclude from changelog

#5853 Split `re_viewport`'s codegened types into `re_types_blueprint`
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/Cargo.toml
  crates/re_data_ui/src/blueprint_types.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/lib.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/container_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/panel_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/viewport_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/auto_layout.fbs
  crates/re_types/definitions/rerun/blueprint/components/auto_space_views.fbs
  crates/re_types/definitions/rerun/blueprint/components/container_kind.fbs
  crates/re_types/definitions/rerun/blueprint/components/grid_columns.fbs
  crates/re_types/definitions/rerun/blueprint/components/included_space_view.fbs
  crates/re_types/definitions/rerun/blueprint/components/root_container.fbs
  crates/re_types/definitions/rerun/blueprint/components/space_view_maximized.fbs
  crates/re_types_blueprint/.gitattributes
  crates/re_types_blueprint/Cargo.toml
  crates/re_types_blueprint/README.md
  crates/re_types_blueprint/src/blueprint/archetypes/.gitattributes
  crates/re_types_blueprint/src/blueprint/archetypes/container_blueprint.rs
  crates/re_types_blueprint/src/blueprint/archetypes/mod.rs
  crates/re_types_blueprint/src/blueprint/archetypes/panel_blueprint.rs
  crates/re_types_blueprint/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_types_blueprint/src/blueprint/components/.gitattributes
  crates/re_types_blueprint/src/blueprint/components/auto_layout.rs
  crates/re_types_blueprint/src/blueprint/components/auto_layout_ext.rs
  crates/re_types_blueprint/src/blueprint/components/auto_space_views.rs
  crates/re_types_blueprint/src/blueprint/components/container_kind.rs
  crates/re_types_blueprint/src/blueprint/components/grid_columns.rs
  crates/re_types_blueprint/src/blueprint/components/included_space_view.rs
  crates/re_types_blueprint/src/blueprint/components/mod.rs
  crates/re_types_blueprint/src/blueprint/components/root_container.rs
  crates/re_types_blueprint/src/blueprint/components/space_view_maximized.rs
  crates/re_types_blueprint/src/blueprint/mod.rs
  crates/re_types_blueprint/src/lib.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/blueprint/.gitattributes
  crates/re_viewport/src/blueprint/components/container_kind_ext.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🚜 refactor, codegen/idl, exclude from changelog

#5865 Remove the deprecated `writing_rules.md`
  DESIGN.md
  design/writing_rules.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#5867 Improve draw order check
  tests/python/release_checklist/check_draw_order.py
Labels: 🔨 testing, exclude from changelog

#5871 Always create a tree with a container even if we have no space-views
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog

#5872 Always generate a random blueprint id to avoid updating an existing blueprint
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/src/python_bridge.rs
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog

#5874 Pin mimalloc to 0.1.37
  Cargo.lock
  Cargo.toml
Labels: 🪳 bug, 📉 performance, dependencies, exclude from changelog

#5869 Add Revy to examples
  examples/manifest.toml
  examples/rust/revy/README.md
Labels: examples, exclude from changelog

#5866 Web viewer guide
  docs/content/howto/embed-rerun-viewer.md
  docs/content/reference/npm.md
  rerun_js/web-viewer/index.js
Labels: 📖 documentation, exclude from changelog

#5868 Save blueprints before closing an app
  crates/re_viewer/src/app.rs
  crates/re_viewer_context/src/store_hub.rs
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog

#5876 Removed unreleased/speculative-links for 0.15
  CHANGELOG.md
  crates/re_types/definitions/rerun/blueprint/archetypes/background_3d.fbs
  crates/re_types/definitions/rerun/blueprint/components/background_3d_kind.fbs
  crates/re_types/definitions/rerun/blueprint/components/container_kind.fbs
  crates/re_types/definitions/rerun/blueprint/datatypes/visible_time_range.fbs
  crates/re_types/definitions/rerun/components/marker_shape.fbs
  crates/re_types/definitions/rerun/datatypes/bool.fbs
  crates/re_types/definitions/rerun/datatypes/time_int.fbs
  crates/re_types/definitions/rerun/datatypes/uint64.fbs
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/getting-started/data-in/open-any-file.md
  docs/content/howto/configure-viewer-through-code.md
  docs/content/reference/types/components/marker_shape.md
  docs/content/reference/types/datatypes/bool.md
  docs/content/reference/types/datatypes/time_int.md
  docs/content/reference/types/datatypes/uint64.md
Labels: 📖 documentation, do-not-merge

#5880 Fix tag formatting for ROS node example
  examples/python/ros_node/README.md
Labels: examples, exclude from changelog

#5886 Allow to call find_package(rerun_sdk) two or more times
  rerun_cpp/Config.cmake.in
Labels: 🌊 C++ API, include in changelog

#5881 Add notebook fake-check to checklist
  tests/python/release_checklist/check_notebook.py
Labels: 🔨 testing, ⛴ release, exclude from changelog

#5877 Fix timeout in notebooks by making the app_url correctly point to app.rerun.io
  rerun_py/src/python_bridge.rs
Labels: 🪳 bug, notebook, include in changelog

#5864 Update `egui_commonmark`
  Cargo.lock
  Cargo.toml
Labels: ui, dependencies, include in changelog

#5891 Fix visible range not working
  crates/re_viewer_context/src/space_view/view_query.rs
Labels: 🪳 bug, exclude from changelog

#5897 Fix python lints, make python lint ci conditional
  .github/workflows/auto_release_crates.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_checks_python.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_js.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_test_wheels.yml
  examples/python/controlnet/main.py
  examples/python/controlnet/requirements.txt
  examples/python/face_tracking/main.py
  examples/python/gesture_detection/main.py
  examples/python/human_pose_tracking/main.py
  examples/python/nv12/main.py
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5899 Don't gate `torch` behind python<3.12
  examples/python/controlnet/requirements.txt
  examples/python/depth_guided_stable_diffusion/requirements.txt
  examples/python/detect_and_track_objects/requirements.txt
  examples/python/llm_embedding_ner/requirements.txt
  examples/python/segment_anything_model/requirements.txt
  noxfile.py
  rerun_py/requirements-build.txt
  rerun_py/requirements-lint.txt
  scripts/requirements-dev.txt
Labels: dependencies, exclude from changelog

#5860 Port `re_viewport`-related queries to new data APIs
  Cargo.lock
  crates/re_entity_db/Cargo.toml
  crates/re_entity_db/src/entity_db.rs
  crates/re_query_cache2/Cargo.toml
  crates/re_query_cache2/src/latest_at/results.rs
  crates/re_query_cache2/src/latest_at/to_archetype/.gitattributes
  crates/re_query_cache2/src/latest_at/to_archetype/background3d.rs
  crates/re_query_cache2/src/latest_at/to_archetype/container_blueprint.rs
  crates/re_query_cache2/src/latest_at/to_archetype/mod.rs
  crates/re_query_cache2/src/latest_at/to_archetype/panel_blueprint.rs
  crates/re_query_cache2/src/latest_at/to_archetype/plot_legend.rs
  crates/re_query_cache2/src/latest_at/to_archetype/scalar_axis.rs
  crates/re_query_cache2/src/latest_at/to_archetype/space_view_blueprint.rs
  crates/re_query_cache2/src/latest_at/to_archetype/space_view_contents.rs
  crates/re_query_cache2/src/latest_at/to_archetype/viewport_blueprint.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view/src/sub_archetypes.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_types_builder/src/codegen/rust/to_archetype.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#5900 Run all jobs if any CI job changes
  .github/workflows/on_pull_request.yml
Labels: 📉 performance, exclude from changelog, :ship: CI

#5902 CI: update misc actions
  .github/actions/setup-rust/action.yml
  .github/workflows/checkboxes.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_pull_request_target_contrib.yml
  .github/workflows/release.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_deploy_landing_preview.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_track_size.yml
  .github/workflows/reusable_update_pr_body.yml
  .github/workflows/reusable_upload_examples.yml
  .github/workflows/reusable_upload_web.yml
Labels: exclude from changelog, :ship: CI

#5901 Speed up CI: Skip a few steps
  .github/workflows/contrib_checks.yml
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  pixi.lock
  pixi.toml
  scripts/ci/rust_checks.py
  tests/roundtrips.py
Labels: exclude from changelog, :ship: CI

#5909 Replace requirements-docs.txt with a python doc pixi environment
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_python.yml
  .github/workflows/reusable_deploy_docs.yml
  crates/re_build_search_index/README.md
  crates/re_build_search_index/src/ingest/python.rs
  pixi.lock
  pixi.toml
  rerun_py/docs/writing_docs.md
  rerun_py/requirements-doc.txt
  scripts/ci/requirements.txt
  scripts/requirements-dev.txt
Labels: 🧑‍💻 dev experience, include in changelog

#5914 Fix remaining just mentions
  ARCHITECTURE.md
  CHANGELOG.md
  CONTRIBUTING.md
  docs/snippets/compare_snippet_output.py
  examples/python/template/README.md
  examples/rust/template/README.md
  noxfile.py
  pixi.lock
  pixi.toml
  scripts/requirements-dev.txt
  scripts/run_python_e2e_test.py
  scripts/screenshot_compare/build_screenshot_compare.py
  scripts/upload_image.py
  tests/cpp/plot_dashboard_stress/main.cpp
  tests/python/plot_dashboard_stress/main.py
  tests/roundtrips.py
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#5913 Improve output of `re_build_web_viewer`
  crates/re_build_web_viewer/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5912 Update python readme and add `py-wheel` command
  BUILD.md
  pixi.toml
  rerun_py/README.md
Labels: 📖 documentation, 🧑‍💻 dev experience, include in changelog

#5915 Re-run all of CI if `pixi.toml` changes
  .github/workflows/on_pull_request.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5908 Update to Rust 1.76
  .github/actions/setup-rust/action.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  BUILD.md
  CHANGELOG.md
  Cargo.toml
  Cranky.toml
  RELEASES.md
  ci_docker/Dockerfile
  ci_docker/publish.sh
  clippy.toml
  crates/re_analytics/examples/end_to_end.rs
  crates/re_build_info/src/build_info.rs
  crates/re_data_store/src/store_read.rs
  crates/re_renderer/src/file_resolver.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  crates/re_viewer/data/quick_start_guides/rust_spawn.md
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewport/src/viewport.rs
  docs/content/getting-started/installing-viewer.md
  docs/content/getting-started/quick-start/rust.md
  examples/rust/clock/Cargo.toml
  examples/rust/custom_data_loader/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/custom_store_subscriber/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/external_data_loader/Cargo.toml
  examples/rust/incremental_logging/Cargo.toml
  examples/rust/log_file/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/shared_recording/Cargo.toml
  examples/rust/spawn_viewer/Cargo.toml
  examples/rust/stdio/Cargo.toml
  examples/rust/template/Cargo.toml
  rust-toolchain
  scripts/clippy_wasm/clippy.toml
  scripts/lint.py
  tests/rust/plot_dashboard_stress/Cargo.toml
Labels: 🧑‍💻 dev experience, include in changelog, :ship: CI

#5917 Fix cell size test now that the overhead has shrunk
  crates/re_log_types/src/data_cell.rs
Labels: 🔨 testing, exclude from changelog

#5903 Use new Mediapipe API in human pose tracking example
  examples/python/face_tracking/requirements.txt
  examples/python/gesture_detection/requirements.txt
  examples/python/human_pose_tracking/README.md
  examples/python/human_pose_tracking/main.py
  examples/python/human_pose_tracking/requirements.txt
Labels: examples, exclude from changelog

#5910 Don't build examples on each PR
  .github/pull_request_template.md
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_track_size.yml
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5920 Improve the "What is Rerun?" documentation
  README.md
  docs/content/getting-started/what-is-rerun.md
Labels: 📖 documentation, exclude from changelog

#5923 Update Python API links to getting-started and tutorial
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation, include in changelog

#5926 Add 0.15.1 to changelog
  CHANGELOG.md
Labels: ⛴ release, exclude from changelog

#5928 Merge 0.15.1 notebook fix to `main`
  CHANGELOG.md
  examples/python/ros_node/README.md
  rerun_py/src/python_bridge.rs
Labels: ⛴ release, exclude from changelog

#5929 Don't redeploy rerun.io before the web artifacts have shipped
  .github/workflows/release.yml
Labels: 🪳 bug, 🕸️ web, ⛴ release, exclude from changelog

#5922 Remove remaining shell scripts, fix rust wasm checks for ci
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_rust.yml
  CONTRIBUTING.md
  pixi.toml
  scripts/check.sh
  scripts/ci/cargo_deny.sh
  scripts/ci/check_large_files.py
  scripts/ci/check_large_files.sh
  scripts/ci/rust_checks.py
  scripts/clippy_wasm.sh
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5932 Simplify docker image to only include rustup and essential system libs
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  ci_docker/Dockerfile
  ci_docker/publish.sh
  pixi.lock
  pixi.toml
Labels: exclude from changelog, :ship: CI

#5916 Only build web viewer if any rust or web stuff has changed
  .github/workflows/on_pull_request.yml
Labels: exclude from changelog, :ship: CI

#5935 Update to pixi 0.19
  .github/workflows/auto_release_crates.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_checks_python.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_js.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_test_wheels.yml
Labels: exclude from changelog, :ship: CI

#5937 Move many CI jobs from `main` to `nightly`
  .github/workflows/nightly.yml
  .github/workflows/on_push_main.yml
  BUILD.md
Labels: exclude from changelog, :ship: CI

#5938 Fix wheel version verification
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_examples.yml
Labels: exclude from changelog, :ship: CI

#5941 Try fix main CI again
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_examples.yml
Labels: exclude from changelog, :ship: CI

#5942 Fix CI: Use the correct `wheel-test` pixi env
  .github/workflows/reusable_build_examples.yml
Labels: 🪳 bug, exclude from changelog, :ship: CI

#5943 CI: Install example pip deps into the correct pixi env
  .github/workflows/reusable_build_examples.yml
Labels: exclude from changelog, :ship: CI

#5940 Add `@rerun-bot full-check` command
  .github/pull_request_template.md
  .github/workflows/on_pr_comment.yml
  .github/workflows/on_push_main.yml
Labels: 🧑‍💻 dev experience, exclude from changelog

#5939 Remove all dev/ci requirements.txt and fully replace with pixi
  .github/workflows/auto_approve.yml
  .github/workflows/auto_release_crates.yml
  .github/workflows/checkboxes.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_pull_request_target_contrib.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_update_pr_body.yml
  noxfile.py
  pixi.lock
  pixi.toml
  rerun_py/requirements-build.txt
  rerun_py/requirements-lint.txt
  scripts/ci/approve_workflow_runs.py
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/crates.py
  scripts/ci/generate_pr_summary.py
  scripts/ci/publish_wheels.py
  scripts/ci/requirements-crates.txt
  scripts/ci/requirements.txt
  scripts/ci/sync_release_assets.py
  scripts/ci/update_pr_body.py
  scripts/requirements-dev.txt
Labels: 🧑‍💻 dev experience, include in changelog, :ship: CI

#5946 Full check part 2
  .github/workflows/on_pr_comment.yml
Labels: exclude from changelog, :ship: CI

#5947 Full check 3
  .github/workflows/on_pr_comment.yml
Labels: exclude from changelog, :ship: CI

#5944 A bunch of small fixes
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_test_wheels.yml
  CHANGELOG.md
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  scripts/ci/build_and_upload_wheels.py
Labels: ui, exclude from changelog

#5950 Full check part 4
  .github/workflows/on_pr_comment.yml
  README.md
Labels: exclude from changelog, :ship: CI

#5952 Random change to test PR comment trigger
  README.md
Labels: exclude from changelog, :ship: CI

#5965 Move "What is Rerun for?" to it's own page
  .gitignore
  docs/content/getting-started/configure-the-viewer.md
  docs/content/getting-started/data-in.md
  docs/content/getting-started/installing-viewer.md
  docs/content/getting-started/navigating-the-viewer.md
  docs/content/getting-started/quick-start.md
  docs/content/getting-started/troubleshooting.md
  docs/content/getting-started/what-is-rerun-for.md
  docs/content/getting-started/what-is-rerun.md
Labels: 📖 documentation, exclude from changelog

#5970 Fix nightly
  .github/workflows/nightly.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_publish_rerun_c.yml
  .github/workflows/reusable_test_wheels.yml
Labels: exclude from changelog, :ship: CI

#5969 Replace linkinator with lychee
  .github/pull_request_template.md
  .github/workflows/README.md
  .github/workflows/documentation.yaml
  .github/workflows/reusable_checks.yml
  CHANGELOG.md
  CONTRIBUTING.md
  examples/rust/revy/README.md
  lychee.toml
  pixi.lock
Labels: exclude from changelog, :ship: CI

#5975 Remove old assertion in arrow bench
  crates/re_data_store/benches/arrow2.rs
Labels: 🪳 bug, 🔨 testing, exclude from changelog

#5977 Fix weekly alpha crate release
  .github/workflows/auto_release_crates.yml
Labels: exclude from changelog, :ship: CI

#5972 Merge rust scripts into `re_dev_tools` crate
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_build_examples/Cargo.toml
  crates/re_build_web_viewer/Cargo.toml
  crates/re_build_web_viewer/src/main.rs
  crates/re_dev_tools/Cargo.toml
  crates/re_dev_tools/README.md
  crates/re_dev_tools/src/build_examples/example.rs
  crates/re_dev_tools/src/build_examples/manifest.rs
  crates/re_dev_tools/src/build_examples/mod.rs
  crates/re_dev_tools/src/build_examples/rrd.rs
  crates/re_dev_tools/src/build_examples/snippets.rs
  crates/re_dev_tools/src/build_examples/wait_for_output.rs
  crates/re_dev_tools/src/build_search_index/README.md
  crates/re_dev_tools/src/build_search_index/build.rs
  crates/re_dev_tools/src/build_search_index/ingest.rs
  crates/re_dev_tools/src/build_search_index/ingest/cpp.rs
  crates/re_dev_tools/src/build_search_index/ingest/docs.rs
  crates/re_dev_tools/src/build_search_index/ingest/examples.rs
  crates/re_dev_tools/src/build_search_index/ingest/python.rs
  crates/re_dev_tools/src/build_search_index/ingest/rust.rs
  crates/re_dev_tools/src/build_search_index/meili.rs
  crates/re_dev_tools/src/build_search_index/mod.rs
  crates/re_dev_tools/src/build_search_index/repl.rs
  crates/re_dev_tools/src/build_search_index/util.rs
  crates/re_dev_tools/src/build_web_viewer/README.md
  crates/re_dev_tools/src/build_web_viewer/lib.rs
  crates/re_dev_tools/src/build_web_viewer/mod.rs
  crates/re_dev_tools/src/main.rs
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/README.md
  docs/snippets/snippets.toml
  pixi.toml
  rerun_cpp/docs/Doxyfile
  rerun_js/web-viewer/package.json
  rerun_py/docs/gen_common_index.py
  scripts/ci/build_and_upload_wheels.py
  scripts/screenshot_compare/build_screenshot_compare.py
  web_viewer/README.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#5980 Fix rust ci not running on cargo.lock changes
  .github/workflows/on_pull_request.yml
Labels: exclude from changelog, :ship: CI

#5981 Update tornado for python notebook example to address security issue
  examples/python/notebook/requirements.txt
Labels: dependencies, exclude from changelog

#5983 Allow PR bodies without any checkboxes
  scripts/ci/check_pr_checkboxes.py
Labels: 🧑‍💻 dev experience, 😤 annoying, exclude from changelog, :ship: CI

#5986 Fix various links in rust, python and toml files
  .github/workflows/reusable_checks.yml
  crates/re_crash_handler/src/lib.rs
  crates/re_types_core/src/lib.rs
  crates/re_viewer/src/app.rs
  deny.toml
  examples/rust/log_file/src/main.rs
  lychee.toml
  pixi.toml
  rerun_py/Cargo.toml
  rerun_py/build.rs
  rerun_py/rerun_sdk/rerun/_log.py
Labels: 📖 documentation, include in changelog, :ship: CI

#5989 Fix main ci - cranky didn't understand config path env var
  scripts/ci/rust_checks.py
  scripts/lint.py
Labels: exclude from changelog, :ship: CI

#5978 Improve type index pages, codegen now knows about doc categories
  crates/re_types/definitions/docs/attributes.fbs
  crates/re_types/definitions/rerun/archetypes/arrows2d.fbs
  crates/re_types/definitions/rerun/archetypes/arrows3d.fbs
  crates/re_types/definitions/rerun/archetypes/asset3d.fbs
  crates/re_types/definitions/rerun/archetypes/bar_chart.fbs
  crates/re_types/definitions/rerun/archetypes/boxes2d.fbs
  crates/re_types/definitions/rerun/archetypes/boxes3d.fbs
  crates/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/definitions/rerun/archetypes/line_strips2d.fbs
  crates/re_types/definitions/rerun/archetypes/line_strips3d.fbs
  crates/re_types/definitions/rerun/archetypes/mesh3d.fbs
  crates/re_types/definitions/rerun/archetypes/pinhole.fbs
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/definitions/rerun/archetypes/points3d.fbs
  crates/re_types/definitions/rerun/archetypes/scalar.fbs
  crates/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/re_types/definitions/rerun/archetypes/series_line.fbs
  crates/re_types/definitions/rerun/archetypes/series_point.fbs
  crates/re_types/definitions/rerun/archetypes/tensor.fbs
  crates/re_types/definitions/rerun/archetypes/text_document.fbs
  crates/re_types/definitions/rerun/archetypes/text_log.fbs
  crates/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/re_types/definitions/rerun/archetypes/view_coordinates.fbs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/docs.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  docs/content/reference/types.md
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/components.md
  docs/content/reference/types/datatypes.md
Labels: 📖 documentation, include in changelog

#5973 Fix nightly ci
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  docs/snippets/snippets.toml
  scripts/run_python_e2e_test.py
  tests/roundtrips.py
Labels: exclude from changelog, :ship: CI
