Repository rerun-io/rerun, pull requests merged in 2024-07, with the labels that each got.

#6683 Update to latest egui master
  Cargo.lock
  Cargo.toml
  crates/re_format/src/lib.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: ui, dependencies, exclude from changelog, egui

#6680 Make it possible to configure how `rerun_notebook` fetches the widget
  rerun_js/web-viewer/index.ts
  rerun_notebook/README.md
  rerun_notebook/package-lock.json
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_notebook/src/rerun_notebook/__main__.py
  rerun_notebook/src/rerun_notebook/asset_server.py
  scripts/ci/publish_wheels.py
Labels: notebook, exclude from changelog

#6659 Improve bundling of `web-viewer` package
  Cargo.toml
  crates/re_dev_tools/src/build_web_viewer/lib.rs
  crates/re_dev_tools/src/build_web_viewer/mod.rs
  lychee.toml
  rerun_js/web-viewer/.gitignore
  rerun_js/web-viewer/build-wasm.mjs
  rerun_js/web-viewer/bundle.mjs
  rerun_js/web-viewer/index.ts
  rerun_js/web-viewer/package.json
  rerun_notebook/build.mjs
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
Labels: 🕸️ web, notebook, exclude from changelog

#6692 Show batches of default components correctly
  Cargo.lock
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/component_ui_registry.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#6679 Add a "Visualizers and Overrides" concept page
  crates/re_types_builder/src/codegen/docs/mod.rs
  docs/content/concepts/blueprint.md
  docs/content/concepts/entity-component.md
  docs/content/concepts/visualizers-and-overrides.md
  docs/content/reference/types/archetypes.md
  docs/snippets/all/concepts/viscomp-base.py
  docs/snippets/all/concepts/viscomp-component-default.py
  docs/snippets/all/concepts/viscomp-component-override.py
  docs/snippets/all/concepts/viscomp-visualizer-override-multiple.py
  docs/snippets/all/concepts/viscomp-visualizer-override.py
  docs/snippets/snippets.toml
Labels: 📖 documentation, include in changelog

#6709 Update to latest egui
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/list_item/label_content.rs
  crates/re_ui/src/list_item/property_content.rs
  crates/re_ui/src/ui_ext.rs
Labels: ui, 📺 re_viewer, dependencies, exclude from changelog, egui

#6703 Fix ui for color fallback showing the wrong value
  crates/re_data_ui/src/annotation_context.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/overrides.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/utils/color.rs
  crates/re_viewer_context/src/utils/mod.rs
Labels: 📺 re_viewer, exclude from changelog

#6710 Fix `HybridLatestAtResults` not using defaults correctly/surprisingly, clarify ResultExt method intention
  crates/re_space_view/src/results_ext.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
Labels: 🪳 bug, exclude from changelog

#6712 Handle static text messages in TextLogView gracefully, handle overrides
  Cargo.lock
  crates/re_space_view_text_log/Cargo.toml
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
Labels: 📺 re_viewer, include in changelog

#6714 Fix overrides/defaults not working in TextDocumentView
  crates/re_space_view/src/results_ext.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
Labels: 🪳 bug, exclude from changelog

#6713 Update roadmap for 0.17
  docs/content/reference/roadmap.md
  scripts/lint.py
Labels: 📖 documentation, exclude from changelog

#6715 Fix snippet CI
  docs/snippets/snippets.toml
Labels: 🪳 bug, exclude from changelog, :ship: CI

#6716 Fix `HybridLatestAtResults`' `get_instance`/`get_instance_with_fallback` not indexing into defaults.
  crates/re_space_view/src/results_ext.rs
Labels: 🪳 bug, exclude from changelog

#6718 Fix draw order slider moving too slowly when negative
  crates/re_edit_ui/src/datatype_editors/float_drag.rs
Labels: 🪳 bug, exclude from changelog

#6719 Fix ui_ext.rs by adding the missing colon in the unused_self Clippy configuration.
  crates/re_ui/src/ui_ext.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#6721 Fix missing clamp to border semantics on displaying component ui for a specific instance
  crates/re_viewer_context/src/component_ui_registry.rs
Labels: 💣 crash, 🦟 regression, exclude from changelog

#6717 BarChartView now queries overrides & defaults
  crates/re_space_view_bar_chart/src/visualizer_system.rs
Labels: 🪳 bug, exclude from changelog

#6724 Reduce scene unit radius start value to 0.1 to mitigate sudden overdraw issues on ui interaction
  crates/re_edit_ui/src/radius.rs
Labels: 📺 re_viewer, exclude from changelog

#6691 Use text-less checkbox instead of toggle
  crates/re_edit_ui/src/datatype_editors/bool_toggle.rs
  crates/re_ui/src/list_item/property_content.rs
Labels: ui, exclude from changelog

#6720 Introduce `ButtonContent` and use it in the selection panel
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_ui/src/list_item/button_content.rs
  crates/re_ui/src/list_item/mod.rs
Labels: ui, include in changelog

#6515 Do not read query in embedded web viewer
  .vscode/settings.json
  Cargo.lock
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/history.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer/src/web_tools.rs
  rerun_js/web-viewer/index.ts
  scripts/lint.py
  web_viewer/index.html
Labels: 🕸️ web, include in changelog

#6729 Update egui
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#6728 Enable examples that used to break pixi
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, examples, exclude from changelog

#6738 Update egui
  Cargo.lock
  Cargo.toml
  crates/re_time_panel/src/data_density_graph.rs
Labels: dependencies, exclude from changelog, egui

#6739 Update docs about versioning
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-in/rust.md
  docs/content/getting-started/installing-viewer.md
  docs/content/reference/sdk-operating-modes.md
  rerun_js/web-viewer-react/README.md
  rerun_js/web-viewer/README.md
Labels: 📖 documentation, exclude from changelog

#6740 Update actions/checkout usage
  .github/workflows/checkboxes.yml
  .github/workflows/reusable_update_pr_body.yml
Labels: exclude from changelog, :ship: CI

#6746 Fix Python codegen for enums
  crates/re_types_builder/src/codegen/python/mod.rs
  rerun_py/rerun_sdk/rerun/blueprint/components/background_kind.py
  rerun_py/rerun_sdk/rerun/blueprint/components/container_kind.py
  rerun_py/rerun_sdk/rerun/blueprint/components/corner2d.py
  rerun_py/rerun_sdk/rerun/blueprint/components/panel_state.py
  rerun_py/rerun_sdk/rerun/blueprint/components/view_fit.py
  rerun_py/rerun_sdk/rerun/components/aggregation_policy.py
  rerun_py/rerun_sdk/rerun/components/colormap.py
  rerun_py/rerun_sdk/rerun/components/magnification_filter.py
  rerun_py/rerun_sdk/rerun/components/marker_shape.py
  rerun_py/tests/test_types/components/enum_test.py
Labels: 🪳 bug, 🐍 Python API, codegen/idl, exclude from changelog

#6750 Fix commands in the GitHub prerelease
  .github/workflows/nightly.yml
Labels: exclude from changelog, :ship: CI

#6752 Update to egui 0.28.0
  Cargo.lock
  Cargo.toml
Labels: 📺 re_viewer, dependencies, include in changelog, egui

#6747 Add opacity override to `rgbd` example
  examples/python/rgbd/rgbd.py
Labels: examples, exclude from changelog

#6745 Better document limited effect of `DepthMeter` & `FillRatio` in 2D views
  crates/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/re_types/definitions/rerun/components/depth_meter.fbs
  crates/re_types/definitions/rerun/components/fill_ratio.fbs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/components/depth_meter.rs
  crates/re_types/src/components/fill_ratio.rs
  crates/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/components/depth_meter.md
  docs/content/reference/types/components/fill_ratio.md
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/components/depth_meter.hpp
  rerun_cpp/src/rerun/components/fill_ratio.hpp
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/components/depth_meter.py
  rerun_py/rerun_sdk/rerun/components/fill_ratio.py
Labels: 📖 documentation, include in changelog

#5842 Add tooltip to timeline selector
  crates/re_time_panel/src/time_control_ui.rs
Labels: 📖 documentation, ui, exclude from changelog

#6741 Multiple instances of points/arrows/boxes with single label display label now at the center
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/utilities/labels.rs
  crates/re_space_view_spatial/src/visualizers/utilities/mod.rs
  crates/re_space_view_spatial/src/visualizers/utilities/spatial_view_visualizer.rs
  crates/re_space_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/re_types/definitions/rerun/archetypes/arrows2d.fbs
  crates/re_types/definitions/rerun/archetypes/arrows3d.fbs
  crates/re_types/definitions/rerun/archetypes/boxes2d.fbs
  crates/re_types/definitions/rerun/archetypes/boxes3d.fbs
  crates/re_types/definitions/rerun/archetypes/line_strips2d.fbs
  crates/re_types/definitions/rerun/archetypes/line_strips3d.fbs
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/definitions/rerun/archetypes/points3d.fbs
  crates/re_types/src/archetypes/arrows2d.rs
  crates/re_types/src/archetypes/arrows3d.rs
  crates/re_types/src/archetypes/boxes2d.rs
  crates/re_types/src/archetypes/boxes3d.rs
  crates/re_types/src/archetypes/line_strips2d.rs
  crates/re_types/src/archetypes/line_strips3d.rs
  crates/re_types/src/archetypes/points2d.rs
  crates/re_types/src/archetypes/points3d.rs
  crates/re_viewer_context/src/annotations.rs
  rerun_cpp/src/rerun/archetypes/arrows2d.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/boxes2d.hpp
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
Labels: 📺 re_viewer, include in changelog

#6742 Fix annotation context labels not showing in views
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/utilities/labels.rs
Labels: 🪳 bug, include in changelog

#6756 Update troubleshooting guide with graphics driver updating advice
  docs/content/getting-started/troubleshooting.md
Labels: 📖 documentation, include in changelog

#6759 Use "more" menu button instead of reset for view property ui
  crates/re_space_view/src/view_property_ui.rs
Labels: ui, exclude from changelog

#6753 Small UI tweaks: improved tooltips and collapsing header
  .typos.toml
  CHANGELOG.md
  Cargo.lock
  crates/re_blueprint_tree/src/blueprint_tree.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_time_panel/src/lib.rs
  crates/re_types/Cargo.toml
  crates/re_types/src/datatypes/angle_ext.rs
  crates/re_ui/src/section_collapsing_header.rs
  crates/re_viewer_context/src/item.rs
  examples/python/ocr/README.md
  scripts/lint.py
Labels: ui, exclude from changelog

#6764 Bring back display ui for `Name` and `Text` components
  crates/re_edit_ui/src/datatype_editors/mod.rs
  crates/re_edit_ui/src/datatype_editors/singleline_string.rs
  crates/re_edit_ui/src/lib.rs
Labels: ui, exclude from changelog

#6767 Optimize large point clouds
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
Labels: 📉 performance, include in changelog

#6765 Better linter for captialization
  ARCHITECTURE.md
  CHANGELOG.md
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  design/space_views.md
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/reference/roadmap.md
  examples/cpp/custom_collection_adapter/README.md
  examples/python/README.md
  examples/python/notebook/README.md
  examples/python/ocr/README.md
  rerun_cpp/arrow_cpp_install.md
  rerun_notebook/README.md
  scripts/lint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#6770 Fix `check_annotations` relying on random values
  tests/python/release_checklist/check_annotations.py
Labels: 🪳 bug, 🔨 testing, 😤 annoying, exclude from changelog

#6586 Query-time clears (latest-at only)
  crates/re_entity_db/src/entity_db.rs
  crates/re_entity_db/src/entity_tree.rs
  crates/re_entity_db/src/lib.rs
  crates/re_entity_db/tests/clear.rs
  crates/re_entity_db/tests/time_histograms.rs
  crates/re_query/src/latest_at/query.rs
  crates/re_query/src/range/query.rs
Labels: ⛃ re_datastore, 🔍 re_query, include in changelog, 🔩 data model

#6774 Fix display for `Text` and `Name` components
  crates/re_edit_ui/src/datatype_editors/singleline_string.rs
Labels: ui, exclude from changelog

#6588 Introduce `ChunkStore::drop_entity_path`
  crates/re_chunk_store/src/gc.rs
  crates/re_chunk_store/src/writes.rs
  crates/re_chunk_store/tests/gc.rs
  crates/re_entity_db/src/entity_db.rs
  tests/python/release_checklist/check_scalar_clears.py
Labels: ⛃ re_datastore, include in changelog

#6771 Use proper colormap popup for the Colormap component
  crates/re_edit_ui/src/lib.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
Labels: ui, exclude from changelog

#6587 New temporal batch APIs
  Cargo.lock
  crates/re_chunk/src/batcher.rs
  crates/re_chunk/src/chunk.rs
  crates/re_chunk/src/id.rs
  crates/re_chunk/src/transport.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/recording_stream.rs
  crates/rerun/src/sdk.rs
  docs/snippets/all/tutorials/temporal_batch.py
  docs/snippets/all/tutorials/temporal_batch.rs
  docs/snippets/snippets.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/temporal_batch.py
  rerun_py/src/arrow.rs
  rerun_py/src/python_bridge.rs
  tests/python/plot_dashboard_stress/main.py
  tests/python/test_temporal_batch/main.py
  tests/rust/test_temporal_batch/Cargo.toml
  tests/rust/test_temporal_batch/src/main.rs
Labels: 🐍 Python API, include in changelog

#6780 Fix typos
  clippy.toml
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/queueable_draw_data.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_viewer/src/app.rs
  crates/rerun/src/run.rs
  scripts/clippy_wasm/clippy.toml
Labels: exclude from changelog, :ship: CI

#6777 Dont forward datatype extensions beyond the FFI barrier
  rerun_py/src/arrow.rs
Labels: 🪳 bug, 🔨 testing, 🐍 Python API, include in changelog, 🪵 Log-API

#6779 Fix incorrect label placement for 3D arrows with origins
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
Labels: 🪳 bug, include in changelog

#6782 Docs: Update howto/notebook + READMEs
  docs/content/howto/notebook.md
  rerun_py/README.md
Labels: 📖 documentation, exclude from changelog

#6785 Update to egui 0.28.1
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#6786 Document support for `ogImageUrl` in docs frontmatter
  docs/README.md
Labels: 📖 documentation, exclude from changelog

#6783 Use overrides & defaults in nuscenes example
  examples/python/nuscenes_dataset/nuscenes_dataset/__main__.py
Labels: examples, include in changelog

#6781 Use the blueprint API for styling in the `plots` example
  examples/python/plots/plots.py
Labels: 🐍 Python API, examples, include in changelog

#6789 Removed unused `PrimitiveCounter` system
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
Labels: 🚜 refactor, exclude from changelog

#6790 Fix confusing naming in line strip textures
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/src/renderer/lines.rs
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#6797 Use "N-dimensional" instead of "rank-N" in docstrings and error messages
  crates/re_types/definitions/rerun/archetypes/bar_chart.fbs
  crates/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/re_types/src/archetypes/bar_chart.rs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/archetypes/image.rs
  crates/re_types/src/archetypes/segmentation_image.rs
  rerun_cpp/src/rerun/archetypes/bar_chart.hpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/depth_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/image_ext.cpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image_ext.cpp
  rerun_cpp/tests/archetypes/image.cpp
  rerun_cpp/tests/archetypes/segmentation_and_depth_image.cpp
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
Labels: 📖 documentation, 🌊 C++ API, include in changelog, 🪵 Log-API

#6799 Remove weekly crate alpha builds
  .github/workflows/auto_release_crates.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#6792 Fix nightly build
  .github/workflows/on_pr_comment.yml
  .github/workflows/release.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_run_notebook.yml
  Cargo.toml
  scripts/ci/check_speculative_links.py
Labels: exclude from changelog, :ship: CI

#6803 Update workflow permissions
  .github/workflows/labels.yml
  .github/workflows/nightly.yml
  .github/workflows/on_pr_comment.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_pull_request_contrib.yml
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_publish_rerun_c.yml
  .github/workflows/reusable_publish_rerun_cli.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_update_pr_body.yml
  .github/workflows/reusable_upload_examples.yml
  .github/workflows/reusable_upload_web.yml
Labels: exclude from changelog, :ship: CI

#6802 Fix release checklist readmes
  tests/python/release_checklist/check_draw_order.py
  tests/python/release_checklist/check_heuristics_2d.py
  tests/python/release_checklist/check_plot_overrides.py
Labels: exclude from changelog

#6778 Refactor `edit_ui`
  Cargo.lock
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_edit_ui/Cargo.toml
  crates/re_edit_ui/src/color.rs
  crates/re_edit_ui/src/datatype_editors/bool_toggle.rs
  crates/re_edit_ui/src/datatype_editors/enum_combobox.rs
  crates/re_edit_ui/src/datatype_editors/float_drag.rs
  crates/re_edit_ui/src/datatype_editors/mod.rs
  crates/re_edit_ui/src/datatype_editors/singleline_string.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/marker_shape.rs
  crates/re_edit_ui/src/material.rs
  crates/re_edit_ui/src/radius.rs
  crates/re_edit_ui/src/range1d.rs
  crates/re_edit_ui/src/visual_bounds2d.rs
  crates/re_types/src/datatypes/quaternion_ext.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/maybe_mut_ref.rs
  tests/python/release_checklist/check_1d_tensor_data.py
  tests/python/release_checklist/check_all_components_ui.py
  tests/python/release_checklist/check_annotations.py
  tests/python/release_checklist/check_container_hierarchy.py
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
  tests/python/release_checklist/check_context_menu_collapse_expand_all.py
  tests/python/release_checklist/check_context_menu_invalid_sub_container.py
  tests/python/release_checklist/check_context_menu_multi_selection.py
  tests/python/release_checklist/check_context_menu_single_selection.py
  tests/python/release_checklist/check_context_menu_single_selection_blueprint_tree.py
  tests/python/release_checklist/check_context_menu_suggested_origin.py
  tests/python/release_checklist/check_draw_order.py
  tests/python/release_checklist/check_focus.py
  tests/python/release_checklist/check_heuristics_2d.py
  tests/python/release_checklist/check_heuristics_mixed_2d_and_3d.py
  tests/python/release_checklist/check_heuristics_mixed_all_root.py
  tests/python/release_checklist/check_hover_select_reset.py
  tests/python/release_checklist/check_mono_entity_views.py
  tests/python/release_checklist/check_notebook.py
  tests/python/release_checklist/check_out_of_tree_data_results.py
  tests/python/release_checklist/check_overrides_2d.py
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/release_checklist/check_plot_overrides.py
  tests/python/release_checklist/check_scalar_clears.py
  tests/python/release_checklist/check_static_components_ui.py
Labels: ui, 🚜 refactor, exclude from changelog

#6805 Add videos to major releases in `CHANGELOG.md`
  CHANGELOG.md
Labels: 📖 documentation, ⛴ release, exclude from changelog

#6806 Fix query benchmarks overflow
  crates/re_query/benches/latest_at.rs
Labels: 🔨 testing, ⛴ release, exclude from changelog

#6804 Add blueprint backwards compat check
  tests/python/release_checklist/check_blueprint_bw_compat.py
  tests/python/release_checklist/check_notebook.py
Labels: 🔨 testing, exclude from changelog

#6791 Improve bounding box based heuristics
  crates/re_space_view_spatial/src/scene_bounding_boxes.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/view_2d.rs
  crates/re_space_view_spatial/src/view_2d_properties.rs
  crates/re_space_view_spatial/src/view_3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_types/src/datatypes/range1d_ext.rs
Labels: 📺 re_viewer, include in changelog

#6809 Delete unused methods from `DataResult` and make `PropertyOverrides` non-optional
  crates/re_selection_panel/src/visible_time_range_ui.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_space_view/src/query.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport_blueprint/src/space_view.rs
  crates/re_viewport_blueprint/src/space_view_contents.rs
Labels: 🚜 refactor, exclude from changelog

#6822 Fix permissions for `full-check` job
  .github/workflows/on_pr_comment.yml
Labels: exclude from changelog, :ship: CI

#6834 Try fix spurious C++ compilation failures on nightly build
  pixi.lock
  pixi.toml
Labels: exclude from changelog, :ship: CI

#6827 Make default notebook widget size smaller and configurable
  examples/python/notebook/cube.ipynb
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: exclude from changelog

#6838 Fix linkchecker: proper allow-list of stackoverflow.com
  lychee.toml
Labels: :ship: CI

#6839 Fix links to crates
  crates/utils/re_analytics/README.md
  crates/utils/re_analytics/src/event.rs
  crates/viewer/re_viewer/src/viewer_analytics/mod.rs
  docs/content/howto/extend/extend-ui.md
  lychee.toml
Labels: exclude from changelog, :ship: CI

#6840 Add breaking changes to the top of changelog and migration guides
  CHANGELOG.md
  RELEASES.md
  docs/content/reference/migration/migration-0-17.md
  scripts/generate_changelog.py
  scripts/lint.py
Labels: 📖 documentation, ⛴ release, exclude from changelog

#6833 CI: Fix nightly build
  .github/workflows/release.yml
  pixi.lock
  rerun_cpp/src/rerun/c/rerun.h
  rerun_js/scripts/version.mjs
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer/package.json
  rerun_notebook/pyproject.toml
  rerun_py/pyproject.toml
Labels: exclude from changelog, :ship: CI

#6845 pixi: Add missing feature "cpp" to "wheel-test" environment
  .github/workflows/contrib_checks.yml
  .github/workflows/cpp_matrix_full.json
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_deploy_docs.yml
  BUILD.md
  CONTRIBUTING.md
  docs/snippets/README.md
  examples/cpp/README.md
  pixi.lock
  pixi.toml
  rerun_cpp/docs/writing_docs.md
  tests/cpp/log_benchmark/main.cpp
  tests/cpp/plot_dashboard_stress/main.cpp
Labels: exclude from changelog, :ship: CI

#6855 Fix text log/document view icons
  crates/viewer/re_ui/src/icons.rs
Labels: 🪳 bug, ui, include in changelog

#6851 New code snippet for Transform3D demonstrating an animated hierarchy
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/src/archetypes/transform3d.rs
  docs/content/reference/types/archetypes/transform3d.md
  docs/snippets/all/archetypes/transform3d_hierarchy.cpp
  docs/snippets/all/archetypes/transform3d_hierarchy.py
  docs/snippets/all/archetypes/transform3d_hierarchy.rs
  docs/snippets/compare_snippet_output.py
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  tests/python/test_api/test_api.py
Labels: 📖 documentation, include in changelog

#6868 Recommend install rerun-cli with `--locked`
  CHANGELOG.md
  README.md
  crates/build/re_build_tools/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/re_sdk/src/web_viewer.rs
  crates/top/rerun-cli/Cargo.toml
  crates/top/rerun-cli/README.md
  crates/top/rerun/README.md
  crates/top/rerun/src/lib.rs
  crates/viewer/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/viewer/re_viewer/data/quick_start_guides/cpp_spawn.md
  docs/content/getting-started/installing-viewer.md
Labels: 📖 documentation, 🦀 Rust API, 🧑‍💻 dev experience, include in changelog

#6864 Fix/cleanup our pixi tasks
  docs/snippets/README.md
  examples/python/README.md
  pixi.lock
  pixi.toml
  rerun_py/README.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#6857 `Chunk` concatenation primitives
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/util.rs
Labels: ⛃ re_datastore, 📉 performance, include in changelog

#6858 Implement on-write `Chunk` compaction
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/entity_tree.rs
  crates/store/re_entity_db/src/time_histogram_per_timeline.rs
  crates/store/re_log_types/src/time_point/time_int.rs
  crates/store/re_query/benches/latest_at.rs
  crates/store/re_query/tests/latest_at.rs
  crates/store/re_query/tests/range.rs
Labels: ⛃ re_datastore, 📉 performance, include in changelog

#6859 Display compaction information in the recording UI
  Cargo.lock
  crates/store/re_chunk_store/src/store.rs
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/entity_db.rs
Labels: ui, include in changelog

#6860 CLI command for compacting recordings
  Cargo.lock
  crates/top/rerun/src/run.rs
  crates/viewer/re_data_ui/src/entity_db.rs
Labels: 🧑‍💻 dev experience, 📉 performance, include in changelog, CLI

#6861 CLI refactor: introduce `rerun rrd <compare|print|compact>` subscommand
  crates/top/rerun/src/run.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  rerun_py/tests/unit/test_binary_stream.py
  scripts/roundtrip_utils.py
Labels: 🚜 refactor, include in changelog, CLI

#6862 CLI command for merging recordings
  crates/build/re_build_info/src/crate_version.rs
  crates/top/rerun/src/run.rs
Labels: 🧑‍💻 dev experience, ⛃ re_datastore, 📉 performance, do-not-merge, include in changelog, CLI

#6867 Update to glam 0.28 & replace `macaw` with fork `re_math`
  Cargo.lock
  Cargo.toml
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/importer/mod.rs
  crates/viewer/re_renderer/src/line_drawable_builder.rs
  crates/viewer/re_renderer/src/renderer/depth_cloud.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_renderer/src/view_builder.rs
  crates/viewer/re_renderer_examples/2d.rs
  crates/viewer/re_renderer_examples/Cargo.toml
  crates/viewer/re_renderer_examples/depth_cloud.rs
  crates/viewer/re_renderer_examples/depth_offset.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_renderer_examples/outlines.rs
  crates/viewer/re_renderer_examples/picking.rs
  crates/viewer/re_space_view_spatial/Cargo.toml
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_space_view_spatial/src/eye.rs
  crates/viewer/re_space_view_spatial/src/mesh_loader.rs
  crates/viewer/re_space_view_spatial/src/picking.rs
  crates/viewer/re_space_view_spatial/src/scene_bounding_boxes.rs
  crates/viewer/re_space_view_spatial/src/space_camera_3d.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/spatial_view_visualizer.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
  examples/rust/minimal_options/Cargo.toml
  examples/rust/objectron/Cargo.toml
  scripts/lint.py
Labels: dependencies, include in changelog

#6872 Fix compaction election process not ignoring incompatible chunks
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, ⛃ re_datastore, 📺 re_viewer, exclude from changelog

#6854 rust-analyzer: configuration overhaul
  .vscode/settings.json
Labels: 🧑‍💻 dev experience, ⏱ build-times, exclude from changelog

#6875 Implement `Chunk::cell`
  crates/store/re_chunk/src/iter.rs
Labels: ⛃ re_datastore, include in changelog

#6877 Implement `Chunk::iter_indices`
  crates/store/re_chunk/src/iter.rs
Labels: ⛃ re_datastore, include in changelog

#6870 Optimize data clamping in spatial view
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/labels.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#6873 Add LeRobot example link
  examples/manifest.toml
  examples/python/lerobot/README.md
Labels: examples, include in changelog

#6878 Use markdown for the view help widget
  crates/viewer/re_space_view/src/controls.rs
  crates/viewer/re_space_view_bar_chart/src/space_view_class.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/view_2d.rs
  crates/viewer/re_space_view_spatial/src/view_3d.rs
  crates/viewer/re_space_view_tensor/src/space_view_class.rs
  crates/viewer/re_space_view_text_document/src/space_view_class.rs
  crates/viewer/re_space_view_text_log/src/space_view_class.rs
  crates/viewer/re_space_view_time_series/src/space_view_class.rs
  crates/viewer/re_ui/src/layout_job_builder.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/markdown_utils.rs
  crates/viewer/re_viewer_context/src/space_view/space_view_class.rs
  crates/viewer/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/viewer/re_viewport/src/viewport.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: enhancement, ui, include in changelog

#6853 Add `Ellipsoids` archetype.
  Cargo.lock
  Cargo.toml
  crates/store/re_types/definitions/rerun/archetypes.fbs
  crates/store/re_types/definitions/rerun/archetypes/ellipsoids.fbs
  crates/store/re_types/src/archetypes/.gitattributes
  crates/store/re_types/src/archetypes/ellipsoids.rs
  crates/store/re_types/src/archetypes/ellipsoids_ext.rs
  crates/store/re_types/src/archetypes/mod.rs
  crates/store/re_types/src/components/half_size3d_ext.rs
  crates/viewer/re_space_view_spatial/Cargo.toml
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_spatial/src/proc_mesh.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/.gitattributes
  docs/content/reference/types/archetypes/ellipsoids.md
  docs/content/reference/types/components/class_id.md
  docs/content/reference/types/components/color.md
  docs/content/reference/types/components/half_size3d.md
  docs/content/reference/types/components/position3d.md
  docs/content/reference/types/components/radius.md
  docs/content/reference/types/components/rotation3d.md
  docs/content/reference/types/components/text.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  docs/snippets/all/archetypes/ellipsoid_batch.cpp
  docs/snippets/all/archetypes/ellipsoid_batch.py
  docs/snippets/all/archetypes/ellipsoid_batch.rs
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/.gitattributes
  rerun_cpp/src/rerun/archetypes/ellipsoids.cpp
  rerun_cpp/src/rerun/archetypes/ellipsoids.hpp
  rerun_cpp/src/rerun/archetypes/ellipsoids_ext.cpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids_ext.py
Labels: 📺 re_viewer, 🍏 primitives, include in changelog, 🪵 Log-API

#6882 [1/4] Python SDK: Rename `ImageEncoded` to `ImageEncodedHelper`
  CHANGELOG.md
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  docs/content/reference/migration/migration-0-18.md
  docs/snippets/all/archetypes/image_advanced.py
  examples/python/nuscenes_dataset/README.md
  examples/python/nuscenes_dataset/nuscenes_dataset/__main__.py
  examples/python/nv12/nv12.py
  examples/python/objectron/README.md
  examples/python/objectron/objectron/__main__.py
  examples/python/open_photogrammetry_format/open_photogrammetry_format.py
  examples/python/structure_from_motion/structure_from_motion/__main__.py
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/tests/unit/test_image.py
  rerun_py/tests/unit/test_image_encoded.py
  tests/python/chroma_downsample_image/main.py
Labels: 🐍 Python API, include in changelog

#6871 Improve navigation between entity and data results in the selection panel
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: ui, include in changelog

#6879 `ChunkStore`: implement new component-less indices and APIs
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_chunk_store/tests/snapshots/memory_test__scalars_on_one_timeline_new.snap
Labels: ⛃ re_datastore, 🔍 re_query, 📉 performance, include in changelog

#6884 [4/4] Remove `TensorBuffer::JPEG`, `DecodedTensor`, `TensorDecodeCache`
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_types/Cargo.toml
  crates/store/re_types/definitions/rerun/components/tensor_data.fbs
  crates/store/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/store/re_types/definitions/rerun/datatypes/tensor_data.fbs
  crates/store/re_types/src/archetypes/asset3d_ext.rs
  crates/store/re_types/src/archetypes/image_encoded_ext.rs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/archetypes/tensor_ext.rs
  crates/store/re_types/src/components/tensor_data.rs
  crates/store/re_types/src/datatypes/tensor_buffer.rs
  crates/store/re_types/src/datatypes/tensor_buffer_ext.rs
  crates/store/re_types/src/datatypes/tensor_data.rs
  crates/store/re_types/src/datatypes/tensor_data_ext.rs
  crates/store/re_types/src/tensor_data.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_space_view_bar_chart/src/space_view_class.rs
  crates/viewer/re_space_view_spatial/src/pickable_image.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/image_encoded.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/viewer/re_space_view_tensor/src/space_view_class.rs
  crates/viewer/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/viewer/re_space_view_tensor/src/visualizer_system.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/tensor/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/tensor/mod.rs
  crates/viewer/re_viewer_context/src/tensor/tensor_decode_cache.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/components/tensor_data.md
  docs/content/reference/types/datatypes/tensor_buffer.md
  docs/content/reference/types/datatypes/tensor_data.md
  rerun_cpp/src/rerun/components/tensor_data.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.cpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer_ext.cpp
  rerun_cpp/src/rerun/datatypes/tensor_data.hpp
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/components/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
Labels: 🦀 Rust API, include in changelog

#6847 Chunkify time panel data density graphs
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/re_sdk/src/spawn.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer_context/src/app_options.rs
  rerun_py/src/python_bridge.rs
  tests/rust/test_data_density_graph/Cargo.toml
  tests/rust/test_data_density_graph/src/main.rs
Labels: 📺 re_viewer, 📉 performance, 🚜 refactor, exclude from changelog

#6895 Add missing props to React package
  rerun_js/web-viewer-react/index.js
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer/index.ts
Labels: 🕸️ web, include in changelog

#6887 Respect 0.0 for start and end boundaries of scalar axis
  crates/viewer/re_space_view_time_series/src/space_view_class.rs
Labels: 🪳 bug, include in changelog, 📈 plot

#6900 Try to fix `nightly` builds
  Cargo.lock
  crates/build/re_dev_tools/src/build_examples/example.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/run.rs
  crates/viewer/re_space_view_dataframe/src/table_ui.rs
  examples/README.md
  examples/python/segment_anything_model/README.md
Labels: exclude from changelog, :ship: CI

#6903 Don't lint comments inside `[metadata]` frontmatter
  scripts/lint.py
Labels: :ship: CI

#6894 Make clamped component data distinguishable in the "latest at" table
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
Labels: ui, include in changelog

#6892 Add Scale3D component
  CMakeLists.txt
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/scale3d.fbs
  crates/store/re_types/definitions/rerun/datatypes/mat3x3.fbs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/transform3d_ext.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/scale3d.rs
  crates/store/re_types/src/components/scale3d_ext.rs
  crates/store/re_types/src/datatypes/vec3d_ext.rs
  crates/store/re_types/tests/transform3d.rs
  crates/top/rerun/src/sdk.rs
  crates/viewer/re_edit_ui/src/lib.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/archetypes/transform3d.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/scale3d.md
  docs/content/reference/types/datatypes/vec3d.md
  docs/snippets/all/archetypes/transform3d_axes.cpp
  docs/snippets/all/archetypes/transform3d_hierarchy.cpp
  docs/snippets/all/archetypes/transform3d_simple.cpp
  lychee.toml
  rerun_cpp/src/rerun/archetypes/transform3d.cpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/scale3d.hpp
  rerun_cpp/src/rerun/components/scale3d_ext.cpp
  rerun_cpp/src/rerun/components/translation3d.hpp
  rerun_cpp/src/rerun/components/translation3d_ext.cpp
  rerun_cpp/tests/archetypes/transform3d.cpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/scale3d.py
  rerun_py/rerun_sdk/rerun/components/scale3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3_ext.py
  rerun_py/tests/unit/test_transform3d.py
  tests/cpp/roundtrips/transform3d/main.cpp
  tests/rust/roundtrips/transform3d/src/main.rs
Labels: 🚜 refactor, 🍏 primitives, include in changelog, 🪵 Log-API

#6911 Separate C++ example build from snippet compare in order to set pixi environment consistently
  .github/workflows/reusable_test_wheels.yml
Labels: exclude from changelog, :ship: CI

#6908 Scroll dataframe view to focused item
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
  crates/viewer/re_space_view_dataframe/src/table_ui.rs
  crates/viewer/re_space_view_dataframe/src/time_range_table.rs
Labels: enhancement, ui, include in changelog

#6907 Link checker improvements
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_checks.yml
  lychee.toml
Labels: exclude from changelog, :ship: CI

#6914 [C++] Fix resetting time destroying recording stream
  crates/top/rerun_c/src/lib.rs
  rerun_cpp/tests/recording_stream.cpp
Labels: 🪳 bug, 🌊 C++ API, include in changelog

#6912 Add example for different data per timeline on `Events and Timelines` doc page
  docs/content/concepts/timelines.md
  docs/snippets/all/concepts/different_data_per_timeline.cpp
  docs/snippets/all/concepts/different_data_per_timeline.py
  docs/snippets/all/concepts/different_data_per_timeline.rs
  docs/snippets/snippets.toml
Labels: 📖 documentation, include in changelog

#6916 Angle datatype stores now only radians
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/build/re_types_builder/src/lib.rs
  crates/store/re_types/definitions/cpp/attributes.fbs
  crates/store/re_types/definitions/rerun/datatypes/angle.fbs
  crates/store/re_types/src/archetypes/boxes3d.rs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/datatypes/angle.rs
  crates/store/re_types/src/datatypes/angle_ext.rs
  crates/store/re_types/src/datatypes/rotation_axis_angle.rs
  crates/store/re_types/tests/asset3d.rs
  crates/store/re_types/tests/box3d.rs
  crates/store/re_types/tests/mint_conversions.rs
  crates/store/re_types/tests/transform3d.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/angle.md
  docs/snippets/all/archetypes/box3d_batch.rs
  docs/snippets/all/archetypes/transform3d_axes.rs
  docs/snippets/all/archetypes/transform3d_hierarchy.rs
  docs/snippets/all/archetypes/transform3d_simple.rs
  docs/snippets/snippets.toml
  examples/rust/dna/src/main.rs
  rerun_cpp/src/rerun/datatypes/angle.cpp
  rerun_cpp/src/rerun/datatypes/angle.hpp
  rerun_cpp/src/rerun/datatypes/angle_ext.cpp
  rerun_cpp/src/rerun/datatypes/rotation_axis_angle.cpp
  rerun_py/rerun_sdk/rerun/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/datatypes/angle_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d.py
  rerun_py/rerun_sdk/rerun/datatypes/translation_rotation_scale3d.py
  rerun_py/tests/unit/test_transform3d.py
  tests/rust/roundtrips/boxes3d/src/main.rs
  tests/rust/roundtrips/transform3d/src/main.rs
  tests/rust/test_api/src/main.rs
  tests/rust/test_data_density_graph/src/main.rs
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#6926 Disable a snippet test that fails on CI
  docs/snippets/snippets.toml
Labels: exclude from changelog, :ship: CI

#6917 Provide view state to `SpaceViewClass::default_query_range()`
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_space_view_time_series/src/space_view_class.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/space_view/space_view_class.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
  crates/viewer/re_viewport_blueprint/src/space_view_contents.rs
Labels: 🚜 refactor, exclude from changelog

#6928 Port `SegmentationImage` to the new image archetype style
  CHANGELOG.md
  crates/store/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/store/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/store/re_types/definitions/rerun/components/color_model.fbs
  crates/store/re_types/definitions/rerun/components/resolution2d.fbs
  crates/store/re_types/src/archetypes/depth_image.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/archetypes/segmentation_image_ext.rs
  crates/store/re_types/tests/segmentation_image.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/archetypes/segmentation_image.md
  docs/content/reference/types/components/blob.md
  docs/content/reference/types/components/channel_data_type.md
  docs/content/reference/types/components/color_model.md
  docs/content/reference/types/components/resolution2d.md
  docs/content/reference/types/components/tensor_data.md
  docs/content/reference/types/datatypes/uvec2d.md
  docs/snippets/all/archetypes/annotation_context_segmentation.cpp
  docs/snippets/all/archetypes/segmentation_image_simple.cpp
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/depth_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.cpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image_ext.cpp
  rerun_cpp/tests/archetypes/segmentation_and_depth_image.cpp
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image_ext.py
  rerun_py/tests/unit/test_segmentation_image.py
  tests/cpp/roundtrips/segmentation_image/main.cpp
  tests/python/roundtrips/segmentation_image/main.py
Labels: 🚜 refactor, include in changelog, 🪵 Log-API

#6905 Small chunk heuristics for data density graph
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/viewer/re_time_panel/Cargo.toml
  crates/viewer/re_time_panel/benches/bench_density_graph.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/src/time_ranges_ui.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  tests/rust/test_data_density_graph/src/main.rs
Labels: 📺 re_viewer, exclude from changelog, heuristics

#6936 Fix `Chunk`'s counting routines checking the wrong variable
  crates/store/re_chunk/src/chunk.rs
  crates/viewer/re_time_panel/benches/bench_density_graph.rs
Labels: 🪳 bug, exclude from changelog

#6937 Additional pixi-environment-related CI fixes
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  pixi.lock
  pixi.toml
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/pixi_install_wheel.py
Labels: exclude from changelog, :ship: CI

#6935 Fix main ci issues
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  crates/top/rerun/src/run.rs
  docs/snippets/compare_snippet_output.py
  docs/snippets/snippets.toml
  examples/python/arkit_scenes/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/nuscenes_dataset/README.md
  examples/python/segment_anything_model/README.md
  examples/python/structure_from_motion/README.md
  pixi.lock
  pixi.toml
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/pixi_install_wheel.py
Labels: exclude from changelog, :ship: CI

#6941 Update setup-pixi to 0.8.1
  .github/workflows/auto_approve.yml
  .github/workflows/checkboxes.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/on_pull_request_target_contrib.yml
  .github/workflows/on_push_docs.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_checks_python.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pr_summary.yml
  .github/workflows/reusable_publish_js.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_update_pr_body.yml
Labels: exclude from changelog, :ship: CI

#6939 Fix nasty compaction threshold bug
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, ⛃ re_datastore, exclude from changelog

#6946 Mitigate hidden opencv dependency conflicts in pixi
  examples/python/detect_and_track_objects/pyproject.toml
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, examples, exclude from changelog, :ship: CI

#6950 Fix missing early exit in `sorted_by_timeline_if_unsorted`
  crates/store/re_chunk/src/shuffle.rs
Labels: 🪳 bug, 📉 performance, exclude from changelog

#6940 Compaction-aware store events
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_query/src/cache.rs
Labels: enhancement, ⛃ re_datastore, 📉 performance, include in changelog

#6955 Fix outdated use of view coordinates in `Spaces and Transforms` doc page
  docs/content/concepts/spaces-and-transforms.md
Labels: 🪳 bug, 📖 documentation, include in changelog

#6929 Add components for `RotationAxisAngle` and `RotationQuat`
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/rotation_axis_angle.fbs
  crates/store/re_types/definitions/rerun/components/rotation_quat.fbs
  crates/store/re_types/definitions/rerun/datatypes/quaternion.fbs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/transform3d_ext.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/rotation_axis_angle.rs
  crates/store/re_types/src/components/rotation_axis_angle_ext.rs
  crates/store/re_types/src/components/rotation_quat.rs
  crates/store/re_types/src/components/rotation_quat_ext.rs
  crates/store/re_types/src/datatypes/quaternion.rs
  crates/store/re_types/src/datatypes/rotation3d_ext.rs
  crates/store/re_types/src/datatypes/rotation_axis_angle_ext.rs
  crates/store/re_types/src/lib.rs
  crates/store/re_types/src/rotation3d.rs
  crates/store/re_types/tests/transform3d.rs
  crates/top/rerun/src/sdk.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_time_panel/benches/bench_density_graph.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/archetypes/transform3d.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/rotation_axis_angle.md
  docs/content/reference/types/components/rotation_quat.md
  docs/content/reference/types/datatypes/quaternion.md
  docs/content/reference/types/datatypes/rotation_axis_angle.md
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.cpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/rotation_axis_angle.hpp
  rerun_cpp/src/rerun/components/rotation_quat.hpp
  rerun_cpp/src/rerun/rotation3d.hpp
  rerun_cpp/tests/archetypes/transform3d.cpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/components/rotation_quat.py
  rerun_py/tests/unit/test_expected_warnings.py
  rerun_py/tests/unit/test_transform3d.py
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#6944 Introduce `TransformRelation` component
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/channel_data_type.fbs
  crates/store/re_types/definitions/rerun/components/transform_relation.fbs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/transform3d_ext.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/transform_relation.rs
  crates/store/re_types/tests/transform3d.rs
  crates/top/rerun/src/sdk.rs
  crates/viewer/re_edit_ui/src/datatype_editors/enum_combobox.rs
  crates/viewer/re_edit_ui/src/lib.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/archetypes/transform3d.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/channel_data_type.md
  docs/content/reference/types/components/color_model.md
  docs/content/reference/types/components/transform3d.md
  docs/content/reference/types/components/transform_relation.md
  docs/snippets/all/archetypes/transform3d_axes.cpp
  docs/snippets/all/archetypes/transform3d_hierarchy.cpp
  docs/snippets/all/archetypes/transform3d_hierarchy.rs
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.cpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/transform_relation.cpp
  rerun_cpp/src/rerun/components/transform_relation.hpp
  rerun_cpp/tests/archetypes/transform3d.cpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/transform_relation.py
  rerun_py/tests/unit/test_transform3d.py
  tests/cpp/roundtrips/transform3d/main.cpp
  tests/rust/roundtrips/transform3d/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#6960 fix pixi_install_wheel.py for windows & linux-aarch64 not listed in pixi env
  pixi.lock
  pixi.toml
  scripts/ci/pixi_install_wheel.py
Labels: exclude from changelog, :ship: CI

#6956 Add troubleshooting section to pip install issues with outdated pip version
  docs/content/getting-started/troubleshooting.md
Labels: 📖 documentation, include in changelog

#6934 Time panel chunkification
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/entity_tree.rs
  crates/store/re_entity_db/src/time_histogram_per_timeline.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/store/re_entity_db/tests/time_histograms.rs
  crates/viewer/re_context_menu/src/actions/collapse_expand_all.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/image_meaning.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/space_view_entity_picker.rs
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
  crates/viewer/re_space_view_dataframe/src/time_range_table.rs
  crates/viewer/re_space_view_dataframe/src/utils.rs
  crates/viewer/re_space_view_spatial/src/view_2d.rs
  crates/viewer/re_space_view_spatial/src/view_3d.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer_context/src/app_options.rs
  crates/viewer/re_viewer_context/src/item.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
  crates/viewer/re_viewport_blueprint/src/space_view_contents.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 📺 re_viewer, include in changelog

#6964 Fix nightly notebook test
  .github/workflows/reusable_run_notebook.yml
  scripts/ci/pixi_install_wheel.py
Labels: exclude from changelog, :ship: CI

#6972 Fix multi rrd on `app.rerun.io`
  web_viewer/index.html
Labels: 🕸️ web, include in changelog

#6967 Fix zero length transform axis having an effect bounding box used for heuristics etc.
  crates/viewer/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#6975 Nightly ci fixes
  .github/workflows/nightly.yml
  crates/store/re_types/definitions/rerun/datatypes/angle.fbs
  docs/content/reference/types/datatypes/angle.md
Labels: exclude from changelog, :ship: CI

#6953 Add optional solid/filled (triangle mesh) rendering to `Boxes3D` and `Ellipsoids`.
  .github/workflows/contrib_rerun_py.yml
  crates/store/re_types/definitions/rerun/archetypes/boxes3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/ellipsoids.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/fill_mode.fbs
  crates/store/re_types/src/archetypes/boxes3d.rs
  crates/store/re_types/src/archetypes/ellipsoids.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/fill_mode.rs
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/tests/box3d.rs
  crates/top/rerun/src/sdk.rs
  crates/viewer/re_edit_ui/src/lib.rs
  crates/viewer/re_space_view_spatial/src/proc_mesh.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/archetypes/boxes3d.md
  docs/content/reference/types/archetypes/ellipsoids.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/fill_mode.md
  docs/snippets/all/archetypes/box3d_batch.cpp
  docs/snippets/all/archetypes/box3d_batch.py
  docs/snippets/all/archetypes/box3d_batch.rs
  docs/snippets/all/archetypes/ellipsoid_batch.cpp
  docs/snippets/all/archetypes/ellipsoid_batch.py
  docs/snippets/all/archetypes/ellipsoid_batch.rs
  rerun_cpp/src/rerun.hpp
  rerun_cpp/src/rerun/archetypes/boxes3d.cpp
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/ellipsoids.cpp
  rerun_cpp/src/rerun/archetypes/ellipsoids.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/fill_mode.cpp
  rerun_cpp/src/rerun/components/fill_mode.hpp
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids_ext.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/fill_mode.py
Labels: 📺 re_viewer, 🍏 primitives, include in changelog

#6983 remove removed `re_data_store` from workspace deps
  Cargo.toml
Labels: exclude from changelog

#6980 Try a different approach to the unsolvable arm environment
  pixi.lock
  pixi.toml
Labels: exclude from changelog, :ship: CI

#6986 Use full commit sha for prerelease job
  .github/workflows/nightly.yml
  rerun_cpp/arrow_cpp_install.md
Labels: exclude from changelog, :ship: CI

#6987 Fix link in Robby Fischer example
  examples/rust/chess_robby_fischer/README.md
Labels: examples, exclude from changelog

#7002 mdlint: check for backticks in links
  scripts/ci/mdlint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#6991 add `python-tasks` to `examples` pixi environment
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#7003 Fix `Utf8List` serializer in python
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/utf8list_ext.py
Labels: 🪳 bug, 🐍 Python API, 🏹 arrow, exclude from changelog

#7004 Fix main
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/utf8list_ext.py
Labels: 🪳 bug, 🐍 Python API, exclude from changelog, :ship: CI

#6885 add depth compare example
  examples/manifest.toml
  examples/python/depth_compare/README.md
Labels: examples, include in changelog

#7005 Fix depth_compare video link
  examples/python/depth_compare/README.md
Labels: examples, exclude from changelog

#7001 Add cyan to yellow colormap
  crates/store/re_types/definitions/rerun/components/colormap.fbs
  crates/store/re_types/src/components/colormap.rs
  crates/viewer/re_renderer/shader/colormap.wgsl
  crates/viewer/re_renderer/src/colormap.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
  docs/content/reference/types/components/colormap.md
  rerun_cpp/src/rerun/components/colormap.cpp
  rerun_cpp/src/rerun/components/colormap.hpp
  rerun_py/rerun_sdk/rerun/components/colormap.py
Labels: 📺 re_viewer, 🍏 primitives, include in changelog

#7006 Define Transform3D again as a mono archetype
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/transform3d_ext.rs
  crates/store/re_types/tests/transform3d.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/archetypes/transform3d.md
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
  rerun_py/tests/unit/test_transform3d.py
Labels: 🍏 primitives, exclude from changelog

#6989 New and improved iteration APIs for `Chunk`s
  Cargo.lock
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/util.rs
  crates/viewer/re_space_view_dataframe/src/time_range_table.rs
Labels: 🧑‍💻 dev experience, 🔍 re_query, 📉 performance, do-not-merge, include in changelog

#6990 Introduce `Chunk` component-level helpers and `UnitChunk`
  crates/store/re_chunk/src/helpers.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/tests/correctness.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_query/src/latest_at/query.rs
  crates/store/re_query/src/range/query.rs
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
  crates/viewer/re_space_view_dataframe/src/utils.rs
Labels: 🧑‍💻 dev experience, 🔍 re_query, include in changelog

#6994 Integrate new data APIs with EntityDb/UI/Blueprint things
  Cargo.lock
  crates/store/re_entity_db/Cargo.toml
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/lib.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_space_view/Cargo.toml
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/query2.rs
  crates/viewer/re_space_view/src/results_ext2.rs
  crates/viewer/re_space_view/src/view_property_ui.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/view_3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_tensor/src/visualizer_system.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_blueprint.rs
  crates/viewer/re_viewer/src/blueprint/validation.rs
  crates/viewer/re_viewer/src/ui/memory_panel.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/annotations.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/item.rs
  crates/viewer/re_viewer_context/src/space_view/mod.rs
  crates/viewer/re_viewer_context/src/space_view/view_query.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
  crates/viewer/re_viewport_blueprint/src/space_view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 📺 re_viewer, 🔍 re_query, include in changelog

#7010 Fix `re_query2` links
  crates/store/re_query2/Cargo.toml
  crates/store/re_query2/README.md
Labels: exclude from changelog, :ship: CI
