Repository rerun-io/rerun, pull requests merged in 2024-06, with the labels that each got.

#6476 Fix rerun.io deploy
  .github/workflows/release.yml
  crates/re_dev_tools/src/build_examples/example.rs
Labels: 📖 documentation, exclude from changelog, :ship: CI

#6473 Don't use Title Casing for "entity"
  crates/re_data_store/README.md
  crates/re_data_store/src/lib.rs
  crates/re_selection_panel/src/query_range_ui.rs
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-in/rust.md
  docs/content/reference/viewer/blueprint.md
  docs/content/reference/viewer/selection.md
  docs/content/reference/viewer/timeline.md
Labels: exclude from changelog

#6477 Remove file that codegen brought back due to merge order
  crates/re_types/src/components/scalar_scattering.rs
Labels: exclude from changelog

#6478 Move case conversions to new crate `re_case`
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_case/Cargo.toml
  crates/re_case/README.md
  crates/re_case/src/lib.rs
  crates/re_types_builder/Cargo.toml
  crates/re_types_builder/src/codegen/cpp/includes.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
Labels: 🚜 refactor, exclude from changelog

#6474 Introduce a generic query helper that handles overrides
  Cargo.lock
  crates/re_query/src/range/results.rs
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/query.rs
  crates/re_space_view/src/results_ext.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
Labels: 📺 re_viewer, exclude from changelog

#6475 Add another helper for `latest_at_with_overrides` and use it for all spatial visualizers
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/query.rs
  crates/re_space_view/src/results_ext.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
Labels: 📺 re_viewer, exclude from changelog

#6479 View property querying with fallbacks
  Cargo.lock
  crates/re_selection_panel/src/override_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view/src/view_property_ui.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer_context/src/component_fallbacks.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport_blueprint/Cargo.toml
  crates/re_viewport_blueprint/src/lib.rs
  crates/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog

#6482 Add links to our docs in component tooltips
  Cargo.lock
  Cargo.toml
  crates/re_blueprint_tree/src/blueprint_tree.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_types_core/Cargo.toml
  crates/re_types_core/src/loggable.rs
  crates/re_ui/src/icons.rs
  crates/re_ui/src/list_item/mod.rs
Labels: 📖 documentation, ui, include in changelog

#6483 Pass view state through to visualizer systems
  crates/re_context_menu/src/actions/add_entities_to_new_space_view.rs
  crates/re_context_menu/src/actions/add_space_view.rs
  crates/re_selection_panel/src/override_ui.rs
  crates/re_selection_panel/src/query_range_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/space_view_entity_picker.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_dataframe/src/visualizer_system.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/view_states.rs
  crates/re_viewer_context/src/space_view/visualizer_system.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport_blueprint/src/space_view.rs
  crates/re_viewport_blueprint/src/viewport_blueprint.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 🚜 refactor, exclude from changelog

#6480 Background color settings uses new generic ui now
  crates/re_edit_ui/src/corner2d.rs
  crates/re_edit_ui/src/datatype_editors/enum_combobox.rs
  crates/re_edit_ui/src/datatype_editors/mod.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/view_2d.rs
  crates/re_space_view_spatial/src/view_2d_properties.rs
  crates/re_space_view_spatial/src/view_3d.rs
  crates/re_space_view_spatial/src/view_3d_properties.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/background.fbs
  crates/re_types/src/blueprint/archetypes/background.rs
  crates/re_types/src/blueprint/archetypes/background_ext.rs
  crates/re_types/src/blueprint/archetypes/mod.rs
  crates/re_viewport_blueprint/src/lib.rs
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  rerun_cpp/src/rerun/blueprint/archetypes/background.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/background.py
Labels: 📺 re_viewer, include in changelog

#6485 TimeSeries y-range is now tightly synced with plot view & uses new generic ui
  crates/re_edit_ui/src/datatype_editors/bool_toggle.rs
  crates/re_edit_ui/src/datatype_editors/mod.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/range1d.rs
  crates/re_query/src/latest_at/to_archetype/scalar_axis.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/scalar_axis.fbs
  crates/re_types/src/blueprint/archetypes/scalar_axis.rs
  docs/content/reference/types/views/time_series_view.md
  docs/snippets/all/views/timeseries.py
  rerun_cpp/src/rerun/blueprint/archetypes/scalar_axis.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/scalar_axis.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/scalar_axis.py
  rerun_py/rerun_sdk/rerun/blueprint/views/time_series_view.py
  rerun_py/tests/unit/test_scalar_axis.py
Labels: 📺 re_viewer, 🟦 blueprint, include in changelog

#6309 Use `list_item` for the component list in `InstancePath::data_ui`
  Cargo.lock
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_data_ui/src/transform3d.rs
  crates/re_ui/src/list_item/scope.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/component_ui_registry.rs
  scripts/ci/rust_checks.py
Labels: ui, include in changelog

#6492 Allow editing visual bounds from ui
  Cargo.lock
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/editors/mod.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/visual_bounds2d.rs
  crates/re_query/src/latest_at/helpers.rs
  crates/re_query/src/latest_at/results.rs
  crates/re_selection_panel/src/override_ui.rs
  crates/re_selection_panel/src/query_range_ui.rs
  crates/re_space_view/src/view_property_ui.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/view_2d.rs
  crates/re_space_view_spatial/src/view_2d_properties.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/visual_bounds2d.fbs
  crates/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/re_types/src/datatypes/range1d_ext.rs
  crates/re_types/src/datatypes/range2d_ext.rs
  crates/re_types_core/src/archetype.rs
  crates/re_types_core/src/lib.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewport_blueprint/src/lib.rs
  crates/re_viewport_blueprint/src/view_properties.rs
Labels: ui, 📺 re_viewer, include in changelog

#6500 Cleanup view property querying
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/src/blueprint/archetypes/visible_time_ranges_ext.rs
  crates/re_viewport_blueprint/src/lib.rs
  crates/re_viewport_blueprint/src/space_view.rs
  crates/re_viewport_blueprint/src/space_view_contents.rs
  crates/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog

#6501 Remove to archetype & archetype queries
  Cargo.lock
  crates/re_entity_db/Cargo.toml
  crates/re_entity_db/src/entity_db.rs
  crates/re_query/Cargo.toml
  crates/re_query/examples/latest_at_archetype.rs
  crates/re_query/src/latest_at/mod.rs
  crates/re_query/src/latest_at/results.rs
  crates/re_query/src/latest_at/to_archetype/.gitattributes
  crates/re_query/src/latest_at/to_archetype/annotation_context.rs
  crates/re_query/src/latest_at/to_archetype/arrows2d.rs
  crates/re_query/src/latest_at/to_archetype/arrows3d.rs
  crates/re_query/src/latest_at/to_archetype/asset3d.rs
  crates/re_query/src/latest_at/to_archetype/background.rs
  crates/re_query/src/latest_at/to_archetype/bar_chart.rs
  crates/re_query/src/latest_at/to_archetype/boxes2d.rs
  crates/re_query/src/latest_at/to_archetype/boxes3d.rs
  crates/re_query/src/latest_at/to_archetype/clear.rs
  crates/re_query/src/latest_at/to_archetype/container_blueprint.rs
  crates/re_query/src/latest_at/to_archetype/depth_image.rs
  crates/re_query/src/latest_at/to_archetype/disconnected_space.rs
  crates/re_query/src/latest_at/to_archetype/image.rs
  crates/re_query/src/latest_at/to_archetype/line_strips2d.rs
  crates/re_query/src/latest_at/to_archetype/line_strips3d.rs
  crates/re_query/src/latest_at/to_archetype/mesh3d.rs
  crates/re_query/src/latest_at/to_archetype/mod.rs
  crates/re_query/src/latest_at/to_archetype/panel_blueprint.rs
  crates/re_query/src/latest_at/to_archetype/pinhole.rs
  crates/re_query/src/latest_at/to_archetype/plot_legend.rs
  crates/re_query/src/latest_at/to_archetype/points2d.rs
  crates/re_query/src/latest_at/to_archetype/points3d.rs
  crates/re_query/src/latest_at/to_archetype/scalar.rs
  crates/re_query/src/latest_at/to_archetype/scalar_axis.rs
  crates/re_query/src/latest_at/to_archetype/segmentation_image.rs
  crates/re_query/src/latest_at/to_archetype/series_line.rs
  crates/re_query/src/latest_at/to_archetype/series_point.rs
  crates/re_query/src/latest_at/to_archetype/space_view_blueprint.rs
  crates/re_query/src/latest_at/to_archetype/space_view_contents.rs
  crates/re_query/src/latest_at/to_archetype/tensor.rs
  crates/re_query/src/latest_at/to_archetype/text_document.rs
  crates/re_query/src/latest_at/to_archetype/text_log.rs
  crates/re_query/src/latest_at/to_archetype/transform3d.rs
  crates/re_query/src/latest_at/to_archetype/view_coordinates.rs
  crates/re_query/src/latest_at/to_archetype/viewport_blueprint.rs
  crates/re_query/src/latest_at/to_archetype/visible_time_ranges.rs
  crates/re_query/src/latest_at/to_archetype/visual_bounds2d.rs
  crates/re_query/src/lib.rs
  crates/re_selection_panel/src/query_range_ui.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/mod.rs
  crates/re_types_builder/src/codegen/rust/to_archetype.rs
  crates/re_viewer_context/src/annotations.rs
  crates/re_viewport_blueprint/src/container.rs
  crates/re_viewport_blueprint/src/space_view.rs
  crates/re_viewport_blueprint/src/space_view_contents.rs
  crates/re_viewport_blueprint/src/viewport_blueprint.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 🚜 refactor, exclude from changelog

#6499 Use test context in component override tests
  crates/re_viewer_context/src/test_context.rs
  crates/re_viewport_blueprint/src/space_view.rs
Labels: 🔨 testing, 🚜 refactor, exclude from changelog

#6503 Bug fix: allow removing blueprint entries even when they are invisible
  crates/re_blueprint_tree/src/blueprint_tree.rs
Labels: 🪳 bug, ui, include in changelog

#6509 Allow manually setting full span scopes
  Cargo.lock
  Cargo.toml
  crates/re_time_panel/src/lib.rs
  crates/re_ui/src/ui_ext.rs
Labels: ui, include in changelog

#6511 Fix rerun-web canvas size
  web_viewer/index.html
Labels: 🕸️ web, include in changelog

#6513 Remove background highlight when list item is non-interactive
  crates/re_ui/src/list_item/list_item.rs
Labels: ui, exclude from changelog

#6504 Inline viewer improvements
  .prettierrc.toml
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/web.rs
  rerun_js/scripts/common.mjs
  rerun_js/web-viewer/.gitignore
  rerun_js/web-viewer/index.js
  rerun_js/web-viewer/index.ts
  rerun_js/web-viewer/package.json
  rerun_js/web-viewer/tsconfig.json
Labels: 🕸️ web, exclude from changelog

#6494 Toggle switch now becomes blue when ON
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/ui_ext.rs
Labels: ui, include in changelog

#6514 Make barchart legend settable via blueprint
  Cargo.lock
  crates/re_entity_db/src/entity_properties.rs
  crates/re_space_view_bar_chart/Cargo.toml
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_types/definitions/rerun/blueprint/views/bar_chart.fbs
  crates/re_types/src/blueprint/views/bar_chart_view.rs
  docs/content/reference/types/views/bar_chart_view.md
  rerun_py/rerun_sdk/rerun/blueprint/views/bar_chart_view.py
Labels: 🟦 blueprint, include in changelog

#6524 Ensure we have roundtrip tests for each archetype in PR CI
  .github/workflows/reusable_test_wheels.yml
  crates/re_space_view_bar_chart/Cargo.toml
  tests/roundtrips.py
Labels: exclude from changelog, :ship: CI

#6529 JS: Make LogChannel public
  rerun_js/web-viewer/index.ts
Labels: 🕸️ web, include in changelog

#6522 Restore the clear test for the GC behavior blueprint depends on
  crates/re_entity_db/src/time_histogram_per_timeline.rs
  crates/re_entity_db/tests/clear.rs
  crates/re_entity_db/tests/time_histograms.rs
Labels: 🦟 regression, exclude from changelog

#6538 Fix `cargo t --all-features --all`
  crates/re_ui/src/modal.rs
  crates/re_viewer_context/src/component_fallbacks.rs
Labels: 😤 annoying, exclude from changelog, :ship: CI

#6535 Update egui
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#6486 Better integration of `ListItem` in tooltips and other popups
  .vscode/launch.json
  Cargo.lock
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/examples/re_ui_example/right_panel.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item/label_content.rs
  crates/re_ui/src/list_item/list_item.rs
  crates/re_ui/src/list_item/property_content.rs
  crates/re_ui/src/ui_ext.rs
Labels: ui, exclude from changelog

#6534 Opt-out of GC protection for `log_seq` and `log_time` when GCing blueprints
  crates/re_data_store/benches/data_store.rs
  crates/re_data_store/benches/gc.rs
  crates/re_data_store/src/store_gc.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_store/tests/data_store.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_entity_db/tests/clear.rs
  crates/re_viewer_context/src/store_hub.rs
Labels: ⛃ re_datastore, 🟦 blueprint, exclude from changelog

#6537 Introduce a mechanism for blueprint-provided defaults
  crates/re_query/src/range/results.rs
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/lib.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/query.rs
  crates/re_space_view/src/results_ext.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_viewer_context/src/space_view/view_context.rs
  crates/re_viewport_blueprint/src/space_view.rs
Labels: 🟦 blueprint, include in changelog

#6549 Expose `Colormap` component for `DepthImage`, depth image colormap now used outside of reprojection
  crates/re_data_ui/src/image.rs
  crates/re_entity_db/src/entity_properties.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/colormap.fbs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/archetypes/depth_image_ext.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/colormap.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/tests/depth_image.rs
  crates/re_viewer/src/component_defaults/mod.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/re_viewer_context/src/gpu_bridge/mod.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewport_blueprint/src/space_view.rs
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/colormap.md
  docs/snippets/all/archetypes/depth_image_3d.cpp
  docs/snippets/all/archetypes/depth_image_3d.py
  docs/snippets/all/archetypes/depth_image_3d.rs
  rerun_cpp/src/rerun/archetypes/depth_image.cpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/colormap.cpp
  rerun_cpp/src/rerun/components/colormap.hpp
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/colormap.py
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#6551 Fix wrong depth projection value on picking when depth meter was edited
  crates/re_entity_db/src/entity_properties.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_types/definitions/rerun/components/colormap.fbs
  docs/content/reference/types/components/colormap.md
Labels: 🪳 bug, 📺 re_viewer, 🚜 refactor, include in changelog

#6559 Use edit ui when no data ui is available
  crates/re_edit_ui/src/datatype_editors/enum_combobox.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_viewer_context/src/component_ui_registry.rs
Labels: ui, exclude from changelog

#6564 Cleanup usage of `unwrap()` in `re_query`
  crates/re_query/src/bin/range_zip.rs
  crates/re_query/src/lib.rs
  crates/re_query/src/range/results.rs
  crates/re_query/src/range_zip/generated.rs
Labels: 🚜 refactor, exclude from changelog

#6171 Update to `wgpu 0.20`, fixing crashes with some linux setups
  Cargo.lock
  Cargo.toml
  crates/re_renderer/src/error_handling/error_tracker.rs
  crates/re_renderer/src/error_handling/wgpu_core_error.rs
  crates/re_renderer/src/wgpu_resources/render_pipeline_pool.rs
Labels: 🪳 bug, dependencies, include in changelog

#6558 TimeSeriesAggregation can now be set per SeriesLine (and as blueprint default per View)
  crates/re_edit_ui/src/lib.rs
  crates/re_entity_db/src/entity_properties.rs
  crates/re_entity_db/src/lib.rs
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_types/definitions/rerun/archetypes/series_line.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/aggregation_policy.fbs
  crates/re_types/definitions/rerun/components/colormap.fbs
  crates/re_types/src/archetypes/series_line.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/aggregation_policy.rs
  crates/re_types/src/components/mod.rs
  crates/re_viewer/src/component_defaults/mod.rs
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/aggregation_policy.md
  rerun_cpp/src/rerun/archetypes/series_line.cpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/aggregation_policy.cpp
  rerun_cpp/src/rerun/components/aggregation_policy.hpp
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/aggregation_policy.py
Labels: 🍏 primitives, include in changelog, 🪵 Log-API, 📈 plot

#6566 Expose `FillRatio` component to configure DepthImage backprojection radius scaling
  Cargo.lock
  crates/re_edit_ui/src/lib.rs
  crates/re_entity_db/src/entity_properties.rs
  crates/re_entity_db/src/lib.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/view_2d.rs
  crates/re_space_view_spatial/src/view_3d.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/fill_ratio.fbs
  crates/re_types/definitions/rerun/datatypes/float32.fbs
  crates/re_types/src/archetypes/depth_image.rs
  crates/re_types/src/archetypes/depth_image_ext.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/fill_ratio.rs
  crates/re_types/src/components/fill_ratio_ext.rs
  crates/re_types/src/components/mod.rs
  crates/re_types/tests/depth_image.rs
  crates/re_types_core/Cargo.toml
  crates/re_types_core/src/datatypes/float32.rs
  crates/re_types_core/src/datatypes/float32_ext.rs
  crates/re_types_core/src/datatypes/mod.rs
  crates/re_viewer/src/component_defaults/mod.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/fill_ratio.md
  docs/content/reference/types/datatypes/float32.md
  rerun_cpp/src/rerun/archetypes/depth_image.cpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/fill_ratio.hpp
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/fill_ratio.py
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#6568 Remove legacy `EntityProperties` + a few related cleanups
  crates/re_entity_db/src/blueprint/.gitattributes
  crates/re_entity_db/src/blueprint/components/.gitattributes
  crates/re_entity_db/src/blueprint/components/entity_properties_component.rs
  crates/re_entity_db/src/blueprint/components/entity_properties_component_ext.rs
  crates/re_entity_db/src/blueprint/components/mod.rs
  crates/re_entity_db/src/blueprint/mod.rs
  crates/re_entity_db/src/editable_auto_value.rs
  crates/re_entity_db/src/entity_properties.rs
  crates/re_entity_db/src/lib.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/view_2d.rs
  crates/re_space_view_spatial/src/view_3d.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/entity_properties_component.fbs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/re_viewer/src/component_defaults/mod.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewer_context/src/space_view/view_states.rs
  crates/re_viewer_context/src/time_control.rs
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport_blueprint/src/space_view.rs
  crates/re_viewport_blueprint/src/space_view_contents.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/entity_properties_component.cpp
  rerun_cpp/src/rerun/blueprint/components/entity_properties_component.hpp
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/entity_properties_component.py
Labels: 🚜 refactor, exclude from changelog

#6560 OCR example
  examples/manifest.toml
  examples/python/ocr/README.md
  examples/python/ocr/ocr.py
  examples/python/ocr/pyproject.toml
  pixi.lock
  pixi.toml
Labels: examples, include in changelog

#6569 Remove serde type codegen + cargo machete pass
  Cargo.lock
  crates/re_blueprint_tree/Cargo.toml
  crates/re_context_menu/Cargo.toml
  crates/re_edit_ui/Cargo.toml
  crates/re_entity_db/Cargo.toml
  crates/re_log_encoding/Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_sdk_comms/Cargo.toml
  crates/re_selection_panel/Cargo.toml
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_text_document/Cargo.toml
  crates/re_types/definitions/rust/attributes.fbs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_core/Cargo.toml
  crates/re_types_core/src/result.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer_context/Cargo.toml
  crates/re_viewport/Cargo.toml
  crates/re_viewport_blueprint/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
Labels: 🚜 refactor, codegen/idl, exclude from changelog

#6579 Make pr comment parsing a python script
  .github/workflows/on_pr_comment.yml
  scripts/ci/parse_bot_pr_comment.py
Labels: exclude from changelog, :ship: CI

#6580 Add a simple security.md
  SECURITY.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#6582 Always enable OpenGL fallback backend, fix `--renderer=gl` only working together with `WGPU_BACKEND` env-var
  crates/re_renderer/src/config.rs
Labels: 🪳 bug, 🔺 re_renderer, include in changelog

#6594 Update OCR example readme
  examples/python/ocr/README.md
Labels: examples, include in changelog

#6591 Archetype roundtrip tests are no longer mandatory
  scripts/roundtrip_utils.py
  tests/roundtrips.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#6593 Update to latest egui master
  Cargo.lock
  Cargo.toml
  crates/re_analytics/Cargo.toml
  crates/re_analytics/src/native/config.rs
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/src/command_palette.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: dependencies, exclude from changelog, egui

#6598 Add a `debugging` cargo profile
  .vscode/launch.json
  Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#6596 Make object hover & selection colors brighter and more pronounced
  crates/re_renderer/shader/composite.wgsl
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_ui/src/context_ext.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/list_item/list_item.rs
Labels: ui, 🔺 re_renderer, include in changelog

#6597 Show outline around hovered/selected tiles in viewport
  crates/re_ui/src/design_tokens.rs
  crates/re_viewport/src/viewport.rs
Labels: ui, include in changelog

#6599 Unified visualizer & override ui, enabled on all entities
  Cargo.lock
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_query/src/latest_at/helpers.rs
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/lib.rs
  crates/re_selection_panel/src/override_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_space_view/src/query.rs
  crates/re_space_view/src/results_ext.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewer_context/src/space_view/visualizer_system.rs
  crates/re_viewer_context/src/test_context.rs
Labels: ui, 📺 re_viewer, include in changelog

#6608 Remove `panic="abort"` from `dev` builds
  Cargo.toml
Labels: ui, 🧑‍💻 dev experience, exclude from changelog

#6573 New notebook API
  crates/re_chunk/src/batcher.rs
  crates/re_log_encoding/src/encoder.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/log_sink.rs
  examples/python/notebook/cube.ipynb
  pixi.lock
  pixi.toml
  rerun_js/web-viewer-react/README.md
  rerun_js/web-viewer/README.md
  rerun_js/web-viewer/index.ts
  rerun_notebook/.gitignore
  rerun_notebook/README.md
  rerun_notebook/build.mjs
  rerun_notebook/example.ipynb
  rerun_notebook/package-lock.json
  rerun_notebook/package.json
  rerun_notebook/pyproject.toml
  rerun_notebook/src/js/widget.css
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_notebook/tsconfig.json
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/html_shared.py
  rerun_py/rerun_sdk/rerun/memory.py
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  scripts/ci/templates/benchmark.html
  scripts/ci/templates/pip_index.html
  scripts/ci/templates/pr_results_summary.html
  scripts/screenshot_compare/assets/templates/example.html
  scripts/screenshot_compare/assets/templates/index.html
  taplo.toml
  web_viewer/index.html
Labels: 🕸️ web, notebook, include in changelog

#6609 Show first line of the docs when hovering a component name
  Cargo.lock
  crates/re_data_ui/src/component_name.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/lib.rs
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_time_panel/src/lib.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/blueprint_validation.rs
  crates/re_types_builder/src/codegen/rust/mod.rs
  crates/re_types_builder/src/codegen/rust/reflection.rs
  crates/re_types_builder/src/codegen/rust/util.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  crates/re_types_core/Cargo.toml
  crates/re_types_core/src/lib.rs
  crates/re_types_core/src/reflection.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/component_defaults/mod.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/reflection/.gitattributes
  crates/re_viewer/src/reflection/mod.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/component_fallbacks.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/test_context.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: 📖 documentation, ui, include in changelog

#6617 Don't pass RRD paths to other data-loaders
  crates/re_data_loader/src/load_file.rs
Labels: 😤 annoying, include in changelog

#6605 Introduce visualizer blueprint query stack ui
  Cargo.lock
  crates/re_selection_panel/Cargo.toml
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_space_view/src/query.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_ui/data/icons/more.png
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item/list_item.rs
  crates/re_ui/src/list_item/property_content.rs
  crates/re_ui/src/ui_ext.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/component_ui_registry.rs
Labels: ui, 📺 re_viewer, include in changelog

#6623 Generate reflection for archetypes
  Cargo.lock
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/view_property_ui.rs
  crates/re_types/src/blueprint/archetypes/background.rs
  crates/re_types/src/blueprint/archetypes/plot_legend.rs
  crates/re_types/src/blueprint/archetypes/scalar_axis.rs
  crates/re_types/src/blueprint/archetypes/tensor_scalar_mapping.rs
  crates/re_types/src/blueprint/archetypes/tensor_slice_selection.rs
  crates/re_types/src/blueprint/archetypes/tensor_view_fit.rs
  crates/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/reflection.rs
  crates/re_types_core/src/archetype.rs
  crates/re_types_core/src/lib.rs
  crates/re_types_core/src/reflection.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/reflection/mod.rs
  crates/re_viewer_context/src/viewer_context.rs
Labels: ui, 🚜 refactor, codegen/idl, exclude from changelog

#6622 Fix `large_collapsing_header` implementation
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/src/ui_ext.rs
Labels: 🪳 bug, ui, exclude from changelog

#6625 Codegen reflection API for enums, with docstring for variants
  Cargo.lock
  crates/re_data_ui/src/component_name.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_edit_ui/Cargo.toml
  crates/re_edit_ui/src/datatype_editors/enum_combobox.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/marker_shape.rs
  crates/re_types/definitions/rerun/blueprint/components/container_kind.fbs
  crates/re_types/src/blueprint/components/background_kind.rs
  crates/re_types/src/blueprint/components/corner2d.rs
  crates/re_types/src/blueprint/components/panel_state.rs
  crates/re_types/src/blueprint/components/view_fit.rs
  crates/re_types/src/components/aggregation_policy.rs
  crates/re_types/src/components/colormap.rs
  crates/re_types/src/components/magnification_filter.rs
  crates/re_types/src/components/marker_shape.rs
  crates/re_types/src/testing/components/enum_test.rs
  crates/re_types_blueprint/src/blueprint/components/container_kind.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_core/src/reflection.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/gpu_bridge/colormap.rs
  rerun_cpp/src/rerun/blueprint/components/container_kind.hpp
  rerun_py/rerun_sdk/rerun/blueprint/components/container_kind.py
Labels: ui, codegen/idl, exclude from changelog

#6630 Fix confusing code around plot marker size vs stroke width
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
Labels: 🪳 bug, exclude from changelog

#6631 Update to latest egui and egui_tiles
  Cargo.lock
  Cargo.toml
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_viewport/src/viewport.rs
Labels: dependencies, exclude from changelog, egui

#6634 Disable `Component Defaults` button if there are no editors
  crates/re_selection_panel/src/defaults_ui.rs
Labels: ui, exclude from changelog

#6640 Allow streaming to the viewer from the cell where it's created
  examples/python/notebook/cube.ipynb
  pixi.lock
  rerun_notebook/pyproject.toml
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🐍 Python API, notebook, include in changelog

#6648 Remove viewer margin in notebook
  rerun_notebook/src/js/widget.css
Labels: 🕸️ web, notebook, exclude from changelog

#6604 Add support for PDF files in the OCR example
  examples/python/ocr/README.md
  examples/python/ocr/ocr.py
  examples/python/ocr/pyproject.toml
  pixi.lock
  pixi.toml
Labels: examples, exclude from changelog, include in changelog

#6652 Fix re_types/tests/image.rs
  crates/re_types/tests/image.rs
  crates/re_types/tests/segmentation_image.rs
Labels: 🔨 testing, exclude from changelog

#6636 Add width/height properties to web viewer
  rerun_js/web-viewer-react/README.md
  rerun_js/web-viewer-react/index.js
  rerun_js/web-viewer/README.md
  rerun_js/web-viewer/index.ts
Labels: 🕸️ web, include in changelog

#6645 improved color editor, remove unused DataUi
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/editors/mod.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/material.rs
  crates/re_edit_ui/src/color.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_edit_ui/src/material.rs
  tests/python/release_checklist/check_all_components_ui.py
Labels: 📺 re_viewer, exclude from changelog

#6637 Reorganize Selection Panel
  crates/re_context_menu/src/actions/remove.rs
  crates/re_edit_ui/src/visual_bounds2d.rs
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/lib.rs
  crates/re_selection_panel/src/selection_history_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/visible_time_range_ui.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_ui/src/list_item/scope.rs
  crates/re_ui/src/ui_ext.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: ui, include in changelog

#6656 Update egui, with fix for jittering menus
  Cargo.lock
  Cargo.toml
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_viewer/src/native.rs
  crates/rerun/src/native_viewer.rs
Labels: dependencies, exclude from changelog, egui

#6639 Fix timeseries view crashing on invalid bounds in debug mode
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: 🪳 bug, 💣 crash, exclude from changelog

#6663 Reintroduce display color ui
  crates/re_edit_ui/src/color.rs
  crates/re_edit_ui/src/lib.rs
Labels: ui, 🦟 regression, exclude from changelog

#6657 Rewrite the `ui.large_collapsing_header` into `re_ui::SectionCollapsingHeader` using `re_ui::ListItem`
  crates/re_blueprint_tree/src/blueprint_tree.rs
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/space_view_space_origin_ui.rs
  crates/re_selection_panel/src/visible_time_range_ui.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item/label_content.rs
  crates/re_ui/src/list_item/list_item.rs
  crates/re_ui/src/section_collapsing_header.rs
  crates/re_ui/src/ui_ext.rs
Labels: enhancement, ui, 🚜 refactor, include in changelog

#6667 Fix wrong link in Vista example
  examples/python/vista/README.md
Labels: examples, exclude from changelog

#6665 Update wgpu to 0.20.2 patch
  Cargo.lock
Labels: dependencies, exclude from changelog

#6666 Fix name editing for point series, fix fallbacks for point/line series display
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/util.rs
Labels: 🪳 bug, 🦟 regression, exclude from changelog, 📈 plot

#6662 Move entity filter "edit" button to a section header icon
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_ui/data/icons/edit.png
  crates/re_ui/examples/re_ui_example/main.rs
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item/item_button.rs
  crates/re_ui/src/list_item/label_content.rs
  crates/re_ui/src/list_item/mod.rs
  crates/re_ui/src/list_item/property_content.rs
  crates/re_ui/src/section_collapsing_header.rs
Labels: enhancement, ui, 🚜 refactor, include in changelog

#6669 Add example of stereo vision SLAM
  examples/cpp/stereo_vision_slam/README.md
  examples/manifest.toml
Labels: examples, include in changelog

#6668 Add help to several sections in the Selection Panel
  crates/re_selection_panel/src/defaults_ui.rs
  crates/re_selection_panel/src/selection_panel.rs
  crates/re_selection_panel/src/visible_time_range_ui.rs
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_ui/src/section_collapsing_header.rs
Labels: ui, include in changelog

#6644 Make draw order editable & solve 2D flickering issues, add draw order to arrow2d archetype
  crates/re_edit_ui/src/datatype_editors/float_drag.rs
  crates/re_edit_ui/src/datatype_editors/mod.rs
  crates/re_edit_ui/src/lib.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_types/definitions/rerun/archetypes/arrows2d.fbs
  crates/re_types/src/archetypes/arrows2d.rs
  crates/re_viewer_context/src/space_view/visualizer_system.rs
  docs/content/reference/types/archetypes/arrows2d.md
  docs/content/reference/types/components/draw_order.md
  rerun_cpp/src/rerun/archetypes/arrows2d.cpp
  rerun_cpp/src/rerun/archetypes/arrows2d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
Labels: 🪳 bug, 📺 re_viewer, include in changelog, 🪵 Log-API

#6676 Remove Axes3D archetype and add axis_length to Transform3D
  crates/re_space_view_spatial/src/view_3d.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/archetypes/axes3d.fbs
  crates/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/re_types/src/archetypes/.gitattributes
  crates/re_types/src/archetypes/axes3d.rs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/transform3d.rs
  crates/re_types/src/archetypes/transform3d_ext.rs
  crates/re_types/tests/transform3d.rs
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/.gitattributes
  docs/content/reference/types/archetypes/axes3d.md
  docs/content/reference/types/archetypes/transform3d.md
  docs/content/reference/types/components/axis_length.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  docs/snippets/all/archetypes/transform3d_axes.cpp
  docs/snippets/all/archetypes/transform3d_axes.py
  docs/snippets/all/archetypes/transform3d_axes.rs
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/.gitattributes
  rerun_cpp/src/rerun/archetypes/axes3d.cpp
  rerun_cpp/src/rerun/archetypes/axes3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.cpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/axes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#6674 Update to latest `egui` master, with fixes for notebook focus
  Cargo.lock
  Cargo.toml
Labels: 🕸️ web, dependencies, notebook, exclude from changelog, egui

#6650 Introduce new python API for setting overides
  Cargo.lock
  crates/re_selection_panel/Cargo.toml
  crates/re_selection_panel/src/visualizer_ui.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/visualizer_overrides.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/visualizer_overrides.fbs
  crates/re_types_blueprint/src/blueprint/components/.gitattributes
  crates/re_types_blueprint/src/blueprint/components/mod.rs
  crates/re_types_blueprint/src/blueprint/components/visualizer_overrides.rs
  crates/re_types_builder/src/codegen/python/views.rs
  crates/re_types_core/src/components/.gitattributes
  crates/re_types_core/src/components/mod.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/re_viewer/src/reflection/mod.rs
  crates/re_viewport_blueprint/src/space_view_contents.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/visualizer_overrides.md
  docs/snippets/all/tutorials/visualizer-overrides.py
  docs/snippets/snippets.toml
  examples/python/blueprint/blueprint.py
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/visualizer_overrides.cpp
  rerun_cpp/src/rerun/blueprint/components/visualizer_overrides.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/visualizer_overrides.hpp
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/visualizer_overrides.py
  rerun_py/rerun_sdk/rerun/blueprint/components/visualizer_overrides_ext.py
  rerun_py/rerun_sdk/rerun/blueprint/views/bar_chart_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial2d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/spatial3d_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/tensor_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/text_document_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/text_log_view.py
  rerun_py/rerun_sdk/rerun/blueprint/views/time_series_view.py
  rerun_py/rerun_sdk/rerun/blueprint/visualizers.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/visualizer_overrides.py
  rerun_py/tests/unit/test_visualizer_overrides.py
Labels: 🐍 Python API, 🟦 blueprint, include in changelog

#6641 Publish `rerun_notebook` in CI
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_publish_wheels.yml
  Cargo.lock
  Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/custom_data_loader/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/custom_store_subscriber/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/external_data_loader/Cargo.toml
  examples/rust/incremental_logging/Cargo.toml
  examples/rust/log_file/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/shared_recording/Cargo.toml
  examples/rust/spawn_viewer/Cargo.toml
  examples/rust/stdio/Cargo.toml
  examples/rust/template/Cargo.toml
  pixi.lock
  pixi.toml
  rerun_cpp/src/rerun/c/rerun.h
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer/package.json
  rerun_notebook/README.md
  rerun_notebook/pyproject.toml
  rerun_py/pyproject.toml
  scripts/ci/build_and_upload_rerun_notebook.py
  scripts/ci/crates.py
  scripts/ci/update_rerun_notebook_version.py
Labels: 🐍 Python API, include in changelog, :ship: CI

#6677 Use new `.clamp_to_range(false)` to make sure drag value inputs are not changed by looking at them
  Cargo.lock
  Cargo.toml
  crates/re_edit_ui/src/datatype_editors/float_drag.rs
  crates/re_edit_ui/src/range1d.rs
  crates/re_edit_ui/src/visual_bounds2d.rs
  crates/re_selection_panel/src/visible_time_range_ui.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_time_panel/src/time_control_ui.rs
Labels: ui, exclude from changelog

#6684 Ignore viemo links on CI
  lychee.toml
Labels: exclude from changelog, :ship: CI
