Repository rerun-io/rerun, pull requests merged in 2024-02, with the labels that each got.

#4987 Clarify aggregation strings
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: 📺 re_viewer, exclude from changelog

#4994 Defend against inverted time ranges
  crates/re_query/src/util.rs
  crates/re_query_cache/src/query.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_viewer/src/ui/visible_history.rs
Labels: 💣 crash, exclude from changelog

#5001 Pin `typos` action to specific version
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks.yml
  crates/re_space_view/src/data_query_blueprint.rs
Labels: exclude from changelog, :ship: CI

#4999 Remove parallel iterators in attribute processors
  crates/re_space_view_spatial/src/visualizers/mod.rs
Labels: 📉 performance, exclude from changelog

#4981 Allow forcing WebGPU/WebGL on the web player, new command line argument to force graphics backend
  .cargo/config.toml
  Cargo.lock
  crates/re_renderer/src/config.rs
  crates/re_sdk/src/web_viewer.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/web.rs
  crates/re_viewer/src/web_tools.rs
  crates/rerun/src/run.rs
  docs/content/getting-started/troubleshooting.md
  examples/rust/custom_space_view/src/main.rs
  examples/rust/extend_viewer_ui/src/main.rs
  web_viewer/index.html
Labels: enhancement, 🕸️ web, include in changelog

#5002 Update to latest egui master
  Cargo.lock
  Cargo.toml
  crates/re_viewer_context/src/annotations.rs
Labels: 📉 performance, dependencies, exclude from changelog

#5000 Integrate caching in 2D and 3D box visualizers
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 📉 performance, include in changelog

#4988 Fill gaps in image encoding documentation, fix how python documents union variants
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/definitions/rerun/components/tensor_data.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_data.fbs
  crates/re_types/src/components/tensor_data.rs
  crates/re_types/src/datatypes/tensor_buffer.rs
  crates/re_types/src/datatypes/tensor_data.rs
  crates/re_types_builder/src/codegen/python.rs
  docs/content/reference/types/components/tensor_data.md
  docs/content/reference/types/datatypes/tensor_data.md
  docs/cspell.json
  rerun_cpp/src/rerun/components/tensor_data.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_cpp/src/rerun/datatypes/tensor_data.hpp
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/components/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/datatypes/scale3d.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer3.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer4.py
Labels: 📖 documentation, include in changelog

#5008 Changed `re_ui::Modal` to use a `egui::Context` instead of a `egui::Ui`
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/modal.rs
  crates/re_viewer/src/ui/add_space_view_or_container_modal.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport.rs
Labels: ui, 🚜 refactor, exclude from changelog

#5007 Primary cache: allow entirely missing optional component columns
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/range.rs
Labels: 🪳 bug, 🔍 re_query, exclude from changelog

#5016 Fix crashes in cache when encountering new component
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/flat_vec_deque.rs
Labels: 🪳 bug, 💣 crash, exclude from changelog

#5014 Add runtime experimental flag for query clamping
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#5004 Introduce a new component for MarkerShape and use it in SeriesPoint
  crates/re_data_ui/src/editors.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_types/definitions/rerun/archetypes/series_point.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/marker_shape.fbs
  crates/re_types/src/archetypes/series_point.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/marker_shape.rs
  crates/re_types/src/components/marker_shape_ext.rs
  crates/re_types/src/components/mod.rs
  docs/content/reference/types/archetypes/series_point.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/marker_shape.md
  rerun_cpp/src/rerun/archetypes/series_point.cpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/marker_shape.cpp
  rerun_cpp/src/rerun/components/marker_shape.hpp
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/marker_shape.py
Labels: ui, 🟦 blueprint, include in changelog

#5003 Primary cache: keep track of timeless hits
  crates/re_query_cache/src/latest_at.rs
Labels: 🪳 bug, 🔍 re_query, 📉 performance, exclude from changelog

#5019 Show marker shape in selection dropdown
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/src/editors.rs
  crates/re_ui/src/list_item.rs
Labels: ui, exclude from changelog

#5022 Improve the UI for the entity query
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view_entity_picker.rs
Labels: ui, include in changelog

#5023 Only show the LegacyVisualizer if a user logs with TimeSeriesScalar archetype
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: ui, include in changelog

#5026 Fix codegen of python scoped objects to handle mixed-scope imports
  crates/re_types_builder/src/codegen/python.rs
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/container_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/plot_legend.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/space_view_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/viewport_blueprint.py
Labels: codegen/idl, exclude from changelog

#5012 Use the "Add Space View/Container" modal for the `+` button of the blueprint tree
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#5025 Introduce a new StrokeWidth component and use it for SeriesLine
  crates/re_data_ui/src/editors.rs
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_types/definitions/rerun/archetypes/series_line.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/stroke_width.fbs
  crates/re_types/src/archetypes/series_line.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/stroke_width.rs
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/stroke_width.md
  rerun_cpp/src/rerun/archetypes/series_line.cpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/stroke_width.cpp
  rerun_cpp/src/rerun/components/stroke_width.hpp
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/stroke_width.py
Labels: ui, 🟦 blueprint, include in changelog

#5031 Fix missing dependency when compiling re_data_ui in isolation
  crates/re_data_ui/Cargo.toml
Labels: exclude from changelog, :ship: CI

#5029 Don't associate a single archetype with two different queries
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
Labels: 🪳 bug, 💬 discussion, exclude from changelog, 🔩 data model

#5021 Add `--threads` / `-j` to control number of compute threads
  crates/rerun-cli/src/bin/rerun.rs
  crates/rerun/src/run.rs
Labels: 📉 performance, include in changelog, CLI

#5038 Batched plot attributes/overrides + misc fixes
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_viewer_context/src/annotations.rs
  rerun_cpp/src/rerun/c/rerun.h
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  tests/cpp/plot_dashboard_stress/main.cpp
  tests/python/plot_dashboard_stress/main.py
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 🪳 bug, 🔨 testing, 📉 performance, exclude from changelog

#5037 Show short component name in the component override menu
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/override_ui.rs
Labels: ui, exclude from changelog

#5041 Deploy cpp docs as both versioned and named
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_deploy_docs.yml
Labels: 📖 documentation, exclude from changelog

#5034 Fix a Visible Time Range UI issue where the summary string would display the wrong data range
  crates/re_viewer/src/ui/visible_history.rs
Labels: 🪳 bug, ui, include in changelog

#5044 Simplify viewport after tile drag-and-drop
  Cargo.lock
  Cargo.toml
  crates/re_viewer/src/app_state.rs
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, ui, include in changelog

#5046 Don't show the Blueprint header when on the welcome screen
  crates/re_viewer/src/app_state.rs
Labels: ui, include in changelog

#5036 Move Visible Time Range higher in the Selection Panel
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
Labels: ui, include in changelog

#5040 Update to `egui` 0.26
  Cargo.lock
  Cargo.toml
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: dependencies, exclude from changelog, egui

#5047 Move SpaceViewBlueprint -> re_space_view
  Cargo.lock
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/auto_layout.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/screenshot.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, 🟦 blueprint, exclude from changelog

#5053 Fix handling very large meshes & plots (allow maximum available gpu buffers)
  crates/re_renderer/src/config.rs
Labels: 🪳 bug, 🔺 re_renderer, 💣 crash, include in changelog

#5050 Allow SpaceViews to customize the behavior for how default visualizers are chosen
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/visualizable.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view_entity_picker.rs
Labels: 📺 re_viewer, 🟦 blueprint, exclude from changelog

#5054 Relax pyarrow dependency to `>=14.0.2`
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  rerun_py/pyproject.toml
Labels: dependencies, include in changelog

#5057 Introduce marker size component
  crates/re_data_ui/src/editors.rs
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_types/definitions/rerun/archetypes/series_point.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/marker_size.fbs
  crates/re_types/definitions/rerun/components/name.fbs
  crates/re_types/src/archetypes/series_point.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/marker_size.rs
  crates/re_types/src/components/mod.rs
  docs/content/reference/types/archetypes/series_point.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/marker_size.md
  rerun_cpp/src/rerun/archetypes/series_point.cpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/marker_size.cpp
  rerun_cpp/src/rerun/components/marker_size.hpp
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/marker_size.py
Labels: 📺 re_viewer, 🟦 blueprint, exclude from changelog

#5042 Update all examples that use `TimeSeriesScalar` to use `Scalar` instead
  crates/re_types/src/archetypes/scalar.rs
  crates/re_types/src/archetypes/time_series_scalar.rs
  docs/code-examples/all/scalar_multiple_plots.cpp
  docs/code-examples/all/scalar_multiple_plots.py
  docs/code-examples/all/scalar_multiple_plots.rs
  docs/code-examples/all/scalar_simple.cpp
  docs/code-examples/all/scalar_simple.py
  docs/code-examples/all/scalar_simple.rs
  docs/content/howto/ros2-nav-turtlebot.md
  examples/python/face_tracking/main.py
  examples/python/plots/main.py
  examples/python/ros_node/main.py
  examples/python/structure_from_motion/main.py
  rerun_cpp/src/rerun/archetypes/scalar.hpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_cpp/src/rerun/components/name.hpp
  rerun_cpp/src/rerun/components/name_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
  rerun_py/rerun_sdk/rerun/components/marker_size.py
  rerun_py/rerun_sdk/rerun/components/marker_size_ext.py
  rerun_py/rerun_sdk/rerun/components/stroke_width.py
  rerun_py/rerun_sdk/rerun/components/stroke_width_ext.py
  tests/cpp/plot_dashboard_stress/main.cpp
  tests/python/plot_dashboard_stress/main.py
  tests/python/visible_history_playground/main.py
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 📖 documentation, examples, include in changelog

#5059 Make override component name un-clickable
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/override_ui.rs
Labels: ui, exclude from changelog

#4997 Bootstrap interactive release checklist
  .github/pull_request_template.md
  rerun_py/rerun_sdk/rerun/script_helpers.py
  scripts/lint.py
  tests/python/release_checklist/README.md
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/release_checklist/check_plot_overrides.py
  tests/python/release_checklist/main.py
Labels: 🔨 testing, ⛴ release, exclude from changelog

#5064 Fixes broken tile resize introduced by #5044
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, ui, exclude from changelog

#5049 Mandatory primary caching
  crates/re_query_cache/benches/latest_at.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/lib.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_query_cache/tests/range.rs
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#5063 Fix empty space-view when dragging away active tab
  Cargo.lock
  Cargo.toml
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#5066 Propagate visible history default values correctly
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view.rs
  crates/re_viewer/src/ui/selection_panel.rs
  tests/python/release_checklist/check_plot_overrides.py
Labels: 🟦 blueprint, exclude from changelog

#5068 Populate the available visualizer list so all visualizers get heurisic properties
  crates/re_space_view/src/data_query_blueprint.rs
Labels: 🪳 bug, exclude from changelog

#5071 Fix forever repaint of big scenes
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5069 Ensure that every indicated 2D entity_path gets a visualizer
  crates/re_space_view_spatial/src/space_view_2d.rs
Labels: 📺 re_viewer, exclude from changelog

#5028 Introduce a new blueprint archetype for AxisY configuration in a plot.
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/util.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/scalar_axis.fbs
  crates/re_types/definitions/rerun/blueprint/components/lock_range_during_zoom.fbs
  crates/re_types/definitions/rerun/components.fbs
  crates/re_types/definitions/rerun/components/range1d.fbs
  crates/re_types/src/blueprint/archetypes/.gitattributes
  crates/re_types/src/blueprint/archetypes/mod.rs
  crates/re_types/src/blueprint/archetypes/scalar_axis.rs
  crates/re_types/src/blueprint/components/.gitattributes
  crates/re_types/src/blueprint/components/lock_range_during_zoom.rs
  crates/re_types/src/blueprint/components/mod.rs
  crates/re_types/src/components/.gitattributes
  crates/re_types/src/components/mod.rs
  crates/re_types/src/components/range1d.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/range1d.md
  rerun_cpp/src/rerun/blueprint/archetypes.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/.gitattributes
  rerun_cpp/src/rerun/blueprint/archetypes/scalar_axis.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/scalar_axis.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/lock_range_during_zoom.cpp
  rerun_cpp/src/rerun/blueprint/components/lock_range_during_zoom.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/range1d.cpp
  rerun_cpp/src/rerun/components/range1d.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/scalar_axis.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/lock_range_during_zoom.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/range1d.py
Labels: 🟦 blueprint, include in changelog

#5079 `rerun print`: print just summary, unless given `--verbose`
  crates/re_format/src/lib.rs
  crates/re_log_types/src/lib.rs
  crates/rerun/src/run.rs
Labels: include in changelog, CLI

#5086 Fix `RERUN_FLUSH_NUM_BYTES` and data size estimations
  crates/re_build_examples/src/rrd.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types_core/src/size_bytes.rs
  crates/rerun/src/run.rs
  examples/python/nuscenes/README.md
  examples/python/plots/main.py
Labels: 🪳 bug, 😤 annoying, include in changelog

#5083 Cached 2D & 3D line clouds
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
Labels: 🔍 re_query, 📉 performance, include in changelog

#5089 Clean up time range ui
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/app_options.rs
Labels: ui, include in changelog

#5080 Basic container test checklist
  tests/python/release_checklist/check_container_hierarchy.py
Labels: 🔨 testing, exclude from changelog

#5074 Code-golf rectangle_fs.wgsl to work around a suspected angle/mesa bug and avoid crash on chrome (#3931)
  crates/re_renderer/shader/decodings.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
Labels: 🔺 re_renderer, 🚜 refactor, 🦟 regression, include in changelog

#5076 When duplicating a space-view copy the nested blueprint tree
  crates/re_log_types/src/path/entity_path.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
  tests/python/release_checklist/check_plot_overrides.py
Labels: 🟦 blueprint, exclude from changelog

#5088 Cached 2D & 3D arrow clouds
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
Labels: 🔍 re_query, 📉 performance, include in changelog

#5091 Do not allow adding Horizontal/Vertical containers inside of containers with the same type
  crates/re_viewport/src/add_space_view_or_container_modal.rs
Labels: ui, include in changelog

#5094 Augment cache parallelism check with all new cached types
  crates/re_space_view_spatial/src/visualizers/mod.rs
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
Labels: 🔨 testing, exclude from changelog

#5097 Add missing inline for EntityPath Index
  crates/re_log_types/src/path/entity_path.rs
Labels: 📉 performance, exclude from changelog

#5096 Improve the selection/hover behavior for plots
  crates/re_space_view_time_series/src/space_view_class.rs
  tests/python/release_checklist/check_hover_select_reset.py
Labels: enhancement, 📺 re_viewer, include in changelog

#5106 Check "pressing escape" in the new selection check
  tests/python/release_checklist/check_hover_select_reset.py
Labels: 🔨 testing, exclude from changelog

#5093 Clean up component grid UI
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/lib.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/app_options.rs
Labels: ui, include in changelog

#5107 Update egui_tiles to 0.7.2
  Cargo.lock
  Cargo.toml
Labels: dependencies, include in changelog

#5087 Improve 2d spawn heuristics
  crates/re_log_types/src/path/entity_path.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  examples/python/detect_and_track_objects/main.py
Labels: 📺 re_viewer, exclude from changelog

#5108 Code examples rust: detect new examples automatically
  docs/code-examples/build.rs
Labels: 🧑‍💻 dev experience, examples, exclude from changelog

#5110 Remove illegitimate uses of `unwrap_debug_or_log_error`
  crates/re_log/src/result_extensions.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/line_strip_builder.rs
  crates/re_renderer/src/point_cloud_builder.rs
Labels: 🧑‍💻 dev experience, 😤 annoying, 💣 crash, exclude from changelog

#5112 Adding code examples for SeriesLine and SeriesPoint
  crates/re_types/definitions/rerun/archetypes/series_line.fbs
  crates/re_types/definitions/rerun/archetypes/series_point.fbs
  crates/re_types/definitions/rerun/components/marker_shape.fbs
  crates/re_types/src/archetypes/series_line.rs
  crates/re_types/src/archetypes/series_point.rs
  crates/re_types/src/components/marker_shape_ext.rs
  docs/code-examples/all/series_line_style.cpp
  docs/code-examples/all/series_line_style.py
  docs/code-examples/all/series_line_style.rs
  docs/code-examples/all/series_point_style.cpp
  docs/code-examples/all/series_point_style.py
  docs/code-examples/all/series_point_style.rs
  docs/code-examples/compare_code_example_output.py
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/archetypes/series_point.md
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_cpp/src/rerun/components/marker_shape.hpp
  rerun_cpp/src/rerun/components/marker_shape_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/components/marker_shape.py
  rerun_py/rerun_sdk/rerun/components/marker_shape_ext.py
  rerun_py/tests/unit/test_series_styles.py
Labels: 📖 documentation, exclude from changelog

#5102 Mark TimeSeriesScalar as deprecated in all SDKs and documentation
  .github/workflows/auto_release_crates.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_npm.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_test_wheels.yml
  CMakeLists.txt
  crates/re_data_store/benches/gc.rs
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_types/definitions/rerun/archetypes/time_series_scalar.fbs
  crates/re_types/definitions/rerun/attributes.fbs
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/time_series_scalar.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  docs/content/reference/types.md
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/time_series_scalar.md
  pixi.lock
  pixi.toml
  rerun_cpp/src/rerun/archetypes/time_series_scalar.cpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_cpp/src/rerun/compiler_utils.hpp
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
Labels: 📖 documentation, include in changelog, 🪵 Log-API

#5128 Fix miscellaneous issues in doc examples
  crates/re_types/src/archetypes/mesh3d.rs
  docs/code-examples/all/mesh3d_indexed.cpp
  docs/code-examples/all/mesh3d_indexed.py
  docs/code-examples/all/mesh3d_indexed.rs
  docs/code-examples/all/mesh3d_partial_updates.cpp
  docs/code-examples/all/pinhole_simple.cpp
  docs/code-examples/all/point2d_random.cpp
  docs/code-examples/all/series_point_style.cpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  tests/rust/roundtrips/text_document/src/main.rs
  tests/rust/roundtrips/text_log/src/main.rs
Labels: examples, exclude from changelog

#5124 Paint closest labels on top of labels further away
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: ui, include in changelog

#5135 Fix broken CI
  .github/pull_request_template.md
  crates/re_types/src/archetypes/mesh3d.rs
  docs/code-examples/all/mesh3d_indexed.rs
  scripts/ci/rust_checks.py
Labels: exclude from changelog, :ship: CI

#5122 Update `raw_mesh` screenshot to include texture
  crates/re_viewer/src/screenshotter.rs
  crates/re_viewer/src/ui/top_panel.rs
  examples/python/raw_mesh/README.md
  examples/rust/raw_mesh/README.md
Labels: 🧑‍💻 dev experience, examples, exclude from changelog

#5134 Primary cache: downgrade busy-lock log to trace level
  crates/re_query_cache/src/latest_at.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#5137 Fix more app ID mismatches
  tests/cpp/roundtrips/line_strips2d/main.cpp
  tests/cpp/roundtrips/line_strips3d/main.cpp
  tests/cpp/roundtrips/text_document/main.cpp
Labels: exclude from changelog, :ship: CI

#5142 Propagate exceptions from parallel DAG workers
  scripts/ci/dag.py
Labels: exclude from changelog, :ship: CI

#5141 Remove experimental_additive_workflow
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#5136 migration guide 0.12->0.13
  crates/re_types/definitions/rerun/archetypes/time_series_scalar.fbs
  crates/re_types/src/archetypes/time_series_scalar.rs
  docs/content/reference/migration-0-9.md
  docs/content/reference/migration.md
  docs/content/reference/migration/migration-0-13.md
  docs/content/reference/migration/migration-0-9.md
  docs/content/reference/types/archetypes/time_series_scalar.md
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
Labels: 📖 documentation, exclude from changelog

#5149 Still process annotations without keypoint_ids
  crates/re_space_view_spatial/src/visualizers/mod.rs
  tests/python/release_checklist/check_annotations.py
Labels: 🪳 bug, exclude from changelog

#5148 New 2d heuristic -- split any bucket with more than 1 image
  crates/re_space_view_spatial/src/space_view_2d.rs
  tests/python/release_checklist/check_2d_heuristics.py
Labels: 📺 re_viewer, include in changelog

#5155 Remove Objectron from default examples
  examples/python/objectron/README.md
Labels: examples, exclude from changelog

#5158 Download `librerun` artifacts using GCS APIs directly
  scripts/ci/bundle_and_upload_rerun_cpp.py
Labels: ⛴ release, exclude from changelog, :ship: CI

#5159 Fix formatting
  scripts/ci/bundle_and_upload_rerun_cpp.py
Labels: exclude from changelog, :ship: CI

#5161 Aggregate plots with duplicate time stamps
  crates/re_space_view_time_series/src/aggregation.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/util.rs
Labels: 📉 performance, exclude from changelog

#5164 Enforce the rule: heuristics should never add a new view that would be completely covered by an existing view
  crates/re_log_types/src/path/entity_path_filter.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view.rs
  crates/re_viewport/src/viewport.rs
Labels: 📺 re_viewer, 🦟 regression, include in changelog, heuristics

#5169 Fixed a typ with a missing word in the documentaiotn
  docs/content/concepts/entity-component.md
Labels: 📖 documentation, exclude from changelog

#5166 Refactor the 2D heuristic again
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/max_image_dimension_subscriber.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
Labels: exclude from changelog, heuristics

#5170 Fix using `rerun` crate as a dependency on CI
  crates/re_build_examples/src/manifest.rs
  crates/re_build_tools/src/lib.rs
  crates/re_build_tools/src/rebuild_detector.rs
  crates/re_renderer/build.rs
  crates/re_types_builder/build.rs
  crates/re_web_viewer_server/build.rs
  examples/rust/objectron/build.rs
Labels: 🦀 Rust API, 🧑‍💻 dev experience, include in changelog

#5176 Update to egui 0.26.1 and fix top-bar interaction
  Cargo.lock
  Cargo.toml
  crates/re_ui/examples/re_ui_example.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: 📺 re_viewer, dependencies, exclude from changelog, egui

#5179 Small release fixes
  .github/workflows/release.yml
Labels: ⛴ release, exclude from changelog, :ship: CI

#5184 Fix warnings when compiling with nightly
  Cargo.lock
  crates/re_analytics/src/native/sink.rs
  crates/re_log_types/src/path/parse_path.rs
  crates/re_memory/src/accounting_allocator.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/re_renderer/src/wgpu_resources/mod.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_types/src/image.rs
  crates/re_types_builder/src/codegen/mod.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer_context/src/clipboard.rs
  crates/re_viewport/src/viewport_blueprint.rs
  scripts/ci/rust_checks.py
Labels: 🧑‍💻 dev experience, dependencies, exclude from changelog

#5186 Add `cargo semver-checks` as a step in the patch release process
  RELEASES.md
Labels: ⛴ release, exclude from changelog

#5187 Update arboard 3.3.0 -> 3.3.1
  Cargo.lock
  deny.toml
Labels: dependencies, exclude from changelog

#5185 Add feature-flagged parallel loading of time series plots
  Cargo.lock
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/line_visualizer_system.rs
Labels: 📺 re_viewer, 📉 performance, exclude from changelog

#5189 Fix (log only) error on quickly resizing the viewer
  crates/re_renderer/src/view_builder.rs
  crates/re_renderer_examples/framework.rs
  crates/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: 🪳 bug, 🔺 re_renderer, include in changelog

#5190 Python: fix error message mentioning `TranslationRotationScale` instead of `TranslationRotationScale3D`
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
Labels: 📖 documentation, 🐍 Python API, exclude from changelog

#5191 Update docs to not mention `WINIT_UNIX_BACKEND`
  docs/content/getting-started/troubleshooting.md
  docs/cspell.json
Labels: 📖 documentation, exclude from changelog

#5160 Convert JS package to yarn workspace
  .github/workflows/on_pull_request.yml
  .github/workflows/release.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_publish_js.yml
  .prettierrc.toml
  .vscode/settings.json
  crates/re_build_web_viewer/src/lib.rs
  rerun_js/.gitignore
  rerun_js/package.json
  rerun_js/scripts/common.mjs
  rerun_js/scripts/publish.mjs
  rerun_js/scripts/version.mjs
  rerun_js/web-viewer-react/.gitignore
  rerun_js/web-viewer-react/README.md
  rerun_js/web-viewer-react/index.js
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer-react/tsconfig.json
  rerun_js/web-viewer/.gitignore
  rerun_js/web-viewer/README.md
  rerun_js/web-viewer/package.json
  rerun_js/web-viewer/scripts/build.mjs
  rerun_js/web-viewer/scripts/install.mjs
  rerun_js/web-viewer/scripts/publish.mjs
  rerun_js/yarn.lock
Labels: 🕸️ web, 🧑‍💻 dev experience, exclude from changelog

#5195 Fix incorrect minimum supported rust version mentioned in docs and examples
  clippy.toml
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  crates/re_viewer/data/quick_start_guides/rust_spawn.md
  docs/content/getting-started/installing-viewer.md
  docs/content/getting-started/rust.md
  examples/rust/clock/Cargo.toml
  examples/rust/custom_data_loader/Cargo.toml
  examples/rust/custom_space_view/Cargo.toml
  examples/rust/custom_store_subscriber/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/external_data_loader/Cargo.toml
  examples/rust/minimal/Cargo.toml
  examples/rust/minimal_options/Cargo.toml
  examples/rust/minimal_serve/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/shared_recording/Cargo.toml
  examples/rust/spawn_viewer/Cargo.toml
  examples/rust/stdio/Cargo.toml
  examples/rust/template/Cargo.toml
  rerun_py/README.md
  scripts/clippy_wasm/clippy.toml
  scripts/lint.py
  tests/rust/plot_dashboard_stress/Cargo.toml
Labels: 🪳 bug, 📖 documentation, include in changelog

#5194 Fix example --help texts for some python examples
  examples/python/car/main.py
  examples/python/dicom_mri/main.py
  examples/python/minimal_options/main.py
  examples/python/multithreading/main.py
  examples/python/open_photogrammetry_format/main.py
  examples/python/rgbd/main.py
Labels: examples, exclude from changelog

#5192 Lift point cloud size limitations
  crates/re_renderer/shader/point_cloud.wgsl
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/re_renderer/src/draw_phases/picking_layer.rs
  crates/re_renderer/src/draw_phases/screenshot.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/texture_info.rs
  crates/re_renderer_examples/2d.rs
  crates/re_renderer_examples/depth_cloud.rs
  crates/re_renderer_examples/multiview.rs
  crates/re_renderer_examples/picking.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_viewer_context/src/space_view/mod.rs
Labels: 🔺 re_renderer, include in changelog

#5197 Bump maturin to 1.14.0
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_publish_wheels.yml
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
Labels: dependencies, include in changelog

#5163 Context Menu 1: Basic scaffolding and simple actions
  Cargo.lock
  Cargo.toml
  crates/re_viewport/src/context_menu.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#5199 Clear all blueprints in RAM and on disk when clicking "Reset Viewer"
  crates/re_ui/src/command.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/store_hub.rs
  crates/rerun/src/run.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, include in changelog

#5200 Update `tungstenite` to remove RUSTSEC warning
  Cargo.lock
  Cargo.toml
  crates/re_ws_comms/Cargo.toml
  deny.toml
Labels: dependencies, include in changelog

#5201 Link to app.rerun.io from examples page
  examples/manifest.toml
Labels: 📖 documentation, examples, exclude from changelog

#5202 Trim list of short-comings in README.md
  README.md
Labels: 📖 documentation, exclude from changelog

#4780 Documentation search index
  .gitignore
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/re_build_examples/src/example.rs
  crates/re_build_examples/src/lib.rs
  crates/re_build_examples/src/main.rs
  crates/re_build_examples/src/manifest.rs
  crates/re_build_examples/src/rrd.rs
  crates/re_build_search_index/Cargo.toml
  crates/re_build_search_index/README.md
  crates/re_build_search_index/src/build.rs
  crates/re_build_search_index/src/ingest.rs
  crates/re_build_search_index/src/ingest/cpp.rs
  crates/re_build_search_index/src/ingest/docs.rs
  crates/re_build_search_index/src/ingest/examples.rs
  crates/re_build_search_index/src/ingest/python.rs
  crates/re_build_search_index/src/ingest/rust.rs
  crates/re_build_search_index/src/main.rs
  crates/re_build_search_index/src/meili.rs
  crates/re_build_search_index/src/repl.rs
  crates/re_build_search_index/src/util.rs
  deny.toml
  docs/cspell.json
  pixi.lock
  pixi.toml
  rerun_cpp/docs/Doxyfile
  rerun_py/docs/gen_common_index.py
  rerun_py/requirements-doc.txt
Labels: 📖 documentation, exclude from changelog

#5188 Less restrictive visualizability constraints of 2d entitites, improved space view generation heuristics
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/spatial_topology.rs
  tests/python/release_checklist/check_heuristics_2d.py
  tests/python/release_checklist/check_heuristics_mixed_2d_and_3d.py
Labels: 📺 re_viewer, include in changelog

#5209 Focus on current bounding-box when resetting camera-eye on a 3D space view (double click it)
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 📺 re_viewer, include in changelog

#5216 New linkinator exceptions
  .github/workflows/documentation.yaml
Labels: exclude from changelog, :ship: CI

#5205 Context menu 2: add support for multiple selection
  crates/re_ui/src/list_item.rs
  crates/re_viewport/src/context_menu.rs
  tests/python/release_checklist/check_context_menu.py
Labels: ui, include in changelog

#5218 Simplify the tensor dimension drag-and-drop code
  crates/re_space_view_tensor/src/tensor_dimension_mapper.rs
Labels: ui, 🚜 refactor, exclude from changelog

#5210 Context menu 3: add "Move to new container" context menu action
  crates/re_viewport/src/context_menu.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  tests/python/release_checklist/check_context_menu.py
Labels: ui, include in changelog

#5215 Add experimental setting flag to always enable visualizer selection
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 📺 re_viewer, exclude from changelog

#5225 Remove now unnecessary unsafe Send/Sync impls for CpuWriteGpuReadBuffer
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#5207 Lift line vertex/strip count limitations
  crates/re_renderer/shader/lines.wgsl
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/data_texture_source.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/lib.rs
  crates/re_renderer/src/line_drawable_builder.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer/src/resource_managers/resource_manager.rs
  crates/re_renderer_examples/2d.rs
  crates/re_renderer_examples/depth_cloud.rs
  crates/re_renderer_examples/multiview.rs
  crates/re_renderer_examples/picking.rs
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/contexts/shared_render_builders.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_viewer_context/src/space_view/mod.rs
Labels: 🔺 re_renderer, include in changelog

#5220 Clickable path parts in selection-panel
  crates/re_data_ui/src/item_ui.rs
  crates/re_ui/src/syntax_highlighting.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, include in changelog

#5236 Fix broken link in the installing-viewer documentation
  docs/content/getting-started/installing-viewer.md
Labels: 📖 documentation, include in changelog

#5229 More robust handling of maximum texture size for non-color data, slight perf improvements for large point clouds
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/data_texture_source.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/line_drawable_builder.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/point_cloud.rs
  crates/re_renderer_examples/2d.rs
  crates/re_renderer_examples/depth_cloud.rs
  crates/re_renderer_examples/multiview.rs
  crates/re_renderer_examples/picking.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
Labels: 🔺 re_renderer, 📉 performance, 🚜 refactor, include in changelog

#5235 Fix ugly UI for some arrow data
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_ui/src/design_tokens.rs
Labels: 🪳 bug, ui, 📺 re_viewer, include in changelog

#5240 Use `DataTextureSource` for lines
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/allocator/data_texture_source.rs
  crates/re_renderer/src/allocator/mod.rs
  crates/re_renderer/src/line_drawable_builder.rs
  crates/re_renderer/src/point_cloud_builder.rs
  crates/re_renderer/src/renderer/lines.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer/src/renderer/point_cloud.rs
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#5243 Do not implement `Borrow` for our interned string (footgun)
  Cargo.lock
  crates/re_string_interner/Cargo.toml
  crates/re_string_interner/src/lib.rs
  crates/re_types_core/src/arrow_string.rs
Labels: 🪳 bug, exclude from changelog

#5244 Add STL mesh support
  Cargo.lock
  Cargo.toml
  crates/re_data_source/src/lib.rs
  crates/re_renderer/Cargo.toml
  crates/re_renderer/src/importer/mod.rs
  crates/re_renderer/src/importer/stl.rs
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/mesh_loader.rs
  crates/re_types/definitions/rerun/archetypes/asset3d.fbs
  crates/re_types/src/archetypes/asset3d.rs
  crates/re_types/src/components/media_type_ext.rs
  docs/code-examples/all/asset3d_simple.cpp
  docs/code-examples/all/asset3d_simple.py
  docs/code-examples/all/asset3d_simple.rs
  docs/content/reference/types/archetypes/asset3d.md
  docs/cspell.json
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d_ext.cpp
  rerun_cpp/src/rerun/components/media_type.hpp
  rerun_cpp/src/rerun/components/media_type_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d_ext.py
  rerun_py/rerun_sdk/rerun/components/media_type_ext.py
Labels: 🔺 re_renderer, 📺 re_viewer, include in changelog

#5245 Don't show the blueprint section when selecting recordings
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, include in changelog

#5228 Track crate dependency count over time
  .github/workflows/reusable_track_size.yml
  rerun_cpp/src/rerun/c/rerun.h
  scripts/ci/compare.py
  scripts/ci/count_bytes.py
  scripts/ci/count_dependencies.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#5246 Use the same icon for recordings everywhere
  crates/re_viewer/src/ui/recordings_panel.rs
Labels: ui, include in changelog

#5252 Remove `build.rs` for the web viewer
  .cargo/config.toml
  BUILD.md
  Cargo.lock
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/README.md
  crates/re_web_viewer_server/build.rs
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#5214 Add example visualizing RRT*
  .vscode/settings.json
  docs/cspell.json
  examples/python/requirements.txt
  examples/python/rrt-star/README.md
  examples/python/rrt-star/main.py
  examples/python/rrt-star/requirements.txt
Labels: examples, exclude from changelog

#5263 Remove setup_web script - pixi handles everything except wasm anyways already
  BUILD.md
  crates/re_build_web_viewer/src/lib.rs
  crates/re_sdk/Cargo.toml
  crates/rerun-cli/Cargo.toml
  crates/rerun/Cargo.toml
  pixi.toml
  rerun_py/Cargo.toml
  scripts/setup.sh
  scripts/setup_web.sh
Labels: 🧑‍💻 dev experience, exclude from changelog

#5262 Fix missing redraw upon resetting blueprint
  crates/re_viewer/src/app.rs
  examples/python/rrt-star/README.md
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5269 Add missing python docs for `disable_timeline` & `reset_time`
  rerun_py/docs/gen_common_index.py
Labels: 🪳 bug, 📖 documentation, 🐍 Python API, include in changelog

#5270 Fix missing error message when passing `from_parent` + rerun transform type to `rerun.Transform3D`
  rerun_py/rerun_sdk/rerun/archetypes/transform3d_ext.py
  rerun_py/tests/unit/test_transform3d.py
Labels: 🪳 bug, 🐍 Python API, 😤 annoying, include in changelog

#5273 Optimized cpu time for 3D point clouds (once again!)
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#5272 Remove gratuitous profiler scopes.
  BUILD.md
  crates/re_query/src/query.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  crates/re_viewer_context/src/tensor/tensor_stats_cache.rs
Labels: 🚜 refactor, exclude from changelog

#5211 Lock the web-sys version to 0.3.67
  Cargo.toml
Labels: dependencies, include in changelog

#5274 Only compute store/caching stats when the memory panel is opened
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: 🧑‍💻 dev experience, 📉 performance, include in changelog

#5266 Fix indeterministic redundancy check for space view spawning heuristic
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_viewport/src/viewport.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5271 Query caching for pinhole querying in transform context
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
Labels: 📉 performance, 🚜 refactor, exclude from changelog

#5279 Fix banding artifacts of 3D space view's skybox
  crates/re_renderer/shader/generic_skybox.wgsl
Labels: enhancement, 🔺 re_renderer, include in changelog

#5249 Add first person 3D eye-camera
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 📺 re_viewer, include in changelog

#5281 Fix `cargo doc` on CI
  crates/re_web_viewer_server/Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5265 Context menu 4: add "Clone space view" action
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/context_menu.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  tests/python/release_checklist/check_context_menu.py
Labels: ui, include in changelog

#5282 Increase the max WebSocket frame limit for the native client
  Cargo.lock
  Cargo.toml
  crates/re_ws_comms/src/client.rs
Labels: dependencies, include in changelog

#5284 Fix `spawn` starting the viewer even if logging is disabled
  crates/re_sdk/src/recording_stream.rs
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 🪳 bug, include in changelog, 🪵 Log-API

#5289 Context menu 5: refactor into multiple files
  crates/re_viewport/src/context_menu/container_and_space_view_actions.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/context_menu/utils.rs
Labels: 🚜 refactor, include in changelog

#5241 Add Gesture Recognition example
  docs/cspell.json
  examples/manifest.toml
  examples/python/gesture_detection/.gitignore
  examples/python/gesture_detection/README.md
  examples/python/gesture_detection/main.py
  examples/python/gesture_detection/requirements.txt
  examples/python/requirements.txt
Labels: examples, include in changelog

#5287 Fix resetting vertical axis when using non-uniform zoom on Time Series
  crates/re_space_view_time_series/src/space_view_class.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5286 Viewers started with `spawn` no longer inherit stdin, ignore errors on version check
  crates/re_sdk/src/spawn.rs
Labels: 🪳 bug, exclude from changelog

#5308 Fix regression in line selection rendering
  crates/re_renderer/src/line_drawable_builder.rs
Labels: 🔺 re_renderer, 🦟 regression, exclude from changelog

#5267 Strongly-typed analytics
  crates/re_analytics/README.md
  crates/re_analytics/examples/end_to_end.rs
  crates/re_analytics/src/cli.rs
  crates/re_analytics/src/event.rs
  crates/re_analytics/src/lib.rs
  crates/re_analytics/src/native/pipeline.rs
  crates/re_analytics/src/native/sink.rs
  crates/re_analytics/src/posthog.rs
  crates/re_analytics/src/web/pipeline.rs
  crates/re_crash_handler/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_viewer/src/viewer_analytics/event.rs
  crates/re_viewer/src/viewer_analytics/mod.rs
  crates/re_viewer/src/web.rs
  crates/re_web_viewer_server/src/lib.rs
Labels: 📊 analytics, exclude from changelog

#5314 Implement `enum` codegen for C++
  CMakeLists.txt
  crates/re_types/definitions/rerun/datatypes/angle.fbs
  crates/re_types/definitions/rerun/datatypes/rotation3d.fbs
  crates/re_types/definitions/rerun/datatypes/scale3d.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/re_types/definitions/rerun/datatypes/transform3d.fbs
  crates/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/re_types_builder/src/bin/build_re_types.rs
  crates/re_types_builder/src/codegen/cpp/array_builder.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/deserializer.rs
  crates/re_types_builder/src/codegen/rust/serializer.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
Labels: codegen/idl, exclude from changelog
