Repository rerun-io/rerun, pull requests merged in 2024-01, with the labels that each got.

#4583 Python SDK: introduce deferred garbage collection queue
  Cargo.lock
  crates/re_log_types/src/arrow_msg.rs
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/buffered_client.rs
  rerun_py/Cargo.toml
  rerun_py/src/python_bridge.rs
  tests/python/gil_stress/main.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#4626 Forbid calling blocking functions in wasm
  clippy.toml
  crates/re_smart_channel/src/receiver.rs
  scripts/clippy_wasm/clippy.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#4619 Account for new space-views when de-duplicating space-view names
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🦟 regression, 🟦 blueprint, exclude from changelog

#4618 In the blueprint tree only show data results starting with the first interesting node
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🟦 blueprint, exclude from changelog

#4632 Remove redundant wheels folder from upload script
  scripts/ci/build_and_upload_wheels.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#4639 Fix example.toml to include all examples on website again
  examples/manifest.toml
Labels: examples, 🦟 regression, exclude from changelog

#4645 Update `egui_plot` to fix auto-bounds bug
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog

#4641 Remove `cache/` from gitignore + fix resulting lints
  .gitignore
  ARCHITECTURE.md
  crates/re_query_cache/README.md
Labels: 🪳 bug, 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#4653 Diagram in docs/index has full color for C++
  docs/content/index.md
Labels: 📖 documentation, exclude from changelog

#4643 Fix group selection/hover with data queries
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#4657 Add overview diagram of external data loaders
  docs/content/howto/open-any-file.md
Labels: 📖 documentation, exclude from changelog

#4640 Fix incorrect bounding box calculation for camera view parts
  crates/re_space_view_spatial/src/parts/cameras.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 📺 re_viewer, include in changelog

#4660 Hide entity filter DSL behind a feature flag
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/app_options.rs
Labels: ui, exclude from changelog

#4642 Make the new container blueprints the default behavior
  Cargo.lock
  Cargo.toml
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🟦 blueprint, include in changelog

#4661 Improve Rerun Menu with link to Rerun Discord
  crates/re_space_view_spatial/src/ui.rs
  crates/re_ui/data/icons/discord.png
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/rerun_menu.rs
Labels: ui, include in changelog

#4658 Fix wrong RowId order of logged data
  crates/re_log_types/src/arrow_msg.rs
  crates/re_log_types/src/data_table_batcher.rs
  crates/re_sdk/src/recording_stream.rs
  crates/rerun/tests/rerun_tests.rs
  rerun_py/src/python_bridge.rs
Labels: 🪳 bug, 📉 performance, include in changelog

#4648 Improve shading with two lights instead of one
  crates/re_renderer/shader/instanced_mesh.wgsl
Labels: 🔺 re_renderer, include in changelog

#4663 Introduce container icons and update space views and UI icons
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_ui/data/icons/add.png
  crates/re_ui/data/icons/arrow_left.png
  crates/re_ui/data/icons/arrow_right.png
  crates/re_ui/data/icons/close.png
  crates/re_ui/data/icons/container_grid.png
  crates/re_ui/data/icons/container_horizontal.png
  crates/re_ui/data/icons/container_tabs.png
  crates/re_ui/data/icons/container_vertical.png
  crates/re_ui/data/icons/external_link.png
  crates/re_ui/data/icons/follow.png
  crates/re_ui/data/icons/invisible.png
  crates/re_ui/data/icons/loop.png
  crates/re_ui/data/icons/maximize.png
  crates/re_ui/data/icons/minimize.png
  crates/re_ui/data/icons/pause.png
  crates/re_ui/data/icons/play.png
  crates/re_ui/data/icons/remove.png
  crates/re_ui/data/icons/reset.png
  crates/re_ui/data/icons/spaceview_2d.png
  crates/re_ui/data/icons/spaceview_3d.png
  crates/re_ui/data/icons/spaceview_chart.png
  crates/re_ui/data/icons/spaceview_dataframe.png
  crates/re_ui/data/icons/spaceview_generic.png
  crates/re_ui/data/icons/spaceview_histogram.png
  crates/re_ui/data/icons/spaceview_log.png
  crates/re_ui/data/icons/spaceview_raw.png
  crates/re_ui/data/icons/spaceview_scatterplot.png
  crates/re_ui/data/icons/spaceview_tensor.png
  crates/re_ui/data/icons/spaceview_text.png
  crates/re_ui/data/icons/spaceview_timeseries.png
  crates/re_ui/data/icons/spaceview_unknown.png
  crates/re_ui/data/icons/visible.png
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: ui, include in changelog

#4662 Entity query editor: simplify button presentation logic
  crates/re_viewport/src/space_view_entity_picker.rs
Labels: ui, exclude from changelog

#4636 Limit server memory
  Cargo.lock
  crates/re_memory/src/memory_limit.rs
  crates/re_sdk/Cargo.toml
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk/src/web_viewer.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer/src/web.rs
  crates/re_ws_comms/Cargo.toml
  crates/re_ws_comms/src/server.rs
  crates/rerun/src/clap.rs
  crates/rerun/src/run.rs
  examples/rust/custom_space_view/src/main.rs
  examples/rust/extend_viewer_ui/src/main.rs
  examples/rust/minimal_serve/src/main.rs
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
  scripts/check.sh
Labels: 📉 performance, include in changelog

#4668 Make scroll-to-zoom a lot more responsive in 3D views
  crates/re_space_view_spatial/src/eye.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#4667 Fix container/spaceview visibillity toggle
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/container_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/space_view_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/visible.fbs
  crates/re_types/src/blueprint/archetypes/space_view_blueprint.rs
  crates/re_types/src/blueprint/components/.gitattributes
  crates/re_types/src/blueprint/components/mod.rs
  crates/re_types/src/blueprint/components/visible.rs
  crates/re_viewport/src/blueprint/archetypes/container_blueprint.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/space_view_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/space_view_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/visible.cpp
  rerun_cpp/src/rerun/blueprint/components/visible.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/container_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/space_view_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/visible.py
Labels: ui, 🦟 regression, 🟦 blueprint, exclude from changelog

#4616 Initial support for manually adding container and space view in the hierarchy
  crates/re_ui/data/icons/add_big.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/add_space_view_or_container_modal.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, 📺 re_viewer, include in changelog

#4675 Update `egui_tiles` and `sysinfo` crates
  Cargo.lock
  Cargo.toml
  crates/re_memory/src/ram_warner.rs
Labels: dependencies, exclude from changelog

#4679 Fix heuristic object properties being broken in some cases / fix DepthMeter being ignored sometimes
  crates/re_entity_db/src/entity_properties.rs
  crates/re_space_view_spatial/src/heuristics.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#4697 Declare that the Python package doesn't support Python 3.12
  rerun_py/pyproject.toml
Labels: 🐍 Python API, exclude from changelog

#4676 Benchmark data store insertion using same timepoint
  crates/re_data_store/benches/arrow2.rs
  crates/re_data_store/benches/data_store.rs
Labels: 📉 performance, exclude from changelog

#4691 Fix arrow bench crashing due to reliance on `mem::size_of`
  crates/re_data_store/benches/arrow2.rs
  crates/re_types/src/components/position2d_ext.rs
  crates/re_types/src/datatypes/vec2d_ext.rs
  crates/re_types/src/testing/components/affix_fuzzer1_ext.rs
  crates/re_types/src/testing/components/mod.rs
  crates/re_types/src/testing/datatypes/affix_fuzzer1_ext.rs
  crates/re_types/src/testing/datatypes/flattened_scalar_ext.rs
  crates/re_types/src/testing/datatypes/mod.rs
  crates/re_types_core/src/arrow_buffer.rs
  crates/re_types_core/src/arrow_string.rs
  crates/re_types_core/src/components/instance_key_ext.rs
Labels: 🪳 bug, 🔨 testing, exclude from changelog

#4699 Fix screenshot command taking several screenshots at once
  crates/re_viewer/src/screenshotter.rs
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#4677 Update roadmap in docs
  docs/content/reference/roadmap.md
  docs/cspell.json
Labels: 📖 documentation, exclude from changelog

#4688 Reflect visibillity in the container tree and fix blueprint-edit-loop
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🟦 blueprint, exclude from changelog

#4703 Lint against double-spaces.
  crates/re_data_ui/src/item_ui.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/buffered_client.rs
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_time_panel/src/time_axis.rs
  design/blueprint_store.md
  design/component_datatypes.md
  docs/code-examples/README.md
  docs/content/concepts/batches.md
  docs/content/concepts/spaces-and-transforms.md
  docs/content/getting-started/python.md
  docs/content/getting-started/viewer-walkthrough.md
  docs/content/howto/notebook.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/howto/shared-recordings.md
  docs/content/reference/migration-0-9.md
  examples/python/arkit_scenes/main.py
  pixi.toml
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/components/tensor_data.hpp
  rerun_cpp/src/rerun/components/tensor_data_ext.cpp
  rerun_cpp/tests/archetypes/transform3d.cpp
  rerun_py/rerun_sdk/rerun/__init__.py
  scripts/lint.py
Labels: 🧑‍💻 dev experience, 😤 annoying, exclude from changelog

#4686 Persist Auto vs Columns for Grid into the Blueprint
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/container_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/grid_columns.fbs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/blueprint/archetypes/container_blueprint.rs
  crates/re_viewport/src/blueprint/components/.gitattributes
  crates/re_viewport/src/blueprint/components/grid_columns.rs
  crates/re_viewport/src/blueprint/components/mod.rs
  crates/re_viewport/src/container.rs
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/grid_columns.cpp
  rerun_cpp/src/rerun/blueprint/components/grid_columns.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/container_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/grid_columns.py
Labels: 🟦 blueprint, exclude from changelog

#4700 Change modal position to a fixed vertical distance from the top of the window
  crates/re_ui/src/modal.rs
Labels: ui, include in changelog

#4707 Workaround for objectron spatial heuristics sometimes failing on startup
  examples/python/objectron/main.py
Labels: 🪳 bug, examples, exclude from changelog

#4696 Fix 2D images showing up in 3D space views again
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/visualizer_system.rs
  crates/re_viewport/src/lib.rs
  scripts/lint.py
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#4146 Add support for Python 3.12
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  examples/python/controlnet/requirements.txt
  examples/python/depth_guided_stable_diffusion/requirements.txt
  examples/python/detect_and_track_objects/requirements.txt
  examples/python/llm_embedding_ner/requirements.txt
  examples/python/segment_anything_model/requirements.txt
  examples/python/signed_distance_fields/requirements.txt
  noxfile.py
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
  rerun_py/requirements-build.txt
  rerun_py/requirements-lint.txt
  scripts/requirements-dev.txt
  scripts/run_all.py
Labels: 🐍 Python API, include in changelog

#4709 Maintain the blueprint validator via codegen
  crates/re_entity_db/src/lib.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/codegen/rust/blueprint_validation.rs
  crates/re_types_builder/src/codegen/rust/mod.rs
  crates/re_viewer/src/.gitattributes
  crates/re_viewer/src/blueprint/mod.rs
  crates/re_viewer/src/blueprint/validation.rs
  crates/re_viewer/src/blueprint/validation_gen/.gitattributes
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/re_viewer/src/blueprint_validation.rs
  crates/re_viewer/src/lib.rs
  crates/re_viewer/src/store_hub.rs
Labels: 🟦 blueprint, exclude from changelog

#4719 Allow dashes and underscores in file names
  CODE_STYLE.md
  RELEASES.md
  crates/re_build_web_viewer/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/rerun-cli/src/bin/rerun.rs
Labels: exclude from changelog

#4728 2D visualizers are no longer applicable to paths that are behind a pinhole camera other than the space's origin
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
Labels: 🪳 bug, exclude from changelog

#4735 Introduce a new "release" channel for examples and use it on explicitly released versions
  .github/workflows/reusable_publish_web.yml
  crates/re_build_examples/src/example.rs
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  examples/python/detect_and_track_objects/README.md
  examples/python/nuscenes/README.md
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/segment_anything_model/README.md
Labels: examples, exclude from changelog

#4736 Don't generate used-by doc links for blueprint components
  crates/re_types_builder/src/codegen/docs/mod.rs
  docs/content/reference/types/datatypes/entity_path.md
  docs/content/reference/types/datatypes/uuid.md
Labels: 📖 documentation, 🟦 blueprint, exclude from changelog

#4720 Unify `web_viewer/index.html` and `index_bundled.html`
  crates/re_web_viewer_server/Cargo.toml
  crates/re_web_viewer_server/src/lib.rs
  web_viewer/index.html
  web_viewer/index_bundled.html
Labels: 🕸️ web, 🧑‍💻 dev experience, include in changelog

#4740 Web: Support multiple `.rrd` URLs
  crates/re_log/src/setup.rs
  crates/re_log_encoding/src/stream_rrd_from_http.rs
  crates/re_smart_channel/src/receive_set.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/web.rs
  rerun_js/web-viewer/index.js
  rerun_js/web-viewer/package.json
  rerun_js/web-viewer/react/index.js
Labels: 🕸️ web, include in changelog

#4749 Default to DEBUG log level in debug builds
  crates/re_log/src/setup.rs
Labels: 🧑‍💻 dev experience, include in changelog, CLI

#4745 Fill in missing example description test snippets
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/segment_anything_model/README.md
  examples/rust/objectron/README.md
  examples/rust/raw_mesh/README.md
Labels: 🪳 bug, examples, exclude from changelog

#4751 Tweak the description of the NYUD example
  examples/python/rgbd/README.md
Labels: 📖 documentation, exclude from changelog

#4757 Fix the material templates which were broken by auto-formatting
  .prettierignore
  rerun_py/docs/templates/python/material/class.html
  rerun_py/docs/templates/python/material/function.html
Labels: 📖 documentation, 🦟 regression, exclude from changelog

#4753 Add math type conversions to `mint` types
  Cargo.lock
  Cargo.toml
  crates/re_types/Cargo.toml
  crates/re_types/src/components/half_sizes2d_ext.rs
  crates/re_types/src/components/half_sizes3d_ext.rs
  crates/re_types/src/components/pinhole_projection_ext.rs
  crates/re_types/src/components/position2d_ext.rs
  crates/re_types/src/components/position3d_ext.rs
  crates/re_types/src/components/rotation3d_ext.rs
  crates/re_types/src/components/vector2d_ext.rs
  crates/re_types/src/components/vector3d_ext.rs
  crates/re_types/src/datatypes/mat3x3_ext.rs
  crates/re_types/src/datatypes/mat4x4_ext.rs
  crates/re_types/src/datatypes/mod.rs
  crates/re_types/src/datatypes/quaternion_ext.rs
  crates/re_types/src/datatypes/rotation3d_ext.rs
  crates/re_types/src/datatypes/rotation_axis_angle_ext.rs
  crates/re_types/src/datatypes/vec2d_ext.rs
  crates/re_types/src/datatypes/vec3d_ext.rs
  crates/re_types/src/datatypes/vec4d_ext.rs
  crates/re_types/tests/mint_conversions.rs
  crates/rerun/Cargo.toml
Labels: enhancement, 🦀 Rust API, include in changelog

#4762 Warn on duplicated data-loader in PATH
  crates/re_data_source/src/data_loader/loader_external.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#4732 Update to egui 0.25 and winit 0.29
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/data.rs
  crates/re_renderer/src/error_handling/error_tracker.rs
  crates/re_renderer_examples/2d.rs
  crates/re_renderer_examples/Cargo.toml
  crates/re_renderer_examples/depth_cloud.rs
  crates/re_renderer_examples/depth_offset.rs
  crates/re_renderer_examples/framework.rs
  crates/re_renderer_examples/multiview.rs
  crates/re_renderer_examples/outlines.rs
  crates/re_renderer_examples/picking.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_ui/src/command.rs
  crates/re_ui/src/command_palette.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewport/src/viewport.rs
  deny.toml
Labels: 📺 re_viewer, dependencies, include in changelog

#4761 Click a recording to select it
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/item.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/store_id.rs
  crates/re_log_types/src/path/component_path.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/data/icons/store.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewer_context/src/store_context.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: ui, include in changelog

#4759 Use thiserror in re_renderer everywhere except shader file reloading
  crates/re_renderer/src/config.rs
  crates/re_renderer/src/importer/gltf.rs
  crates/re_renderer/src/importer/obj.rs
  crates/re_renderer/src/renderer/mesh_renderer.rs
  crates/re_renderer/src/view_builder.rs
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#4760 Improve documentation of the `Clear` archetype
  crates/re_types/definitions/rerun/archetypes/clear.fbs
  crates/re_types_core/src/archetypes/clear.rs
  docs/content/reference/types/archetypes/clear.md
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
Labels: 📖 documentation, include in changelog

#4766 Fix `entity_path_vec!` and `entity_path!` depending on `ToString` being in scope.
  crates/re_log_types/src/path/mod.rs
Labels: 🦀 Rust API, include in changelog

#4768 Lint all python code
  justfile
  noxfile.py
  rerun_py/pyproject.toml
  scripts/fast_lint.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#4770 Fix CMake trying to pick up test folders outside of the Rerun project/zip
  rerun_cpp/CMakeLists.txt
Labels: 🪳 bug, 🌊 C++ API, include in changelog

#4771 Replace `warn` logging with `debug` logging for dangerous looking {under|over}flows
  crates/re_data_store/src/store_gc.rs
  crates/re_entity_db/src/entity_tree.rs
  crates/re_entity_db/src/time_histogram_per_timeline.rs
  crates/re_entity_db/src/times_per_timeline.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#4659 Primary caching 3: barebone latest-at caching
  Cargo.lock
  Cargo.toml
  crates/re_data_store/src/store_read.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_log_types/benches/vec_deque_ext.rs
  crates/re_log_types/src/time_range.rs
  crates/re_log_types/src/vec_deque_ext.rs
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/lib.rs
  crates/re_query_cache/Cargo.toml
  crates/re_query_cache/benches/latest_at.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/lib.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/tests/latest_at.rs
Labels: 🔍 re_query, 📉 performance, include in changelog

#4680 Primary caching 4: runtime toggle support
  crates/re_data_store/src/store_read.rs
  crates/re_query_cache/benches/latest_at.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4681 Primary caching 5: 2D & 3D point clouds
  Cargo.lock
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_types/definitions/rerun/components/instance_key.fbs
  crates/re_types_core/Cargo.toml
  crates/re_types_core/src/components/instance_key.rs
Labels: 🔍 re_query, 📉 performance, include in changelog

#4698 Primary caching 6: TextLogs & TimeSeries
  Cargo.lock
  crates/re_query_cache/src/lib.rs
  crates/re_space_view_text_log/Cargo.toml
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_types/definitions/rerun/archetypes/text_log.fbs
  crates/re_types/src/archetypes/text_log.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
  docs/content/reference/types/archetypes/text_log.md
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, include in changelog

#4776 Update to pyo3 0.20.2
  Cargo.lock
  Cargo.toml
  rerun_py/src/python_bridge.rs
Labels: dependencies, exclude from changelog

#4775 Rename `code-examples/roundtrips.py` to `compare_code_example_output.py`
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_test_wheels.yml
  docs/code-examples/README.md
  docs/code-examples/compare_code_example_output.py
  noxfile.py
  scripts/fast_lint.py
  scripts/roundtrip_utils.py
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#4786 Improve error handling in codegen
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/python.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/objects.rs
Labels: 🧑‍💻 dev experience, codegen/idl, exclude from changelog

#4796 Click a spatial space view background to select the space view
  crates/re_space_view_spatial/src/ui.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#4795 Use rr.Transform3D in Spaces and Transforms doc
  docs/content/concepts/spaces-and-transforms.md
Labels: 📖 documentation, exclude from changelog

#4801 Replace some of our use of `polars`
  Cargo.lock
  crates/re_data_store/src/store_dump.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_store/tests/dump.rs
  crates/re_log_types/src/data_cell.rs
  crates/re_log_types/src/example_components.rs
  crates/re_query/Cargo.toml
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/query.rs
  crates/re_query/tests/archetype_query_tests.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_query/tests/common/mod.rs
  crates/re_query/tests/type_tests.rs
Labels: dependencies, 🚜 refactor, exclude from changelog

#4711 Primary caching 7: Always expose the data time in query responses
  crates/re_data_store/benches/data_store.rs
  crates/re_data_store/src/polars_util.rs
  crates/re_data_store/src/store_helpers.rs
  crates/re_data_store/src/store_read.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/query.rs
  crates/re_query/src/range.rs
  crates/re_query/src/util.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_query/tests/archetype_visit_tests.rs
  crates/re_query_cache/src/query.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_viewer/src/blueprint/validation.rs
  crates/re_viewer_context/src/item.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 🔍 re_query, 📉 performance, do-not-merge, exclude from changelog

#4712 Primary caching 8: implement latest-at data-time cache entry deduplication
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/lib.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/tests/latest_at.rs
Labels: 🔍 re_query, 📉 performance, do-not-merge, exclude from changelog

#4721 Primary caching 9: timeless latest-at support
  crates/re_log_types/src/time_point/time_int.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/query.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4726 Primary caching 10: latest-at cache invalidation
  crates/re_data_store/src/store_subscriber.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4773 Primary caching 11: cache stats and integration with memory panel
  Cargo.lock
  crates/re_log_types/src/time_point/time_int.rs
  crates/re_memory/src/memory_history.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/cache_stats.rs
  crates/re_query_cache/src/flat_vec_deque.rs
  crates/re_query_cache/src/lib.rs
  crates/re_query_cache/src/query.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: 🧑‍💻 dev experience, 🔍 re_query, 📉 performance, do-not-merge, include in changelog

#4803 Syntax highlighting of entity paths and instance paths
  Cargo.lock
  crates/re_data_ui/src/item_ui.rs
  crates/re_ui/Cargo.toml
  crates/re_ui/src/lib.rs
  crates/re_ui/src/syntax_highlighting.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, 📺 re_viewer, include in changelog

#4808 Pin `numpy` to `<2` to avoid breakage upon release
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  pixi.toml
  rerun_py/pyproject.toml
  rerun_py/requirements-lint.txt
Labels: 🐍 Python API, dependencies, exclude from changelog

#4784 Primary caching 12: barebone range support
  crates/re_data_store/benches/arrow2.rs
  crates/re_log_types/src/example_components.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/lib.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/src/range.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_query_cache/tests/range.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 🔍 re_query, 📉 performance, include in changelog

#4785 Primary caching 13: stats & memory panel integration for range queries
  crates/re_data_store/src/store_format.rs
  crates/re_data_store/src/store_write.rs
  crates/re_log_types/src/time_point/timeline.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/cache_stats.rs
  crates/re_query_cache/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4793 Primary caching 14: don't bake `LatestAt(T-1)` results into low-level range queries
  crates/re_data_store/examples/range_components.rs
  crates/re_data_store/src/polars_util.rs
  crates/re_data_store/tests/data_store.rs
  crates/re_query/src/range.rs
  crates/re_query/tests/archetype_range_tests.rs
  crates/re_query_cache/tests/range.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_viewer/src/ui/visible_history.rs
Labels: 🔍 re_query, include in changelog, 🔩 data model

#4800 Primary caching 15: range read performance optimization
  crates/re_query_cache/src/range.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4797 Immediate compatiblity feedback for external loaders
  crates/re_data_source/src/data_loader/loader_external.rs
Labels: 🪳 bug, 😤 annoying, 📉 performance, include in changelog

#4814 Update container (and a couple other) icons
  crates/re_data_ui/src/item_ui.rs
  crates/re_ui/data/icons/container.png
  crates/re_ui/data/icons/container_grid.png
  crates/re_ui/data/icons/container_horizontal.png
  crates/re_ui/data/icons/container_tabs.png
  crates/re_ui/data/icons/container_vertical.png
  crates/re_ui/data/icons/group.png
  crates/re_ui/data/icons/loop.png
  crates/re_ui/data/icons/spaceview_2d.png
  crates/re_ui/data/icons/spaceview_3d.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4806 Execute PR-triggered cpp-upload only if there's no release label
  .github/workflows/on_pull_request.yml
  .github/workflows/reusable_publish_rerun_c.yml
Labels: exclude from changelog, :ship: CI

#4781 Always point to versioned manifest when building a versioned binary
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
Labels: 🪳 bug, ⛴ release, include in changelog

#4799 Double click on entity in blueprint & timepanel focuses camera on it in 3D space views
  crates/re_data_ui/src/item_ui.rs
  crates/re_space_view/src/controls.rs
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/scene_bounding_boxes.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/spatial_view_visualizer.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/viewer_context.rs
  tests/python/many_entities/main.py
Labels: enhancement, 📺 re_viewer, include in changelog

#4831 Clear selection when clicking blank space in the Blueprint View
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4822 Add support for full span highlighting to modal and use it in the "Add Space View or Container" modal
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/modal.rs
  crates/re_viewer/src/ui/add_space_view_or_container_modal.rs
Labels: ui, include in changelog

#4835 Version lock griffe to 0.39 and fix some doc errors
  rerun_py/requirements-doc.txt
  rerun_py/rerun_sdk/rerun/_log.py
Labels: 📖 documentation, exclude from changelog

#4682 Make space view names optional and subdue placeholder view label in the UI
  crates/re_data_ui/src/item_ui.rs
  crates/re_log_types/src/path/entity_path.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/ui/add_space_view_or_container_modal.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4834 Add `rerun --serve` and improve `--help`
  .github/workflows/labels.yml
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk/src/web_viewer.rs
  crates/re_ws_comms/src/client.rs
  crates/re_ws_comms/src/server.rs
  crates/rerun-cli/Cargo.toml
  crates/rerun/Cargo.toml
  crates/rerun/src/run.rs
  rerun_cpp/src/rerun/c/rerun.h
Labels: include in changelog, CLI

#4842 Indicate Mat3x3 and Mat4x4 constructors are column major
  rerun_cpp/src/rerun/datatypes/mat3x3.hpp
  rerun_cpp/src/rerun/datatypes/mat3x3_ext.cpp
  rerun_cpp/src/rerun/datatypes/mat4x4.hpp
  rerun_cpp/src/rerun/datatypes/mat4x4_ext.cpp
Labels: 📖 documentation, 🌊 C++ API, exclude from changelog

#4840 Fix external data loader plugins on Windows
  crates/re_data_source/src/data_loader/loader_external.rs
  docs/cspell.json
  examples/python/external_data_loader/README.md
Labels: 🪳 bug, 🪟 windows, include in changelog

#4841 Show download sizes of in the example page
  Cargo.lock
  Cargo.toml
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  deny.toml
Labels: ui, include in changelog

#4843 Document that in C++ PinholeProjection::from_mat3x3 is column major
  rerun_cpp/src/rerun/components/pinhole_projection.hpp
  rerun_cpp/src/rerun/components/pinhole_projection_ext.cpp
Labels: 📖 documentation, 🌊 C++ API, include in changelog

#4850 Bump h2 to 0.3.24
  Cargo.lock
Labels: dependencies, exclude from changelog

#4862 Update changelog for 0.12.1
  CHANGELOG.md
  RELEASES.md
  docs/cspell.json
Labels: ⛴ release, exclude from changelog

#4836 More rigorious evaluation of visualizable entities in spatial views using new `SpatialTopology` store subscriber
  Cargo.lock
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/lib.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/spatial_topology.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
Labels: enhancement, 📺 re_viewer, exclude from changelog

#4864 Use new egui_tiles `active_tiles` api to simplify space view multithreading
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport.rs
Labels: 📺 re_viewer, 🚜 refactor, exclude from changelog

#4847 Fix support for compressing mono images by respecting mode to determine depth
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/tests/unit/test_image_encoded.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#4870 Include LICENSE files into C++ SDK Assets
  scripts/ci/bundle_and_upload_rerun_cpp.py
Labels: 🌊 C++ API, include in changelog

#4871 re_query: remove `polars` and general dependency/features clean up
  Cargo.lock
  crates/re_data_store/Cargo.toml
  crates/re_entity_db/Cargo.toml
  crates/re_log_types/Cargo.toml
  crates/re_log_types/src/data_table.rs
  crates/re_log_types/src/lib.rs
  crates/re_query/Cargo.toml
  crates/re_query/src/archetype_view.rs
  crates/re_query/src/dataframe_util.rs
  crates/re_query/src/lib.rs
  crates/re_query/src/query.rs
  crates/re_query_cache/Cargo.toml
  crates/re_sdk/Cargo.toml
  crates/re_space_view/Cargo.toml
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#4872 Fix panic when failing to load RRD size
  crates/re_viewer/src/ui/welcome_screen/example_page.rs
Labels: exclude from changelog

#4609 New debug option to show an actual timeline for the Blueprint
  crates/re_data_ui/src/annotation_context.rs
  crates/re_data_ui/src/blueprint_data.rs
  crates/re_data_ui/src/component.rs
  crates/re_data_ui/src/component_path.rs
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/data.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/entity_path.rs
  crates/re_data_ui/src/image.rs
  crates/re_data_ui/src/image_meaning.rs
  crates/re_data_ui/src/instance_path.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/lib.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_data_ui/src/pinhole.rs
  crates/re_data_ui/src/rotation3d.rs
  crates/re_data_ui/src/store_id.rs
  crates/re_data_ui/src/transform3d.rs
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_time_panel/src/data_density_graph.rs
  crates/re_time_panel/src/lib.rs
  crates/re_time_panel/src/time_ranges_ui.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewer_context/src/time_control.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/blueprint/data_ui.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/mod.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🧑‍💻 dev experience, 🟦 blueprint, include in changelog

#4873 Post-0.12.1 release CI updates
  .github/workflows/release.yml
  scripts/ci/sync_release_assets.py
Labels: exclude from changelog, :ship: CI

#4851 Primary caching 16: context-free range semantics
  crates/re_data_store/src/polars_util.rs
  crates/re_data_store/tests/data_store.rs
  crates/re_query/src/range.rs
  crates/re_query/tests/archetype_range_tests.rs
  tests/rust/plot_dashboard_stress/Cargo.toml
Labels: 🔍 re_query, 📉 performance, include in changelog, 🔩 data model

#4852 Primary caching 17: timeless range
  crates/re_data_store/src/store_format.rs
  crates/re_data_store/src/store_read.rs
  crates/re_data_store/src/store_sanity.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_log_types/src/data_row.rs
  crates/re_log_types/src/time_point/time_int.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/cache_stats.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/range.rs
  crates/re_query_cache/tests/range.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4853 Primary caching 18: range invalidation (ENABLED BY DEFAULT :confetti_ball:)
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/cache_stats.rs
  crates/re_query_cache/src/flat_vec_deque.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/range.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_query_cache/tests/range.rs
  crates/re_viewer_context/src/app_options.rs
Labels: 🔍 re_query, 📉 performance, do-not-merge, exclude from changelog

#4856 Primary caching 19 (final): de-statification
  Cargo.lock
  crates/re_entity_db/Cargo.toml
  crates/re_entity_db/src/entity_db.rs
  crates/re_entity_db/src/entity_properties.rs
  crates/re_entity_db/src/lib.rs
  crates/re_query/Cargo.toml
  crates/re_query/src/lib.rs
  crates/re_query/src/util.rs
  crates/re_query_cache/Cargo.toml
  crates/re_query_cache/benches/latest_at.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/cache_stats.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/lib.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/src/range.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_query_cache/tests/range.rs
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: 🔍 re_query, 📉 performance, 🚜 refactor, exclude from changelog

#4880 Datatype deduplication 1: remove polars
  Cargo.lock
  Cargo.toml
  crates/re_data_store/Cargo.toml
  crates/re_data_store/examples/dump_dataframe.rs
  crates/re_data_store/examples/latest_component.rs
  crates/re_data_store/examples/latest_components.rs
  crates/re_data_store/examples/range_components.rs
  crates/re_data_store/src/arrow_util.rs
  crates/re_data_store/src/lib.rs
  crates/re_data_store/src/polars_util.rs
  crates/re_data_store/src/store.rs
  crates/re_data_store/src/store_polars.rs
  crates/re_data_store/src/store_read.rs
  crates/re_data_store/src/test_util.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_store/tests/data_store.rs
  crates/re_data_store/tests/dump.rs
  crates/re_data_store/tests/internals.rs
  crates/re_query/Cargo.toml
  crates/re_query/tests/store.rs
  deny.toml
Labels: dependencies, 🚜 refactor, exclude from changelog

#4892 Primary cache: do not err on `PrimaryNotFound`
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
Labels: 🪳 bug, 🔍 re_query, exclude from changelog

#4897 Fix code-example gen causing clippy warnings on windows
  docs/code-examples/build.rs
Labels: 🧑‍💻 dev experience, 🪟 windows, exclude from changelog

#4896 `Once` semantics for `setup_{web|native}_logging`
  crates/re_analytics/examples/end_to_end.rs
  crates/re_data_store/src/test_util.rs
  crates/re_data_store/tests/correctness.rs
  crates/re_data_store/tests/data_store.rs
  crates/re_data_store/tests/dump.rs
  crates/re_data_store/tests/internals.rs
  crates/re_entity_db/tests/clear.rs
  crates/re_log/src/lib.rs
  crates/re_log/src/multi_logger.rs
  crates/re_log/src/setup.rs
  crates/re_renderer_examples/framework.rs
  crates/re_types_builder/src/bin/build_re_types.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_viewer/src/web.rs
  crates/re_web_viewer_server/src/main.rs
  crates/rerun-cli/src/bin/rerun.rs
  crates/rerun_c/src/lib.rs
  examples/rust/clock/src/main.rs
  examples/rust/custom_data_loader/src/main.rs
  examples/rust/custom_space_view/src/main.rs
  examples/rust/custom_store_subscriber/src/main.rs
  examples/rust/extend_viewer_ui/src/main.rs
  examples/rust/minimal_options/src/main.rs
  examples/rust/objectron/src/main.rs
  examples/rust/raw_mesh/src/main.rs
  rerun_py/src/python_bridge.rs
  tests/rust/plot_dashboard_stress/src/main.rs
  tests/rust/roundtrips/annotation_context/src/main.rs
  tests/rust/roundtrips/arrows2d/src/main.rs
  tests/rust/roundtrips/arrows3d/src/main.rs
  tests/rust/roundtrips/boxes2d/src/main.rs
  tests/rust/roundtrips/boxes3d/src/main.rs
  tests/rust/roundtrips/depth_image/src/main.rs
  tests/rust/roundtrips/disconnected_space/src/main.rs
  tests/rust/roundtrips/image/src/main.rs
  tests/rust/roundtrips/line_strips2d/src/main.rs
  tests/rust/roundtrips/line_strips3d/src/main.rs
  tests/rust/roundtrips/pinhole/src/main.rs
  tests/rust/roundtrips/points2d/src/main.rs
  tests/rust/roundtrips/points3d/src/main.rs
  tests/rust/roundtrips/segmentation_image/src/main.rs
  tests/rust/roundtrips/tensor/src/main.rs
  tests/rust/roundtrips/text_document/src/main.rs
  tests/rust/roundtrips/text_log/src/main.rs
  tests/rust/roundtrips/transform3d/src/main.rs
  tests/rust/roundtrips/view_coordinates/src/main.rs
  tests/rust/test_api/src/main.rs
Labels: 🧑‍💻 dev experience, 😤 annoying, exclude from changelog

#4848 Add support for editing a space view's space origin
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewport/src/lib.rs
Labels: ui, include in changelog

#4879 Single-selection drag-and-drop demos
  Cargo.lock
  Cargo.toml
  crates/re_ui/Cargo.toml
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/list_item.rs
Labels: ui, exclude from changelog

#4902 pixi: make sure `py-plot-dashboard` depends on pixi's `py-build`
  pixi.toml
Labels: 🪳 bug, 🧑‍💻 dev experience, 😤 annoying, exclude from changelog

#4900 Migrate from `egui_Tile::TileId` to proper blueprint IDs in `ViewportBlueprint` API
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/add_space_view_or_container_modal.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/app_options.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, include in changelog

#4877 Support YUY2-encoded images
  crates/re_data_ui/src/image.rs
  crates/re_renderer/shader/decodings.wgsl
  crates/re_renderer/shader/rectangle.wgsl
  crates/re_renderer/shader/rectangle_fs.wgsl
  crates/re_renderer/shader/rectangle_vs.wgsl
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_tensor/src/tensor_slice_to_gpu.rs
  crates/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/re_types/src/datatypes/tensor_buffer.rs
  crates/re_types/src/datatypes/tensor_buffer_ext.rs
  crates/re_types/src/datatypes/tensor_data_ext.rs
  crates/re_types/src/tensor_data.rs
  crates/re_viewer_context/src/gpu_bridge/tensor_to_gpu.rs
  examples/python/nv12/main.py
  rerun_cpp/src/rerun/datatypes/tensor_buffer.cpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer_ext.cpp
  rerun_py/rerun_sdk/rerun/_image.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  tests/python/chroma_downsample_image/main.py
  tests/python/chroma_downsample_image/requirements.txt
Labels: 🔺 re_renderer, include in changelog

#4891 Primary cache: don't denormalize defaulted component values
  crates/re_data_store/benches/data_store.rs
  crates/re_query_cache/benches/latest_at.rs
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/query.rs
  crates/re_query_cache/src/range.rs
  crates/re_query_cache/tests/latest_at.rs
  crates/re_query_cache/tests/range.rs
  crates/re_space_view_spatial/benches/bench_points.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
Labels: 🔍 re_query, 📉 performance, exclude from changelog

#4904 Fix Rust examples and improve ci coverage
  .github/workflows/nightly.yml
  .github/workflows/reusable_checks.yml
  Cargo.lock
  crates/re_query/Cargo.toml
  crates/re_query_cache/Cargo.toml
  crates/re_renderer_examples/Cargo.toml
  crates/re_space_view/Cargo.toml
  crates/re_space_view_dataframe/Cargo.toml
  crates/re_space_view_text_log/Cargo.toml
  crates/re_viewer/src/viewer_analytics.rs
  crates/re_viewport/Cargo.toml
  crates/re_web_viewer_server/Cargo.toml
  crates/rerun-cli/Cargo.toml
  crates/rerun/Cargo.toml
  examples/rust/clock/Cargo.toml
  examples/rust/external_data_loader/src/main.rs
  examples/rust/minimal_options/Cargo.toml
  examples/rust/objectron/Cargo.toml
  examples/rust/raw_mesh/Cargo.toml
  examples/rust/raw_mesh/src/main.rs
  scripts/ci/rust_checks.py
  tests/rust/log_benchmark/Cargo.toml
  tests/rust/test_image_memory/Cargo.toml
Labels: 🪳 bug, exclude from changelog, :ship: CI

#4912 Fix missing dependency from too eager cargo machete + merge order issue
  Cargo.lock
  crates/re_space_view_text_log/Cargo.toml
Labels: 🪳 bug, 🧑‍💻 dev experience, exclude from changelog

#4865 Configurable dynamic plot aggregation based on zoom-level
  Cargo.lock
  crates/re_entity_db/src/entity_properties.rs
  crates/re_space_view_time_series/Cargo.toml
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
Labels: ui, 📺 re_viewer, 📉 performance, include in changelog

#4903 Random walk series for plot benchmark in python
  Cargo.lock
  Cargo.toml
  tests/cpp/plot_dashboard_stress/main.cpp
  tests/python/plot_dashboard_stress/main.py
  tests/rust/plot_dashboard_stress/Cargo.toml
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 📉 performance, exclude from changelog

#4920 Update to latest egui master
  Cargo.lock
  Cargo.toml
  crates/re_space_view_spatial/src/eye.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example.rs
Labels: dependencies, exclude from changelog

#4918 Improve documentation of re_memory crate
  crates/re_memory/README.md
  crates/re_memory/src/allocation_tracker.rs
  crates/re_memory/src/lib.rs
  crates/re_memory/src/memory_use.rs
  crates/re_memory/src/ram_warner.rs
  crates/re_memory/src/util.rs
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#4921 Fix C++ arrow build flag forwarding
  rerun_cpp/download_and_build_arrow.cmake
Labels: 🏹 arrow, 🌊 C++ API, include in changelog

#4913 Run taplo and typos always via pixi
  .github/workflows/auto_release_crates.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/release.yml
  .github/workflows/reusable_checks.yml
  justfile
  pixi.toml
  scripts/setup_dev.sh
  taplo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#4908 Notes on spatial transforms & spatial topology
  design/spatial_transforms.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#4924 [skip ci] fix trailing whitespace
  design/spatial_transforms.md
Labels: 🪳 bug, exclude from changelog

#4874 Improved automatic view creation heuristic, major speedup for scenes with many entities
  Cargo.lock
  crates/re_data_store/src/store_write.rs
  crates/re_entity_db/src/entity_tree.rs
  crates/re_log_types/src/path/entity_path_filter.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/heuristics.rs
  crates/re_space_view/src/lib.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/heuristics.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/spatial_topology.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/Cargo.toml
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/auto_spawn_heuristic.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/spawn_heuristics.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewer_context/src/typed_entity_collections.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport.rs
  examples/python/objectron/main.py
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  tests/python/many_entities/main.py
Labels: enhancement, 📉 performance, 🚜 refactor, include in changelog

#4930 Add support for removing container children from the selection panel
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, include in changelog

#4932 Optimize point clouds
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_space_view_spatial/src/visualizers/mod.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
Labels: 📉 performance, include in changelog

#4942 External loader: don't do process IO on compute threadpool
  crates/re_data_source/src/data_loader/loader_external.rs
Labels: 🪳 bug, 💣 crash, include in changelog

#4943 Make it easier to position 3D eye-camera center
  Cargo.lock
  crates/re_space_view_spatial/Cargo.toml
  crates/re_space_view_spatial/src/eye.rs
  crates/re_space_view_spatial/src/ui_3d.rs
Labels: 📺 re_viewer, include in changelog

#4914 Support modifying the plot style by introducing a generic framework for overriding components
  Cargo.lock
  crates/re_data_ui/src/component_ui_registry.rs
  crates/re_data_ui/src/editors.rs
  crates/re_data_ui/src/lib.rs
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_dataframe/src/visualizer_system.rs
  crates/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/re_space_view_spatial/src/visualizers/meshes.rs
  crates/re_space_view_spatial/src/visualizers/points2d.rs
  crates/re_space_view_spatial/src/visualizers/points3d.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_viewer/Cargo.toml
  crates/re_viewer/src/ui/mod.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/component_ui_registry.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewer_context/src/space_view/visualizer_system.rs
  crates/re_viewport/src/space_view.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 🟦 blueprint, include in changelog

#4951 Include tessellation and rendering in CPU time shown in top bar
  Cargo.lock
  Cargo.toml
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/memory_panel.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, include in changelog

#4949 Primary cache: fix crash when using `Clear`
  crates/re_query_cache/src/flat_vec_deque.rs
Labels: 🪳 bug, 💣 crash, exclude from changelog

#4927 Remove the "+" icon from the "Add SV/Container" modal and close on click
  crates/re_ui/data/icons/add_big.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/add_space_view_or_container_modal.rs
Labels: ui, include in changelog

#4950 Don't clear scalars in `face tracking` example
  examples/python/face_tracking/main.py
Labels: examples, 🚜 refactor, exclude from changelog

#4957 Break up plot charts when there's a `Clear`
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_types/definitions/rerun/archetypes/clear.fbs
  crates/re_types_core/src/archetypes/clear.rs
  docs/content/reference/types/archetypes/clear.md
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
Labels: ui, include in changelog, 🔩 data model

#4948 Primary cache: basic debug tools via command palette
  Cargo.lock
  crates/re_query_cache/Cargo.toml
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/cache_stats.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/range.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
Labels: 🧑‍💻 dev experience, 🔍 re_query, include in changelog

#4935 `DisconnectedSpace` now only applies to spatial space views
  crates/re_types/definitions/rerun/archetypes/disconnected_space.fbs
  crates/re_types/definitions/rerun/components/disconnected_space.fbs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_types/src/components/disconnected_space.rs
  docs/content/reference/types/archetypes/disconnected_space.md
  docs/content/reference/types/components/disconnected_space.md
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_cpp/src/rerun/components/disconnected_space.hpp
  rerun_py/rerun_sdk/rerun/archetypes/disconnected_space.py
  rerun_py/rerun_sdk/rerun/components/disconnected_space.py
Labels: 📖 documentation, 🍏 primitives, include in changelog

#4933 Fix not allowing to add any entitites to data table view
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
  crates/re_viewer_context/src/typed_entity_collections.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/space_view.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#4937 Remove legacy SpaceInfo
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/unreachable_transform_reason.rs
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/space_info.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 📺 re_viewer, 🚜 refactor, exclude from changelog

#4972 Fix lagging time cursor when panning a time series plot
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/src/lib.rs
Labels: ui, 📺 re_viewer, include in changelog

#4910 Add support for drag-and-drop in blueprint tree
  Cargo.lock
  Cargo.toml
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/drag_and_drop.rs
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: enhancement, ui, include in changelog

#4973 Add required features to winit for re_renderer_examples to pass check on linux
  crates/re_renderer_examples/Cargo.toml
Labels: 🔺 re_renderer, exclude from changelog

#4959 Allow selection of entitites directly in the plot space view
  Cargo.lock
  Cargo.toml
  crates/re_data_ui/src/item_ui.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_space_view_time_series/src/visualizer_system.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#4975 Style container's label as unnamed
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4982 New empty space view defaults to uncollapsed in blueprint tree
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#4980 Primary cache: support reentrancy
  crates/re_query_cache/src/cache.rs
  crates/re_query_cache/src/latest_at.rs
  crates/re_query_cache/src/range.rs
Labels: 🔍 re_query, 💣 crash, exclude from changelog

#4978 Fix space view cloning to also copy entity properties (visible time range, etc.)
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/space_view.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: ui, include in changelog
