Repository rerun-io/rerun, pull requests merged in 2024-03, with the labels that each got.

#5364 Fix `Scalar` link in website docs
  docs/content/reference/types.md
Labels: 🪳 bug, 📖 documentation, exclude from changelog

#5354 `ListItem`'s collapsing triangle is now styled consistently with the rest of the item
  crates/re_ui/src/lib.rs
  crates/re_ui/src/list_item.rs
Labels: ui, include in changelog

#5366 Fix arrow libraries from download & build not being found in some cases
  .github/workflows/on_pull_request.yml
  rerun_cpp/download_and_build_arrow.cmake
Labels: 🌊 C++ API, include in changelog

#5365 Always use Python 3.11 in pixi
  examples/python/car/requirements.txt
  examples/python/depth_guided_stable_diffusion/requirements.txt
  examples/python/detect_and_track_objects/requirements.txt
  examples/python/face_tracking/requirements.txt
  examples/python/gesture_detection/requirements.txt
  examples/python/human_pose_tracking/requirements.txt
  examples/python/live_depth_sensor/requirements.txt
  examples/python/objectron/requirements.txt
  examples/python/open_photogrammetry_format/requirements.txt
  examples/python/rgbd/requirements.txt
  examples/python/ros_node/requirements.txt
  examples/python/structure_from_motion/requirements.txt
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5371 Do not duplicate the space origin subtree in the blueprint tree UI
  crates/re_ui/data/icons/link.png
  crates/re_ui/src/icons.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, 🛑 controversial, exclude from changelog

#5373 Fix CI: bad `egui_tiles` commit and merge bug in #5369
  Cargo.lock
  Cargo.toml
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: dependencies, exclude from changelog

#5362 Add helpers to enable stable and controllable collapsed state in hierarchical lists
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer_context/src/collapsed_id.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#5338 Different icon for empty entity paths
  crates/re_data_ui/src/item_ui.rs
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, include in changelog

#5374 Add RERUN_INSTALL_RERUN_C CMake option to disable installation of rerun_c library
  rerun_cpp/CMakeLists.txt
  rerun_cpp/Config.cmake.in
Labels: 🌊 C++ API, include in changelog

#5375 Fix cmake install not finding external arrow for dynamic arrow linking)
  rerun_cpp/Config.cmake.in
Labels: 🪳 bug, 🌊 C++ API, include in changelog

#5386 Fix crates.py retry delay parsing
  scripts/ci/crates.py
Labels: exclude from changelog, :ship: CI

#5378 Merge quick start guides
  crates/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/re_viewer/data/quick_start_guides/cpp_spawn.md
  crates/re_viewer/data/quick_start_guides/python_connect.md
  crates/re_viewer/data/quick_start_guides/python_spawn.md
  crates/re_viewer/data/quick_start_guides/rust_connect.md
  crates/re_viewer/data/quick_start_guides/rust_spawn.md
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: ui, include in changelog

#5389 Backport changes from release-0.14.1
  CHANGELOG.md
Labels: exclude from changelog

#5379 SDK `DataLoader`s 7: stateful file logging
  crates/re_data_source/src/data_loader/mod.rs
  crates/re_sdk/src/recording_stream.rs
  crates/rerun_c/src/lib.rs
  examples/python/external_data_loader/main.py
  examples/rust/external_data_loader/src/main.rs
  examples/rust/log_file/src/main.rs
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, 🦀 Rust API, include in changelog, 🪵 Log-API

#5361 SDK `DataLoader`s 8: customizable (external) loaders for C++
  crates/rerun_c/src/lib.rs
  crates/rerun_c/src/rerun.h
  examples/cpp/external_data_loader/main.cpp
  examples/cpp/log_file/main.cpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
Labels: 🌊 C++ API, include in changelog, 🪵 Log-API

#5393 Bump `mio` (RUSTSEC-2024-0019)
  Cargo.lock
Labels: dependencies, exclude from changelog

#5385 Python serializable `ViewportBlueprint`
  crates/re_data_ui/src/editors.rs
  crates/re_space_view/src/data_query_blueprint.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/viewport_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/auto_layout.fbs
  crates/re_types/definitions/rerun/blueprint/components/auto_space_views.fbs
  crates/re_types/definitions/rerun/blueprint/components/included_space_view.fbs
  crates/re_types/definitions/rerun/blueprint/components/root_container.fbs
  crates/re_types/definitions/rerun/blueprint/components/space_view_maximized.fbs
  crates/re_types/definitions/rerun/blueprint/components/viewport_layout.fbs
  crates/re_types_core/src/loggable_batch.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewport/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_viewport/src/blueprint/components/.gitattributes
  crates/re_viewport/src/blueprint/components/included_space_view.rs
  crates/re_viewport/src/blueprint/components/mod.rs
  crates/re_viewport/src/blueprint/components/root_container.rs
  crates/re_viewport/src/blueprint/components/space_view_maximized.rs
  crates/re_viewport/src/blueprint/components/space_view_maximized_ext.rs
  crates/re_viewport/src/blueprint/components/viewport_layout.rs
  crates/re_viewport/src/blueprint/components/viewport_layout_ext.rs
  crates/re_viewport/src/blueprint/data_ui.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/viewport_blueprint.rs
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/included_space_view.hpp
  rerun_cpp/src/rerun/blueprint/components/space_view_maximized.cpp
  rerun_cpp/src/rerun/blueprint/components/space_view_maximized.hpp
  rerun_cpp/src/rerun/blueprint/components/viewport_layout.cpp
  rerun_cpp/src/rerun/blueprint/components/viewport_layout.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/viewport_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/auto_layout.py
  rerun_py/rerun_sdk/rerun/blueprint/components/auto_layout_ext.py
  rerun_py/rerun_sdk/rerun/blueprint/components/auto_space_views.py
  rerun_py/rerun_sdk/rerun/blueprint/components/auto_space_views_ext.py
  rerun_py/rerun_sdk/rerun/blueprint/components/viewport_layout.py
  rerun_py/tests/unit/test_viewport_blueprint.py
Labels: 🐍 Python API, 🟦 blueprint, exclude from changelog

#5392 More context menu 1: refactor
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/context_menu/actions.rs
  crates/re_viewport/src/context_menu/container_and_space_view_actions.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/context_menu/sub_menu.rs
  crates/re_viewport/src/context_menu/utils.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  tests/python/release_checklist/check_context_menu.py
Labels: 🚜 refactor, include in changelog

#5394 Update welcome screen panel illustrations
  crates/re_ui/data/images/configure-card.png
  crates/re_ui/data/images/live-data-card.png
  crates/re_ui/data/images/onboarding-configure.png
  crates/re_ui/data/images/onboarding-examples.jpg
  crates/re_ui/data/images/onboarding-live-data.png
  crates/re_ui/data/images/onboarding-recorded-data.png
  crates/re_ui/data/images/recorded-data-card.png
  crates/re_ui/src/icons.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: ui, include in changelog

#5399 Remove the check for WrongNumberOfInstances
  crates/re_log_types/src/data_row.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_types_core/src/lib.rs
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_log.py
Labels: include in changelog, 🪵 Log-API

#5397 More context menu 2: add support to show/hide `DataResult`s
  crates/re_viewport/src/context_menu/actions.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  tests/python/release_checklist/check_context_menu.py
Labels: ui, include in changelog

#5407 More context menu 3: add support for removing `DataResult` from a space view
  crates/re_viewport/src/context_menu/actions.rs
  tests/python/release_checklist/check_context_menu.py
Labels: ui, include in changelog

#5416 Bump egui master
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog

#5417 Make the Null fields in enums be nullable
  crates/re_types/src/blueprint/components/corner2d.rs
  crates/re_types/src/components/marker_shape.rs
  crates/re_types/src/testing/components/enum_test.rs
  crates/re_types_builder/src/arrow_registry.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_viewport/src/blueprint/components/container_kind.rs
Labels: 🪳 bug, codegen/idl, exclude from changelog

#5409 Update wgpu to 0.19.3
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
Labels: dependencies, include in changelog

#5411 More context menu 4: create a new space view with selected entities
  crates/re_viewport/src/context_menu/actions.rs
  crates/re_viewport/src/context_menu/mod.rs
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
Labels: ui, include in changelog

#5427 Fix crash from removing SpaceViewContents due to double-clear
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
Labels: 🪳 bug, exclude from changelog

#5424 Fix parents of queried paths getting visualized, fix 2D objects not showing at all in 3D if their camera parent is not included
  crates/re_entity_db/src/entity_properties.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer_context/src/query_context.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, include in changelog

#5430 Remove recursive clear cascade debug assertion
  crates/re_entity_db/src/entity_db.rs
Labels: ⛃ re_datastore, 💣 crash, exclude from changelog

#5422 More context menu 5: add context menu to streams tree
  Cargo.lock
  crates/re_time_panel/Cargo.toml
  crates/re_time_panel/src/lib.rs
  crates/re_viewer/src/app_state.rs
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
Labels: ui, include in changelog

#5423 Better origin heuristics for "Add entities to new space view"
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewport/src/context_menu/actions.rs
  tests/python/release_checklist/check_context_menu_suggested_origin.py
Labels: ui, exclude from changelog, heuristics

#5432 Make pinhole.hpp robust against min/max preprocessor macros (typically from windows.h)
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
  rerun_cpp/src/rerun/archetypes/pinhole_ext.cpp
  rerun_cpp/tests/windows_min_max_robustness.cpp
Labels: 🪳 bug, 🌊 C++ API, include in changelog

#5433 More context menu 6: Add "Expand/Collapse all" actions
  crates/re_viewport/src/context_menu/actions.rs
  crates/re_viewport/src/context_menu/mod.rs
  tests/python/release_checklist/check_context_menu_collapse_expand_all.py
Labels: ui, include in changelog

#5456 More context menu 7: cleanup
  crates/re_viewport/src/context_menu/actions.rs
  crates/re_viewport/src/context_menu/actions/add_container.rs
  crates/re_viewport/src/context_menu/actions/add_entities_to_new_space_view.rs
  crates/re_viewport/src/context_menu/actions/add_space_view.rs
  crates/re_viewport/src/context_menu/actions/clone_space_view.rs
  crates/re_viewport/src/context_menu/actions/collapse_expand_all.rs
  crates/re_viewport/src/context_menu/actions/mod.rs
  crates/re_viewport/src/context_menu/actions/move_contents_to_new_container.rs
  crates/re_viewport/src/context_menu/actions/remove.rs
  crates/re_viewport/src/context_menu/actions/show_hide.rs
  crates/re_viewport/src/context_menu/mod.rs
  tests/python/release_checklist/check_context_menu.py
  tests/python/release_checklist/check_context_menu_invalid_sub_container.py
  tests/python/release_checklist/check_context_menu_multi_selection.py
  tests/python/release_checklist/check_context_menu_single_selection.py
  tests/python/release_checklist/check_context_menu_single_selection_blueprint_tree.py
Labels: 🔨 testing, 🚜 refactor, include in changelog

#5462 Add `incremental_logging` example
  Cargo.lock
  examples/cpp/CMakeLists.txt
  examples/cpp/incremental_logging/CMakeLists.txt
  examples/cpp/incremental_logging/README.md
  examples/cpp/incremental_logging/main.cpp
  examples/python/incremental_logging/README.md
  examples/python/incremental_logging/main.py
  examples/python/incremental_logging/requirements.txt
  examples/python/requirements.txt
  examples/rust/incremental_logging/Cargo.toml
  examples/rust/incremental_logging/README.md
  examples/rust/incremental_logging/src/main.rs
Labels: 🐍 Python API, 🦀 Rust API, examples, 🌊 C++ API, include in changelog

#5443 Configurable background color for 3D Space Views
  crates/re_data_ui/src/editors.rs
  crates/re_renderer/shader/generic_skybox.wgsl
  crates/re_renderer/src/renderer/generic_skybox.rs
  crates/re_renderer/src/renderer/mod.rs
  crates/re_renderer_examples/depth_cloud.rs
  crates/re_renderer_examples/multiview.rs
  crates/re_renderer_examples/outlines.rs
  crates/re_renderer_examples/picking.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_types/definitions/rerun/blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/background_3d.fbs
  crates/re_types/definitions/rerun/blueprint/components/background_3d_kind.fbs
  crates/re_types/src/blueprint/archetypes/.gitattributes
  crates/re_types/src/blueprint/archetypes/background3d.rs
  crates/re_types/src/blueprint/archetypes/background3d_ext.rs
  crates/re_types/src/blueprint/archetypes/mod.rs
  crates/re_types/src/blueprint/components/.gitattributes
  crates/re_types/src/blueprint/components/background3d_kind.rs
  crates/re_types/src/blueprint/components/mod.rs
  crates/re_types/src/components/color_ext.rs
  crates/re_types/src/datatypes/rgba32_ext.rs
  crates/re_viewer/src/blueprint/validation_gen/mod.rs
  rerun_cpp/src/rerun/blueprint/archetypes.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/.gitattributes
  rerun_cpp/src/rerun/blueprint/archetypes/background3d.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/background3d.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/blueprint/components/background3d_kind.cpp
  rerun_cpp/src/rerun/blueprint/components/background3d_kind.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/background3d.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/components/background3d_kind.py
Labels: enhancement, 🔺 re_renderer, 📺 re_viewer, 🟦 blueprint, include in changelog

#5474 Fix size comparison (red CI)
  scripts/ci/compare.py
Labels: exclude from changelog, :ship: CI

#5478 Add google colab notebook update to the release instructions
  .github/workflows/release.yml
Labels: ⛴ release, exclude from changelog

#5475 More typo fixes
  .typos.toml
  CHANGELOG.md
  crates/re_data_store/tests/correctness.rs
  crates/re_renderer/src/view_builder.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_viewer/data/quick_start_guides/how_does_it_work.md
  design/batching.md
  docs/cspell.json
  rerun_py/ARCHITECTURE.md
  rerun_py/tests/unit/test_transform3d.py
  tests/cpp/roundtrips/image/main.cpp
Labels: 📖 documentation, exclude from changelog

#5476 Use uppercase for "2D" and "3D"
  CHANGELOG.md
  crates/re_log_types/src/path/entity_path_filter.rs
  crates/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/re_renderer/src/depth_offset.rs
  crates/re_renderer/src/renderer/rectangles.rs
  crates/re_renderer/src/resource_managers/texture_manager.rs
  crates/re_renderer_examples/2d.rs
  crates/re_renderer_examples/Cargo.toml
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/spatial_topology.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_core/src/components/instance_key_ext.rs
  design/blueprint_store.md
  docs/code-examples/all/line_strip2d_batch.cpp
  docs/code-examples/all/line_strip2d_batch.py
  docs/code-examples/all/line_strip2d_batch.rs
  docs/code-examples/all/line_strip3d_batch.cpp
  docs/code-examples/all/line_strip3d_batch.py
  docs/code-examples/all/line_strip3d_batch.rs
  docs/content/concepts/annotation-context.md
  docs/content/concepts/entity-path.md
  docs/content/getting-started/viewer-walkthrough.md
  docs/content/reference/types.md
  examples/cpp/dna/README.md
  examples/cpp/incremental_logging/README.md
  examples/python/arkit_scenes/main.py
  examples/python/dna/README.md
  examples/python/face_tracking/README.md
  examples/python/incremental_logging/README.md
  examples/python/nv12/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/plots/README.md
  examples/python/shape_pointe/README.md
  examples/rust/dna/README.md
  examples/rust/incremental_logging/README.md
  rerun_py/rerun_sdk/rerun/datatypes/rotation3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/transform3d_ext.py
  scripts/lint.py
  tests/cpp/roundtrips/line_strips2d/main.cpp
  tests/cpp/roundtrips/points2d/main.cpp
  tests/python/release_checklist/check_heuristics_mixed_2d_and_3d.py
  tests/python/release_checklist/check_hover_select_reset.py
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/roundtrips/line_strips2d/main.py
  tests/python/roundtrips/points2d/main.py
  tests/python/test_api/main.py
  tests/rust/roundtrips/line_strips2d/src/main.rs
  tests/rust/roundtrips/points2d/src/main.rs
Labels: 📖 documentation, exclude from changelog

#5408 MVP Blueprint APIs for layout and contents
  crates/re_sdk/src/recording_stream.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/viewport_blueprint.fbs
  crates/re_viewport/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/rerun_c/src/lib.rs
  examples/python/blueprint/main.py
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.hpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/viewport_blueprint.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_viewport_blueprint.py
  tests/python/blueprint/main.py
Labels: 🟦 blueprint, exclude from changelog

#5481 Implement recursive component overrides
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer_context/src/space_view/view_query.rs
Labels: 🟦 blueprint, exclude from changelog

#5471 Remove DynSpaceViewClass indirection
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/visualizable.rs
  crates/re_space_view_bar_chart/src/space_view_class.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/src/space_view_class.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/dyn_space_view_class.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/context_menu/actions/add_entities_to_new_space_view.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/system_execution.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
Labels: 🚜 refactor, exclude from changelog

#5488 Save recordings from web viewer
  crates/re_data_store/src/store_read.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_log_encoding/src/encoder.rs
  crates/re_log_encoding/src/lib.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/saving.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  scripts/ci/compare.py
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#5482 Automatically expand and scroll the blueprint tree when focusing on an item
  Cargo.lock
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/context_menu/actions/collapse_expand_all.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  tests/python/release_checklist/check_focus.py
Labels: enhancement, ui, include in changelog

#5493 Update egui to improve logic for when a submenu gets closed
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#5485 Allow rerun_py to be built without the viewer
  Cargo.lock
  rerun_py/Cargo.toml
Labels: 🟦 blueprint, exclude from changelog

#5500 Add `-g` option to `re_build_web_viewer` to keep debug symbols
  crates/re_build_web_viewer/src/lib.rs
  crates/re_build_web_viewer/src/main.rs
Labels: 🕸️ web, 🧑‍💻 dev experience, exclude from changelog

#5489 Build C++ SDK for Linux ARM64
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  rerun_cpp/CMakeLists.txt
  rerun_cpp/cmake_setup_in_detail.md
  scripts/ci/bundle_and_upload_rerun_cpp.py
Labels: 🌊 C++ API, include in changelog, :ship: CI

#5504 Add some common artefact directories to `.prettierignore`
  .prettierignore
Labels: 🧑‍💻 dev experience, exclude from changelog

#5498 Add the remaining space views and name them consistently
  examples/python/blueprint/main.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/containers.py
  rerun_py/rerun_sdk/rerun/blueprint/space_views.py
  tests/python/blueprint/main.py
Labels: 🐍 Python API, 🟦 blueprint, include in changelog

#5506 Rename `.blueprint` extension to `.rbl`
  crates/re_log_encoding/src/decoder/mod.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/saving.rs
Labels: 📺 re_viewer, exclude from changelog

#5509 Add blueprint support to script helpers
  rerun_py/rerun_sdk/rerun/script_helpers.py
Labels: 🐍 Python API, 🟦 blueprint, exclude from changelog

#5499 Add support for active_tab
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/containers.py
  rerun_py/rerun_sdk/rerun/script_helpers.py
Labels: 🐍 Python API, 🟦 blueprint, exclude from changelog

#5503 Build CLI for Linux ARM64
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  scripts/ci/sync_release_assets.py
Labels: include in changelog, CLI, :ship: CI

#5515 Add missing Tabs import to blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog

#5522 Add `workflow_dispatch` to reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#5513 Support loading `.bpl` blueprint files
  crates/re_data_source/src/data_loader/loader_rrd.rs
  crates/re_data_source/src/data_source.rs
  crates/re_data_source/src/lib.rs
  crates/re_data_source/src/load_file.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_log_types/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewport/src/container.rs
Labels: 📺 re_viewer, 🟦 blueprint, include in changelog

#5508 Allow hiding/showing entity subtrees under shown/hidden parent tree
  crates/re_entity_db/src/entity_properties.rs
  crates/re_space_view/src/data_query.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_bar_chart/src/visualizer_system.rs
  crates/re_space_view_dataframe/src/space_view_class.rs
  crates/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/re_space_view_spatial/src/visualizers/cameras.rs
  crates/re_space_view_spatial/src/visualizers/entity_iterator.rs
  crates/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/re_space_view_tensor/src/visualizer_system.rs
  crates/re_space_view_text_document/src/visualizer_system.rs
  crates/re_space_view_text_log/src/visualizer_system.rs
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_space_view_time_series/src/line_visualizer_system.rs
  crates/re_space_view_time_series/src/overrides.rs
  crates/re_space_view_time_series/src/point_visualizer_system.rs
  crates/re_types/definitions/rerun/blueprint/components/visible.fbs
  crates/re_types/src/blueprint/components/mod.rs
  crates/re_types/src/blueprint/components/visible.rs
  crates/re_types/src/blueprint/components/visible_ext.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/view_query.rs
  crates/re_viewport/src/context_menu/actions/show_hide.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  examples/rust/custom_space_view/src/color_coordinates_visualizer_system.rs
Labels: 🟦 blueprint, include in changelog

#5526 Fix the names of the links in types.md
  docs/content/reference/types.md
Labels: 📖 documentation, exclude from changelog

#5517 Introduce basic support for $origin substitution in EntityPathFilter
  crates/re_log_types/src/path/entity_path_filter.rs
  crates/re_log_types/src/path/mod.rs
  crates/re_space_view/src/heuristics.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_text_log/src/space_view_class.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/space_view/spawn_heuristics.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/context_menu/actions/add_entities_to_new_space_view.rs
  crates/re_viewport/src/context_menu/actions/add_space_view.rs
  crates/re_viewport/src/space_view_heuristics.rs
  crates/re_viewport/src/viewport_blueprint.rs
  examples/python/plots/main.py
  examples/rust/custom_space_view/src/color_coordinates_space_view.rs
  rerun_py/rerun_sdk/rerun/blueprint/space_views.py
Labels: 🟦 blueprint, include in changelog

#5539 Switch the blueprint timeline from seconds to sequence
  crates/re_space_view/src/space_view.rs
  crates/re_viewer/src/app_blueprint.rs
  crates/re_viewer/src/ui/override_ui.rs
  crates/re_viewer_context/src/blueprint_helpers.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/viewport_blueprint.rs
  rerun_py/rerun_sdk/rerun/blueprint/api.py
Labels: 🟦 blueprint, exclude from changelog

#5543 Include multi-platform dockerbuild with arm64 support
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  ci_docker/Dockerfile
  ci_docker/publish.sh
Labels: exclude from changelog, :ship: CI

#5548 Support loading multiple recordings and/or blueprints in web-viewer
  Cargo.lock
  Cargo.toml
  crates/re_data_source/src/data_source.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/web.rs
Labels: 🕸️ web, 🟦 blueprint, include in changelog

#5529 Activate blueprint as soon as it has finished transmitting
  crates/re_data_ui/src/log_msg.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_viewer/src/app.rs
  crates/rerun/src/run.rs
Labels: 📺 re_viewer, 🟦 blueprint, exclude from changelog

#5551 Make arrow null fields nullable in C++
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/objects.rs
  rerun_cpp/src/rerun/blueprint/components/background3d_kind.cpp
  rerun_cpp/src/rerun/blueprint/components/container_kind.cpp
  rerun_cpp/src/rerun/blueprint/components/corner2d.cpp
  rerun_cpp/src/rerun/components/marker_shape.cpp
  rerun_cpp/tests/generated/components/enum_test.cpp
Labels: 🏹 arrow, codegen/idl, 🌊 C++ API, exclude from changelog

#5547 Fix RERUN_C_BUILD_ARTIFACT path value if CARGO_BUILD_TARGET env variable is set
  crates/rerun_c/CMakeLists.txt
Labels: 🌊 C++ API, include in changelog

#5552 Remove what's left of setup_dev.sh & setup.sh
  BUILD.md
  ci_docker/Dockerfile
  scripts/setup.sh
  scripts/setup_dev.sh
Labels: 🧑‍💻 dev experience, exclude from changelog

#5494 Automatically expand and scroll the streams tree when focusing on an item
  crates/re_time_panel/src/lib.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  tests/python/release_checklist/check_focus.py
Labels: ui, include in changelog

#5550 Hide entity icons in paths
  crates/re_data_ui/src/item_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
Labels: ui, exclude from changelog

#5511 Build wheels for Linux ARM64
  .github/workflows/auto_release_crates.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_js.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  ci_docker/Dockerfile
  ci_docker/publish.sh
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, include in changelog, :ship: CI

#5560 Don't merge recording and blueprint in --test-receive
  crates/rerun/src/run.rs
Labels: 🔨 testing, 🦟 regression, exclude from changelog

#5565 Fix a bug where an incorrect 3D space view origin could be suggested
  crates/re_space_view_spatial/src/space_view_3d.rs
Labels: 🪳 bug, ui, exclude from changelog

#5556 Add blueprint to the `nuscenes` example
  crates/re_viewer/src/ui/selection_panel.rs
  examples/python/arkit_scenes/main.py
  examples/python/nuscenes/main.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/containers.py
Labels: examples, 🟦 blueprint, include in changelog

#5567 Tensor space view can now show images
  crates/re_space_view_tensor/src/space_view_class.rs
Labels: 📺 re_viewer, include in changelog

#5563 Fix not creating 3D space views for pinhole-only 3D scenes
  crates/re_space_view_spatial/src/space_view_3d.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, include in changelog

#5571 Make space view use its own data-result when editing visible history
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
Labels: 🟦 blueprint, exclude from changelog

#5564 Show visible time range on all entities of a space view that supports it
  crates/re_viewer/src/ui/visible_history.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#5569 Refactor `Selection` use a `BTreeMap` and make it more encapsulated
  Cargo.lock
  Cargo.toml
  crates/re_space_view_spatial/src/ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/selection_history.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/context_menu/mod.rs
Labels: 🚜 refactor, include in changelog

#5591 Self-documenting example manifest
  examples/manifest.toml
Labels: 📖 documentation, examples, exclude from changelog

#5580 Fix C++ and Python data loader examples to use nanoseconds instead of seconds
  examples/cpp/external_data_loader/main.cpp
  examples/python/external_data_loader/main.py
Labels: 🪳 bug, examples, exclude from changelog

#5587 Moved taplo back to the default feature in `pixi.toml`
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#5490 Update `controlnet` example readme
  docs/cspell.json
  examples/python/controlnet/README.md
Labels: 📖 documentation, examples, exclude from changelog

#5592 `import rerun.blueprint as rbl` -> `import rerun.blueprint as rrb`
  examples/python/arkit_scenes/main.py
  examples/python/nuscenes/main.py
Labels: 🐍 Python API, exclude from changelog

#5582 Add blueprint to depth guided stable diffusion example
  examples/python/depth_guided_stable_diffusion/huggingface_pipeline.py
  examples/python/depth_guided_stable_diffusion/main.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart_ext.py
Labels: examples, 🟦 blueprint, include in changelog

#5576 Remove car example
  BUILD.md
  examples/manifest.toml
  examples/python/README.md
  examples/python/car/README.md
  examples/python/car/main.py
  examples/python/car/requirements.txt
  examples/python/requirements.txt
  rerun_py/README.md
  scripts/run_python_e2e_test.py
Labels: examples, include in changelog

#5578 Fix depth cloud bounding boxes for depth cloud visualizations with transforms
  crates/re_renderer/src/renderer/depth_cloud.rs
  crates/re_space_view_spatial/src/visualizers/images.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5579 Fix image view not handling images with extra leading dimensions of size 1
  crates/re_types/src/datatypes/tensor_data_ext.rs
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/depth_guided_stable_diffusion/huggingface_pipeline.py
  examples/python/depth_guided_stable_diffusion/main.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart_ext.py
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5597 Rename some structures and APIs around selection
  crates/re_space_view_spatial/src/ui.rs
  crates/re_space_view_spatial/src/ui_2d.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewer_context/src/selection_history.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/viewer_context.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: 🚜 refactor, exclude from changelog

#5575 Fix doc snippets
  crates/re_build_examples/src/snippets.rs
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  docs/content/reference/types/archetypes/annotation_context.md
  docs/content/reference/types/archetypes/arrows2d.md
  docs/content/reference/types/archetypes/arrows3d.md
  docs/content/reference/types/archetypes/asset3d.md
  docs/content/reference/types/archetypes/bar_chart.md
  docs/content/reference/types/archetypes/boxes2d.md
  docs/content/reference/types/archetypes/boxes3d.md
  docs/content/reference/types/archetypes/clear.md
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/archetypes/disconnected_space.md
  docs/content/reference/types/archetypes/image.md
  docs/content/reference/types/archetypes/line_strips2d.md
  docs/content/reference/types/archetypes/line_strips3d.md
  docs/content/reference/types/archetypes/mesh3d.md
  docs/content/reference/types/archetypes/pinhole.md
  docs/content/reference/types/archetypes/points2d.md
  docs/content/reference/types/archetypes/points3d.md
  docs/content/reference/types/archetypes/scalar.md
  docs/content/reference/types/archetypes/segmentation_image.md
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/archetypes/series_point.md
  docs/content/reference/types/archetypes/tensor.md
  docs/content/reference/types/archetypes/text_document.md
  docs/content/reference/types/archetypes/text_log.md
  docs/content/reference/types/archetypes/time_series_scalar.md
  docs/content/reference/types/archetypes/transform3d.md
  docs/content/reference/types/archetypes/view_coordinates.md
  docs/snippets/build.rs
  docs/snippets/src/lib.rs
  docs/snippets/src/snippets/.gitignore
Labels: 📖 documentation, exclude from changelog

#5598 Removing items with the context menu now also removes them from the selection
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewport/src/context_menu/actions/remove.rs
Labels: 🪳 bug, ui, exclude from changelog

#5590 Fix indentation of leaf items in hierarchical lists
  crates/re_data_ui/src/editors.rs
  crates/re_time_panel/src/lib.rs
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, exclude from changelog

#5600 Do not display non-visualizable items as hidden in the blueprint tree
  crates/re_viewport/src/viewport_blueprint_ui.rs
Labels: ui, exclude from changelog

#5610 Fix bad link from trouble shooting guide
  docs/content/getting-started/troubleshooting.md
Labels: 📖 documentation, exclude from changelog

#5604 Remove deprecated `TimeSeriesScalar`
  crates/re_query_cache/src/flat_vec_deque.rs
  crates/re_space_view_time_series/src/legacy_visualizer_system.rs
  crates/re_space_view_time_series/src/lib.rs
  crates/re_space_view_time_series/src/space_view_class.rs
  crates/re_types/definitions/rerun/archetypes.fbs
  crates/re_types/definitions/rerun/archetypes/time_series_scalar.fbs
  crates/re_types/src/archetypes/.gitattributes
  crates/re_types/src/archetypes/mod.rs
  crates/re_types/src/archetypes/time_series_scalar.rs
  docs/content/getting-started/viewer-walkthrough.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/reference/migration/migration-0-13.md
  docs/content/reference/migration/migration-0-9.md
  docs/content/reference/types.md
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/.gitattributes
  docs/content/reference/types/archetypes/time_series_scalar.md
  docs/content/reference/types/components/color.md
  docs/content/reference/types/components/radius.md
  docs/content/reference/types/components/scalar.md
  docs/content/reference/types/components/scalar_scattering.md
  docs/content/reference/types/components/text.md
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/.gitattributes
  rerun_cpp/src/rerun/archetypes/time_series_scalar.cpp
  rerun_cpp/src/rerun/archetypes/time_series_scalar.hpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/time_series_scalar.py
  tests/python/release_checklist/check_container_hierarchy.py
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/release_checklist/check_plot_overrides.py
  tests/python/release_checklist/check_scalar_clears.py
  tests/roundtrips.py
Labels: 🐍 Python API, 🦀 Rust API, 🌊 C++ API, include in changelog, 🪵 Log-API

#5572 Add option to include blueprint in an `.rrd` when calling `.save(…)`
  crates/re_build_examples/src/example.rs
  crates/re_build_info/src/build_info.rs
  crates/re_sdk/src/recording_stream.rs
  examples/python/structure_from_motion/main.py
  rerun_py/rerun_sdk/rerun/script_helpers.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, include in changelog

#5611 Fix build workflows
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
Labels: exclude from changelog, :ship: CI

#5613 Add blueprint to Live Camera Edge Detection example
  examples/python/live_camera_edge_detection/main.py
Labels: examples, include in changelog

#5614 Add blueprint to LLM Embedding Ner example
  examples/python/llm_embedding_ner/main.py
Labels: examples, include in changelog

#5612 Add blueprint to Human Pose Tracking example
  examples/python/human_pose_tracking/main.py
Labels: examples, include in changelog

#5616 Add blueprint to Face Tracking example
  examples/python/face_tracking/main.py
Labels: examples, include in changelog

#5617 Add blueprint to Objectron example
  examples/python/objectron/main.py
Labels: examples, include in changelog

#5609 Reduce the height of the the tab bars and side panel titles
  crates/re_ui/src/lib.rs
Labels: ui, include in changelog

#5619 Add blueprint to Gesture Detection example
  examples/python/gesture_detection/main.py
Labels: examples, include in changelog

#5621 Update to latest egui master
  Cargo.lock
  Cargo.toml
  crates/re_space_view_spatial/src/eye.rs
  crates/re_ui/src/command.rs
Labels: dependencies, exclude from changelog, egui

#5618 Document `data-inline-viewer`
  docs/README.md
  examples/python/arkit_scenes/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/dna/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/incremental_logging/README.md
  examples/python/nuscenes/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/segment_anything_model/README.md
  examples/python/structure_from_motion/README.md
Labels: 📖 documentation, 🕸️ web, exclude from changelog

#5615 Update example thumbnails
  docs/cspell.json
  examples/cpp/clock/README.md
  examples/cpp/eigen_opencv/README.md
  examples/cpp/incremental_logging/README.md
  examples/cpp/minimal/README.md
  examples/cpp/stdio/README.md
  examples/cpp/vrs/README.md
  examples/python/arflow/README.md
  examples/python/arkit_scenes/README.md
  examples/python/clock/README.md
  examples/python/controlnet/README.md
  examples/python/depth_guided_stable_diffusion/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/dicom_mri/README.md
  examples/python/differentiable_blocks_world/README.md
  examples/python/face_tracking/README.md
  examples/python/gesture_detection/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/lidar/README.md
  examples/python/limap/README.md
  examples/python/live_camera_edge_detection/README.md
  examples/python/llm_embedding_ner/README.md
  examples/python/mcc/README.md
  examples/python/minimal/README.md
  examples/python/multiprocessing/README.md
  examples/python/multithreading/README.md
  examples/python/objectron/README.md
  examples/python/plots/README.md
  examples/python/raw_mesh/README.md
  examples/python/rgbd/README.md
  examples/python/ros_node/README.md
  examples/python/segment_anything_model/README.md
  examples/python/shape_pointe/README.md
  examples/python/signed_distance_fields/README.md
  examples/python/simplerecon/README.md
  examples/python/slahmr/README.md
  examples/python/structure_from_motion/README.md
  examples/python/tapir/README.md
  examples/python/widebaseline/README.md
  examples/rust/clock/README.md
  examples/rust/custom_space_view/README.md
  examples/rust/extend_viewer_ui/README.md
  examples/rust/incremental_logging/README.md
  examples/rust/minimal/README.md
  examples/rust/minimal_serve/README.md
  examples/rust/objectron/README.md
  examples/rust/raw_mesh/README.md
  examples/rust/stdio/README.md
  scripts/ci/thumbnails.py
Labels: examples, exclude from changelog

#5624 Support toggling item visibility on touch screens
  crates/re_ui/examples/re_ui_example.rs
  crates/re_ui/src/list_item.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view_space_origin_ui.rs
Labels: ui, include in changelog

#5628 Fix RRT-Star example not showing up on website & app-rerun.io
  examples/manifest.toml
  examples/python/rrt-star/README.md
Labels: examples, include in changelog

#5630 Fix not logging 3D gesture z component correctly in Gesture Detection example
  examples/python/gesture_detection/main.py
Labels: 🪳 bug, examples, include in changelog

#5603 New standalone example showing blueprint configuration of some stock
  crates/re_space_view_time_series/src/space_view_class.rs
  examples/python/blueprint_stocks/README.md
  examples/python/blueprint_stocks/main.py
  examples/python/blueprint_stocks/requirements.txt
  examples/python/requirements.txt
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/containers.py
Labels: examples, 🟦 blueprint, include in changelog

#5623 Add blueprint to the RGBD example
  examples/python/rgbd/main.py
Labels: examples, include in changelog

#5627 Select active recording if nothing else is selected
  crates/re_viewer/src/app_state.rs
Labels: ui, include in changelog

#5637 Fix build on main
  crates/re_viewer/src/app_state.rs
Labels: 🪳 bug, exclude from changelog

#5626 Allow setting custom names to container
  crates/re_space_view/src/lib.rs
  crates/re_space_view/src/space_view.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/contents.rs
  crates/re_viewer_context/src/lib.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/context_menu/actions/collapse_expand_all.rs
  crates/re_viewport/src/context_menu/actions/remove.rs
  crates/re_viewport/src/context_menu/actions/show_hide.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/lib.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/containers.py
Labels: 🐍 Python API, ui, 🟦 blueprint, include in changelog

#5638 Avoid warning on win/mac by not making the blueprint stream thread-local
  rerun_py/rerun_sdk/rerun/blueprint/api.py
Labels: 🦟 regression, 🟦 blueprint, exclude from changelog

#5635 Add blueprint to Signed Distance Fields example
  examples/python/signed_distance_fields/README.md
  examples/python/signed_distance_fields/main.py
  scripts/ci/thumbnails.py
Labels: examples, include in changelog

#5625 Remove unstable notes from blueprint type docs, some minor cleanup
  crates/re_entity_db/src/blueprint/components/entity_properties_component.rs
  crates/re_types/definitions/rerun/blueprint/archetypes/space_view_contents.fbs
  crates/re_types/definitions/rerun/blueprint/archetypes/viewport_blueprint.fbs
  crates/re_types/definitions/rerun/blueprint/components/auto_layout.fbs
  crates/re_types/definitions/rerun/blueprint/components/auto_space_views.fbs
  crates/re_types/definitions/rerun/blueprint/components/background_3d_kind.fbs
  crates/re_types/definitions/rerun/blueprint/components/entity_properties_component.fbs
  crates/re_types/definitions/rerun/blueprint/components/included_space_view.fbs
  crates/re_types/definitions/rerun/blueprint/components/query_expression.fbs
  crates/re_types/definitions/rerun/blueprint/components/space_view_maximized.fbs
  crates/re_types/definitions/rerun/blueprint/components/visible_time_range.fbs
  crates/re_types/src/blueprint/archetypes/space_view_contents.rs
  crates/re_types/src/blueprint/components/background3d_kind.rs
  crates/re_types/src/blueprint/components/query_expression.rs
  crates/re_types/src/blueprint/components/visible_time_range.rs
  crates/re_viewport/src/blueprint/archetypes/viewport_blueprint.rs
  crates/re_viewport/src/blueprint/components/auto_layout.rs
  crates/re_viewport/src/blueprint/components/auto_space_views.rs
  crates/re_viewport/src/blueprint/components/included_space_view.rs
  crates/re_viewport/src/blueprint/components/space_view_maximized.rs
  rerun_cpp/src/rerun/blueprint/archetypes/space_view_contents.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/viewport_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components/auto_layout.hpp
  rerun_cpp/src/rerun/blueprint/components/auto_space_views.hpp
  rerun_cpp/src/rerun/blueprint/components/background3d_kind.hpp
  rerun_cpp/src/rerun/blueprint/components/entity_properties_component.hpp
  rerun_cpp/src/rerun/blueprint/components/included_space_view.hpp
  rerun_cpp/src/rerun/blueprint/components/query_expression.hpp
  rerun_cpp/src/rerun/blueprint/components/space_view_maximized.hpp
  rerun_cpp/src/rerun/blueprint/components/visible_time_range.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/space_view_contents.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/viewport_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/components/auto_layout.py
  rerun_py/rerun_sdk/rerun/blueprint/components/auto_space_views.py
  rerun_py/rerun_sdk/rerun/blueprint/components/background3d_kind.py
  rerun_py/rerun_sdk/rerun/blueprint/components/entity_properties_component.py
  rerun_py/rerun_sdk/rerun/blueprint/components/included_space_view.py
  rerun_py/rerun_sdk/rerun/blueprint/components/query_expression.py
  rerun_py/rerun_sdk/rerun/blueprint/components/space_view_maximized.py
  rerun_py/rerun_sdk/rerun/blueprint/components/visible_time_range.py
Labels: 📖 documentation, 🟦 blueprint, exclude from changelog

#5634 Fix controlnet example for current `controlnet` package version and add blueprint
  examples/python/controlnet/main.py
Labels: examples, include in changelog

#5647 Update egui
  Cargo.lock
  Cargo.toml
Labels: 📺 re_viewer, dependencies, 💣 crash, exclude from changelog, egui

#5643 Remove items from selection upon removal consistently
  crates/re_viewer/src/app_state.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewport/src/context_menu/actions/remove.rs
  crates/re_viewport/src/viewport_blueprint.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5644 Remove no longer needed `NonInteractiveEntities` view system
  crates/re_space_view_spatial/src/contexts/mod.rs
  crates/re_space_view_spatial/src/contexts/non_interactive_entities.rs
  crates/re_space_view_spatial/src/ui.rs
Labels: 🚜 refactor, exclude from changelog

#5648 Don't activate all blueprints in a data source when the end is reached
  crates/re_entity_db/src/entity_db.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
Labels: 🟦 blueprint, exclude from changelog

#5650 Fix layouting issue on welcome screen for narrow window, triggering debug assertion
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: 📺 re_viewer, 💣 crash, include in changelog

#5652 Use container names in some blueprints
  examples/python/arkit_scenes/main.py
  examples/python/blueprint_stocks/main.py
  examples/python/depth_guided_stable_diffusion/main.py
  examples/python/rgbd/main.py
Labels: examples, exclude from changelog

#5651 Add blueprint APIs to common index for python docs
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/space_views.py
Labels: 📖 documentation, 🟦 blueprint, exclude from changelog

#5646 Enable selecting data sources and blueprints and recordings in them
  Cargo.lock
  crates/re_build_search_index/src/ingest/python.rs
  crates/re_data_store/src/store_stats.rs
  crates/re_data_ui/Cargo.toml
  crates/re_data_ui/src/data_source.rs
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/lib.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_entity_db/src/store_bundle.rs
  crates/re_smart_channel/Cargo.toml
  crates/re_smart_channel/src/lib.rs
  crates/re_space_view_spatial/src/ui_3d.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/recordings_panel.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/Cargo.toml
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/selection_state.rs
  crates/re_viewer_context/src/store_context.rs
  crates/re_viewport/Cargo.toml
  crates/re_viewport/src/context_menu/actions/collapse_expand_all.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/space_view_highlights.rs
  crates/re_viewport/src/viewport_blueprint.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  rerun_cpp/src/rerun/c/rerun.h
Labels: ui, include in changelog

#5655 Warn user when a software rasterizer is used
  crates/re_renderer/src/context.rs
  crates/re_renderer/src/lib.rs
  crates/re_viewer/src/ui/top_panel.rs
Labels: ui, include in changelog

#5656 Simplify blueprint API by removing Viewport concept
  examples/python/blueprint/main.py
  examples/python/blueprint_stocks/main.py
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/blueprint/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  tests/python/blueprint/main.py
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
  tests/python/release_checklist/check_context_menu_collapse_expand_all.py
  tests/python/release_checklist/check_context_menu_invalid_sub_container.py
  tests/python/release_checklist/check_context_menu_multi_selection.py
  tests/python/release_checklist/check_context_menu_single_selection.py
  tests/python/release_checklist/check_context_menu_single_selection_blueprint_tree.py
  tests/python/release_checklist/check_context_menu_suggested_origin.py
  tests/python/release_checklist/check_focus.py
Labels: 🐍 Python API, 🟦 blueprint, exclude from changelog

#5664 Improve logging around blueprint saving during shutdown
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, exclude from changelog

#5667 Fix crashing when querying app url from python without webviewer & build info
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, 💣 crash, exclude from changelog

#5676 Fix missing application id in RRT* example
  examples/python/rrt-star/main.py
  scripts/lint.py
Labels: examples, exclude from changelog

#5674 Fix broken 2D Space View heuristics in Python Notebooks
  crates/re_space_view_spatial/src/max_image_dimension_subscriber.rs
  crates/re_space_view_spatial/src/space_view_2d.rs
  crates/re_space_view_spatial/src/spatial_topology.rs
  crates/re_viewer/src/app.rs
  pixi.toml
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#5675 Docs: improve discoverability of image compression
  crates/re_types/definitions/rerun/archetypes/image.fbs
  crates/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/re_types/definitions/rerun/archetypes/points3d.fbs
  crates/re_types/definitions/rerun/datatypes/tensor_buffer.fbs
  crates/re_types/src/archetypes/image.rs
  crates/re_types/src/datatypes/tensor_buffer.rs
  crates/re_types_builder/src/codegen/common.rs
  crates/re_types_builder/src/codegen/cpp/mod.rs
  crates/re_types_builder/src/codegen/docs/mod.rs
  crates/re_types_builder/src/codegen/mod.rs
  crates/re_types_builder/src/codegen/python/mod.rs
  crates/re_types_builder/src/codegen/rust/api.rs
  crates/re_types_builder/src/docs.rs
  crates/re_types_builder/src/lib.rs
  crates/re_types_builder/src/objects.rs
  docs/content/reference/types/archetypes/image.md
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/datatypes/tensor_buffer.hpp
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_buffer.py
Labels: 📖 documentation, codegen/idl, include in changelog

#5677 Use script_setup in blueprint_stocks example
  examples/python/blueprint_stocks/main.py
Labels: examples, exclude from changelog

#5680 Improve spacing and alignment of menus
  Cargo.lock
  Cargo.toml
  crates/re_ui/src/design_tokens.rs
Labels: ui, dependencies, include in changelog, egui

#5684 Fix update PR body workflow
  .github/workflows/reusable_update_pr_body.yml
Labels: exclude from changelog, :ship: CI

#5681 Apply shadows under menus
  crates/re_ui/src/design_tokens.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#5696 Update to egui 0.27.0
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: dependencies, exclude from changelog, egui

#5688 Remove a bunch of title casing, and add simple lint against it
  CHANGELOG.md
  crates/re_data_ui/src/item_ui.rs
  crates/re_entity_db/examples/memory_usage.rs
  crates/re_sdk/src/global.rs
  crates/re_smart_channel/src/lib.rs
  crates/re_space_view/Cargo.toml
  crates/re_space_view/src/space_view.rs
  crates/re_space_view_bar_chart/Cargo.toml
  crates/re_space_view_dataframe/Cargo.toml
  crates/re_space_view_spatial/src/contexts/transform_context.rs
  crates/re_space_view_spatial/src/space_view_3d.rs
  crates/re_space_view_tensor/Cargo.toml
  crates/re_space_view_tensor/src/space_view_class.rs
  crates/re_space_view_text_document/Cargo.toml
  crates/re_space_view_text_log/Cargo.toml
  crates/re_space_view_time_series/Cargo.toml
  crates/re_types/definitions/rerun/archetypes/disconnected_space.fbs
  crates/re_types/src/archetypes/disconnected_space.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer/src/ui/memory_panel.rs
  crates/re_viewer/src/ui/rerun_menu.rs
  crates/re_viewer/src/ui/selection_history_ui.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/ui/visible_history.rs
  crates/re_viewer_context/src/item.rs
  crates/re_viewer_context/src/space_view/mod.rs
  crates/re_viewer_context/src/space_view/space_view_class_placeholder.rs
  crates/re_viewer_context/src/space_view/space_view_class_registry.rs
  crates/re_viewport/src/add_space_view_or_container_modal.rs
  crates/re_viewport/src/container.rs
  crates/re_viewport/src/context_menu/actions/add_entities_to_new_space_view.rs
  crates/re_viewport/src/context_menu/mod.rs
  crates/re_viewport/src/space_view_entity_picker.rs
  crates/re_viewport/src/viewport.rs
  crates/re_viewport/src/viewport_blueprint_ui.rs
  docs/content/reference/types/archetypes/disconnected_space.md
  examples/cpp/shared_recording/README.md
  examples/python/shared_recording/README.md
  examples/rust/custom_space_view/README.md
  examples/rust/custom_store_subscriber/README.md
  examples/rust/custom_store_subscriber/src/main.rs
  examples/rust/shared_recording/README.md
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_py/rerun_sdk/rerun/archetypes/disconnected_space.py
  rerun_py/tests/unit/test_space_view_blueprint.py
  scripts/lint.py
  tests/python/release_checklist/check_context_menu_suggested_origin.py
Labels: ui, exclude from changelog

#5705 Update `mimalloc` to latest to fix stack unwinding
  Cargo.lock
  Cargo.toml
Labels: 🪳 bug, 🧑‍💻 dev experience, dependencies, exclude from changelog

#5706 Enable the `derive` feature of `serde`
  Cargo.toml
Labels: exclude from changelog, :ship: CI

#5710 Remove item spacing in sibling recordings/blueprints list
  crates/re_data_ui/src/data_source.rs
  crates/re_data_ui/src/entity_db.rs
Labels: ui, exclude from changelog

#5708 Build release `.wasm` with debug symbols
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_release_crates.yml
  crates/re_build_web_viewer/README.md
  pixi.toml
  rerun_js/web-viewer/package.json
  scripts/ci/build_and_upload_wheels.py
  web_viewer/README.md
Labels: 🕸️ web, 🧑‍💻 dev experience, 📉 performance, include in changelog

#5693 Entity path query now shows simple statistics and warns if nothing is displayed
  crates/re_space_view/src/space_view_contents.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer_context/src/query_context.rs
Labels: 📺 re_viewer, 🟦 blueprint, include in changelog

#5689 Improve getting started doc section
  docs/content/getting-started.md
  docs/content/getting-started/data-in.md
  docs/content/getting-started/data-in/open-any-file.md
  docs/content/getting-started/data-in/streaming.md
  docs/content/getting-started/data-in/streaming/cpp.md
  docs/content/getting-started/data-in/streaming/python.md
  docs/content/getting-started/data-in/streaming/rust.md
  docs/content/getting-started/installing-viewer.md
  docs/content/getting-started/quick-start.md
  docs/content/getting-started/quick-start/cpp.md
  docs/content/getting-started/quick-start/python.md
  docs/content/getting-started/quick-start/rust.md
  docs/content/getting-started/troubleshooting.md
  docs/content/getting-started/visualize.md
  docs/content/getting-started/visualize/blueprint.md
  docs/content/getting-started/visualize/viewer-walkthrough.md
  docs/content/getting-started/what-is-rerun.md
  docs/content/howto/ros2-nav-turtlebot.md
  docs/content/index.md
Labels: 📖 documentation, include in changelog

#5678 Introduce the concepts of "default" and "active" blueprint. Make reset return to default.
  crates/re_data_ui/src/entity_db.rs
  crates/re_data_ui/src/item_ui.rs
  crates/re_data_ui/src/log_msg.rs
  crates/re_entity_db/src/entity_db.rs
  crates/re_log_types/src/lib.rs
  crates/re_sdk/src/lib.rs
  crates/re_sdk/src/log_sink.rs
  crates/re_sdk/src/recording_stream.rs
  crates/re_sdk_comms/src/server.rs
  crates/re_space_view/src/space_view.rs
  crates/re_space_view/src/space_view_contents.rs
  crates/re_ui/src/command.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/store_hub.rs
  crates/re_viewer/src/ui/blueprint_panel.rs
  crates/re_viewer_context/src/command_sender.rs
  crates/re_viewer_context/src/store_context.rs
  crates/rerun/src/run.rs
  crates/rerun_c/src/lib.rs
  examples/python/arkit_scenes/main.py
  examples/python/blueprint/main.py
  examples/python/blueprint_stocks/main.py
  examples/python/controlnet/main.py
  examples/python/depth_guided_stable_diffusion/main.py
  examples/python/face_tracking/main.py
  examples/python/gesture_detection/main.py
  examples/python/human_pose_tracking/main.py
  examples/python/live_camera_edge_detection/main.py
  examples/python/llm_embedding_ner/main.py
  examples/python/nuscenes/main.py
  examples/python/objectron/main.py
  examples/python/plots/main.py
  examples/python/rgbd/main.py
  examples/python/signed_distance_fields/main.py
  examples/python/structure_from_motion/main.py
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/script_helpers.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
  tests/python/blueprint/main.py
  tests/python/release_checklist/check_context_menu_add_entity_to_new_space_view.py
  tests/python/release_checklist/check_context_menu_collapse_expand_all.py
  tests/python/release_checklist/check_context_menu_invalid_sub_container.py
  tests/python/release_checklist/check_context_menu_multi_selection.py
  tests/python/release_checklist/check_context_menu_single_selection.py
  tests/python/release_checklist/check_context_menu_single_selection_blueprint_tree.py
  tests/python/release_checklist/check_context_menu_suggested_origin.py
  tests/python/release_checklist/check_focus.py
Labels: 🟦 blueprint, exclude from changelog

#5699 Simplify Welcome Screen and use card-based layout for examples
  crates/re_ui/data/icons/github.png
  crates/re_ui/data/images/configure-card.png
  crates/re_ui/data/images/live-data-card.png
  crates/re_ui/data/images/recorded-data-card.png
  crates/re_ui/src/design_tokens.rs
  crates/re_ui/src/icons.rs
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app_state.rs
  crates/re_viewer/src/ui/top_panel.rs
  crates/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: ui, include in changelog

#5703 Add source URL to example manifest
  crates/re_build_examples/src/manifest.rs
  crates/re_viewer/src/ui/welcome_screen/mod.rs
  crates/re_viewer/src/ui/welcome_screen/welcome_section.rs
Labels: examples, exclude from changelog, :ship: CI

#5707 Update thumbnails for some in-app examples
  examples/cpp/dna/README.md
  examples/python/dna/README.md
  examples/python/nuscenes/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/rrt-star/README.md
  examples/rust/dna/README.md
Labels: examples, exclude from changelog
