Repository rerun-io/rerun, pull requests merged in 2024-08, with the labels that each got.

#7034 Clarify in docs when ViewCoordinate is picked up by a 3D view
  crates/store/re_types/definitions/rerun/archetypes/view_coordinates.fbs
  crates/store/re_types/src/archetypes/view_coordinates.rs
  docs/content/concepts/spaces-and-transforms.md
  docs/content/reference/types/archetypes/view_coordinates.md
  rerun_cpp/src/rerun/archetypes/view_coordinates.hpp
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
Labels: 📖 documentation, include in changelog

#7018 Chunkified, deserialization-free LineStrip visualizers
  crates/store/re_chunk/src/iter.rs
  crates/viewer/re_space_view/src/results_ext2.rs
  crates/viewer/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, 🍏 primitives, include in changelog

#7037 Fix image round trip test and add backwards compatible converter
  rerun_py/rerun_sdk/rerun/datatypes/tensor_data_ext.py
  rerun_py/tests/unit/test_image.py
  tests/python/roundtrips/image/main.py
Labels: 🦟 regression, exclude from changelog

#7030 Removed now unused `Rotation3D` component & datatype
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/rotation3d.fbs
  crates/store/re_types/definitions/rerun/datatypes.fbs
  crates/store/re_types/definitions/rerun/datatypes/rotation3d.fbs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/rotation3d.rs
  crates/store/re_types/src/components/rotation3d_ext.rs
  crates/store/re_types/src/datatypes/.gitattributes
  crates/store/re_types/src/datatypes/mod.rs
  crates/store/re_types/src/datatypes/rotation3d.rs
  crates/store/re_types/src/datatypes/rotation3d_ext.rs
  crates/store/re_types/tests/mint_conversions.rs
  crates/top/rerun/src/sdk.rs
  crates/viewer/re_data_ui/src/component_ui_registry.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_data_ui/src/rotation3d.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/rotation3d.md
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/.gitattributes
  docs/content/reference/types/datatypes/quaternion.md
  docs/content/reference/types/datatypes/rotation3d.md
  docs/content/reference/types/datatypes/rotation_axis_angle.md
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/rotation3d.hpp
  rerun_cpp/src/rerun/components/rotation3d_ext.cpp
  rerun_cpp/src/rerun/datatypes.hpp
  rerun_cpp/src/rerun/datatypes/.gitattributes
  rerun_cpp/src/rerun/datatypes/rotation3d.cpp
  rerun_cpp/src/rerun/datatypes/rotation3d.hpp
  rerun_cpp/src/rerun/datatypes/rotation3d_ext.cpp
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/rotation3d.py
  rerun_py/rerun_sdk/rerun/datatypes/.gitattributes
  rerun_py/rerun_sdk/rerun/datatypes/__init__.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation3d.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation3d_ext.py
  rerun_py/tests/unit/test_transform3d.py
Labels: 🍏 primitives, include in changelog, 🪵 Log-API

#7019 `Ellipsoids` renamed to `Ellipsoids3D`
  crates/store/re_types/definitions/rerun/archetypes/ellipsoids.fbs
  crates/store/re_types/src/archetypes/.gitattributes
  crates/store/re_types/src/archetypes/ellipsoids3d.rs
  crates/store/re_types/src/archetypes/ellipsoids3d_ext.rs
  crates/store/re_types/src/archetypes/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/.gitattributes
  docs/content/reference/types/archetypes/ellipsoids3d.md
  docs/content/reference/types/components/class_id.md
  docs/content/reference/types/components/color.md
  docs/content/reference/types/components/fill_mode.md
  docs/content/reference/types/components/half_size3d.md
  docs/content/reference/types/components/leaf_rotation_axis_angle.md
  docs/content/reference/types/components/leaf_rotation_quat.md
  docs/content/reference/types/components/leaf_translation3d.md
  docs/content/reference/types/components/radius.md
  docs/content/reference/types/components/text.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  docs/snippets/all/archetypes/ellipsoid3d_batch.cpp
  docs/snippets/all/archetypes/ellipsoid3d_batch.py
  docs/snippets/all/archetypes/ellipsoid3d_batch.rs
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/.gitattributes
  rerun_cpp/src/rerun/archetypes/ellipsoids3d.cpp
  rerun_cpp/src/rerun/archetypes/ellipsoids3d.hpp
  rerun_cpp/src/rerun/archetypes/ellipsoids3d_ext.cpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d_ext.py
  rerun_py/tests/unit/test_ellipsoids3d.py
Labels: 🍏 primitives, exclude from changelog

#7020 Chunkified, deserialization-free visualizers for all standard shapes
  crates/store/re_types/definitions/rerun/components/half_size2d.fbs
  crates/store/re_types/definitions/rerun/components/half_size3d.fbs
  crates/store/re_types/src/components/half_size2d.rs
  crates/store/re_types/src/components/half_size3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/labels.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/mod.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, 🍏 primitives, include in changelog

#7024 Vastly improved support for deserialized iteration
  Cargo.lock
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/example_components.rs
  crates/store/re_query2/Cargo.toml
  crates/store/re_query2/examples/range.rs
  crates/store/re_query2/tests/range.rs
  crates/viewer/re_space_view/src/results_ext2.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
Labels: 🧑‍💻 dev experience, 🔍 re_query, do-not-merge, 🍏 primitives, include in changelog

#7023 Chunkified image visualizers
  .gitignore
  Cargo.lock
  crates/store/re_types/definitions/rerun/components/opacity.fbs
  crates/store/re_types/src/components/opacity.rs
  crates/viewer/re_space_view_spatial/Cargo.toml
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/image_encoded.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, 🍏 primitives, include in changelog

#7027 Chunkified text-log view with multi-timeline display
  Cargo.lock
  crates/store/re_chunk/src/iter.rs
  crates/viewer/re_space_view/src/results_ext2.rs
  crates/viewer/re_space_view_text_log/Cargo.toml
  crates/viewer/re_space_view_text_log/src/space_view_class.rs
  crates/viewer/re_space_view_text_log/src/visualizer_system.rs
Labels: 📺 re_viewer, 🔍 re_query, 🍏 primitives, include in changelog

#7032 Chunkify everything left
  Cargo.lock
  crates/store/re_entity_db/Cargo.toml
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/lib.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_selection_panel/Cargo.toml
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_space_view/Cargo.toml
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/query.rs
  crates/viewer/re_space_view/src/query2.rs
  crates/viewer/re_space_view/src/results_ext.rs
  crates/viewer/re_space_view/src/results_ext2.rs
  crates/viewer/re_space_view_bar_chart/src/visualizer_system.rs
  crates/viewer/re_space_view_spatial/src/contexts/depth_offsets.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/ui_3d.rs
  crates/viewer/re_space_view_spatial/src/view_3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_space_view_tensor/src/visualizer_system.rs
  crates/viewer/re_space_view_text_document/src/visualizer_system.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app_blueprint.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/space_view/mod.rs
  crates/viewer/re_viewer_context/src/space_view/view_query.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, include in changelog

#7036 Implement compress directly on top of image again
  CHANGELOG.md
  crates/store/re_types/definitions/rerun/archetypes/image_encoded.fbs
  docs/content/reference/migration/migration-0-18.md
  examples/python/arkit_scenes/README.md
  examples/python/arkit_scenes/arkit_scenes/__main__.py
  examples/python/detect_and_track_objects/README.md
  examples/python/detect_and_track_objects/detect_and_track_objects.py
  examples/python/face_tracking/README.md
  examples/python/gesture_detection/README.md
  examples/python/gesture_detection/gesture_detection.py
  examples/python/human_pose_tracking/README.md
  examples/python/human_pose_tracking/human_pose_tracking.py
  examples/python/open_photogrammetry_format/open_photogrammetry_format.py
  examples/python/rgbd/README.md
  examples/python/rgbd/rgbd.py
  examples/python/structure_from_motion/README.md
  examples/python/structure_from_motion/structure_from_motion/__main__.py
  rerun_py/rerun_sdk/rerun/archetypes/image_encoded.py
  rerun_py/rerun_sdk/rerun/archetypes/image_encoded_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/components/channel_datatype_ext.py
  rerun_py/tests/unit/test_image.py
Labels: 🐍 Python API, exclude from changelog

#7038 Allow logging batches of quaternions from numpy arrays
  crates/store/re_types/definitions/rerun/datatypes/quaternion.fbs
  rerun_py/rerun_sdk/rerun/datatypes/quaternion.py
  rerun_py/rerun_sdk/rerun/datatypes/quaternion_ext.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_box3d.py
  rerun_py/tests/unit/test_ellipsoids3d.py
  rerun_py/tests/unit/test_quaternion.py
Labels: 🐍 Python API, include in changelog

#7039 Python benchmark for transform logging over time
  pixi.toml
  tests/python/log_benchmark/__init__.py
  tests/python/log_benchmark/test_log_benchmark.py
Labels: 🔨 testing, exclude from changelog

#7054 Fix `cargo t --all-features --all`
  crates/top/rerun/src/lib.rs
Labels: 🪳 bug, 😤 annoying, exclude from changelog

#7057 Improved CLI 0: refactor commands into dedicated modules
  crates/top/rerun/src/commands/analytics/mod.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun/src/commands/mod.rs
  crates/top/rerun/src/commands/rrd/compact.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/top/rerun/src/commands/rrd/merge.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/top/rerun/src/lib.rs
Labels: 🚜 refactor, exclude from changelog, CLI

#7060 Improved CLI 1: support wildcard inputs for all relevant `rerun rrd` subcommands
  crates/top/rerun/src/commands/rrd/compact.rs
  crates/top/rerun/src/commands/rrd/merge.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
Labels: 🧑‍💻 dev experience, include in changelog, CLI

#7061 Improved CLI 2: explicit CLI flags for compaction settings
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
Labels: 🧑‍💻 dev experience, include in changelog, CLI

#7055 Improve usability of `rerun::Collection` by providing free functions for `borrow` & `take_ownership`
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/tests/collection.cpp
Labels: 🌊 C++ API, include in changelog

#7063 Fix crash on shutdown when using global recording stream variables in C++
  crates/top/rerun_c/src/lib.rs
  rerun_cpp/tests/recording_stream.cpp
Labels: 🪳 bug, 💣 crash, 🌊 C++ API, include in changelog

#6888 Add mini NVS solver example
  examples/manifest.toml
  examples/python/mini_nvs_solver/README.md
Labels: examples, include in changelog

#7073 Remove redundant batch validation on Rust/Python's `log_temporal_batch`
  crates/top/re_sdk/src/recording_stream.rs
  rerun_py/src/arrow.rs
Labels: 🚜 refactor, exclude from changelog

#7064 Introduce a "Selectable Toggle" widget and use it for the 3D view's camera kind
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/ui_ext.rs
Labels: ui, include in changelog

#7079 Use chunk recording without injected timelines
  crates/top/re_sdk/src/recording_stream.rs
  rerun_py/rerun_sdk/rerun/temporal_batch.py
  rerun_py/src/python_bridge.rs
  tests/rust/test_data_density_graph/src/main.rs
Labels: 🚜 refactor, exclude from changelog

#7082 Optimize gap detector on dense timelines, like `log_tick`
  Cargo.lock
  crates/utils/re_int_histogram/src/lib.rs
  crates/viewer/re_time_panel/Cargo.toml
  crates/viewer/re_time_panel/src/time_axis.rs
Labels: 📉 performance, include in changelog

#7085 Refactor: Less use of `TimesPerTimeline`
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/time_histogram_per_timeline.rs
  crates/store/re_entity_db/src/times_per_timeline.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
Labels: 🚜 refactor, exclude from changelog

#7074 Improve entity stats when hovered
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/stats.rs
  crates/store/re_chunk_store/tests/stats.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/utils/re_format/src/lib.rs
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_viewer/src/ui/memory_panel.rs
Labels: ui, include in changelog

#7087 Rename `ImageEncoded` to `EncodedImage`
  CHANGELOG.md
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_types/definitions/rerun/archetypes.fbs
  crates/store/re_types/definitions/rerun/archetypes/encoded_image.fbs
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  crates/store/re_types/definitions/rerun/components/pixel_format.fbs
  crates/store/re_types/src/archetypes/.gitattributes
  crates/store/re_types/src/archetypes/encoded_image.rs
  crates/store/re_types/src/archetypes/encoded_image_ext.rs
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/archetypes/mod.rs
  crates/store/re_types/src/components/pixel_format.rs
  crates/store/re_types/src/datatypes/tensor_data_ext.rs
  crates/viewer/re_space_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  crates/viewer/re_viewer_context/src/tensor/image_decode_cache.rs
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/.gitattributes
  docs/content/reference/types/archetypes/encoded_image.md
  docs/content/reference/types/archetypes/image.md
  docs/content/reference/types/components/blob.md
  docs/content/reference/types/components/draw_order.md
  docs/content/reference/types/components/media_type.md
  docs/content/reference/types/components/opacity.md
  docs/content/reference/types/components/pixel_format.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
  docs/snippets/all/archetypes/encoded_image.cpp
  docs/snippets/all/archetypes/encoded_image.py
  docs/snippets/all/archetypes/encoded_image.rs
  docs/snippets/all/archetypes/image_advanced.py
  examples/python/nuscenes_dataset/README.md
  examples/python/nuscenes_dataset/nuscenes_dataset/__main__.py
  examples/python/objectron/README.md
  examples/python/objectron/objectron/__main__.py
  examples/python/open_photogrammetry_format/open_photogrammetry_format.py
  examples/python/structure_from_motion/structure_from_motion/__main__.py
  examples/rust/objectron/src/main.rs
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/.gitattributes
  rerun_cpp/src/rerun/archetypes/encoded_image.cpp
  rerun_cpp/src/rerun/archetypes/encoded_image.hpp
  rerun_cpp/src/rerun/archetypes/encoded_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/components/pixel_format.hpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/components/pixel_format.py
  rerun_py/tests/unit/test_image.py
Labels: 🚜 refactor, exclude from changelog, 🪵 Log-API

#7089 Fix docs: don't claim `Boxes2D` supports rotation
  crates/store/re_types/definitions/rerun/archetypes/boxes2d.fbs
  crates/store/re_types/src/archetypes/boxes2d.rs
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/boxes2d.md
  rerun_cpp/src/rerun/archetypes/boxes2d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
Labels: 📖 documentation, exclude from changelog

#7077 Refactor the time drag value widget code to make it more globally available
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/time_drag_value.rs
Labels: 🚜 refactor, exclude from changelog

#7076 `ChunkTimeline` -> `TimeColumn`, `log_temporal_batch` -> `send_columns`
  Cargo.lock
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/helpers.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/latest_at.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/range.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/entity_tree.rs
  crates/store/re_entity_db/src/time_histogram_per_timeline.rs
  crates/store/re_entity_db/src/times_per_timeline.rs
  crates/store/re_query/src/cache.rs
  crates/store/re_query/src/range.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/sdk.rs
  docs/snippets/all/tutorials/send_columns.py
  docs/snippets/all/tutorials/send_columns.rs
  docs/snippets/snippets.toml
  examples/rust/custom_store_subscriber/src/main.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/send_columns.py
  rerun_py/src/arrow.rs
  tests/python/log_benchmark/test_log_benchmark.py
  tests/python/plot_dashboard_stress/main.py
  tests/python/test_send_columns/main.py
  tests/rust/test_temporal_batch/Cargo.toml
  tests/rust/test_temporal_batch/src/main.rs
Labels: 🚜 refactor, exclude from changelog

#7097 Add link to GLOMAP example.
  examples/manifest.toml
  examples/python/glomap/README.md
Labels: examples, include in changelog

#7099 Hide the component default section for views without visualizers
  crates/viewer/re_selection_panel/src/defaults_ui.rs
Labels: ui, exclude from changelog

#7096 Add back `rr.ImageEncoded` for backwards compatibility
  CHANGELOG.md
  docs/content/reference/migration/migration-0-18.md
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_image_encoded.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/blob_ext.py
  rerun_py/tests/unit/test_image_encoded.py
Labels: 🐍 Python API, exclude from changelog

#7102 Change Image to use ImageBuffer instead of Blob
  crates/store/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  crates/store/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/image_buffer.fbs
  crates/store/re_types/src/archetypes/depth_image.rs
  crates/store/re_types/src/archetypes/depth_image_ext.rs
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/archetypes/segmentation_image_ext.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/image_buffer.rs
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/tests/depth_image.rs
  crates/store/re_types/tests/segmentation_image.rs
  crates/viewer/re_space_view_spatial/src/ui.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/image_info.rs
  crates/viewer/re_viewer_context/src/tensor/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/tensor/image_stats_cache.rs
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/archetypes/image.md
  docs/content/reference/types/archetypes/segmentation_image.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/blob.md
  docs/content/reference/types/components/image_buffer.md
  docs/content/reference/types/datatypes/blob.md
  rerun_cpp/src/rerun/archetypes/depth_image.cpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/depth_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/image.cpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/image_ext.cpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.cpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image_ext.cpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/image_buffer.hpp
  rerun_cpp/tests/archetypes/image.cpp
  rerun_cpp/tests/archetypes/segmentation_and_depth_image.cpp
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image_ext.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/image_buffer.py
  rerun_py/tests/unit/test_image.py
Labels: exclude from changelog, 🔩 data model

#7088 Create separate `ImageStats` for images
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/tensor/image_stats.rs
  crates/viewer/re_viewer_context/src/tensor/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/tensor/mod.rs
  crates/viewer/re_viewer_context/src/tensor/tensor_stats.rs
Labels: 🚜 refactor, exclude from changelog

#7091 Support decoding multiplexed RRD streams
  crates/store/re_data_source/src/load_stdin.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/viewer/re_viewer/src/loading.rs
Labels: enhancement, include in changelog, CLI

#7092 Improved CLI 3: stdin streaming support
  Cargo.lock
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/mod.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/top/rerun/src/commands/stdio.rs
Labels: 🧑‍💻 dev experience, 📉 performance, include in changelog, CLI

#7093 Streaming errors for encoders
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/saving.rs
  rerun_py/src/python_bridge.rs
Labels: 🧑‍💻 dev experience, 📉 performance, exclude from changelog, CLI

#7094 Improved CLI 4: stdout streaming support
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/top/rerun/src/commands/stdio.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/saving.rs
Labels: 🧑‍💻 dev experience, 📉 performance, include in changelog, CLI

#7095 Improved CLI 5: implement `rerun rrd filter`
  Cargo.lock
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/stdio.rs
Labels: 🧑‍💻 dev experience, 📉 performance, include in changelog, CLI

#7110 Re-enable per-series parallelism
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#7112 Query: configurable timeline|component eager slicing
  crates/store/re_query/src/lib.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/query.rs
  crates/viewer/re_space_view_text_log/src/visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, include in changelog

#7113 Higher compaction thresholds by default (x4)
  crates/store/re_chunk_store/src/store.rs
Labels: ⛃ re_datastore, 📉 performance, include in changelog

#7114 Fix CI: update test snapshots
  crates/store/re_chunk_store/tests/snapshots/memory_test__scalars_on_one_timeline_new.snap
Labels: 🔨 testing, exclude from changelog, :ship: CI

#7104 Add `__version__` and `__version_info__` to rerun package
  .github/workflows/release.yml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/tests/unit/test_version.py
  scripts/ci/update_rerun_py_version.py
  tests/python/release_checklist/check_version.py
Labels: 🐍 Python API, include in changelog

#7107 Update doc for `new_recording` API
  rerun_py/rerun_sdk/rerun/recording_stream.py
Labels: 📖 documentation, 🐍 Python API, exclude from changelog

#7116 Remove tiny profile scopes
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/src/query.rs
  crates/utils/re_tracing/src/lib.rs
  crates/viewer/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/viewer/re_renderer/src/allocator/data_texture_source.rs
Labels: 🧑‍💻 dev experience, 📉 performance, exclude from changelog

#7118 Pin `fixed` to `<1.28`
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog

#7103 C++ API for `send_columns`
  crates/top/re_sdk/src/lib.rs
  crates/top/rerun_c/src/lib.rs
  crates/top/rerun_c/src/rerun.h
  docs/snippets/all/tutorials/send_columns.cpp
  docs/snippets/all/tutorials/send_columns.py
  docs/snippets/all/tutorials/send_columns.rs
  docs/snippets/all/tutorials/send_columns_arrays.cpp
  docs/snippets/all/tutorials/send_columns_arrays.py
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/arrow_utils.hpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/indicator_component.cpp
  rerun_cpp/src/rerun/indicator_component.hpp
  rerun_cpp/src/rerun/partitioned_component_batch.cpp
  rerun_cpp/src/rerun/partitioned_component_batch.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/src/rerun/time_column.cpp
  rerun_cpp/src/rerun/time_column.hpp
  rerun_cpp/src/rerun/timeline.cpp
  rerun_cpp/src/rerun/timeline.hpp
  rerun_cpp/tests/collection.cpp
  rerun_py/rerun_sdk/rerun/send_columns.py
  tests/python/test_send_columns/main.py
Labels: 🌊 C++ API, include in changelog

#7075 Update the UI colors to use our (blueish) ramp instead of pure greys
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/section_collapsing_header.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewport_blueprint/src/ui/add_space_view_or_container_modal.rs
Labels: ui, include in changelog

#7119 Do instancing on superfluous leaf transforms for Boxes & Ellipsoids
  crates/store/re_chunk/src/helpers.rs
  crates/store/re_types/definitions/rerun/archetypes/boxes3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/ellipsoids.fbs
  crates/store/re_types/src/archetypes/boxes3d.rs
  crates/store/re_types/src/archetypes/ellipsoids3d.rs
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  docs/content/reference/types/archetypes/boxes3d.md
  docs/content/reference/types/archetypes/ellipsoids3d.md
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/ellipsoids3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  tests/python/release_checklist/check_component_and_transform_clamping.py
Labels: 🪳 bug, enhancement, 📺 re_viewer, exclude from changelog

#7123 Fix doclinks in .fbs file
  crates/store/re_types/definitions/rerun/components/image_buffer.fbs
  crates/store/re_types/definitions/rerun/components/image_format.fbs
  crates/store/re_types/definitions/rerun/datatypes/image_format.fbs
  crates/store/re_types/src/components/image_buffer.rs
  crates/store/re_types/src/components/image_format.rs
  crates/store/re_types/src/datatypes/image_format.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/image_buffer.md
  docs/content/reference/types/components/image_format.md
  docs/content/reference/types/datatypes.md
  docs/content/reference/types/datatypes/image_format.md
  rerun_cpp/src/rerun/components/image_buffer.hpp
  rerun_cpp/src/rerun/components/image_format.hpp
  rerun_cpp/src/rerun/datatypes/image_format.hpp
  rerun_py/rerun_sdk/rerun/components/image_buffer.py
  rerun_py/rerun_sdk/rerun/components/image_format.py
  rerun_py/rerun_sdk/rerun/datatypes/image_format.py
Labels: 📖 documentation, exclude from changelog

#7111 Always log all components of `Transform3D`
  README.md
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/lib.rs
  crates/store/re_types/definitions/rerun/archetypes/leaf_transforms3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/definitions/rerun/attributes.fbs
  crates/store/re_types/src/archetypes/leaf_transforms3d.rs
  crates/store/re_types/src/archetypes/mesh3d.rs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/transform3d_ext.rs
  crates/store/re_types/tests/transform3d.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  docs/content/getting-started/data-in/rust.md
  docs/content/reference/migration/migration-0-18.md
  docs/content/reference/types/archetypes/leaf_transforms3d.md
  docs/content/reference/types/archetypes/transform3d.md
  docs/snippets/all/archetypes/leaf_transforms3d_combined.rs
  docs/snippets/all/archetypes/mesh3d_leaf_transforms3d.rs
  docs/snippets/all/archetypes/transform3d_axes.cpp
  docs/snippets/all/archetypes/transform3d_axes.py
  docs/snippets/all/archetypes/transform3d_axes.rs
  docs/snippets/build.rs
  rerun_cpp/src/rerun/archetypes/leaf_transforms3d.cpp
  rerun_cpp/src/rerun/archetypes/leaf_transforms3d.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.cpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/component_batch.hpp
  rerun_py/rerun_sdk/rerun/archetypes/leaf_transforms3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/tests/unit/test_leaf_transforms3d.py
  rerun_py/tests/unit/test_transform3d.py
Labels: exclude from changelog, 🔩 data model

#7129 Optimize out unnecessary sorts in line series visualizer
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#7135 Notify store subscribers of dropped entities
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, ⛃ re_datastore, exclude from changelog

#7106 Add a backwards compatible rotations helpers for Boxes3D
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d_ext.py
  rerun_py/tests/unit/test_box3d.py
Labels: 🐍 Python API, exclude from changelog

#7120 Drop, rather than clear, removed blueprint entities
  crates/store/re_entity_db/src/entity_db.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/command_sender.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/space_view.rs
Labels: 🟦 blueprint, include in changelog

#7125 Make naming around columns/batches more consistent
  crates/top/rerun_c/src/lib.rs
  crates/top/rerun_c/src/rerun.h
  docs/snippets/all/tutorials/send_columns.py
  docs/snippets/all/tutorials/send_columns_arrays.cpp
  docs/snippets/all/tutorials/send_columns_arrays.py
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/component_column.cpp
  rerun_cpp/src/rerun/component_column.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/send_columns.py
  tests/python/plot_dashboard_stress/main.py
Labels: 🚜 refactor, exclude from changelog

#7128 Better ui for `Blob`s, especially those representing images
  Cargo.lock
  Cargo.toml
  crates/store/re_query/src/latest_at.rs
  crates/store/re_types/src/components/media_type_ext.rs
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_name.rs
  crates/viewer/re_data_ui/src/component_ui_registry.rs
  crates/viewer/re_data_ui/src/data_source.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_data_ui/src/pinhole.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_edit_ui/src/datatype_editors/singleline_string.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_space_view/src/view_property_ui.rs
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
  crates/viewer/re_space_view_dataframe/src/time_range_table.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/command_sender.rs
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: ui, 📺 re_viewer, include in changelog

#7139 Fix main build
  crates/viewer/re_space_view_dataframe/src/view_query.rs
Labels: 🪳 bug, exclude from changelog

#7131 Implement `RangeQueryOptions` directly within `RangeQuery`
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/range.rs
  crates/store/re_chunk/tests/range.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_query/src/lib.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/query.rs
  crates/viewer/re_space_view_text_log/src/visualizer_system.rs
Labels: 🔍 re_query, 🚜 refactor, include in changelog

#7132 Implement support for `RangeQueryOptions::include_extended_bounds`
  .github/workflows/labels.yml
  crates/store/re_chunk/src/range.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_query/src/range.rs
Labels: 🔍 re_query, include in changelog

#7133 Implement timeseries query clamping
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/space_view_class.rs
  crates/viewer/re_space_view_time_series/src/util.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer_context/src/app_options.rs
Labels: 📺 re_viewer, 🔍 re_query, 📉 performance, include in changelog

#7140 Disambiguate plot labels with multiple entities ending with the same part
  crates/store/re_log_types/src/path/entity_path.rs
  crates/viewer/re_space_view_time_series/src/lib.rs
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/space_view_class.rs
  crates/viewer/re_space_view_time_series/src/util.rs
Labels: 🪳 bug, ui, include in changelog

#7142 Fix formatting
  crates/store/re_chunk/src/range.rs
Labels: 😤 annoying, exclude from changelog, :ship: CI

#7044 Add `FillMode::MajorWireframe` for more significant ellipsoid wireframes.
  Cargo.lock
  Cargo.toml
  crates/store/re_types/definitions/rerun/components/fill_mode.fbs
  crates/store/re_types/src/components/fill_mode.rs
  crates/viewer/re_space_view_spatial/src/proc_mesh.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  docs/content/reference/types/components/fill_mode.md
  rerun_cpp/src/rerun/components/fill_mode.hpp
  rerun_py/rerun_sdk/rerun/components/fill_mode.py
  rerun_py/tests/unit/test_box3d.py
  rerun_py/tests/unit/test_ellipsoids3d.py
  scripts/lint.py
Labels: 📺 re_viewer, 🍏 primitives, exclude from changelog

#7127 Add numeric SDK version macros to C/C++
  .github/workflows/release.yml
  CMakeLists.txt
  crates/top/rerun_c/CMakeLists.txt
  crates/top/rerun_c/src/lib.rs
  crates/top/rerun_c/src/rerun.h
  rerun_cpp/CMakeLists.txt
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/c/sdk_info.h
  rerun_cpp/src/rerun/sdk_info.hpp
  rerun_cpp/tests/sdk_info.cpp
  scripts/ci/update_rerun_py_and_c_version.py
  scripts/ci/update_rerun_py_version.py
Labels: 🌊 C++ API, include in changelog

#7144 Fix naming and config of instance pose related snippets
  crates/store/re_types/definitions/rerun/archetypes/instance_poses3d.fbs
  docs/content/reference/types/archetypes/instance_poses3d.md
  docs/snippets/all/archetypes/instance_poses3d_combined.cpp
  docs/snippets/all/archetypes/instance_poses3d_combined.py
  docs/snippets/all/archetypes/instance_poses3d_combined.rs
  docs/snippets/snippets.toml
Labels: 🔨 testing, exclude from changelog

#7150 Handle windows file handling issues in test_image_encoded.py
  rerun_py/tests/unit/test_image_encoded.py
Labels: 🔨 testing, 🪟 windows, exclude from changelog

#7147 Show preview of `Image/DepthImage/SegmentationImage` when selected
  Cargo.lock
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/instance_path.rs
Labels: ui, exclude from changelog

#7151 Workaround for OpenCV TLS issue on linux arm64 ci
  .github/workflows/reusable_test_wheels.yml
Labels: exclude from changelog, :ship: CI

#7154 re_web_viewer_server: include static files from symlink
  crates/viewer/re_web_viewer_server/src/lib.rs
Labels: exclude from changelog, :ship: CI

#7149 CLI manual
  Cargo.lock
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
  docs/content/reference/cli.md
  pixi.toml
  scripts/lint.py
Labels: 📖 documentation, include in changelog, CLI

#7153 Improvements for migration guide 0.17 -> 0.18
  docs/content/reference/migration/migration-0-18.md
Labels: 📖 documentation, exclude from changelog

#7161 Handle compaction events in cache subscriber
  crates/store/re_query/src/cache.rs
Labels: 🪳 bug, 📉 performance, exclude from changelog

#7159 Fix broken querying logic with the dataframe view in time range mode
  crates/viewer/re_space_view_dataframe/src/time_range_table.rs
Labels: 🪳 bug, ui, exclude from changelog

#7162 Fixed crash with empty arrow arrays
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
Labels: 🪳 bug, ui, exclude from changelog

#7156 Add button for copying and saving images
  Cargo.lock
  crates/store/re_types/src/datatypes/pixel_format_ext.rs
  crates/store/re_types/src/image.rs
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/image_format.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_renderer/shader/decodings.wgsl
  crates/viewer/re_space_view_dataframe/src/view_query.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/file_dialog.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
  crates/viewer/re_viewer_context/src/image_info.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  tests/python/test_api/test_api.py
Labels: ui, 📺 re_viewer, include in changelog

#7160 Include listarray in rerun_py extension type bypass
  rerun_py/src/arrow.rs
Labels: 🪳 bug, exclude from changelog

#7158 Stress test with send_columns for Rust & C++, improve C++ TimeColumn api, fix reporting
  rerun_cpp/src/rerun/time_column.cpp
  rerun_cpp/src/rerun/time_column.hpp
  tests/cpp/plot_dashboard_stress/main.cpp
  tests/python/plot_dashboard_stress/main.py
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 🔨 testing, exclude from changelog

#7168 Fix release checklist crashing
  tests/python/release_checklist/check_all_components_ui.py
  tests/python/release_checklist/check_context_menu_suggested_origin.py
Labels: 🪳 bug, 🔨 testing, exclude from changelog

#7163 Sanity check the size of the image buffer in C++
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/datatypes/image_format_ext.rs
  crates/store/re_types/src/datatypes/pixel_format_ext.rs
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/depth_image_ext.cpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/image_ext.cpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image_ext.cpp
  rerun_cpp/src/rerun/components/image_buffer.hpp
  rerun_cpp/src/rerun/components/image_buffer_ext.cpp
  rerun_cpp/src/rerun/datatypes/blob.hpp
  rerun_cpp/src/rerun/datatypes/blob_ext.cpp
  rerun_cpp/src/rerun/datatypes/image_format.hpp
  rerun_cpp/src/rerun/datatypes/image_format_ext.cpp
  rerun_cpp/src/rerun/image_utils.hpp
  rerun_cpp/tests/archetypes/segmentation_and_depth_image.cpp
Labels: 🌊 C++ API, exclude from changelog

#7164 New example for the `Ellipsoids3D` archetype
  Cargo.lock
  crates/store/re_types/definitions/rerun/archetypes/ellipsoids3d.fbs
  docs/content/reference/types/archetypes/ellipsoids3d.md
  docs/snippets/Cargo.toml
  docs/snippets/README.md
  docs/snippets/all/archetypes/ellipsoid3d_simple.cpp
  docs/snippets/all/archetypes/ellipsoid3d_simple.py
  docs/snippets/all/archetypes/ellipsoid3d_simple.rs
  docs/snippets/build.rs
  docs/snippets/snippets.toml
Labels: 📖 documentation, exclude from changelog

#7169 Fix transform arrows showing up everywhere
  crates/viewer/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#7171 Fix wrong edit UI for `Colormap`
  crates/viewer/re_edit_ui/src/lib.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
  tests/python/release_checklist/check_colormap_edit_ui.py
Labels: ui, 🦟 regression, exclude from changelog

#7174 Fix some component UI
  crates/viewer/re_edit_ui/src/datatype_editors/enum_combobox.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
Labels: 🪳 bug, ui, exclude from changelog

#7172 Add `send_columns` examples for images, fix rust `send_columns` handling of listarrays
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  crates/store/re_types/definitions/rerun/components/blob.fbs
  crates/store/re_types/definitions/rerun/datatypes/blob.fbs
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/components/blob.rs
  crates/store/re_types/src/components/image_format_ext.rs
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/datatypes/blob.rs
  crates/store/re_types/src/datatypes/blob_ext.rs
  crates/store/re_types/src/datatypes/image_format_ext.rs
  crates/store/re_types_core/src/arrow_buffer.rs
  crates/top/re_sdk/src/recording_stream.rs
  docs/content/reference/types/archetypes/image.md
  docs/snippets/all/archetypes/image_send_columns.cpp
  docs/snippets/all/archetypes/image_send_columns.py
  docs/snippets/all/archetypes/image_send_columns.rs
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/components/image_format.hpp
  rerun_cpp/src/rerun/components/image_format_ext.cpp
  rerun_py/rerun_sdk/rerun/archetypes/image.py
Labels: examples, include in changelog

#7181 Handle compaction events in latest-at cache subscriber
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_query/src/cache.rs
Labels: 🪳 bug, 📉 performance, exclude from changelog

#7180 Make the recordings panel resizable
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: 📺 re_viewer, include in changelog

#7182 Deal with invalidation parallelism-induced memleak
  crates/store/re_query/src/cache.rs
  crates/store/re_query/src/latest_at.rs
Labels: 🪳 bug, 📉 performance, exclude from changelog

#7179 Ensure example .rrd files have description first
  Cargo.lock
  crates/build/re_dev_tools/Cargo.toml
  crates/build/re_dev_tools/src/build_examples/install.rs
  crates/build/re_dev_tools/src/build_examples/rrd.rs
  crates/build/re_dev_tools/src/build_examples/snippets.rs
  crates/build/re_dev_tools/src/build_examples/wait_for_output.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_entity_db/src/entity_db.rs
Labels: examples, exclude from changelog

#7178 Move existing scalar & point cloud `send_columns` examples to scalar/point3d snippets
  crates/build/re_types_builder/src/codegen/common.rs
  crates/build/re_types_builder/src/codegen/docs/mod.rs
  crates/store/re_types/definitions/rerun/archetypes/points3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/scalar.fbs
  crates/store/re_types/definitions/rerun/components/blob.fbs
  crates/store/re_types/definitions/rerun/datatypes/blob.fbs
  crates/store/re_types/src/components/blob.rs
  crates/store/re_types/src/datatypes/blob.rs
  docs/content/reference/types/archetypes/points3d.md
  docs/content/reference/types/archetypes/scalar.md
  docs/snippets/all/archetypes/points3d_send_columns.cpp
  docs/snippets/all/archetypes/points3d_send_columns.py
  docs/snippets/all/archetypes/scalar_send_columns.cpp
  docs/snippets/all/archetypes/scalar_send_columns.py
  docs/snippets/all/archetypes/scalar_send_columns.rs
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
Labels: examples, exclude from changelog

#7185 Add support for `rerun rrd filter --drop-entity`
  crates/top/rerun/src/commands/rrd/filter.rs
Labels: 🧑‍💻 dev experience, include in changelog, CLI

#7186 Fix `MarkerSize` handling
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
Labels: ui, 🦟 regression, exclude from changelog

#7184 Simple ad-hoc solution for plot discontinuities
  crates/store/re_entity_db/tests/clear.rs
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  tests/python/release_checklist/check_scalar_clears.py
Labels: 🦟 regression, exclude from changelog

#7187 Fix fallback for Pinhole resolution
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_spatial/src/ui_2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
Labels: 🪳 bug, 📺 re_viewer, 🦟 regression, exclude from changelog

#7196 Fix broken unsetting of blueprint components
  crates/viewer/re_space_view/src/view_property_ui.rs
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
Labels: 🪳 bug, ui, 📺 re_viewer, 🦟 regression, exclude from changelog

#7199 Ignore `RowId` in zipping iterators
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/results_ext.rs
  crates/viewer/re_space_view/src/time_key.rs
  crates/viewer/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_space_view_text_log/src/visualizer_system.rs
  tests/python/release_checklist/check_static_override.py
Labels: 🪳 bug, 🦟 regression, exclude from changelog

#7189 Update example screenshots, improve pinhole example, fix `DisconnectedSpace` docs
  crates/store/re_types/definitions/rerun/archetypes/annotation_context.fbs
  crates/store/re_types/definitions/rerun/archetypes/boxes3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/store/re_types/definitions/rerun/archetypes/disconnected_space.fbs
  crates/store/re_types/definitions/rerun/archetypes/line_strips2d.fbs
  crates/store/re_types/definitions/rerun/archetypes/line_strips3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/mesh3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/pinhole.fbs
  crates/store/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/store/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/store/re_types/definitions/rerun/components/disconnected_space.fbs
  crates/store/re_types/src/archetypes/annotation_context.rs
  crates/store/re_types/src/archetypes/boxes3d.rs
  crates/store/re_types/src/archetypes/disconnected_space.rs
  crates/store/re_types/src/archetypes/line_strips2d.rs
  crates/store/re_types/src/archetypes/line_strips3d.rs
  crates/store/re_types/src/archetypes/mesh3d.rs
  crates/store/re_types/src/archetypes/pinhole.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/components/disconnected_space.rs
  docs/content/reference/types/archetypes/annotation_context.md
  docs/content/reference/types/archetypes/boxes3d.md
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/archetypes/disconnected_space.md
  docs/content/reference/types/archetypes/line_strips2d.md
  docs/content/reference/types/archetypes/line_strips3d.md
  docs/content/reference/types/archetypes/mesh3d.md
  docs/content/reference/types/archetypes/pinhole.md
  docs/content/reference/types/archetypes/points2d.md
  docs/content/reference/types/archetypes/segmentation_image.md
  docs/snippets/all/archetypes/pinhole_perspective.cpp
  docs/snippets/all/archetypes/pinhole_perspective.py
  docs/snippets/all/archetypes/pinhole_perspective.rs
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/disconnected_space.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/components/disconnected_space.hpp
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/disconnected_space.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  scripts/screenshot_compare/assets/templates/index.html
  scripts/screenshot_compare/build_screenshot_compare.py
Labels: 📖 documentation, examples, include in changelog

#7202 Clear source before adding receiver in history
  crates/viewer/re_viewer/src/history.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#7190 Use an ImageBuffer/ImageFormat for Mesh3D albedo texture
  crates/store/re_types/definitions/rerun/archetypes/mesh3d.fbs
  crates/store/re_types/src/archetypes/mesh3d.rs
  crates/store/re_types/src/archetypes/mesh3d_ext.rs
  crates/store/re_types/src/datatypes/tensor_data_ext.rs
  crates/store/re_types/src/tensor_data.rs
  crates/store/re_types/tests/mesh3d.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_renderer/shader/instanced_mesh.wgsl
  crates/viewer/re_space_view_spatial/src/mesh_loader.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
  docs/content/reference/types/archetypes/mesh3d.md
  docs/content/reference/types/components/image_buffer.md
  docs/content/reference/types/components/image_format.md
  docs/content/reference/types/components/tensor_data.md
  rerun_cpp/src/rerun/archetypes/mesh3d.cpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d_ext.py
Labels: 🦀 Rust API, include in changelog, 🔩 data model

#7203 Improve fallback provider for timeseries `Name` component
  crates/viewer/re_space_view_time_series/src/lib.rs
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/space_view_class.rs
  crates/viewer/re_space_view_time_series/src/util.rs
Labels: ui, exclude from changelog

#7205 Mark required components only be there if they're not logged as empty array
  crates/viewer/re_viewer_context/src/space_view/visualizer_entity_subscriber.rs
Labels: 📺 re_viewer, exclude from changelog

#7206 Fix a ui issue where a visualiser would have both an override and default set for some component
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
Labels: 🪳 bug, ui, include in changelog

#7207 Fix serialization of UTF8List, causing VisualizerOverride to be broken
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/utf8list_ext.py
  rerun_py/tests/unit/test_utf8list.py
Labels: 🪳 bug, 🐍 Python API, 🦟 regression, exclude from changelog

#7209 Remove extra separator line between panels
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🪳 bug, ui, exclude from changelog

#7212 Document `send_columns`
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  crates/store/re_types/src/archetypes/image.rs
  docs/content/concepts/batches.md
  docs/content/concepts/timelines.md
  docs/content/howto.md
  docs/content/howto/send_columns.md
  docs/content/reference/types/archetypes/image.md
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_py/rerun_sdk/rerun/archetypes/image.py
Labels: 📖 documentation, exclude from changelog

#7214 Call out `send_columns` in data loader and plot examples
  docs/snippets/all/archetypes/image_send_columns.py
  examples/cpp/external_data_loader/README.md
  examples/python/external_data_loader/README.md
  examples/python/plots/README.md
  examples/rust/external_data_loader/README.md
  rerun_py/rerun_sdk/rerun/archetypes/image.py
Labels: 📖 documentation, examples, exclude from changelog

#7208 Deduplicate space view label processing code
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/labels.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/mod.rs
Labels: 📺 re_viewer, exclude from changelog

#7215 Fix error when trying to clear non-existant component
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_space_view/src/view_property_ui.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/space_view/view_context.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#7221 Correct dependency on `puffin` to 0.19.1, preventing a possible build failure.
  Cargo.toml
Labels: dependencies, include in changelog

#7220 Remove “has not yet been released” from migration-0-18.md
  docs/content/reference/migration/migration-0-18.md
Labels: 📖 documentation, exclude from changelog

#7228 Update `time` crate to 0.3.36, fixing compilation on newer Rust versions
  Cargo.lock
Labels: dependencies, include in changelog

#7235 Fix typo in arrow_cpp_install.md
  rerun_cpp/arrow_cpp_install.md
Labels: 📖 documentation, exclude from changelog

#7239 Dead code removal, renames, and clean-up
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/README.md
  crates/viewer/re_component_ui/src/color.rs
  crates/viewer/re_component_ui/src/datatype_editors/bool_toggle.rs
  crates/viewer/re_component_ui/src/datatype_editors/enum_combobox.rs
  crates/viewer/re_component_ui/src/datatype_editors/float_drag.rs
  crates/viewer/re_component_ui/src/datatype_editors/mod.rs
  crates/viewer/re_component_ui/src/datatype_editors/singleline_string.rs
  crates/viewer/re_component_ui/src/datatype_editors/vec.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/marker_shape.rs
  crates/viewer/re_component_ui/src/radius.rs
  crates/viewer/re_component_ui/src/range1d.rs
  crates/viewer/re_component_ui/src/response_utils.rs
  crates/viewer/re_component_ui/src/timeline.rs
  crates/viewer/re_component_ui/src/transforms.rs
  crates/viewer/re_component_ui/src/visual_bounds2d.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/image_meaning.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_data_ui/src/log_msg.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
Labels: 🚜 refactor, exclude from changelog

#7242 Fix search index build
  .github/workflows/on_push_docs.yml
  Cargo.lock
  crates/build/re_dev_tools/Cargo.toml
  crates/build/re_dev_tools/src/build_search_index/ingest/rust.rs
  crates/viewer/re_web_viewer_server/src/lib.rs
  pixi.lock
  pixi.toml
Labels: 📖 documentation, exclude from changelog

#7246 Install sdk_info.h even if RERUN_INSTALL_RERUN_C option is OFF
  rerun_cpp/CMakeLists.txt
Labels: 🪳 bug, 🌊 C++ API, include in changelog

#7250 Combine `re_types` integration tests into one test target.
  crates/store/re_types/Cargo.toml
  crates/store/re_types/tests/types/annotation_context.rs
  crates/store/re_types/tests/types/arrows3d.rs
  crates/store/re_types/tests/types/asset3d.rs
  crates/store/re_types/tests/types/box2d.rs
  crates/store/re_types/tests/types/box3d.rs
  crates/store/re_types/tests/types/clear.rs
  crates/store/re_types/tests/types/depth_image.rs
  crates/store/re_types/tests/types/disconnected_space.rs
  crates/store/re_types/tests/types/fuzzy.rs
  crates/store/re_types/tests/types/image.rs
  crates/store/re_types/tests/types/line_strips2d.rs
  crates/store/re_types/tests/types/line_strips3d.rs
  crates/store/re_types/tests/types/main.rs
  crates/store/re_types/tests/types/mesh3d.rs
  crates/store/re_types/tests/types/mint_conversions.rs
  crates/store/re_types/tests/types/pinhole.rs
  crates/store/re_types/tests/types/points2d.rs
  crates/store/re_types/tests/types/points3d.rs
  crates/store/re_types/tests/types/segmentation_image.rs
  crates/store/re_types/tests/types/tensor.rs
  crates/store/re_types/tests/types/text_document.rs
  crates/store/re_types/tests/types/transform3d.rs
  crates/store/re_types/tests/types/util.rs
  crates/store/re_types/tests/types/validity.rs
  crates/store/re_types/tests/types/view_coordinates.rs
Labels: 🧑‍💻 dev experience, ⏱ build-times, exclude from changelog

#7219 Fix references to closed tickets
  crates/build/re_types_builder/src/bin/build_re_types.rs
  crates/build/re_types_builder/src/codegen/mod.rs
  crates/build/re_types_builder/src/lib.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_log_encoding/src/stream_rrd_from_http.rs
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/tuid.rs
  crates/store/re_ws_comms/src/lib.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/rerun/src/lib.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer_examples/2d.rs
  crates/viewer/re_renderer_examples/depth_cloud.rs
  crates/viewer/re_renderer_examples/depth_offset.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_renderer_examples/outlines.rs
  crates/viewer/re_renderer_examples/picking.rs
  crates/viewer/re_space_view_spatial/src/lib.rs
  crates/viewer/re_space_view_tensor/src/lib.rs
  crates/viewer/re_space_view_time_series/src/lib.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer_context/src/image_info.rs
  crates/viewer/re_viewport/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/space_view_contents.rs
  docs/snippets/build.rs
  docs/snippets/snippets.toml
  rerun_py/tests/unit/test_instance_pose3d.py
  rerun_py/tests/unit/test_transform3d.py
  scripts/zombie_todos.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#7251 Fix gamma (srgb EOTF) for GLTF via `Asset3D` embedded rgb(a) textures
  crates/viewer/re_renderer/src/importer/gltf.rs
Labels: 🪳 bug, 🔺 re_renderer, 📺 re_viewer, include in changelog

#7240 Consistently call it "latest-at", with a dash
  CHANGELOG.md
  crates/store/re_chunk/src/latest_at.rs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/dataframe_query.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/visible_time_ranges.fbs
  crates/store/re_types/definitions/rerun/blueprint/components/latest_at_queries.fbs
  crates/store/re_types/definitions/rerun/blueprint/datatypes/latest_at_query.fbs
  crates/store/re_types/src/blueprint/archetypes/dataframe_query.rs
  crates/store/re_types/src/blueprint/archetypes/visible_time_ranges.rs
  crates/store/re_types/src/blueprint/components/latest_at_queries.rs
  crates/store/re_types/src/blueprint/datatypes/latest_at_query.rs
  crates/viewer/re_space_view_dataframe/src/latest_at_table.rs
  crates/viewer/re_space_view_dataframe/src/query_kind_ui.rs
  crates/viewer/re_space_view_dataframe/src/space_view_class.rs
  crates/viewer/re_space_view_dataframe/src/time_range_table.rs
  crates/viewer/re_space_view_dataframe/src/view_query.rs
  crates/viewer/re_viewer/src/reflection/mod.rs
  crates/viewer/re_viewer_context/src/query_context.rs
  docs/content/concepts/batches.md
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-in/rust.md
  rerun_cpp/src/rerun/blueprint/archetypes/dataframe_query.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/visible_time_ranges.hpp
  rerun_cpp/src/rerun/blueprint/components/latest_at_queries.hpp
  rerun_cpp/src/rerun/blueprint/datatypes/latest_at_query.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/dataframe_query.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/visible_time_ranges.py
  rerun_py/rerun_sdk/rerun/blueprint/components/latest_at_queries.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/latest_at_query.py
Labels: 📖 documentation, exclude from changelog

#7244 Link to the per-language docs for `send_columns`
  docs/content/howto/send_columns.md
Labels: 📖 documentation, exclude from changelog

#7243 Remove references to justfile
  crates/build/re_types_builder/README.md
  crates/build/re_types_builder/src/bin/build_re_types.rs
  crates/store/re_types/README.md
  rerun_cpp/README.md
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#7211 Show single-line editor if there is no multiline editor
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
Labels: ui, exclude from changelog

#7213 Fix python version updating script
  rerun_py/tests/unit/test_version.py
  scripts/ci/update_rerun_py_and_c_version.py
Labels: 🪳 bug, exclude from changelog, :ship: CI

#7230 Fix url to event.rs in `rerun analytics details`
  crates/utils/re_analytics/src/cli.rs
Labels: 📖 documentation, exclude from changelog

#7238 BGR(A) image format support
  crates/store/re_types/definitions/rerun/datatypes/color_model.fbs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/datatypes/color_model.rs
  crates/store/re_types/src/datatypes/color_model_ext.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_renderer/shader/rectangle.wgsl
  crates/viewer/re_renderer/shader/rectangle_fs.wgsl
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_space_view_spatial/src/mesh_loader.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
  crates/viewer/re_viewer_context/src/image_info.rs
  docs/content/reference/types/datatypes/color_model.md
  docs/snippets/all/archetypes/image_advanced.py
  examples/python/arkit_scenes/arkit_scenes/__main__.py
  examples/python/face_tracking/face_tracking.py
  examples/python/gesture_detection/gesture_detection.py
  examples/python/human_pose_tracking/human_pose_tracking.py
  examples/python/live_camera_edge_detection/live_camera_edge_detection.py
  examples/python/ocr/ocr.py
  examples/python/rgbd/rgbd.py
  examples/python/segment_anything_model/segment_anything_model.py
  examples/python/structure_from_motion/structure_from_motion/__main__.py
  rerun_cpp/src/rerun/datatypes/color_model.hpp
  rerun_cpp/src/rerun/image_utils.hpp
  rerun_notebook/package-lock.json
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/color_model.py
  tests/python/release_checklist/check_bgr.py
Labels: enhancement, 📺 re_viewer, include in changelog

#7231 Fix header levels in `sdk-operating-modes.md`
  docs/content/reference/sdk-operating-modes.md
Labels: 📖 documentation, exclude from changelog

#7241 Hide time controls if there is only one time point on a timeline
  crates/viewer/re_time_panel/src/lib.rs
Labels: ui, 😤 annoying, include in changelog

#7229 Speed up data density graph by rendering them more coarsly
  crates/viewer/re_time_panel/src/data_density_graph.rs
Labels: 📉 performance, include in changelog

#7256 Remove `Datatype` and `DatatypeBatch`
  crates/store/re_types/src/lib.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/loggable.rs
  crates/store/re_types_core/src/loggable_batch.rs
  crates/top/re_sdk/src/lib.rs
  docs/snippets/all/tutorials/custom_data.rs
Labels: 🚜 refactor, include in changelog

#7258 Remove `LoggableBatch::num_instances`
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/loggable_batch.rs
Labels: do-not-merge, 🚜 refactor, include in changelog

#7262 re_arrow2 0.17.5
  Cargo.lock
Labels: dependencies, include in changelog

#7264 Fix main (`cargo insta review`)
  crates/store/re_chunk_store/tests/snapshots/memory_test__scalars_on_one_timeline_new.snap
Labels: 🔨 testing, exclude from changelog, :ship: CI

#7263 Default `RERUN_CHUNK_MAX_BYTES` to 384kiB instead of 4MiB
  crates/store/re_chunk_store/src/store.rs
Labels: ⛃ re_datastore, 📺 re_viewer, 📉 performance, include in changelog

#7259 Add `rerun::external::ndarray`
  crates/store/re_types/src/lib.rs
Labels: 🦀 Rust API, include in changelog

#7269 Fix a bunch of broken links
  ARCHITECTURE.md
  crates/store/re_types/definitions/rerun/components/show_labels.fbs
  crates/store/re_types_core/src/lib.rs
  docs/content/howto.md
  docs/content/reference/sdk-micro-batching.md
  docs/content/reference/store-compaction.md
  docs/content/reference/types/components/show_labels.md
  docs/content/reference/types/datatypes/bool.md
  examples/cpp/external_data_loader/README.md
  examples/rust/README.md
  rerun_cpp/README.md
  rerun_cpp/cmake_setup_in_detail.md
  scripts/lint.py
Labels: 📖 documentation, exclude from changelog

#7260 Remove unused `Loggable::extended_arrow_datatype`
  crates/store/re_types_core/src/loggable.rs
  crates/store/re_types_core/src/tuid.rs
Labels: 🚜 refactor, include in changelog

#7291 Handle proper half-size splatting semantics in from_mins_and_sizes
  crates/store/re_types/src/archetypes/boxes2d_ext.rs
  crates/store/re_types/src/archetypes/boxes3d_ext.rs
Labels: 🪳 bug, 🦀 Rust API, include in changelog

#7288 Fix VisualizerOverrides serializer and improved error handling
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/utf8list.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/utf8list_ext.py
  rerun_py/tests/unit/test_utf8list.py
  tests/python/release_checklist/check_blueprint_overrides.py
Labels: 🪳 bug, 🐍 Python API, 📺 re_viewer, include in changelog

#7297 Fix and test all known `HybridResults` issues from 0.18
  crates/store/re_chunk/src/chunk.rs
  crates/viewer/re_space_view/src/lib.rs
  crates/viewer/re_space_view/src/results_ext.rs
  crates/viewer/re_space_view/src/time_key.rs
  crates/viewer/re_space_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_space_view_spatial/src/visualizers/images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_space_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_space_view_text_log/src/visualizer_system.rs
  tests/python/release_checklist/check_latest_at_partial_updates.py
  tests/python/release_checklist/check_range_partial_updates.py
Labels: 🪳 bug, 🔨 testing, 🦟 regression, include in changelog

#7300 Speed up handling of large numbers of transform entities
  crates/viewer/re_space_view_spatial/src/contexts/transform_context.rs
  crates/viewer/re_space_view_spatial/src/transform_component_tracker.rs
  crates/viewer/re_space_view_spatial/src/visualizers/transform3d_arrows.rs
Labels: 📉 performance, include in changelog

#7266 Pass `ShowLabels` default through component fallback provider system.
  crates/viewer/re_space_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/labels.rs
  crates/viewer/re_space_view_spatial/src/visualizers/utilities/mod.rs
Labels: 📺 re_viewer, exclude from changelog

#7302 Fix secondary plot components ignoring blueprint defaults
  crates/viewer/re_space_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_space_view_time_series/src/point_visualizer_system.rs
  tests/python/release_checklist/check_latest_at_partial_updates.py
  tests/python/release_checklist/check_range_partial_updates.py
Labels: 🪳 bug, include in changelog

#7307 Fix post-release version bump
  .github/workflows/release.yml
Labels: exclude from changelog, :ship: CI

#7308 Update `time` crate to 0.3.36, fixing compilation on newer Rust versions
  Cargo.lock
  Cargo.toml
Labels: dependencies, 🦟 regression, include in changelog

#7306 add sam2_depthanything example
  examples/manifest.toml
  examples/python/sam2_depthanything/README.md
Labels: examples, exclude from changelog

#7309 Improve video data loader
  Cargo.lock
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/loader_archetype.rs
Labels: exclude from changelog

#7311 Cherry-pick 0.18.1's changelog
  CHANGELOG.md
Labels: 📖 documentation, exclude from changelog

#7313 Fix `video_simple` snippet
  docs/assets/empty.mp4
  docs/snippets/all/archetypes/video_simple.cpp
  docs/snippets/all/archetypes/video_simple.py
  docs/snippets/all/archetypes/video_simple.rs
  docs/snippets/snippets.toml
Labels: exclude from changelog
