Repository rerun-io/rerun, pull requests merged in 2025-10, with the labels that each got.

#11382 logging: filter noisy dependency logs (dataplatform)
  crates/utils/re_perf_telemetry/src/telemetry.rs
Labels: exclude from changelog, dataplatform

#11386 dont hardcode build mode into `BuildInfo`
  crates/build/re_build_info/src/build_info.rs
  crates/build/re_build_info/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/utils/re_analytics/src/lib.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
Labels: exclude from changelog, dataplatform

#11328 Snapshot utility function in TestContext
  crates/viewer/re_test_viewport/src/lib.rs
  crates/viewer/re_view_bar_chart/tests/bar_chart_test.rs
  crates/viewer/re_view_bar_chart/tests/snapshots/bar_chart_1d.png
  crates/viewer/re_view_bar_chart/tests/snapshots/tensor_1d.png
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_spatial/tests/bgr_images.rs
  crates/viewer/re_view_spatial/tests/blueprint_2d.rs
  crates/viewer/re_view_spatial/tests/visible_time_range.rs
  crates/viewer/re_view_tensor/tests/tensor_1d.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_view_time_series/tests/blueprint.rs
  crates/viewer/re_view_time_series/tests/snapshots/bootstrapped_secondaries_full.png
  crates/viewer/re_view_time_series/tests/snapshots/bootstrapped_secondaries_partial.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_show_second_only.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_true.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: exclude from changelog

#11383 Add `-` formatting option for redacted values
  CODE_STYLE.md
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/tests/formatting.rs
  crates/store/re_chunk/tests/snapshots/formatting__format_chunk_redacted.snap
  crates/store/re_dataframe/src/query.rs
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/utils/re_mcap/Cargo.toml
  crates/utils/re_mcap/src/layers/protobuf.rs
Labels: exclude from changelog

#11409 Move transform processing modules into new, viewer-independent `re_tf` crate
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/store/re_tf/Cargo.toml
  crates/store/re_tf/README.md
  crates/store/re_tf/src/lib.rs
  crates/store/re_tf/src/transform_cache.rs
  crates/store/re_tf/src/transform_tree.rs
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/src/contexts/mod.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/space_camera_3d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/mod.rs
Labels: 🚜 refactor, exclude from changelog

#11412 create SDK wheels for mac on push-to-main workflow
  .github/workflows/on_push_main.yml
Labels: exclude from changelog

#11403 Fix the `default_for_column` logic
  crates/viewer/re_dataframe_ui/src/filters/filter.rs
Labels: 🪳 bug, ui, exclude from changelog

#11411 End-to-end out-of-band entry headers: datasets (part 2)
  crates/store/re_protos/proto/rerun/v1alpha1/cloud.proto
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.rs
  crates/store/re_redap_client/src/connection_client.rs
  crates/store/re_redap_client/src/grpc.rs
  crates/store/re_server/src/rerun_cloud.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog, dataplatform

#11414 Use rust-lld for Windows builds
  .cargo/config.toml
  Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#11418 Reconcile historically messy RerunCloud extension types
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.ext.rs
  crates/store/re_server/src/rerun_cloud.rs
Labels: exclude from changelog, dataplatform

#11401 Add meaningful equality comparisons to many rust wrappers
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataframe_rendering.rs
  rerun_py/src/catalog/datafusion_table.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/table_entry.rs
  rerun_py/src/catalog/task.rs
  rerun_py/src/dataframe/component_columns.rs
  rerun_py/src/dataframe/index_columns.rs
  rerun_py/src/dataframe/recording.rs
  rerun_py/src/dataframe/recording_view.rs
  rerun_py/src/dataframe/rrd.rs
  rerun_py/src/dataframe/schema.rs
  rerun_py/src/python_bridge.rs
  rerun_py/src/viewer.rs
  rerun_py/tests/unit/test_datafusion_tables.py
  scripts/lint.py
Labels: sdk-python, 😤 annoying, include in changelog

#11422 Use `ChunkStoreHandle` in the OSS server instead of `EntityDb`
  Cargo.lock
  crates/store/re_server/Cargo.toml
  crates/store/re_server/src/rerun_cloud.rs
  crates/store/re_server/src/store.rs
Labels: 🚜 refactor, exclude from changelog

#11415 Store (and display) recordings in insertion order
  Cargo.lock
  crates/store/re_entity_db/Cargo.toml
  crates/store/re_entity_db/src/store_bundle.rs
Labels: enhancement, ui, include in changelog

#11425 {Cosmetic} Typo fix
  crates/viewer/re_test_viewport/src/lib.rs
Labels: exclude from changelog

#11350 Fix: enabling `auth` should not pull in all of `re_viewer`
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/auth.rs
  crates/top/rerun/src/commands/entrypoint.rs
  scripts/ci/rust_checks.py
Labels: 🧑‍💻 dev experience, dependencies, exclude from changelog, CLI

#11431 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#11433 Print out the url that 'rerun auth login' opens
  crates/utils/re_auth/src/cli.rs
Labels: exclude from changelog

#11428 Walkers updated to 0.45
  Cargo.lock
  Cargo.toml
Labels: 📺 re_viewer, dependencies, exclude from changelog

#11400 Add how to connect the server to the CLI command output
  crates/store/re_server/src/server.rs
Labels: 📖 documentation, 😤 annoying, include in changelog, CLI

#11430 add feedback link to docs
  docs/content/development/roadmap.md
  docs/content/getting-started/mcap.md
  docs/content/howto/integrations/embed-notebooks.md
  docs/content/howto/logging/send-table.md
  docs/content/reference/mcap/message-formats.md
Labels: 📖 documentation, exclude from changelog, deploy docs

#11434 Clean-up of the partition table datafusion table provider
  Cargo.lock
  crates/store/re_datafusion/Cargo.toml
  crates/store/re_datafusion/examples/catalog.rs
  crates/store/re_datafusion/src/catalog_provider.rs
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/lib.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_redap_client/src/connection_client.rs
  crates/store/re_redap_client/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#11429 feat: Add validation for `required` fields in fbs files
  crates/build/re_types_builder/src/objects.rs
  crates/store/re_types/definitions/rerun/archetypes/asset_video.fbs
  crates/store/re_types/definitions/rerun/archetypes/bar_chart.fbs
  crates/store/re_types/definitions/rerun/archetypes/pinhole.fbs
  crates/store/re_types/definitions/rerun/archetypes/video_frame_reference.fbs
  crates/store/re_types/definitions/rerun/archetypes/view_coordinates.fbs
Labels: 🧑‍💻 dev experience, codegen/idl, exclude from changelog

#11427 Transform resolution is no longer a store subscriber
  Cargo.lock
  crates/store/re_tf/src/component_type_info.rs
  crates/store/re_tf/src/lib.rs
  crates/store/re_tf/src/transform_resolution_cache.rs
  crates/store/re_tf/src/transform_tree.rs
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/src/caches/mesh_cache.rs
  crates/viewer/re_view_spatial/src/caches/mod.rs
  crates/viewer/re_view_spatial/src/caches/transform_database_store.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/mesh_loader.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/cache/caches.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/tensor_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_asset_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: 🚜 refactor, exclude from changelog

#11419 Update wgpu to 27
  Cargo.lock
  Cargo.toml
  crates/viewer/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/viewer/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/context_test.rs
  crates/viewer/re_renderer/src/device_caps.rs
  crates/viewer/re_renderer_examples/framework.rs
Labels: 🔺 re_renderer, dependencies, exclude from changelog

#11439 Determine per-view overrides in parallel (-> faster many entities + many views on native)
  Cargo.lock
  crates/viewer/re_test_viewport/src/lib.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/view/mod.rs
  crates/viewer/re_viewer_context/src/view/view_class_registry.rs
  crates/viewer/re_viewer_context/src/view/visualizer_entity_subscriber.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
Labels: 📺 re_viewer, 📉 performance, include in changelog

#11416 refactor: Move examples for notebook viewer and callbacks to `examples/python`
  examples/manifest.toml
  examples/python/notebook_callbacks/README.md
  examples/python/notebook_callbacks/notebook_callbacks.ipynb
  examples/python/notebook_callbacks/requirements.txt
  examples/python/notebook_viewer/README.md
  examples/python/notebook_viewer/notebook_viewer.ipynb
  examples/python/notebook_viewer/requirements.txt
Labels: examples, include in changelog

#11445 Improve many-entity performance by fixing redundant `AnnotationContext` lookups (also affects scene without annotation contexts)
  Cargo.lock
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_test_viewport/src/lib.rs
  crates/viewer/re_view/src/annotation_scene_context.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/contexts/depth_offsets.rs
  crates/viewer/re_view_spatial/src/contexts/mod.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/annotations.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/view/mod.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class_registry.rs
  crates/viewer/re_viewer_context/src/view/view_context_system.rs
  crates/viewer/re_viewport/src/system_execution.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 📉 performance, include in changelog

#11446 Merge `DroppableEncoder` and `Encoder` into a single facility
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_encoding/src/file_sink.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun/src/commands/mcap/mod.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun/src/commands/rrd/route.rs
Labels: sdk-rust, include in changelog, 🪵 Log & send APIs

#11452 `StreamDecoder`: lift naming confusion regarding chunks
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/stream_rrd_from_http.rs
Labels: sdk-rust, do-not-merge, 🚜 refactor, exclude from changelog, 🪵 Log & send APIs

#11455 `StreamDecoder`: fix support for out-of-order legacy store ID
  crates/store/re_log_encoding/src/codec/file/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
Labels: sdk-rust, exclude from changelog, 🪵 Log & send APIs

#11449 remove GetChunks and all its usage
  crates/store/re_datafusion/src/dataframe_query_common.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
  crates/store/re_protos/proto/rerun/v1alpha1/cloud.proto
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.rs
  crates/store/re_redap_client/src/connection_client.rs
  crates/store/re_redap_client/src/grpc.rs
  crates/store/re_redap_client/src/lib.rs
  crates/store/re_server/src/rerun_cloud.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog

#11460 Represent `std_msgs/msg/Empty` as empty list
  crates/utils/re_mcap/src/layers/ros2_reflection.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog, 🧢 MCAP

#11459 Reflection-based `protobuf` parser only returns single component
  crates/utils/re_mcap/src/layers/protobuf.rs
  crates/utils/re_mcap/src/layers/snapshots/re_mcap__layers__protobuf__test__two_simple_rows.snap
Labels: include in changelog, 🧢 MCAP

#11463 Do not include metadata when rendering table in html
  rerun_py/src/catalog/dataframe_rendering.rs
Labels: 🪳 bug, 🧑‍💻 dev experience, notebook, include in changelog
