Repository rerun-io/rerun, pull requests merged in 2025-04, with the labels that each got.

#9438 Align all RPCs with latest spec
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  crates/viewer/re_redap_browser/src/entries.rs
  scripts/ci/check_large_files.py
Labels: exclude from changelog, dataplatform

#9439 Fix 2D image split heuristic
  Cargo.lock
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/tests/snapshots/spawn_heuristics__detect_and_track_objects_like_scene_2d_view_heuristic.snap
  crates/viewer/re_view_spatial/tests/spawn_heuristics.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/spawn_heuristics.rs
  crates/viewer/re_viewport_blueprint/src/test_context_ext.rs
Labels: 🦟 regression, exclude from changelog, heuristics

#9444 Update to `arrow 54.3.1`
  Cargo.lock
  Cargo.toml
  rerun_py/Cargo.toml
Labels: 🏹 arrow, dependencies, exclude from changelog

#9448 Silence pyo3 RUSTSEC since we cannot address it right now
  deny.toml
Labels: dependencies, exclude from changelog, :ship: CI

#9450 Remove unused `serde` for `StoreInfo`
  crates/store/re_log_types/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#9443 gRPC spec update: use Schema for schema responses
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog

#9434 Partition manifests basics
  Cargo.lock
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_encoding/src/protobuf_conversions.rs
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/src/catalog/dataset.rs
Labels: exclude from changelog, dataplatform

#9451 Implement `Dataset.download_partition()` to download a partition as a `Recording`
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/errors.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9435 Infer image/video channel index from LeRobot metadata
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: 📺 re_viewer, include in changelog

#9458 Introduce `Dataset.arrow_schema()` to return the arrow schema of the underlying data
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/dataframe.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9462 Preparing for re_protos for dataset queries
  Cargo.lock
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9437 Add `TableStore` for table/dataframe entries + basic UI
  Cargo.lock
  crates/store/re_log_types/src/lib.rs
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_context_menu/src/actions/collapse_expand_all.rs
  crates/viewer/re_context_menu/src/actions/copy_entity_path.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_data_ui/src/data_source.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_data_ui/src/store_id.rs
  crates/viewer/re_selection_panel/src/item_heading_no_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/callback.rs
  crates/viewer/re_viewer/src/ui/mod.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/table/mod.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/collapsed_id.rs
  crates/viewer/re_viewer_context/src/drag_and_drop.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/global_context/item.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/storage_context.rs
  crates/viewer/re_viewer_context/src/store_context.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/table_context.rs
  crates/viewer/re_viewer_context/src/tables.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
  crates/viewer/re_viewport/src/view_highlights.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: ui, include in changelog, feat-dataframe-view

#9467 Assume `rerun.kind: data` when `rerun.kind` is missing
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/column_kind.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_sorbet/src/error.rs
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
Labels: 🪳 bug, exclude from changelog

#9468 re_uri: Use correct default port (51234, not 80)
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_blueprint_tree/tests/blueprint_tree_tests.rs
  crates/viewer/re_blueprint_tree/tests/view_structure_test.rs
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/web_tools.rs
  examples/rust/dataframe_query/src/main.rs
  rerun_py/src/catalog/catalog_client.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9447 Add `serve_grpc` API
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/top/re_sdk/Cargo.toml
  crates/top/re_sdk/src/grpc_server.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun_c/Cargo.toml
  crates/top/rerun_c/src/lib.rs
  crates/utils/re_uri/src/error.rs
  docs/content/reference/cli.md
  docs/content/reference/sdk/operating-modes.md
  lychee.toml
  rerun_cpp/CMakeLists.txt
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/error.hpp
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/recording_stream.cpp
  rerun_py/Cargo.toml
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: include in changelog, CLI, 🪵 Log & send APIs

#9471 Stand up the search APIs for the new Dataset object
  crates/store/re_datafusion/src/lib.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/catalog/mod.rs
Labels: exclude from changelog, dataplatform

#9418 Unify redap browser and recording panel
  Cargo.lock
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_context_menu/Cargo.toml
  crates/viewer/re_context_menu/src/actions/collapse_expand_all.rs
  crates/viewer/re_context_menu/src/actions/copy_entity_path.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/add_server_modal.rs
  crates/viewer/re_redap_browser/src/context.rs
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_selection_panel/src/item_heading_no_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/callback.rs
  crates/viewer/re_viewer/src/history.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/collapsed_id.rs
  crates/viewer/re_viewer_context/src/drag_and_drop.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/global_context/item.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport/src/view_highlights.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: ui, exclude from changelog

#9472 Implement `Dataset.partition_table()` to expose the partition table as a datafusion table provider
  crates/store/re_datafusion/examples/catalog.rs
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/lib.rs
  crates/store/re_datafusion/src/partition_table.rs
  rerun_py/src/catalog/dataset.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9473 Move `EntryId` to `re_log_types`
  Cargo.lock
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_log_types/src/entry_id.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/viewer/re_context_menu/Cargo.toml
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/global_context/item.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/entry.rs
Labels: 🚜 refactor, exclude from changelog

#9477 Refactor `re_uri`
  crates/utils/re_uri/src/endpoints/catalog.rs
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/endpoints/proxy.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/origin.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/utils/re_uri/src/scheme.rs
  crates/utils/re_uri/src/time_range.rs
Labels: 🚜 refactor, exclude from changelog

#9475 Impl `QueryDataset`
  crates/store/re_log_types/src/entry_id.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9481 add entity paths to Frontend definitions
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
Labels: exclude from changelog

#9478 Support `#datapath` fragment on redap URL
  Cargo.lock
  crates/utils/re_uri/Cargo.toml
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/fragment.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/utils/re_uri/src/time_range.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  scripts/lint.py
Labels: enhancement, exclude from changelog, dataplatform

#9482 Automatically add unknown catalog servers
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: exclude from changelog

#9148 Add experimental `send_recording` python api
  .gitattributes
  crates/top/re_sdk/src/recording_stream.rs
  docs/snippets/all/concepts/send_recording.py
  docs/snippets/all/concepts/send_recording.rs
  docs/snippets/snippets.toml
  examples/assets/example.rrd
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, include in changelog, 🪵 Log & send APIs, feat-dataframe-api

#9479 Implement dataframe API over `Dataset`
  Cargo.lock
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_datafusion/Cargo.toml
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_sorbet/src/column_descriptor.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/mod.rs
  rerun_py/src/dataframe.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9486 Show tables under local and use table icon
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: ui, exclude from changelog

#9484 Add context helpers for dataframes
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/table.rs
  rerun_py/src/dataframe.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9491 Add `Dataset.partition_url()` to produce urls for a given partition
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9493 Allow passing url to notebook viewer
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🐍 Python API, notebook, include in changelog

#9488 Improved table visuals
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/table_utils.rs
  crates/viewer/re_viewer/src/ui/table/mod.rs
Labels: ui, exclude from changelog

#9495 Improve `rerun.notebook.Viewer` constructor
  examples/python/notebook/cube.ipynb
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🪳 bug, notebook, include in changelog

#9494 Add a dumb cache for schemas
  Cargo.lock
  rerun_py/Cargo.toml
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#9496 Dataframe queries on dataset: silo by partition and inject partition id in the results
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🐍 Python API, exclude from changelog, feat-dataframe-api, dataplatform

#9505 Improved automatically adding unknown catalog server
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: exclude from changelog

#9509 Tweaks for displaymode/active application on incoming servers & applications
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: ui, exclude from changelog

#9508 Don't show "no recordings loaded" when there's tables or a server connected
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: exclude from changelog

#9513 fix-ci: update to tokio 1.44.2 to fix RUSTSEC-2025-0023
  Cargo.lock
  Cargo.toml
Labels: exclude from changelog

#9511 Fix opening partitions from redap origins with port 443 or 80
  crates/utils/re_uri/src/origin.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_redap_browser/src/servers.rs
Labels: 🪳 bug, exclude from changelog

#9502 Catalog API improvements and typing stubs
  crates/store/re_log_types/src/entry_id.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/catalog.py
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/mod.rs
  rerun_py/src/catalog/table.rs
  rerun_py/src/dataframe.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9510 Implement `send_table` in `re_grpc_server` and `re_viewer`
  Cargo.lock
  crates/store/re_grpc_server/Cargo.toml
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/sdk_comms.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.sdk_comms.v1alpha1.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/history.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/native.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  examples/rust/custom_callback/src/viewer.rs
  examples/rust/custom_view/src/main.rs
  examples/rust/extend_viewer_ui/src/main.rs
  examples/rust/viewer_callbacks/src/main.rs
  rerun_js/web-viewer/index.ts
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🕸️ web, 📺 re_viewer, include in changelog, feat-dataframe-api

#9518 Remove datafusion patch
  Cargo.lock
  Cargo.toml
Labels: 🏹 arrow, ⛴ release, dependencies, exclude from changelog

#9517 Update to egui_plot 0.32.1
  Cargo.lock
  Cargo.toml
Labels: ⛴ release, dependencies, exclude from changelog

#9512 Refactor: replace naked `url: String` with `re_uri` type
  Cargo.lock
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_server/Cargo.toml
  crates/store/re_grpc_server/src/lib.rs
  crates/top/re_sdk/src/grpc_server.rs
  crates/top/re_sdk/src/web_viewer.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_smart_channel/src/receive_set.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/origin.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
Labels: 🚜 refactor, exclude from changelog

#9523 Rename 'endpoint' to 'uri' where it makes sense
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/top/re_sdk/src/grpc_server.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/re_sdk/src/web_viewer.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_smart_channel/src/receive_set.rs
  crates/utils/re_uri/src/endpoints/catalog.rs
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/endpoints/proxy.rs
  crates/utils/re_uri/src/error.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/origin.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/python_bridge.rs
Labels: 🚜 refactor, exclude from changelog

#9522 Example showcasing `send_table` from notebooks
  crates/viewer/re_viewer/src/web.rs
  examples/python/notebook/send_table.ipynb
Labels: examples, notebook, include in changelog, 🪵 Log & send APIs

#9524 Fix sidebar disappearing when switching from table to welcome screen
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🪳 bug, exclude from changelog

#9507 `DisplayRecordbatch`: route `RowId` to `ComponentData::data_ui` if available
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
Labels: ui, 🚀 performance, exclude from changelog

#9519 Reordering and hiding of table columns
  Cargo.lock
  Cargo.toml
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/table_utils.rs
  crates/viewer/re_ui/data/icons/dnd_handle.png
  crates/viewer/re_ui/data/icons/settings.png
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_viewer/src/ui/table/mod.rs
Labels: ui, exclude from changelog

#9499 Merge schemas when querying across partitions
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: exclude from changelog, dataplatform

#9528 Fix python lint
  examples/python/notebook/send_table.ipynb
Labels: exclude from changelog

#9529 Make `PyDataframeQueryView` immutable
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🐍 Python API, exclude from changelog, feat-dataframe-api, dataplatform

#9515 Do not send `StoreId` in `send_recording` Rust snippet
  docs/snippets/all/concepts/send_recording.rs
  examples/assets/example.rrd
Labels: exclude from changelog, :ship: CI

#9540 Add `rr.serve_web_viewer`
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/web_viewer.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_web_viewer_server/src/lib.rs
  docs/content/concepts/app-model.md
  lychee.toml
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/script_helpers.py
  rerun_py/rerun_sdk/rerun/web.py
  rerun_py/src/python_bridge.rs
  scripts/screenshot_compare/build_screenshot_compare.py
  scripts/snapshots.py
Labels: 🐍 Python API, include in changelog

#9542 Add support for `/entry/$ENTRY_ID` URIs
  crates/store/re_data_source/src/data_source.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/endpoints/entry.rs
  crates/utils/re_uri/src/endpoints/mod.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  scripts/ci/check_large_files.py
Labels: exclude from changelog, dataplatform

#9549 Move `StartupOptions` to a separate file to reduce the size of `app.rs`
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/startup_options.rs
  scripts/ci/check_large_files.py
Labels: 🚜 refactor, exclude from changelog

#9546 Improve recording panel ui
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: ui, exclude from changelog

#9548 CMake: Use `find_dependency` for Arrow
  rerun_cpp/Config.cmake.in
Labels: 🌊 C++ API, include in changelog

#9538 Add experimental `send_table` to Python SDK
  crates/store/re_grpc_client/src/message_proxy/mod.rs
  crates/store/re_grpc_client/src/message_proxy/write_table.rs
  docs/snippets/all/howto/send_table.py
  examples/python/notebook/send_table.ipynb
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/errors.rs
  rerun_py/src/lib.rs
  rerun_py/src/python_bridge.rs
  rerun_py/src/viewer.rs
Labels: include in changelog, 🪵 Log & send APIs

#9553 Order dataset by name in the recording panel
  Cargo.lock
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/entries.rs
Labels: 🪳 bug, ui, exclude from changelog

#9557 Import `rerun.notebook` lazily
  examples/python/notebook/cube.ipynb
  pixi.lock
  pixi.toml
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
Labels: 🐍 Python API, notebook, include in changelog

#9562 Exclude `how_to/send_table` from snippets
  docs/snippets/snippets.toml
Labels: exclude from changelog, :ship: CI

#9559 Use `Hash64` instead of `RowId` as cache keys
  crates/viewer/re_component_ui/src/fallback_ui.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/mesh_loader.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/tensor_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_cache.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/image_info.rs
Labels: 🚜 refactor, exclude from changelog

#9563 Include field names in Archetype docs
  crates/build/re_types_builder/src/codegen/docs/website.rs
  crates/build/re_types_builder/src/objects.rs
  docs/content/reference/types/archetypes/annotation_context.md
  docs/content/reference/types/archetypes/arrows2d.md
  docs/content/reference/types/archetypes/arrows3d.md
  docs/content/reference/types/archetypes/asset3d.md
  docs/content/reference/types/archetypes/asset_video.md
  docs/content/reference/types/archetypes/bar_chart.md
  docs/content/reference/types/archetypes/boxes2d.md
  docs/content/reference/types/archetypes/boxes3d.md
  docs/content/reference/types/archetypes/capsules3d.md
  docs/content/reference/types/archetypes/clear.md
  docs/content/reference/types/archetypes/depth_image.md
  docs/content/reference/types/archetypes/ellipsoids3d.md
  docs/content/reference/types/archetypes/encoded_image.md
  docs/content/reference/types/archetypes/geo_line_strings.md
  docs/content/reference/types/archetypes/geo_points.md
  docs/content/reference/types/archetypes/graph_edges.md
  docs/content/reference/types/archetypes/graph_nodes.md
  docs/content/reference/types/archetypes/image.md
  docs/content/reference/types/archetypes/instance_poses3d.md
  docs/content/reference/types/archetypes/line_strips2d.md
  docs/content/reference/types/archetypes/line_strips3d.md
  docs/content/reference/types/archetypes/mesh3d.md
  docs/content/reference/types/archetypes/pinhole.md
  docs/content/reference/types/archetypes/points2d.md
  docs/content/reference/types/archetypes/points3d.md
  docs/content/reference/types/archetypes/recording_properties.md
  docs/content/reference/types/archetypes/scalar.md
  docs/content/reference/types/archetypes/scalars.md
  docs/content/reference/types/archetypes/segmentation_image.md
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/archetypes/series_lines.md
  docs/content/reference/types/archetypes/series_point.md
  docs/content/reference/types/archetypes/series_points.md
  docs/content/reference/types/archetypes/tensor.md
  docs/content/reference/types/archetypes/text_document.md
  docs/content/reference/types/archetypes/text_log.md
  docs/content/reference/types/archetypes/transform3d.md
  docs/content/reference/types/archetypes/video_frame_reference.md
  docs/content/reference/types/archetypes/view_coordinates.md
Labels: 📖 documentation, include in changelog

#9551 Revert "Add a dumb cache for schemas (#9494)"
  Cargo.lock
  rerun_py/Cargo.toml
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#9560 Fix the docstrings in `RecordingStream`
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/time.py
Labels: 🐍 Python API, exclude from changelog

#9547 Make use of the new `serve_web_viewer` function
  crates/store/re_grpc_server/src/lib.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/clap.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/origin.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_redap_browser/src/servers.rs
  docs/content/reference/sdk/operating-modes.md
  examples/rust/minimal_serve/src/main.rs
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 📖 documentation, exclude from changelog, 🪵 Log & send APIs

#9550 Set `RERUN_ARROW_LINK_SHARED_DEFAULT` based on found Arrow build
  rerun_cpp/CMakeLists.txt
Labels: 🌊 C++ API, include in changelog

#9567 Run git lfs checkout on contribuor PR
  .github/workflows/contrib_rerun_py.yml
Labels: exclude from changelog, :ship: CI

#9568 Do not run `send_recording` snippet
  docs/snippets/snippets.toml
Labels: exclude from changelog, :ship: CI

#9573 Fix notebook version not being set by update script
  scripts/ci/update_rerun_notebook_version.py
Labels: exclude from changelog, :ship: CI

#9574 Get rid of deprecated Dataset Manifest columns
  crates/store/re_protos/src/lib.rs
Labels: exclude from changelog, dataplatform

#9575 update crossbeam-channel to 0.5.15
  Cargo.lock
Labels: exclude from changelog

#9571 add another (fallible) helper for arrow downcasting
  crates/utils/re_arrow_util/src/arrays.rs
Labels: exclude from changelog

#9576 Add basic server ui
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: ui, exclude from changelog, dataplatform

#9577 Use lfs in web publish job
  .github/workflows/reusable_publish_web.yml
Labels: exclude from changelog, :ship: CI

#9580 Cloneable `AuthDecorator`
  crates/utils/re_auth/src/service/client.rs
Labels: exclude from changelog, dataplatform

#9582 Format random IDs withour dashes
  Cargo.lock
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/load_file.rs
  crates/store/re_log_types/src/lib.rs
  crates/utils/re_analytics/examples/end_to_end.rs
  crates/utils/re_analytics/src/native/config.rs
  crates/utils/re_analytics/src/web/config.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/blueprint_id.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9585 Remove debug-assert that asserted that column names have no colons
  crates/store/re_types_core/src/loggable.rs
Labels: 🧑‍💻 dev experience, examples, exclude from changelog

#9584 Update `walkers` to 0.36.0
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, feat-map-view

#9572 redap_protos: add endpoint for the tasks service to blocking-query tasks
  crates/store/re_protos/proto/rerun/v1alpha1/tasks.proto
  crates/store/re_protos/src/v1alpha1/rerun.redap_tasks.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9566 Prevent switches to welcome screen if tables are present
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: exclude from changelog

#9578 re_protos: expose Tasks endpoints via the redap_frontend
  buf.yaml
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9587 Improve view heuristics for time series plot
  crates/viewer/re_view/src/heuristics.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  scripts/generate_changelog.py
Labels: 📺 re_viewer, include in changelog

#9705 Refactor: use named bools
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/arrow.rs
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
Labels: 🚜 refactor, exclude from changelog

#9723 Refactor `re_types_builder` slightly
  crates/build/re_types_builder/src/arrow_registry.rs
  crates/build/re_types_builder/src/codegen/cpp/array_builder.rs
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/docs/website.rs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/objects.rs
  rerun_cpp/tests/generated/datatypes/affix_fuzzer3.cpp
  rerun_cpp/tests/generated/datatypes/affix_fuzzer4.cpp
Labels: 🚜 refactor, exclude from changelog

#9537 re_protos: use async registration by default (protos)
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9704 Replace uses of `arrow2` in `rerun_c` with `arrow-rs`
  Cargo.lock
  crates/top/rerun_c/Cargo.toml
  crates/top/rerun_c/src/arrow_utils.rs
  crates/top/rerun_c/src/component_type_registry.rs
  crates/top/rerun_c/src/lib.rs
  rerun_cpp/src/rerun/c/rerun.h
Labels: 🏹 arrow, 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#9724 Remove all uses of `arrow` and `arrow2` from `re_types_builder`
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/build/re_types_builder/Cargo.toml
  crates/build/re_types_builder/src/arrow_registry.rs
  crates/build/re_types_builder/src/bin/build_re_types.rs
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/docs/arrow_datatype.rs
  crates/build/re_types_builder/src/codegen/docs/datatype_docs.rs
  crates/build/re_types_builder/src/codegen/docs/mod.rs
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  crates/build/re_types_builder/src/codegen/docs/website.rs
  crates/build/re_types_builder/src/codegen/fbs/mod.rs
  crates/build/re_types_builder/src/codegen/mod.rs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/arrow.rs
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/build/re_types_builder/src/data_type.rs
  crates/build/re_types_builder/src/lib.rs
  crates/build/re_types_builder/src/objects.rs
  crates/build/re_types_builder/src/type_registry.rs
  crates/viewer/re_view_spatial/tests/draw_order.rs
Labels: 🏹 arrow, dependencies, 🚜 refactor, codegen/idl, exclude from changelog

#9586 Introduce `Navigation` in preparation for tabs and simplify welcome screen loading
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_blueprint.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/navigation.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/global_context/display_mode.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor, exclude from changelog

#9730 dataplatform tasks: rename task related methods
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/tasks.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap_tasks.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9590 rerun_py: adapt the `register` API to the new asynchronous nature of `register_with_dataset`
  Cargo.lock
  rerun_py/Cargo.toml
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9733 Move `TimeDragValue` to `re_ui`
  crates/viewer/re_chunk_store_ui/src/chunk_list_mode.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/time_drag_value.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_viewer_context/src/lib.rs
Labels: exclude from changelog

#9726 Remove last TODO:s related to Arrow2 migration
  crates/build/re_types_builder/src/codegen/rust/arrow.rs
  crates/store/re_chunk/src/range.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/tests/arrow_encode_roundtrip.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_types_core/src/arrow_buffer.rs
  crates/utils/re_arrow_util/src/arrays.rs
Labels: 🚜 refactor, exclude from changelog

#9732 Replace our `ArrowBuffer` with arrow's `ScalarBuffer`
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/arrow.rs
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/build/re_types_builder/src/objects.rs
  crates/store/re_types/definitions/rerun/datatypes/blob.fbs
  crates/store/re_types/definitions/rerun/testing/datatypes/fuzzy.fbs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/datatypes/blob.rs
  crates/store/re_types/src/datatypes/blob_ext.rs
  crates/store/re_types/src/datatypes/tensor_buffer.rs
  crates/store/re_types/src/datatypes/tensor_buffer_ext.rs
  crates/store/re_types/src/datatypes/tensor_data.rs
  crates/store/re_types/src/datatypes/tensor_data_ext.rs
  crates/store/re_types/src/image.rs
  crates/store/re_types/src/testing/components/affix_fuzzer11.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer1.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer21.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer21_ext.rs
  crates/store/re_types/src/testing/datatypes/mod.rs
  crates/store/re_types_core/src/arrow_buffer.rs
  crates/store/re_types_core/src/lib.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/image_info.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#9734 Do not hide all entities when the search is active but empty
  crates/viewer/re_blueprint_tree/src/data.rs
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/empty.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/empty.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/multiple_proj.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/multiple_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/non_root_origin.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/proj_with_placeholder.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/root_origin.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/single_proj.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/unknown_origin.png
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-/unknown_origin.snap
  crates/viewer/re_blueprint_tree/tests/view_structure_test.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_active_no_query.png
  crates/viewer/re_ui/src/filter_widget.rs
Labels: ui, include in changelog

#9735 Revert `Navigation` and `DisplayMode` changes
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_blueprint.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/navigation.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/global_context/display_mode.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: exclude from changelog

#9569 Fix `Mat3x3` shape inference in `.columns` api
  crates/build/re_types_builder/src/codegen/python/mod.rs
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/recording_properties.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/scalars.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_lines.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/series_points.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
  rerun_py/tests/unit/test_transform3d.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#9727 Use new `ListVisuals` in `PropertyContent`
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_ui/src/list_item/property_content.rs
  crates/viewer/re_ui/tests/snapshots/list_items.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_red.png
Labels: ui, exclude from changelog

#9736 When closing current recording, mark new recording as selected
  crates/viewer/re_viewer/src/app.rs
Labels: ui, exclude from changelog

#9738 Fix typo in `AddServerModal`
  crates/viewer/re_redap_browser/src/add_server_modal.rs
Labels: exclude from changelog

#9737 Introduce new `re_dataframe_ui` crate and move `DisplayRecordBatch` to it
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/README.md
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_view_dataframe/Cargo.toml
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/lib.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/ui/table/mod.rs
Labels: 🚜 refactor, exclude from changelog

#9728 Allow using table name to create a table entry datafusion table provider
  crates/store/re_datafusion/src/grpc_streaming_provider.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_log_types/src/entry_id.rs
  crates/store/re_log_types/src/lib.rs
Labels: exclude from changelog

#9742 Misc cleanup
  CMakeLists.txt
  crates/store/re_types/definitions/rerun/components/gamma_correction.fbs
  crates/store/re_types/src/components/gamma_correction.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/utils/re_log/src/setup.rs
  crates/utils/re_uri/src/origin.rs
  crates/viewer/re_renderer/README.md
  docs/content/reference/types/components/gamma_correction.md
  rerun_cpp/src/rerun/components/gamma_correction.hpp
  rerun_py/rerun_sdk/rerun/components/gamma_correction.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#9743 Move `RequestedObject` and `table_utils` to `re_dataframe_ui`
  Cargo.lock
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/src/requested_object.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_viewer/src/ui/table/mod.rs
Labels: 🚜 refactor, exclude from changelog

#9739 Unify viewer callbacks into a single `Event` interface
  .prettierrc.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/callback.rs
  crates/viewer/re_viewer/src/event.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/startup_options.rs
  crates/viewer/re_viewer/src/web.rs
  docs/content/howto/integrations/embed-notebooks.md
  docs/content/howto/integrations/embed-web.md
  examples/rust/viewer_callbacks/src/main.rs
  rerun_js/web-viewer/index.ts
  rerun_notebook/callbacks.ipynb
  rerun_notebook/package-lock.json
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/event.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 📖 documentation, 🕸️ web, notebook, include in changelog

#9746 Fix shape inference for non fixed size list array types
  crates/build/re_types_builder/src/codegen/python/mod.rs
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/recording_properties.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/scalars.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_lines.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/series_points.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
  rerun_py/tests/unit/test_arrows3d.py
Labels: 🪳 bug, exclude from changelog

#9329 Fix visibility flags for series line/point not splatting correctly
  crates/viewer/re_view_time_series/src/series_query.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_show_second_only.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_true.png
Labels: exclude from changelog, 📈 plot

#9747 Don't use deprecated `SeriesLine` archetype
  crates/viewer/re_view_time_series/tests/basic.rs
Labels: exclude from changelog

#9748 Revert making `RequestedObject` clone
  Cargo.lock
  Cargo.toml
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/src/requested_object.rs
Labels: exclude from changelog

#9753 Update fialing test
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
Labels: 🔨 testing, exclude from changelog, :ship: CI

#9757 Set wheels' min python version to 3.9
  rerun_py/Cargo.toml
Labels: 🐍 Python API, exclude from changelog

#9750 Use approximate equals when comparing floats in snippets
  CONTRIBUTING.md
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_types/src/archetypes/capsules3d.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/utils/re_arrow_util/Cargo.toml
  crates/utils/re_arrow_util/src/compare.rs
  crates/utils/re_arrow_util/src/format_data_type.rs
  crates/utils/re_arrow_util/src/lib.rs
  docs/snippets/all/archetypes/capsules3d_batch.cpp
  docs/snippets/all/archetypes/capsules3d_batch.rs
  docs/snippets/all/archetypes/instance_poses3d_combined.py
  docs/snippets/all/archetypes/mesh3d_partial_updates.py
  docs/snippets/all/archetypes/transform3d_axes.cpp
  docs/snippets/all/archetypes/transform3d_axes.py
  docs/snippets/all/archetypes/transform3d_hierarchy.py
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/capsules3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
Labels: 🔨 testing, exclude from changelog

#9760 Fix links in plots example README
  examples/python/plots/README.md
Labels: 📖 documentation, examples, exclude from changelog

#9763 Remove warning/error on loading .rrd from older Rerun version
  Cargo.lock
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_data_loader/src/loader_external.rs
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_data_source/src/load_stdin.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/examples/query.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/store/re_log_encoding/src/stream_rrd_from_http.rs
  crates/store/re_log_encoding/tests/arrow_encode_roundtrip.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/top/rerun/src/commands/stdio.rs
  crates/top/rerun/src/lib.rs
  crates/viewer/re_viewer/src/loading.rs
  crates/viewer/re_viewer_context/src/store_bundle.rs
  docs/snippets/all/concepts/send_recording.rs
  docs/snippets/all/descriptors/descr_builtin_archetype.rs
  docs/snippets/all/descriptors/descr_builtin_component.rs
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  docs/snippets/all/descriptors/descr_custom_component.rs
  docs/snippets/all/reference/dataframe_query.rs
  examples/rust/dataframe_query/src/main.rs
  rerun_py/src/dataframe.rs
Labels: exclude from changelog

#9771 Match legend colors with chart lines
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: 🪳 bug, 📺 re_viewer, include in changelog, 📈 plot

#9772 Clarify Web Viewer limitations
  README.md
  crates/top/rerun-cli/Cargo.toml
  crates/top/rerun-cli/README.md
  crates/top/rerun/Cargo.toml
  crates/top/rerun/README.md
  crates/utils/re_video/Cargo.toml
  crates/viewer/re_viewer/data/quick_start_guides/cpp_connect.md
  crates/viewer/re_viewer/data/quick_start_guides/cpp_spawn.md
  docs/content/concepts/app-model.md
  rerun_py/Cargo.toml
Labels: 📖 documentation, include in changelog

#9773 Remove `FetchPartition`
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/src/catalog/dataset.rs
Labels: exclude from changelog, dataplatform

#9777 Increase grpc server message queue size
  crates/store/re_grpc_server/src/lib.rs
Labels: exclude from changelog

#9784 Fix hovering / clicking in the text document view
  crates/viewer/re_view_text_document/src/view_class.rs
Labels: 🪳 bug, ui, include in changelog

#9785 Fix graph view heuristic always recommending no views
  crates/viewer/re_view_graph/src/view.rs
Labels: 🪳 bug, exclude from changelog, feat-graph-view

#9786 Fixed streams tree not focusing on the double-clicked item
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/tests/snapshots/focused_item_is_focused.png
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
Labels: 🪳 bug, ui, include in changelog

#9780 Centralize `RedapClient` configuration/initialization/etc
  Cargo.lock
  Cargo.toml
  crates/store/re_datafusion/Cargo.toml
  crates/store/re_datafusion/examples/catalog.rs
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/viewer/re_redap_browser/src/entries.rs
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#9792 Show image format (resolution etc) of image blobs
  crates/store/re_types/src/datatypes/image_format_ext.rs
  crates/viewer/re_component_ui/src/image_format.rs
  crates/viewer/re_data_ui/src/blob.rs
Labels: ui, 📺 re_viewer, include in changelog

#9801 C++: Emit warnings when using deprecated Rerun types
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  rerun_cpp/src/rerun/archetypes/scalar.hpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
Labels: 🌊 C++ API, include in changelog

#9805 Move migration guide to the top
  docs/content/reference/migration/migration-0-23.md
Labels: exclude from changelog, deploy docs

#9803 Enable missing-f-string-syntax in ruff (`RUF027`)
  pixi.lock
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/rerun_sdk/rerun/time.py
  scripts/ci/crates.py
  scripts/upload_rrd.py
Labels: exclude from changelog

#9802 Migration guide: Add note about notebook import
  docs/content/reference/migration/migration-0-23.md
Labels: exclude from changelog, deploy docs

#9808 Make sure Gradio is capitalized
  scripts/lint.py
Labels: 📖 documentation, exclude from changelog, :ship: CI

#9791 Fix doclinks to archetypes
  crates/store/re_types_core/src/loggable.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_viewer/src/app.rs
Labels: 📺 re_viewer, 😤 annoying, include in changelog

#9790 Add link to Gradio annotation example
  examples/manifest.toml
  examples/python/annotation_gradio/README.md
Labels: examples, include in changelog

#9804 Direct API for setting blueprint on a notebook-embedded viewer
  examples/python/notebook/set_application_blueprint.ipynb
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, notebook, include in changelog

#9762 Fix custom view example not instantiating visualizer by default
  examples/rust/custom_view/src/color_coordinates_view.rs
Labels: examples, include in changelog

#9810 Fix CI errors
  examples/python/notebook/set_application_blueprint.ipynb
  rerun_py/rerun_bindings/rerun_bindings.pyi
Labels: 🪳 bug, exclude from changelog

#9788 Refactor entity filtering in heuristics
  crates/viewer/re_view/src/heuristics.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/heuristics.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_spatial/tests/spawn_heuristics.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_text_document/src/view_class.rs
  crates/viewer/re_view_text_log/src/view_class.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/view/spawn_heuristics.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class_placeholder.rs
  crates/viewer/re_viewport_blueprint/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
Labels: 🚜 refactor, exclude from changelog, heuristics

#9817 Re-enable `pyo3.rs` link checks
  lychee.toml
Labels: exclude from changelog

#9823 Remove dead proto objects and their extensions
  Cargo.lock
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9824 Remove component name indirection from `ChunkComponents`
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/helpers.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/latest_at.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/migration.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_dataframe/src/query.rs
  crates/store/re_query/src/cache.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_view/src/lib.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/mesh_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/tensor_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_cache.rs
  crates/viewer/re_viewer_context/src/view/visualizer_entity_subscriber.rs
  docs/snippets/all/descriptors/descr_builtin_archetype.rs
  docs/snippets/all/descriptors/descr_builtin_component.rs
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  docs/snippets/all/descriptors/descr_custom_component.rs
Labels: 🚜 refactor, exclude from changelog

#9825 Improve `rerun` crate forwarding, removing need to depend on other `re_*` crates for viewer customization
  Cargo.lock
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun/src/lib.rs
  crates/viewer/re_view_graph/src/visualizers/edges.rs
  crates/viewer/re_view_graph/src/visualizers/nodes.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer_context/src/lib.rs
  examples/rust/custom_callback/Cargo.toml
  examples/rust/custom_callback/src/app.rs
  examples/rust/custom_callback/src/comms/app.rs
  examples/rust/custom_callback/src/comms/viewer.rs
  examples/rust/custom_callback/src/viewer.rs
  examples/rust/custom_view/Cargo.toml
  examples/rust/custom_view/src/color_archetype.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
  examples/rust/custom_view/src/color_coordinates_visualizer_system.rs
  examples/rust/custom_view/src/main.rs
  examples/rust/extend_viewer_ui/Cargo.toml
  examples/rust/extend_viewer_ui/src/main.rs
  examples/rust/viewer_callbacks/Cargo.toml
  examples/rust/viewer_callbacks/src/main.rs
Labels: 🦀 Rust API, include in changelog

#9830 Fix missing feature for `custom_view`
  examples/rust/custom_view/Cargo.toml
Labels: 🪳 bug, exclude from changelog

#9764 Introduce a DataFusion-backed table widget
  Cargo.lock
  Cargo.toml
  crates/store/re_datafusion/Cargo.toml
  crates/store/re_datafusion/src/lib.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_datafusion/src/wasm_compat.rs
  crates/store/re_sorbet/src/column_descriptor_ref.rs
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/src/datafusion_adapter.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/src/requested_object.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_redap_browser/src/tables_session_context.rs
  crates/viewer/re_ui/data/icons/arrow_down.png
  crates/viewer/re_ui/data/icons/arrow_up.png
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_viewer/src/ui/table/mod.rs
Labels: ui, include in changelog, dataplatform

#9844 Update mac runners to `macos-15` and use clang 18
  .github/actions/setup-rust/action.yml
  .github/workflows/cpp_matrix_full.json
  .github/workflows/nightly.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_checks_rust.yml
Labels: exclude from changelog, :ship: CI

#9831 Tensor view improvements
  crates/viewer/re_view_tensor/src/view_class.rs
  tests/python/release_checklist/check_1d_tensor_data.py
Labels: 🪳 bug, ui, include in changelog

#9828 Add `ViewerClient` to `rerun.experimental`
  docs/content/howto/logging/send-table.md
  docs/snippets/all/howto/send_table.py
  examples/python/notebook/send_table.ipynb
  rerun_notebook/package-lock.json
  rerun_py/rerun_sdk/rerun/experimental/__init__.py
Labels: 🐍 Python API, include in changelog, 🪵 Log & send APIs

#9851 Move `*Selector` from `re_chunk_store` to `re_sorbet`
  Cargo.lock
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/selectors.rs
  crates/viewer/re_view_dataframe/Cargo.toml
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/dataframe.rs
Labels: 🚜 refactor, exclude from changelog

#9842 Make store aware of full component descriptors
  Cargo.lock
  crates/store/re_chunk/examples/latest_at.rs
  crates/store/re_chunk/examples/range.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/helpers.rs
  crates/store/re_chunk/src/latest_at.rs
  crates/store/re_chunk/src/range.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/tests/latest_at.rs
  crates/store/re_chunk/tests/range.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/stats.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_chunk_store/tests/correctness.rs
  crates/store/re_chunk_store/tests/drop_time_range.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/src/query.rs
  crates/store/re_query/examples/latest_at.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/range.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/loggable.rs
  crates/viewer/re_chunk_store_ui/src/chunk_list_mode.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_time_panel/benches/bench_density_graph.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog
