Repository rerun-io/rerun, pull requests merged in 2025-08, with the labels that each got.

#10783 Support scroll-/pinch-to-zoom with first person eye control
  crates/viewer/re_view_spatial/src/eye.rs
Labels: 📺 re_viewer, include in changelog

#10793 Add some analytics events
  .typos.toml
  Cargo.lock
  crates/top/rerun/Cargo.toml
  crates/utils/re_analytics/src/event.rs
  crates/utils/re_analytics/src/lib.rs
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer/src/viewer_analytics/mod.rs
  crates/viewer/re_web_viewer_server/Cargo.toml
Labels: 📊 analytics, include in changelog

#10799 Resolve CPP Arrow Build
  rerun_cpp/download_and_build_arrow.cmake
  scripts/zombie_todos.py
Labels: 🌊 C++ API, include in changelog

#10804 Optimize memory usage in `StreamingDecoder`
  crates/store/re_log_encoding/src/decoder/streaming.rs
Labels: exclude from changelog, dataplatform

#10795 Add support for layers to the python registration APIs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog, dataplatform

#10810 Fix flaky batcher-config test
  crates/top/re_sdk/src/recording_stream.rs
Labels: 🪳 bug, 🔨 testing, exclude from changelog

#10698 DataFrame query streaming provider without memory limit
  Cargo.lock
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_datafusion/Cargo.toml
  crates/store/re_datafusion/src/dataframe_query_common.rs
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
  crates/store/re_datafusion/src/lib.rs
  crates/utils/re_perf_telemetry/src/grpc.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: exclude from changelog, feat-dataframe-api, dataplatform

#10819 Add time range query params when opening a time_range-based url
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/utils/re_uri/src/time_range.rs
Labels: 📺 re_viewer, include in changelog

#10791 Low-level Arrow conversion of `protobuf`-encoded MCAP messages
  Cargo.lock
  Cargo.toml
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/loader_mcap.rs
  crates/store/re_data_loader/src/mcap/decode.rs
  crates/store/re_data_loader/src/mcap/schema/mod.rs
  crates/store/re_data_loader/src/mcap/schema/protobuf.rs
  crates/store/re_data_loader/src/mcap/schema/sensor_msgs/point_cloud_2.rs
  crates/utils/re_mcap_ros2/src/sensor_msgs.rs
Labels: 📺 re_viewer, include in changelog, feat-mcap

#10825 Improve command palette in light mode
  crates/viewer/re_ui/src/command_palette.rs
Labels: 🪳 bug, ui, include in changelog

#10786 Show warning about running inside of Docker in top panel
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/docker_detection.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
Labels: ui, exclude from changelog

#10827 Add 0.24.1 changelog entry
  CHANGELOG.md
  scripts/generate_changelog.py
Labels: ⛴ release, exclude from changelog

#10833 Fix Mac CI By Updating Default Env
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :apple: MacOS

#10803 Fix disallowed color method declarations in `clippy.toml`
  clippy.toml
  crates/viewer/re_renderer/src/importer/gltf.rs
  crates/viewer/re_renderer_examples/2d.rs
  crates/viewer/re_renderer_examples/depth_cloud.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_renderer_examples/outlines.rs
  crates/viewer/re_renderer_examples/world_grid.rs
  scripts/clippy_wasm/clippy.toml
Labels: 🔨 testing, exclude from changelog

#10840 Don't add env variable since we don't special case osx-86
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :apple: MacOS

#10848 Set default partition size in streaming providers
  crates/store/re_datafusion/src/dataframe_query_common.rs
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
Labels: exclude from changelog, dataplatform

#10849 Fix warnings produced by Python examples
  crates/build/re_dev_tools/src/build_examples/example.rs
  crates/build/re_dev_tools/src/build_examples/rrd.rs
  crates/build/re_dev_tools/src/build_examples/snippets.rs
  examples/python/controlnet/pyproject.toml
  examples/python/depth_guided_stable_diffusion/pyproject.toml
  examples/python/detect_and_track_objects/README.md
  examples/python/detect_and_track_objects/pyproject.toml
  examples/python/segment_anything_model/pyproject.toml
  pixi.lock
  pixi.toml
  rerun_py/.non_sdk_mypy.ini
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/color_model.py
  rerun_py/rerun_sdk/rerun/datatypes/color_model_ext.py
Labels: 🐍 Python API, examples, exclude from changelog

#10850 Fix partition_id filtering for queries
  crates/store/re_datafusion/src/dataframe_query_common.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🪳 bug, exclude from changelog

#10847 Small nightly clippy fixes
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_types/src/archetypes/mesh3d_ext.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/demo_util.rs
  crates/utils/re_perf_telemetry/src/grpc.rs
  crates/utils/re_video/src/decode/gop_detection.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/viewer/re_renderer/src/allocator/uniform_buffer_fill.rs
  crates/viewer/re_renderer/src/texture_info.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_viewport/src/system_execution.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  rerun_py/src/dataframe/recording.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#10853 Add automatic undo-bug-detection code
  crates/viewer/re_viewer_context/src/undo.rs
Labels: 🔨 testing, 🧑‍💻 dev experience, 📺 re_viewer, exclude from changelog

#10858 Fix loading MCAP on wasm
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_data_loader/src/load_file.rs
Labels: 🪳 bug, 🕸️ web, exclude from changelog, feat-mcap

#10865 Fix `RUSTSEC-2025-0047` by upgrading `slab`
  Cargo.lock
Labels: exclude from changelog

#10829 Implement row filtering on client side
  crates/store/re_datafusion/src/dataframe_query_common.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: exclude from changelog, feat-dataframe-api, dataplatform

#10837 Add in-memory rerun server
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/top/rerun_server/Cargo.toml
  crates/top/rerun_server/README.md
  crates/top/rerun_server/build.rs
  crates/top/rerun_server/src/bin/main.rs
  crates/top/rerun_server/src/entrypoint.rs
  crates/top/rerun_server/src/frontend.rs
  crates/top/rerun_server/src/lib.rs
  crates/top/rerun_server/src/server.rs
  crates/top/rerun_server/src/store.rs
Labels: 🔨 testing, exclude from changelog

#10873 Add support on windows for in memory server
  crates/top/rerun_server/src/entrypoint.rs
Labels: 🪳 bug, exclude from changelog

#10883 Fix login API link
  crates/utils/re_auth/src/workos/api.rs
Labels: exclude from changelog

#10864 Check if our CLI docs match `rerun man`
  .github/workflows/reusable_checks_rust.yml
  docs/content/reference/cli.md
  scripts/ci/check_cli_docs.py
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog, CLI, :ship: CI

#10882 Improve formatting of arrow datatypes: include nullability
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__query_static_any_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/utils/re_arrow_util/src/format_data_type.rs
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_chunk_component_column.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_chunk_component_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_dataframe_component_column.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_dataframe_component_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_field_nullable.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_field_nullable_with_extras.png
Labels: 🧑‍💻 dev experience, exclude from changelog

#10863 Improve browser navigation for http & Rerun dataplatform links
  Cargo.lock
  crates/store/re_data_source/Cargo.toml
  crates/store/re_data_source/src/data_source.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/fragment.rs
  crates/viewer/re_global_context/src/command_sender.rs
  crates/viewer/re_recording_panel/src/lib.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_test_context/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/history.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/open_url.rs
  crates/viewer/re_viewer/src/startup_options.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/mod.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: 🕸️ web, include in changelog

#10890 Update to latest `pytest`
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#10845 Shrink many of our error types
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_entity_db/src/instance_path.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_types/src/path/parse_path.rs
  crates/store/re_query/src/lib.rs
  crates/store/re_sorbet/src/error.rs
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/result.rs
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_renderer/src/mesh.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  crates/viewer/re_viewer_context/src/view/mod.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  rerun_py/src/catalog/errors.rs
Labels: 📉 performance, exclude from changelog

#10904 Fix links
  lychee.toml
Labels: exclude from changelog

#10897 Fix debug-crash in undo.rs because of state restore
  Cargo.lock
  crates/store/re_sorbet/src/sorbet_schema.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/undo.rs
Labels: 🪳 bug, exclude from changelog

#10899 Better support binary arrow data in the viewer
  crates/store/re_chunk/src/iter.rs
  crates/store/re_types/src/datatypes/blob_ext.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/utils/re_byte_size/src/arrow_sizes.rs
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  rerun_py/README.md
  rerun_py/tests/unit/test_asset3d.py
Labels: exclude from changelog

#10895 Fix bug with df.count()
  clippy.toml
  crates/store/re_dataframe/src/query.rs
  crates/store/re_datafusion/src/dataframe_query_common.rs
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun_server/src/frontend.rs
  crates/utils/re_arrow_util/src/batches.rs
  crates/viewer/re_dataframe_ui/tests/column_header_tooltips.rs
  crates/viewer/re_viewer/src/web.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/catalog/mod.rs
Labels: 🪳 bug, exclude from changelog

#10920 Fixed highlighting of Python code in docs
  docs/content/concepts/spaces-and-transforms.md
  docs/content/reference/migration/migration-0-15.md
  docs/content/reference/migration/migration-0-22.md
  docs/content/reference/migration/migration-0-23.md
Labels: 📖 documentation, include in changelog, deploy docs

#10870 More aggressive linting of `...` vs `…`
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_sorbet/src/migrations/mod.rs
  crates/top/rerun/src/clap.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun_server/src/entrypoint.rs
  crates/utils/re_auth/src/cli.rs
  crates/viewer/re_web_viewer_server/src/lib.rs
  docs/snippets/all/concepts/app-model/native-async.cpp
  docs/snippets/all/concepts/app-model/native-async.py
  docs/snippets/all/concepts/app-model/native-async.rs
  docs/snippets/all/concepts/app-model/native-sync.cpp
  docs/snippets/all/concepts/app-model/native-sync.py
  docs/snippets/all/concepts/app-model/native-sync.rs
  docs/snippets/all/howto/serve_web_viewer.py
  examples/python/air_traffic_data/air_traffic_data.py
  examples/python/imu_signals/imu_signals.py
  examples/python/llm_embedding_ner/llm_embedding_ner.py
  examples/python/ocr/ocr.py
  examples/rust/custom_callback/src/comms/app.rs
  examples/rust/custom_callback/src/comms/viewer.rs
  rerun_js/web-viewer-react/README.md
  rerun_notebook/src/rerun_notebook/asset_server.py
  scripts/ci/generate_prerelease_pip_index.py
  scripts/ci/thumbnails.py
  scripts/lint.py
  scripts/zombie_todos.py
  tests/python/release_checklist/check_context_menu_multi_selection.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#10918 Updated `.rrd` compatibility note
  ARCHITECTURE.md
Labels: 📖 documentation, exclude from changelog

#10923 Update to egui 0.32.1
  Cargo.lock
  Cargo.toml
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_catalog_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_url_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_catalog_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_url_string_any_value_url_string.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/BarChart.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/TimeSeries.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/BarChart.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TimeSeries.png
Labels: 🔨 testing, 🧑‍💻 dev experience, dependencies, exclude from changelog, egui

#10926 Really fix the link checker once and for once
  lychee.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#10911 Refactor recording panel UI implementation
  Cargo.lock
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/lib.rs
  crates/store/re_entity_db/src/store_bundle.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/viewer/re_recording_panel/Cargo.toml
  crates/viewer/re_recording_panel/src/data.rs
  crates/viewer/re_recording_panel/src/lib.rs
  crates/viewer/re_recording_panel/src/recording_panel_ui.rs
  crates/viewer/re_recording_panel/tests/snapshot_tests.rs
  crates/viewer/re_recording_panel/tests/snapshots/snapshot_tests__empty_context_test.snap
  crates/viewer/re_recording_panel/tests/snapshots/snapshot_tests__fake_local_and_example_recordings_test.snap
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🚜 refactor, exclude from changelog

#10952 Ignore `target_pixi_wasm`
  .gitignore
  .prettierignore
  lychee.toml
  pixi.lock
  rerun_py/pyproject.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#10951 Tell rust-analyzer to run clippy by default
  .vscode/settings.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#10955 Fix MCAP `AnyValues` component descriptors
  crates/utils/re_mcap/src/layers/schema.rs
Labels: exclude from changelog

#10925 Switch runtime asserts to compiletime asserts
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_types/src/path/parse_path.rs
  crates/store/re_query/src/lib.rs
  crates/store/re_sorbet/src/error.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_renderer/src/mesh.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  crates/viewer/re_viewer_context/src/view/mod.rs
  rerun_py/src/catalog/errors.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#10953 Add e2e integration test using memory server
  Cargo.lock
  Cargo.toml
  crates/viewer/re_ui/src/command.rs
  pixi.toml
  tests/rust/re_integration_test/Cargo.toml
  tests/rust/re_integration_test/src/lib.rs
  tests/rust/re_integration_test/tests/re_integration.py
  tests/rust/re_integration_test/tests/re_integration.rs
  tests/rust/re_integration_test/tests/snapshots/re_integration__integration_test.snap
Labels: 🔨 testing, exclude from changelog

#10964 Fix nightly build
  .github/workflows/nightly.yml
Labels: exclude from changelog, :ship: CI

#10963 Fix closing recordings/tables that are still being loaded showing up again
  crates/viewer/re_viewer/src/app.rs
Labels: 📺 re_viewer, include in changelog

#10970 Persist fallback token
  crates/store/re_grpc_client/src/connection_registry.rs
  web_viewer/index.html
Labels: 📺 re_viewer, include in changelog

#10960 Fix new integration test on windows
  Cargo.lock
  Cargo.toml
  crates/viewer/re_viewer/tests/app_kittest.rs
  tests/rust/re_integration_test/Cargo.toml
  tests/rust/re_integration_test/src/lib.rs
  tests/rust/re_integration_test/tests/re_integration.rs
  tests/rust/re_integration_test/tests/snapshots/re_integration__integration_test.snap
Labels: exclude from changelog, :ship: CI

#10978 Fix spawn CARGO_TARGET_DIR redirect not properly working on windows
  crates/top/re_sdk/src/spawn.rs
Labels: 🪟 windows, exclude from changelog

#10961 Fix empty server UI
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
Labels: ui, exclude from changelog, feat-redap-browser

#10977 Fix SDK->Viewer connection
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
Labels: exclude from changelog

#10979 Fix windows integration tests
  crates/store/re_server/src/frontend.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/viewer_test_utils/mod.rs
  crates/viewer/re_viewer/tests/app_kittest.rs
  tests/rust/re_integration_test/src/lib.rs
  tests/rust/re_integration_test/tests/re_integration.py
  tests/rust/re_integration_test/tests/re_integration.rs
Labels: 🔨 testing, 🪟 windows, exclude from changelog

#10980 Enable OSS server feature when building wheels and release artifacts
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  crates/top/rerun-cli/Cargo.toml
  pixi.toml
Labels: ⛴ release, exclude from changelog, CLI

#10969 Fix closing SDK connections
  crates/viewer/re_viewer/src/app.rs
Labels: exclude from changelog

#10927 Open any importable link from command palette
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_ui/src/command_palette.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/history.rs
  crates/viewer/re_viewer/src/open_url.rs
  crates/viewer/re_viewer/src/web.rs
Labels: 📺 re_viewer, include in changelog

#10986 Use head sha instead of branch name for auto-approval
  scripts/ci/approve_workflow_runs.py
Labels: exclude from changelog, :ship: CI

#10928 Allow opening web viewer links directly
  Cargo.lock
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_data_source/src/lib.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/open_url.rs
Labels: 📺 re_viewer, include in changelog

#10985 Fix `ReceiveSet::recv` panicing without receivers
  crates/utils/re_smart_channel/src/receive_set.rs
Labels: 🕸️ web, 💣 crash, exclude from changelog

#10987 rerun_cpp: Fix useless semicolon warnings
  rerun_cpp/src/rerun/log_sink.hpp
Labels: 🌊 C++ API, exclude from changelog

#10857 Log all `sensor_msgs/msg/Image` metadata
  crates/utils/re_mcap/src/parsers/ros2msg/sensor_msgs/image.rs
Labels: 📺 re_viewer, include in changelog, feat-mcap

#10994 Add H.265 support for native & `VideoStream`
  .typos.toml
  Cargo.lock
  Cargo.toml
  crates/store/re_types/definitions/rerun/components/video_codec.fbs
  crates/store/re_types/src/components/video_codec.rs
  crates/utils/re_video/Cargo.toml
  crates/utils/re_video/src/decode/ffmpeg_cli/ffmpeg.rs
  crates/utils/re_video/src/decode/ffmpeg_cli/mod.rs
  crates/utils/re_video/src/decode/ffmpeg_cli/version.rs
  crates/utils/re_video/src/decode/gop_detection.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/utils/re_video/src/demux/mp4.rs
  crates/utils/re_video/src/gop_detection.rs
  crates/utils/re_video/src/h264.rs
  crates/utils/re_video/src/h265.rs
  crates/utils/re_video/src/lib.rs
  crates/utils/re_video/src/nalu.rs
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/tests/snapshots/video_asset_H265_beyond_end.png
  crates/viewer/re_view_spatial/tests/snapshots/video_asset_H265_not_on_frame_boundary.png
  crates/viewer/re_view_spatial/tests/snapshots/video_asset_H265_start.png
  crates/viewer/re_view_spatial/tests/snapshots/video_stream_H265_before_start.png
  crates/viewer/re_view_spatial/tests/snapshots/video_stream_H265_beyond_end.png
  crates/viewer/re_view_spatial/tests/snapshots/video_stream_H265_not_on_frame_boundary.png
  crates/viewer/re_view_spatial/tests/snapshots/video_stream_H265_start.png
  crates/viewer/re_view_spatial/tests/video.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  docs/content/reference/types/components/video_codec.md
  docs/content/reference/video.md
  docs/snippets/all/archetypes/video_stream_synthetic.py
  pixi.toml
  rerun_cpp/src/rerun/components/video_codec.hpp
  rerun_py/rerun_sdk/rerun/archetypes/video_stream.py
  rerun_py/rerun_sdk/rerun/components/video_codec.py
Labels: enhancement, 📺 re_viewer, include in changelog, 🎞️ video

#11002 Prevent MCAP loader trigger for non-MCAP files on web
  crates/store/re_data_loader/src/loader_mcap.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog, feat-mcap

#10876 Add CI tests for gRPC calls to OSS server
  pixi.lock
  pixi.toml
  rerun_py/tests/unit/test_datafusion_tables.py
  tests/assets/rrd/dataset/README.md
  tests/assets/rrd/dataset/file1.rrd
  tests/assets/rrd/dataset/file2.rrd
Labels: exclude from changelog, :ship: CI, dataplatform

#11006 Add test for empty batch creation related to calling count()
  rerun_py/tests/unit/test_datafusion_tables.py
Labels: 🔨 testing, exclude from changelog

#11010 [CI] Fix not caching Rust artifacts on Mac & Windows & use bigger runners
  .github/actions/setup-rust/action.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_checks_rust.yml
  crates/viewer/re_viewer/src/app.rs
Labels: exclude from changelog, :ship: CI

#11018 [CI] Use 32 core Windows for Rust tests
  .github/workflows/reusable_checks_rust.yml
  crates/viewer/re_renderer/src/renderer/mod.rs
Labels: exclude from changelog, :ship: CI

#11022 use time ceiling instead of cast in UDF
  rerun_py/rerun_sdk/rerun/utilities/datafusion/functions/url_generation.py
  rerun_py/tests/unit/test_datafusion_tables.py
  tests/assets/rrd/dataset/README.md
  tests/assets/rrd/dataset/file1.rrd
  tests/assets/rrd/dataset/file10.rrd
  tests/assets/rrd/dataset/file11.rrd
  tests/assets/rrd/dataset/file12.rrd
  tests/assets/rrd/dataset/file13.rrd
  tests/assets/rrd/dataset/file14.rrd
  tests/assets/rrd/dataset/file15.rrd
  tests/assets/rrd/dataset/file16.rrd
  tests/assets/rrd/dataset/file17.rrd
  tests/assets/rrd/dataset/file18.rrd
  tests/assets/rrd/dataset/file19.rrd
  tests/assets/rrd/dataset/file2.rrd
  tests/assets/rrd/dataset/file20.rrd
  tests/assets/rrd/dataset/file3.rrd
  tests/assets/rrd/dataset/file4.rrd
  tests/assets/rrd/dataset/file5.rrd
  tests/assets/rrd/dataset/file6.rrd
  tests/assets/rrd/dataset/file7.rrd
  tests/assets/rrd/dataset/file8.rrd
  tests/assets/rrd/dataset/file9.rrd
Labels: 🪳 bug, exclude from changelog, feat-dataframe-api

#11020 Add flag that allows cleanup of more recent Lance files in the maintenance
  crates/store/re_grpc_client/src/connection_client.rs
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog

#11025 Remove `--drop-at-latency`
  crates/top/rerun/src/commands/entrypoint.rs
  docs/content/howto/visualization/limit-ram.md
  docs/content/reference/cli.md
  docs/content/reference/migration/migration-0-25.md
Labels: include in changelog, CLI

#11026 Decouple public and private gRPC APIs
  buf.yaml
  crates/store/re_datafusion/examples/catalog.rs
  crates/store/re_datafusion/src/dataframe_query_common.rs
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_grpc_client/src/connection_client.rs
  crates/store/re_grpc_client/src/connection_registry.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/proto/rerun/v1alpha1/tasks.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap_tasks.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap_tasks.v1alpha1.rs
  crates/store/re_server/src/frontend.rs
  crates/store/re_server/src/store.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_entry_kind.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/servers.rs
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/catalog/mod.rs
  tests/rust/re_integration_test/src/test_data.rs
Labels: 🚜 refactor, exclude from changelog, dataplatform

#10996 Upgrade Ruff to 0.12.10
  docs/snippets/compare_snippet_output.py
  examples/python/all_examples/all_examples/__init__.py
  examples/python/arkit_scenes/arkit_scenes/download_dataset.py
  examples/python/ocr/ocr.py
  examples/python/raw_mesh/raw_mesh/__main__.py
  examples/python/ros_node/rerun_urdf.py
  pixi.lock
  pixi.toml
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_converters.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole_ext.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/blueprint/containers.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/tensor_dimension_index_slider_ext.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/dataframe.py
  rerun_py/rerun_sdk/rerun/datatypes/class_description_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/plane3d_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/tensor_dimension_selection_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary.py
  rerun_py/rerun_sdk/rerun/datatypes/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/error_utils.py
  rerun_py/tests/unit/test_arrows3d.py
  rerun_py/tests/unit/test_box2d.py
  rerun_py/tests/unit/test_box3d.py
  rerun_py/tests/unit/test_container_blueprint.py
  rerun_py/tests/unit/test_ellipsoids3d.py
  rerun_py/tests/unit/test_geo_line_strings.py
  rerun_py/tests/unit/test_geopoints.py
  rerun_py/tests/unit/test_instance_pose3d.py
  rerun_py/tests/unit/test_line_strips2d.py
  rerun_py/tests/unit/test_line_strips3d.py
  rerun_py/tests/unit/test_matnxn.py
  rerun_py/tests/unit/test_mesh3d.py
  rerun_py/tests/unit/test_plot_legend.py
  rerun_py/tests/unit/test_points2d.py
  rerun_py/tests/unit/test_points3d.py
  rerun_py/tests/unit/test_scalar_axis.py
  rerun_py/tests/unit/test_tensor_slice_selection.py
  rerun_py/tests/unit/test_transform3d.py
  rerun_py/tests/unit/test_view_blueprint.py
  rerun_py/tests/unit/test_view_contents.py
  rerun_py/tests/unit/test_viewport_blueprint.py
  scripts/ci/check_cli_docs.py
  scripts/ci/crates.py
  scripts/ci/render_bench.py
  scripts/ci/sync_release_assets.py
  scripts/ci/update_rerun_notebook_version.py
  scripts/ci/update_rerun_py_and_c_version.py
  scripts/lint.py
  scripts/zombie_todos.py
  tests/python/plot_dashboard_stress/main.py
  tests/python/release_checklist/check_chroma_subsampling.py
Labels: 🐍 Python API, 🧑‍💻 dev experience, include in changelog

#11031 Use `opened_store_id_or_recommended()` in MCAP loader
  crates/store/re_data_loader/src/loader_mcap.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#11043 Remove '-o' shorthand for stdout from script_add_args
  docs/content/reference/migration/migration-0-25.md
  rerun_py/rerun_sdk/rerun/script_helpers.py
Labels: 🐍 Python API, include in changelog

#11034 Use `ViewerImportUrl` for updating history, adds more unit tests
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_log_types/src/path/data_path.rs
  crates/viewer/re_global_context/src/item.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/open_url.rs
Labels: 🔨 testing, do-not-merge, 🚜 refactor, exclude from changelog

#11037 Fix 3D eye camera reset not resuming tracking scene bounding box
  crates/viewer/re_view_spatial/src/ui_3d.rs
Labels: 🪳 bug, include in changelog
