Repository rerun-io/rerun, pull requests merged in 2025-03, with the labels that each got.

#9130 Fix formatting of empty record batches
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/utils/re_tuid/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9153 Show EXIF data for JPEG/TIFF images
  Cargo.lock
  Cargo.toml
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/blob.rs
Labels: ui, 📺 re_viewer, include in changelog

#9167 Remove unneeded speculative link markers
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: exclude from changelog, :ship: CI

#9160 Fix shader compilation further in Chrome 131
  crates/viewer/re_renderer/shader/point_cloud.wgsl
Labels: 🪳 bug, 🕸️ web, 🔺 re_renderer, 💣 crash, exclude from changelog

#9168 Remove `recording` from `AppState::show`
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: exclude from changelog

#9172 Copy description of selection (entity path, store id, etc.) via `cmd/ctrl + c`
  crates/viewer/re_context_menu/src/actions/copy_entity_path.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
Labels: 📺 re_viewer, include in changelog

#9175 Migrate vscode settings to native Ruff language server
  .vscode/settings.json
Labels: 🧑‍💻 dev experience, 😤 annoying, exclude from changelog

#9128 Add `rerun rrd verify`
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/store/re_types_core/src/loggable.rs
  crates/store/re_types_core/src/reflection.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/top/rerun/src/commands/stdio.rs
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#9186 Update egui to 0.31.1
  Cargo.lock
  Cargo.toml
  crates/viewer/re_blueprint_tree/tests/range_selection_test.rs
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_0.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_1.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_2.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_3.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_4.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_5.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_6.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_7.png
Labels: 🔨 testing, dependencies, include in changelog, egui

#9179 Add `rr.IndexColumn`
  crates/store/re_log_types/src/time_point/mod.rs
  docs/content/getting-started/data-out/analyze-and-send.md
  docs/content/reference/migration/migration-0-23.md
  docs/snippets/all/archetypes/image_column_updates.py
  docs/snippets/all/archetypes/points3d_column_updates.py
  docs/snippets/all/archetypes/scalar_column_updates.py
  docs/snippets/all/archetypes/transform3d_column_updates.py
  docs/snippets/all/archetypes/video_auto_frames.py
  docs/snippets/all/howto/any_batch_value_column_updates.py
  docs/snippets/all/howto/any_values_column_updates.py
  docs/snippets/all/tutorials/data_out.py
  examples/python/air_traffic_data/air_traffic_data.py
  examples/python/drone_lidar/drone_lidar.py
  examples/python/imu_signals/README.md
  examples/python/imu_signals/imu_signals.py
  examples/python/notebook/partial_updates.ipynb
  examples/python/plots/plots.py
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/time.py
  tests/python/chunk_zoo/chunk_zoo.py
  tests/python/chunked_video/chunked_video.py
  tests/python/log_benchmark/test_log_benchmark.py
  tests/python/plot_dashboard_stress/main.py
  tests/python/release_checklist/check_drag_and_drop_selection.py
  tests/python/release_checklist/check_entity_drag_and_drop.py
  tests/python/release_checklist/check_multi_entity_drag_and_drop.py
  tests/python/release_checklist/check_video.py
Labels: 🐍 Python API, include in changelog

#9178 gRPC spec update: Fetch range of chunks
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
Labels: exclude from changelog, remote-store

#9191 Update docstrings for `TimeInt` and `TimeRangeBoundary`
  rerun_py/rerun_sdk/rerun/datatypes/time_int_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary_ext.py
Labels: 🐍 Python API, exclude from changelog

#9196 Update test and snippets using `new_recording()` to _actually_ use the stateless API
  docs/snippets/all/concepts/explicit_recording.py
  rerun_py/tests/unit/test_dataframe.py
  tests/python/gil_stress/main.py
Labels: 🐍 Python API, exclude from changelog

#9197 Remove deprecated Python APIs: `log_components`, `connect`, `connect_tcp`
  docs/content/reference/migration/migration-0-23.md
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
Labels: 🐍 Python API, include in changelog

#9203 Fix nightly build by updating pixi and constraining to `--platform` in `pixi_install_wheel.py`
  .github/workflows/auto_approve.yml
  .github/workflows/checkboxes.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/labels.yml
  .github/workflows/on_push_docs.yml
  .github/workflows/release.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_cpp.yml
  .github/workflows/reusable_checks_python.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_publish_js.yml
  .github/workflows/reusable_publish_web.yml
  .github/workflows/reusable_publish_wheels.yml
  .github/workflows/reusable_release_crates.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_sync_release_assets.yml
  .github/workflows/reusable_test_wheels.yml
  .github/workflows/reusable_track_size.yml
  pixi.lock
  pixi.toml
  scripts/check_env.py
  scripts/ci/pixi_install_wheel.py
Labels: exclude from changelog, :ship: CI

#9208 Refactor: move time/index-related code around
  crates/store/re_log_types/src/index/duration.rs
  crates/store/re_log_types/src/index/mod.rs
  crates/store/re_log_types/src/index/non_min_i64.rs
  crates/store/re_log_types/src/index/resolved_time_range.rs
  crates/store/re_log_types/src/index/time.rs
  crates/store/re_log_types/src/index/time_int.rs
  crates/store/re_log_types/src/index/time_point.rs
  crates/store/re_log_types/src/index/time_real.rs
  crates/store/re_log_types/src/index/time_type.rs
  crates/store/re_log_types/src/index/timeline.rs
  crates/store/re_log_types/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#9205 Add tests for `VisibleTimeRange` and intra-timestamp data
  crates/viewer/re_view_spatial/tests/snapshots/intra_timestamp/42:42.png
  crates/viewer/re_view_spatial/tests/snapshots/intra_timestamp/42:44.png
  crates/viewer/re_view_spatial/tests/snapshots/intra_timestamp/43:44.png
  crates/viewer/re_view_spatial/tests/snapshots/intra_timestamp/43:45.png
  crates/viewer/re_view_spatial/tests/snapshots/intra_timestamp/46:46.png
  crates/viewer/re_view_spatial/tests/snapshots/intra_timestamp/infinity:infinity.png
  crates/viewer/re_view_spatial/tests/snapshots/visible_time_range/absolute.png
  crates/viewer/re_view_spatial/tests/snapshots/visible_time_range/cursor_relative.png
  crates/viewer/re_view_spatial/tests/snapshots/visible_time_range/infinite.png
  crates/viewer/re_view_spatial/tests/snapshots/visible_time_range/latest_at.png
  crates/viewer/re_view_spatial/tests/snapshots/visible_time_range/override.png
  crates/viewer/re_view_spatial/tests/visible_time_range.rs
  tests/python/release_checklist/check_range_partial_updates.py
Labels: 🔨 testing, exclude from changelog

#9218 Add missing `rr.set_strict_mode(True)` to test which require it
  rerun_py/tests/unit/test_quaternion.py
  rerun_py/tests/unit/test_vecnd.py
Labels: 🪳 bug, 🔨 testing, exclude from changelog

#9200 New C++ API for timestamp/duration indices
  crates/top/rerun_c/src/lib.rs
  docs/content/reference/migration/migration-0-23.md
  docs/snippets/all/archetypes/image_row_updates.cpp
  docs/snippets/all/archetypes/instance_poses3d_combined.cpp
  docs/snippets/all/archetypes/mesh3d_instancing.cpp
  docs/snippets/all/archetypes/mesh3d_partial_updates.cpp
  docs/snippets/all/archetypes/points3d_column_updates.cpp
  docs/snippets/all/archetypes/points3d_partial_updates.cpp
  docs/snippets/all/archetypes/points3d_row_updates.cpp
  docs/snippets/all/archetypes/scalar_multiple_plots.cpp
  docs/snippets/all/archetypes/scalar_row_updates.cpp
  docs/snippets/all/archetypes/scalar_simple.cpp
  docs/snippets/all/archetypes/series_line_style.cpp
  docs/snippets/all/archetypes/series_point_style.cpp
  docs/snippets/all/archetypes/transform3d_axes.cpp
  docs/snippets/all/archetypes/transform3d_column_updates.cpp
  docs/snippets/all/archetypes/transform3d_hierarchy.cpp
  docs/snippets/all/archetypes/transform3d_row_updates.cpp
  docs/snippets/all/archetypes/video_auto_frames.cpp
  docs/snippets/all/concepts/different_data_per_timeline.cpp
  docs/snippets/all/concepts/indices.cpp
  docs/snippets/all/howto/any_values_row_updates.cpp
  docs/snippets/all/tutorials/timelines_example.cpp
  examples/cpp/clock/main.cpp
  examples/cpp/dna/main.cpp
  examples/cpp/external_data_loader/main.cpp
  examples/cpp/incremental_logging/main.cpp
  rerun_cpp/src/rerun/archetypes/asset_video.hpp
  rerun_cpp/src/rerun/archetypes/instance_poses3d.hpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/scalar.hpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.hpp
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/src/rerun/time_column.cpp
  rerun_cpp/src/rerun/time_column.hpp
  rerun_cpp/src/rerun/timeline.cpp
  rerun_cpp/src/rerun/timeline.hpp
  rerun_cpp/tests/recording_stream.cpp
  tests/cpp/log_benchmark/points3d_many_individual.cpp
  tests/cpp/plot_dashboard_stress/main.cpp
Labels: 🌊 C++ API, include in changelog

#9174 Editable time control & time context menus
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/index/time.rs
  crates/store/re_log_types/src/index/time_point.rs
  crates/store/re_log_types/src/index/time_type.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_9223372036854775807.png
  pixi.lock
Labels: 📺 re_viewer, include in changelog

#9222 Fix warnings in `use` in test
  crates/viewer/re_view_spatial/tests/visible_time_range.rs
Labels: exclude from changelog

#9219 Remove deprecated Rust `connect` APIs
  crates/top/re_sdk/src/recording_stream.rs
  docs/content/reference/migration/migration-0-23.md
Labels: 🦀 Rust API, include in changelog

#9227 Do not try to format everything on a clean clone
  docs/snippets/src/snippets/mod.rs
  pixi.toml
Labels: 🪳 bug, 😤 annoying, exclude from changelog, :ship: CI

#9229 Update `ring`
  Cargo.lock
Labels: dependencies, exclude from changelog

#9225 Update torch to 2.6
  examples/python/controlnet/pyproject.toml
  examples/python/depth_guided_stable_diffusion/pyproject.toml
  examples/python/detect_and_track_objects/pyproject.toml
  examples/python/segment_anything_model/pyproject.toml
  pixi.lock
  pixi.toml
Labels: dependencies, exclude from changelog

#9226 Introduce `IndexCell`
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/latest_at.rs
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_log_types/src/index/index_cell.rs
  crates/store/re_log_types/src/index/mod.rs
  crates/store/re_log_types/src/index/non_min_i64.rs
  crates/store/re_log_types/src/index/resolved_time_range.rs
  crates/store/re_log_types/src/index/time_int.rs
  crates/store/re_log_types/src/index/time_point.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_query/tests/latest_at.rs
  crates/store/re_query/tests/range.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_view_text_log/src/view_class.rs
  examples/rust/external_data_loader/src/main.rs
  examples/rust/objectron/src/main.rs
  tests/rust/test_data_density_graph/src/main.rs
Labels: 🦀 Rust API, include in changelog

#9237 rs-checks: print list of failed jobs at the end
  scripts/ci/rust_checks.py
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#9230 Improve documentation around new URI scheme
  crates/utils/re_uri/src/lib.rs
  docs/content/reference/migration/migration-0-23.md
  lychee.toml
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
Labels: exclude from changelog

#9214 Run `mypy` on the contents of `scripts/`
  .mypy.ini
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
  scripts/ci/__init__.py
  scripts/ci/approve_workflow_runs.py
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/bundle_and_upload_rerun_cpp.py
  scripts/ci/compare_path_digest.py
  scripts/ci/crates.py
  scripts/ci/mdlint.py
  scripts/ci/python_check_signatures.py
  scripts/ci/render_bench.py
  scripts/ci/rust_checks.py
  scripts/ci/setup_software_rasterizer.py
  scripts/ci/update_rerun_notebook_version.py
  scripts/fetch_crashes.py
  scripts/generate_changelog.py
  scripts/highlight_issues.py
  scripts/lint.py
  scripts/run_all.py
  scripts/screenshot_compare/build_screenshot_compare.py
  scripts/snapshots.py
  scripts/zombie_todos.py
Labels: 🧑‍💻 dev experience, include in changelog

#9206 Deprecate `rr.new_recording()` in favour of `rr.RecordingStream()` and improve type checking of the Rust bindings
  docs/content/reference/migration/migration-0-23.md
  docs/snippets/all/concepts/explicit_recording.py
  examples/python/notebook/README.md
  pixi.lock
  rerun_py/docs/gen_common_index.py
  rerun_py/pyproject.toml
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_bindings/types.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/legacy_notebook.py
  rerun_py/rerun_sdk/rerun/memory.py
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/time.py
  rerun_py/src/dataframe.rs
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_dataframe.py
  scripts/snapshots.py
  tests/python/gil_stress/main.py
Labels: 🐍 Python API, include in changelog

#9247 Stop inspecting `is_official_example` in `StoreInfo`
  crates/store/re_data_loader/src/load_file.rs
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_entity_db/src/store_bundle.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/log_msg.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/protobuf_conversions/log_types.rs
  crates/store/re_protos/src/v1alpha1/rerun.log_msg.v1alpha1.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun_c/src/lib.rs
  crates/utils/re_analytics/src/event.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog

#9233 Check dataset version when loading LeRobot dataset
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: 📺 re_viewer, include in changelog

#9241 Refactor time code, and change formatting of time ranges in URIs
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/subscribers.rs
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/index/duration.rs
  crates/store/re_log_types/src/index/index_cell.rs
  crates/store/re_log_types/src/index/mod.rs
  crates/store/re_log_types/src/index/non_min_i64.rs
  crates/store/re_log_types/src/index/time.rs
  crates/store/re_log_types/src/index/time_int.rs
  crates/store/re_log_types/src/index/time_type.rs
  crates/store/re_log_types/src/index/timeline.rs
  crates/store/re_log_types/src/index/timestamp.rs
  crates/store/re_log_types/src/index/timestamp_format.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_types/src/archetypes/asset_video.rs
  crates/store/re_types/src/archetypes/points3d.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/utils/re_uri/src/error.rs
  crates/utils/re_uri/src/lib.rs
  crates/viewer/re_chunk_store_ui/src/chunk_list_mode.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_time_panel/src/paint_ticks.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_view_spatial/tests/visible_time_range.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewer_context/src/global_context/app_options.rs
  crates/viewer/re_viewer_context/src/time_drag_value.rs
  docs/snippets/all/archetypes/points3d_column_updates.rs
  docs/snippets/all/archetypes/video_auto_frames.rs
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 🦀 Rust API, exclude from changelog, remote-store

#9252 Remove `remote` feature from `pypi` definitions
  rerun_py/Cargo.toml
  rerun_py/src/dataframe.rs
  rerun_py/src/lib.rs
  rerun_py/src/python_bridge.rs
Labels: exclude from changelog

#9253 Upgrade `env_logger` to replace `humantime` with `jiff`
  Cargo.lock
  Cargo.toml
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/log_integration.rs
  crates/utils/re_log/Cargo.toml
  deny.toml
Labels: exclude from changelog

#9256 Remove `remote` feature remnants
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks.yml
  docs/snippets/all/concepts/viscomp-component-default.py
  rerun_py/Cargo.toml
  scripts/ci/build_and_upload_wheels.py
Labels: exclude from changelog

#9210 Infer partition size for FixedSizeList-backed components
  crates/build/re_types_builder/src/codegen/python/mod.rs
  docs/content/howto/logging/send-columns.md
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/arrows3d_column_updates.cpp
  docs/snippets/all/archetypes/arrows3d_column_updates.py
  docs/snippets/all/archetypes/arrows3d_column_updates.rs
  docs/snippets/all/archetypes/arrows3d_row_updates.cpp
  docs/snippets/all/archetypes/arrows3d_row_updates.py
  docs/snippets/all/archetypes/arrows3d_row_updates.rs
  docs/snippets/snippets.toml
  lychee.toml
  rerun_py/rerun_sdk/rerun/_validators.py
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
  rerun_py/tests/unit/test_validators.py
Labels: 🐍 Python API, include in changelog, 🪵 Log & send APIs

#9242 Add Mast3r_slam Example
  examples/manifest.toml
  examples/python/mast3r_slam/README.md
Labels: examples, include in changelog

#9261 Install nextest in contrib CI
  .github/workflows/contrib_checks.yml
Labels: exclude from changelog, :ship: CI

#9234 Batch registration of recordings
  Cargo.lock
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_protos/proto/rerun/v1alpha1/remote_store.proto
  crates/store/re_protos/src/v1alpha1/rerun.remote_store.v1alpha1.rs
  crates/utils/re_arrow_util/Cargo.toml
  crates/utils/re_arrow_util/src/arrays.rs
  crates/utils/re_arrow_util/src/batches.rs
  crates/utils/re_arrow_util/src/lib.rs
  rerun_py/src/remote.rs
Labels: 🏹 arrow, exclude from changelog, dataplatform

#9262 Fix `columns` for columns of multiple batch-length==1 fixed size arrays
  crates/build/re_types_builder/src/codegen/python/mod.rs
  docs/snippets/all/archetypes/arrows3d_column_updates.cpp
  docs/snippets/all/archetypes/arrows3d_column_updates.py
  docs/snippets/all/archetypes/arrows3d_column_updates.rs
  docs/snippets/all/archetypes/arrows3d_row_updates.cpp
  docs/snippets/all/archetypes/arrows3d_row_updates.py
  docs/snippets/all/archetypes/arrows3d_row_updates.rs
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
Labels: 🐍 Python API, 🦟 regression, exclude from changelog

#9264 Remove unnecessary `re_types` dev dependency in `re_entity_db`
  Cargo.lock
  crates/store/re_entity_db/Cargo.toml
  crates/store/re_entity_db/tests/clear.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9147 Add selection change and time(line) change callbacks to Jupyter Notebook and JS APIs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer_context/src/callback.rs
  crates/viewer/re_viewer_context/src/global_context/item.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  pixi.lock
  rerun_js/web-viewer/index.ts
  rerun_notebook/callbacks.ipynb
  rerun_notebook/example.ipynb
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_notebook/src/rerun_notebook/asset_server.py
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🕸️ web, notebook, include in changelog

#9268 Streamline the help view shortcuts with the shortcuts in the menu
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/tests/snapshots/help_view_timeline_mac.png
  crates/viewer/re_time_panel/tests/snapshots/help_view_timeline_windows.png
  crates/viewer/re_ui/data/icons/command.png
  crates/viewer/re_ui/data/icons/control.png
  crates/viewer/re_ui/data/icons/option.png
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/help.rs
  crates/viewer/re_ui/src/icon_text.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/tests/help_ui_test.rs
  crates/viewer/re_ui/tests/snapshots/help_Mac.png
  crates/viewer/re_ui/tests/snapshots/help_Windows.png
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_bar_chart/tests/snapshots/help_view_bar_chart_view_mac.png
  crates/viewer/re_view_bar_chart/tests/snapshots/help_view_bar_chart_view_windows.png
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_dataframe/tests/snapshots/help_view_dataframe_view_mac.png
  crates/viewer/re_view_dataframe/tests/snapshots/help_view_dataframe_view_windows.png
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_graph/tests/snapshots/help_view_graph_view_mac.png
  crates/viewer/re_view_graph/tests/snapshots/help_view_graph_view_windows.png
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_map/tests/snapshots/help_view_map_view_mac.png
  crates/viewer/re_view_map/tests/snapshots/help_view_map_view_windows.png
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_spatial/tests/snapshots/help_view_2d_view_mac.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_2d_view_windows.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_3d_view_mac.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_3d_view_windows.png
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_tensor/tests/snapshots/help_view_tensor_view_mac.png
  crates/viewer/re_view_tensor/tests/snapshots/help_view_tensor_view_windows.png
  crates/viewer/re_view_text_document/src/view_class.rs
  crates/viewer/re_view_text_document/tests/snapshots/help_view_text_document_view_mac.png
  crates/viewer/re_view_text_document/tests/snapshots/help_view_text_document_view_windows.png
  crates/viewer/re_view_text_log/src/view_class.rs
  crates/viewer/re_view_text_log/tests/snapshots/help_view_text_log_view_mac.png
  crates/viewer/re_view_text_log/tests/snapshots/help_view_text_log_view_windows.png
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_view_time_series/tests/snapshots/help_view_time_series_view_mac.png
  crates/viewer/re_view_time_series/tests/snapshots/help_view_time_series_view_windows.png
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class_placeholder.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
Labels: enhancement, ui, include in changelog

#9282 Upload snapshot test results as artifact
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks_rust.yml
  scripts/ci/rust_checks.py
Labels: 🔨 testing, exclude from changelog, :ship: CI

#9273 gRPC spec update: introduce Manifest registry service
  crates/store/re_protos/.gitattributes
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, remote-store

#9286 Manifest registry service spec update: make few more calls stream back the response
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, remote-store

#9275 Do not assert on `Container` type in `compare_snippet_output`
  crates/build/re_dev_tools/src/build_examples/snippets.rs
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  docs/snippets/compare_snippet_output.py
  docs/snippets/snippets.toml
  taplo.toml
Labels: 🦟 regression, exclude from changelog, :ship: CI

#9289 Improved `re_format_arrow`: column metadata toggle
  crates/store/re_format_arrow/src/lib.rs
Labels: enhancement, 🏹 arrow, exclude from changelog, dataplatform

#9269 Correct truncation of AnyValues when using strings or bytes
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/tests/unit/test_any_values.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#9290 Default to DEBUG log level in debug builds (again)
  crates/utils/re_log/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9294 Change from `doi.org` to `dl.acm.org` for the ARFlow paper in our docs
  .github/workflows/reusable_checks.yml
  examples/python/arflow/README.md
  lychee.toml
Labels: exclude from changelog

#9305 Disable run notebook job
  .github/workflows/nightly.yml
  .github/workflows/reusable_run_notebook.yml
Labels: exclude from changelog, :ship: CI

#9292 Split `TimeType::Time`; changing dataloader API
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/tests/correctness.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/store/re_log_types/src/index/time.rs
  crates/store/re_log_types/src/index/time_cell.rs
  crates/store/re_log_types/src/index/time_type.rs
  crates/store/re_log_types/src/index/timeline.rs
  crates/top/rerun_c/src/lib.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_time_panel/src/paint_ticks.rs
  crates/viewer/re_time_panel/src/time_axis.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/src/time_selection_ui.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  crates/viewer/re_viewer_context/src/time_drag_value.rs
  docs/content/reference/data-loaders/overview.md
  docs/content/reference/migration/migration-0-23.md
  examples/cpp/external_data_loader/main.cpp
  examples/python/external_data_loader/rerun-loader-python-file.py
  examples/rust/external_data_loader/src/main.rs
  rerun_py/rerun_sdk/rerun/_send_columns.py
Labels: include in changelog, 🔩 data model

#9259 feat: update arrow to 54
  Cargo.lock
  Cargo.toml
  deny.toml
  examples/rust/dataframe_query/Cargo.toml
  examples/rust/dna/Cargo.toml
  examples/rust/graph_lattice/Cargo.toml
  rerun_py/src/dataframe.rs
  rerun_py/src/python_bridge.rs
Labels: 🏹 arrow, dependencies, include in changelog

#9311 Revert adding timezone to timestamp datatype
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/store/re_log_types/src/index/time_type.rs
  rerun_py/rerun_sdk/rerun/_send_columns.py
Labels: exclude from changelog

#9309 manifest registry service - small fixes
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog

#9308 Speed up 2d spawn heuristic for many entities & fix heuristic creating overlapping views for `EncodedImage`
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
Labels: 🪳 bug, 📺 re_viewer, 🚀 performance, include in changelog

#9299 Initial gRPC protos for the new catalog API: dataset CRUD
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9315 Prevent automatic opening of views for archetypes in `RecordingProperties`
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_view/src/heuristics.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/heuristics.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_text_document/src/view_class.rs
  crates/viewer/re_view_text_log/src/view_class.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class_placeholder.rs
  crates/viewer/re_viewport_blueprint/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/dataframe.rs
  rerun_py/src/remote.rs
  rerun_py/tests/unit/test_dataframe.py
Labels: ui, include in changelog, 🔩 data model, feat-dataframe-api

#9326 Snippet index links should be correct by design
  lychee.toml
Labels: exclude from changelog, :ship: CI

#9297 Fix the string representation of archetypes
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/tests/unit/test_archetype_str.py
Labels: 🐍 Python API, 🦟 regression, include in changelog

#9328 adding constants for the dataset manifest field names
  crates/store/re_protos/src/lib.rs
Labels: exclude from changelog

#9312 Callbacks: Update APIs, improve docs
  Cargo.lock
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/callback.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer_context/src/callback.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  docs/content/howto/callbacks.md
  docs/content/howto/integrations/embed-notebooks.md
  docs/content/howto/integrations/embed-web.md
  rerun_js/web-viewer/README.md
  rerun_js/web-viewer/index.ts
  rerun_notebook/callbacks.ipynb
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 📖 documentation, 🕸️ web, notebook, include in changelog

#9293 Remove `re_log_types::Time`
  Cargo.lock
  crates/store/re_chunk_store/tests/correctness.rs
  crates/store/re_chunk_store/tests/formatting.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/index/duration.rs
  crates/store/re_log_types/src/index/mod.rs
  crates/store/re_log_types/src/index/time.rs
  crates/store/re_log_types/src/index/time_cell.rs
  crates/store/re_log_types/src/index/time_int.rs
  crates/store/re_log_types/src/index/time_real.rs
  crates/store/re_log_types/src/index/time_type.rs
  crates/store/re_log_types/src/index/timestamp.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/protobuf_conversions/log_types.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/timestamp_ext.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_time_panel/src/paint_ticks.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
  crates/viewer/re_viewer_context/src/test_context.rs
  rerun_py/src/dataframe.rs
Labels: 🦀 Rust API, exclude from changelog

#9335 Fix rust analyzer in VSCode not running properly on test files
  .vscode/settings.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#9323 Use `RecordingEndpoint` in `SmartMessageSource::RedapGrpcStream`
  Cargo.lock
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_types/src/index/resolved_time_range.rs
  crates/utils/re_smart_channel/Cargo.toml
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_smart_channel/src/receive_set.rs
  crates/utils/re_uri/src/endpoints/catalog.rs
  crates/utils/re_uri/src/endpoints/proxy.rs
  crates/utils/re_uri/src/endpoints/recording.rs
  crates/utils/re_uri/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: enhancement, exclude from changelog

#9321 Fix `to_nanos` incorrectly handling `np.timedelta`
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/time.py
  rerun_py/tests/unit/test_time.py
  rerun_py/tests/unit/test_time_column.py
Labels: 🪳 bug, 🐍 Python API, exclude from changelog

#9341 Fix various typos
  .typos.toml
  crates/build/re_types_builder/src/codegen/rust/util.rs
  crates/utils/re_int_histogram/benches/int_histogram_benchmark.rs
  crates/utils/re_int_histogram/tests/memory_test.rs
  crates/viewer/re_view_time_series/tests/basic.rs
Labels: exclude from changelog, :ship: CI

#9327 Enable scalar arrays per time point for scatter plots
  crates/viewer/re_view/src/lib.rs
  crates/viewer/re_view_time_series/Cargo.toml
  crates/viewer/re_view_time_series/src/lib.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: 📺 re_viewer, include in changelog, 📈 plot

#9333 Double clicking plots focuses them now in other panels
  crates/viewer/re_view_time_series/src/view_class.rs
Labels: 📺 re_viewer, include in changelog, 📈 plot

#9319 Add IMU example to manifest
  examples/python/imu_signals/.gitignore
  examples/python/imu_signals/README.md
  examples/python/imu_signals/imu_signals.py
  examples/python/imu_signals/pyproject.toml
  pixi.lock
  pixi.toml
Labels: examples, exclude from changelog

#9347 Fix some `set_time` calls in markdown/docs/readmes
  design/blueprint_store.md
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/rust.md
  docs/content/howto/integrations/ros2-nav-turtlebot.md
  examples/cpp/stereo_vision_slam/README.md
Labels: 📖 documentation, exclude from changelog

#9316 Provide APIs to log arbitrary data to recording properties
  .gitignore
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_log_types/src/path/entity_path.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/store/re_log_types/src/path/entity_path_part.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_data_ui/src/data_source.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  docs/snippets/CMakeLists.txt
  docs/snippets/INDEX.md
  docs/snippets/all/concepts/recording_properties.cpp
  docs/snippets/all/concepts/recording_properties.py
  docs/snippets/all/concepts/recording_properties.rs
  rerun_cpp/src/rerun/recording_stream.cpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/header_checks.cpp
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_properties.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_dataframe.py
Labels: include in changelog, 🔩 data model, 🪵 Log & send APIs

#9150 Switch from `cargo-machete` to `cargo-shear`
  .github/workflows/cargo_shear.yml
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_entity_db/Cargo.toml
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_types/Cargo.toml
  crates/store/re_protos/Cargo.toml
  crates/store/re_types/Cargo.toml
  crates/store/re_types_core/Cargo.toml
  crates/top/re_sdk/Cargo.toml
  crates/top/rerun/Cargo.toml
  crates/utils/re_log/Cargo.toml
  crates/utils/re_tracing/Cargo.toml
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer_context/Cargo.toml
  docs/snippets/Cargo.toml
Labels: exclude from changelog, :ship: CI

#9357 Fix `duration` conversion in `send_columns`
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/tests/unit/test_time_column.py
Labels: exclude from changelog

#9361 Fix typo in `recording_properties` snippet
  docs/snippets/all/concepts/recording_properties.cpp
Labels: exclude from changelog

#9358 fix: re_uri expects Timeline to be serializable
  crates/utils/re_uri/Cargo.toml
Labels: exclude from changelog

#9354 Fix outdated usage of `rerun::show` in rust getting started guide
  docs/content/getting-started/data-in/rust.md
Labels: 📖 documentation, exclude from changelog, deploy docs

#9365 introduce the `Frontend` service
  buf.yaml
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9346 Add Rust Viewer Callbacks example
  Cargo.lock
  crates/viewer/re_viewer/src/callback.rs
  crates/viewer/re_viewer/src/web.rs
  examples/manifest.toml
  examples/rust/viewer_callbacks/Cargo.toml
  examples/rust/viewer_callbacks/README.md
  examples/rust/viewer_callbacks/src/main.rs
Labels: 🦀 Rust API, examples, include in changelog

#9359 redap_jobs: introduce grpc definitions
  crates/store/re_protos/proto/rerun/v1alpha1/tasks.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap_tasks.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9370 Ensure we migrate deprecated types on ingestion
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/store/re_types_core/src/reflection.rs
  crates/top/rerun/src/commands/rrd/verify.rs
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#9307 Prevent modals from shrinking / moving around when the content changes
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_ui/src/modal.rs
Labels: ui, exclude from changelog

#9372 `IfDuplicateBehavior` belongs in `common`
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#9301 Initial python wrapper for the new catalog API
  Cargo.lock
  rerun_py/Cargo.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/catalog.py
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/catalog/mod.rs
  rerun_py/src/dataframe.rs
  rerun_py/src/lib.rs
  rerun_py/src/python_bridge.rs
  rerun_py/src/remote.rs
  rerun_py/src/utils.rs
Labels: 🐍 Python API, include in changelog, dataplatform

#9364 Change `DeleteDatasetEntry` to `DeleteEntry` in both the protos and the Python SDK
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/entry.rs
Labels: 🐍 Python API, exclude from changelog, remote-store

#9374 Remove `protobuf_conversions` in favor of `rerun_common_v1alpha1_ext`
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/protobuf_conversions/arrow.rs
  crates/store/re_protos/src/protobuf_conversions/mod.rs
  crates/store/re_protos/src/protobuf_conversions/tuid.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
Labels: 🚜 refactor, exclude from changelog, dataplatform

#9376 fetch chunk manifest for a Dataset
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, remote-store

#9352 Make `BinaryStream::read` produce full RRD files
  crates/top/re_sdk/src/binary_stream_sink.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  rerun_py/src/python_bridge.rs
Labels: 🦀 Rust API, include in changelog

#9356 Explicit control over sending properties
  crates/top/re_sdk/src/recording_stream.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
Labels: exclude from changelog

#9378 Rename `EntryType` to `EntryKind`
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/mod.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9366 Hide excluding `EntityPath::properties` in `ViewContents` UI
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: exclude from changelog

#9386 gRPC spec update: expose ``FetchPartition`` on the frontend
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
Labels: exclude from changelog

#9383 Proto extension industrialization template/demo
  Cargo.lock
  crates/store/re_protos/.gitattributes
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  rerun_py/Cargo.toml
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/catalog/mod.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog, dataplatform

#9392 Ensure that `component_list_ui` uses unique id for its `list_item_scope`
  crates/viewer/re_data_ui/src/instance_path.rs
Labels: 🪳 bug, ui, exclude from changelog

#9395 Misc improvements to codegen and testing
  CMakeLists.txt
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/build/re_types_builder/src/docs.rs
  crates/build/re_types_builder/src/objects.rs
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/viewer/re_renderer_examples/framework.rs
  docs/snippets/compare_snippet_output.py
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#9396 Update some 'from_parent=' to 'relation='
  examples/python/nuscenes_dataset/README.md
  examples/python/nuscenes_dataset/nuscenes_dataset/__main__.py
Labels: examples, exclude from changelog

#9381 Implement basic UI to display recording properties
  Cargo.lock
  crates/viewer/re_component_ui/src/datatype_uis/mod.rs
  crates/viewer/re_component_ui/src/datatype_uis/view_timestamp.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/Timestamp_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/Timestamp_placeholder.png
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_selection_panel/Cargo.toml
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: ui, include in changelog

#9397 Improve snippet index
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  docs/snippets/INDEX.md
Labels: 📖 documentation, exclude from changelog

#9387 Update `__` as reserved entity path in docs
  docs/content/concepts/entity-path.md
  docs/content/reference/migration/migration-0-23.md
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/error_utils.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
Labels: 📖 documentation, include in changelog

#9401 Add missing `Debug`/`Clone` derive in protobuf helper objects
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
Labels: exclude from changelog, dataplatform

#9403 Creating a dataset should not require a full `EntryDetails`
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#9399 Increase transform_clamping test threshold
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
Labels: exclude from changelog, :ship: CI

#9407 Move `store_bundle` to `re_viewer_context`
  Cargo.lock
  crates/store/re_entity_db/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/loading.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/store_bundle.rs
  crates/viewer/re_viewer_context/src/store_context.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: exclude from changelog

#9408 Do not include RRD header when binary stream storage is empty
  crates/top/re_sdk/src/binary_stream_sink.rs
Labels: 🪳 bug, exclude from changelog

#9409 Don't trigger callbacks on welcome screen
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🪳 bug, exclude from changelog

#9410 Fix warning: we know the type of log_time and log_tick
  crates/store/re_entity_db/src/entity_db.rs
Labels: 📺 re_viewer, exclude from changelog

#9402 Use multi-dimensional scalar values when loading LeRobot dataset
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: 📺 re_viewer, include in changelog

#9412 Use the `FrontendClient` instead of the `CatalogClient`
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/viewer/re_redap_browser/src/collections.rs
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#9413 Update redap browser to use the new catalog API
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/viewer/re_redap_browser/src/collections.rs
  crates/viewer/re_redap_browser/src/context.rs
  crates/viewer/re_redap_browser/src/dataset_ui.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app.rs
Labels: exclude from changelog, dataplatform, feat-redap-browser

#9415 Fix optional notebook package import
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🪳 bug, 🐍 Python API, notebook, exclude from changelog

#9414 Fix Bazel build: shader reloading only on in Rerun workspace
  crates/viewer/re_renderer/README.md
  crates/viewer/re_renderer/build.rs
Labels: 🔺 re_renderer, 🧑‍💻 dev experience, include in changelog

#9425 Mention lack of alpha-transparency as a shortcoming
  README.md
Labels: 📖 documentation, exclude from changelog

#9426 Update array-init-cursor to 0.2.1
  Cargo.lock
Labels: dependencies, exclude from changelog

#9429 Fix `pixi run rerun-web`
  crates/viewer/re_renderer/build.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9421 Revert reserved namespace warning from instance path
  crates/viewer/re_data_ui/src/instance_path.rs
Labels: exclude from changelog

#9400 Add `detach_process` option to `spawn`
  crates/top/re_sdk/src/spawn.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun_c/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  docs/content/reference/cli.md
  rerun_cpp/src/rerun/c/rerun.h
  rerun_cpp/src/rerun/spawn_options.cpp
  rerun_cpp/src/rerun/spawn_options.hpp
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/_spawn.py
  rerun_py/rerun_sdk/rerun/blueprint/api.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, 🦀 Rust API, 🌊 C++ API, include in changelog

#9239 Consistent constructor naming of `Asset3D` across C++ and Rust
  crates/store/re_types/src/archetypes/asset3d.rs
  crates/store/re_types/src/archetypes/asset3d_ext.rs
  crates/viewer/re_view_spatial/tests/transform_hierarchy.rs
  docs/content/reference/migration/migration-0-23.md
  docs/snippets/all/archetypes/asset3d_simple.cpp
  docs/snippets/all/archetypes/asset3d_simple.rs
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d_ext.cpp
Labels: 🦀 Rust API, 🌊 C++ API, include in changelog

#9436 Rename `Scalars::one` to `Scalars::single`
  crates/store/re_types/src/archetypes/scalar.rs
  crates/store/re_types/src/archetypes/scalars.rs
  crates/store/re_types/src/archetypes/scalars_ext.rs
  crates/store/re_types/src/archetypes/series_line.rs
  crates/store/re_types/src/archetypes/series_lines.rs
  crates/store/re_types/src/archetypes/series_point.rs
  crates/store/re_types/src/archetypes/series_points.rs
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  docs/snippets/all/archetypes/scalars_multiple_plots.rs
  docs/snippets/all/archetypes/scalars_row_updates.rs
  docs/snippets/all/archetypes/scalars_simple.rs
  docs/snippets/all/archetypes/series_lines_style.rs
  docs/snippets/all/archetypes/series_points_style.rs
  tests/rust/plot_dashboard_stress/src/main.rs
Labels: 🚜 refactor, exclude from changelog

#9422 Introduce URI scheme for dataset and add support for opening remote recordings using the new API
  Cargo.lock
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_smart_channel/src/receive_set.rs
  crates/utils/re_uri/Cargo.toml
  crates/utils/re_uri/src/endpoints/catalog.rs
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/endpoints/mod.rs
  crates/utils/re_uri/src/endpoints/proxy.rs
  crates/utils/re_uri/src/endpoints/recording.rs
  crates/utils/re_uri/src/error.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: exclude from changelog, dataplatform

#9423 Remove legacy API protos and their use, including the legacy Python API
  Cargo.lock
  Cargo.toml
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  crates/store/re_protos/proto/rerun/v1alpha1/collection.proto
  crates/store/re_protos/proto/rerun/v1alpha1/collection_ops.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/proto/rerun/v1alpha1/remote_store.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.remote_store.v1alpha1.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_smart_channel/src/receive_set.rs
  crates/utils/re_uri/src/endpoints/catalog.rs
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/endpoints/mod.rs
  crates/utils/re_uri/src/endpoints/proxy.rs
  crates/utils/re_uri/src/endpoints/recording.rs
  crates/utils/re_uri/src/lib.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  examples/python/remote/metadata.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/catalog.py
  rerun_py/rerun_sdk/rerun/remote.py
  rerun_py/src/catalog/mod.rs
  rerun_py/src/dataframe.rs
  rerun_py/src/lib.rs
  rerun_py/src/python_bridge.rs
  rerun_py/src/remote.rs
Labels: 🚜 refactor, exclude from changelog, dataplatform
