Repository rerun-io/rerun, pull requests merged in 2025-07, with the labels that each got.

#10404 Delay showing video wait-for-decoder spinner on seeks
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/utils/re_video/src/time.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_renderer/src/video/chunk_decoder.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_renderer/src/video/player.rs
  crates/viewer/re_view_spatial/src/visualizers/video/mod.rs
Labels: enhancement, 📺 re_viewer, include in changelog, 🎞️ video

#10450 Fix signature for `DatasetEntry.set_default_blueprint_partition_id()`
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/dataset_entry.rs
Labels: 🐍 Python API, exclude from changelog

#10446 reduce the need for .into on EntityPath in tests
  crates/store/re_chunk/examples/chunk_latest_at.rs
  crates/store/re_chunk/examples/chunk_range.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/tests/latest_at.rs
  crates/store/re_chunk/tests/range.rs
  crates/store/re_chunk_store/src/subscribers.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/tests/arrow_encode_roundtrip.rs
  crates/store/re_log_types/src/path/entity_path.rs
  crates/store/re_query/examples/query_latest_at.rs
  crates/store/re_query/examples/query_range.rs
  crates/store/re_query/tests/latest_at.rs
  crates/store/re_query/tests/range.rs
  crates/viewer/re_blueprint_tree/tests/blueprint_tree_tests.rs
  crates/viewer/re_blueprint_tree/tests/range_selection_test.rs
  crates/viewer/re_blueprint_tree/tests/view_structure_test.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_time_panel/src/recursive_chunks_per_timeline_subscriber.rs
  crates/viewer/re_time_panel/tests/time_panel_filter_tests.rs
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_spatial/tests/annotations.rs
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  crates/viewer/re_view_spatial/tests/transform_hierarchy.rs
  crates/viewer/re_view_spatial/tests/transform_tree_origins.rs
  crates/viewer/re_view_spatial/tests/visible_time_range.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport_blueprint/src/ui/add_view_or_container_modal.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  examples/rust/custom_data_loader/src/main.rs
  tests/python/release_checklist/check_blueprint_overrides.py
Labels: 🔨 testing, 🚜 refactor, exclude from changelog

#10457 Fix issue query of zombie todo script
  scripts/zombie_todos.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#10463 Implement `From` for more narrow integers and floats for `Float64`
  crates/store/re_types_core/src/datatypes/float64_ext.rs
Labels: 🦀 Rust API, include in changelog

#10469 Automate `check_blueprint_overrides` with image comparision test
  crates/viewer/re_view_time_series/tests/blueprint.rs
  crates/viewer/re_view_time_series/tests/snapshots/blueprint_overrides_and_defaults_with_time_series.png
  tests/python/release_checklist/check_blueprint_overrides.py
Labels: 🔨 testing, exclude from changelog

#10465 Remove indicator component UI from `DataPath`
  crates/store/re_types_core/src/component_descriptor.rs
  crates/viewer/re_data_ui/src/component_path.rs
Labels: exclude from changelog

#10438 Unify `ComponentDescriptor` handling across all SDKs
  crates/store/re_log_types/src/example_components.rs
  crates/store/re_log_types/src/path/parse_path.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_types/src/any_values.rs
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/component_descriptor.rs
  crates/store/re_types_core/src/reflection.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  rerun_cpp/src/rerun/component_descriptor.hpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_bindings/types.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/src/python_bridge.rs
Labels: exclude from changelog

#10473 Add --connect documentation to the CLI reference
  docs/content/reference/cli.md
Labels: 📖 documentation, exclude from changelog, deploy docs

#10477 Reduce log spam from ffmpeg
  crates/utils/re_video/Cargo.toml
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#10479 Show average FPS of selected video
  crates/utils/re_video/src/demux/mod.rs
  crates/viewer/re_data_ui/src/video.rs
Labels: ui, 📺 re_viewer, include in changelog, 🎞️ video

#10483 Cache old texture pixel readback data to avoid flickering
  crates/viewer/re_view_spatial/src/picking_ui_pixel.rs
Labels: 📺 re_viewer, 🦟 regression, exclude from changelog

#10482 Move `fuzzy_descriptors` up into the request object, with its peers
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog, dataplatform

#10487 Update egui: nicer looking text in light mode
  Cargo.lock
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/Visible_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/Visible_placeholder.png
  crates/viewer/re_time_panel/tests/snapshots/help_view_timeline_mac.png
  crates/viewer/re_time_panel/tests/snapshots/help_view_timeline_windows.png
  crates/viewer/re_ui/tests/snapshots/help_Mac.png
  crates/viewer/re_ui/tests/snapshots/help_Windows.png
  crates/viewer/re_view_bar_chart/tests/snapshots/help_view_bar_chart_view_mac.png
  crates/viewer/re_view_bar_chart/tests/snapshots/help_view_bar_chart_view_windows.png
  crates/viewer/re_view_dataframe/tests/snapshots/help_view_dataframe_view_mac.png
  crates/viewer/re_view_dataframe/tests/snapshots/help_view_dataframe_view_windows.png
  crates/viewer/re_view_dataframe/tests/snapshots/unknown_timeline_selection_panel_ui.png
  crates/viewer/re_view_graph/tests/snapshots/help_view_graph_view_mac.png
  crates/viewer/re_view_graph/tests/snapshots/help_view_graph_view_windows.png
  crates/viewer/re_view_map/tests/snapshots/help_view_map_view_mac.png
  crates/viewer/re_view_map/tests/snapshots/help_view_map_view_windows.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_2d_view_mac.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_2d_view_windows.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_3d_view_mac.png
  crates/viewer/re_view_spatial/tests/snapshots/help_view_3d_view_windows.png
  crates/viewer/re_view_tensor/tests/snapshots/help_view_tensor_view_mac.png
  crates/viewer/re_view_tensor/tests/snapshots/help_view_tensor_view_windows.png
  crates/viewer/re_view_text_document/tests/snapshots/help_view_text_document_view_mac.png
  crates/viewer/re_view_text_document/tests/snapshots/help_view_text_document_view_windows.png
  crates/viewer/re_view_text_log/tests/snapshots/help_view_text_log_view_mac.png
  crates/viewer/re_view_text_log/tests/snapshots/help_view_text_log_view_windows.png
  crates/viewer/re_view_time_series/tests/snapshots/help_view_time_series_view_mac.png
  crates/viewer/re_view_time_series/tests/snapshots/help_view_time_series_view_windows.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Dataframe.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/BarChart.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Dataframe.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Graph.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TextDocument.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TextLog.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TimeSeries.png
Labels: ui, dependencies, exclude from changelog, egui

#10472 `DatasetEntry.register` now returns the created partition id
  Cargo.lock
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/connection_client.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/catalog/task.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#10491 Source physical column names from the original `RecordBatch`es
  crates/viewer/re_dataframe_ui/src/datafusion_adapter.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
Labels: ui, 🦟 regression, exclude from changelog, dataplatform, feat-redap-browser

#10492 Add the long awaited `py-build-release-examples`
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#10499 Remove dead code
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/timeline.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/TimelineName_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/TimelineName_placeholder.png
Labels: exclude from changelog

#10497 Fix `VideoStream` playback
  crates/viewer/re_renderer/src/video/player.rs
Labels: 🪳 bug, exclude from changelog, 🎞️ video

#10503 Rename the 'Welcome screen' option to 'Rerun examples'
  crates/viewer/re_global_context/src/app_options.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
Labels: ui, include in changelog

#10513 Switch from `indicators` to `relevant_archetypes`
  crates/store/re_types_core/src/loggable.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_viewer_context/src/typed_entity_collections.rs
  crates/viewer/re_viewer_context/src/view/visualizer_entity_subscriber.rs
  crates/viewer/re_viewer_context/src/view/visualizer_system.rs
  examples/rust/custom_view/src/points3d_color_visualizer.rs
Labels: exclude from changelog

#10517 Remove margin around table
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/tests/snapshots/null_timeline.png
Labels: ui, 📺 re_viewer, exclude from changelog

#10527 Fix tooltips sometimes jumping around on screen
  Cargo.lock
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#10533 Replace menu icon with SVG to make it sharper
  crates/viewer/re_ui/data/icons/rerun_menu.png
  crates/viewer/re_ui/data/icons/rerun_menu.svg
  crates/viewer/re_ui/src/context_ext.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
Labels: 📺 re_viewer, exclude from changelog

#10526 Show arrow data in header tooltips and ever more data when alt is down
  Cargo.lock
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/header_tooltip.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/tests/column_header_tooltips.rs
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_chunk_component_column.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_chunk_component_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_dataframe_component_column.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_dataframe_component_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_index_column.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_index_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_user_and_sorbet_metadata.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_user_and_sorbet_metadata_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_user_metadata.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_user_metadata_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_field_nullable.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_field_nullable_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_id_column.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_id_column_with_extras.png
  crates/viewer/re_ui/src/context_ext.rs
  crates/viewer/re_ui/src/ui_ext.rs
Labels: ui, include in changelog

#10488 Improve `zombie_todo.py`
  scripts/zombie_todos.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#10390 Add `DataframeQueryView.to_arrow_reader()`
  crates/viewer/re_dataframe_ui/tests/column_header_tooltips.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🐍 Python API, exclude from changelog, feat-dataframe-api, dataplatform

#10532 expose dataset maintenance endpoint on the frontend
  crates/store/re_grpc_client/src/connection_client.rs
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog

#10546 Fix a few problems with iterating over hash types
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/viewer/re_chunk_store_ui/src/chunk_list_mode.rs
  crates/viewer/re_chunk_store_ui/src/lib.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_context_menu/src/actions/add_entities_to_new_view.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_ui/src/filter_widget.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: 🪳 bug, 🧑‍💻 dev experience, 📺 re_viewer, exclude from changelog

#10547 Fix `set_time_ctrl` not doing anything when called twice
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
Labels: 🐍 Python API, notebook, include in changelog

#10545 Fix H.264 with b-frames not decoding last few frames on native
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/viewer/re_view_spatial/tests/snapshots/video_asset_H264_beyond_end.png
  crates/viewer/re_view_spatial/tests/video.rs
Labels: 🪳 bug, include in changelog, 🎞️ video

#10553 Improve image benchmark with named arguments
  tests/rust/log_benchmark/src/image.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#10448 Creating custom stream instead of relying on existing partition stream
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🏹 arrow, exclude from changelog, dataplatform

#10557 Dynamically Set Active Partition URL and Select Time Window
  .typos.toml
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  rerun_js/web-viewer/index.ts
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/notebook.py
  rerun_py/src/catalog/dataset_entry.rs
  scripts/fast_lint.py
  scripts/lint.py
Labels: 🧑‍💻 dev experience, notebook, include in changelog

#10552 Improve error gRPC-related error messages
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_server/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#10567 Update egui with deprecated popup API
  Cargo.lock
  crates/viewer/re_selection_panel/src/view_space_origin_ui.rs
  crates/viewer/re_ui/src/notifications.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: dependencies, exclude from changelog, egui

#10563 Fix deadlock while preserving recording isolation
  crates/top/re_sdk/src/recording_stream.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/src/python_bridge.rs
  rerun_py/src/utils.rs
  rerun_py/tests/unit/test_expected_warnings.py
  rerun_py/tests/unit/test_multi_stream.py
Labels: 🐍 Python API, exclude from changelog

#10576 Revert "Creating custom stream instead of relying on existing partition stream"
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🦟 regression, exclude from changelog

#10573 Improve table line height logic
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_chunk_store_ui/src/sort.rs
  crates/viewer/re_component_ui/src/geo_line_string.rs
  crates/viewer/re_component_ui/src/line_strip.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/tests/snapshots/null_timeline.png
  crates/viewer/re_view_text_log/src/view_class.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#10578 Fix spacing in table view header
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/tests/snapshots/null_timeline.png
Labels: ui, exclude from changelog

#10518 Support callbacks in React
  crates/viewer/re_viewer/src/event.rs
  rerun_js/web-viewer-react/index.js
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer-react/types.d.ts
  rerun_js/web-viewer/index.ts
Labels: 🕸️ web, include in changelog

#10579 Remove unused `ViewContextSystem::compatible_component_set`
  crates/viewer/re_view/src/annotation_scene_context.rs
  crates/viewer/re_view_spatial/src/contexts/depth_offsets.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_viewer_context/src/view/view_context_system.rs
Labels: exclude from changelog

#10569 Add support for table entries in the redap browser
  Cargo.lock
  crates/store/re_grpc_client/src/connection_client.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_global_context/src/item.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  rerun_py/src/catalog/connection_handle.rs
Labels: ui, include in changelog, dataplatform, feat-redap-browser

#10571 Add a 'copy entry url' button next to the name of remote datasets and table
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/servers.rs
Labels: ui, include in changelog, feat-redap-browser

#10591 Stop serializing selection state
  crates/viewer/re_viewer/src/app_state.rs
Labels: 📺 re_viewer, exclude from changelog

#10587 Show loading screen when starting viewer with a URL
  crates/utils/re_smart_channel/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/loading_data_ui.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/mod.rs
Labels: ui, 📺 re_viewer, include in changelog

#10589 Improve documentation around `AnyValues` and custom data
  docs/content/howto/logging/custom-data.md
  docs/snippets/all/tutorials/any_values.py
  docs/snippets/all/tutorials/any_values.rs
Labels: 📖 documentation, include in changelog

#10369 Add additional Rust test cases for (static) dataframe queries
  Cargo.lock
  crates/store/re_chunk_store/tests/dataframe.rs
  crates/store/re_chunk_store/tests/snapshots/dataframe__schema_static_columns-2.snap
  crates/store/re_chunk_store/tests/snapshots/dataframe__schema_static_columns-3.snap
  crates/store/re_chunk_store/tests/snapshots/dataframe__schema_static_columns.snap
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/tests/static.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/dataframe/recording.rs
  rerun_py/src/dataframe/recording_view.rs
  rerun_py/tests/unit/test_dataframe.py
Labels: 🔨 testing, exclude from changelog

#10584 Removes remnants of indicators from dataframe queries and viewer
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/tests/dataframe.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_sorbet/src/migrations/v0_0_2__to__v0_1_0.rs
  crates/store/re_sorbet/src/schema_builder.rs
  crates/store/re_types_core/src/component_descriptor.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/src/header_tooltip.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_dataframe_ui/tests/column_header_tooltips.rs
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_chunk_component_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_dataframe_component_column_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_user_and_sorbet_metadata_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_user_metadata_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_raw_field_with_extras.png
  crates/viewer/re_dataframe_ui/tests/snapshots/header_tooltip_row_field_nullable_with_extras.png
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_view_spatial/tests/snapshots/video_asset_H264_beyond_end.png
  crates/viewer/re_viewer_context/src/tables.rs
  crates/viewer/re_viewer_context/src/view/visualizer_system.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/dataframe.py
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/dataframe/component_columns.rs
  rerun_py/src/dataframe/recording.rs
Labels: 📺 re_viewer, include in changelog, 🪵 Log & send APIs, feat-dataframe-view, feat-dataframe-api

#10598 Convert `AnyValues` test in `re_dataframe` to snapshot
  crates/store/re_dataframe/src/query.rs
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__query_static_any_values.snap
  crates/store/re_dataframe/tests/static.rs
Labels: exclude from changelog

#10600 Remove hacks to half-buggily-support undef behavior (duped Row IDs)
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, ⛃ re_datastore, 📉 performance, exclude from changelog

#10603 Fix Chunk Store issues that went under the radar
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: 🪳 bug, ⛃ re_datastore, exclude from changelog

#10590 Fix `VideoStream` stuttering on web
  Cargo.lock
  crates/utils/re_video/Cargo.toml
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/decode/webcodecs.rs
  crates/viewer/re_renderer/src/video/chunk_decoder.rs
  crates/viewer/re_renderer/src/video/player.rs
  examples/python/camera_video_stream/camera_video_stream.py
Labels: 🕸️ web, exclude from changelog, 🎞️ video

#10608 Workaround firefox tabs crashing when seeking in video
  crates/utils/re_video/src/decode/webcodecs.rs
Labels: 🕸️ web, 💣 crash, exclude from changelog, 🎞️ video

#10604 Update egui to 0.32
  .cargo/config.toml
  .github/workflows/contrib_checks.yml
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_build_web.yml
  .github/workflows/reusable_checks.yml
  .github/workflows/reusable_checks_rust.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_test_wheels.yml
  Cargo.lock
  Cargo.toml
  crates/build/re_dev_tools/src/build_web_viewer/lib.rs
  crates/store/re_datafusion/Cargo.toml
  crates/utils/re_tuid/src/lib.rs
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/filter_widget.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  deny.toml
  examples/rust/animated_urdf/Cargo.toml
  scripts/ci/rust_checks.py
Labels: dependencies, include in changelog

#10611 Fix crate publishing caused by `include_bytes` outside of crate
  Cargo.lock
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/tables.rs
Labels: exclude from changelog

#10613 Fix depending on deleted alpha in pixi
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#10617 Improve error message for FFmpeg not found
  crates/utils/re_video/src/decode/ffmpeg_h264/version.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
Labels: 📺 re_viewer, include in changelog, 🎞️ video

#10605 `rrd stats`: add transport-layer only fast path
  crates/top/rerun/src/commands/rrd/stats.rs
Labels: 📉 performance, include in changelog, CLI, dataplatform

#10623 Use new archetype name layout in defaults ui
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
Labels: ui, exclude from changelog

#10607 `rerun rrd route` command to manipulate `.rrd`s on transport level
  crates/store/re_log_encoding/src/codec/file/encoder.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/route.rs
  docs/content/reference/cli.md
Labels: ⛃ re_datastore, include in changelog, CLI

#10614 Add snippet demonstrating re-muxing of `VideoStream` data
  docs/content/reference/video.md
  docs/snippets/all/archetypes/video_stream_query_and_mux.py
  docs/snippets/snippets.toml
Labels: examples, include in changelog

#10629 Remove `:` after visualizer in selection panel
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
Labels: exclude from changelog

#10635 Remove redundant ffmpeg install check
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
Labels: 🪳 bug, 📉 performance, include in changelog

#10638 Add `attr.docs.unreleased` to `LinearSpeed`
  crates/store/re_types/definitions/rerun/components/linear_speed.fbs
  docs/content/reference/types/components/linear_speed.md
  docs/content/reference/types/datatypes/float64.md
Labels: exclude from changelog

#10641 Regenerate cli.md
  docs/content/reference/cli.md
Labels: 📖 documentation, exclude from changelog, CLI

#10622 Update documentation for component defaults
  crates/build/re_types_builder/src/codegen/docs/website.rs
  design/blueprint_store.md
  docs/content/concepts/visualizers-and-overrides.md
  docs/content/getting-started/configure-the-viewer/interactively.md
  docs/content/getting-started/navigating-the-viewer.md
  docs/content/reference/migration/migration-0-24.md
  docs/content/reference/types/archetypes.md
Labels: 📖 documentation, exclude from changelog

#10650 Fix TODO notes that refer to closed issues
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_renderer/shader/lines.wgsl
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_renderer/src/resource_managers/image_data_to_texture.rs
  crates/viewer/re_renderer/src/video/player.rs
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  docs/content/getting-started/data-out/explore-as-dataframe.md
  docs/content/getting-started/data-out/export-dataframe.md
  docs/content/getting-started/troubleshooting.md
  examples/python/nuscenes_dataset/README.md
  rerun_cpp/src/rerun/archetypes/tensor_ext.cpp
  rerun_py/rerun_sdk/rerun/datatypes/time_range_boundary.py
  rerun_py/src/catalog/catalog_client.rs
  tests/python/chunked_video/chunked_video.py
Labels: 📖 documentation, 🔨 testing, 🚜 refactor, exclude from changelog

#10601 Add `to_arrow_reader()` to `TableEntry` and `DataFusionTable`
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/arrow.rs
  rerun_py/src/catalog/datafusion_table.rs
  rerun_py/src/catalog/table_entry.rs
Labels: 🐍 Python API, include in changelog

#10306 Log a warning when starting the viewer from inside a Docker container
  crates/utils/re_analytics/src/event.rs
  crates/viewer/re_viewer/src/docker_detection.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/native.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
Labels: 🧑‍💻 dev experience, include in changelog

#10654 Introduce `RecordingOpen` viewer event
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/event.rs
  examples/rust/viewer_callbacks/src/main.rs
  pixi.toml
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer/index.ts
  rerun_py/rerun_sdk/rerun/event.py
Labels: 🕸️ web, notebook, include in changelog

#10637 Add juxtaposition of `SeriesLines` and `SeriesPoints` to `visualizer-overrides` snippet
  docs/snippets/INDEX.md
  docs/snippets/all/tutorials/visualizer-overrides.py
Labels: 📖 documentation, include in changelog

#10657 Make it possible to configure batcher explicitly via python APIs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
  rerun_py/tests/unit/test_batcher_config.py
  scripts/ci/python_check_signatures.py
Labels: 🐍 Python API, include in changelog

#10660 Fix rust api annoyances
  crates/store/re_types_core/src/archetype.rs
  crates/top/re_sdk/src/lib.rs
Labels: 🦀 Rust API, exclude from changelog

#10662 Micro-batching snippets
  docs/content/reference/sdk/micro-batching.md
  docs/snippets/INDEX.md
  docs/snippets/all/howto/micro_batching.py
  docs/snippets/all/howto/micro_batching.rs
  docs/snippets/snippets.toml
Labels: 📖 documentation, include in changelog

#10665 re_perf_telemetry should not override explicit RUST_LOG entries
  crates/utils/re_perf_telemetry/src/lib.rs
  crates/utils/re_perf_telemetry/src/telemetry.rs
Labels: exclude from changelog, dataplatform

#10666 AnyValues Edge Cases and Air Traffic Example Fix
  examples/python/air_traffic_data/air_traffic_data.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/tests/unit/test_any_values.py
Labels: 🪳 bug, examples, exclude from changelog

#10673 Fix transform order for arkit example
  examples/python/arkit_scenes/arkit_scenes/__main__.py
Labels: 🪳 bug, examples, exclude from changelog

#10674 Add documentation for all things compaction
  crates/top/rerun/src/commands/rrd/mod.rs
  docs/content/howto/optimize-chunks.md
  docs/content/reference/cli.md
Labels: 📖 documentation, ⛃ re_datastore, 📉 performance, include in changelog, CLI

#10670 Add note on x-platform decoder inaccuracy
  docs/content/reference/video.md
Labels: 📖 documentation, exclude from changelog, 🎞️ video

#10676 Don't style (&describe) missing video samples like an error
  crates/viewer/re_view_spatial/src/pickable_textured_rect.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
  crates/viewer/re_view_spatial/src/picking_ui_pixel.rs
  crates/viewer/re_view_spatial/src/visualizers/video/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/video/video_frame_reference.rs
  crates/viewer/re_view_spatial/src/visualizers/video/video_stream.rs
Labels: ui, exclude from changelog, 🎞️ video

#10678 Return dataframe types instead of polluting with any
  rerun_py/rerun_bindings/rerun_bindings.pyi
Labels: 🧑‍💻 dev experience, dogfooding, exclude from changelog, dataplatform

#10686 attempt fix doc deployment
  docs/content/reference/video.md
Labels: exclude from changelog, deploy docs

#10706 fix breaking example in rerun_notebook/example.ipynb
  rerun_notebook/example.ipynb
Labels: 🪳 bug, notebook, include in changelog

#10714 Move `log_msg` protos helper to the correct file
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.log_msg.v1alpha1.ext.rs
Labels: 🚜 refactor, exclude from changelog

#10715 Improve error handling in `air_traffic_data.py`
  examples/python/air_traffic_data/air_traffic_data.py
Labels: examples, exclude from changelog

#10734 Add support for codegen in bacon
  bacon.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#10713 Always bootstrap secondaries in plot view
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_view_time_series/tests/snapshots/bootstrapped_secondaries_full.png
  crates/viewer/re_view_time_series/tests/snapshots/bootstrapped_secondaries_partial.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: 🪳 bug, include in changelog, 🔩 data model, 📈 plot

#10733 Add missing `re_global_context/testing` to `re_blueprint_tree`
  crates/viewer/re_blueprint_tree/Cargo.toml
  crates/viewer/re_viewer_context/Cargo.toml
Labels: exclude from changelog

#10743 Regression-proof error constants for re_auth
  crates/utils/re_auth/src/lib.rs
  crates/utils/re_auth/src/service/server.rs
  crates/viewer/re_redap_browser/src/entries.rs
Labels: ui, exclude from changelog, dataplatform

#10747 Get rid of `RegisterWithDatasetBlocking` (dev)
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#10738 Add wasm support for MCAP loader
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_data_loader/src/loader_mcap.rs
Labels: 🕸️ web, 📺 re_viewer, exclude from changelog

#10754 Ability to create dataset with specified ID
  crates/store/re_grpc_client/src/connection_client.rs
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#10758 Remove `impl Display for StoreId` as it no longer makes sense
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_entity_db/src/store_bundle.rs
  crates/store/re_entity_db/src/times_per_timeline.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_query/src/cache.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/commands/rrd/print.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_data_ui/src/store_id.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  examples/rust/custom_store_subscriber/src/main.rs
  rerun_py/src/python_bridge.rs
Labels: ui, 🚜 refactor, exclude from changelog

#10752 Parse `PointCloud2` into raw Arrow and `Points3D`
  crates/store/re_data_loader/src/loader_mcap.rs
  crates/store/re_data_loader/src/mcap/schema/mod.rs
  crates/store/re_data_loader/src/mcap/schema/sensor_msgs/mod.rs
  crates/store/re_data_loader/src/mcap/schema/sensor_msgs/point_cloud_2.rs
  crates/utils/re_mcap_ros2/src/geometry_msgs.rs
  crates/utils/re_mcap_ros2/src/sensor_msgs.rs
Labels: 📺 re_viewer, include in changelog, feat-mcap

#10765 Set application id to file path when loading file
  crates/store/re_data_loader/src/load_file.rs
  crates/viewer/re_viewer/src/app.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#10755 Handle errors in redap browser more gracefully
  Cargo.lock
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_redap_browser/src/tables_session_context.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: 🪳 bug, exclude from changelog, feat-redap-browser

#10722 Upload notebook assets to `{version}/notebook/{file}`
  rerun_js/web-viewer/index.ts
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_notebook/src/rerun_notebook/error_widget.js
  scripts/ci/publish_wheels.py
Labels: exclude from changelog

#10769 Log all low-level MCAP primitives + raw messages as fallback
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_data_loader/src/loader_mcap.rs
  crates/store/re_data_loader/src/mcap/decode.rs
  crates/store/re_data_loader/src/mcap/schema/mod.rs
  crates/store/re_data_loader/src/mcap/schema/raw.rs
  crates/store/re_data_loader/src/mcap/schema/sensor_msgs/point_cloud_2.rs
  crates/store/re_data_loader/src/mcap/schema/unsupported.rs
Labels: ui, 📺 re_viewer, include in changelog, feat-mcap

#10774 Add `__len__` to codegened Python datatypes
  crates/build/re_types_builder/src/codegen/python/mod.rs
  rerun_py/rerun_sdk/rerun/components/annotation_context.py
  rerun_py/rerun_sdk/rerun/components/geo_line_string.py
  rerun_py/rerun_sdk/rerun/components/line_strip2d.py
  rerun_py/rerun_sdk/rerun/components/line_strip3d.py
  rerun_py/rerun_sdk/rerun/datatypes/blob.py
  rerun_py/rerun_sdk/rerun/datatypes/dvec2d.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4.py
  rerun_py/rerun_sdk/rerun/datatypes/plane3d.py
  rerun_py/rerun_sdk/rerun/datatypes/quaternion.py
  rerun_py/rerun_sdk/rerun/datatypes/range1d.py
  rerun_py/rerun_sdk/rerun/datatypes/uuid.py
  rerun_py/rerun_sdk/rerun/datatypes/uvec2d.py
  rerun_py/rerun_sdk/rerun/datatypes/uvec3d.py
  rerun_py/rerun_sdk/rerun/datatypes/uvec4d.py
  rerun_py/rerun_sdk/rerun/datatypes/vec2d.py
  rerun_py/rerun_sdk/rerun/datatypes/vec3d.py
  rerun_py/rerun_sdk/rerun/datatypes/vec4d.py
  rerun_py/rerun_sdk/rerun/datatypes/view_coordinates.py
  rerun_py/tests/test_types/components/affix_fuzzer11.py
  rerun_py/tests/test_types/components/affix_fuzzer12.py
  rerun_py/tests/test_types/components/affix_fuzzer13.py
  rerun_py/tests/test_types/components/affix_fuzzer16.py
  rerun_py/tests/test_types/components/affix_fuzzer17.py
  rerun_py/tests/test_types/components/affix_fuzzer18.py
  rerun_py/tests/test_types/components/affix_fuzzer7.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer22.py
  rerun_py/tests/unit/test_transform3d.py
  rerun_py/tests/unit/test_utilities_datafusion.py
Labels: 🐍 Python API, codegen/idl, include in changelog

#10775 New .proto definitions for updating a Catalog Entry -- starting with name
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/proto/rerun/v1alpha1/catalog.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#10704 Try to Fix Python Typing
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/viewer/re_global_context/src/app_options.rs
  crates/viewer/re_view_time_series/src/util.rs
  docs/snippets/all/archetypes/video_stream_synthetic.py
  docs/snippets/all/descriptors/descr_custom_archetype.py
  docs/snippets/all/migration/log_line.py
  docs/snippets/all/tutorials/custom_data.py
  examples/python/camera_video_stream/camera_video_stream.py
  examples/python/controlnet/controlnet.py
  examples/python/detect_and_track_objects/detect_and_track_objects.py
  examples/python/multiprocess_logging/multiprocess_logging.py
  pixi.lock
  pixi.toml
  rerun_py/.non_sdk_mypy.ini
  rerun_py/pyproject.toml
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/archetypes/depth_image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/image_ext.py
  rerun_py/rerun_sdk/rerun/archetypes/video_stream.py
  rerun_py/rerun_sdk/rerun/components/scale3d_ext.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer20.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer5.py
  rerun_py/tests/test_types/datatypes/multi_enum.py
  rerun_py/tests/unit/common_arrays.py
  rerun_py/tests/unit/test_line_strips2d.py
  rerun_py/tests/unit/test_multiprocessing_gc.py
  rerun_py/tests/unit/test_plot_legend.py
  rerun_py/tests/unit/test_transform3d.py
  rerun_py/tests/unit/test_view_blueprint.py
  rerun_py/tests/unit/test_viewport_blueprint.py
  scripts/ci/crates.py
  scripts/fast_lint.py
  tests/python/release_checklist/check_chroma_subsampling.py
Labels: 🧑‍💻 dev experience, 😤 annoying, 🛑 controversial, include in changelog
