Repository rerun-io/rerun, pull requests merged in 2025-01, with the labels that each got.

#8573 Fix tooltips being dragged along in graph view
  crates/viewer/re_view_graph/src/ui/draw.rs
Labels: ui, include in changelog

#8553 Introduce new Chunk iteration APIs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_query/examples/range.rs
  crates/store/re_query/tests/range.rs
  crates/store/re_types_core/src/lib.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/entity_iterator.rs
Labels: enhancement, 🏹 arrow, 🧑‍💻 dev experience, 🔍 re_query, include in changelog

#8554 Update all visualizers to use new Chunk iteration APIs
  crates/viewer/re_view_graph/src/visualizers/nodes.rs
  crates/viewer/re_view_map/src/visualizers/geo_line_strings.rs
  crates/viewer/re_view_map/src/visualizers/geo_points.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_view_text_log/src/visualizer_system.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
Labels: 📺 re_viewer, 🚜 refactor, exclude from changelog

#8555 Update `GraphEdge` visualizer to use sliced struct fields
  crates/viewer/re_view_graph/src/visualizers/edges.rs
Labels: 📺 re_viewer, do-not-merge, 🚜 refactor, exclude from changelog

#8556 Remove all legacy Chunk iteration APIs
  Cargo.lock
  crates/store/re_chunk/src/iter.rs
  crates/viewer/re_view/Cargo.toml
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_graph/src/visualizers/edges.rs
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/src/visualizers/utilities/entity_iterator.rs
Labels: 🏹 arrow, 📺 re_viewer, 🔍 re_query, 🚜 refactor, include in changelog

#8579 Fix downcast typo in line visualizers
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
Labels: 📺 re_viewer, 🔍 re_query, 💣 crash, exclude from changelog

#8587 Fix `RecordingStream::log` implicitly requiring `Sized`
  crates/top/re_sdk/src/recording_stream.rs
Labels: 🪳 bug, 🦀 Rust API, 😤 annoying, include in changelog

#8585 Reallow `#[cfg(TODO)]`
  Cargo.toml
Labels: 🧑‍💻 dev experience, 😤 annoying, exclude from changelog

#8539 Port more of the viewer to arrow1
  Cargo.lock
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_dataframe/src/query.rs
  crates/utils/re_memory/src/accounting_allocator.rs
  crates/viewer/re_view_dataframe/Cargo.toml
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  rerun_py/src/dataframe.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8590 Use the same `arrow_ui` function everywhere
  Cargo.lock
  crates/viewer/re_chunk_store_ui/Cargo.toml
  crates/viewer/re_chunk_store_ui/src/arrow_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_chunk_store_ui/src/lib.rs
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/src/fallback_ui.rs
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/ui_layout.rs
  crates/viewer/re_ui/tests/arrow_ui_test.rs
  crates/viewer/re_ui/tests/snapshots/arrow_ui.png
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/lib.rs
Labels: ui, 🚜 refactor, exclude from changelog

#8596 Use arrow1 datatype in reflection
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_viewer/src/blueprint/validation.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor, exclude from changelog

#8595 Use arrow1 Fields in Archetype::from_arrow
  .github/ISSUE_TEMPLATE/project.md
  crates/store/re_types/tests/types/annotation_context.rs
  crates/store/re_types/tests/types/arrows3d.rs
  crates/store/re_types/tests/types/asset3d.rs
  crates/store/re_types/tests/types/box2d.rs
  crates/store/re_types/tests/types/box3d.rs
  crates/store/re_types/tests/types/clear.rs
  crates/store/re_types/tests/types/depth_image.rs
  crates/store/re_types/tests/types/fuzzy.rs
  crates/store/re_types/tests/types/image.rs
  crates/store/re_types/tests/types/line_strips2d.rs
  crates/store/re_types/tests/types/line_strips3d.rs
  crates/store/re_types/tests/types/main.rs
  crates/store/re_types/tests/types/mesh3d.rs
  crates/store/re_types/tests/types/pinhole.rs
  crates/store/re_types/tests/types/points2d.rs
  crates/store/re_types/tests/types/points3d.rs
  crates/store/re_types/tests/types/segmentation_image.rs
  crates/store/re_types/tests/types/tensor.rs
  crates/store/re_types/tests/types/text_document.rs
  crates/store/re_types/tests/types/transform3d.rs
  crates/store/re_types/tests/types/util.rs
  crates/store/re_types/tests/types/validity.rs
  crates/store/re_types/tests/types/view_coordinates.rs
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/lib.rs
  docs/snippets/all/tutorials/custom_data.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8571 Replace `--serve` with `--serve-web` from v0.20
  crates/top/rerun/src/commands/entrypoint.rs
  docs/content/reference/cli.md
Labels: 🪳 bug, 📖 documentation, exclude from changelog, CLI

#8284 Add example for extending the viewer with custom callbacks
  Cargo.lock
  examples/rust/custom_callback/Cargo.toml
  examples/rust/custom_callback/README.md
  examples/rust/custom_callback/src/app.rs
  examples/rust/custom_callback/src/comms/app.rs
  examples/rust/custom_callback/src/comms/mod.rs
  examples/rust/custom_callback/src/comms/protocol.rs
  examples/rust/custom_callback/src/comms/viewer.rs
  examples/rust/custom_callback/src/lib.rs
  examples/rust/custom_callback/src/panel.rs
  examples/rust/custom_callback/src/viewer.rs
  examples/rust/extend_viewer_ui/README.md
Labels: 🦀 Rust API, examples, include in changelog

#8543 `EntityPathFilter` variable substitutions are now delegated to (new) `ResolvedEntityPathFilter`
  crates/store/re_dataframe/examples/query.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/store/re_log_types/src/path/mod.rs
  crates/viewer/re_context_menu/src/actions/add_entities_to_new_view.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_viewer_context/src/view/spawn_heuristics.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  rerun_py/src/dataframe.rs
Labels: 🪳 bug, 🦀 Rust API, 🚜 refactor, 🟦 blueprint, include in changelog

#8598 Fix soft-merge conflict with `PyRemoteRecording`
  crates/store/re_log_types/src/path/entity_path_filter.rs
  examples/manifest.toml
  rerun_py/src/remote.rs
Labels: 🪳 bug, exclude from changelog

#8591 Specify, test, and fix all broken `AsComponents`<>`ComponentBatch` interactions from blanket impls
  Cargo.lock
  crates/store/re_types_core/Cargo.toml
  crates/store/re_types_core/src/as_components.rs
  crates/store/re_types_core/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  docs/snippets/all/archetypes/mesh3d_partial_updates.rs
Labels: 🪳 bug, 🦀 Rust API, include in changelog

#8601 Fix `custom_callback` manifest
  Cargo.lock
  crates/store/re_types_core/src/as_components.rs
  examples/rust/custom_callback/Cargo.toml
Labels: 🪳 bug, dependencies, exclude from changelog

#8578 Use `egui_kittest` for the graph view
  Cargo.lock
  crates/store/re_dataframe/src/query.rs
  crates/store/re_log_types/src/time_point/timeline.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_graph/Cargo.toml
  crates/viewer/re_view_graph/src/layout/geometry.rs
  crates/viewer/re_view_graph/src/layout/result.rs
  crates/viewer/re_view_graph/src/lib.rs
  crates/viewer/re_view_graph/src/visualizers/edges.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_graph/tests/snapshots/coincident_nodes.png
  crates/viewer/re_view_graph/tests/snapshots/self_and_multi_edges.png
  crates/viewer/re_viewer/src/blueprint/validation.rs
  crates/viewer/re_viewer_context/src/query_context.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/time_control.rs
  crates/viewer/re_viewer_context/src/typed_entity_collections.rs
  crates/viewer/re_viewer_context/src/view/highlights.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport/src/lib.rs
  crates/viewer/re_viewport/src/system_execution.rs
  tests/python/release_checklist/check_graph_view.py
  tests/python/release_checklist/check_graph_view_multi_self_edges.py
Labels: 🔨 testing, exclude from changelog

#8599 Restore the time panel help button
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/tests/snapshots/time_panel_dense_data.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections.png
Labels: ui, include in changelog

#8605 Remove superfluous blanket impls in our logging traits
  crates/store/re_types_core/src/as_components.rs
  crates/store/re_types_core/src/loggable_batch.rs
Labels: 🦀 Rust API, 🚜 refactor, exclude from changelog, 🪵 Log & send APIs

#8609 Fix compilation for GCC 13.3 (missing `cstdint` include)
  rerun_cpp/src/rerun/component_descriptor.hpp
Labels: 🪳 bug, 🌊 C++ API, include in changelog

#8604 Only override the arrow1 versions of the Loggable trait
  Cargo.lock
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/helpers.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_log_types/src/path/entity_path.rs
  crates/store/re_types_core/benches/bench_tuid.rs
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/as_components.rs
  crates/store/re_types_core/src/loggable.rs
  crates/store/re_types_core/src/tuid.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_view/src/lib.rs
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8611 Fix broken mesh visualizer
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  rerun_cpp/src/rerun/component_descriptor.hpp
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#8566 Add `rpc` calls to unregister recordings from catalog
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
Labels: exclude from changelog, dataplatform

#8616 Use the correct eframe options for our custom viewer examples
  examples/rust/custom_callback/src/viewer.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: examples, exclude from changelog, egui

#8607 Implement copy-screenshot-to-clipboard on Web
  Cargo.lock
  Cargo.toml
  crates/viewer/re_context_menu/src/actions/screenshot_action.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/screenshotter.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/clipboard.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#8610 Fix WSL support, update troubleshooting guide
  Cargo.lock
  Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_component_ui/src/marker_shape.rs
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_map/src/map_overlays.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/native.rs
  crates/viewer/re_viewer/src/web.rs
  docs/content/getting-started/troubleshooting.md
Labels: 🪳 bug, 💣 crash, include in changelog, VM / WSL / Docker

#8621 Fix .gitignore ignoring `crates/build`
  .gitignore
Labels: exclude from changelog

#8614 improve ergonomics of encoding and decoding data (using arrow IPC)
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8624 Update failing screenshot tests, tweak graph test
  crates/viewer/re_ui/tests/snapshots/modal_normal.png
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_graph/tests/snapshots/coincident_nodes.png
  crates/viewer/re_view_graph/tests/snapshots/self_and_multi_edges.png
Labels: exclude from changelog, :ship: CI

#8612 Add analytics for wgpu backend and whether the viewer runs in WSL
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_analytics/src/event.rs
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/native.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer/src/viewer_analytics/mod.rs
  crates/viewer/re_viewer/src/viewer_analytics/wsl.rs
  crates/viewer/re_viewer/src/web.rs
  examples/rust/custom_callback/src/viewer.rs
  examples/rust/custom_view/src/main.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 📊 analytics, include in changelog

#8617 Port `PendingRow` to `arrow-rs`
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/arrow2_util.rs
  crates/store/re_chunk/src/arrow_util.rs
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/migration.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk/tests/memory_test.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_chunk_store/tests/memory_test.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun_c/src/lib.rs
  rerun_py/src/arrow.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8628 Port `generic_placeholder_for_datatype` to `arrow-rs`
  Cargo.lock
  crates/store/re_types_core/Cargo.toml
  crates/store/re_types_core/src/arrow_string.rs
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/Plane3D_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/Plane3D_placeholder.png
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
Labels: 🚜 refactor, exclude from changelog

#8632 Port `ChunkBuilder` to `arrow-rs`
  Cargo.lock
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/tests/latest_at.rs
  crates/store/re_chunk/tests/range.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_chunk_store/tests/reads.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8606 Enable `re_renderer` for all tests using the `TestContext` if graphics adapter is present
  Cargo.lock
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/Colormap_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/Colormap_placeholder.png
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport_blueprint/Cargo.toml
  deny.toml
Labels: 🔨 testing, exclude from changelog

#8626 Update remote store id field name
  examples/python/remote/metadata.py
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8636 Extend (and rename) `ItemSpaceContext` to provide local context to context menu action
  crates/viewer/re_context_menu/src/actions/collapse_expand_all.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
Labels: ui, exclude from changelog

#8620 Run Linux & Windows screenshot tests via `lavapipe` software rasterizer
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks_rust.yml
  .gitignore
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/view_builder.rs
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_ui/tests/arrow_ui_test.rs
  crates/viewer/re_ui/tests/list_item_tests.rs
  crates/viewer/re_ui/tests/modal_tests.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  scripts/ci/setup_software_rasterizer.py
Labels: 🔨 testing, 🪟 windows, 🐧 linux, exclude from changelog, :ship: CI

#8633 Make `ViewerContext::render_ctx` non-optional
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
  crates/viewer/re_view_spatial/src/picking_ui_pixel.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/mod.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor, exclude from changelog

#8655 Fix some clippy 1.84.0 lints
  crates/build/re_build_tools/src/hashing.rs
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/build/re_types_builder/src/docs.rs
  crates/store/re_chunk/src/arrow2_util.rs
  crates/store/re_chunk/src/arrow_util.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_data_loader/src/loader_external.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_sdk_comms/src/tcp_client.rs
  crates/store/re_types_core/src/loggable_batch.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_byte_size/src/std_sizes.rs
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_component_ui/src/radius.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_renderer/build.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/src/time_selection_ui.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/scene_bounding_boxes.rs
  crates/viewer/re_view_spatial/src/transform_component_tracker.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_tensor/src/dimension_mapping.rs
  crates/viewer/re_view_tensor/src/tensor_dimension_mapper.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/util.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer_context/src/query_context.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
  rerun_py/src/python_bridge.rs
Labels: 🚜 refactor, exclude from changelog

#8638 Port `TimeColumn` to arrow-rs
  Cargo.lock
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/tests/memory_test.rs
  crates/store/re_chunk_store/tests/snapshots/memory_test__scalars_on_one_timeline_new.snap
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/src/query.rs
  crates/store/re_log_types/src/time_point/mod.rs
  crates/store/re_log_types/src/time_point/timeline.rs
  crates/top/re_sdk/Cargo.toml
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun_c/Cargo.toml
  crates/top/rerun_c/src/lib.rs
  crates/utils/re_byte_size/src/arrow_sizes.rs
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  rerun_py/src/arrow.rs
Labels: 🏹 arrow, exclude from changelog

#8645 Filter entities in the UI (part 0): Make `CustomContent` more useful
  crates/viewer/re_selection_panel/src/item_heading_no_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_ui/examples/re_ui_example/right_panel.rs
  crates/viewer/re_ui/src/list_item/custom_content.rs
  crates/viewer/re_ui/src/list_item/debug_content.rs
  crates/viewer/re_ui/src/list_item/mod.rs
  crates/viewer/re_ui/src/list_item/property_content.rs
  crates/viewer/re_ui/tests/list_item_tests.rs
  crates/viewer/re_ui/tests/snapshots/list_items.png
Labels: ui, include in changelog

#8629 Add support for projection and filtering to python SDK remote store catalog queries
  examples/python/remote/metadata.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8642 New types and traits for (co-existing!) eager serialization
  crates/store/re_chunk/src/builder.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/store/re_types_core/src/as_components.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/loggable_batch.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  docs/snippets/all/descriptors/descr_builtin_component.rs
  docs/snippets/all/descriptors/descr_custom_component.rs
  docs/snippets/all/tutorials/custom_data.rs
  scripts/ci/check_large_files.py
Labels: enhancement, 🦀 Rust API, 🍏 primitives, include in changelog

#8648 Prevent flaky roundtrips in `rerun rrd compare`
  crates/top/rerun/src/commands/rrd/compare.rs
Labels: 🪳 bug, 🔨 testing, 🏹 arrow, exclude from changelog

#8649 Add legacy and next-gen partial updates snippets for all languages
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/points3d_partial_updates.cpp
  docs/snippets/all/archetypes/points3d_partial_updates.py
  docs/snippets/all/archetypes/points3d_partial_updates.rs
  docs/snippets/all/archetypes/points3d_partial_updates_legacy.cpp
  docs/snippets/all/archetypes/points3d_partial_updates_legacy.py
  docs/snippets/all/archetypes/points3d_partial_updates_legacy.rs
  lychee.toml
Labels: 📖 documentation, 🔨 testing, examples, exclude from changelog, 🪵 Log & send APIs

#8650 Eagerly serialized, partially updatable 2D & 3D line strips
  crates/store/re_types/definitions/rerun/archetypes/line_strips2d.fbs
  crates/store/re_types/definitions/rerun/archetypes/line_strips3d.fbs
  crates/store/re_types/src/archetypes/line_strips2d.rs
  crates/store/re_types/src/archetypes/line_strips3d.rs
  crates/store/re_types/tests/types/line_strips2d.rs
  crates/store/re_types/tests/types/line_strips3d.rs
Labels: 🦀 Rust API, 🍏 primitives, exclude from changelog

#8656 Fix formatting of RowId/Tuid when printing ChunkStore
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/tests/formatting.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_format_arrow/Cargo.toml
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_types_core/src/tuid.rs
  crates/utils/re_tuid/src/lib.rs
Labels: 🏹 arrow, 🧑‍💻 dev experience, exclude from changelog

#8657 Port row_ids to arrow1
  crates/store/re_chunk/src/arrow_util.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_dataframe/src/query.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/tuid.rs
  crates/utils/re_byte_size/src/arrow_sizes.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8663 Fix doc comments for `query_catalog` in `rerun_bindings.pyi`
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
  scripts/ci/build_and_upload_wheels.py
Labels: exclude from changelog

#8652 Filter entities in the UI (part 1): Introduce a filter widget
  Cargo.lock
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/data/icons/search.png
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/filter_widget.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/tests/filter_widget_test.rs
  crates/viewer/re_ui/tests/snapshots/filter_widget.png
Labels: ui, include in changelog

#8670 Update to flatbuffers 24
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog

#8667 Fix: rename `depends_on` to `depends-on` in `pixi.toml`
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#8658 Refactor `TimeColumnDescriptor`
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/query.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  rerun_py/src/dataframe.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8664 Port `re_format_arrow` to `arrow-rs`
  Cargo.lock
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_format_arrow/Cargo.toml
  crates/store/re_format_arrow/src/lib.rs
Labels: 🏹 arrow, exclude from changelog

#8672 Filter entities in the UI (part 3): Move action to a menu in the blueprint panel and keep default blueprint when using heuristics
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/command_sender.rs
  crates/viewer/re_viewer_context/src/store_context.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
Labels: ui, include in changelog

#8678 Fix unused imports
  crates/store/re_log_encoding/src/protobuf_conversions.rs
Labels: exclude from changelog

#8682 Port Transform3D to eager serialization & update API
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/store/re_types/definitions/rerun/archetypes/transform3d.fbs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/transform3d_ext.rs
  crates/store/re_types/tests/types/transform3d.rs
  docs/snippets/all/archetypes/transform3d_axes.rs
Labels: 🦀 Rust API, exclude from changelog

#8666 Add `archetype_native` attribute and make `ContainerBlueprint` eager + partial
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/util.rs
  crates/build/re_types_builder/src/lib.rs
  crates/build/re_types_builder/src/objects.rs
  crates/store/re_types/definitions/attributes/rust.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/background.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/container_blueprint.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/visual_bounds2d.fbs
  crates/store/re_types/src/blueprint/archetypes/background.rs
  crates/store/re_types/src/blueprint/archetypes/container_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/mod.rs
  crates/store/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
Labels: 🦀 Rust API, 🧑‍💻 dev experience, codegen/idl, exclude from changelog

#8651 gRPC spec update: define recording schema protobuf types and expose the schema via new endpoint
  Cargo.lock
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_protos/proto/rerun/v0/common.proto
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.common.v0.rs
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  examples/python/remote/metadata.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8684 Fix performance regression due to extra arrow round-tripping
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/migration.rs
  crates/store/re_chunk/src/transport.rs
Labels: 🏹 arrow, 🚀 performance, 🦟 regression, exclude from changelog

#8687 Port `TransportChunk::schema` to arrow-rs
  Cargo.lock
  crates/store/re_chunk/src/arrow.rs
  crates/store/re_chunk/src/arrow2_util.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  rerun_py/src/arrow.rs
  rerun_py/src/remote.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8688 Fix doc comment for SN client rust binding
  rerun_py/src/remote.rs
Labels: exclude from changelog

#8683 Fix flaky `re_graph_view` test by removing dynamically-placed node
  crates/viewer/re_view_graph/Cargo.toml
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_graph/tests/snapshots/self_and_multi_edges.png
Labels: exclude from changelog

#8653 Handle empty line strips in the viewer
  Cargo.lock
  crates/utils/re_log/src/lib.rs
  crates/utils/re_log/src/setup.rs
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/context_test.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/renderer/lines.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#8694 Update `re_arrow2`
  Cargo.lock
  Cargo.toml
Labels: 🏹 arrow, dependencies, exclude from changelog

#8689 Create `re_arrow_util`
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/concat_record_batches.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/migration.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk/tests/memory_test.rs
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_format_arrow/Cargo.toml
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/example_components.rs
  crates/store/re_query/Cargo.toml
  crates/store/re_query/examples/latest_at.rs
  crates/store/re_types_core/Cargo.toml
  crates/store/re_types_core/src/tuid.rs
  crates/top/rerun_c/Cargo.toml
  crates/top/rerun_c/src/lib.rs
  crates/utils/re_arrow_util/Cargo.toml
  crates/utils/re_arrow_util/README.md
  crates/utils/re_arrow_util/src/arrow2_util.rs
  crates/utils/re_arrow_util/src/arrow_util.rs
  crates/utils/re_arrow_util/src/lib.rs
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_view_dataframe/Cargo.toml
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  rerun_py/Cargo.toml
  rerun_py/src/arrow.rs
  rerun_py/src/dataframe.rs
  rerun_py/src/remote.rs
  rerun_py/src/video.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8690 Add new `Transform3D` partial updates snippet for all languages
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/transform3d_partial_updates.cpp
  docs/snippets/all/archetypes/transform3d_partial_updates.py
  docs/snippets/all/archetypes/transform3d_partial_updates.rs
  docs/snippets/snippets.toml
  lychee.toml
Labels: 🔨 testing, examples, include in changelog, 🪵 Log & send APIs

#8696 Use insta for dataframe snapshot tests
  Cargo.lock
  crates/store/re_chunk/src/arrow.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/src/query.rs
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  rerun_py/src/remote.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8698 Respect max width of formatter when formatting ChunkStore/Chunk
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/tests/formatting.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_format_arrow/src/lib.rs
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#8699 Use full chunk table format for snapshot tests
  crates/store/re_dataframe/src/query.rs
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
Labels: 🔨 testing, exclude from changelog

#8702 Remove unused `num_instances()` method
  docs/content/reference/migration/migration-0-22.md
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates_ext.py
Labels: 🐍 Python API, include in changelog

#8700 Port `TransportChunk` to `arrow-rs`
  Cargo.lock
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/arrow.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/concat_record_batches.rs
  crates/store/re_chunk/src/lib.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/Cargo.toml
  crates/store/re_dataframe/examples/query.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/lib.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_log_types/src/arrow_msg.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/lib.rs
  docs/snippets/all/reference/dataframe_query.rs
  examples/rust/dataframe_query/src/main.rs
  rerun_py/Cargo.toml
  rerun_py/src/dataframe.rs
  rerun_py/src/remote.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8707 Less use of `TransportChunk`
  crates/store/re_chunk/src/transport.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_log_encoding/src/codec/wire/decoder.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  crates/store/re_log_types/Cargo.toml
  rerun_py/src/remote.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8717 Move the blueprint saving logic to `re_viewer_blueprint`
  Cargo.lock
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewport/Cargo.toml
  crates/viewer/re_viewport/src/lib.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/auto_layout.rs
  crates/viewer/re_viewport_blueprint/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 🔨 testing, 🚜 refactor, exclude from changelog

#8720 Add missing feature flags to arrow2, to fix CI
  crates/utils/re_arrow_util/Cargo.toml
Labels: exclude from changelog

#8718 Add `any_values` and `extra_values` snippets for rust
  docs/snippets/INDEX.md
  docs/snippets/all/tutorials/any_values.rs
  docs/snippets/all/tutorials/extra_values.py
  docs/snippets/all/tutorials/extra_values.rs
  docs/snippets/snippets.toml
  lychee.toml
Labels: 🦀 Rust API, include in changelog, 🪵 Log & send APIs

#8708 doc: Update `annotation-context.rs` to use correct API
  docs/content/concepts/annotation-context.md
  docs/snippets/all/tutorials/annotation-context.rs
  docs/snippets/all/tutorials/annotation_context.cpp
  docs/snippets/all/tutorials/annotation_context.py
  docs/snippets/all/tutorials/annotation_context.rs
  docs/snippets/snippets.toml
Labels: 📖 documentation, include in changelog

#8721 Pin ci machines with Vulkan setup to Ubuntu 22.04
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks_rust.yml
  crates/utils/re_video/src/decode/mod.rs
Labels: exclude from changelog, :ship: CI

#8722 Fix CI
  docs/snippets/INDEX.md
Labels: 🪳 bug, exclude from changelog, :ship: CI

#8710 define Catalog fields name in the protobuf spec crate and use them in the catalog view
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_protos/src/lib.rs
Labels: exclude from changelog, remote-store

#8705 Add support for asynchronous decoding of rrd stream
  Cargo.lock
  Cargo.toml
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/codec/file/mod.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/lib.rs
Labels: exclude from changelog

#8734 Fix link to ARFlow `client` and feature gate serialization `const`s
  crates/store/re_log_types/src/arrow_msg.rs
  examples/python/arflow/README.md
Labels: exclude from changelog

#8627 Basic JWT-based authentication and authorization
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/utils/re_auth/Cargo.toml
  crates/utils/re_auth/README.md
  crates/utils/re_auth/src/error.rs
  crates/utils/re_auth/src/lib.rs
  crates/utils/re_auth/src/provider.rs
  crates/utils/re_auth/src/service/client.rs
  crates/utils/re_auth/src/service/mod.rs
  crates/utils/re_auth/src/service/server.rs
  crates/utils/re_auth/src/token.rs
  crates/utils/re_auth/src/user.rs
  crates/utils/re_auth/tests/tokens.rs
Labels: exclude from changelog, dataplatform

#8739 Store: get rid of `query_id`
  crates/store/re_chunk_store/src/gc.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/src/stats.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/writes.rs
Labels: ⛃ re_datastore, 🚜 refactor, exclude from changelog

#8738 Draw nodes above edges in graph view
  crates/viewer/re_view_graph/src/ui/draw.rs
Labels: ui, include in changelog

#8500 Reenable tagging post-0.21 release
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_types_core/src/component_descriptor.rs
  docs/snippets/all/descriptors/descr_builtin_archetype.rs
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  docs/snippets/all/descriptors/descr_custom_component.rs
  docs/snippets/snippets.toml
  rerun_py/tests/unit/test_dataframe.py
Labels: ⛃ re_datastore, exclude from changelog, 🪵 Log & send APIs

#8747 Use serde to encode arrow datatype
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_protos/proto/rerun/v0/common.proto
  crates/store/re_protos/src/v0/rerun.common.v0.rs
Labels: exclude from changelog, dataplatform

#8742 Finally get rid of all the long-deprecated 'timeless' stuff
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk_store/tests/correctness.rs
  crates/store/re_entity_db/src/entity_tree.rs
  crates/store/re_entity_db/src/time_histogram_per_timeline.rs
  crates/store/re_log_types/src/time_point/time_int.rs
  crates/store/re_query/tests/latest_at.rs
  crates/store/re_query/tests/range.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  docs/content/concepts/annotation-context.md
  docs/content/getting-started/configure-the-viewer/through-code-tutorial.md
  docs/content/howto/integrations/ros2-nav-turtlebot.md
  examples/README.md
  examples/cpp/external_data_loader/main.cpp
  examples/cpp/ros2_bridge/README.md
  examples/cpp/ros_bridge/README.md
  examples/cpp/vrs/README.md
  examples/python/arkit_scenes/README.md
  examples/python/blueprint_stocks/blueprint_stocks.py
  examples/python/clock/README.md
  examples/python/controlnet/README.md
  examples/python/detect_and_track_objects/README.md
  examples/python/external_data_loader/rerun-loader-python-file.py
  examples/python/face_tracking/README.md
  examples/python/human_pose_tracking/README.md
  examples/python/live_depth_sensor/README.md
  examples/python/nuscenes_dataset/README.md
  examples/python/nuscenes_dataset/nuscenes_dataset/__main__.py
  examples/python/objectron/README.md
  examples/python/open_photogrammetry_format/README.md
  examples/python/open_photogrammetry_format/open_photogrammetry_format.py
  examples/python/plots/README.md
  examples/python/raw_mesh/raw_mesh/__main__.py
  examples/python/rgbd/rgbd.py
  examples/python/rrt_star/rrt_star.py
  examples/python/segment_anything_model/segment_anything_model.py
  examples/python/signed_distance_fields/README.md
  examples/rust/external_data_loader/src/main.rs
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/recording_stream.cpp
  rerun_py/rerun_sdk/rerun/_log.py
  tests/python/release_checklist/check_1d_tensor_data.py
  tests/python/release_checklist/check_bgr.py
  tests/python/release_checklist/check_blueprint_bw_compat.py
  tests/python/release_checklist/check_chroma_subsampling.py
  tests/python/release_checklist/check_component_and_transform_clamping.py
  tests/python/release_checklist/check_container_hierarchy.py
  tests/python/release_checklist/check_deselect_on_escape.py
  tests/python/release_checklist/check_draw_order.py
  tests/python/release_checklist/check_heuristics_mixed_all_root.py
  tests/python/release_checklist/check_modal_scrolling.py
  tests/python/release_checklist/check_notebook.py
  tests/python/release_checklist/check_out_of_tree_data_results.py
  tests/python/release_checklist/check_parallelism_caching_reentrancy.py
  tests/python/release_checklist/check_plot_overrides.py
  tests/python/release_checklist/check_rbl_import.py
  tests/python/release_checklist/check_static_override.py
  tests/python/release_checklist/check_transform3d_hierarchy.py
  tests/python/release_checklist/check_version.py
  tests/python/release_checklist/check_video.py
Labels: 🚜 refactor, exclude from changelog

#8743 Update wgpu to 24.0.0
  Cargo.lock
  Cargo.toml
  crates/build/re_dev_tools/src/build_web_viewer/lib.rs
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/viewer/re_renderer/src/allocator/data_texture_source.rs
  crates/viewer/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/viewer/re_renderer/src/config.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/context_test.rs
  crates/viewer/re_renderer/src/draw_phases/picking_layer.rs
  crates/viewer/re_renderer/src/draw_phases/screenshot.rs
  crates/viewer/re_renderer/src/error_handling/error_tracker.rs
  crates/viewer/re_renderer/src/error_handling/wgpu_core_error.rs
  crates/viewer/re_renderer/src/error_handling/wgpu_error_scope.rs
  crates/viewer/re_renderer/src/resource_managers/texture_manager.rs
  crates/viewer/re_renderer/src/video/chunk_decoder.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_view_spatial/src/picking_ui_pixel.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: dependencies, include in changelog, wasm-bindgen version update

#8762 Move and document `DataResultNodeOrPath`
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_blueprint_tree/src/data_result_node_or_path.rs
  crates/viewer/re_blueprint_tree/src/lib.rs
  crates/viewer/re_viewer_context/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#8728 Filter entities in the UI (part 5): Add snapshot tests for the blueprint tree
  Cargo.lock
  crates/store/re_log_types/src/path/entity_path_filter.rs
  crates/viewer/re_blueprint_tree/Cargo.toml
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_blueprint_tree/tests/blueprint_tree_tests.rs
  crates/viewer/re_blueprint_tree/tests/snapshots/basic_blueprint_panel.png
  crates/viewer/re_blueprint_tree/tests/snapshots/blueprint_panel_filter_active_above_origin.png
  crates/viewer/re_blueprint_tree/tests/snapshots/blueprint_panel_filter_active_inside_origin.png
  crates/viewer/re_blueprint_tree/tests/snapshots/blueprint_panel_filter_active_outside_origin.png
  crates/viewer/re_blueprint_tree/tests/snapshots/collapse_all_blueprint_panel.png
  crates/viewer/re_blueprint_tree/tests/snapshots/expand_all_blueprint_panel.png
  crates/viewer/re_view_graph/Cargo.toml
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_viewer_context/src/query_context.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/view_class_registry.rs
  crates/viewer/re_viewport_blueprint/Cargo.toml
  crates/viewer/re_viewport_blueprint/src/lib.rs
  crates/viewer/re_viewport_blueprint/src/test_context_ext.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: ui, include in changelog

#8767 Rename "applicable" to "maybe visualizable" and adjust various docs accordingly
  crates/viewer/re_context_menu/src/actions/add_entities_to_new_view.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/heuristics.rs
  crates/viewer/re_view/src/lib.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_bar_chart/src/visualizer_system.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_spatial/src/heuristics.rs
  crates/viewer/re_view_spatial/src/spatial_topology.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/typed_entity_collections.rs
  crates/viewer/re_viewer_context/src/view/mod.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class_registry.rs
  crates/viewer/re_viewer_context/src/view/visualizer_entity_subscriber.rs
  crates/viewer/re_viewer_context/src/view/visualizer_system.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
  crates/viewer/re_viewport_blueprint/src/entity_add_info.rs
  crates/viewer/re_viewport_blueprint/src/test_context_ext.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
Labels: 🚜 refactor, exclude from changelog

#8773 fix machine name on rust contributor ci
  .github/workflows/contrib_checks.yml
Labels: exclude from changelog, :ship: CI

#8772 `rs-checks`: continue on failure
  Cargo.toml
  crates/build/re_dev_tools/Cargo.toml
  crates/store/re_types_core/Cargo.toml
  pixi.toml
  scripts/ci/rust_checks.py
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#8765 Handle static transforms in the transform cache & add tests for these cases
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
Labels: 🦟 regression, exclude from changelog

#8769 Make tagged columnar updates work with mono-components too
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/store/re_types/src/archetypes/arrows2d.rs
  crates/store/re_types/src/archetypes/arrows3d.rs
  crates/store/re_types/src/archetypes/bar_chart.rs
  crates/store/re_types/src/archetypes/capsules3d.rs
  crates/store/re_types/src/archetypes/depth_image.rs
  crates/store/re_types/src/archetypes/ellipsoids3d.rs
  crates/store/re_types/src/archetypes/encoded_image.rs
  crates/store/re_types/src/archetypes/graph_edges.rs
  crates/store/re_types/src/archetypes/graph_nodes.rs
  crates/store/re_types/src/archetypes/line_strips2d.rs
  crates/store/re_types/src/archetypes/line_strips3d.rs
  crates/store/re_types/src/archetypes/points2d.rs
  crates/store/re_types/src/archetypes/points3d.rs
  crates/store/re_types/src/archetypes/scalar.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/archetypes/series_line.rs
  crates/store/re_types/src/archetypes/series_point.rs
  crates/store/re_types/src/archetypes/text_document.rs
  crates/store/re_types/src/archetypes/text_log.rs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/store/re_types_core/src/archetypes/clear.rs
  docs/snippets/all/archetypes/scalar_send_columns.cpp
  docs/snippets/all/archetypes/scalar_send_columns.py
  docs/snippets/all/archetypes/scalar_send_columns.rs
  docs/snippets/snippets.toml
Labels: enhancement, 🦀 Rust API, exclude from changelog, 🔩 data model

#8774 Fix typo in rust_checks.py
  scripts/ci/rust_checks.py
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#8771 Columnar APIs: do not autogenerate indicator for `Scalar`
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/store/re_types/src/archetypes/scalar.rs
  docs/snippets/all/archetypes/scalar_send_columns.rs
Labels: 🦀 Rust API, 🚀 performance, 🍏 primitives, exclude from changelog, 🔩 data model

#8709 Implement gRPC log sink
  Cargo.lock
  Cargo.toml
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/message_proxy.rs
  crates/top/re_sdk/Cargo.toml
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/rerun/Cargo.toml
  rerun_notebook/package-lock.json
  rerun_py/Cargo.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: include in changelog, 🪵 Log & send APIs, remote-store

#8732 resolve clippy::unwrap_used in re_types_core
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/tuid.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#8730 Implement gRPC log stream
  Cargo.lock
  Cargo.toml
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/message_proxy.rs
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_server/Cargo.toml
  crates/store/re_grpc_server/src/main.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer/src/web_tools.rs
Labels: include in changelog, 🪵 Log & send APIs, remote-store

#8783 Fix `cargo t --all --all-features`
  crates/top/re_sdk/src/log_sink.rs
Labels: 🔨 testing, exclude from changelog

#8782 Forbid compaction of tagged+untagged data for a single component
  crates/store/re_chunk/src/merge.rs
Labels: 🪳 bug, 🏹 arrow, ⛃ re_datastore, exclude from changelog, 🔩 data model

#8775 Columnar APIs: autogenerate helpers for unit-length batches
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/store/re_types/src/archetypes/arrows2d.rs
  crates/store/re_types/src/archetypes/arrows3d.rs
  crates/store/re_types/src/archetypes/bar_chart.rs
  crates/store/re_types/src/archetypes/capsules3d.rs
  crates/store/re_types/src/archetypes/depth_image.rs
  crates/store/re_types/src/archetypes/ellipsoids3d.rs
  crates/store/re_types/src/archetypes/encoded_image.rs
  crates/store/re_types/src/archetypes/geo_line_strings.rs
  crates/store/re_types/src/archetypes/geo_points.rs
  crates/store/re_types/src/archetypes/graph_edges.rs
  crates/store/re_types/src/archetypes/graph_nodes.rs
  crates/store/re_types/src/archetypes/instance_poses3d.rs
  crates/store/re_types/src/archetypes/line_strips2d.rs
  crates/store/re_types/src/archetypes/line_strips3d.rs
  crates/store/re_types/src/archetypes/points2d.rs
  crates/store/re_types/src/archetypes/points3d.rs
  crates/store/re_types/src/archetypes/scalar.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/archetypes/series_line.rs
  crates/store/re_types/src/archetypes/series_point.rs
  crates/store/re_types/src/archetypes/text_document.rs
  crates/store/re_types/src/archetypes/text_log.rs
  crates/store/re_types/src/archetypes/transform3d.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/store/re_types/src/blueprint/archetypes/background.rs
  crates/store/re_types/src/blueprint/archetypes/container_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/dataframe_query.rs
  crates/store/re_types/src/blueprint/archetypes/force_center.rs
  crates/store/re_types/src/blueprint/archetypes/force_collision_radius.rs
  crates/store/re_types/src/blueprint/archetypes/force_link.rs
  crates/store/re_types/src/blueprint/archetypes/force_many_body.rs
  crates/store/re_types/src/blueprint/archetypes/force_position.rs
  crates/store/re_types/src/blueprint/archetypes/line_grid3d.rs
  crates/store/re_types/src/blueprint/archetypes/map_background.rs
  crates/store/re_types/src/blueprint/archetypes/map_zoom.rs
  crates/store/re_types/src/blueprint/archetypes/near_clip_plane.rs
  crates/store/re_types/src/blueprint/archetypes/panel_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/plot_legend.rs
  crates/store/re_types/src/blueprint/archetypes/scalar_axis.rs
  crates/store/re_types/src/blueprint/archetypes/tensor_scalar_mapping.rs
  crates/store/re_types/src/blueprint/archetypes/tensor_slice_selection.rs
  crates/store/re_types/src/blueprint/archetypes/tensor_view_fit.rs
  crates/store/re_types/src/blueprint/archetypes/view_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/view_contents.rs
  crates/store/re_types/src/blueprint/archetypes/viewport_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/visible_time_ranges.rs
  crates/store/re_types/src/blueprint/archetypes/visual_bounds2d.rs
  crates/store/re_types_core/src/archetypes/clear.rs
  docs/snippets/all/archetypes/points3d_send_columns.rs
  docs/snippets/all/archetypes/scalar_send_columns.rs
Labels: enhancement, 🦀 Rust API, exclude from changelog

#8778 Add Rust snippets for columnar updates of custom data
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  docs/snippets/INDEX.md
  docs/snippets/all/howto/any_batch_value_send_columns.rs
  docs/snippets/all/howto/any_values_send_columns.rs
  docs/snippets/all/tutorials/custom_data.py
  docs/snippets/snippets.toml
  lychee.toml
Labels: 📖 documentation, 🦀 Rust API, examples, exclude from changelog

#8787 Update to latest egui master
  Cargo.lock
  Cargo.toml
  crates/viewer/re_viewer/src/web_tools.rs
  deny.toml
  scripts/ci/rust_checks.py
Labels: dependencies, exclude from changelog, egui

#8786 Fix Python bridge losing descriptor/tags information during transit
  rerun_py/src/arrow.rs
  rerun_py/src/video.rs
Labels: 🪳 bug, 🐍 Python API, 🏹 arrow, exclude from changelog, 🔩 data model

#8794 Fix clicking of links in markdown
  crates/viewer/re_view_text_document/src/view_class.rs
Labels: 🪳 bug, ui, 📺 re_viewer, 🦟 regression, include in changelog, egui

#8789 Make `Pinhole` archetype in Rust eager serialized
  crates/store/re_types/definitions/rerun/archetypes/pinhole.fbs
  crates/store/re_types/src/archetypes/pinhole.rs
  crates/store/re_types/src/archetypes/pinhole_ext.rs
  crates/store/re_types/src/components/pinhole_projection_ext.rs
  crates/store/re_types/src/components/resolution_ext.rs
  crates/store/re_types/tests/types/pinhole.rs
  crates/viewer/re_view_spatial/src/eye.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/pinhole.rs
  crates/viewer/re_view_spatial/src/space_camera_3d.rs
  crates/viewer/re_view_spatial/src/ui.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/view_2d_properties.rs
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
Labels: 🦀 Rust API, include in changelog

#8796 Update to re_arrow2 0.18.2
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog

#8791 Fix warnings when using pixi 0.40.x
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#8793 Make `Image` & `Mesh3D` archetypes in Rust eager serialized
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  crates/store/re_types/definitions/rerun/archetypes/mesh3d.fbs
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/archetypes/mesh3d.rs
  crates/store/re_types/src/archetypes/mesh3d_ext.rs
  crates/store/re_types/src/components/image_buffer_ext.rs
  crates/store/re_types/src/components/image_format_ext.rs
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/datatypes/blob_ext.rs
  crates/store/re_types/src/datatypes/image_format_ext.rs
  crates/store/re_types/tests/types/mesh3d.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/mesh_cache.rs
  crates/viewer/re_view_spatial/src/mesh_loader.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/image_info.rs
Labels: 🦀 Rust API, include in changelog

#8801 Make rust `Tensor` archetype eager serialized
  Cargo.lock
  crates/store/re_types/Cargo.toml
  crates/store/re_types/definitions/rerun/archetypes/tensor.fbs
  crates/store/re_types/src/archetypes/tensor.rs
  crates/store/re_types/src/archetypes/tensor_ext.rs
  crates/store/re_types/tests/types/tensor.rs
  docs/content/reference/migration/migration-0-22.md
  rerun_cpp/src/rerun/archetypes/tensor_ext.cpp
Labels: 🦀 Rust API, include in changelog

#8803 export ComponentName from re_dataframe
  crates/store/re_dataframe/src/lib.rs
Labels: exclude from changelog, feat-dataframe-api

#8800 Update wgpu 24.0.0->24.0.1
  Cargo.lock
  Cargo.toml
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/video/chunk_decoder.rs
Labels: dependencies, exclude from changelog

#8805 Fix regression in container blueprint saving
  crates/viewer/re_viewport_blueprint/src/container.rs
Labels: 🦟 regression, 🟦 blueprint, exclude from changelog

#8807 Fix mesh casting color components incorrectly
  crates/viewer/re_view_spatial/src/mesh_loader.rs
Labels: 🦟 regression, exclude from changelog

#8813 Move `Time/ComponentColumnDescriptor` to new `re_sorbet`
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_log_types/src/time_point/mod.rs
  crates/store/re_sorbet/Cargo.toml
  crates/store/re_sorbet/README.md
  crates/store/re_sorbet/src/data_column_schema.rs
  crates/store/re_sorbet/src/index_column_schema.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/metadata.rs
  rerun_py/src/arrow.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8804 Rust: remove legacy `send_columns` and update everything left
  crates/store/re_types/src/archetypes/asset_video.rs
  crates/store/re_types/src/archetypes/points3d.rs
  crates/store/re_types/src/archetypes/scalar.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/top/re_sdk/src/recording_stream.rs
  docs/snippets/all/archetypes/image_send_columns.rs
  docs/snippets/all/archetypes/points3d_send_columns.rs
  docs/snippets/all/archetypes/scalar_send_columns.rs
  docs/snippets/all/archetypes/video_auto_frames.rs
  docs/snippets/all/howto/any_batch_value_send_columns.rs
  docs/snippets/all/howto/any_values_send_columns.rs
  examples/rust/incremental_logging/src/main.rs
  tests/rust/plot_dashboard_stress/src/main.rs
  tests/rust/test_temporal_batch/src/main.rs
Labels: 🦀 Rust API, include in changelog, 🔩 data model

#8792 Tagged columnar updates: Python
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/objects.rs
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/points3d_send_columns.py
  docs/snippets/all/archetypes/scalar_send_columns.py
  docs/snippets/all/howto/any_batch_value_send_columns.py
  docs/snippets/all/howto/any_values_send_columns.py
  docs/snippets/snippets.toml
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
Labels: 🐍 Python API, include in changelog, 🔩 data model

#8810 Fix CPU spike caused by hanging connection after socket closure (#8806)
  crates/utils/re_smart_channel/src/receive_set.rs
Labels: 🪳 bug, 🕸️ web, include in changelog, 🪵 Log & send APIs

#8818 Remove component-driven sections from snippet index
  crates/build/re_types_builder/src/codegen/docs/snippets_ref.rs
  docs/snippets/INDEX.md
Labels: 📖 documentation, examples, exclude from changelog

#8809 Include a python API for routing time control commands to the notebook instance
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🐍 Python API, notebook, include in changelog

#8832 Add hint for missing web viewer when building `re_web_viewer_server`
  crates/viewer/re_web_viewer_server/build.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#8830 Fix python Windows unicode issues (maybe)
  crates/viewer/re_viewer_context/src/typed_entity_collections.rs
  scripts/ci/rust_checks.py
Labels: exclude from changelog, :ship: CI

#8834 Disable web viewer file check in ci
  crates/viewer/re_web_viewer_server/build.rs
Labels: exclude from changelog, :ship: CI

#8833 Always split indicators into their own dedicated chunks
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_types/src/archetypes/scalar.rs
  docs/snippets/all/descriptors/descr_builtin_archetype.rs
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
Labels: ⛃ re_datastore, 🚀 performance, exclude from changelog, 🔩 data model, 🪵 Log & send APIs

#8808 Improve performance for Blueprint & Streams Panel for many entities
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
Labels: ui, 🚀 performance, include in changelog

#8836 Add `with_many_` variants for C++ archetype mono fields & port remaining snippets
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  docs/content/reference/migration/migration-0-22.md
  docs/snippets/all/archetypes/image_send_columns.cpp
  docs/snippets/all/archetypes/points3d_send_columns.cpp
  docs/snippets/all/archetypes/scalar_send_columns.cpp
  docs/snippets/all/archetypes/video_auto_frames.cpp
  docs/snippets/snippets.toml
  rerun_cpp/src/rerun/archetypes/annotation_context.hpp
  rerun_cpp/src/rerun/archetypes/arrows2d.hpp
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
  rerun_cpp/src/rerun/archetypes/asset3d.hpp
  rerun_cpp/src/rerun/archetypes/asset_video.hpp
  rerun_cpp/src/rerun/archetypes/bar_chart.hpp
  rerun_cpp/src/rerun/archetypes/boxes2d.hpp
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/capsules3d.hpp
  rerun_cpp/src/rerun/archetypes/clear.hpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/ellipsoids3d.hpp
  rerun_cpp/src/rerun/archetypes/encoded_image.hpp
  rerun_cpp/src/rerun/archetypes/graph_edges.hpp
  rerun_cpp/src/rerun/archetypes/graph_nodes.hpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/line_strips3d.hpp
  rerun_cpp/src/rerun/archetypes/mesh3d.hpp
  rerun_cpp/src/rerun/archetypes/pinhole.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/points3d.hpp
  rerun_cpp/src/rerun/archetypes/scalar.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_cpp/src/rerun/archetypes/tensor.hpp
  rerun_cpp/src/rerun/archetypes/text_document.hpp
  rerun_cpp/src/rerun/archetypes/text_log.hpp
  rerun_cpp/src/rerun/archetypes/transform3d.hpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.hpp
  rerun_cpp/src/rerun/archetypes/view_coordinates.hpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer1.hpp
  rerun_cpp/tests/generated/archetypes/affix_fuzzer3.hpp
  tests/cpp/plot_dashboard_stress/main.cpp
Labels: 🌊 C++ API, include in changelog

#8799 Python: remove legacy `send_columns` and update everything left
  crates/store/re_types/definitions/rerun/components/video_timestamp.fbs
  crates/store/re_types/definitions/rerun/datatypes/video_timestamp.fbs
  docs/content/getting-started/data-out/analyze-and-send.md
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/image_send_columns.py
  docs/snippets/all/archetypes/mesh3d_partial_updates.py
  docs/snippets/all/archetypes/points3d_partial_updates_legacy.cpp
  docs/snippets/all/archetypes/points3d_partial_updates_legacy.py
  docs/snippets/all/archetypes/points3d_partial_updates_legacy.rs
  docs/snippets/all/archetypes/points3d_send_columns.py
  docs/snippets/all/archetypes/scalar_send_columns.py
  docs/snippets/all/archetypes/video_auto_frames.py
  docs/snippets/all/concepts/static/send_static.py
  docs/snippets/all/howto/any_batch_value_send_columns.py
  docs/snippets/all/howto/any_values_send_columns.py
  docs/snippets/all/tutorials/data_out.py
  docs/snippets/snippets.toml
  examples/python/air_traffic_data/air_traffic_data.py
  examples/python/drone_lidar/drone_lidar.py
  examples/python/incremental_logging/incremental_logging.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_send_columns.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/video_timestamp.py
  tests/python/chunk_zoo/chunk_zoo.py
  tests/python/chunked_video/chunked_video.py
  tests/python/log_benchmark/test_log_benchmark.py
  tests/python/plot_dashboard_stress/main.py
  tests/python/release_checklist/check_drag_and_drop_selection.py
  tests/python/release_checklist/check_entity_drag_and_drop.py
  tests/python/release_checklist/check_multi_entity_drag_and_drop.py
  tests/python/release_checklist/check_video.py
Labels: 🐍 Python API, include in changelog, 🔩 data model

#8821 Use Arrow IPC to encode the column schema
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/src/protobuf_conversions.rs
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/lib.rs
  crates/store/re_log_types/src/protobuf_conversions.rs
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/README.md
  crates/store/re_protos/proto/rerun/v0/common.proto
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/protobuf_conversions/arrow.rs
  crates/store/re_protos/src/protobuf_conversions/log_types.rs
  crates/store/re_protos/src/protobuf_conversions/mod.rs
  crates/store/re_protos/src/protobuf_conversions/tuid.rs
  crates/store/re_protos/src/v0/rerun.common.v0.rs
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/column_schema.rs
  crates/store/re_sorbet/src/data_column_schema.rs
  crates/store/re_sorbet/src/index_column_schema.rs
  crates/store/re_sorbet/src/ipc.rs
  crates/store/re_sorbet/src/lib.rs
  crates/utils/re_tuid/Cargo.toml
  crates/utils/re_tuid/src/lib.rs
  crates/utils/re_tuid/src/protobuf_conversions.rs
  rerun_py/Cargo.toml
  rerun_py/rerun_sdk/rerun/dataframe.py
  rerun_py/src/remote.rs
  rerun_py/tests/unit/test_dataframe.py
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog, dataplatform

#8839 The empty/full entity icon now reflects presence of component on the current timeline
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/viewer/re_blueprint_tree/tests/blueprint_tree_tests.rs
  crates/viewer/re_blueprint_tree/tests/view_structure_test.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: ui, include in changelog

#8845 Fix formatting in Python SDK LineStrip2D/3D
  rerun_py/rerun_sdk/rerun/components/geo_line_string_ext.py
  rerun_py/rerun_sdk/rerun/components/line_strip2d_ext.py
  rerun_py/rerun_sdk/rerun/components/line_strip3d_ext.py
Labels: 🪳 bug, 🐍 Python API, exclude from changelog

#8843 Order-agnostic `rrd compare` command + snippet clean up
  crates/top/rerun/src/commands/rrd/compare.rs
  docs/snippets/all/archetypes/image_send_columns.cpp
  docs/snippets/all/archetypes/image_send_columns.py
  docs/snippets/all/archetypes/image_send_columns.rs
  docs/snippets/all/archetypes/mesh3d_partial_updates.cpp
  docs/snippets/snippets.toml
  scripts/roundtrip_utils.py
Labels: enhancement, 🔨 testing, exclude from changelog, :ship: CI

#8846 Remove indicators from custom data examples
  docs/snippets/all/descriptors/descr_custom_archetype.cpp
  docs/snippets/all/descriptors/descr_custom_archetype.py
  docs/snippets/all/descriptors/descr_custom_archetype.rs
  docs/snippets/all/tutorials/custom_data.cpp
  docs/snippets/all/tutorials/custom_data.py
  docs/snippets/all/tutorials/custom_data.rs
Labels: 📖 documentation, enhancement, examples, exclude from changelog

#8849 Python: untagged-resistant APIs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/store/re_types_core/src/archetype.rs
  docs/content/howto/logging/custom-data.md
  docs/snippets/all/descriptors/descr_custom_archetype.py
  docs/snippets/all/tutorials/custom_data.py
  docs/snippets/snippets.toml
  examples/python/openstreetmap_data/openstreetmap_data.py
  examples/python/plots/plots.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/any_value.py
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/rerun_sdk/rerun/components/view_coordinates_ext.py
  rerun_py/rerun_sdk/rerun/datatypes/class_description_ext.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
Labels: 🐍 Python API, exclude from changelog, 🔩 data model

#8862 Fix failing nightly
  crates/viewer/re_blueprint_tree/Cargo.toml
  docs/snippets/all/tutorials/custom_data.rs
Labels: exclude from changelog, :ship: CI

#8847 Convert graph view to `egui::Scene`
  Cargo.lock
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/zoom_pan_area.rs
  crates/viewer/re_view_graph/src/properties.rs
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/ui/state.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_graph/tests/snapshots/coincident_nodes.png
  crates/viewer/re_view_graph/tests/snapshots/self_and_multi_edges.png
Labels: exclude from changelog

#8867 Fix rounding issue in snippet comparision
  docs/snippets/all/archetypes/arrows3d_simple.cpp
Labels: 🔨 testing, exclude from changelog

#8853 Require descriptors to be provided on all log calls in C++ (either explicitely or implicitely via archetype)
  docs/content/reference/migration/migration-0-22.md
  docs/snippets/all/concepts/different_data_per_timeline.cpp
  docs/snippets/all/descriptors/descr_builtin_component.cpp
  docs/snippets/all/descriptors/descr_custom_component.cpp
  examples/cpp/incremental_logging/main.cpp
  rerun_cpp/src/rerun/as_components.hpp
  rerun_cpp/src/rerun/component_batch.hpp
  rerun_cpp/src/rerun/component_column.hpp
  rerun_cpp/src/rerun/recording_stream.hpp
  rerun_cpp/tests/log_empty.cpp
  rerun_cpp/tests/recording_stream.cpp
Labels: 🌊 C++ API, include in changelog

#8856 Fix cameras with unknown resolution showing
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
Labels: 🦟 regression, exclude from changelog

#8868 Run codegen
  rerun_cpp/src/rerun/archetypes/arrows3d.hpp
Labels: exclude from changelog, :ship: CI

#8861 Show start of large arrow values instead of just their size
  .gitignore
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/store/re_format_arrow/src/lib.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/VisibleTimeRange_placeholder.png
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_ui/tests/snapshots/arrow_ui.png
Labels: ui, 🏹 arrow, include in changelog

#8854 Make it possible to change the contents of a view multiple times per frame
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 🪳 bug, ui, include in changelog

#8863 Filter entities in the UI (part 7): Refactor and optimize `re_time_panel` and add more tests
  Cargo.lock
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_time_panel/Cargo.toml
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
  crates/viewer/re_time_panel/src/time_axis.rs
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_active_query.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_9223372036854775807.png
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: ui, 🚜 refactor, include in changelog

#8864 Clickable URLs in named components / `AnyValues`
  Cargo.lock
  crates/viewer/re_component_ui/src/datatype_uis/mod.rs
  crates/viewer/re_component_ui/src/datatype_uis/singleline_string.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_empty_array_any_value_empty_array.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_large_blob_any_value_large_blob.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_small_array_any_value_small_array.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_string_any_value_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_url_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_empty_array_any_value_empty_array.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_large_blob_any_value_large_blob.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_small_array_any_value_small_array.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_string_any_value_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_url_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_ui_registry.rs
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_ui/src/ui_layout.rs
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
  docs/content/howto/logging/custom-data.md
  docs/snippets/all/tutorials/any_values.py
  docs/snippets/all/tutorials/any_values.rs
  rerun_py/rerun_sdk/rerun/any_value.py
Labels: enhancement, ui, include in changelog

#8870 Implement range selection with shift-click in the time panel
  Cargo.lock
  crates/viewer/re_time_panel/Cargo.toml
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
Labels: ui, include in changelog

#8873 `re_time_panel`: no longer cram everything in `lib.rs`
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/lib.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
  crates/viewer/re_time_panel/src/time_panel.rs
Labels: 🚜 refactor, exclude from changelog
