Repository rerun-io/rerun, pull requests merged in 2025-05, with the labels that each got.

#9854 Properly resolve component selectors in dataset index creation and search APIs
  crates/store/re_log_types/src/path/mod.rs
  crates/store/re_log_types/src/path/parse_path.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_sorbet/src/column_descriptor_ref.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/selectors.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/dataframe.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9850 Add note on LLVM/wasm in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#9856 Fix lint error from #9854
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/dataframe.rs
Labels: 🪳 bug, exclude from changelog

#9858 Check `.pyi` files in PRs
  .github/workflows/on_pull_request.yml
Labels: exclude from changelog, :ship: CI

#9861 Fix python formatting
  rerun_py/rerun_bindings/rerun_bindings.pyi
Labels: exclude from changelog

#9846 Improve and mitigate warnings around dataloss when flushing
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/rerun_c/src/lib.rs
Labels: include in changelog, 🪵 Log & send APIs

#9867 Fix world grid not scaling correctly when camera is below the grid
  crates/viewer/re_renderer/shader/utils/plane.wgsl
  crates/viewer/re_renderer/shader/world_grid.wgsl
Labels: 🪳 bug, 🔺 re_renderer, 📺 re_viewer, include in changelog

#9875 Fix bad error message in catalog client
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/dataframe.rs
Labels: 🐍 Python API, 🧑‍💻 dev experience, exclude from changelog

#9878 Fix incorrectly advertised minimum supported `pyarrow` version (18.0.0 is required)
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
Labels: 🪳 bug, 🐍 Python API, dependencies, include in changelog

#9880 Fix incorrectly advertised numpy 1.x support (numpy2 is required now)
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
Labels: 🪳 bug, 🐍 Python API, dependencies, include in changelog

#9871 Query cache is now aware of component tags, `latest_at` queries can opt-in to full tags
  .typos.toml
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_static.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__async_barebones_temporal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__barebones.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__clears.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_range.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__filtered_is_not_null.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-3.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__selection-4.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__sparse_fill_strategy_latestatglobal.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__using_index_values.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents-2.snap
  crates/store/re_dataframe/src/snapshots/re_dataframe__query__tests__view_contents_and_selection.snap
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/store/re_log_types/src/example_components.rs
  crates/store/re_query/benches/latest_at.rs
  crates/store/re_query/src/cache.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/range.rs
  crates/store/re_query/tests/latest_at.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/loggable.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_viewer/src/ui/memory_panel.rs
  crates/viewer/re_viewer_context/src/global_context/item.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog

#9879 RRD migration tool (for release)
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_encoding/src/legacy.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/arrow_msg.rs
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/migration.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/rrd/migrate.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
Labels: exclude from changelog

#9852 protos: support parallel partition manifest creation during dataset registration
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
Labels: exclude from changelog, dataplatform

#9877 Basic ability to show components that only differ by archetype/field name on same entity
  crates/store/re_entity_db/src/instance_path.rs
  crates/store/re_log_types/src/path/component_path.rs
  crates/store/re_log_types/src/path/data_path.rs
  crates/store/re_log_types/src/path/parse_path.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_sorbet/src/selectors.rs
  crates/store/re_types_core/src/component_descriptor.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_selection_panel/src/item_heading_no_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/tests/snapshots/focused_item_is_focused.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_path_to,_rig.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_to_the.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_to_the_.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-ath,left.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-ath,t.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-none.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-path.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-t.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the,oid.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the_.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-void.png
  crates/viewer/re_ui/src/syntax_highlighting.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/global_context/item.rs
  rerun_py/src/dataframe.rs
Labels: 📺 re_viewer, include in changelog

#9893 Temp disable schema check in `RegisterWithDataset`
  rerun_py/src/catalog/connection_handle.rs
Labels: exclude from changelog, dataplatform

#9890 Fix size check for NV12 & YUY2 formats in C++ and Rust
  crates/store/re_types/src/datatypes/pixel_format_ext.rs
  rerun_cpp/src/rerun/image_utils.hpp
Labels: 🪳 bug, 🐍 Python API, 🦀 Rust API, include in changelog

#9894 Migrate started time to recording properties
  crates/store/re_data_loader/src/load_file.rs
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/legacy.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/commands/rrd/migrate.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer_context/src/store_bundle.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
Labels: exclude from changelog

#9891 Forbid opening PRs from `main` branch of a fork
  .github/workflows/enforce_branch_name.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#9888 Use descriptors when accessing components of `ViewProperty`
  crates/store/re_query/examples/latest_at.rs
  crates/store/re_query/src/latest_at.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_graph/src/layout/params.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_tensor/src/dimension_mapping.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog

#9896 Use `ArchetypeFieldName` in `ArchetypeFieldReflection`
  crates/build/re_types_builder/src/codegen/rust/reflection.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
Labels: 🚜 refactor, exclude from changelog

#9897 Update changelog with 0.23.2
  CHANGELOG.md
Labels: exclude from changelog

#9883 Use full component descriptors optionally in ranges queries
  Cargo.lock
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_query/Cargo.toml
  crates/store/re_query/examples/latest_at.rs
  crates/store/re_query/examples/range.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/lib.rs
  crates/store/re_query/src/range.rs
  crates/store/re_query/tests/range.rs
  crates/store/re_types_core/src/result.rs
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
Labels: 🚜 refactor, exclude from changelog

#9887 Visualizers' data queries take component tags into account
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view_spatial/src/contexts/depth_offsets.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/pinhole.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/labels.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_view_text_log/src/visualizer_system.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/view/visualizer_entity_subscriber.rs
  crates/viewer/re_viewer_context/src/view/visualizer_system.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 📺 re_viewer, include in changelog

#9816 Add migration tool for legacy .rrd files
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/arrow_msg.rs
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/migration.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/rrd/migrate.rs
  crates/top/rerun/src/commands/rrd/mod.rs
  crates/top/rerun/src/commands/rrd/print.rs
Labels: include in changelog, CLI

#9899 Add `Tasks.status_table()` to expose to the tasks status and metadata
  crates/store/re_log_types/src/hash.rs
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.redap_tasks.v1alpha1.ext.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/errors.rs
  rerun_py/src/catalog/task.rs
Labels: 🐍 Python API, exclude from changelog

#9901 Store and query overrides & defaults with full `ComponentDescriptor`
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/view/view_context.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🟦 blueprint, exclude from changelog

#9904 Make `get_required_chunks` require full descriptor
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_view_text_log/src/visualizer_system.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
Labels: 🚜 refactor, exclude from changelog

#9902 create partition manifests now requires storage url and partition type
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, remote-store

#9905 Deduplicate task ids in `PyTasks`
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/task.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#9907 Introduce `Chunk(s)WithDescriptor` to avoid some descriptor passing duplication
  crates/store/re_chunk/src/iter.rs
  crates/viewer/re_view/src/chunks_with_descriptor.rs
  crates/viewer/re_view/src/lib.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_view_text_log/src/visualizer_system.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
Labels: 🚜 refactor, exclude from changelog

#9911 Use egui from `main` instead of `master`
  Cargo.lock
  Cargo.toml
Labels: dependencies, exclude from changelog, egui

#9908 Add descriptors to all remaining blueprint components
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/view/view_context.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 🚜 refactor, include in changelog

#9913 Use `MaybeTagged` as an interim solution for porting view results lookups & port map view
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/lib.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_map/src/visualizers/geo_line_strings.rs
  crates/viewer/re_view_map/src/visualizers/geo_points.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
Labels: 🚜 refactor, exclude from changelog

#9910 Replace `save_empty_blueprint_component` with `clear_blueprint_component`
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/view/view_context.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 🚜 refactor, exclude from changelog

#9914 Introduce `DisplayComponentColumn` to isolate the component column ui logic
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#9915 Use tagged lookup in `HybridResults` for all spatial view visualizers
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
Labels: 🚜 refactor, exclude from changelog

#9924 Update a typo in docs
  rerun_py/rerun_sdk/rerun/datatypes/rotation_axis_angle_ext.py
Labels: 🪳 bug, 📖 documentation, exclude from changelog

#9923 Fix notification popup instantly closing
  crates/viewer/re_ui/src/notifications.rs
  crates/viewer/re_ui/src/ui_ext.rs
Labels: 🪳 bug, ui, exclude from changelog

#9925 All queries to the query cache are now guaranteed to use tagged components
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_data_ui/src/data_source.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/labels.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_viewer/src/app_blueprint.rs
  crates/viewer/re_viewer/src/blueprint/validation.rs
  crates/viewer/re_viewer_context/src/annotations.rs
  crates/viewer/re_viewer_context/src/global_context/item.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  examples/rust/custom_view/src/color_coordinates_visualizer_system.rs
  examples/rust/extend_viewer_ui/src/main.rs
Labels: 🚜 refactor, exclude from changelog

#9919 Add `ColumnDescriptor::RowId`
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/column_descriptor_ref.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_sorbet/src/selectors.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/store/re_types/definitions/rerun/blueprint/datatypes/selected_columns.fbs
  crates/store/re_types_core/src/component_descriptor.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/dataframe.rs
Labels: exclude from changelog, 🔩 data model, feat-dataframe-view, feat-dataframe-api

#9929 Remove `MaybeTagged` accessor utility
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/src/lib.rs
  crates/store/re_query/src/range.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
Labels: 🚜 refactor, exclude from changelog

#9934 Relax `SorbetColumnDescriptors` and add `ChunkColumnDescriptors`
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/chunk_columns.rs
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/error.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/dataframe.rs
Labels: 🚜 refactor, exclude from changelog, 🔩 data model, feat-dataframe-view, feat-dataframe-api

#9916 Only trigger a datafusion update when the relevant part of the blueprint changes
  crates/viewer/re_dataframe_ui/src/datafusion_adapter.rs
Labels: 🚜 refactor, exclude from changelog

#9935 redap: support REDAP_TOKEN env var
  Cargo.lock
  Cargo.toml
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/redap/mod.rs
Labels: exclude from changelog, dataplatform

#9931 Make chunk component/slice iteration use full component descriptors
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_query/examples/range.rs
  crates/store/re_query/tests/range.rs
  crates/viewer/re_view/src/chunks_with_descriptor.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/series_query.rs
  examples/rust/custom_view/src/color_coordinates_visualizer_system.rs
Labels: 🚜 refactor, exclude from changelog

#9940 Prepare for Rust Edition 2024
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_types/src/path/entity_path.rs
  crates/store/re_sorbet/src/column_kind.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_types/src/archetypes/pinhole.rs
  crates/store/re_types/src/archetypes/points2d.rs
  crates/store/re_types/src/archetypes/tensor.rs
  crates/top/rerun/src/commands/rrd/migrate.rs
  crates/top/rerun_c/src/lib.rs
  crates/top/rerun_c/src/video.rs
  crates/utils/re_auth/src/provider.rs
  crates/utils/re_log/src/setup.rs
  crates/utils/re_uri/src/error.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_renderer_examples/picking.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_ui/src/filter_widget.rs
  crates/viewer/re_view/src/chunks_with_descriptor.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  docs/snippets/all/archetypes/pinhole_simple.rs
  docs/snippets/all/archetypes/points2d_random.rs
  docs/snippets/all/archetypes/points3d_random.rs
  docs/snippets/all/archetypes/tensor_simple.rs
  examples/rust/dna/src/main.rs
  examples/rust/objectron/build.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/dataframe.rs
  rerun_py/src/python_bridge.rs
  tests/rust/test_api/src/main.rs
  tests/rust/test_ui_wakeup/src/main.rs
Labels: 🧑‍💻 dev experience, 🚜 refactor, exclude from changelog

#9870 Series of build changes for web release to minimize generated wasm
  Cargo.toml
  crates/build/re_dev_tools/src/build_web_viewer/lib.rs
  crates/build/re_dev_tools/src/build_web_viewer/mod.rs
  pixi.toml
  rerun_js/web-viewer/build-wasm.mjs
Labels: 🕸️ web, 📉 performance, ⛴ release, include in changelog, :ship: CI

#9928 Selection ui now handles different images on the same entity path
  Cargo.lock
  crates/store/re_log_types/src/lib.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_types/src/image.rs
  crates/store/re_types_core/src/lib.rs
  crates/viewer/re_component_ui/src/fallback_ui.rs
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/component_ui_registry.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/mesh_loader.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/image_stats_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_cache.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/image_info.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: ui, 📺 re_viewer, include in changelog

#9892 Remove deprecated `Scalar`, `SeriesLine`, `SeriesPoint` archetypes
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  crates/store/re_sorbet/src/migration.rs
  crates/store/re_types/definitions/rerun/archetypes.fbs
  crates/store/re_types/definitions/rerun/archetypes/scalar.fbs
  crates/store/re_types/definitions/rerun/archetypes/series_line.fbs
  crates/store/re_types/definitions/rerun/archetypes/series_point.fbs
  crates/store/re_types/src/archetypes/.gitattributes
  crates/store/re_types/src/archetypes/mod.rs
  crates/store/re_types/src/archetypes/scalar.rs
  crates/store/re_types/src/archetypes/series_line.rs
  crates/store/re_types/src/archetypes/series_point.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  docs/content/concepts/visualizers-and-overrides.md
  docs/content/howto/integrations/ros2-nav-turtlebot.md
  docs/content/reference/migration/migration-0-13.md
  docs/content/reference/migration/migration-0-24.md
  docs/content/reference/types/archetypes.md
  docs/content/reference/types/archetypes/.gitattributes
  docs/content/reference/types/archetypes/scalar.md
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/archetypes/series_point.md
  docs/content/reference/types/components/aggregation_policy.md
  docs/content/reference/types/components/color.md
  docs/content/reference/types/components/marker_shape.md
  docs/content/reference/types/components/marker_size.md
  docs/content/reference/types/components/name.md
  docs/content/reference/types/components/scalar.md
  docs/content/reference/types/components/series_visible.md
  docs/content/reference/types/components/stroke_width.md
  docs/content/reference/types/views/time_series_view.md
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/boxes3d_simple.py
  rerun_cpp/src/rerun/archetypes.hpp
  rerun_cpp/src/rerun/archetypes/.gitattributes
  rerun_cpp/src/rerun/archetypes/scalar.cpp
  rerun_cpp/src/rerun/archetypes/scalar.hpp
  rerun_cpp/src/rerun/archetypes/series_line.cpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/archetypes/series_point.cpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/.gitattributes
  rerun_py/rerun_sdk/rerun/archetypes/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
Labels: 🍏 primitives, include in changelog, 🪵 Log & send APIs

#9932 Fix missing reference to `Spatial3DView` in `Pinhole` docs
  crates/store/re_types/definitions/rerun/archetypes/pinhole.fbs
  crates/store/re_types/src/reflection/mod.rs
  docs/content/reference/types/archetypes/pinhole.md
  docs/content/reference/types/views/spatial2d_view.md
  docs/content/reference/types/views/spatial3d_view.md
Labels: 📖 documentation, include in changelog

#9946 Add draw order to video (-frame-reference), fix 2d objects sometimes being behind videos
  crates/store/re_types/definitions/rerun/archetypes/boxes2d.fbs
  crates/store/re_types/definitions/rerun/archetypes/depth_image.fbs
  crates/store/re_types/definitions/rerun/archetypes/image.fbs
  crates/store/re_types/definitions/rerun/archetypes/line_strips2d.fbs
  crates/store/re_types/definitions/rerun/archetypes/points2d.fbs
  crates/store/re_types/definitions/rerun/archetypes/segmentation_image.fbs
  crates/store/re_types/definitions/rerun/archetypes/video_frame_reference.fbs
  crates/store/re_types/src/archetypes/boxes2d.rs
  crates/store/re_types/src/archetypes/depth_image.rs
  crates/store/re_types/src/archetypes/image.rs
  crates/store/re_types/src/archetypes/line_strips2d.rs
  crates/store/re_types/src/archetypes/points2d.rs
  crates/store/re_types/src/archetypes/segmentation_image.rs
  crates/store/re_types/src/archetypes/video_frame_reference.rs
  crates/store/re_types/src/components/draw_order_ext.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  docs/content/reference/types/archetypes/video_frame_reference.md
  docs/content/reference/types/components/draw_order.md
  rerun_cpp/src/rerun/archetypes/boxes2d.hpp
  rerun_cpp/src/rerun/archetypes/depth_image.hpp
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/line_strips2d.hpp
  rerun_cpp/src/rerun/archetypes/points2d.hpp
  rerun_cpp/src/rerun/archetypes/segmentation_image.hpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.cpp
  rerun_cpp/src/rerun/archetypes/video_frame_reference.hpp
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
Labels: 🪳 bug, 🍏 primitives, include in changelog

#9950 Fix redirect to the latest migration guide
  docs/content/reference/migration.md
  docs/content/reference/migration/migration-0-24.md
Labels: exclude from changelog

#9952 Avoid WebGPU on Safari
  crates/viewer/re_renderer/src/device_caps.rs
Labels: 🕸️ web, exclude from changelog

#9956 Fix crash in MaxImageDimensionSubscriber
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
Labels: 🪳 bug, exclude from changelog

#9957 Fix scalar loading for LeRobot
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: 🪳 bug, exclude from changelog

#9958 LeRobot: Add support for List datatype
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: include in changelog

#9959 Fix broken python boxes3d snippet
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/boxes3d_simple.py
Labels: 🪳 bug, exclude from changelog

#9961 Refactor in preparation for supporting light mode
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/context_ext.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/help.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
  crates/viewer/re_ui/src/notifications.rs
  crates/viewer/re_ui/src/section_collapsing_header.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_view_spatial/src/view_2d_properties.rs
  crates/viewer/re_view_spatial/src/view_3d_properties.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/ui/mobile_warning_ui.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer_context/src/drag_and_drop.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  crates/viewer/re_viewport_blueprint/src/ui/add_view_or_container_modal.rs
Labels: ui, 📺 re_viewer, 🚜 refactor, exclude from changelog

#9964 Spelling consistency: grey -> gray
  .typos.toml
  CHANGELOG.md
  crates/utils/re_video/src/decode/mod.rs
  rerun_cpp/src/rerun/archetypes/image.hpp
  rerun_cpp/src/rerun/archetypes/image_ext.cpp
  rerun_cpp/tests/archetypes/image.cpp
  tests/python/release_checklist/check_chroma_subsampling.py
Labels: 📖 documentation, 🧑‍💻 dev experience, 🌊 C++ API, exclude from changelog

#9966 Fix building with arrow 20.0.0
  rerun_cpp/src/rerun/time_column.cpp
Labels: 🪳 bug, 💣 crash, 🌊 C++ API, include in changelog

#9965 Fix panel hide buttons saving untagged blueprint
  crates/viewer/re_viewer/src/app_blueprint.rs
Labels: 🪳 bug, exclude from changelog

#9953 Add a light mode theme
  .typos.toml
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_time_panel/tests/snapshots/focused_item_is_focused.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_dense_data.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_active_no_query.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_active_query.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_inactive.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_path_to,_rig.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_to_the.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_to_the_.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-ath,left.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-ath,t.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-none.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-path.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-t.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the,oid.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the_.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-void.png
  crates/viewer/re_ui/data/design_tokens_dark.json
  crates/viewer/re_ui/data/design_tokens_light.json
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/design_token_colors.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
  crates/viewer/re_ui/src/notifications.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer_context/src/utils/text.rs
Labels: ui, 📺 re_viewer, include in changelog, 🧑‍🎨 Design

#9975 Follow system theme in debug builds
  crates/utils/re_log/src/lib.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#9976 Enable debug symbols for workspace crates
  Cargo.toml
Labels: 🧑‍💻 dev experience, ⏱ build-times, exclude from changelog

#9982 Use recording name for file name when saving a file
  crates/viewer/re_viewer/src/app.rs
Labels: 📺 re_viewer, include in changelog

#9988 Fix table colors in light mode
  crates/utils/re_log/src/lib.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_ui/src/design_token_colors.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_viewer/src/navigation.rs
Labels: ui, 📺 re_viewer, exclude from changelog

#9951 Fix MSVC C++20 compilation issues
  .github/workflows/cpp_matrix_full.json
  .github/workflows/reusable_checks_cpp.yml
  docs/snippets/all/descriptors/descr_builtin_component.cpp
  rerun_cpp/src/rerun/component_batch.hpp
  rerun_cpp/tests/recording_stream.cpp
Labels: 🪳 bug, 🪟 windows, 🌊 C++ API, include in changelog

#9938 Use `ComponentDescriptor` in `HybridLatestAtResult`
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/loggable.rs
  crates/viewer/re_view/src/annotation_scene_context.rs
  crates/viewer/re_view/src/results_ext.rs
  crates/viewer/re_view_bar_chart/src/visualizer_system.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_view_graph/src/visualizers/edges.rs
  crates/viewer/re_view_graph/src/visualizers/nodes.rs
  crates/viewer/re_view_spatial/src/contexts/depth_offsets.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/mesh_cache.rs
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_text_document/src/visualizer_system.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_viewer_context/src/cache/tensor_stats_cache.rs
  crates/viewer/re_viewer_context/src/view/view_context_system.rs
  crates/viewer/re_viewer_context/src/view/visualizer_entity_subscriber.rs
  crates/viewer/re_viewer_context/src/view/visualizer_system.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
Labels: 🚜 refactor, exclude from changelog

#9936 Add `DataFusionTableWidget::column_visibility` and use it to improve visibility defaults for the partition table
  crates/store/re_sorbet/src/column_descriptor_ref.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: ui, exclude from changelog, dataplatform, feat-redap-browser

#9999 `LatestAtResults::component_mono_quiet` now requires `ComponentDescriptor`
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_query/src/latest_at.rs
  crates/viewer/re_view_spatial/src/pinhole.rs
Labels: exclude from changelog

#9994 Improve custom visualizer example
  crates/viewer/re_view/src/query.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
  docs/content/howto/visualization/extend-ui.md
  examples/rust/custom_view/README.md
  examples/rust/custom_view/src/color_archetype.rs
  examples/rust/custom_view/src/color_coordinates_visualizer_system.rs
  examples/rust/custom_view/src/main.rs
  examples/rust/custom_view/src/points3d_color_view.rs
  examples/rust/custom_view/src/points3d_color_visualizer.rs
Labels: examples, include in changelog

#10002 Fix arflow demo links
  examples/python/arflow/README.md
  lychee.toml
Labels: 📖 documentation, examples, exclude from changelog, deploy docs

#9963 Fix time series points querying extra points at start and end of time range (causing stuttering on playback in some scenes)
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog, 📈 plot

#9991 Misc server related improvements
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  crates/store/re_sorbet/src/chunk_columns.rs
Labels: exclude from changelog, dataplatform

#9995 Fix manual refresh not working in Redap browser
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_redap_browser/src/tables_session_context.rs
Labels: exclude from changelog

#10003 Allow editing existing recording properties, like name
  crates/store/re_log_types/src/index/time_point.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_name.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_selection_panel/Cargo.toml
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_ui/src/list_item/item_button.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
  crates/viewer/re_view_spatial/tests/visible_time_range.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_blueprint.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/view/view_context.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 📺 re_viewer, include in changelog

#10004 Allow selecting multiple recordings
  crates/viewer/re_data_ui/src/item_ui.rs
Labels: ui, 📺 re_viewer, include in changelog

#10001 Add `/env/` to `.gitignore`
  .gitignore
Labels: 🧑‍💻 dev experience, exclude from changelog

#10006 Increase max size of gRPC messages
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_server/src/lib.rs
Labels: 🪳 bug, include in changelog, remote-store

#10008 Remove dead code: `timepoint_max`
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_log_types/src/arrow_msg.rs
  crates/store/re_log_types/src/lib.rs
  crates/top/rerun/src/commands/rrd/migrate.rs
Labels: 🚜 refactor, exclude from changelog

#10011 Disambiguate `latest_at` and `range` example targets
  crates/store/re_chunk/examples/chunk_latest_at.rs
  crates/store/re_chunk/examples/chunk_range.rs
  crates/store/re_query/examples/query_latest_at.rs
  crates/store/re_query/examples/query_range.rs
Labels: exclude from changelog

#9947 Add a tooltip to column headers with the content of the descriptor
  Cargo.lock
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_ui/data/icons/copy.png
  crates/viewer/re_ui/src/icons.rs
Labels: ui, exclude from changelog, dataplatform

#10013 Tweak light mode colors
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_time_panel/src/time_control_ui.rs
  crates/viewer/re_time_panel/src/time_selection_ui.rs
  crates/viewer/re_ui/src/design_token_colors.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: ui, exclude from changelog

#9787 Improve 2D heuristic fallback values for image opacity
  .github/workflows/reusable_checks_rust.yml
  crates/viewer/re_view_spatial/src/ui.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_spatial/tests/snapshots/draw_order.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_boxes.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_spheres.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_0.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_1.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_2.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_3.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_4.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_5.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_6.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_hierarchy_step_7.png
  crates/viewer/re_view_spatial/tests/transform_hierarchy.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  scripts/ci/rust_checks.py
Labels: exclude from changelog

#10020 Simplify the logic around fallback ui in `re_component_ui`
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/src/fallback_ui.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: 🚜 refactor, exclude from changelog

#10005 Make remainders of `LatestAtResults` tag-aware
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/store/re_query/benches/latest_at.rs
  crates/store/re_query/examples/query_latest_at.rs
  crates/store/re_query/src/latest_at.rs
  crates/store/re_query/tests/latest_at.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: exclude from changelog

#10021 Use BuildJet runners with more CPUs and RAM
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_test_wheels.yml
Labels: exclude from changelog, :ship: CI

#10017 Add CI lint for wrong publish flags
  .github/workflows/reusable_checks.yml
  crates/utils/re_auth/Cargo.toml
  pixi.toml
  scripts/ci/crates.py
Labels: exclude from changelog, :ship: CI

#10023 No longer require graphics API validation layer for image comparision tests
  crates/viewer/re_renderer/src/device_caps.rs
Labels: exclude from changelog, :ship: CI

#10026 Require `ComponentDescriptor` in `ChunkBuilder::with_component_batch*` methods
  crates/store/re_chunk/examples/chunk_latest_at.rs
  crates/store/re_chunk/examples/chunk_range.rs
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk/tests/latest_at.rs
  crates/store/re_chunk/tests/range.rs
  crates/store/re_chunk_store/src/events.rs
  crates/store/re_chunk_store/src/subscribers.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_chunk_store/tests/correctness.rs
  crates/store/re_chunk_store/tests/drop_time_range.rs
  crates/store/re_chunk_store/tests/gc.rs
  crates/store/re_chunk_store/tests/reads.rs
  crates/store/re_chunk_store/tests/stats.rs
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_entity_db/src/entity_tree.rs
  crates/store/re_entity_db/tests/clear.rs
  crates/store/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  crates/store/re_query/examples/query_latest_at.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/viewer/re_time_panel/src/recursive_chunks_per_timeline_subscriber.rs
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
Labels: 🚜 refactor, include in changelog, 🔩 data model

#10016 Remove remaining mentions of `rr.connect`
  README.md
  crates/top/re_sdk/src/recording_stream.rs
  design/blueprint_store.md
  docs/content/concepts/app-model.md
  docs/content/concepts/static.md
  docs/content/getting-started/data-in/python.md
  docs/content/getting-started/data-out/analyze-and-send.md
  docs/content/howto/integrations/embed-notebooks.md
  docs/content/howto/visualization/configure-viewer-through-code.md
  docs/content/reference/sdk/operating-modes.md
  examples/python/notebook/README.md
  rerun_cpp/README.md
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 📖 documentation, include in changelog, deploy docs

#10024 Add end-to-end test for changing origin of a 3D view
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/ui.rs
  crates/viewer/re_view_spatial/tests/snapshots/transform_tree_origins__sun.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_tree_origins__sun_planet.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_tree_origins__sun_planet_moon.png
  crates/viewer/re_view_spatial/tests/transform_tree_origins.rs
Labels: 🔨 testing, exclude from changelog

#10009 Update to wgpu 0.25
  .github/workflows/contrib_checks.yml
  Cargo.lock
  Cargo.toml
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/context_test.rs
  crates/viewer/re_renderer/src/device_caps.rs
  crates/viewer/re_renderer/src/error_handling/error_tracker.rs
  crates/viewer/re_renderer/src/error_handling/wgpu_core_error.rs
  crates/viewer/re_renderer/src/global_bindings.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: dependencies, include in changelog

#10010 Fix issues when combining `InstancePoses3D` with transform properties of `Boxes3D`/`Ellipsoids3D`/`Capsules3D`
  crates/store/re_types/definitions/rerun/archetypes/boxes3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/capsules3d.fbs
  crates/store/re_types/definitions/rerun/archetypes/ellipsoids3d.fbs
  crates/store/re_types/src/archetypes/boxes3d.rs
  crates/store/re_types/src/archetypes/capsules3d.rs
  crates/store/re_types/src/archetypes/ellipsoids3d.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_view_spatial/src/contexts/transform_tree_context.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/src/visualizers/arrows3d.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes2d.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/ellipsoids.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/lines2d.rs
  crates/viewer/re_view_spatial/src/visualizers/lines3d.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/points2d.rs
  crates/viewer/re_view_spatial/src/visualizers/points3d.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/proc_mesh_vis.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_boxes.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_spheres.png
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  docs/content/reference/migration/migration-0-24.md
  docs/content/reference/types/archetypes/boxes3d.md
  docs/content/reference/types/archetypes/capsules3d.md
  docs/content/reference/types/archetypes/ellipsoids3d.md
  rerun_cpp/src/rerun/archetypes/boxes3d.hpp
  rerun_cpp/src/rerun/archetypes/capsules3d.hpp
  rerun_cpp/src/rerun/archetypes/ellipsoids3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
Labels: 📺 re_viewer, include in changelog

#10040 Update to latest egui main
  Cargo.lock
Labels: dependencies, exclude from changelog, egui

#9997 Replace `tinystl` with `stl_io` to support more stl files
  Cargo.lock
  Cargo.toml
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/importer/stl.rs
Labels: enhancement, 📺 re_viewer, dependencies, include in changelog

#10043 Expose LineBatchBuilder
  crates/viewer/re_renderer/src/lib.rs
Labels: 🔺 re_renderer, exclude from changelog

#10044 Remove `component_mono_with_log_level_by_name()` from `LatestAtResults`
  crates/store/re_query/src/latest_at.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
Labels: 🚜 refactor, exclude from changelog

#10045 All methods of `re_query::LatestAtResults` use `ComponentDescriptor`
  crates/store/re_chunk/src/builder.rs
  crates/store/re_query/src/latest_at.rs
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_graph/src/ui/selection.rs
  crates/viewer/re_view_spatial/src/transform_cache.rs
  crates/viewer/re_viewport_blueprint/src/view_properties.rs
Labels: 🚜 refactor, exclude from changelog

#10046 Prepare for supporting SVG icons
  crates/viewer/re_ui/src/icon_text.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer_context/src/tables.rs
Labels: ui, 🚜 refactor, exclude from changelog

#10034 Introduce variant UIs in `re_component_ui`
  Cargo.lock
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/variant_uis/mod.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_viewer_context/src/global_context/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  crates/viewer/re_viewer_context/src/lib.rs
Labels: 📺 re_viewer, include in changelog

#10047 Use cargo binstall to install cargo shear
  .github/workflows/cargo_shear.yml
Labels: exclude from changelog, :ship: CI

#10041 Upload NPM package as tarball to GCS
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_build_js.yml
  .github/workflows/reusable_upload_js.yml
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer/package.json
  scripts/ci/sync_release_assets.py
Labels: exclude from changelog, :ship: CI

#10052 Replace some use of `backtrace` crate with `std::backtrace`
  Cargo.lock
  crates/store/re_chunk/Cargo.toml
  crates/store/re_log_types/Cargo.toml
  crates/store/re_log_types/src/instance.rs
  crates/store/re_types_core/Cargo.toml
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/result.rs
  examples/rust/external_data_loader/Cargo.toml
Labels: 🧑‍💻 dev experience, dependencies, exclude from changelog

#10050 Split off `GlobalContext` to its own crate
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/top/rerun-cli/Cargo.toml
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_global_context/Cargo.toml
  crates/viewer/re_global_context/README.md
  crates/viewer/re_global_context/src/app_options.rs
  crates/viewer/re_global_context/src/blueprint_id.rs
  crates/viewer/re_global_context/src/command_sender.rs
  crates/viewer/re_global_context/src/contents.rs
  crates/viewer/re_global_context/src/file_dialog.rs
  crates/viewer/re_global_context/src/item.rs
  crates/viewer/re_global_context/src/lib.rs
  crates/viewer/re_global_context/src/store_hub_entry.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_view_spatial/src/picking_ui.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🚜 refactor, exclude from changelog

#10054 Fix column names and hide indicator components in the partition table
  crates/viewer/re_redap_browser/src/servers.rs
Labels: ui, exclude from changelog, feat-redap-browser

#10061 Enable the `re_auth` middleware on Wasm grpc client
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/utils/re_auth/Cargo.toml
  crates/utils/re_auth/src/lib.rs
  crates/utils/re_auth/src/service/mod.rs
  pixi.lock
  pixi.toml
Labels: 🕸️ web, exclude from changelog, dataplatform

#10062 Update callbacks and custom_callbacks example docs to mention the other
  docs/content/howto/callbacks.md
  examples/rust/custom_callback/README.md
Labels: 📖 documentation, include in changelog, deploy docs

#10063 Check TextEdit state before copying selection description
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#10080 Improve UX of opening recordings in catalog browser
  Cargo.lock
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_smart_channel/src/receive_set.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/navigation.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: 🪳 bug, ui, exclude from changelog, feat-redap-browser

#10075 Fix incorrect 'structfields' doc links
  crates/viewer/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/viewer/re_renderer/src/wgpu_resources/buffer_pool.rs
Labels: 📖 documentation, exclude from changelog

#10081 Expose more `re_renderer` symbols and allow shader reload for shaders outside of the regular shader directory
  Cargo.lock
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/file_resolver.rs
  crates/viewer/re_renderer/src/file_server.rs
  crates/viewer/re_renderer/src/global_bindings.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/wgpu_resources/shader_module_pool.rs
Labels: 🔺 re_renderer, exclude from changelog

#10084 Implement hot-reloading of design tokens / theme
  Cargo.lock
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/build.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/hot_reload_design_tokens.rs
  crates/viewer/re_ui/src/lib.rs
Labels: ui, 🧑‍💻 dev experience, exclude from changelog, 🧑‍🎨 Design

#10089 Move sizes and spacing into design tokens
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_chunk_store_ui/src/sort.rs
  crates/viewer/re_component_ui/src/geo_line_string.rs
  crates/viewer/re_component_ui/src/line_strip.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_selection_panel/src/item_heading_with_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/src/time_selection_ui.rs
  crates/viewer/re_ui/data/dark_theme.ron
  crates/viewer/re_ui/data/light_theme.ron
  crates/viewer/re_ui/examples/re_ui_example/hierarchical_drag_and_drop.rs
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_ui/src/context_ext.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/help.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/list_item/custom_content.rs
  crates/viewer/re_ui/src/list_item/label_content.rs
  crates/viewer/re_ui/src/list_item/list_item.rs
  crates/viewer/re_ui/src/list_item/mod.rs
  crates/viewer/re_ui/src/list_item/property_content.rs
  crates/viewer/re_ui/src/modal.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_spatial/src/visualizers/cameras.rs
  crates/viewer/re_view_spatial/src/visualizers/transform3d_arrows.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_text_document/src/view_class.rs
  crates/viewer/re_view_text_log/src/view_class.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/example_section.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/no_data_ui.rs
  crates/viewer/re_viewer/src/ui/welcome_screen/welcome_section.rs
  crates/viewer/re_viewer_context/src/drag_and_drop.rs
  crates/viewer/re_viewer_context/src/view/view_class_placeholder.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: ui, exclude from changelog

#10095 Make `channel` `pub` in `re_grpc_client`
  crates/store/re_grpc_client/src/lib.rs
Labels: exclude from changelog, dataplatform

#10096 Fix nightly asset sync
  .github/workflows/reusable_upload_js.yml
Labels: exclude from changelog

#10086 Forward `REDAP_TOKEN` to the web viewer in notebook environments
  Cargo.lock
  crates/store/re_grpc_client/src/connection_registry.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/web.rs
  rerun_js/web-viewer/index.ts
  rerun_notebook/build.mjs
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🕸️ web, exclude from changelog, dataplatform

#10097 Do not hold on to the `RedapClient` in the SDK
  crates/store/re_grpc_client/src/connection_registry.rs
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset.rs
  rerun_py/src/catalog/entry.rs
  rerun_py/src/catalog/table.rs
  rerun_py/src/catalog/task.rs
Labels: 🐍 Python API, exclude from changelog
