Repository rerun-io/rerun, pull requests merged in 2025-02, with the labels that each got.

#8887 Clarify use of `std::move(*this)` & similar situations
  CODE_STYLE.md
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  docs/snippets/all/howto/any_batch_value_send_columns.cpp
  docs/snippets/all/howto/any_values_send_columns.cpp
  rerun_cpp/src/rerun/collection.hpp
  rerun_cpp/src/rerun/result.hpp
Labels: 🧑‍💻 dev experience, 🌊 C++ API, exclude from changelog

#8889 fix re_blueprint_tree standalone all features build
  crates/viewer/re_blueprint_tree/Cargo.toml
Labels: 🔨 testing, exclude from changelog

#8897 Fix handling null timestamps in the dataframe
  crates/store/re_chunk/src/chunk.rs
  crates/viewer/re_view_dataframe/src/display_record_batch.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
Labels: 🪳 bug, include in changelog

#8899 Link fixes
  docs/content/concepts/chunks.md
  docs/content/howto/logging/send-columns.md
  docs/content/howto/logging/send-partial-updates.md
  docs/content/reference/migration/migration-0-22.md
Labels: 📖 documentation, exclude from changelog

#8888 add prompt depth anything example
  examples/manifest.toml
  examples/python/prompt_depth_anything/README.md
Labels: examples, include in changelog

#8890 Expose creating and querying index for a ReDap collection in python SDK
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_bindings/types.py
  rerun_py/rerun_sdk/rerun/remote.py
  rerun_py/src/dataframe.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#8901 Rename the index APIs from `query` to `search`
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
Labels: exclude from changelog, dataplatform

#8898 Rerun CMake dependency now automatically ensures C++17 or newer
  CMakeLists.txt
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/quick-start/cpp.md
  examples/cpp/clock/CMakeLists.txt
  examples/cpp/custom_collection_adapter/CMakeLists.txt
  examples/cpp/dna/CMakeLists.txt
  examples/cpp/external_data_loader/CMakeLists.txt
  examples/cpp/incremental_logging/CMakeLists.txt
  examples/cpp/log_file/CMakeLists.txt
  examples/cpp/minimal/CMakeLists.txt
  examples/cpp/shared_recording/CMakeLists.txt
  examples/cpp/spawn_viewer/CMakeLists.txt
  examples/cpp/stdio/CMakeLists.txt
  rerun_cpp/CMakeLists.txt
Labels: 🌊 C++ API, include in changelog

#8900 Add snapshot test to cover for the case of timeline with nulls
  Cargo.lock
  crates/viewer/re_view_dataframe/Cargo.toml
  crates/viewer/re_view_dataframe/src/lib.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/mod.rs
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_dataframe/tests/snapshots/null_timeline.png
Labels: 🔨 testing, exclude from changelog, feat-dataframe-view

#8904 Fix main
  .gitignore
  Cargo.lock
  crates/viewer/re_view_dataframe/Cargo.toml
Labels: dependencies, exclude from changelog, :ship: CI

#8905 Get rid of `check_all_components_ui`
  tests/python/release_checklist/check_all_components_ui.py
Labels: 🔨 testing, exclude from changelog

#8906 Fix dataframe "testing" feature
  Cargo.lock
  crates/viewer/re_view_dataframe/Cargo.toml
  crates/viewer/re_view_dataframe/tests/basic.rs
Labels: exclude from changelog, :ship: CI

#8892 Deprecate Python's `log_components`
  docs/content/reference/migration/migration-0-22.md
  rerun_py/rerun_sdk/rerun/_log.py
Labels: 🐍 Python API, include in changelog

#8910 Introduce API to add another recording to a viewer widget
  examples/python/notebook/cube.ipynb
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🐍 Python API, notebook, include in changelog

#8908 Support unknown timeline in dataframe view
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/mod.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_dataframe/tests/snapshots/unknown_timeline_selection_panel_ui.png
  crates/viewer/re_view_dataframe/tests/snapshots/unknown_timeline_view_ui.png
Labels: 🪳 bug, ui, include in changelog, feat-dataframe-view

#8912 Fix action button showing up for recording in app id tooltip
  crates/viewer/re_data_ui/src/app_id.rs
  crates/viewer/re_data_ui/src/data_source.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
Labels: 🪳 bug, ui, exclude from changelog

#8914 Switch .vscode extension to dependi
  .vscode/extensions.json
Labels: 🧑‍💻 dev experience, exclude from changelog

#8913 Fix memory leaks when closing recordings
  .gitignore
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_chunk_store/src/subscribers.rs
Labels: 🪳 bug, 🚀 performance, include in changelog

#8911 Expose flush on Python recording stream and call it on context manager exit
  crates/top/re_sdk/src/log_sink.rs
  crates/top/re_sdk/src/recording_stream.rs
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/tests/unit/test_dataframe.py
Labels: 🐍 Python API, include in changelog

#8918 Set default log level to `warn` now that notification center is in place
  crates/utils/re_log/src/lib.rs
Labels: 📺 re_viewer, 🏎️ Quick Issue, include in changelog

#8917 More Viewer control in notebooks (recording id, panel states)
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/web.rs
  examples/python/notebook/cube.ipynb
  rerun_js/web-viewer/build-wasm.mjs
  rerun_js/web-viewer/index.ts
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_py/rerun_sdk/rerun/notebook.py
Labels: 🐍 Python API, notebook, include in changelog

#8920 Workspace configuration to improve working with protobufs in vscode
  .vscode/settings.json
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
Labels: 🧑‍💻 dev experience, exclude from changelog

#8921 Add some missing gitignore expressions
  .gitignore
  examples/python/human_pose_tracking/.gitignore
Labels: 🧑‍💻 dev experience, exclude from changelog

#8922 Fix testing feature
  crates/viewer/re_time_panel/Cargo.toml
Labels: exclude from changelog, :ship: CI

#8896 First draft of 0.22 release notes
  CHANGELOG.md
  scripts/generate_changelog.py
Labels: ⛴ release, exclude from changelog

#8923 Don't compare arrows3d_simple C++ snippet b/c floats
  docs/snippets/snippets.toml
Labels: 🔨 testing, exclude from changelog, :ship: CI

#8915 Fix not being able to reset blueprint after override edit
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_view_tensor/src/view_class.rs
Labels: 🦟 regression, exclude from changelog

#8916 Implement snapshot test for 2D draw order
  Cargo.lock
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_view_spatial/tests/snapshots/draw_order.png
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  tests/python/release_checklist/check_draw_order.py
Labels: enhancement, 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#8930 Always cache the vulkan SDK on CI
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks_rust.yml
Labels: enhancement, 🚀 performance, exclude from changelog, :ship: CI

#8932 Workaround vulkan.lunarg being down
  .github/workflows/reusable_checks_rust.yml
  crates/utils/re_video/src/lib.rs
Labels: exclude from changelog, :ship: CI

#8926 Update egui to 0.31
  Cargo.lock
  Cargo.toml
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_map/src/visualizers/geo_line_strings.rs
  crates/viewer/re_view_map/src/visualizers/geo_points.rs
  crates/viewer/re_view_map/src/visualizers/mod.rs
  crates/viewer/re_viewer/src/ui/memory_panel.rs
Labels: dependencies, include in changelog, egui

#8934 Move `ChunkId` (and `RowId`) from `re_chunk` to `re_types_core`
  .typos.toml
  Cargo.lock
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/lib.rs
  crates/store/re_types_core/src/id.rs
  crates/store/re_types_core/src/lib.rs
  crates/store/re_types_core/src/tuid.rs
  crates/viewer/re_renderer/src/draw_phases/mod.rs
  docs/content/reference/migration/migration-0-22.md
Labels: 🚜 refactor, exclude from changelog

#8927 Handle indicators, overrides & view states in view tests
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/typed_entity_collections.rs
  crates/viewer/re_viewport_blueprint/src/test_context_ext.rs
Labels: 🔨 testing, exclude from changelog

#8938 Remove container/view IDs from insta snapshots
  crates/viewer/re_blueprint_tree/src/data.rs
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/empty.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/multiple_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/no-query/unknown_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-_path_to,_rig/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-_path_to_th/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-_to_the_/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-_to_the_/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-_to_the_/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-_to_the_/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-ath,left/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-ath,t/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-ath,t/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-ath,t/unknown_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-path/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-path/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-path/unknown_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-t/multiple_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-t/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-t/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-t/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-t/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-t/unknown_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the,oid/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the,oid/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the,oid/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the,oid/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-to_the/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-void/multiple_proj.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-void/non_root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-void/proj_with_placeholder.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-void/root_origin.snap
  crates/viewer/re_blueprint_tree/tests/snapshots/view_structure_test/query-void/single_proj.snap
  crates/viewer/re_blueprint_tree/tests/view_structure_test.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
Labels: 🔨 testing, exclude from changelog

#8941 Fix graph view test
  crates/viewer/re_view_graph/tests/basic.rs
Labels: 🔨 testing, exclude from changelog

#8939 Improve arrow UI for large blob-like things
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_large_blob_any_value_large_blob.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_small_array_any_value_small_array.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_large_blob_any_value_large_blob.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_small_array_any_value_small_array.png
  crates/viewer/re_ui/src/arrow_ui.rs
  crates/viewer/re_ui/tests/arrow_ui_test.rs
  crates/viewer/re_ui/tests/snapshots/arrow_ui.png
Labels: 🪳 bug, ui, 📺 re_viewer, 🚀 performance, include in changelog

#8909 Initial LeRobot dataset loader
  Cargo.lock
  Cargo.toml
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_data_loader/src/loader_directory.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
  deny.toml
Labels: 📺 re_viewer, examples, include in changelog, dataplatform

#8952 Treat zero-angle rotation as identity when axis is invalid
  crates/store/re_types/definitions/rerun/components/rotation_axis_angle.fbs
  crates/store/re_types/definitions/rerun/datatypes/rotation_axis_angle.fbs
  crates/store/re_types/src/components/pose_rotation_axis_angle.rs
  crates/store/re_types/src/components/pose_rotation_axis_angle_ext.rs
  crates/store/re_types/src/components/rotation_axis_angle.rs
  crates/store/re_types/src/datatypes/rotation_axis_angle.rs
  crates/store/re_types/src/reflection/mod.rs
  docs/content/reference/types/components/pose_rotation_axis_angle.md
  docs/content/reference/types/components/rotation_axis_angle.md
  docs/content/reference/types/datatypes/rotation_axis_angle.md
  rerun_cpp/src/rerun/components/pose_rotation_axis_angle.hpp
  rerun_cpp/src/rerun/components/rotation_axis_angle.hpp
  rerun_cpp/src/rerun/datatypes/rotation_axis_angle.hpp
  rerun_py/rerun_sdk/rerun/components/pose_rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/components/rotation_axis_angle.py
  rerun_py/rerun_sdk/rerun/datatypes/rotation_axis_angle.py
Labels: 🪳 bug, 😤 annoying, 🦟 regression, include in changelog

#8947 Improved help view
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_ui/data/icons/lmc.png
  crates/viewer/re_ui/data/icons/rmc.png
  crates/viewer/re_ui/data/icons/scroll.png
  crates/viewer/re_ui/data/icons/shift.png
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/help.rs
  crates/viewer/re_ui/src/icon_text.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
  crates/viewer/re_view_spatial/src/view_3d.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_text_document/src/view_class.rs
  crates/viewer/re_view_text_log/src/view_class.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class.rs
  crates/viewer/re_viewer_context/src/view/view_class_placeholder.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
  examples/rust/custom_view/src/color_coordinates_view.rs
Labels: enhancement, ui, include in changelog

#8951 Fix slight parity issue on migration guide
  docs/content/reference/migration/migration-0-22.md
Labels: 📖 documentation, exclude from changelog

#8958 Automated `check_annotations`
  Cargo.lock
  crates/viewer/re_view_spatial/Cargo.toml
  crates/viewer/re_view_spatial/tests/annotations.rs
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_background.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_rect_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_rect_red.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_red.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_overview.png
  tests/python/release_checklist/check_annotations.py
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#8961 Automated `check_transform_clamping`
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_boxes.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_spheres.png
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  tests/python/release_checklist/check_component_and_transform_clamping.py
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#8960 Stop forgetting about updating the migration guide link
  .github/workflows/reusable_checks.yml
  docs/content/reference/migration.md
  scripts/ci/check_migration_guide_redirect.py
Labels: 📖 documentation, exclude from changelog, :ship: CI

#8959 Fix search index build
  .github/workflows/contrib_checks.yml
  .github/workflows/on_push_docs.yml
  .github/workflows/reusable_checks.yml
  Cargo.lock
  Cargo.toml
  crates/build/re_dev_tools/src/build_search_index/build.rs
  crates/build/re_dev_tools/src/build_search_index/ingest.rs
  crates/build/re_dev_tools/src/build_search_index/ingest/rust.rs
  crates/build/re_dev_tools/src/build_search_index/repl.rs
  crates/store/re_log_types/src/time_point/timeline.rs
  crates/store/re_types_core/src/archetype.rs
  crates/store/re_types_core/src/loggable.rs
  crates/store/re_types_core/src/view.rs
  crates/utils/re_string_interner/src/lib.rs
  crates/viewer/re_web_viewer_server/build.rs
Labels: exclude from changelog, deploy docs

#8963 Fix link in text log view help text
  crates/viewer/re_view_text_log/src/view_class.rs
  lychee.toml
Labels: ui, include in changelog

#8928 make python sdk index search APIs slightly more ergonomic
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_bindings/types.py
  rerun_py/src/remote.rs
Labels: exclude from changelog

#8946 Add `git-lfs` to our CI container
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  ci_docker/Dockerfile
  ci_docker/README.md
  ci_docker/publish.sh
Labels: exclude from changelog, :ship: CI

#8964 Fix search index build (again)
  .github/workflows/on_push_docs.yml
  Cargo.toml
Labels: exclude from changelog, deploy docs

#8966 Bump `transform_clamping`'s acceptable error rate to 0.007
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
Labels: exclude from changelog, :ship: CI

#8956 Add example for python notebook with partial & columnar updates
  examples/python/notebook/README.md
  examples/python/notebook/partial_updates.ipynb
Labels: examples, include in changelog

#8967 Assorted bouquet of `main` fixes
  .github/workflows/reusable_build_examples.yml
  .github/workflows/reusable_test_wheels.yml
  CHANGELOG.md
Labels: exclude from changelog, :ship: CI

#8955 Add snapshot test for the help view
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/tests/help_ui_test.rs
  crates/viewer/re_ui/tests/snapshots/help_Mac.png
  crates/viewer/re_ui/tests/snapshots/help_Windows.png
Labels: 🔨 testing, exclude from changelog

#8968 Make `execute_systems_for_view` time passing more consistent
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_spatial/tests/annotations.rs
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  crates/viewer/re_viewport/src/system_execution.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 🚜 refactor, exclude from changelog

#8976 Refactor query testing to remove need for `TransportChunk`
  crates/store/re_dataframe/src/query.rs
Labels: 🔨 testing, 🚜 refactor, exclude from changelog

#8980 Guard against empty body in PR checkbox lint
  scripts/ci/check_pr_checkboxes.py
Labels: exclude from changelog

#8971 Disable anti-aliasing in tests
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/context_test.rs
  crates/viewer/re_renderer/src/device_caps.rs
  crates/viewer/re_renderer/src/draw_phases/outlines.rs
  crates/viewer/re_renderer/src/error_handling/error_tracker.rs
  crates/viewer/re_renderer/src/error_handling/mod.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/renderer/depth_cloud.rs
  crates/viewer/re_renderer/src/renderer/generic_skybox.rs
  crates/viewer/re_renderer/src/renderer/lines.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_renderer/src/renderer/point_cloud.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_renderer/src/renderer/test_triangle.rs
  crates/viewer/re_renderer/src/renderer/world_grid.rs
  crates/viewer/re_renderer/src/view_builder.rs
  crates/viewer/re_renderer_examples/framework.rs
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_green.png
  crates/viewer/re_view_spatial/tests/snapshots/draw_order.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_boxes.png
  crates/viewer/re_view_spatial/tests/snapshots/transform_clamping_spheres.png
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer/src/viewer_analytics/mod.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: 🔨 testing, 🔺 re_renderer, exclude from changelog

#8972 Add link to Snap Store in Gettting Started
  docs/content/getting-started/installing-viewer.md
Labels: 📖 documentation, ⛴ release, include in changelog

#8949 Checklist for LeRobot dataloader
  scripts/lint.py
  tests/assets/lerobot/apple_storage/.gitattributes
  tests/assets/lerobot/apple_storage/README.md
  tests/assets/lerobot/apple_storage/data/chunk-000/episode_000000.parquet
  tests/assets/lerobot/apple_storage/data/chunk-000/episode_000001.parquet
  tests/assets/lerobot/apple_storage/data/chunk-000/episode_000002.parquet
  tests/assets/lerobot/apple_storage/meta/episodes.jsonl
  tests/assets/lerobot/apple_storage/meta/info.json
  tests/assets/lerobot/apple_storage/meta/stats.json
  tests/assets/lerobot/apple_storage/meta/tasks.jsonl
  tests/assets/lerobot/apple_storage/videos/chunk-000/observation.image/episode_000000.mp4
  tests/assets/lerobot/apple_storage/videos/chunk-000/observation.image/episode_000001.mp4
  tests/assets/lerobot/apple_storage/videos/chunk-000/observation.image/episode_000002.mp4
  tests/python/release_checklist/check_lerobot_dataloader.py
Labels: 🔨 testing, exclude from changelog

#8978 Fix rrd size tracking
  .github/workflows/reusable_track_size.yml
  scripts/ci/compare.py
Labels: exclude from changelog

#8981 Infer entity paths from LeRobot dataset feature metadata
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: enhancement, 📺 re_viewer, include in changelog

#8982 Automated graph checks
  crates/viewer/re_view_graph/tests/basic.rs
  crates/viewer/re_view_graph/tests/snapshots/multi_graphs.png
  tests/python/release_checklist/check_graph_view.py
Labels: 🔨 testing, 🧑‍💻 dev experience, exclude from changelog

#8984 Adapt `re_grpc_client` to new URI scheme
  Cargo.lock
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/redap/address.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/top/rerun/src/commands/entrypoint.rs
Labels: exclude from changelog, dataplatform

#8988 Document default-log level change
  CHANGELOG.md
  crates/utils/re_log/src/lib.rs
  docs/content/reference/migration/migration-0-22.md
Labels: 📖 documentation, 🦀 Rust API, 😤 annoying, include in changelog

#8974 Switch to cargo nextest for rust test execution
  .github/actions/setup-rust/action.yml
  .github/workflows/contrib_checks.yml
  .github/workflows/reusable_checks_rust.yml
  scripts/ci/rust_checks.py
Labels: 🔨 testing, exclude from changelog, :ship: CI

#8997 Remove extra module within `re_arrow_util`
  crates/store/re_chunk/src/batcher.rs
  crates/store/re_chunk/src/builder.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_chunk/src/merge.rs
  crates/store/re_chunk/src/migration.rs
  crates/store/re_chunk/src/shuffle.rs
  crates/store/re_chunk/src/slice.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk/tests/memory_test.rs
  crates/store/re_chunk_store/src/writes.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_types_core/src/loggable_batch.rs
  crates/utils/re_arrow_util/src/arrow_util.rs
  crates/utils/re_arrow_util/src/lib.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8998 Simplify and test `wrap_in_list_array`
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/utils/re_arrow_util/src/lib.rs
Labels: 🏹 arrow, 🚜 refactor, exclude from changelog

#8990 Add a snapshot test for the range selection with shift-click
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_blueprint_tree/tests/range_selection_test.rs
  crates/viewer/re_blueprint_tree/tests/snapshots/range_selection_in_blueprint_tree.png
  crates/viewer/re_context_menu/src/collapse_expand.rs
  crates/viewer/re_selection_panel/src/lib.rs
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_background.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_rect_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_rect_red.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_red.png
  crates/viewer/re_viewer_context/src/collapsed_id.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport_blueprint/src/test_context_ext.rs
  crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs
Labels: 🔨 testing, ui, exclude from changelog

#8999 Improve `Tuid`
  Cargo.lock
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_types_core/src/id.rs
  crates/utils/re_tuid/Cargo.toml
  crates/utils/re_tuid/benches/bench_tuid.rs
  crates/utils/re_tuid/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#9009 Remove check for inner nullability of component columns
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_grpc_client/src/redap/mod.rs
Labels: 🪳 bug, 🏹 arrow, exclude from changelog, 🔩 data model, dataplatform

#9014 Fix `serde` for `Tuid`
  crates/utils/re_tuid/src/lib.rs
Labels: 🪳 bug, exclude from changelog

#9000 Fix bug leading to swizzled lerobot data in dataloader
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/utils/re_arrow_util/src/lib.rs
Labels: 🪳 bug, include in changelog

#9025 Add missing bytemuck feature
  crates/utils/re_tuid/Cargo.toml
Labels: 🪳 bug, dependencies, exclude from changelog

#9017 Add general `re_sorbet::SorbetSchema`
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/transport.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/column_kind.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_sorbet/src/error.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog, 🔩 data model

#9004 Fix: `--serve-web` should consume data sources
  crates/store/re_grpc_server/src/lib.rs
  crates/top/rerun/src/commands/entrypoint.rs
Labels: 🕸️ web, exclude from changelog

#9037 Don't use np.float_ since it was removed in numpy 2.0
  examples/python/structure_from_motion/structure_from_motion/__main__.py
  rerun_py/rerun_bindings/types.py
Labels: 🐍 Python API, include in changelog

#9035 Fix time series marker sizes not being able to vary over time
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
Labels: 🪳 bug, include in changelog, 📈 plot

#9026 Use `SorbetColumnDescriptors` in `re_dataframe`
  Cargo.lock
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/engine.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_sorbet/Cargo.toml
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  rerun_py/src/dataframe.rs
  rerun_py/src/remote.rs
Labels: 🚜 refactor, exclude from changelog, 🔩 data model, feat-dataframe-view, feat-dataframe-api

#9040 Fix: Configure max message size for gRPC server
  crates/store/re_grpc_server/src/lib.rs
Labels: exclude from changelog

#9030 Always access `caches` through `store_context`
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/tensor.rs
  crates/viewer/re_view_spatial/src/lib.rs
  crates/viewer/re_view_spatial/src/visualizers/assets3d.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/meshes.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/proc_mesh_vis.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_tensor/src/visualizer_system.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: exclude from changelog

#9033 Make `SeriesLine` visualizer work with several scalars per time
  Cargo.lock
  Cargo.toml
  crates/store/re_types/src/components/name_ext.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  tests/rust/experimental_multi_scalar/Cargo.toml
  tests/rust/experimental_multi_scalar/src/main.rs
Labels: 📺 re_viewer, include in changelog, 📈 plot

#8995 Migrate file format to protobuf
  Cargo.lock
  Cargo.toml
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_entity_db/examples/memory_usage.rs
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/benches/msg_encode_benchmark.rs
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/codec/file/mod.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_encoding/src/file_sink.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/store/re_log_encoding/tests/arrow_encode_roundtrip.rs
  crates/top/re_sdk/src/binary_stream_sink.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/top/rerun/src/commands/rrd/merge_compact.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/saving.rs
Labels: include in changelog, 🪵 Log & send APIs

#9043 Add `ComponentDescriptorRef` to `re_sorbet`
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/column_descriptor_ref.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
Labels: exclude from changelog, 🔩 data model

#9048 Fix lint for nightly
  crates/store/re_log_encoding/src/codec/file/mod.rs
Labels: exclude from changelog

#9045 Improve `redap://` connection UX and error messages
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/address.rs
  crates/store/re_grpc_client/src/redap/mod.rs
Labels: ui, include in changelog, dataplatform

#9047 Add snapshot tests for multiple time series per entity
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: 🪳 bug, 🔨 testing, exclude from changelog, 📈 plot

#9055 fix merge order issue
  crates/viewer/re_view_time_series/tests/basic.rs
Labels: exclude from changelog, :ship: CI

#9054 Fix Arrows2D draw order having no effect
  crates/viewer/re_view_spatial/src/visualizers/arrows2d.rs
  crates/viewer/re_view_spatial/tests/draw_order.rs
  crates/viewer/re_view_spatial/tests/snapshots/draw_order.png
Labels: 🪳 bug, include in changelog

#9041 Encode wether or not a chunk is sorted by `RowId` in the column metadata
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/store/re_sorbet/src/metadata.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
Labels: exclude from changelog, 🔩 data model

#9052 Use correct `BatchType` in `re_sorbet`
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_columns.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
Labels: 🪳 bug, exclude from changelog, 🔩 data model

#9051 Implement `TryFrom<&str>` for `redap::Origin`
  crates/store/re_grpc_client/src/redap/address.rs
  crates/store/re_grpc_client/src/redap/mod.rs
Labels: exclude from changelog

#9057 Improve comment regarding arrow1-IPC-serialization
  crates/store/re_log_encoding/src/codec/arrow.rs
Labels: 🪳 bug, 🏹 arrow, dependencies, exclude from changelog

#9062 Introduce a `LogMsg` that keeps track of its origins in bytes
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
Labels: 🏹 arrow, exclude from changelog, 🪵 Log & send APIs

#9066 Remove `redap` feature
  crates/store/re_data_source/Cargo.toml
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/top/re_sdk/Cargo.toml
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_viewer/Cargo.toml
  rerun_py/Cargo.toml
Labels: exclude from changelog

#9065 Improve `image_column_updates` python example
  docs/snippets/all/archetypes/image_column_updates.py
Labels: 📖 documentation, examples, include in changelog, deploy docs

#9071 Remove `grpc` as a feature flag (always have it enabled)
  .github/workflows/reusable_checks_rust.yml
  crates/store/re_data_source/Cargo.toml
  crates/store/re_data_source/src/data_source.rs
  crates/top/re_sdk/Cargo.toml
  crates/top/rerun-cli/Cargo.toml
  crates/top/rerun/Cargo.toml
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/web_tools.rs
  pixi.toml
  rerun_js/web-viewer/build-wasm.mjs
  rerun_py/Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#9061 Fix inconsistencies in plot highlights
  Cargo.lock
  Cargo.toml
  crates/viewer/re_view_time_series/src/lib.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/util.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
Labels: 📺 re_viewer, include in changelog, 📈 plot

#9067 Move `rerun.components.blueprint.Visible` to `rerun.components.Visible`
  crates/store/re_types/definitions/rerun/blueprint/archetypes/container_blueprint.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/line_grid3d.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/plot_legend.fbs
  crates/store/re_types/definitions/rerun/blueprint/archetypes/view_blueprint.fbs
  crates/store/re_types/definitions/rerun/blueprint/components.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/visible.fbs
  crates/store/re_types/src/blueprint/archetypes/container_blueprint.rs
  crates/store/re_types/src/blueprint/archetypes/line_grid3d.rs
  crates/store/re_types/src/blueprint/archetypes/plot_legend.rs
  crates/store/re_types/src/blueprint/archetypes/view_blueprint.rs
  crates/store/re_types/src/blueprint/components/.gitattributes
  crates/store/re_types/src/blueprint/components/mod.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/visible.rs
  crates/store/re_types/src/components/visible_ext.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_blueprint_tree/src/data.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_context_menu/src/actions/show_hide.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/blueprint/validation_gen/mod.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport_blueprint/src/container.rs
  crates/viewer/re_viewport_blueprint/src/view.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/visible.md
  docs/content/reference/types/datatypes/bool.md
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/container_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/line_grid3d.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/line_grid3d.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/plot_legend.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/plot_legend.hpp
  rerun_cpp/src/rerun/blueprint/archetypes/view_blueprint.cpp
  rerun_cpp/src/rerun/blueprint/archetypes/view_blueprint.hpp
  rerun_cpp/src/rerun/blueprint/components.hpp
  rerun_cpp/src/rerun/blueprint/components/.gitattributes
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/visible.hpp
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/container_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/line_grid3d.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/plot_legend.py
  rerun_py/rerun_sdk/rerun/blueprint/archetypes/view_blueprint.py
  rerun_py/rerun_sdk/rerun/blueprint/components/.gitattributes
  rerun_py/rerun_sdk/rerun/blueprint/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/visible.py
  rerun_py/tests/unit/test_container_blueprint.py
  rerun_py/tests/unit/test_plot_legend.py
  rerun_py/tests/unit/test_view_blueprint.py
Labels: include in changelog, 🪵 Log & send APIs

#9072 Better error message for using MsgPack serializer
  crates/store/re_log_encoding/src/lib.rs
Labels: exclude from changelog

#9074 Rename UI and crate for the Redap browser
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/viewer/re_catalog_hub/README.md
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/README.md
  crates/viewer/re_redap_browser/src/collection_ui.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🚜 refactor, exclude from changelog

#9064 Switch back to the viewer when clicking a recording URI
  Cargo.lock
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/src/redap/address.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/recording_uri.fbs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/recording_uri.rs
  crates/store/re_types/src/components/recording_uri_ext.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/recording_uri.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/RecordingUri_simple.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_catalog_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/RecordingUri_simple.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_catalog_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_data_ui/src/component_name.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/collection_ui.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_time_panel/src/time_control_ui.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_ui/src/ui_layout.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/global_context/mod.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/test_context.rs
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/recording_uri.md
  docs/content/reference/types/datatypes/utf8.md
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/recording_uri.hpp
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/recording_uri.py
Labels: ui, exclude from changelog, feat-redap-browser

#9073 Fix links to `nyu_depth_v2`
  examples/python/rgbd/README.md
  examples/python/rgbd/rgbd.py
  lychee.toml
Labels: exclude from changelog

#9081 Fix warning about unused parameter
  crates/top/rerun/src/commands/entrypoint.rs
Labels: exclude from changelog, :ship: CI

#9068 Infer column partition size from shape in `Scalar.columns()`
  crates/build/re_types_builder/src/codegen/python/mod.rs
  examples/python/plots/plots.py
  rerun_py/rerun_sdk/rerun/archetypes/annotation_context.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows2d.py
  rerun_py/rerun_sdk/rerun/archetypes/arrows3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset3d.py
  rerun_py/rerun_sdk/rerun/archetypes/asset_video.py
  rerun_py/rerun_sdk/rerun/archetypes/bar_chart.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes2d.py
  rerun_py/rerun_sdk/rerun/archetypes/boxes3d.py
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
  rerun_py/rerun_sdk/rerun/archetypes/clear.py
  rerun_py/rerun_sdk/rerun/archetypes/depth_image.py
  rerun_py/rerun_sdk/rerun/archetypes/ellipsoids3d.py
  rerun_py/rerun_sdk/rerun/archetypes/encoded_image.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_line_strings.py
  rerun_py/rerun_sdk/rerun/archetypes/geo_points.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_edges.py
  rerun_py/rerun_sdk/rerun/archetypes/graph_nodes.py
  rerun_py/rerun_sdk/rerun/archetypes/image.py
  rerun_py/rerun_sdk/rerun/archetypes/instance_poses3d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips2d.py
  rerun_py/rerun_sdk/rerun/archetypes/line_strips3d.py
  rerun_py/rerun_sdk/rerun/archetypes/mesh3d.py
  rerun_py/rerun_sdk/rerun/archetypes/pinhole.py
  rerun_py/rerun_sdk/rerun/archetypes/points2d.py
  rerun_py/rerun_sdk/rerun/archetypes/points3d.py
  rerun_py/rerun_sdk/rerun/archetypes/scalar.py
  rerun_py/rerun_sdk/rerun/archetypes/segmentation_image.py
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/archetypes/tensor.py
  rerun_py/rerun_sdk/rerun/archetypes/text_document.py
  rerun_py/rerun_sdk/rerun/archetypes/text_log.py
  rerun_py/rerun_sdk/rerun/archetypes/transform3d.py
  rerun_py/rerun_sdk/rerun/archetypes/video_frame_reference.py
  rerun_py/rerun_sdk/rerun/archetypes/view_coordinates.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer1.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer2.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer3.py
  rerun_py/tests/test_types/archetypes/affix_fuzzer4.py
  rerun_py/tests/unit/test_scalar.py
Labels: enhancement, 🐍 Python API, examples, include in changelog, 🪵 Log & send APIs, 📈 plot

#9070 Make `IndexColumnDescriptor` members private
  crates/store/re_chunk/src/transport.rs
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/store/re_sorbet/src/column_descriptor_ref.rs
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/top/rerun/src/commands/rrd/filter.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  rerun_py/src/dataframe.rs
Labels: 🚜 refactor, exclude from changelog, 🔩 data model

#9053 RRD manifests bootstrap
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_log_types/src/time_point/mod.rs
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  scripts/ci/check_large_files.py
Labels: exclude from changelog, dataplatform

#9044 Include static chunks in all-component queries
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_chunk_store/tests/reads.rs
Labels: exclude from changelog

#9085 Fix non-final releases creating final-release git tags
  .github/workflows/release.yml
Labels: 🪳 bug, ⛴ release, exclude from changelog

#9083 Move URI handling logic to new `re_uri` crate
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  crates/store/re_data_source/Cargo.toml
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_uri/Cargo.toml
  crates/utils/re_uri/README.md
  crates/utils/re_uri/src/endpoints/catalog.rs
  crates/utils/re_uri/src/endpoints/mod.rs
  crates/utils/re_uri/src/endpoints/recording.rs
  crates/utils/re_uri/src/error.rs
  crates/utils/re_uri/src/lib.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/collection_ui.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  lychee.toml
Labels: exclude from changelog

#9088 Add command palette action for resetting to the default blueprint
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
Labels: 📺 re_viewer, include in changelog

#9092 Fix `insta` crate leaking into regular (non-testing) builds
  crates/store/re_dataframe/Cargo.toml
  deny.toml
  scripts/ci/rust_checks.py
Labels: 🦀 Rust API, dependencies, include in changelog

#9094 Do not generate debug symbols by default
  Cargo.toml
Labels: 🧑‍💻 dev experience, 🚀 performance, exclude from changelog

#9079 Plot series visibility separarate from entity visibility, handle multi-series visibility
  Cargo.lock
  Cargo.toml
  crates/store/re_types/definitions/rerun/archetypes/series_line.fbs
  crates/store/re_types/definitions/rerun/archetypes/series_point.fbs
  crates/store/re_types/definitions/rerun/components.fbs
  crates/store/re_types/definitions/rerun/components/SeriesVisible.fbs
  crates/store/re_types/src/archetypes/series_line.rs
  crates/store/re_types/src/archetypes/series_point.rs
  crates/store/re_types/src/components/.gitattributes
  crates/store/re_types/src/components/mod.rs
  crates/store/re_types/src/components/series_visible.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/marker_shape.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/SeriesVisible_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/SeriesVisible_placeholder.png
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_selection_panel/src/visible_time_range_ui.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_view_time_series/Cargo.toml
  crates/viewer/re_view_time_series/src/lib.rs
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
  crates/viewer/re_view_time_series/src/util.rs
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_viewer/src/ui/memory_panel.rs
  crates/viewer/re_viewer_context/src/blueprint_helpers.rs
  crates/viewer/re_viewer_context/src/query_context.rs
  crates/viewer/re_viewer_context/src/view/view_query.rs
  crates/viewer/re_viewport_blueprint/src/entity_add_info.rs
  crates/viewer/re_viewport_blueprint/src/view_contents.rs
  docs/content/reference/types/archetypes/series_line.md
  docs/content/reference/types/archetypes/series_point.md
  docs/content/reference/types/components.md
  docs/content/reference/types/components/.gitattributes
  docs/content/reference/types/components/series_visible.md
  docs/content/reference/types/datatypes/bool.md
  rerun_cpp/src/rerun/archetypes/series_line.cpp
  rerun_cpp/src/rerun/archetypes/series_line.hpp
  rerun_cpp/src/rerun/archetypes/series_point.cpp
  rerun_cpp/src/rerun/archetypes/series_point.hpp
  rerun_cpp/src/rerun/components.hpp
  rerun_cpp/src/rerun/components/.gitattributes
  rerun_cpp/src/rerun/components/series_visible.hpp
  rerun_py/rerun_sdk/rerun/archetypes/series_line.py
  rerun_py/rerun_sdk/rerun/archetypes/series_point.py
  rerun_py/rerun_sdk/rerun/components/.gitattributes
  rerun_py/rerun_sdk/rerun/components/__init__.py
  rerun_py/rerun_sdk/rerun/components/series_visible.py
  tests/rust/experimental_multi_scalar/src/main.rs
Labels: 📺 re_viewer, include in changelog, 📈 plot

#9095 gRPC spec update: make resource registration be catalog entry aware
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  examples/python/remote/metadata.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#9099 Fix `QueryManifest`'s missing catalog entry parameter
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
Labels: 🪳 bug, exclude from changelog, dataplatform

#9086 Persist servers and allow adding/removing them from the UI
  Cargo.lock
  Cargo.toml
  crates/store/re_data_source/src/data_source.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_uri/Cargo.toml
  crates/utils/re_uri/src/lib.rs
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/add_server_modal.rs
  crates/viewer/re_redap_browser/src/collection_ui.rs
  crates/viewer/re_redap_browser/src/collections.rs
  crates/viewer/re_redap_browser/src/context.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/requested_object.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer_context/src/async_runtime_handle.rs
  crates/viewer/re_viewer_context/src/lib.rs
Labels: ui, include in changelog, feat-redap-browser

#9104 Update maturin to 1.8.1 and fix `pyproject.toml`
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
Labels: 🐍 Python API, dependencies, include in changelog

#9106 Update ruff to 0.9.6
  examples/python/all_examples/all_examples/__init__.py
  examples/python/face_tracking/face_tracking.py
  examples/python/gesture_detection/gesture_detection.py
  examples/python/notebook/cube.ipynb
  examples/python/notebook/partial_updates.ipynb
  examples/python/notebook_neural_field_2d/neural_field_2d.ipynb
  examples/python/nuscenes_dataset/nuscenes_dataset/export_gps.py
  examples/python/ocr/ocr.py
  examples/python/segment_anything_model/segment_anything_model.py
  pixi.lock
  pixi.toml
  rerun_notebook/example.ipynb
  rerun_notebook/package-lock.json
  rerun_py/rerun_sdk/rerun/_baseclasses.py
  rerun_py/rerun_sdk/rerun/_log.py
  rerun_py/rerun_sdk/rerun/components/pinhole_projection.py
  rerun_py/tests/unit/test_box3d.py
  rerun_py/tests/unit/test_clear.py
  scripts/ci/bundle_and_upload_rerun_cpp.py
  scripts/ci/compare.py
  scripts/ci/crates.py
  scripts/ci/mdlint.py
  scripts/ci/python_check_signatures.py
  scripts/ci/setup_software_rasterizer.py
  scripts/ci/update_rerun_py_and_c_version.py
  scripts/fetch_crashes.py
  scripts/roundtrip_utils.py
  scripts/screenshot_compare/build_screenshot_compare.py
  tests/python/dataframe/examples.ipynb
Labels: dependencies, exclude from changelog

#9093 Build Rust snippets first then run them in parallel as a separate step
  docs/snippets/compare_snippet_output.py
Labels: 🔨 testing, exclude from changelog

#9114 Install cargo-deny `0.17` instead of latest
  scripts/ci/rust_checks.py
Labels: exclude from changelog

#9111 Remove ALPN from gRPC connection
  crates/store/re_grpc_client/src/redap/mod.rs
Labels: exclude from changelog

#9117 Add entity paths to manifest APIs
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
Labels: exclude from changelog, remote-store, dataplatform

#9118 Make remaining data fetching APIs catalog entry aware
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
  rerun_py/src/remote.rs
Labels: exclude from changelog, remote-store

#9042 Fetch time range
  .github/workflows/cargo_machete.yml
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_data_source/src/lib.rs
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_types/src/time_real.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_uri/Cargo.toml
  crates/utils/re_uri/src/endpoints/recording.rs
  crates/utils/re_uri/src/error.rs
  crates/utils/re_uri/src/lib.rs
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/history.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer/src/web_tools.rs
  crates/viewer/re_viewer_context/src/global_context/command_sender.rs
  crates/viewer/re_viewer_context/src/test_context.rs
Labels: exclude from changelog, dataplatform

#9121 Add support for collection enumeration to the remote store protocol
  Cargo.lock
  Cargo.toml
  crates/build/re_protos_builder/src/bin/build_re_remote_store_types.rs
  crates/store/re_protos/Cargo.toml
  crates/store/re_protos/proto/rerun/v0/collection.proto
  crates/store/re_protos/proto/rerun/v0/collection_ops.proto
  crates/store/re_protos/proto/rerun/v0/remote_store.proto
  crates/store/re_protos/src/v0/rerun.remote_store.v0.rs
Labels: exclude from changelog, remote-store

#9102 IMU data example
  examples/manifest.toml
  examples/python/imu_signals/.gitignore
  examples/python/imu_signals/README.md
  examples/python/imu_signals/imu_signals.py
  examples/python/imu_signals/pyproject.toml
Labels: examples, include in changelog

#9137 Add context menu action to copy entity paths to clipboard
  crates/viewer/re_context_menu/src/actions/copy_entity_path.rs
  crates/viewer/re_context_menu/src/actions/mod.rs
  crates/viewer/re_context_menu/src/lib.rs
Labels: 📺 re_viewer, include in changelog

#9142 Fix doclink
  crates/top/rerun/src/lib.rs
Labels: exclude from changelog

#9141 Expose functions to load LeRobot episodes
  crates/store/re_data_loader/src/lib.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#9145 Add refresh button to the collection UI
  crates/viewer/re_redap_browser/src/collection_ui.rs
  crates/viewer/re_redap_browser/src/collections.rs
  crates/viewer/re_redap_browser/src/servers.rs
Labels: ui, exclude from changelog, feat-redap-browser

#9154 Remove warning when asked to show an image in a tiny viewport
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
Labels: exclude from changelog

#9152 Fix shader compiluation failure in Chrome 131
  crates/viewer/re_renderer/shader/point_cloud.wgsl
Labels: 🪳 bug, 🕸️ web, 🔺 re_renderer, include in changelog

#9155 Handle `SetFocus` system command in `TestContext`
  crates/viewer/re_viewer_context/src/test_context.rs
  crates/viewer/re_viewport_blueprint/src/test_context_ext.rs
Labels: 🔨 testing, exclude from changelog

#9149 Fix multi-value `Scalar` breaking legend disambiguation
  Cargo.lock
  crates/viewer/re_view_time_series/Cargo.toml
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
Labels: ui, 🦟 regression, exclude from changelog

#9157 Better support for catalog on web
  crates/viewer/re_ui/src/command.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/history.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer/src/web_tools.rs
Labels: exclude from changelog
