Repository rerun-io/rerun, pull requests merged in 2025-09, with the labels that each got.

#11060 Add `.editorconfig` with correct settings for `.ron` files
  .editorconfig
Labels: 🧑‍💻 dev experience, include in changelog

#11063 Adjust label checker & changelog gen to use `sdk-` prefixed labels
  .github/workflows/labels.yml
  scripts/generate_changelog.py
Labels: exclude from changelog, :ship: CI

#11066 Adjust label checker & changelog gen to use sdk- prefixed labels
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog

#11067 Re-apply some reverted things
  crates/build/re_types_builder/src/codegen/cpp/array_builder.rs
  crates/build/re_types_builder/src/codegen/cpp/mod.rs
  crates/build/re_types_builder/src/codegen/docs/website.rs
  crates/build/re_types_builder/src/codegen/python/mod.rs
  crates/build/re_types_builder/src/codegen/rust/api.rs
  crates/build/re_types_builder/src/codegen/rust/arrow.rs
  crates/build/re_types_builder/src/codegen/rust/deserializer.rs
  crates/build/re_types_builder/src/codegen/rust/serializer.rs
  crates/build/re_types_builder/src/data_type.rs
  crates/build/re_types_builder/src/objects.rs
  crates/build/re_types_builder/src/type_registry.rs
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_chunk/src/iter.rs
  crates/store/re_data_loader/src/loader_archetype.rs
  crates/store/re_sorbet/src/migrations/mod.rs
  crates/store/re_types/definitions/rerun/attributes.fbs
  crates/store/re_types/src/archetypes/asset_video_ext.rs
  crates/store/re_types/src/blueprint/datatypes/component_column_selector.rs
  crates/store/re_types/src/blueprint/datatypes/selected_columns.rs
  crates/store/re_types/src/datatypes/annotation_info.rs
  crates/store/re_types/src/datatypes/tensor_data.rs
  crates/store/re_types/src/datatypes/utf8pair.rs
  crates/store/re_types/src/testing/components/affix_fuzzer10.rs
  crates/store/re_types/src/testing/components/affix_fuzzer12.rs
  crates/store/re_types/src/testing/components/affix_fuzzer13.rs
  crates/store/re_types/src/testing/components/affix_fuzzer9.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer1.rs
  crates/store/re_types/src/testing/datatypes/affix_fuzzer20.rs
  crates/store/re_types/src/testing/datatypes/string_component.rs
  crates/store/re_types_core/src/datatypes/entity_path.rs
  crates/store/re_types_core/src/datatypes/utf8.rs
  crates/store/re_types_core/src/datatypes/visible_time_range.rs
  crates/top/rerun_c/src/video.rs
  crates/utils/re_arrow_util/src/arrays.rs
  crates/utils/re_arrow_util/src/lib.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/viewer/re_ui/src/arrow_ui.rs
  rerun_py/rerun_sdk/rerun/_converters.py
Labels: exclude from changelog

#11029 Add `tzdata` dependency to fix Windows CI
  rerun_py/tests/unit/test_datafusion_tables.py
Labels: 🪟 windows, exclude from changelog, :ship: CI

#11061 Implement full text filtering for string-based columns of the table widget
  Cargo.toml
  crates/viewer/re_dataframe_ui/src/datafusion_adapter.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/filter_ui.rs
  crates/viewer/re_dataframe_ui/src/filters.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_ui_string_contains.png
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_ui_string_contains_empty.png
  crates/viewer/re_dataframe_ui/tests/snapshots/popup_ui_string_contains.png
  crates/viewer/re_dataframe_ui/tests/snapshots/popup_ui_string_contains_empty.png
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_ui/data/dark_theme.ron
  crates/viewer/re_ui/data/icons/filter.svg
  crates/viewer/re_ui/data/light_theme.ron
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/ui_ext.rs
  pixi.toml
Labels: enhancement, ui, include in changelog, feat-redap-browser

#11080 cpp-build-snippets can now run in `min-wheel-test` environment, report ci disk usage
  .github/workflows/reusable_test_wheels.yml
  pixi.lock
  pixi.toml
Labels: exclude from changelog, :ship: CI

#11081 Added release calendar for Python
  rerun_py/docs/gen_common_index.py
Labels: 📖 documentation, include in changelog

#11088 Refactor `re_grpc_server`
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_types/src/arrow_msg.rs
  crates/store/re_protos/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#11086 Use `opened_store_id_or_recommended()` in URDF loader
  crates/store/re_data_loader/src/loader_urdf.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#11097 Update alpha-release-related information
  .github/workflows/release.yml
  RELEASES.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#11087 Fix link checker (again)
  .github/workflows/reusable_checks.yml
  RELEASES.md
  crates/viewer/re_ui/data/Inter-README.txt
  lychee.toml
Labels: 🪳 bug, exclude from changelog, :ship: CI

#11094 Make sure our python deprecation notices end up in docs
  pixi.lock
  pixi.toml
  rerun_py/mkdocs.yml
  rerun_py/pyproject.toml
Labels: 📖 documentation, sdk-python, include in changelog

#11052 Add `rcl_interfaces/msg/Log` MessageParser
  crates/utils/re_mcap/src/layers/ros2.rs
  crates/utils/re_mcap/src/parsers/ros2msg/definitions/mod.rs
  crates/utils/re_mcap/src/parsers/ros2msg/definitions/rcl_interfaces.rs
  crates/utils/re_mcap/src/parsers/ros2msg/mod.rs
  crates/utils/re_mcap/src/parsers/ros2msg/rcl_interfaces/log.rs
  crates/utils/re_mcap/src/parsers/ros2msg/rcl_interfaces/mod.rs
Labels: 📺 re_viewer, include in changelog, feat-mcap

#11106 Fix JS artifacts publishing
  rerun_js/scripts/publish.mjs
Labels: exclude from changelog

#11108 Alpha release: better process for GH releases and changelog
  .github/workflows/release.yml
  RELEASES.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#11117 Add data inline viewer validity test
  docs/content/howto/logging/send-columns.md
  scripts/ci/mdlint.py
Labels: 📖 documentation, 🔨 testing, include in changelog

#11077 End-to-end out-of-band entry headers: kickoff
  Cargo.lock
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/cloud.proto
  crates/store/re_protos/src/headers.rs
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.cloud.v1alpha1.rs
  crates/store/re_redap_client/src/connection_client.rs
  crates/store/re_redap_client/src/grpc.rs
  crates/store/re_server/Cargo.toml
  crates/store/re_server/src/rerun_cloud.rs
  crates/utils/re_perf_telemetry/src/grpc.rs
Labels: exclude from changelog, dataplatform

#11122 Default to webGL on firefox web-viewer
  Cargo.toml
  crates/viewer/re_renderer/src/device_caps.rs
Labels: 🕸️ web, 💣 crash, exclude from changelog

#11123 Add some explanations for proto breaking changes
  .github/workflows/reusable_checks_protobuf.yml
  pixi.toml
Labels: 📖 documentation, 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#11114 Tell the user about the native viewer
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_log_types/src/index/timestamp.rs
  crates/store/re_log_types/src/index/timestamp_format.rs
  crates/viewer/re_global_context/src/command_sender.rs
  crates/viewer/re_selection_panel/tests/snapshots/selection_panel_component_hybrid_overwrite.png
  crates/viewer/re_selection_panel/tests/snapshots/selection_panel_component_static_overwrite.png
  crates/viewer/re_test_context/src/lib.rs
  crates/viewer/re_ui/data/icons/error.svg
  crates/viewer/re_ui/data/icons/info.svg
  crates/viewer/re_ui/data/icons/success.svg
  crates/viewer/re_ui/data/icons/warn.svg
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/notifications.rs
  crates/viewer/re_ui/src/time.rs
  crates/viewer/re_ui/tests/snapshots/alert.png
  crates/viewer/re_view_dataframe/tests/snapshots/unknown_timeline_view_ui.png
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/tests/snapshots/open_url_modal__invalid_url.png
  crates/viewer/re_viewer/tests/snapshots/open_url_modal__no_url.png
  crates/viewer/re_viewer/tests/snapshots/settings_screen.png
Labels: 🕸️ web, ui, 📺 re_viewer, include in changelog

#11133 Show welcome screen when all recordings are closed
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/navigation.rs
  crates/viewer/re_viewer_context/src/store_hub.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#11129 Improve numpy 1 compatibility
  crates/build/re_types_builder/src/codegen/python/mod.rs
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/_numpy_compatibility.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/tensor_dimension_index_slider.py
  rerun_py/rerun_sdk/rerun/datatypes/angle.py
  rerun_py/rerun_sdk/rerun/datatypes/blob.py
  rerun_py/rerun_sdk/rerun/datatypes/class_id.py
  rerun_py/rerun_sdk/rerun/datatypes/dvec2d.py
  rerun_py/rerun_sdk/rerun/datatypes/float32.py
  rerun_py/rerun_sdk/rerun/datatypes/float64.py
  rerun_py/rerun_sdk/rerun/datatypes/keypoint_id.py
  rerun_py/rerun_sdk/rerun/datatypes/mat3x3.py
  rerun_py/rerun_sdk/rerun/datatypes/mat4x4.py
  rerun_py/rerun_sdk/rerun/datatypes/plane3d.py
  rerun_py/rerun_sdk/rerun/datatypes/quaternion.py
  rerun_py/rerun_sdk/rerun/datatypes/range1d.py
  rerun_py/rerun_sdk/rerun/datatypes/rgba32.py
  rerun_py/rerun_sdk/rerun/datatypes/time_int.py
  rerun_py/rerun_sdk/rerun/datatypes/uint16.py
  rerun_py/rerun_sdk/rerun/datatypes/uint32.py
  rerun_py/rerun_sdk/rerun/datatypes/uint64.py
  rerun_py/rerun_sdk/rerun/datatypes/uuid.py
  rerun_py/rerun_sdk/rerun/datatypes/uvec2d.py
  rerun_py/rerun_sdk/rerun/datatypes/uvec3d.py
  rerun_py/rerun_sdk/rerun/datatypes/uvec4d.py
  rerun_py/rerun_sdk/rerun/datatypes/vec2d.py
  rerun_py/rerun_sdk/rerun/datatypes/vec3d.py
  rerun_py/rerun_sdk/rerun/datatypes/vec4d.py
  rerun_py/rerun_sdk/rerun/datatypes/video_timestamp.py
  rerun_py/rerun_sdk/rerun/datatypes/view_coordinates.py
  rerun_py/tests/test_types/components/affix_fuzzer11.py
  rerun_py/tests/test_types/components/affix_fuzzer8.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer2.py
  rerun_py/tests/test_types/datatypes/affix_fuzzer22.py
  rerun_py/tests/test_types/datatypes/flattened_scalar.py
  rerun_py/tests/test_types/datatypes/primitive_component.py
Labels: sdk-python, include in changelog

#11125 Ensure syntax highlighting methods are consistently documented
  crates/viewer/re_ui/src/syntax_highlighting.rs
Labels: ui, exclude from changelog

#11131 Add the ability to sort `Drawables` (new subdivision of `DrawData`) to `re_renderer`
  crates/viewer/re_renderer/src/allocator/cpu_write_gpu_read_belt.rs
  crates/viewer/re_renderer/src/allocator/gpu_readback_belt.rs
  crates/viewer/re_renderer/src/context.rs
  crates/viewer/re_renderer/src/draw_phase_manager.rs
  crates/viewer/re_renderer/src/draw_phases/mod.rs
  crates/viewer/re_renderer/src/lib.rs
  crates/viewer/re_renderer/src/queueable_draw_data.rs
  crates/viewer/re_renderer/src/renderer/compositor.rs
  crates/viewer/re_renderer/src/renderer/debug_overlay.rs
  crates/viewer/re_renderer/src/renderer/depth_cloud.rs
  crates/viewer/re_renderer/src/renderer/generic_skybox.rs
  crates/viewer/re_renderer/src/renderer/lines.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_renderer/src/renderer/mod.rs
  crates/viewer/re_renderer/src/renderer/point_cloud.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_renderer/src/renderer/test_triangle.rs
  crates/viewer/re_renderer/src/renderer/world_grid.rs
  crates/viewer/re_renderer/src/resource_managers/yuv_converter.rs
  crates/viewer/re_renderer/src/view_builder.rs
  crates/viewer/re_renderer_examples/2d.rs
  crates/viewer/re_renderer_examples/depth_cloud.rs
  crates/viewer/re_renderer_examples/depth_offset.rs
  crates/viewer/re_renderer_examples/multiview.rs
  crates/viewer/re_renderer_examples/outlines.rs
  crates/viewer/re_renderer_examples/picking.rs
  crates/viewer/re_renderer_examples/world_grid.rs
  crates/viewer/re_view_map/src/visualizers/geo_line_strings.rs
  crates/viewer/re_view_map/src/visualizers/geo_points.rs
  crates/viewer/re_view_spatial/src/ui_2d.rs
  crates/viewer/re_view_spatial/src/ui_3d.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/mod.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/re_renderer_callback.rs
Labels: 🔺 re_renderer, 🚜 refactor, exclude from changelog

#11151 Clean up `re_perf_telemetry` related code
  ARCHITECTURE.md
  Cargo.toml
  crates/top/rerun-cli/Cargo.toml
  crates/top/rerun-cli/src/bin/rerun.rs
  crates/top/rerun/Cargo.toml
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_perf_telemetry/Cargo.toml
  crates/utils/re_perf_telemetry/README.md
  crates/utils/re_perf_telemetry/src/lib.rs
  crates/utils/re_perf_telemetry/src/metrics_server.rs
  rerun_py/src/python_bridge.rs
Labels: 😤 annoying, 🚜 refactor, exclude from changelog

#11158 Try to resolve snippet errors
  docs/snippets/CMakeLists.txt
  docs/snippets/INDEX.md
  docs/snippets/all/tutorials/any_values.py
  docs/snippets/all/tutorials/dynamic_archetype.cpp
  docs/snippets/all/tutorials/dynamic_archetype.py
  docs/snippets/all/tutorials/dynamic_archetype.rs
  pixi.toml
  rerun_py/rerun_sdk/rerun/any_value.py
  tests/assets/rrd/snippets/tutorials/dynamic_archetype.rrd
Labels: sdk-python, exclude from changelog

#11135 Refactor setting selection to always use system commands
  Cargo.lock
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_context_menu/src/actions/add_entities_to_new_view.rs
  crates/viewer/re_context_menu/src/actions/clone_view.rs
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_global_context/Cargo.toml
  crates/viewer/re_global_context/src/command_sender.rs
  crates/viewer/re_global_context/src/item_collection.rs
  crates/viewer/re_global_context/src/lib.rs
  crates/viewer/re_recording_panel/src/recording_panel_ui.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  crates/viewer/re_view_graph/src/ui/draw.rs
  crates/viewer/re_view_graph/src/view.rs
  crates/viewer/re_view_map/src/map_view.rs
  crates/viewer/re_view_tensor/src/view_class.rs
  crates/viewer/re_view_text_document/src/view_class.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/open_url.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/selection_state.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 📺 re_viewer, 🚜 refactor, exclude from changelog

#11127 Changelog generation to use native gh CLI auth
  pixi.lock
  pixi.toml
  scripts/generate_changelog.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#11167 Add Example Of LeRobot Dataloader
  docs/content/getting-started/data-in/open-any-file.md
  examples/manifest.toml
  examples/python/lerobot/README.md
  examples/python/lerobot_loader/README.md
Labels: 📖 documentation, exclude from changelog

#11210 CI: Fix retry on windows runners
  .github/workflows/reusable_test_wheels.yml
Labels: exclude from changelog, :ship: CI

#11212 update changed mesh3d instance rrd
  tests/assets/rrd/snippets/archetypes/mesh3d_instancing.rrd
Labels: 🔨 testing, exclude from changelog, :ship: CI

#11214 Fix outlines not showing sometimes for individual instances
  crates/store/re_entity_db/src/instance_path.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_renderer/src/renderer/mesh_renderer.rs
  crates/viewer/re_test_context/src/lib.rs
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_view_spatial/tests/select_box_instances.rs
  crates/viewer/re_view_spatial/tests/snapshots/select_box_instances_0.png
  crates/viewer/re_view_spatial/tests/snapshots/select_box_instances_1.png
  crates/viewer/re_view_spatial/tests/snapshots/select_box_instances_all.png
  crates/viewer/re_view_time_series/src/line_visualizer_system.rs
  crates/viewer/re_view_time_series/src/point_visualizer_system.rs
Labels: 🪳 bug, exclude from changelog, release-oss-0.25

#11198 Bump our minimum macos for examples
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, 😤 annoying, examples, exclude from changelog, :apple: MacOS

#11093 Prevent arow_cpp from configuring/building/installing all the time
  rerun_cpp/download_and_build_arrow.cmake
Labels: sdk-cpp, include in changelog

#11220 dataplatform: make traceheaders struct serde friendly
  crates/utils/re_perf_telemetry/src/lib.rs
Labels: exclude from changelog, dataplatform

#11219 Use Display for DataTypes, not Debug formatting
  Cargo.lock
  crates/store/re_data_loader/src/loader_lerobot.rs
  crates/store/re_sorbet/src/index_column_descriptor.rs
  crates/store/re_sorbet/src/row_id_column_descriptor.rs
  crates/store/re_types/src/archetypes/depth_image_ext.rs
  crates/store/re_types/src/archetypes/image_ext.rs
  crates/store/re_types/src/components/image_buffer_ext.rs
  crates/store/re_types_core/src/reflection.rs
  crates/store/re_types_core/src/result.rs
  crates/top/rerun/src/commands/rrd/verify.rs
  crates/utils/re_arrow_util/src/format_data_type.rs
  crates/viewer/re_chunk_store_ui/Cargo.toml
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
Labels: ui, 🧑‍💻 dev experience, exclude from changelog

#11225 Fix wrong rendering of some texture formats in light mode
  crates/viewer/re_renderer/shader/rectangle.wgsl
  crates/viewer/re_renderer/shader/rectangle_fs.wgsl
  crates/viewer/re_renderer/src/renderer/mod.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_view_tensor/src/tensor_slice_to_gpu.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/colormap.rs
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
Labels: 🪳 bug, 🔺 re_renderer, include in changelog

#11230 Fix: Patch blueprint id when forced_application_id is set
  crates/store/re_data_loader/src/loader_rrd.rs
Labels: 🪳 bug, 🟦 blueprint, exclude from changelog, release-oss-0.25

#11228 Add Ability to Visualize Partial LeRobot Dataset
  crates/store/re_data_loader/src/lerobot.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: dogfooding, include in changelog, 🪵 Log & send APIs

#11226 Bump re_mp4 to 0.4.0
  .typos.toml
  Cargo.lock
  Cargo.toml
Labels: 🪳 bug, include in changelog, feat-video

#11237 Fix table UI not saying switch to when opening a certain links
  crates/utils/re_smart_channel/src/lib.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
Labels: 🪳 bug, ui, 📺 re_viewer, include in changelog, dataplatform

#11241 Fix title bar height on macOS Tahoe
  Cargo.lock
  Cargo.toml
  crates/viewer/re_ui/Cargo.toml
  crates/viewer/re_ui/README.md
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/src/context_ext.rs
  crates/viewer/re_ui/src/egui_ext/mac_traffic_light_sizes.rs
  crates/viewer/re_ui/src/egui_ext/mod.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog, :apple: MacOS

#11242 Add copy button to the recording link table item
  Cargo.lock
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_viewer_context/src/open_url.rs
Labels: ui, 📺 re_viewer, include in changelog

#11249 Move remaining things into workspace deps
  Cargo.toml
  crates/store/re_datafusion/Cargo.toml
  tests/rust/plot_dashboard_stress/Cargo.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#11255 Remove release blogpost link
  CHANGELOG.md
Labels: exclude from changelog

#11251 Fix space origin editor resetting & closing immediately
  crates/viewer/re_selection_panel/src/view_space_origin_ui.rs
Labels: 🪳 bug, include in changelog, consider-patch

#11246 Keep last paused time in web-viewer url
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/time_control.rs
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#11247 Fix some menu buttons closing unexpectedly
  crates/viewer/re_ui/src/list_item/item_buttons.rs
  crates/viewer/re_ui/src/section_collapsing_header.rs
Labels: 🪳 bug, include in changelog, consider-patch

#11265 Improve rrd loading errors by checking FourCC first
  crates/store/re_data_loader/src/loader_rrd.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/encoder.rs
  crates/store/re_log_encoding/src/lib.rs
  crates/viewer/re_recording_panel/src/recording_panel_ui.rs
Labels: 🧑‍💻 dev experience, include in changelog

#11267 Fix `to_arrow_reader` causing an error for streaming providers
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
  rerun_py/src/arrow.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/datafusion_table.rs
  rerun_py/src/catalog/table_entry.rs
  rerun_py/tests/unit/test_datafusion_tables.py
Labels: 🪳 bug, exclude from changelog, dataplatform

#11262 Refactor boolean column filtering code for clarity
  crates/viewer/re_dataframe_ui/src/filters/boolean.rs
  crates/viewer/re_dataframe_ui/src/filters/boolean_filter.rs
  crates/viewer/re_dataframe_ui/src/filters/filter.rs
  crates/viewer/re_dataframe_ui/src/filters/filter_ui.rs
  crates/viewer/re_dataframe_ui/src/filters/mod.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/tests/filter_tests.rs
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_non_nullable@both_null_true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_non_nullable@inner_null_true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_non_nullable@no_null_true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_non_nullable@outer_null_true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_nullable@both_null.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_nullable@inner_null.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals_list_nullable@outer_null.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__non_nullable_boolean_equals@false.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__non_nullable_boolean_equals@nulls_false.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__non_nullable_boolean_equals@nulls_true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__non_nullable_boolean_equals@true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__nullable_boolean_equals@nulls_false.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__nullable_boolean_equals@nulls_null.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__nullable_boolean_equals@nulls_true.snap
Labels: 🚜 refactor, exclude from changelog

#11278 Format `RecordBatch` with redactions for non-deterministic values
  Cargo.lock
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/tests/formatting.rs
  crates/store/re_chunk/tests/snapshots/formatting__format_chunk.snap
  crates/store/re_chunk/tests/snapshots/formatting__format_chunk_redacted.snap
  crates/store/re_format_arrow/src/lib.rs
  crates/top/rerun/src/commands/rrd/compare.rs
  crates/top/rerun/src/commands/rrd/print.rs
Labels: exclude from changelog

#11283 Add "🧢 MCAP" section to future `CHANGELOG.md`s
  .github/workflows/labels.yml
  scripts/generate_changelog.py
Labels: exclude from changelog, 🧢 MCAP

#11280 Add support for `enum` in protobuf MCAP messages
  Cargo.lock
  crates/store/re_data_loader/tests/assets/simple_protobuf_vec3.mcap
  crates/store/re_data_loader/tests/snapshots/test.snap
  crates/store/re_data_loader/tests/snapshots/test_mcap_loader__tests__assert_chunk_snapshot@simple_protobuf_vec3.mcap.snap
  crates/store/re_data_loader/tests/snapshots/test_mcap_loader__tests__assert_chunk_snapshot@supported_ros2_messages.mcap.snap
  crates/store/re_data_loader/tests/snapshots/test_mcap_loader__tests__ros2.snap
  crates/store/re_data_loader/tests/test_mcap_loader.rs
  crates/utils/re_mcap/Cargo.toml
  crates/utils/re_mcap/src/layers/protobuf.rs
  crates/utils/re_mcap/src/layers/snapshots/re_mcap__layers__protobuf__test__two_simple_rows.snap
Labels: include in changelog, 🧢 MCAP

#11317 Ignore 3rd party C++ libraries from link checker
  lychee.toml
Labels: exclude from changelog, :ship: CI

#11314 Python SDK: remove `blocking` argument of `flush`
  docs/content/reference/migration.md
  docs/content/reference/migration/migration-0-26.md
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/src/python_bridge.rs
Labels: sdk-python, include in changelog

#11296 Add optional viewer url parameter to web app options
  crates/build/re_types_builder/src/codegen/common.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/src/startup_options.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer/src/web_tools.rs
  rerun_js/web-viewer/index.ts
Labels: 🕸️ web, 📺 re_viewer, include in changelog

#11324 Remove `reqwest` spam when using maps
  crates/utils/re_log/src/lib.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#11309 Automates version check
  rerun_py/tests/unit/test_version.py
  tests/python/release_checklist/check_version.py
Labels: exclude from changelog

#11325 Only include web url for copies in web-viewer
  crates/viewer/re_viewer/src/app.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#11323 Automates entity view tests for tensors and text
  Cargo.lock
  crates/viewer/re_view_tensor/tests/snapshots/tensor_2d_both.png
  crates/viewer/re_view_tensor/tests/snapshots/tensor_2d_root.png
  crates/viewer/re_view_tensor/tests/snapshots/tensor_2d_t1.png
  crates/viewer/re_view_tensor/tests/snapshots/tensor_2d_t2.png
  crates/viewer/re_view_tensor/tests/tensor_2d.rs
  crates/viewer/re_view_text_document/Cargo.toml
  crates/viewer/re_view_text_document/tests/snapshots/text_view_both.png
  crates/viewer/re_view_text_document/tests/snapshots/text_view_one.png
  crates/viewer/re_view_text_document/tests/snapshots/text_view_root.png
  crates/viewer/re_view_text_document/tests/snapshots/text_view_two.png
  crates/viewer/re_view_text_document/tests/text_document_test.rs
  tests/python/release_checklist/check_mono_entity_views.py
Labels: exclude from changelog

#11291 Update DataFusion to version 49.0.2
  Cargo.lock
  Cargo.toml
  crates/store/re_datafusion/src/dataframe_query_common.rs
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  crates/store/re_datafusion/src/dataframe_query_provider_wasm.rs
  crates/viewer/re_dataframe_ui/src/filters/filter.rs
  deny.toml
  docs/content/reference/migration/migration-0-26.md
  pixi.lock
  pixi.toml
  rerun_notebook/package-lock.json
  rerun_py/pyproject.toml
Labels: 🏹 arrow, dependencies, include in changelog, dataplatform

#11342 Fix running pytest in strict mode
  rerun_py/tests/unit/test_any_values.py
Labels: 🔨 testing, sdk-python, 🧑‍💻 dev experience, exclude from changelog

#11330 Fix url edit warning spam
  Cargo.lock
  crates/utils/re_uri/Cargo.toml
  crates/utils/re_uri/src/endpoints/dataset.rs
  crates/utils/re_uri/src/fragment.rs
Labels: 📺 re_viewer, 😤 annoying, include in changelog

#11341 Add support for `starts with` and `ends with` to string filter
  crates/viewer/re_dataframe_ui/src/filters/boolean.rs
  crates/viewer/re_dataframe_ui/src/filters/filter.rs
  crates/viewer/re_dataframe_ui/src/filters/filter_ui.rs
  crates/viewer/re_dataframe_ui/src/filters/mod.rs
  crates/viewer/re_dataframe_ui/src/filters/string.rs
  crates/viewer/re_dataframe_ui/src/filters/timestamp.rs
  crates/viewer/re_dataframe_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/tests/filter_tests.rs
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__boolean_equals@nulls_true.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@a.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@a_uppercase.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@empty.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@ends_with_c.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@nulls_a.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@nulls_empty.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@nulls_ends_with_c.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@nulls_starts_with_b.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_contains@starts_with_b.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@both_null_Contains_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@both_null_EndsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@both_null_StartsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@inner_null_Contains_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@inner_null_EndsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@inner_null_StartsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@no_null_Contains_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@no_null_EndsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@no_null_StartsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@outer_null_Contains_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@outer_null_EndsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_tests__string_list@outer_null_StartsWith_ab.snap
  crates/viewer/re_dataframe_ui/tests/snapshots/filter_ui_string_starts_with.png
  crates/viewer/re_dataframe_ui/tests/snapshots/popup_ui_string_contains.png
  crates/viewer/re_dataframe_ui/tests/snapshots/popup_ui_string_contains_empty.png
  crates/viewer/re_dataframe_ui/tests/snapshots/popup_ui_string_starts_with.png
Labels: ui, include in changelog

#11302 Improve robustness of rrd loader
  .vscode/launch.json
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/stream_rrd_from_http.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#11340 Mark valid data ranges in timeline when loading data via range-limited URL
  Cargo.lock
  crates/store/re_log_types/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.log_msg.v1alpha1.ext.rs
  crates/store/re_redap_client/src/grpc.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_data_ui/src/entity_db.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_global_context/src/command_sender.rs
  crates/viewer/re_selection_panel/tests/snapshots/selection_panel_recording.png
  crates/viewer/re_test_context/src/lib.rs
  crates/viewer/re_time_panel/benches/bench_density_graph.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/time_axis.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/src/time_ranges_ui.rs
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections_with_two_valid_ranges.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections_with_two_valid_ranges_zoomed_out.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections_with_valid_range.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections_with_valid_range_zoomed_out.png
  crates/viewer/re_time_panel/tests/time_panel_tests.rs
  crates/viewer/re_ui/data/dark_theme.ron
  crates/viewer/re_ui/data/light_theme.ron
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/viewer_analytics/event.rs
  crates/viewer/re_viewer_context/Cargo.toml
  crates/viewer/re_viewer_context/src/time_control.rs
Labels: ui, 📺 re_viewer, include in changelog, dataplatform

#11363 generate_changelog.py: explain employees vs externals
  scripts/generate_changelog.py
Labels: 🧑‍💻 dev experience, ⛴ release, exclude from changelog

#11370 Fix LeRobot release checklist item
  tests/python/release_checklist/check_lerobot_dataloader.py
Labels: 🪳 bug, ⛴ release, exclude from changelog

#11346 Support registering the table zoo to a local server
  examples/manifest.toml
  examples/python/table_zoo/README.md
  examples/python/table_zoo/pyproject.toml
  examples/python/table_zoo/table_zoo.py
  rerun_py/.non_sdk_mypy.ini
  tests/python/table_zoo/table_zoo.py
Labels: 🧑‍💻 dev experience, exclude from changelog

#11362 Remove some dead code from `re_redap_client`
  Cargo.lock
  crates/store/re_redap_client/Cargo.toml
  crates/store/re_redap_client/src/grpc.rs
  crates/store/re_redap_client/src/lib.rs
Labels: 🚜 refactor, exclude from changelog

#11365 Fix race condition for ui adjustments while loading recordings from redap client
  crates/store/re_data_loader/src/load_file.rs
  crates/store/re_data_source/src/data_source.rs
  crates/store/re_data_source/src/load_stdin.rs
  crates/store/re_grpc_client/src/read.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_encoding/src/stream_rrd_from_http.rs
  crates/store/re_log_types/src/data_source_message.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_redap_client/Cargo.toml
  crates/store/re_redap_client/src/grpc.rs
  crates/store/re_redap_client/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_global_context/src/command_sender.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/app_state.rs
  crates/viewer/re_viewer/src/native.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  crates/viewer/re_viewer/src/web.rs
  crates/viewer/re_viewer_context/src/open_url.rs
  crates/viewer/re_viewer_context/src/viewer_context.rs
Labels: 🪳 bug, include in changelog, dataplatform

#11364 fix formatting and parsing of component paths in links
  crates/store/re_chunk_store/src/query.rs
  crates/store/re_dataframe/src/query.rs
  crates/store/re_entity_db/src/instance_path.rs
  crates/store/re_log_types/src/path/component_path.rs
  crates/store/re_log_types/src/path/data_path.rs
  crates/store/re_log_types/src/path/parse_path.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/utils/re_smart_channel/src/lib.rs
  crates/utils/re_uri/src/redap_uri.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/component_path.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_global_context/src/item.rs
  crates/viewer/re_selection_panel/src/item_heading_no_breadcrumbs.rs
  crates/viewer/re_selection_panel/src/item_title.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_test_context/src/lib.rs
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_time_panel/src/streams_tree_data.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_ui/src/syntax_highlighting.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer_context/src/open_url.rs
Labels: 🪳 bug, 📺 re_viewer, 🚜 refactor, include in changelog

#11379 Share button on notebook no longer uses the current base url for web viewer urls
  crates/top/rerun/src/commands/entrypoint.rs
  crates/viewer/re_viewer/src/startup_options.rs
  crates/viewer/re_viewer/src/web.rs
  rerun_js/web-viewer/index.ts
  rerun_notebook/src/js/widget.ts
Labels: 🪳 bug, notebook, include in changelog

#11387 Mask platform-specific menu entry in app kittest
  crates/viewer/re_viewer/tests/app_kittest.rs
  crates/viewer/re_viewer/tests/snapshots/menu_without_recording.png
Labels: 🔨 testing, exclude from changelog
