Repository rerun-io/rerun, pull requests merged in 2025-06, with the labels that each got.

#10109 Always enable `svg` feature on `egui_extras`, fixing svgs for viewer embedding examples
  Cargo.toml
Labels: 🦟 regression, exclude from changelog

#10039 Implement gRPC versioning APIs
  crates/build/re_build_info/src/build_info.rs
  crates/build/re_build_info/src/crate_version.rs
  crates/build/re_build_info/src/lib.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/top/rerun/src/commands/entrypoint.rs
  crates/utils/re_analytics/src/lib.rs
  crates/utils/re_crash_handler/src/lib.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
Labels: exclude from changelog, dataplatform

#10115 Forbid accessing files when compiling for Wasm
  crates/build/re_build_tools/src/lib.rs
  crates/build/re_build_tools/src/rebuild_detector.rs
  crates/store/re_chunk_store/src/store.rs
  crates/store/re_dataframe/src/engine.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/viewer/re_global_context/src/app_options.rs
  crates/viewer/re_renderer/build.rs
  crates/viewer/re_renderer/src/wgpu_resources/shader_module_pool.rs
  scripts/clippy_wasm/clippy.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#10118 Only treat executable files as data loaders
  Cargo.lock
  crates/store/re_data_loader/Cargo.toml
  crates/store/re_data_loader/src/loader_external.rs
Labels: 🧑‍💻 dev experience, 😤 annoying, exclude from changelog

#10134 Fix errors in getting-started/data-in documentation
  docs/content/getting-started/data-in/cpp.md
  docs/content/getting-started/data-in/rust.md
Labels: 📖 documentation, include in changelog

#10123 Prepare `re_video` and `re_renderer::VideoPlayer` for streaming video
  clippy.toml
  crates/store/re_types/src/archetypes/asset_video_ext.rs
  crates/top/rerun_c/src/video.rs
  crates/utils/re_video/benches/video_load_bench.rs
  crates/utils/re_video/examples/frames.rs
  crates/utils/re_video/src/decode/av1.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/decode/webcodecs.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/utils/re_video/src/demux/mp4.rs
  crates/utils/re_video/src/lib.rs
  crates/utils/re_video/src/stable_index_deque.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_renderer/src/video/chunk_decoder.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_renderer/src/video/player.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer_context/src/cache/video_cache.rs
  rerun_py/src/video.rs
  scripts/clippy_wasm/clippy.toml
Labels: exclude from changelog, 🎞️ video

#10125 Prepare video visualizer for upcoming stream visualizer
  crates/store/re_types/src/components/draw_order_ext.rs
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_renderer/src/renderer/rectangles.rs
  crates/viewer/re_view_spatial/src/contexts/depth_offsets.rs
  crates/viewer/re_view_spatial/src/visualizers/depth_images.rs
  crates/viewer/re_view_spatial/src/visualizers/encoded_image.rs
  crates/viewer/re_view_spatial/src/visualizers/images.rs
  crates/viewer/re_view_spatial/src/visualizers/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/segmentation_images.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/entity_iterator.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/spatial_view_visualizer.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/textured_rect.rs
  crates/viewer/re_view_spatial/src/visualizers/video/mod.rs
  crates/viewer/re_view_spatial/src/visualizers/video/video_frame_reference.rs
  crates/viewer/re_view_spatial/src/visualizers/videos.rs
  crates/viewer/re_viewer_context/src/cache/image_decode_cache.rs
  crates/viewer/re_viewer_context/src/cache/mod.rs
  crates/viewer/re_viewer_context/src/cache/video_asset_cache.rs
  crates/viewer/re_viewer_context/src/lib.rs
Labels: 🚜 refactor, exclude from changelog, 🎞️ video

#10150 Fix typo in `descr_custom_archetype.py` snippet
  docs/snippets/all/descriptors/descr_custom_archetype.py
Labels: exclude from changelog

#10148 Build in `manylinux_2_28` container
  .github/workflows/contrib_rerun_py.yml
  .github/workflows/reusable_build_and_upload_rerun_c.yml
  .github/workflows/reusable_build_and_upload_rerun_cli.yml
  .github/workflows/reusable_build_and_upload_wheels.yml
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
  .github/workflows/reusable_deploy_docs.yml
  .github/workflows/reusable_pip_index.yml
  .github/workflows/reusable_run_notebook.yml
  .github/workflows/reusable_test_wheels.yml
  ci_docker/Dockerfile
  ci_docker/publish.sh
  pixi.toml
  scripts/ci/build_and_upload_wheels.py
  scripts/ci/sync_release_assets.py
Labels: 🐍 Python API, include in changelog, :ship: CI

#10153 Do not attempt to download blueprint dataset partition tables in redap server
  crates/viewer/re_redap_browser/src/tables_session_context.rs
Labels: 🪳 bug, exclude from changelog, dataplatform, feat-redap-browser

#10172 Fix nightly build. maybe
  .github/workflows/reusable_bundle_and_upload_rerun_cpp.yml
Labels: exclude from changelog, :ship: CI

#10161 Add snapshot test for View selection UI:s
  Cargo.lock
  crates/viewer/re_view_bar_chart/src/view_class.rs
  crates/viewer/re_viewer/Cargo.toml
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/default_views.rs
  crates/viewer/re_viewer/src/lib.rs
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/BarChart.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Dataframe.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Graph.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/TextDocument.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/TextLog.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/TimeSeries.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/BarChart.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Dataframe.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Graph.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TextDocument.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TextLog.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TimeSeries.png
  crates/viewer/re_viewer_context/src/gpu_bridge/image_to_gpu.rs
Labels: 🔨 testing, ui, exclude from changelog

#10180 Update selection UI snapshot images
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Graph.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/TimeSeries.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/2D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/3D.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Graph.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Map.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/Tensor.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TimeSeries.png
Labels: 🔨 testing, exclude from changelog, :ship: CI

#10163 Animate the maximization of a view
  Cargo.lock
  crates/viewer/re_viewport/Cargo.toml
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: ui, include in changelog

#10178 Replace our own annexb/nal/sps parsing with `h264reader` crate
  Cargo.lock
  Cargo.toml
  crates/utils/re_video/Cargo.toml
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/mod.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/sps.rs
  crates/utils/re_video/src/decode/gop_detection.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/decode/nalu.rs
Labels: 🚜 refactor, exclude from changelog

#10175 Add pixi command to build wheel with the viewer
  pixi.toml
  rerun_py/README.md
Labels: 🧑‍💻 dev experience, exclude from changelog

#10199 Fix `cargo build -p re_grpc_client` (and main CI)
  crates/store/re_grpc_client/Cargo.toml
Labels: exclude from changelog, :ship: CI

#10157 Supporting API changes for single PM Redap implementation
  Cargo.lock
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/src/codec/arrow.rs
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_protos/proto/rerun/v1alpha1/common.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
Labels: exclude from changelog, dataplatform

#10149 Group dataframe table by archetype and use new table design
  crates/store/re_sorbet/src/column_descriptor.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_chunk_store_ui/src/chunk_ui.rs
  crates/viewer/re_chunk_store_ui/src/sort.rs
  crates/viewer/re_component_ui/src/geo_line_string.rs
  crates/viewer/re_component_ui/src/line_strip.rs
  crates/viewer/re_data_ui/src/annotation_context.rs
  crates/viewer/re_data_ui/src/component.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_view_dataframe/src/dataframe_ui.rs
  crates/viewer/re_view_dataframe/tests/basic.rs
  crates/viewer/re_view_dataframe/tests/snapshots/null_timeline.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_red.png
  crates/viewer/re_view_text_log/src/view_class.rs
Labels: ui, include in changelog

#10195 Update Arrow and DataFusion dedpendencies
  Cargo.lock
  Cargo.toml
  crates/build/re_types_builder/src/reflection.rs
  crates/store/re_chunk/src/chunk.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  deny.toml
Labels: 🏹 arrow, 🔍 re_query, dependencies, include in changelog

#10160 Show help clicking the `?` as well as by just hovering it
  Cargo.lock
  crates/viewer/re_blueprint_tree/src/blueprint_tree.rs
  crates/viewer/re_chunk_store_ui/src/chunk_store_ui.rs
  crates/viewer/re_data_ui/src/item_ui.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_selection_panel/src/defaults_ui.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
  crates/viewer/re_selection_panel/src/view_entity_picker.rs
  crates/viewer/re_selection_panel/src/visualizer_ui.rs
  crates/viewer/re_time_panel/src/time_panel.rs
  crates/viewer/re_time_panel/tests/snapshots/focused_item_is_focused.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_dense_data.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_active_no_query.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_active_query.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_filter_test_inactive.png
  crates/viewer/re_time_panel/tests/snapshots/time_panel_two_sections.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_a_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_0.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_5.png
  crates/viewer/re_time_panel/tests/snapshots/various_entity_kinds_timeline_b_9223372036854775807.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_path_to,_rig.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_to_the.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-_to_the_.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-ath,left.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-ath,t.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-none.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-path.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-t.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the,oid.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-to_the_.png
  crates/viewer/re_time_panel/tests/snapshots/various_filters-void.png
  crates/viewer/re_ui/data/icons/help.svg
  crates/viewer/re_ui/examples/re_ui_example/main.rs
  crates/viewer/re_ui/examples/re_ui_example/right_panel.rs
  crates/viewer/re_ui/src/filter_widget.rs
  crates/viewer/re_ui/src/icons.rs
  crates/viewer/re_ui/src/list_item/custom_content.rs
  crates/viewer/re_ui/src/list_item/item_button.rs
  crates/viewer/re_ui/src/list_item/property_content.rs
  crates/viewer/re_ui/src/modal.rs
  crates/viewer/re_ui/src/notifications.rs
  crates/viewer/re_ui/src/section_collapsing_header.rs
  crates/viewer/re_ui/src/ui_ext.rs
  crates/viewer/re_ui/tests/help_ui_test.rs
  crates/viewer/re_ui/tests/list_item_tests.rs
  crates/viewer/re_ui/tests/modal_tests.rs
  crates/viewer/re_ui/tests/snapshots/help_Mac.png
  crates/viewer/re_ui/tests/snapshots/help_Windows.png
  crates/viewer/re_view/src/view_property_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  crates/viewer/re_viewer/src/ui/recordings_panel.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewport/src/viewport_ui.rs
Labels: 📖 documentation, ui, include in changelog

#10189 Enable `VideoStream` H264 on the web
  crates/store/re_types/definitions/rerun/components/video_codec.fbs
  crates/store/re_types/src/image.rs
  crates/utils/re_video/examples/frames.rs
  crates/utils/re_video/src/decode/async_decoder_wrapper.rs
  crates/utils/re_video/src/decode/av1.rs
  crates/utils/re_video/src/decode/ffmpeg_h264/ffmpeg.rs
  crates/utils/re_video/src/decode/gop_detection.rs
  crates/utils/re_video/src/decode/mod.rs
  crates/utils/re_video/src/decode/webcodecs.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/utils/re_video/src/demux/mp4.rs
  crates/utils/re_video/src/h264.rs
  crates/utils/re_video/src/lib.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_global_context/src/app_options.rs
  crates/viewer/re_renderer/src/resource_managers/yuv_converter.rs
  crates/viewer/re_renderer/src/video/chunk_decoder.rs
  crates/viewer/re_renderer/src/video/mod.rs
  crates/viewer/re_renderer/src/video/player.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_viewer/src/startup_options.rs
  crates/viewer/re_viewer/src/ui/settings_screen.rs
  crates/viewer/re_viewer_context/src/cache/video_asset_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  tests/python/video_ffmpeg/main.py
Labels: 🕸️ web, 📺 re_viewer, include in changelog, 🎞️ video

#10214 Add `libgfortran5` dependency to fix MacOS OpenCV & numpy issues
  pixi.lock
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog, :apple: MacOS

#10173 Add detailed view of latency
  Cargo.lock
  crates/store/re_chunk/src/transport.rs
  crates/store/re_entity_db/Cargo.toml
  crates/store/re_entity_db/src/entity_db.rs
  crates/store/re_entity_db/src/ingestion_statistics.rs
  crates/store/re_entity_db/src/lib.rs
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/src/codec/arrow.rs
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/decoder/mod.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/protobuf_conversions.rs
  crates/store/re_sorbet/Cargo.toml
  crates/store/re_sorbet/src/chunk_schema.rs
  crates/store/re_sorbet/src/lib.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
  crates/store/re_sorbet/src/timestamp_metadata.rs
  crates/utils/re_arrow_util/src/batches.rs
  crates/viewer/re_global_context/src/app_options.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
  tests/cpp/log_benchmark/image.cpp
  tests/python/log_benchmark/test_log_benchmark.py
  tests/rust/log_benchmark/src/image.rs
  tests/rust/log_benchmark/src/main.rs
Labels: 🧑‍💻 dev experience, 📉 performance, include in changelog

#10205 Add unit tests for `VideoStreamCache` + important fixes
  .gitattributes
  crates/store/re_types/src/archetypes/asset_video_ext.rs
  crates/top/rerun_c/src/video.rs
  crates/utils/re_video/benches/video_load_bench.rs
  crates/utils/re_video/examples/frames.rs
  crates/utils/re_video/src/demux/mod.rs
  crates/utils/re_video/src/demux/mp4.rs
  crates/utils/re_video/src/stable_index_deque.rs
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_viewer_context/src/cache/video_asset_cache.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  pixi.toml
  rerun_py/src/video.rs
  tests/assets/video/gif_as_h264_nobframes.h264
Labels: exclude from changelog, 🎞️ video

#10219 Revert removal of `DecodeError::Chunk`
  crates/store/re_log_encoding/src/decoder/mod.rs
Labels: exclude from changelog

#10220 Implement `FromIterator<SerializedComponentChunk>` for `ChunkComponents`
  crates/store/re_chunk/src/chunk.rs
  crates/store/re_data_loader/src/loader_lerobot.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#10223 Always enable `small_rng`, it's free
  Cargo.toml
Labels: 🔨 testing, exclude from changelog, :ship: CI

#10221 Major overhaul of `CatalogClient` API
  Cargo.lock
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/catalog.py
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/catalog/mod.rs
  rerun_py/src/catalog/table_entry.rs
Labels: 🐍 Python API, exclude from changelog, dataplatform

#10225 Provide descriptor-aware `AnyValues` example in snippets
  docs/snippets/all/tutorials/any_values.cpp
  docs/snippets/all/tutorials/any_values.py
  rerun_py/rerun_sdk/rerun/any_value.py
  tests/assets/rrd/snippets/tutorials/any_values.rrd
Labels: 📖 documentation, include in changelog

#10201 Fix initializing two recordings with the same recording id causing SDK hangs
  rerun_py/src/dataframe.rs
  rerun_py/src/python_bridge.rs
  rerun_py/src/utils.rs
  rerun_py/tests/unit/test_dataframe.py
  rerun_py/tests/unit/test_expected_warnings.py
Labels: 🪳 bug, 🐍 Python API, include in changelog

#10231 Support loading ROS paths in URDF loader
  crates/store/re_data_loader/src/loader_urdf.rs
Labels: 📺 re_viewer, include in changelog

#10230 Remove usage of `unwrap()` in `re_sdk`
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/recording_stream.rs
  crates/top/re_sdk/src/spawn.rs
Labels: 🧑‍💻 dev experience, exclude from changelog

#10233 Move the default plot legend to bottom left instead of right
  crates/store/re_types/definitions/rerun/blueprint/components/corner_2d.fbs
  crates/store/re_types/src/blueprint/components/corner2d.rs
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/Corner2D_placeholder.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/Corner2D_placeholder.png
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_show_second_only.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_true.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Dark/TimeSeries.png
  crates/viewer/re_viewer/tests/snapshots/all_view_selecion_uis/Light/TimeSeries.png
Labels: 📺 re_viewer, include in changelog, 📈 plot

#10206 Add missing word in entity path docs page
  docs/content/concepts/entity-path.md
Labels: 📖 documentation, exclude from changelog, deploy docs

#10215 Use new column name in `blueprint::datatypes::ComponentColumnSelector`
  Cargo.lock
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/store/re_sorbet/src/selectors.rs
  crates/store/re_types/Cargo.toml
  crates/store/re_types/definitions/rerun/blueprint/datatypes/component_column_selector.fbs
  crates/store/re_types/src/blueprint/components/component_column_selector_ext.rs
  crates/store/re_types/src/blueprint/components/filter_is_not_null_ext.rs
  crates/store/re_types/src/blueprint/datatypes/component_column_selector.rs
  crates/store/re_types/src/blueprint/datatypes/component_column_selector_ext.rs
  crates/store/re_types_core/src/reflection.rs
  crates/viewer/re_component_ui/tests/test_all_components_ui.rs
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
  crates/viewer/re_view_dataframe/src/view_query/ui.rs
  docs/content/reference/migration/migration-0-24.md
  rerun_cpp/src/rerun/blueprint/datatypes/component_column_selector.hpp
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/component_column_selector.py
Labels: 🟦 blueprint, include in changelog, 🔩 data model

#10238 Add `FillMode` to `Capsules3D`
  crates/store/re_types/definitions/rerun/archetypes/capsules3d.fbs
  crates/store/re_types/src/archetypes/capsules3d.rs
  crates/store/re_types/src/reflection/mod.rs
  crates/viewer/re_view_spatial/src/proc_mesh.rs
  crates/viewer/re_view_spatial/src/visualizers/capsules3d.rs
  docs/content/reference/types/archetypes/capsules3d.md
  docs/content/reference/types/components/fill_mode.md
  rerun_cpp/src/rerun/archetypes/capsules3d.cpp
  rerun_cpp/src/rerun/archetypes/capsules3d.hpp
  rerun_py/rerun_sdk/rerun/archetypes/capsules3d.py
Labels: 📺 re_viewer, include in changelog

#10248 Fix SDK's Redap TLS
  Cargo.lock
  Cargo.toml
  rerun_py/Cargo.toml
  rerun_py/src/catalog/catalog_client.rs
Labels: 💣 crash, exclude from changelog, dataplatform

#10240 Update docs deploy workflow
  .github/workflows/reusable_deploy_docs.yml
  docs/content/getting-started/data-in/rust.md
  pixi.lock
  pixi.toml
  rerun_cpp/docs/writing_docs.md
  rerun_py/docs/writing_docs.md
Labels: 📖 documentation, exclude from changelog

#10249 Link to `Asset3D` in raw_mesh example
  examples/python/raw_mesh/README.md
  examples/python/raw_mesh/raw_mesh/__main__.py
  examples/rust/raw_mesh/README.md
  examples/rust/raw_mesh/src/main.rs
Labels: 📖 documentation, examples, exclude from changelog

#10254 Remove perf regression alerts
  .github/workflows/reusable_bench.yml
  .github/workflows/reusable_track_size.yml
Labels: exclude from changelog, :ship: CI

#10234 Make plot axis thinner
  Cargo.lock
  crates/viewer/re_view_time_series/src/view_class.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_show_second_only.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_true.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: 📺 re_viewer, include in changelog, 📈 plot

#10239 Add "deep inspection" selection ui for the new `VideoStream` archetype
  crates/viewer/re_data_ui/src/blob.rs
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_data_ui/src/video.rs
  crates/viewer/re_view_spatial/src/visualizers/video/video_stream.rs
  crates/viewer/re_viewer_context/src/cache/mod.rs
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  crates/viewer/re_viewer_context/src/lib.rs
  crates/viewer/re_viewer_context/src/utils/mod.rs
  crates/viewer/re_viewer_context/src/utils/video.rs
Labels: ui, include in changelog, 🎞️ video

#10111 Improve `rerun_notebook` startup times
  lychee.toml
  pixi.lock
  rerun_js/web-viewer/bundle.mjs
  rerun_js/web-viewer/index.ts
  rerun_js/web-viewer/package.json
  rerun_notebook/README.md
  rerun_notebook/build.mjs
  rerun_notebook/package-lock.json
  rerun_notebook/package.json
  rerun_notebook/pyproject.toml
  rerun_notebook/src/js/widget.ts
  rerun_notebook/src/rerun_notebook/__init__.py
  rerun_notebook/src/rerun_notebook/asset_server.py
  rerun_notebook/src/rerun_notebook/error_widget.js
  rerun_py/rerun_sdk/rerun/notebook.py
  scripts/ci/publish_wheels.py
Labels: 🕸️ web, 🐍 Python API, 📉 performance, notebook, include in changelog

#10258 minor: add __repr__ to two classes
  rerun_py/rerun_sdk/rerun/catalog.py
  rerun_py/src/catalog/catalog_client.rs
  rerun_py/src/catalog/entry.rs
Labels: notebook, exclude from changelog, feat-dataframe-api

#10269 Switch lint-rs-files to use edition 2024
  pixi.toml
Labels: 🧑‍💻 dev experience, exclude from changelog

#10268 Max image dimension subscriber (used for heuristics) now fully supports `VideoStream`
  crates/viewer/re_view_spatial/src/max_image_dimension_subscriber.rs
  crates/viewer/re_view_spatial/src/view_2d.rs
Labels: exclude from changelog, 🎞️ video

#10228 Re-enable latency measurements
  Cargo.lock
  crates/store/re_entity_db/src/ingestion_statistics.rs
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_log_encoding/Cargo.toml
  crates/store/re_log_encoding/src/codec/arrow.rs
  crates/store/re_log_encoding/src/protobuf_conversions.rs
  crates/store/re_log_types/src/arrow_msg.rs
  crates/store/re_log_types/src/lib.rs
  crates/store/re_sorbet/src/timestamp_metadata.rs
  crates/top/re_sdk/Cargo.toml
  crates/top/re_sdk/src/recording_stream.rs
  crates/viewer/re_view_spatial/tests/transform_clamping.rs
  tests/rust/log_benchmark/src/image.rs
  tests/rust/log_benchmark/src/main.rs
  tests/rust/log_benchmark/src/points3d_large_batch.rs
  tests/rust/log_benchmark/src/points3d_many_individual.rs
Labels: 🧑‍💻 dev experience, 📉 performance, exclude from changelog

#10259 Update `egui_plot` and `egui`
  Cargo.lock
  crates/viewer/re_time_panel/src/data_density_graph.rs
  crates/viewer/re_view_time_series/tests/basic.rs
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_show_second_only.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_true.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
Labels: dependencies, exclude from changelog, egui, 📈 plot

#10278 Build wheel index on main
  .github/workflows/on_push_main.yml
Labels: exclude from changelog, :ship: CI

#10281 Don't check wheels for push-to-main pip-index
  .github/workflows/on_push_main.yml
  .github/workflows/reusable_pip_index.yml
Labels: exclude from changelog, :ship: CI

#10277 Fix: let users pick file name when saving a single recording
  crates/viewer/re_viewer/src/app.rs
Labels: 📺 re_viewer, exclude from changelog, Bug

#10285 Improve test case discovery in `bacon`
  bacon.toml
Labels: exclude from changelog

#10253 Improve catalog table ux
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_ui/src/design_tokens.rs
Labels: enhancement, ui, exclude from changelog

#10279 Add Python example snippet for `VideoStream` using `av` to encode numpy images
  crates/build/re_types_builder/src/docs.rs
  crates/store/re_types/definitions/rerun/archetypes/video_stream.fbs
  crates/store/re_types/definitions/rerun/blueprint/datatypes/component_column_selector.fbs
  crates/store/re_types/src/archetypes/video_stream.rs
  crates/store/re_types/src/blueprint/datatypes/component_column_selector.rs
  crates/store/re_types/src/reflection/mod.rs
  docs/content/reference/types/archetypes/video_stream.md
  docs/snippets/INDEX.md
  docs/snippets/all/archetypes/video_stream_synthetic.py
  docs/snippets/snippets.toml
  pixi.lock
  pixi.toml
  rerun_cpp/src/rerun/archetypes/video_stream.hpp
  rerun_cpp/src/rerun/blueprint/datatypes/component_column_selector.hpp
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/archetypes/video_stream.py
  rerun_py/rerun_sdk/rerun/blueprint/datatypes/component_column_selector.py
Labels: examples, include in changelog

#10284 Add duration field to the recording UI
  Cargo.lock
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/entity_db.rs
Labels: ui, include in changelog

#10290 Add catalog entry table
  Cargo.lock
  crates/store/re_protos/src/v1alpha1/rerun.catalog.v1alpha1.ext.rs
  crates/viewer/re_component_ui/Cargo.toml
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/variant_uis/mod.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_entry_kind.rs
  crates/viewer/re_dataframe_ui/src/datafusion_adapter.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
  crates/viewer/re_redap_browser/src/add_server_modal.rs
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_redap_browser/src/tables_session_context.rs
  crates/viewer/re_ui/src/ui_layout.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: enhancement, ui, include in changelog, dataplatform

#10270 Update egui (new egui_kittest node)
  Cargo.lock
  crates/viewer/re_blueprint_tree/tests/range_selection_test.rs
Labels: enhancement, 🔨 testing, exclude from changelog

#10158 Multi-sink / `tee` Python API
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/re_sdk/src/recording_stream.rs
  docs/snippets/INDEX.md
  docs/snippets/all/howto/tee.py
  docs/snippets/snippets.toml
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: enhancement, 🐍 Python API, include in changelog

#10293 IO-bound Redap
  Cargo.lock
  crates/build/re_protos_builder/src/lib.rs
  crates/store/re_chunk/Cargo.toml
  crates/store/re_chunk/src/transport.rs
  crates/store/re_datafusion/Cargo.toml
  crates/store/re_datafusion/src/datafusion_connector.rs
  crates/store/re_datafusion/src/partition_table.rs
  crates/store/re_datafusion/src/search_provider.rs
  crates/store/re_datafusion/src/table_entry_provider.rs
  crates/store/re_grpc_client/Cargo.toml
  crates/store/re_grpc_client/src/lib.rs
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_log_encoding/src/codec/arrow.rs
  crates/store/re_log_encoding/src/codec/file/decoder.rs
  crates/store/re_log_encoding/src/codec/file/encoder.rs
  crates/store/re_log_encoding/src/codec/file/mod.rs
  crates/store/re_log_encoding/src/codec/wire/encoder.rs
  crates/store/re_log_encoding/src/codec/wire/mod.rs
  crates/store/re_log_encoding/src/decoder/stream.rs
  crates/store/re_log_encoding/src/decoder/streaming.rs
  crates/store/re_log_encoding/src/protobuf_conversions.rs
  crates/store/re_protos/proto/rerun/v1alpha1/log_msg.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/lib.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.common.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.log_msg.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  crates/store/re_sorbet/Cargo.toml
  crates/store/re_sorbet/src/chunk_batch.rs
  crates/store/re_sorbet/src/migration.rs
  crates/store/re_sorbet/src/sorbet_batch.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
  rerun_py/Cargo.toml
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/catalog/table_entry.rs
  rerun_py/src/lib.rs
  rerun_py/src/utils.rs
  scripts/clippy_wasm/clippy.toml
Labels: 📉 performance, exclude from changelog, dataplatform

#10320 Always enable 'attributes' on tracing
  Cargo.toml
Labels: 😤 annoying, dependencies, exclude from changelog, :ship: CI

#10302 Add a benchmark for logging/rendering many boxes
  Cargo.lock
  crates/store/re_sorbet/src/migration.rs
  crates/viewer/re_renderer/Cargo.toml
  crates/viewer/re_renderer_examples/Cargo.toml
  crates/viewer/re_view_spatial/src/proc_mesh.rs
  crates/viewer/re_view_spatial/src/visualizers/boxes3d.rs
  crates/viewer/re_view_spatial/src/visualizers/utilities/proc_mesh_vis.rs
  crates/viewer/re_viewer_context/Cargo.toml
  tests/rust/log_benchmark/Cargo.toml
  tests/rust/log_benchmark/README.md
  tests/rust/log_benchmark/src/boxes3d_batch.rs
  tests/rust/log_benchmark/src/main.rs
Labels: 🔨 testing, 📉 performance, 🚜 refactor, exclude from changelog

#10326 Fix `more.svg` (`…`)
  crates/viewer/re_ui/data/icons/more.svg
Labels: ui, exclude from changelog

#10334 Fix `SIGBUS` startup crash on some Mac systems
  Cargo.lock
Labels: 🪳 bug, 📺 re_viewer, 💣 crash, include in changelog

#10312 Rename to `tee` to `attach_sinks`
  docs/snippets/INDEX.md
  docs/snippets/all/howto/set_sinks.py
  docs/snippets/snippets.toml
  rerun_py/docs/gen_common_index.py
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/rerun_sdk/rerun/__init__.py
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/src/python_bridge.rs
Labels: 🐍 Python API, include in changelog

#10336 Add `set_sinks` to Rust `RecordingStream`
  crates/top/re_sdk/src/lib.rs
  crates/top/re_sdk/src/log_sink.rs
  crates/top/re_sdk/src/recording_stream.rs
  docs/snippets/INDEX.md
  docs/snippets/all/howto/set_sinks.rs
Labels: 🦀 Rust API, include in changelog

#10341 Allow pasting in a full URL in the "Add redap" modal
  crates/viewer/re_redap_browser/src/add_server_modal.rs
Labels: 📺 re_viewer, exclude from changelog

#10332 Add support for `index=None` to local and remote dataframe APIs and deprecate `select_static`
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_chunk_store/src/lib.rs
  crates/store/re_chunk_store/tests/dataframe.rs
  crates/viewer/re_view_dataframe/src/view_class.rs
  docs/content/reference/migration/migration-0-24.md
  rerun_py/rerun_bindings/rerun_bindings.pyi
  rerun_py/src/catalog/dataframe_query.rs
  rerun_py/src/catalog/dataset_entry.rs
  rerun_py/src/dataframe.rs
  rerun_py/tests/unit/test_dataframe.py
Labels: 🐍 Python API, include in changelog, feat-dataframe-api, dataplatform

#10355 Fix exclusion of recording properties in `ResolvedEntityPathFilter::unresolved`
  crates/store/re_log_types/src/path/entity_path_filter.rs
Labels: exclude from changelog

#10300 Allow editing connection settings for an existing redap server
  crates/store/re_grpc_client/src/connection_registry.rs
  crates/viewer/re_redap_browser/src/lib.rs
  crates/viewer/re_redap_browser/src/server_modal.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_ui/data/icons/trash.svg
  crates/viewer/re_ui/src/icons.rs
Labels: enhancement, ui, include in changelog

#10357 Improved menu styling
  Cargo.lock
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_catalog_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_narrow/custom_url_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_catalog_string_any_value_url_string.png
  crates/viewer/re_component_ui/tests/snapshots/all_components_list_item_wide/custom_url_string_any_value_url_string.png
  crates/viewer/re_context_menu/src/lib.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_ui/data/dark_theme.ron
  crates/viewer/re_ui/data/light_theme.ron
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/src/lib.rs
  crates/viewer/re_ui/src/list_item/item_button.rs
  crates/viewer/re_ui/src/menu.rs
  crates/viewer/re_ui/tests/snapshots/arrow_ui.png
  crates/viewer/re_ui/tests/snapshots/help_Mac.png
  crates/viewer/re_ui/tests/snapshots/help_Windows.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_background.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_rect_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_rect_red.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_green.png
  crates/viewer/re_view_spatial/tests/snapshots/annotations_hover_region_red.png
  crates/viewer/re_view_time_series/tests/snapshots/clear_series_points_and_line_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/line_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/per_series_visibility_splat_false.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_multiple_properties_two_series_per_entity.png
  crates/viewer/re_view_time_series/tests/snapshots/point_properties_two_series_per_entity.png
  crates/viewer/re_viewer/src/ui/rerun_menu.rs
Labels: ui, include in changelog

#10363 Fix timeline combo box in dataframe view
  crates/viewer/re_view_dataframe/src/view_query/blueprint.rs
Labels: exclude from changelog

#10364 Remove unneeded edit ui warning
  crates/viewer/re_viewer_context/src/component_ui_registry.rs
Labels: exclude from changelog

#10360 Deprecate `serve_web` and improve documentation around how to serve a web viewer
  crates/top/re_sdk/src/recording_stream.rs
  docs/content/reference/migration/migration-0-24.md
  docs/content/reference/sdk/operating-modes.md
  docs/snippets/Cargo.toml
  docs/snippets/INDEX.md
  docs/snippets/all/howto/serve_web_viewer.py
  docs/snippets/all/howto/serve_web_viewer.rs
  docs/snippets/snippets.toml
  rerun_py/docs/gen_common_index.py
  rerun_py/docs/writing_docs.md
  rerun_py/rerun_sdk/rerun/recording_stream.py
  rerun_py/rerun_sdk/rerun/sinks.py
  rerun_py/rerun_sdk/rerun/web.py
Labels: 📖 documentation, 🐍 Python API, 🦀 Rust API, include in changelog

#10371 Fix C++ crash due to FFI struct mismatch
  crates/top/rerun_c/src/lib.rs
Labels: 🦟 regression, 🌊 C++ API, exclude from changelog

#10362 Improved table loading ui
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
Labels: ui, exclude from changelog

#10374 Do not use title casing
  crates/viewer/re_data_ui/src/instance_path.rs
  crates/viewer/re_time_panel/src/time_panel.rs
Labels: exclude from changelog

#10367 Fix switch to link showing when recording isn't loaded yet
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
Labels: 🪳 bug, exclude from changelog

#10368 Disambiguate component entries in selection panel
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: ui, include in changelog

#10345 Add support for querying static chunks only
  crates/store/re_chunk_store/src/dataframe.rs
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: 🐍 Python API, exclude from changelog, feat-dataframe-api

#10383 Fix migrations of blueprint indicator components
  crates/store/re_sorbet/src/migrations/v0_24.rs
Labels: 🪳 bug, exclude from changelog

#10376 Small `Alert` improvements
  crates/viewer/re_ui/src/alert.rs
  crates/viewer/re_ui/src/design_tokens.rs
  crates/viewer/re_ui/tests/snapshots/alert.png
Labels: ui, exclude from changelog

#10384 Remove usage of unwrap in `re_view_tensor`
  crates/viewer/re_view_tensor/src/lib.rs
  crates/viewer/re_view_tensor/src/view_class.rs
Labels: 🚜 refactor, exclude from changelog

#10382 Fix `--serve-web <file>`
  crates/top/rerun/src/commands/entrypoint.rs
Labels: 🪳 bug, exclude from changelog, CLI

#10387 Display the partition ID in recording selection panel
  Cargo.lock
  crates/viewer/re_data_ui/Cargo.toml
  crates/viewer/re_data_ui/src/entity_db.rs
Labels: ui, include in changelog, dataplatform

#10309 Fix white barchart in lightmode
  crates/viewer/re_view_bar_chart/src/view_class.rs
Labels: ui, 😤 annoying, exclude from changelog

#10379 Silence harmeless "Unrecognized present mode" warning
  crates/utils/re_log/src/lib.rs
Labels: 🪳 bug, 📺 re_viewer, include in changelog

#10388 Edit redap token via `Command`
  crates/viewer/re_redap_browser/src/server_modal.rs
  crates/viewer/re_redap_browser/src/servers.rs
  crates/viewer/re_viewer/src/app_state.rs
Labels: 🪳 bug, exclude from changelog

#10389 Improve table column names
  crates/store/re_log_types/src/path/entity_path.rs
  crates/store/re_sorbet/src/component_column_descriptor.rs
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/table_blueprint.rs
Labels: 📺 re_viewer, exclude from changelog

#10399 Update to arrow 55.2
  Cargo.lock
  Cargo.toml
  crates/store/re_grpc_client/src/message_proxy/read.rs
  crates/store/re_grpc_client/src/message_proxy/write.rs
  crates/store/re_log_types/src/arrow_msg.rs
  crates/store/re_log_types/src/lib.rs
  crates/utils/re_arrow_util/src/batches.rs
  crates/viewer/re_viewer/src/web.rs
Labels: 🏹 arrow, 📉 performance, dependencies, exclude from changelog

#10297 Standalone example for compressed video streams
  crates/viewer/re_viewer_context/src/cache/video_stream_cache.rs
  docs/snippets/all/archetypes/video_stream_synthetic.py
  examples/manifest.toml
  examples/python/camera_video_stream/README.md
  examples/python/camera_video_stream/camera_video_stream.py
  examples/python/camera_video_stream/pyproject.toml
  pixi.lock
  pixi.toml
  rerun_py/pyproject.toml
  rerun_py/rerun_sdk/rerun/archetypes/video_stream.py
  scripts/lint.py
  tests/python/video_ffmpeg/main.py
  tests/python/video_mcap/.gitattributes
  tests/python/video_mcap/CompressedVideo.proto
  tests/python/video_mcap/CompressedVideo_pb2.py
  tests/python/video_mcap/generate_proto.py
  tests/python/video_mcap/main.py
Labels: examples, include in changelog, 🎞️ video

#10401 Fix copy and cut from notebook cells
  Cargo.lock
Labels: dependencies, include in changelog, egui

#10392 Replace `rerun:version` with `sorbet:version` to help with future migrations
  Cargo.lock
  Cargo.toml
  crates/store/re_chunk_store/Cargo.toml
  crates/store/re_chunk_store/tests/formatting.rs
  crates/store/re_chunk_store/tests/snapshots/formatting__format_chunk_store.snap
  crates/store/re_format_arrow/src/lib.rs
  crates/store/re_sorbet/Cargo.toml
  crates/store/re_sorbet/src/migrations/make_list_arrays.rs
  crates/store/re_sorbet/src/migrations/mod.rs
  crates/store/re_sorbet/src/migrations/v0_0_1__to__v0_0_2.rs
  crates/store/re_sorbet/src/migrations/v0_0_2__to__v0_1_0.rs
  crates/store/re_sorbet/src/sorbet_schema.rs
Labels: exclude from changelog, 🔩 data model

#10408 Fetch static data first when loading Redap recording
  crates/store/re_grpc_client/src/redap/mod.rs
  crates/store/re_protos/proto/rerun/v1alpha1/frontend.proto
  crates/store/re_protos/proto/rerun/v1alpha1/manifest_registry.proto
  crates/store/re_protos/src/v1alpha1/rerun.frontend.v1alpha1.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.ext.rs
  crates/store/re_protos/src/v1alpha1/rerun.manifest_registry.v1alpha1.rs
  rerun_py/src/catalog/connection_handle.rs
  rerun_py/src/catalog/dataset_entry.rs
Labels: exclude from changelog, dataplatform

#10413 Trigger C++ ci on rerun_c changes, trigger Rust ci on `re_ui` data changes
  .github/workflows/on_pull_request.yml
Labels: 🧑‍💻 dev experience, exclude from changelog, :ship: CI

#10424 Fetch dataset entries in parallel
  Cargo.lock
  crates/viewer/re_redap_browser/Cargo.toml
  crates/viewer/re_redap_browser/src/entries.rs
  crates/viewer/re_redap_browser/src/tables_session_context.rs
Labels: exclude from changelog

#10414 Reduce recording properties logging output in Rust SDK
  crates/top/re_sdk/src/recording_stream.rs
Labels: exclude from changelog

#10416 Unify component information in selection panel and header popups
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_selection_panel/src/selection_panel.rs
Labels: ui, exclude from changelog, 🔩 data model, feat-redap-browser

#10434 Show a blinking orange dot in debug builds on multi-pass egui frame
  Cargo.lock
  crates/viewer/re_viewer/src/ui/top_panel.rs
Labels: 🧑‍💻 dev experience, 📺 re_viewer, exclude from changelog

#10402 Fix broken latency measurement
  Cargo.lock
  crates/store/re_grpc_server/Cargo.toml
  crates/store/re_grpc_server/src/lib.rs
  crates/store/re_sorbet/src/timestamp_metadata.rs
  crates/viewer/re_viewer/src/app.rs
  crates/viewer/re_viewer/src/ui/top_panel.rs
Labels: 🪳 bug, 📺 re_viewer, exclude from changelog

#10412 Better thumbnail display in table
  Cargo.lock
  crates/viewer/re_component_ui/src/lib.rs
  crates/viewer/re_component_ui/src/variant_uis/mod.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_thumbnail.rs
  crates/viewer/re_component_ui/src/variant_uis/redap_uri_button.rs
  crates/viewer/re_data_ui/src/image.rs
  crates/viewer/re_data_ui/src/lib.rs
  crates/viewer/re_dataframe_ui/Cargo.toml
  crates/viewer/re_dataframe_ui/src/datafusion_table_widget.rs
  crates/viewer/re_dataframe_ui/src/display_record_batch.rs
  crates/viewer/re_dataframe_ui/src/table_utils.rs
Labels: ui, exclude from changelog

#10443 Fix time panel archetype name overflowing
  crates/viewer/re_time_panel/src/time_panel.rs
Labels: 🦟 regression, exclude from changelog

#10410 Publish JS docs
  .github/workflows/on_push_main.yml
  .github/workflows/release.yml
  .github/workflows/reusable_deploy_docs.yml
  docs/content/reference/npm.md
  pixi.toml
  rerun_js/.gitignore
  rerun_js/package.json
  rerun_js/scripts/docs.mjs
  rerun_js/scripts/serve-docs.mjs
  rerun_js/scripts/version.mjs
  rerun_js/web-viewer-react/.gitignore
  rerun_js/web-viewer-react/README.md
  rerun_js/web-viewer-react/package.json
  rerun_js/web-viewer-react/typedoc.json
  rerun_js/web-viewer/.gitignore
  rerun_js/web-viewer/README.md
  rerun_js/web-viewer/index.ts
  rerun_js/web-viewer/package.json
  rerun_js/web-viewer/typedoc.json
  rerun_js/yarn.lock
Labels: 📖 documentation, include in changelog

#10435 Section on component descriptors in `v0.24` migration guide
  docs/content/reference/migration/migration-0-24.md
Labels: exclude from changelog

#10442 Generate one partition stream per partition ID in query provider
  crates/store/re_datafusion/src/dataframe_query_provider.rs
  rerun_py/src/catalog/dataframe_query.rs
Labels: 📉 performance, exclude from changelog, dataplatform
